import type { WeekContent } from '../types';

const week40: WeekContent = {
  title: "Types in Anticipation — Old Testament Shadows Pointing to Christ",
  subtitle: "Before Christ came in the flesh, He came in symbols — woven into the lives, rituals, and events of His ancient covenant people.",
  weekScriptures: "Gen 28:12; Ex 17:5-6; Ruth 4:14; 1 Sam 16:11-13; 2 Sam 7:12-16; Jonah 1:17; 1 Cor 10:1-4; Gal 3:24; Heb 8:5; Heb 10:1; Jarom 1:11; Mosiah 16:14-15; Ex 25:8-9; Ether 12:19",
  synthesis: {
    summary: "Typology is the practice of reading Old Testament events, persons, and rituals as divinely intended prefigurations of Jesus Christ. The sacrifice of Isaac, the Passover lamb, the manna, the brazen serpent, and the Day of Atonement all point forward to Christ's life, death, and saving power. These were not accidents or later reinterpretations — Nephite prophets explicitly taught that their entire religious system was designed to keep their minds fixed on the coming Messiah.",
    connections: [
      "This week pairs directly with Week 41 (Types in Memory), which examines symbols that point backward to Christ after His coming.",
      "The Passover lamb type connects to Week 18 (Trial and Crucifixion), where Christ becomes the literal fulfillment of the sacrifice.",
      "The Day of Atonement type is the ritual foundation for the Atonement doctrine explored in Weeks 20–21."
    ],
    teaching: "Why would God teach about Christ through symbols and events rather than simply stating doctrine in plain words? What is gained by typological teaching?",
    commitment: "Choose one Old Testament type from this week and study its fulfillment in Christ. As you encounter symbols in the temple, sacrament, or daily worship, ask: what is this pointing me toward?"
  },
  days: [
    {
      label: "The binding of Isaac",
      focus: "Abraham's near-sacrifice of Isaac is the most powerful type of the Father offering His Son. Today explores this profound parallel.",
      scriptures: [{book:"Gen",ch:22,vs:1,ve:14},{book:"Jacob",ch:4,vs:5},{book:"John",ch:3,vs:16},{book:"Heb",ch:11,vs:17,ve:19}],
      nuances: "In Genesis 22:2, God tells Abraham to offer Isaac on 'one of the mountains' in 'the land of Moriah.' Second Chronicles 3:1 identifies Mount Moriah as the site where Solomon later built the temple — and Jewish tradition holds that this is the same ridge where Golgotha stood. Abraham may have offered Isaac on the very hill where God would offer His Son.",
      commentary: "The binding of Isaac (known in Hebrew as the Akedah) is one of the most theologically rich narratives in all of scripture. God commands Abraham to offer his beloved son — the son of promise, the son through whom all covenant blessings were to flow. Abraham obeys without recorded protest, rising early the next morning.\n\nThe parallels to Calvary are staggering. Isaac carries the wood for his own sacrifice (Genesis 22:6), as Christ carried His cross. Isaac asks 'Where is the lamb?' and Abraham answers prophetically: 'God will provide himself a lamb for a burnt offering' (Genesis 22:7–8). Isaac submits willingly to being bound — Jewish tradition emphasizes that Isaac, likely a young man, could have resisted his elderly father. Father and son both participate willingly.\n\nJacob 4:5 states directly that Abraham's experience was 'a similitude of God and his Only Begotten Son.' This is not a later Christian reinterpretation imposed on the text — it is a Nephite prophet declaring that God designed the Akedah as a type of the Atonement.\n\nHebrews 11:17–19 adds that Abraham received Isaac back 'in a figure' — the Greek 'en parabole' — meaning the entire episode functioned as a parable of resurrection. Abraham believed God could raise the dead, and in a sense, he received Isaac back from death. The ram caught in the thicket (Genesis 22:13) became the substitute — just as Christ became the substitute for all of us.\n\nThe one difference between the type and the fulfillment is devastating in its implications: for Isaac, God provided a substitute. For His own Son, He did not.",
      patterns: "The Akedah establishes the typological pattern for the entire week: a real historical event that simultaneously prefigures Christ. This dual-layered reading of scripture — historical and Christological — is the method Jesus Himself used on the road to Emmaus (Week 39, Day 7).",
      reflection: "Abraham was asked to give up what he loved most. What might God be asking you to place on the altar — not because He wants to take it, but because He wants to see if you trust Him?"
    },
    {
      label: "The Passover Lamb",
      focus: "The Passover is the foundational type of Israel's deliverance. Christ is the Lamb whose blood saves from death.",
      scriptures: [{book:"Ex",ch:12,vs:3,ve:13},{book:"1 Cor",ch:5,vs:7},{book:"John",ch:1,vs:29},{book:"Isa",ch:53,vs:7}],
      nuances: "Exodus 12:46 specifies that no bone of the Passover lamb shall be broken. John 19:33–36 records that the soldiers broke the legs of the two thieves but not Christ's — 'that the scripture should be fulfilled, A bone of him shall not be broken.' The type was precise down to the physical details of the sacrifice.",
      commentary: "The Passover is the most important ritual in the Old Testament — the event that defined Israel as a nation and established their relationship with God. On the night before the exodus, each family sacrificed a lamb without blemish, applied its blood to the doorposts, and ate the flesh in haste. When the destroying angel passed through Egypt, every household marked by the blood was spared.\n\nPaul's statement in 1 Corinthians 5:7 is direct: 'Christ our passover is sacrificed for us.' He is not making an analogy — he is declaring an identity. The Passover lamb was always pointing to this Lamb. John the Baptist recognized this when he declared, 'Behold the Lamb of God, which taketh away the sin of the world' (John 1:29).\n\nThe details of the Passover type are precise. The lamb was to be without blemish (Christ was sinless). It was selected on the tenth of Nisan and kept until the fourteenth (Christ entered Jerusalem on Palm Sunday and was crucified on Friday of the same week). Its blood was applied to the doorframe — two sides and the top — forming the shape of a cross, according to some traditions. The lamb was roasted whole, not raw or boiled, corresponding to the totality of Christ's suffering.\n\nIsaiah 53:7 completes the image: 'He is brought as a lamb to the slaughter, and as a sheep before her shearers is dumb, so he openeth not his mouth.' The Passover lamb was silent. Christ was silent before Pilate. The type and the fulfillment converge in silence.",
      patterns: "The Passover is the type that most directly connects to the sacrament (Week 41). Israel was commanded to repeat the Passover annually to remember their deliverance; Christians partake of the sacrament weekly to remember theirs. The pattern of remembrance through ritual meal spans both testaments.",
      reflection: "The Passover required the Israelites to personally apply the blood of the lamb to their doorposts. How do you personally apply the blood of Christ — His Atonement — in your own life?"
    },
    {
      label: "Manna from heaven",
      focus: "God fed Israel with bread from heaven for forty years. Jesus declared Himself the true Bread of Life. Today traces the connection.",
      scriptures: [{book:"Ex",ch:16,vs:14,ve:15},{book:"John",ch:6,vs:31,ve:35},{book:"1 Ne",ch:17,vs:28,ve:29},{book:"Deut",ch:8,vs:3}],
      nuances: "The Hebrew word 'manna' comes from 'man hu' — 'What is it?' The Israelites literally named their sustenance with a question. This naming carries theological significance: the bread from heaven was mysterious, unexpected, and unlike anything they had known before — just as Christ Himself would be.",
      commentary: "For forty years in the wilderness, God provided manna — a fine, white substance that appeared each morning with the dew. It sustained an entire nation in a barren desert. It could not be hoarded (it spoiled overnight except before the Sabbath). It had to be gathered daily. It came from above.\n\nJesus explicitly identified Himself as the fulfillment of this type in John 6:31–35. When the crowd asked for a sign like the manna, Jesus responded: 'My Father giveth you the true bread from heaven... I am the bread of life: he that cometh to me shall never hunger.' The crowd wanted literal bread; Jesus offered Himself.\n\nThe characteristics of manna map precisely onto Christ. Manna came from heaven — Christ descended from the Father. Manna was given freely — salvation is a gift. Manna had to be gathered daily — our relationship with Christ requires daily renewal. Manna could not be stored up — yesterday's spiritual experience cannot sustain today's needs. Manna sustained physical life — Christ offers eternal life.\n\nDeuteronomy 8:3 adds a critical insight: God allowed Israel to hunger and then fed them with manna 'that he might make thee know that man doth not live by bread only, but by every word that proceedeth out of the mouth of the Lord.' The manna was not just food — it was a lesson about dependence on God. Jesus quoted this very verse when tempted by Satan in the wilderness (Matthew 4:4).",
      patterns: "The manna-to-Bread-of-Life connection parallels the Passover-to-sacrament connection. In both cases, a physical provision in the Old Testament becomes a spiritual reality in the New. God teaches through the tangible to prepare for the transcendent.",
      reflection: "Manna had to be gathered fresh each morning. What does your daily 'gathering' of spiritual sustenance look like? Is it consistent, or are you trying to live on yesterday's manna?"
    },
    {
      label: "The brazen serpent",
      focus: "A bronze serpent lifted on a pole healed Israel from deadly bites. Jesus said this was a type of His own lifting up on the cross.",
      scriptures: [{book:"Num",ch:21,vs:6,ve:9},{book:"John",ch:3,vs:14,ve:15},{book:"2 Ne",ch:25,vs:20},{book:"Alma",ch:33,vs:19,ve:22}],
      nuances: "The Hebrew 'nachash nechosheth' in Numbers 21:9 — 'serpent of brass' — is a wordplay: 'nachash' (serpent) and 'nechosheth' (bronze/brass) share the same consonantal root. This literary device embedded the instruction into the very name of the cure: to be saved from the serpent, look at the serpent. To be saved from sin, look upon the One who was 'made sin for us' (2 Corinthians 5:21).",
      commentary: "The brazen serpent is perhaps the most counterintuitive type in all of scripture. When fiery serpents plagued Israel, God's remedy was not to remove the serpents but to provide a means of healing: a bronze serpent lifted on a pole. Anyone bitten had only to look at it and live. The cure required nothing more — and nothing less — than looking.\n\nJesus Himself identified this as a type of His crucifixion in John 3:14–15: 'As Moses lifted up the serpent in the wilderness, even so must the Son of man be lifted up: That whosoever believeth in him should not perish, but have eternal life.' This is the verse immediately preceding John 3:16 — the most famous verse in Christianity. The context of John 3:16 is typological.\n\nNephi confirms the type in 2 Nephi 25:20 and Alma elaborates in Alma 33:19–22: the symbol was 'raised up' so that those who looked might live. Alma then laments that many Israelites refused to look because the remedy was 'so simple.' They perished not because there was no cure but because they would not use it.\n\nThis is the most searching application of any Old Testament type. The Atonement of Christ is available to every soul. The requirement is not complexity but faith — to look, to believe, to accept the remedy offered. Yet many will not look, because it seems too simple, too easy, too unlike what they expected salvation to require.",
      patterns: "The requirement to 'look and live' is the pattern of faith throughout scripture: Naaman washing in the Jordan (2 Kings 5), the Israelites marching around Jericho (Joshua 6), Moroni's promise to pray with real intent (Moroni 10:4). God consistently asks for simple faith before granting miraculous results.",
      reflection: "Are there areas of your life where you resist the simple remedies God offers — perhaps because they seem too easy or too different from what you expected?"
    },
    {
      label: "The Day of Atonement",
      focus: "Leviticus 16 describes the most sacred day in Israel's calendar — a day that prefigured every dimension of Christ's atoning sacrifice.",
      scriptures: [{book:"Lev",ch:16,vs:7,ve:22},{book:"Heb",ch:9,vs:11,ve:14},{book:"2 Ne",ch:11,vs:4},{book:"Alma",ch:25,vs:15,ve:16}],
      nuances: "On the Day of Atonement, two goats were selected. One was sacrificed and its blood carried into the Holy of Holies. The other — the 'azazel' or scapegoat — had the sins of the people symbolically placed on its head and was driven into the wilderness. Together, the two goats represent the full scope of Christ's atonement: He both pays the price of sin (the sacrificed goat) and carries our sins away from us (the scapegoat).",
      commentary: "The Day of Atonement (Yom Kippur) was the only day the high priest entered the Holy of Holies — the innermost chamber of the tabernacle, where God's presence dwelt. He entered not without blood, offering it for his own sins and for the sins of the people. The ritual was elaborate, solemn, and freighted with meaning.\n\nHebrews 9:11–14 provides the definitive Christian interpretation: Christ entered the true Holy of Holies — heaven itself — not with the blood of goats and calves but with His own blood, obtaining eternal redemption. The earthly tabernacle was a copy of the heavenly reality. Every Year, the high priest reenacted what Christ would do once and for all.\n\nThe scapegoat ritual is particularly vivid. The high priest laid both hands on the goat's head and confessed all the iniquities of Israel. The goat then bore those sins into the wilderness — a place of desolation and separation. Christ bore our sins into the desolation of Gethsemane and Golgotha, carrying them away so that, as the Psalmist wrote, they are 'as far as the east is from the west' (Psalm 103:12).\n\nNephi's declaration in 2 Nephi 11:4 — 'all things which have been given of God from the beginning of the world, unto man, are the typifying of him' — applies to no ritual more powerfully than the Day of Atonement. Every detail — the blood, the veil, the scapegoat, the high priest's garments, the incense — pointed to Christ.",
      patterns: "The Day of Atonement is the ritual foundation for Atonement theology (Weeks 20–21). The spatial movement — from the outer court through the veil into God's presence — is also the spatial pattern of the temple endowment, connecting Old Testament ritual to modern Latter-day Saint worship.",
      reflection: "The high priest entered God's presence on behalf of the people. Christ entered on your behalf. What does it mean to you that someone has already gone before you into God's presence?"
    },
    {
      label: "Melchizedek — priest and king",
      focus: "A mysterious figure in Genesis offers bread and wine and holds a priesthood that foreshadows Christ's eternal ministry.",
      scriptures: [{book:"Gen",ch:14,vs:18},{book:"Heb",ch:7,vs:1,ve:3},{book:"Ps",ch:110,vs:4},{book:"Alma",ch:13,vs:14,ve:19}],
      nuances: "The name 'Melchizedek' in Hebrew means 'king of righteousness' (melek = king, tsedeq = righteousness). He is also identified as 'king of Salem,' and Salem (shalom) means peace. Hebrews 7:2 explicitly unpacks both names: 'first being by interpretation King of righteousness, and after that also King of Salem, which is, King of peace.' These are titles of Christ.",
      commentary: "Melchizedek appears in Genesis 14 without genealogy, without introduction, and without explanation. He is king of Salem and priest of the most high God. He brings bread and wine to Abraham and blesses him. Abraham pays tithes to him. And then Melchizedek disappears from the narrative as suddenly as he arrived.\n\nThe author of Hebrews seizes on this mysterious figure and builds an entire Christology around him. Because Melchizedek has no recorded genealogy — no beginning of days nor end of life — he is 'made like unto the Son of God' and 'abideth a priest continually' (Hebrews 7:3). Christ's priesthood is not after the order of Aaron (which depends on lineage and succession) but after the order of Melchizedek (which is eternal).\n\nPsalm 110:4 prophesies this directly: 'Thou art a priest for ever after the order of Melchizedek.' This psalm, attributed to David, was understood as messianic by Jewish interpreters long before Christ. Jesus Himself cited it in Matthew 22:44.\n\nAlma 13:14–19 provides additional detail found nowhere else in scripture. Melchizedek was a king who 'did establish peace in the land in his days' — his people had 'waxed strong in iniquity' but through his preaching of repentance, they were transformed. This Restoration insight reframes Melchizedek from a mysterious cipher to a model of priestly ministry: he brought people to repentance and peace, exactly as Christ does.\n\nThe bread and wine Melchizedek offered to Abraham anticipate the sacrament — the covenant meal of the new and everlasting covenant. The type spans from Genesis to the Last Supper to every sacrament table today.",
      patterns: "Melchizedek as both king and priest anticipates Christ's dual role. In ancient Israel, these roles were strictly separate — kings from Judah, priests from Levi. Christ alone unites both offices, fulfilling what Melchizedek prefigured.",
      reflection: "Melchizedek used his authority to establish peace. How does the priesthood function in your life — whether held personally or received through ordinances — as a means of peace?"
    },
    {
      label: "All things typify Him",
      focus: "Today synthesizes the week by examining the Nephite prophets' explicit teaching that the entire Mosaic system was designed as a witness of Christ.",
      scriptures: [{book:"2 Ne",ch:11,vs:4},{book:"Mosiah",ch:13,vs:29,ve:33},{book:"Alma",ch:25,vs:15,ve:16},{book:"Moses",ch:6,vs:63}],
      nuances: "Moses 6:63 is perhaps the most expansive typological statement in all of scripture: 'All things are created and made to bear record of me... all things bear record of me.' The scope is not limited to rituals or prophecies — creation itself is a type of Christ. The grain that dies to produce fruit, the sun that sets and rises, the seasons of death and renewal — all are witnesses.",
      commentary: "Nephi declared in 2 Nephi 11:4 that 'all things which have been given of God from the beginning of the world, unto man, are the typifying of him.' This is not an exaggeration or a devotional sentiment — it is a hermeneutical principle. Everything God gave was designed to teach about Christ.\n\nAbinadi, standing before the wicked priests of King Noah, made the same argument in Mosiah 13:29–33. The law of Moses — with all its sacrifices, rituals, and regulations — was given because the people were stiff-necked and needed constant, tangible reminders. Every morning and evening sacrifice, every Sabbath observance, every feast day was a lesson about the coming Redeemer. The law was a schoolmaster (Galatians 3:24) designed to bring Israel to Christ.\n\nAlma 25:15–16 records that the converted Lamanites understood this principle: they kept the law of Moses but understood it was a type of Christ's coming. They did not worship the ritual itself — they worshipped the One the ritual pointed to. This distinction is critical. Typology is not about the symbol; it is about the Savior behind the symbol.\n\nMoses 6:63 extends the typological principle beyond ritual to all of creation. Everything created bears record of Christ. This transforms how a disciple sees the world. The natural cycles of death and renewal, the light that dispels darkness, the water that sustains life — all are divine tutorials about the Redeemer.\n\nThis week has examined specific types: Isaac, the Passover, manna, the serpent, the Day of Atonement, Melchizedek. But the principle extends infinitely. Every page of the Old Testament, properly read, testifies of Jesus Christ.",
      patterns: "The movement from specific types (this week) to universal witness (Moses 6:63) mirrors the movement of the gospel itself — from particular covenant events to universal truth. Christ is not a detail within the plan; He is the meaning of everything.",
      reflection: "If all things bear record of Christ, what have you seen recently — in nature, in your daily life, in an ordinary moment — that could be a reminder of Him?"
    }
  ]
};

export default week40;
