import type { WeekContent } from '../types';

const week17: WeekContent = {
  title: "Glory of — The Radiance of Christ",
  subtitle: "The glory of Christ is the visible manifestation of His divine nature — a radiance that fills temples, transforms mortals, and will one day fill the earth.",
  weekScriptures: "Ex 33:18-23; Ps 19:1; Ps 72:19; Hab 2:14; John 2:11; Acts 7:55-56; Rom 6:4; Philip 3:21; Col 3:4; D&C 63:2; D&C 76:56-58; D&C 84:24; Alma 40:25-26",
  synthesis: {
    summary: "Glory in scripture is not abstract praise but visible, tangible reality — light, presence, weight. The Hebrew 'kavod' means weightiness or heaviness; God's glory is the felt impact of His presence. Christ possesses this glory from eternity, shared it with the Father before the world was, and will ultimately share it with the faithful. This week traces the glory of Christ from its premortal origins through its mortal manifestation, its temple presence, and its ultimate eschatological fulfillment when it fills all creation.",
    connections: [
      "The glory of Christ is His power (Week 16) made visible — power is what He does; glory is what He radiates.",
      "Christ as Light of the World (Week 18) is a specific expression of His glory — glory is the broader category of which light is one manifestation.",
      "The transfiguration studied this week connects to Christ's Second Coming (Weeks 42-43), when His glory will no longer be veiled but fully revealed."
    ],
    teaching: "What is the difference between praising God's glory (worship) and seeing God's glory (theophany)? How are both relevant to your discipleship?",
    commitment: "This week, look for evidences of Christ's glory in your daily life — in nature, in the temple, in the faces of people who reflect His light. Record one observation each day."
  },
  days: [
    {
      label: "Glory before the world was",
      focus: "Christ's glory is not earned or acquired; it is eternal. Today explores His premortal glory and the prayer that His followers might share in it.",
      scriptures: [{book:"John",ch:17,vs:5},{book:"John",ch:17,vs:22,ve:24},{book:"D&C",ch:93,vs:36}],
      nuances: "In John 17:5, Jesus prays to be glorified 'with the glory which I had with thee before the world was.' The Greek 'pro tou ton kosmon einai' (before the world existed) places Christ's glory outside of time. This is not glory He acquired through His mortal ministry but glory He possessed eternally and voluntarily set aside. The prayer is not for something new but for the restoration of something primordial.",
      commentary: "John 17 is the longest recorded prayer of Jesus, spoken on the night of His arrest. In its opening verses, He makes a breathtaking request: restore to me the glory I shared with you before creation. This is not a human being aspiring to divinity but a divine being requesting the return of what was always His. The veil of mortality had temporarily obscured His glory, but the glory itself was eternal.\n\nEven more remarkable is verse 22: 'And the glory which thou gavest me I have given them.' Christ does not hoard His glory; He shares it. The purpose of His glorification is the glorification of His followers. This is one of the most audacious promises in scripture — that mortals might participate in the same glory that existed before the foundation of the world.\n\nD&C 93:36 adds a distinctively Restoration insight: 'The glory of God is intelligence, or, in other words, light and truth.' Glory is not merely brightness or visual splendor — it is the fullness of knowledge, light, and truth. This reframes the entire concept: to grow in intelligence and truth is to grow in glory. Every act of learning, every reception of truth, every embrace of light participates in the glory of God.\n\nThe theological implications are profound. If glory is light and truth, and Christ offers to share His glory, then the gospel is an invitation into ever-expanding knowledge, illumination, and reality — an eternal education in the nature of things.",
      patterns: "The pattern of premortal glory temporarily veiled and then restored appears in Christ's own experience (John 17:5), in the plan for humanity (D&C 93:29-36), and in the temple endowment, where participants symbolically pass through stages of increasing light and knowledge.",
      reflection: "Christ prayed that you might share in His eternal glory. What does it mean to you that divine glory is not reserved for God alone but intended to be shared?"
    },
    {
      label: "Glory revealed in the temple",
      focus: "The temple is where God's glory dwells among His people. Today traces the glory of Christ from the tabernacle to the temple to modern houses of God.",
      scriptures: [{book:"Isa",ch:6,vs:1,ve:3},{book:"Ezek",ch:43,vs:1,ve:5},{book:"1 Ne",ch:1,vs:8,ve:10}],
      nuances: "Isaiah's vision in Isaiah 6:1-3 includes the seraphim crying 'Holy, holy, holy is the Lord of hosts: the whole earth is full of his glory.' The threefold repetition (trisagion) is the Hebrew superlative — the ultimate expression of holiness. The Hebrew 'kavod' (glory) here is not metaphorical; Isaiah is describing a visible, space-filling reality. The train of God's robe fills the temple. His presence is not contained by the building but overflows it.",
      commentary: "Isaiah 6 records one of the most significant theophanies in the Old Testament. The prophet sees the Lord high and lifted up, with seraphim declaring His holiness. The glory is so overwhelming that the temple doorposts shake and the building fills with smoke. Isaiah's immediate response is not awe but anguish: 'Woe is me! for I am undone; because I am a man of unclean lips.' Contact with divine glory reveals human inadequacy. This is the consistent pattern — glory both attracts and convicts.\n\nEzekiel 43:1-5 describes the glory of God returning to the temple. For Ezekiel, who had witnessed the glory departing from Solomon's temple (Ezekiel 10:18-19) — one of the most devastating events in Israelite theology — this vision of return was supremely hopeful. The glory comes from the east, fills the house, and the earth shines with His glory. What was lost is restored.\n\nLehi's vision in 1 Nephi 1:8-10 opens the Book of Mormon with a temple theophany. Lehi sees God sitting on His throne, surrounded by numberless concourses of angels, and 'One descending out of the midst of heaven' whose luster is above that of the sun. This is the premortal Christ, and Lehi's reaction mirrors Isaiah's: he is overcome. The Book of Mormon begins, like Isaiah's ministry, with a direct encounter with divine glory.\n\nFor Latter-day Saints, the temple remains the place where God's glory is most concentrated on earth. While modern temple experiences may not include the visible fire and smoke of Isaiah's vision, the purpose is the same: to bring mortals into the presence of divine glory and prepare them for more.",
      patterns: "The glory of God and the temple are linked throughout scripture: the pillar of fire over the tabernacle, the cloud filling Solomon's temple, the glory filling Ezekiel's future temple, and the promise in D&C 109 that God's glory would rest upon latter-day temples. The temple is designed as a container for glory.",
      reflection: "Isaiah was 'undone' by his encounter with God's glory. When has an experience in the temple (or elsewhere) given you a glimpse of divine glory that left you feeling both small and deeply loved?"
    },
    {
      label: "Glory incarnate",
      focus: "In Jesus Christ, the glory of God took human form. Today examines the astonishing claim that mortals 'beheld his glory' in a person.",
      scriptures: [{book:"John",ch:1,vs:14},{book:"Heb",ch:1,vs:3},{book:"2 Cor",ch:4,vs:6}],
      nuances: "Hebrews 1:3 calls Christ 'the brightness of his glory, and the express image of his person.' The Greek 'apaugasma' (brightness/radiance) can mean either the radiance streaming from a light source or the reflection of that light. Either way, the claim is that looking at Christ is looking at God's glory. The word 'charakter' (express image) referred to the impression made by a seal or stamp — an exact replica. Christ is not approximately like God; He is the precise imprint of God's being.",
      commentary: "John 1:14 makes one of the most daring claims in the New Testament: 'We beheld his glory, the glory as of the only begotten of the Father.' John is saying that in the person of Jesus — eating, sleeping, walking the roads of Palestine — they saw divine glory. Not in a mystical vision or a temple theophany, but in a human being. The Word became flesh, and the glory was not diminished by the flesh but transmitted through it.\n\nHebrews 1:3 formalizes this theologically: Christ is not merely a prophet who reflects some of God's attributes. He is the radiance of God's glory and the exact imprint of His nature. This language would later fuel centuries of Christological debate, leading eventually to the Council of Chalcedon's affirmation that Christ is fully God and fully man. For Restoration theology, the additional witness of Joseph Smith seeing the Father and Son as glorified, embodied beings (JS-H 1:17) confirms that glory and physical form are not contradictory but complementary.\n\nPaul's statement in 2 Corinthians 4:6 ties it to personal experience: 'God, who commanded the light to shine out of darkness, hath shined in our hearts, to give the light of the knowledge of the glory of God in the face of Jesus Christ.' The glory of God is encountered in the face of Christ — and this knowledge shines in the human heart. The incarnation means that divine glory has come close enough to touch, to see, to know personally.",
      patterns: "The incarnation of glory is the ultimate expression of the condescension of God (Week 1, Day 2). God did not merely send glory from heaven; He brought it in person. This pattern — God coming down rather than requiring us to go up — is the defining characteristic of the gospel.",
      reflection: "Paul says the knowledge of God's glory comes 'in the face of Jesus Christ.' How does studying the life of Jesus specifically (not just theology about God) reveal divine glory to you?"
    },
    {
      label: "The Transfiguration",
      focus: "For a brief moment on a mountaintop, the veil was pulled back and the disciples saw Christ's glory undimmed. Today examines the Transfiguration and its significance.",
      scriptures: [{book:"Matt",ch:17,vs:1,ve:5},{book:"2 Ne",ch:11,vs:2,ve:3},{book:"3 Ne",ch:19,vs:25}],
      nuances: "In Matthew 17:2, 'his face did shine as the sun, and his raiment was white as the light' uses 'metemorphōthē' (was transfigured/transformed). This is the root of our English 'metamorphosis.' The transformation was not a putting on of something external but a revealing of something internal — the divine nature that was always present beneath the veil of mortality. The glory did not come upon Him from outside; it shone through from within.",
      commentary: "The Transfiguration is a pivotal event in the Gospels. Peter, James, and John ascend a high mountain with Jesus and witness what no mortal eye was prepared for: His face shining like the sun, His clothing blazing with light, Moses and Elijah appearing alongside Him, and the Father's voice declaring, 'This is my beloved Son, in whom I am well pleased; hear ye him.' For one moment, the fullness of Christ's glory was unveiled.\n\nThis event served multiple purposes. It confirmed Christ's identity at a crucial moment — He had recently predicted His own death, and the disciples were troubled. It connected His ministry to the law (Moses) and the prophets (Elijah). And it foreshadowed His future glorification, giving the disciples a preview of the resurrected, glorified Christ they would later encounter.\n\nNephi's testimony in 2 Nephi 11:2-3 — that he had 'seen the Redeemer' and his witness is true — suggests a similar experience of beholding divine glory directly. The Book of Mormon contains multiple accounts of prophets seeing Christ before His mortal birth, each confirming that His glory is not limited to one dispensation or one hemisphere.\n\n3 Nephi 19:25 describes a remarkable parallel: during the Savior's ministry among the Nephites, His disciples were transfigured in prayer, becoming 'as white as the countenance and also the garments of Jesus.' The glory that shone in Christ began to shine through His followers. Transfiguration, it seems, is not for Christ alone — it is the destiny of those who draw near to Him.",
      patterns: "Mountain-top theophanies form a consistent pattern: Moses on Sinai, Elijah on Horeb, Jesus on the Mount of Transfiguration, Joseph Smith and Oliver Cowdery in the Kirtland Temple. Mountains in scripture are the place where heaven and earth meet and glory is revealed.",
      reflection: "The disciples saw Christ's glory for a moment and were forever changed. What glimpses of divine glory have you experienced, and how have they shaped your faith?"
    },
    {
      label: "Glory as transformation",
      focus: "We are not merely observers of Christ's glory; we are being changed by it. Today explores the doctrine that beholding glory produces glory.",
      scriptures: [{book:"2 Cor",ch:3,vs:18},{book:"Moses",ch:1,vs:1,ve:5},{book:"Moses",ch:1,vs:11}],
      nuances: "In 2 Corinthians 3:18, 'we all, with open face beholding as in a glass the glory of the Lord, are changed into the same image from glory to glory.' The Greek 'metamorphoumetha' (we are being transformed) is the same root as the Transfiguration. Paul is saying that what happened to Christ on the mountain is happening to believers progressively — we are being transfigured 'from glory to glory' (apo doxēs eis doxan), from one degree of glory to the next.",
      commentary: "Paul's teaching in 2 Corinthians 3:18 is one of the most transformative verses in the New Testament. The act of beholding Christ's glory is itself the mechanism of change. You do not change first and then see glory; you see glory and are changed by the seeing. This is not passive observation but active transformation — the more you look at Christ, the more you become like Him.\n\nMoses 1:1-5 illustrates this principle dramatically. Moses is caught up to a high mountain, speaks with God face to face, and sees His glory. God declares that Moses is made 'in the similitude of mine Only Begotten' and shows him the workings of creation. For a time, Moses participates in divine perspective, seeing the world as God sees it.\n\nMoses 1:11 then records the aftermath: after God's presence withdraws, Moses falls to the earth and declares, 'Now, for this cause I know that man is nothing, which thing I never had supposed.' The encounter with glory produces not self-aggrandizement but humility. Moses simultaneously learns his worth (made in the similitude of the Only Begotten) and his dependence (man is nothing without God). Both truths are products of glory.\n\nThis double effect — being elevated and humbled at the same time — is the consistent result of encountering divine glory in scripture. Those who see God's glory never come away arrogant. They come away transformed, humbled, and empowered by a clear vision of their relationship to God.",
      patterns: "The pattern of progressive transformation — 'from glory to glory' — echoes the Latter-day Saint understanding of eternal progression. D&C 76 describes three degrees of glory, and D&C 93 teaches that Christ received grace for grace, growing from grace to grace until He received a fullness. The same pattern is offered to His followers.",
      reflection: "Paul says we are 'changed into the same image from glory to glory.' What spiritual practices in your life most consistently expose you to Christ's glory and produce transformation?"
    },
    {
      label: "Glory and the last days",
      focus: "Christ's glory is not only past and present but future. Today examines the prophetic promise that His glory will fill the earth.",
      scriptures: [{book:"Isa",ch:40,vs:5},{book:"Rev",ch:21,vs:23},{book:"D&C",ch:76,vs:19,ve:23}],
      nuances: "Isaiah 40:5 prophesies that 'the glory of the Lord shall be revealed, and all flesh shall see it together.' The Hebrew 'yachdav' (together) is emphatic — not some flesh or select flesh but all flesh, simultaneously. This is not a private mystical experience but a universal, public revelation. The glory that was once confined to the Holy of Holies will fill the entire earth.",
      commentary: "Isaiah 40 opens with 'Comfort ye, comfort ye my people' and moves toward the promise that God's glory will be universally revealed. After centuries of exile, oppression, and waiting, the prophetic vision is that the glory will not remain hidden. It will be made manifest to everyone, everywhere, at the same time.\n\nRevelation 21:23 describes the new Jerusalem: 'The city had no need of the sun, neither of the moon, to shine in it: for the glory of God did lighten it, and the Lamb is the light thereof.' In the final state, the glory of Christ replaces the sun itself. The entire created order is restructured around His radiance. This is not metaphor but eschatological reality — the physical universe will be reorganized with Christ's glory as its central illumination.\n\nJoseph Smith and Sidney Rigdon's vision recorded in D&C 76:19-23 provides a modern witness: they saw the Son of God sitting on the right hand of God and bore testimony that 'he lives! For we saw him, even on the right hand of God.' The glory they beheld confirmed every ancient witness and added a modern one. The progressive revelation of glory — from Isaiah's vision to John's Revelation to Joseph's Restoration — is accelerating toward a climax.\n\nThe trajectory of scripture moves from hidden glory (in the tabernacle, behind the veil) to revealed glory (in Christ's incarnation) to universal glory (at His return). We are living in the penultimate stage, when the glory has been revealed in Christ but has not yet filled the earth. The temple is a foretaste of what is coming.",
      patterns: "The progressive unveiling of glory — tabernacle, temple, incarnation, Second Coming — mirrors the progressive unfolding of the plan of salvation across dispensations. Each stage reveals more glory than the last, building toward the fullness described in Revelation 21 and D&C 76.",
      reflection: "If Christ's glory will one day be the light that replaces the sun, how does that ultimate vision shape how you understand current periods of spiritual darkness?"
    },
    {
      label: "Prepared to receive His glory",
      focus: "Not everyone is prepared to endure divine glory. Today explores what prepares the human soul to receive, rather than be consumed by, the glory of Christ.",
      scriptures: [{book:"D&C",ch:88,vs:7,ve:10},{book:"Morm",ch:9,vs:5},{book:"D&C",ch:76,vs:19,ve:23}],
      nuances: "Mormon 9:5 contains a stark warning: 'If ye could be brought to a knowledge of your awful state... ye would be more miserable to dwell in the presence of that holy Being, when ye shall have a full knowledge of your guilt.' The word 'miserable' is not punitive but descriptive — an unprepared soul in the presence of glory does not experience joy but torment. Glory itself becomes the source of suffering for those who have not been transformed to receive it.",
      commentary: "D&C 88:7-10 describes Christ as the light that is 'in all things, giveth life to all things, is the law by which all things are governed.' This light and glory are not selective — they proceed forth to fill the immensity of space. But the capacity to receive that glory varies enormously. The same sunlight that nourishes a flower can scorch unprotected skin. The glory of Christ is always present; the question is whether we have been prepared to receive it.\n\nMormon 9:5 provides the sobering counterpoint. Moroni warns that the wicked would be more miserable in God's presence than out of it. This is not because God punishes by proximity but because glory reveals. In the presence of perfect holiness, every impurity becomes agonizingly visible. The unprepared soul does not need to be punished — self-knowledge in the light of glory is itself the suffering.\n\nD&C 76, revisited for its climactic declaration, reveals a vision of degrees of glory — telestial, terrestrial, and celestial — each representing a different capacity to receive divine light. This is among the most distinctive doctrines of the Restoration: the afterlife is not binary (heaven or hell) but graduated according to what each soul has become capable of receiving. Preparation for glory is the work of a lifetime — and it consists of becoming, through Christ, the kind of being for whom glory is home.\n\nThe week closes with this sobering and hopeful truth: Christ's glory is coming, whether we are ready for it or not. The purpose of the gospel, the ordinances, the covenants, and daily discipleship is to prepare us to stand in that glory and not be consumed but be completed.",
      patterns: "The pattern of preparation for glory runs through scripture: Moses was transfigured before seeing God (Moses 1:2), the Israelites were told to sanctify themselves before Sinai (Exodus 19:10), and the disciples were prepared by prayer before their transfiguration (3 Nephi 19). Glory is always available; preparation is the variable.",
      reflection: "If Christ's glory reveals everything about who we really are, how does that truth motivate your daily choices? What are you becoming in preparation for that day?"
    }
  ]
};

export default week17;
