import type { WeekContent } from '../types';

const week21: WeekContent = {
  title: "Baptism of — The Sinless One Enters the Water",
  subtitle: "Jesus Christ's baptism inaugurated His public ministry and established the pattern every disciple follows.",
  weekScriptures: "Acts 2:37-38; Acts 8:36-39; Acts 22:16; 1 Pet 3:21; Mark 16:16; D&C 13:1; D&C 22:1-4; D&C 68:25-27; D&C 84:64; 2 Ne 9:23-24; Moro 6:1-4; Alma 5:62; 3 Ne 27:20",
  synthesis: {
    summary: "The baptism of Jesus Christ is one of the most theologically rich events in scripture. The sinless Son of God submitted to an ordinance designed for sinners — not because He needed it, but because we needed to see Him do it. His baptism revealed the Godhead, inaugurated His ministry, established the form and authority of the ordinance, and created the covenant path every disciple walks. Every baptism since points back to His.",
    connections: [
      "Christ's baptism directly connects to Week 20 (Teaching Mode), as it is the supreme enacted parable — teaching by doing what He asks all others to do.",
      "The covenant nature of baptism connects forward to Week 11 (Atonement) and Week 33 (Mediator), where the covenant relationship Christ established finds its fullest expression.",
      "The Father's voice at the baptism connects to Week 2 (Son of God) and Week 23 (Authority of), where Christ's identity and commission are declared from heaven."
    ],
    teaching: "Why did the sinless Son of God need to be baptized? How many different reasons can you find across this week's scriptures? What does each reason teach you about the nature of baptism itself?",
    commitment: "Reflect on your own baptismal covenant this week. Consider writing down what your baptism means to you now — not what it meant when it happened, but what it means today."
  },
  days: [
    {
      label: "Jesus comes to the Jordan",
      focus: "The Son of God presents Himself for baptism by a mortal. Today examines the scene, its participants, and the stunning humility of the moment.",
      scriptures: [{book:"Matt",ch:3,vs:13,ve:17},{book:"Mark",ch:1,vs:9,ve:11},{book:"2 Ne",ch:31,vs:4,ve:7}],
      nuances: "In Matthew 3:14, John 'forbade' Jesus — the Greek 'diekoluen' is imperfect tense, meaning John kept trying to prevent Him, not just once but repeatedly. John's protest was sustained, emphatic. The word 'suffer' in Jesus' response ('Suffer it to be so now') is 'aphes,' literally 'let go' or 'permit' — Jesus is asking John to release his objection. The phrase 'to fulfil all righteousness' (pasan dikaiosunen) has no exact parallel elsewhere in scripture, suggesting a unique, comprehensive purpose.",
      commentary: "Jesus traveled from Galilee to the Jordan specifically to be baptized by John. This was not a spontaneous decision but a deliberate journey to a specific person with a specific authority. Matthew records that John tried to prevent it — recognizing that the one standing before him had no sins to wash away. John understood his own role as preparatory and could not reconcile the idea of the Master submitting to the servant's ordinance.\n\nJesus' response is brief and decisive: 'Suffer it to be so now: for thus it becometh us to fulfil all righteousness.' He does not explain fully. He asks John to trust that this is necessary even if the reasons are not yet clear. This is itself a model of faith — acting on divine direction before full understanding arrives.\n\nNephi, writing six centuries before the event, provides the theological explanation that Matthew does not. In 2 Nephi 31:5–7, Nephi asks the very question John asked: if Jesus is holy, why does He need baptism? Nephi's answer is layered: Christ humbles Himself before the Father, He covenants to be obedient, He shows the gate through which all must enter, and He demonstrates that no one is exempt from the commandments of God.\n\nThe geography matters. The Jordan River carried deep symbolic weight — Israel had crossed it to enter the promised land under Joshua (whose name, like Jesus, derives from the Hebrew root meaning 'to save'). Jesus entering the Jordan echoes Israel's crossing: a passage through water into a new beginning.",
      patterns: "The pattern of the sinless One submitting to requirements designed for the fallen recurs throughout Christ's life. He who had no sin was baptized, kept the law of Moses, and ultimately suffered the penalty for sin. This voluntary submission is the heartbeat of the Atonement, explored in Weeks 12–13.",
      reflection: "Jesus did not need baptism, yet He submitted to it. What does His example teach you about approaching ordinances and commandments you may not fully understand?"
    },
    {
      label: "The Godhead revealed",
      focus: "At Jesus' baptism, all three members of the Godhead are manifest simultaneously. Today explores what this reveals about the nature of God.",
      scriptures: [{book:"Matt",ch:3,vs:16,ve:17},{book:"Luke",ch:3,vs:21,ve:22},{book:"John",ch:1,vs:29,ve:34}],
      nuances: "The phrase 'like a dove' (hosei peristeran) in Matthew 3:16 has been interpreted differently across traditions. Some see the dove as the form the Spirit took; others see it as a descriptor of the manner of descent — gently, peacefully. The Latter-day Saint understanding, informed by D&C 93:15 and Joseph Smith's teachings, affirms that the Holy Ghost descended in the 'sign of the dove.' The voice from heaven uses the phrase 'ho huios mou ho agapetos' — 'my Son, the beloved' — language that echoes the binding of Isaac in Genesis 22, where Isaac is called Abraham's beloved son.",
      commentary: "The baptism of Jesus is the only event in the Gospels where all three members of the Godhead are distinctly and simultaneously manifest: the Son standing in the water, the Spirit descending like a dove, and the Father's voice speaking from heaven. This is not subtle. The Godhead is on full display.\n\nFor Latter-day Saints, this scene carries particular theological weight because it demonstrates the separateness and unity of the Godhead. The Father speaks, the Son is spoken to, and the Spirit descends — three distinct beings acting in perfect concert. This aligns with the Restoration understanding of the Godhead as three separate personages united in purpose, as taught in D&C 130:22.\n\nThe Father's declaration — 'This is my beloved Son, in whom I am well pleased' — is both introduction and endorsement. It publicly identifies Jesus as the divine Son and declares the Father's approval before the ministry begins. The Father's voice will be heard again at the Transfiguration (Matt. 17:5) and at the temple in Jerusalem (John 12:28), each time affirming the Son at a pivotal moment.\n\nJohn the Baptist's witness in John 1:29–34 adds another layer. John testifies that he saw the Spirit descend and remain on Jesus, and that this was the pre-arranged sign by which he would recognize the Messiah. The baptism was not just a public event — it was the fulfillment of a private revelation John had received. God confirmed His Son through both public manifestation and private testimony.",
      patterns: "The simultaneous manifestation of the Godhead at the baptism anticipates other moments of divine disclosure: the First Vision (JS-H 1:17), the Nephite experience in 3 Nephi 11, and the vision of D&C 76. Each time the Godhead is revealed together, it marks the opening of a new dispensational chapter.",
      reflection: "The Father publicly declared His love for the Son before Jesus had performed a single miracle or preached a single sermon. What does that timing suggest about how God feels about you — before you have 'proven' anything?"
    },
    {
      label: "Fulfilling all righteousness",
      focus: "Jesus said He was baptized 'to fulfil all righteousness.' Today unpacks what that phrase means — and why it matters for every person who follows Him into the water.",
      scriptures: [{book:"2 Ne",ch:31,vs:5,ve:13},{book:"D&C",ch:20,vs:72,ve:74},{book:"3 Ne",ch:11,vs:23,ve:28}],
      nuances: "In 2 Nephi 31:9, 'the gate' (translating from the plates) uses a metaphor of entry — baptism is not merely a step along the path but the entrance to the path itself. The concept of a gate implies a clear inside and outside, a threshold that must be crossed. In 3 Nephi 11:27, the statement that the Father, Son, and Holy Ghost are 'one' uses the same language that appears in Christ's intercessory prayer in John 17:21–22, indicating unity of purpose and will.",
      commentary: "Nephi's extended commentary on Christ's baptism in 2 Nephi 31 is the most thorough theological treatment of this event in all of scripture. He identifies multiple reasons for the baptism: to humble Himself before the Father, to witness that He would be obedient to the Father's commandments, to show the children of men the straitness of the path, and to set the example.\n\nThe phrase 'fulfil all righteousness' contains a principle that extends far beyond a single event. Christ demonstrated that covenant obedience is not optional for anyone — not even for the Son of God. If He, being perfect, submitted to every requirement, then the principle is clear: the path is walked, not bypassed. There are no shortcuts in the gospel, and there is no rank that exempts one from obedience.\n\nIn 3 Nephi 11:23–28, the resurrected Christ personally establishes the ordinance of baptism among the Nephites, prescribing its exact form: immersion, in His name, by one who has authority. He also addresses a concern that had apparently caused 'disputations' — He wants no contention about the manner or doctrine of baptism. The clarity is deliberate. This ordinance is too important to be obscured by debate.\n\nD&C 20:72–74 preserves the baptismal prayer, which every baptized Latter-day Saint has heard spoken over them. The covenant language is precise: willingness to take upon oneself the name of Christ, to always remember Him, and to keep His commandments. These are not abstract promises but a daily program of discipleship.",
      patterns: "The ordinance of baptism connects to every other ordinance in the gospel. The sacrament renews it weekly. The temple extends it to the dead. Each ordinance builds on what baptism begins — a covenant relationship with Christ. This progressive covenant structure will be explored further in Week 33 (Mediator).",
      reflection: "If you were to write a personal statement of what your baptismal covenant means to you today, what would you say? How has your understanding of it grown since the day you were baptized?"
    },
    {
      label: "Born of water and of the Spirit",
      focus: "Baptism by water is inseparable from baptism by the Spirit. Today examines the two-part nature of the ordinance and why both are essential.",
      scriptures: [{book:"Moses",ch:6,vs:64,ve:68},{book:"Moro",ch:8,vs:25,ve:26},{book:"John",ch:3,vs:1,ve:8}],
      nuances: "In Moses 6:59, the phrase 'born into the world by water, and blood, and the spirit' parallels the physical birth process (water, blood, breath) with spiritual rebirth. This parallelism is unique to Restoration scripture and is not found in the biblical text. In John 3:5, 'born of water and of the Spirit' uses 'gennao,' which can mean both 'born' and 'begotten,' encompassing the full process of coming into new life.",
      commentary: "When Jesus told Nicodemus that a man must be born of water and of the Spirit, He was not describing two separate events but a single, integrated process of spiritual rebirth. The water and the Spirit work together. Moses 6:64–68 provides the most detailed description of this dual baptism in all of scripture, given by God to Adam: 'by the water ye keep the commandment; by the Spirit ye are justified.'\n\nThis passage in Moses also introduces the remarkable parallel between physical birth and spiritual rebirth: just as we are born into the world through water, blood, and spirit, we are born again through the waters of baptism, the blood of Christ's Atonement, and the Holy Spirit. The ordinance of baptism is designed to echo and complete the process of mortal birth — a birth into a higher kind of life.\n\nMoroni 8:25–26 adds that the gift of the Holy Ghost follows faith, repentance, and baptism — and that this gift brings 'meekness and lowliness of heart,' which in turn invites the Holy Ghost to fill the person with 'hope and perfect love.' The process is sequential and cumulative: each step enables the next.\n\nThe doctrine is clear across dispensations: water baptism without the gift of the Holy Ghost is incomplete, and the Spirit without the covenant of baptism is ungoverned. Both are necessary. This is why Christ established both ordinances — baptism by water and confirmation by the laying on of hands — as inseparable steps on the covenant path.",
      patterns: "The water-and-Spirit pattern appears in the creation account (the Spirit moving upon the waters in Genesis 1:2), in Israel's crossing of the Red Sea (water) followed by the covenant at Sinai (the Spirit of the law), and in the Nephite experience of baptism followed by the visitation of the Holy Ghost (3 Ne. 19:13). The pattern is built into the fabric of God's interaction with humanity.",
      reflection: "How have you experienced the Holy Ghost working in your life since your baptism? Do you see the confirmation of the Spirit as an ongoing process or a one-time event?"
    },
    {
      label: "Baptism as covenant",
      focus: "Baptism is not merely a ritual act — it is a covenant, a binding agreement between the individual and God. Today examines the covenantal dimension of the ordinance.",
      scriptures: [{book:"Mosiah",ch:18,vs:8,ve:10},{book:"D&C",ch:33,vs:11,ve:12},{book:"3 Ne",ch:12,vs:1,ve:2}],
      nuances: "In Mosiah 18:8, the phrase 'bear one another's burdens' uses language that anticipates the Atonement language of Alma 7:11–13, where Christ bears the burdens of humanity. The covenant to bear burdens is a covenant to participate, at a mortal scale, in the Savior's own work. The baptismal covenant makes every member of the body of Christ a small-scale redeemer within their sphere.",
      commentary: "At the waters of Mormon, Alma taught the people what they were covenanting to do by entering the water: bear one another's burdens, mourn with those who mourn, comfort those who stand in need of comfort, and stand as witnesses of God at all times, in all things, and in all places. This is the most comprehensive description of the baptismal covenant in all of scripture.\n\nNotice what is not on the list: perfect behavior, complete doctrinal understanding, or the absence of doubt. The covenant is relational and directional — you agree to move toward Christ and carry others with you. You agree to be present in other people's suffering, not to solve it but to share it. This is a covenant of Christlike engagement with the world.\n\nIn D&C 33:11–12, the Lord calls people to be baptized 'even by water, and then cometh the baptism of fire and of the Holy Ghost.' The language echoes John the Baptist's prophecy about Christ: 'I baptize with water ... he shall baptize you with the Holy Ghost, and with fire' (Matt. 3:11). The fire imagery suggests purification, transformation, and the consuming of what is impure.\n\n3 Nephi 12:1–2 is the resurrected Christ's own statement on the sequence: believe, be baptized, receive the Holy Ghost, and then the Beatitudes begin to describe your life. The Sermon at the temple is framed as post-baptismal instruction — a description of what the covenant life looks like in practice. The baptismal covenant is the entry point into everything that follows.",
      patterns: "Covenants are the organizing structure of God's relationship with humanity. Each major covenant in scripture — from Adam to Abraham to Moses to Christ — builds on what came before. Baptism is the individual's entry into this covenant chain. The temple ordinances (Week 49) extend and complete what baptism begins.",
      reflection: "Read Mosiah 18:8–10 slowly. Which part of the baptismal covenant feels most natural to you? Which part feels most challenging? What does that tell you about where you are in your discipleship?"
    },
    {
      label: "Buried and risen: baptism and resurrection",
      focus: "Paul teaches that baptism symbolizes death, burial, and resurrection with Christ. Today explores the profound symbolism of immersion.",
      scriptures: [{book:"Rom",ch:6,vs:3,ve:6},{book:"Gal",ch:3,vs:27},{book:"D&C",ch:76,vs:51,ve:52}],
      nuances: "In Romans 6:4, 'buried with him by baptism into death' uses the Greek 'sunetaphemen' — we were co-buried, entombed together with Him. The prefix 'sun-' (with, together) appears throughout this passage: co-buried, co-planted, co-crucified. Paul is describing not imitation but participation — the baptized person is mystically joined to Christ's death and resurrection.",
      commentary: "Paul saw in baptism something deeper than washing or even covenant making. He saw a participation in the death and resurrection of Christ Himself. When you go under the water, Paul says, you are buried with Christ. When you come up, you rise with Him into newness of life. The ordinance is not merely symbolic — it enacts the reality it represents.\n\nThis is why immersion matters. Sprinkling cannot convey burial and emergence. The physical form of the ordinance carries the theological meaning: complete submersion (death to the old self), a moment beneath the water (burial), and the upward movement into air and light (resurrection). The body teaches the soul through the experience.\n\nGalatians 3:27 adds the metaphor of clothing: those who are baptized 'have put on Christ,' as one puts on a garment. The image suggests that Christ's identity covers and replaces the old identity. You emerge from the water wearing a new self.\n\nD&C 76:51–52 describes those who inherit the celestial kingdom as those who 'received the testimony of Jesus, and believed on his name and were baptized.' Baptism is listed among the defining characteristics of those who attain the highest salvation — not as a formality but as a genuine spiritual turning point.\n\nThe death-and-resurrection symbolism of baptism means that every baptismal font is, in a sense, both a tomb and a womb. Something dies in that water, and something is born.",
      patterns: "The death-and-resurrection pattern embedded in baptism connects to the broader scriptural theme of new creation. Just as God brought order from chaos through water in Genesis 1, He brings new life from spiritual death through the waters of baptism. The flood narrative (Gen. 6–9), the Red Sea crossing (Ex. 14), and Naaman's washing in the Jordan (2 Kgs. 5:14) all carry baptismal echoes.",
      reflection: "What part of your 'old self' did you leave in the water when you were baptized? Is there something you are still carrying that you could leave behind through the renewing power of the sacrament?"
    },
    {
      label: "Authority to baptize",
      focus: "Not just anyone can baptize. Today examines why proper authority matters — and how Christ personally established the authority to perform this ordinance.",
      scriptures: [{book:"3 Ne",ch:11,vs:23,ve:28},{book:"Acts",ch:19,vs:1,ve:6},{book:"D&C",ch:20,vs:72,ve:74}],
      nuances: "In 3 Nephi 11:25, Christ gives the exact wording of the baptismal prayer and uses the phrase 'having authority given me of Jesus Christ.' This is remarkable — the authority to baptize comes from Christ Himself and must be explicitly acknowledged in the ordinance. In Acts 19:3–5, Paul asks the Ephesian converts 'unto what then were ye baptized?' — indicating that the authority behind the baptism determines its validity, not just the act itself.",
      commentary: "When the resurrected Christ appeared to the Nephites, one of His first acts was to call Nephi forward, give him authority, and prescribe the exact manner and words of baptism. This was not incidental — it was foundational. Before teaching the Sermon at the temple, before healing the sick or blessing the children, He established the ordinance and its authority. The sequence tells us something about priorities.\n\nChrist's care in prescribing the exact form of baptism — immersion, in His name, with the specific prayer recorded in 3 Nephi 11:25 and D&C 20:73 — reflects the seriousness with which God regards His ordinances. The form is not arbitrary. Every element carries meaning: immersion represents burial and resurrection, the name of Christ invokes His covenant, and the authority ensures the ordinance is recognized by heaven.\n\nThe episode in Acts 19 illustrates what happens when authority is absent. Paul encounters believers in Ephesus who had been baptized 'unto John's baptism' but had never received the Holy Ghost. Paul rebaptizes them with proper authority, lays hands on them, and the Spirit comes. The sincerity of their first baptism was not in question — but sincerity without authority left the ordinance incomplete.\n\nThis principle is central to Restoration theology. The priesthood authority to baptize was restored through John the Baptist himself (D&C 13), creating a direct link between the authority at the Jordan River and the authority exercised in every Latter-day Saint baptism today. The chain is unbroken — from Christ to John to Joseph and Oliver to every authorized priesthood holder since.",
      patterns: "The principle that ordinances require proper authority connects directly to Week 23 (Authority of), where the broader question of Christ's authority is explored. Authority is not a bureaucratic requirement but the mechanism by which heaven and earth are connected through covenant. Every dispensation opens with a restoration of authority — from Adam to Noah to Abraham to Moses to Christ to Joseph Smith.",
      reflection: "How does understanding the chain of priesthood authority — from Christ to John the Baptist to Joseph Smith to the person who baptized you — affect how you view your own baptism?"
    }
  ]
};

export default week21;
