import type { WeekContent } from '../types';

const week26: WeekContent = {
  title: "King & Lord — The Sovereign Majesty of Jesus Christ",
  subtitle: "He is not merely a teacher or example — He is the King of Kings and Lord of Lords, the rightful ruler of heaven and earth.",
  weekScriptures: "Rev 19:11–16; 1 Tim 6:14–16; Ps 24:7–10; Dan 7:13–14; Isa 9:6–7; Jer 23:5–6; Zech 14:9; Matt 25:31–34; Luke 1:32–33; John 18:36–37; Philip 2:9–11; 1 Ne 22:24–26; 2 Ne 10:14; Mosiah 3:5; D&C 38:1–3; D&C 76:1–4; Rev 17:14; Ps 2:6–9",
  synthesis: {
    summary: "This week explores the scriptural witness that Jesus Christ holds the title King of Kings and Lord of Lords — not as metaphor but as literal description of His present and future sovereignty. From Old Testament prophecy through New Testament declaration to Restoration confirmation, every dispensation testifies that Christ is the supreme ruler over all creation, all nations, and all other powers. His kingship is unlike earthly rule: it is founded on righteousness, mercy, and the power of the Atonement.",
    connections: [
      "Christ's kingship is rooted in His identity as Creator and Redeemer — themes explored in Weeks 1, 7, and 8.",
      "The coronation imagery in Revelation connects to His role as Judge (Week 36) and Second Coming (Week 43).",
      "His sovereignty as Lord connects to the covenant relationship explored in Week 28 (Messenger of the Covenant)."
    ],
    teaching: "If Jesus Christ is truly the King of Kings, what does that mean for how you relate to other authorities, governments, and power structures in your life?",
    commitment: "Identify one area of your life where you have not yet fully submitted to Christ's authority. What would it look like to let Him be King there?"
  },
  days: [
    {
      label: "King of Kings declared",
      focus: "The title 'King of Kings and Lord of Lords' appears at the climax of scripture's greatest vision. Today we examine what this title means and why it matters.",
      scriptures: [{book:"Rev",ch:19,vs:11,ve:16},{book:"1 Tim",ch:6,vs:14,ve:16},{book:"Ps",ch:2,vs:6,ve:9}],
      nuances: "In Revelation 19:16, the title 'King of Kings and Lord of Lords' (Greek: 'Basileus basileōn kai Kurios kuriōn') uses a Hebrew superlative construction — like 'Holy of Holies' or 'Song of Songs.' It does not mean He is one king among many but that He is the supreme, unrivaled sovereign. The title is written on His vesture and thigh — a detail suggesting it is inseparable from His very person.",
      commentary: "Revelation 19 presents the triumphant Christ riding on a white horse, His eyes like flame, wearing many crowns, with a name that no one fully knows. On His robe is inscribed the title that crowns all others: King of Kings and Lord of Lords. This is the culmination of the entire biblical narrative — the moment when every contested claim to authority is resolved.\n\nPaul in 1 Timothy 6 describes Christ as the 'blessed and only Potentate' who dwells in unapproachable light. The language is deliberately imperial — Paul is writing in a Roman world that demanded worship of Caesar as 'lord and god.' His claim that only Christ holds this title was politically dangerous and theologically absolute.\n\nPsalm 2 provides the Old Testament foundation: God has set His King on Zion, His holy hill. The nations may rage and the rulers conspire, but the divine decree stands. This psalm was understood as messianic by both Jewish and early Christian interpreters, and it frames Christ's kingship as something established by the Father Himself — not seized or earned but bestowed by divine right.\n\nThe cumulative force of these passages is unmistakable: no earthly power, no rival ideology, no competing loyalty can stand against the sovereignty of the risen Christ.",
      patterns: "The 'King of Kings' title echoes through Mesopotamian and Persian royal ideology, where it described the supreme emperor. Scripture deliberately takes this political title and applies it to Christ, asserting His authority over all human systems of power — a theme that runs from Daniel through Revelation.",
      reflection: "What does it mean for your daily life that the Person you pray to holds the title King of Kings — not as poetry but as literal truth?"
    },
    {
      label: "The ancient throne foreseen",
      focus: "Old Testament prophets saw Christ's kingship centuries before His birth. Today explores the prophetic vision of His everlasting throne.",
      scriptures: [{book:"Isa",ch:9,vs:6,ve:7},{book:"Dan",ch:7,vs:13,ve:14},{book:"Jer",ch:23,vs:5,ve:6}],
      nuances: "In Isaiah 9:6, the Hebrew titles are extraordinary: 'Pele Yo'etz' (Wonderful Counselor), 'El Gibbor' (Mighty God), 'Avi Ad' (Everlasting Father or Father of Eternity), 'Sar Shalom' (Prince of Peace). The title 'El Gibbor' — Mighty God — is particularly striking because 'El' is a divine name. Isaiah is attributing full deity to this coming child.",
      commentary: "Isaiah 9:6–7 is among the most famous messianic prophecies in all scripture. A child is born, a son is given, and the government rests on His shoulders. The titles Isaiah assigns are not those of an earthly monarch — they are divine names. The increase of His government and peace will have no end. This is not a temporary administration but an everlasting kingdom.\n\nDaniel 7:13–14 adds a visionary dimension. One 'like the Son of man' comes before the Ancient of Days and receives dominion, glory, and a kingdom that encompasses all peoples, nations, and languages. His dominion is everlasting — it will not pass away, and His kingdom will never be destroyed. This is the passage Jesus most frequently drew upon when referring to Himself as 'the Son of Man' (explored further in Week 30).\n\nJeremiah 23:5–6 introduces the image of a righteous Branch raised up from David's line — a king who will reign wisely and execute justice and righteousness. His name will be 'The Lord Our Righteousness' (Yahweh Tsidkenu). Jeremiah places kingship and righteousness as inseparable: Christ's rule is not merely powerful but fundamentally just.\n\nTogether these prophecies paint a portrait of a king unlike any earthly ruler — one whose authority is divine, whose reign is eternal, and whose kingdom is characterized by justice and peace rather than coercion and conquest.",
      patterns: "Isaiah, Daniel, and Jeremiah each approach Christ's kingship from a different angle — Isaiah through titles, Daniel through vision, Jeremiah through lineage. This multi-witness prophetic pattern confirms the doctrine with the certainty that Deuteronomy 19:15 requires.",
      reflection: "Which of the titles in Isaiah 9:6 speaks most powerfully to you right now — Wonderful Counselor, Mighty God, Everlasting Father, or Prince of Peace? Why?"
    },
    {
      label: "A kingdom not of this world",
      focus: "When Pilate asked if He was a king, Jesus did not deny it — but He redefined what kingship means. Today examines the nature of Christ's kingdom.",
      scriptures: [{book:"John",ch:18,vs:36,ve:37},{book:"Matt",ch:25,vs:31,ve:34},{book:"Luke",ch:1,vs:32,ve:33}],
      nuances: "In John 18:36, 'My kingdom is not of this world' uses the Greek 'ek tou kosmou toutou' — meaning 'out of' or 'from' this world. Jesus is not saying His kingdom is irrelevant to this world but that its origin and power do not derive from earthly sources. The distinction is about source and character, not about disengagement from reality.",
      commentary: "Standing before Pilate, bound and beaten, Jesus makes one of the most remarkable claims in history: He is a king. But His kingdom is not of this world. If it were, His servants would fight. This is not a retreat from power but a redefinition of it. Christ's authority does not depend on armies, wealth, or political maneuvering. It operates on entirely different principles.\n\nMatthew 25 shows what that kingship looks like in practice. When the Son of Man comes in His glory with all the holy angels, He will sit on the throne of His glory and separate the nations. The criteria for judgment are startlingly practical: Did you feed the hungry? Visit the sick? Clothe the naked? Christ's kingship is exercised through compassion and measured by how we treat the most vulnerable.\n\nLuke 1:32–33 records Gabriel's announcement to Mary: her son will be given the throne of His father David, and of His kingdom there will be no end. The angel links Christ's kingship to David's line — fulfilling the covenant God made with David in 2 Samuel 7 — while also declaring that this kingdom transcends every earthly dynasty.\n\nThe tension between 'not of this world' and 'no end to His kingdom' is the central paradox of Christian political theology. Christ's kingdom is real, present, and powerful — yet it operates by principles that look like weakness to the world: service, sacrifice, and love.",
      patterns: "The contrast between earthly and divine kingship is a pattern throughout scripture — from Saul versus David to Herod versus Jesus. Earthly kings grasp for power; the divine King lays it down and takes it up again through the Atonement (see Weeks 11–13).",
      reflection: "How do you experience the tension between living in an earthly society with its own authorities and belonging to a kingdom 'not of this world'?"
    },
    {
      label: "Every knee shall bow",
      focus: "The ultimate scope of Christ's lordship — every being in every realm will acknowledge Him. Today explores the universality of His dominion.",
      scriptures: [{book:"Philip",ch:2,vs:9,ve:11},{book:"D&C",ch:76,vs:1,ve:4},{book:"Rev",ch:17,vs:14}],
      nuances: "Philippians 2:10–11 describes every knee bowing 'in heaven, and things in earth, and things under the earth' — the Greek 'epouranion, epigeion, katachthonion' encompasses the entire cosmos in a tripartite division. Paul is drawing on Isaiah 45:23, where Jehovah declares that every knee will bow to Him — and applying that Jehovah-text directly to Jesus, an extraordinary Christological move.",
      commentary: "Philippians 2:5–11 is widely recognized as one of the earliest Christian hymns, possibly predating Paul's letter. It traces a descending and ascending arc: Christ, who was in the form of God, emptied Himself, became a servant, humbled Himself to death on a cross — and therefore God highly exalted Him and gave Him a name above every name. The kingship of Christ is not despite His suffering but because of it. He descended below all things so He could ascend above all things.\n\nD&C 76 opens with a declaration of God's greatness and mercy, framing the vision of the degrees of glory that follows. The revelation makes clear that Christ's dominion extends to every kingdom — celestial, terrestrial, and telestial. His lordship is not limited to the righteous; it encompasses every soul who has ever lived.\n\nRevelation 17:14 places the title in a context of cosmic warfare: the Lamb will overcome all opposing powers because He is Lord of Lords and King of Kings, and those with Him are called, chosen, and faithful. The title is not merely honorific — it describes actual, operative authority that defeats every rival.\n\nThe universality of Christ's lordship means there is no corner of creation, no depth of human experience, no realm of existence that lies outside His sovereign care.",
      patterns: "The Philippians hymn follows the same descent-ascent pattern as 3 Nephi 11 and D&C 88:6 — Christ descends below all things to rise above all things. This kenotic pattern (self-emptying followed by exaltation) is central to understanding Week 11 (Atonement) and Week 12 (Resurrection).",
      reflection: "Philippians says Christ was exalted because He humbled Himself. What does this teach you about the relationship between humility and true authority in your own life?"
    },
    {
      label: "The Lord of Hosts",
      focus: "Throughout the Old Testament, Jehovah is called the Lord of Hosts — the commander of heavenly armies. Today connects this title to the premortal Christ.",
      scriptures: [{book:"Ps",ch:24,vs:7,ve:10},{book:"D&C",ch:38,vs:1,ve:3},{book:"Zech",ch:14,vs:9}],
      nuances: "Psalm 24 uses the title 'Yahweh Tsevaot' — the Lord of Hosts (or armies). 'Tsevaot' can refer to human armies, angelic hosts, or the stars of heaven. The breadth of the term suggests authority over every ordered force in creation. The psalm was likely used liturgically as a processional hymn when the Ark of the Covenant entered the temple.",
      commentary: "Psalm 24 is a dramatic temple liturgy. The gates are commanded to lift up their heads so the King of Glory may enter. The question rings out: 'Who is this King of glory?' The answer: 'The Lord of hosts, he is the King of glory.' This is a processional scene — the divine King entering His temple, His holy place. Early Christian readers saw in this a prophecy of Christ's triumphal ascension into heaven.\n\nD&C 38:1–3 opens with the Lord identifying Himself in unmistakable terms: He is the same who looked upon the wide expanse of eternity and all the seraphic hosts of heaven before the world was made. He is the same who knows all things. He is Christ, the Great I AM. This self-identification connects the Restoration Christ directly to the Jehovah of the Old Testament — the Lord of Hosts who commanded Israel's worship.\n\nZechariah 14:9 looks forward to a day when 'the Lord shall be king over all the earth: in that day shall there be one Lord, and his name one.' This eschatological vision anticipates the complete unification of all things under Christ's lordship — a day when divided loyalties and competing gods are no more.\n\nRestoration theology affirms that the Jehovah of the Old Testament is the premortal Jesus Christ. Every time the psalms and prophets speak of the Lord of Hosts, they are speaking of the same Being who was born in Bethlehem and appeared to Joseph Smith.",
      patterns: "The temple connection in Psalm 24 — the King entering His house — anticipates Christ's visits to His temple in 3 Nephi 11 and Malachi 3, both central to Restoration theology. This links to Week 28 (Messenger of the Covenant) and Week 42 (Appearances).",
      reflection: "If Psalm 24 describes the King of Glory entering His temple, how does that shape your experience of entering the temple yourself?"
    },
    {
      label: "Christ's kingship in the Book of Mormon",
      focus: "Book of Mormon prophets testified of Christ's sovereign rule in ways that complement and deepen biblical witness. Today explores their unique contributions.",
      scriptures: [{book:"1 Ne",ch:22,vs:24,ve:26},{book:"2 Ne",ch:10,vs:14},{book:"Mosiah",ch:3,vs:5}],
      nuances: "In 2 Nephi 10:14, Jacob declares that 'he that fighteth against Zion shall perish.' The Hebrew concept behind 'Zion' carries connotations of the highest point — the place of God's rule. Jacob is not making a political statement about a city but a theological statement about the invincibility of Christ's cause and covenant people.",
      commentary: "Nephi prophesies that in the last days, the Holy One of Israel will reign in dominion, might, power, and great glory. His language in 1 Nephi 22 emphasizes that Christ's kingship will be manifest — visible, active, and unmistakable. Nephi places this not in a distant heavenly realm but on this earth, among His covenant people. The righteous need not fear because their king is among them.\n\nJacob extends this in 2 Nephi 10:14 with a declaration that has both comfort and warning: the God of Israel is the true king, and all who fight against Zion will perish. Jacob is speaking to a displaced people — exiles who had lost their homeland, their temple, and much of their national identity. His message is that none of those losses negate Christ's sovereignty. The king remains king even when His people are scattered.\n\nKing Benjamin's angel in Mosiah 3:5 makes a statement of breathtaking scope: the Lord Omnipotent who reigns from all eternity to all eternity shall come down from heaven among the children of men. The title 'Lord Omnipotent' (used only in the Book of Mormon and in Revelation 19:6) links Christ's kingship to His omnipotence — He rules because He possesses all power, and He possesses all power because He is God.\n\nThe Book of Mormon contributes a distinctive emphasis: Christ's kingship is not merely future. He is reigning now, from all eternity. The question is not whether He will become king but whether we will recognize the kingship that already exists.",
      patterns: "Book of Mormon prophets consistently frame Christ's kingship as a source of hope for scattered and afflicted people — a pattern that runs from 1 Nephi through 4 Nephi. This pastoral dimension of Christ's sovereignty connects to Week 14 (Good Shepherd).",
      reflection: "Jacob testified of Christ's kingship while living in exile. How does Christ's sovereignty bring comfort to you in times when you feel displaced or uncertain?"
    },
    {
      label: "Crowned with many crowns",
      focus: "Christ wears many crowns because He holds many roles. Today synthesizes the week by exploring how His kingship integrates every other title and office.",
      scriptures: [{book:"Rev",ch:19,vs:12},{book:"Isa",ch:9,vs:7},{book:"D&C",ch:38,vs:1,ve:3},{book:"2 Ne",ch:10,vs:14}],
      nuances: "Revelation 19:12 says Christ has 'on his head many crowns' — the Greek 'diademata polla.' Unlike 'stephanos' (a victory wreath), 'diadema' is a royal crown denoting sovereign authority. The many crowns suggest multiple realms of dominion, multiple offices held simultaneously. No single crown captures the fullness of His authority.",
      commentary: "The image of many crowns is the perfect conclusion for this week's study. Christ is not king in one narrow sense — He is king as Creator, king as Redeemer, king as Judge, king as Shepherd, king as High Priest. Each crown represents a dimension of His authority that other weeks in this study explore in detail.\n\nIsaiah 9:7 promises that of the increase of His government there will be no end. This is an extraordinary phrase — most governments plateau or decline. Christ's kingdom is characterized by endless expansion, not of territory but of righteousness, justice, and peace. His is the only administration that grows without corruption.\n\nD&C 38:1–3 demonstrates the integration of His titles: He is the Great I AM, the Creator, the one who knows all things. Each of these is a distinct office, yet they converge in a single Person. His kingship is not a role He plays but the natural expression of who He is.\n\nAs you look back over this week, the central truth is this: Jesus Christ is not symbolically or metaphorically the King — He is the actual, present, reigning sovereign of all creation. Every other power is temporary. Every other authority is delegated. His alone is inherent, eternal, and absolute. The question the gospel puts to each of us is not whether He is King but whether we will live as His subjects — willingly, joyfully, and with full confidence in His reign.",
      patterns: "The 'many crowns' motif integrates themes from across the entire year of study — Creator (Week 7), Redeemer (Week 8), Judge (Week 36), Shepherd (Week 14), High Priest (Week 17). Christ's kingship is the unifying frame for every other title.",
      reflection: "As you finish this week, which 'crown' of Christ — Creator, Redeemer, Judge, Shepherd, King — do you most need Him to wear in your life right now?"
    }
  ]
};

export default week26;
