import type { WeekContent } from '../types';

const week09: WeekContent = {
  title: "Mission of — The Purpose Behind Everything He Did",
  subtitle: "Jesus Christ came with a specific mission: to do the will of the Father, to bring salvation, and to invite all to come unto Him.",
  weekScriptures: "Luke 4:16–21; John 6:38–40; Luke 19:10; 2 Ne. 2:6–8; Mosiah 15:8–9; 3 Ne. 27:13–15; John 10:10–18; D&C 18:10–12; John 18:37; Alma 42:15; D&C 11:28; Moses 1:39; John 17:1–5; 3 Ne. 27:21–22; Jacob 1:7; Alma 34:8–10; Heb. 10:5–10; D&C 138:1–4; 1 Tim. 2:3–6; 2 Ne. 26:24–28",
  synthesis: {
    summary: "Jesus Christ did not come to earth by accident or impulse. He came with a clearly defined mission given by the Father: to seek and save the lost, to fulfill the law, to lay down His life, and to bring to pass immortality and eternal life. Every miracle, every parable, every step toward Gethsemane and Golgotha was part of that purpose. Understanding His mission reframes everything He said and did — not as random acts of kindness but as the deliberate execution of the plan of salvation.",
    connections: [
      "The identity of Christ explored in Week 1 gives Him the authority to carry out this mission — only a divine being could accomplish what was required.",
      "His mission anticipates the Atonement (Week 13), the Crucifixion (Week 11), and the Resurrection (Week 12) as deliberate acts, not tragic accidents.",
      "The voluntary nature of His mission connects directly to the doctrine of agency — He chose to come, just as we must choose to follow."
    ],
    teaching: "If someone asked you, 'What was Jesus actually trying to accomplish?' — how would you answer using this week's scriptures? What surprises you about the breadth of His stated mission?",
    commitment: "Identify one aspect of Christ's mission that feels especially personal to you right now. How can you align your life more fully with that purpose this week?"
  },
  days: [
    {
      label: "His mission in His own words",
      focus: "Jesus declared His own mission publicly at the start of His ministry. Today we hear Him define it Himself.",
      scriptures: [{book:"Luke",ch:4,vs:16,ve:21},{book:"John",ch:6,vs:38,ve:40},{book:"3 Ne",ch:27,vs:13,ve:15}],
      nuances: "In Luke 4:18, Jesus reads from Isaiah 61 and applies it to Himself. The Greek 'apestalken me' (has sent me) uses the root of 'apostello' — the same word from which 'apostle' derives. Jesus is declaring Himself the sent one, the ultimate Apostle of the Father. His mission language is always rooted in being sent, not in self-appointment.",
      commentary: "In the synagogue at Nazareth, Jesus unrolls the scroll of Isaiah and reads a passage about preaching to the poor, healing the brokenhearted, and proclaiming liberty to captives. Then He makes the stunning declaration: this scripture is fulfilled today, in your hearing. This is not merely a sermon — it is a mission statement. He is identifying Himself as the one Isaiah foretold.\n\nJohn 6:38–40 adds another dimension. Jesus states plainly that He came not to do His own will but the will of the Father. His mission is perfectly aligned with the Father's purpose. He did not freelance. Every act of healing, every teaching, every confrontation with religious leaders was in service of a single purpose: to bring salvation and lose none of those the Father had given Him.\n\n3 Nephi 27:13–15 offers the resurrected Christ's own summary of His entire mission to the Nephites. He came to do the will of the Father. He was lifted up on the cross so He could draw all people to Himself. The mission is clear, deliberate, and comprehensive.\n\nAcross these three passages — a Galilean synagogue, a Judean teaching moment, and a post-resurrection appearance in the Americas — the same Person defines the same mission in the same terms. He was sent. He came to save. He accomplished what the Father asked.",
      patterns: "Christ consistently defines His mission in terms of the Father's will, not His own initiative. This pattern of divine submission will reappear throughout the year, especially in Weeks 11–13 as He approaches the cross.",
      reflection: "Jesus knew exactly why He was here. How clearly can you articulate the purpose of your own life? What would change if you saw your life as a mission given by the Father?"
    },
    {
      label: "Sent to seek the lost",
      focus: "A central element of Christ's mission was to find and recover those who had strayed. Today explores the seeking nature of His work.",
      scriptures: [{book:"Luke",ch:19,vs:10},{book:"D&C",ch:18,vs:10,ve:12},{book:"2 Ne",ch:26,vs:24,ve:28}],
      nuances: "In Luke 19:10, the Greek 'z\u0113t\u0113sai kai s\u014dsai' (to seek and to save) uses two infinitives of purpose. The seeking comes before the saving — Christ actively pursues before He rescues. This is not passive availability; it is aggressive redemption. The word 'apollumi' (lost/perishing) can mean both 'destroyed' and 'wandering' — He comes for both the ruined and the confused.",
      commentary: "The encounter with Zacchaeus is one of the most vivid illustrations of Christ's mission. A tax collector — despised, dishonest, literally short in stature — climbs a tree just to catch a glimpse of Jesus. And Jesus stops, looks up, and calls him by name. The crowd murmurs that Jesus has gone to be a guest of a sinner. But Jesus declares the purpose of the entire visit: the Son of Man came to seek and to save that which was lost.\n\nD&C 18:10–12 expands the principle into Restoration theology. The worth of souls is great in the sight of God, and Christ suffered, bled, and died for all. If you labor all your days and bring but one soul to Him, great shall be your joy. This passage has become one of the most quoted in Latter-day Saint culture, and rightly so — it captures the missionary heartbeat of Christ's own mission.\n\nNephi's words in 2 Nephi 26:24–28 are sweeping: everything Christ does, He does for the benefit of the world. He invites all to come unto Him — black and white, bond and free, male and female. His mission excludes no one. He commands none to depart from Him.\n\nAcross the Christian tradition, the seeking nature of God has been a central theme from the parable of the lost sheep to the hymns of John Wesley. Restoration theology intensifies this with the claim that the work of seeking extends beyond death itself — through temple ordinances for the dead (see D&C 138, studied later this week).",
      patterns: "The seeking pattern appears across all dispensations. God sought Adam in the garden, called Abraham from Ur, sent prophets to Israel, and sent His Son to the world. The mission of seeking is not a New Testament innovation — it is the oldest divine pattern.",
      reflection: "Is there someone in your life who feels 'lost' — distant from God or from hope? How might you participate in Christ's seeking mission this week?"
    },
    {
      label: "To give life, and give it abundantly",
      focus: "Christ's mission was not merely to prevent death but to offer a richer, fuller kind of life. Today explores what 'abundant life' means.",
      scriptures: [{book:"John",ch:10,vs:10,ve:18},{book:"2 Ne",ch:2,vs:6,ve:8},{book:"Moses",ch:1,vs:39}],
      nuances: "In John 10:10, 'perissos' (translated 'more abundantly') means exceeding, overflowing, beyond measure. Christ is not offering a slightly improved existence — He is offering life that spills over every boundary. The contrast with the thief who comes to steal, kill, and destroy is stark. The Good Shepherd's mission is the polar opposite of the adversary's agenda.",
      commentary: "John 10 is the Good Shepherd discourse, one of the most intimate self-descriptions Jesus ever gave. He declares that He is the door, the shepherd, and the one who lays down His life for the sheep. No one takes His life from Him — He lays it down voluntarily. This is mission language at its most personal: He came so that His sheep might have life, and have it more abundantly.\n\nLehi's teaching in 2 Nephi 2:6–8 situates this abundant life within the plan of redemption. The Messiah comes to redeem mankind from the fall. Redemption is offered freely to all who have a broken heart and contrite spirit. The mission is not only cosmic in scope — it is conditioned on the heart's response.\n\nMoses 1:39 provides the definitive summary of the Father's (and by extension, the Son's) entire purpose: to bring to pass the immortality and eternal life of man. Immortality is universal — all will be resurrected. Eternal life is conditional — it requires covenant faithfulness. Christ's mission encompasses both gifts.\n\nThe concept of 'abundant life' has been interpreted in many ways across Christianity. Prosperity gospel movements have reduced it to material wealth. Contemplative traditions have understood it as interior communion with God. Restoration theology sees it as exaltation — becoming like the Father and the Son, inheriting all that They have. This is the most expansive reading of 'abundant life' in all of Christian thought.",
      patterns: "The contrast between the thief and the shepherd in John 10 parallels the contrast between Satan's plan and Christ's plan in the premortal council. The adversary offered a plan that would steal agency; Christ offered a plan that would give abundant life.",
      reflection: "What does 'abundant life' look like in your current season? Are there areas where you have been settling for survival when Christ is offering something more?"
    },
    {
      label: "To fulfill the law and the prophets",
      focus: "Christ came not to destroy but to fulfill. Today examines how His mission completed everything that came before Him.",
      scriptures: [{book:"Heb",ch:10,vs:5,ve:10},{book:"Alma",ch:34,vs:8,ve:10},{book:"3 Ne",ch:27,vs:21,ve:22}],
      nuances: "Hebrews 10:5 quotes Psalm 40:6 from the Septuagint: 'a body thou hast prepared me.' The Hebrew original reads 'ears thou hast opened for me,' suggesting obedient listening. The Septuagint translators rendered it as 'body,' shifting the emphasis to incarnation. The author of Hebrews uses this Septuagint reading to argue that Christ's physical body was the ultimate offering — the one to which all animal sacrifices pointed.",
      commentary: "The book of Hebrews makes a sweeping argument: the entire Mosaic system of sacrifices was preparatory. Bulls and goats could never actually remove sin — they could only point forward to the one sacrifice that could. When Christ said, 'Lo, I come to do thy will, O God,' He was declaring that His mission was to be the final offering, the one that rendered all previous offerings complete.\n\nAmulek's teaching in Alma 34:8–10 makes the same argument in Book of Mormon terms. There must be a great and last sacrifice — not a sacrifice of man, not of beast, but an infinite and eternal sacrifice. The word 'infinite' is crucial: the sacrifice must be unlimited in scope because the problem it addresses — the fall, sin, death — is unlimited in its reach.\n\nIn 3 Nephi 27:21–22, the resurrected Christ commands His disciples to do the things they have seen Him do. His mission becomes the template for their mission. The fulfillment of the law was not the end of the story — it was the beginning of a new chapter in which His followers carry forward the work.\n\nClassical Christian theology has long recognized this fulfillment theme. The relationship between the Old and New Testaments is one of promise and fulfillment, shadow and substance. Restoration theology extends this further by teaching that the fulness of the gospel — including temple ordinances — represents the complete fulfillment of everything the prophets anticipated.",
      patterns: "The principle of fulfillment connects the Old Testament, New Testament, and Restoration. Each dispensation is not a replacement but a completion of what came before. This will be central in Weeks 39–41 on prophecies and types.",
      reflection: "Are there 'old' promises, covenants, or commitments in your life that God is not asking you to abandon but to fulfill more deeply?"
    },
    {
      label: "To bear witness of the truth",
      focus: "Before Pilate, Jesus declared that He came to bear witness of the truth. Today explores the truth-bearing dimension of His mission.",
      scriptures: [{book:"John",ch:18,vs:37},{book:"Alma",ch:42,vs:15},{book:"D&C",ch:11,vs:28}],
      nuances: "In John 18:37, Jesus tells Pilate, 'Everyone that is of the truth heareth my voice.' The Greek 'ho \u014dn ek t\u0113s al\u0113theias' means 'the one who is from the truth' — belonging to the truth as a source or origin. Jesus is not merely saying 'truth-lovers listen to me.' He is saying those who originate from truth recognize Him. This is a statement about spiritual identity, not just intellectual preference.",
      commentary: "Standing before Pilate — beaten, bound, facing execution — Jesus makes one of the most extraordinary claims of His ministry. He did not come to establish a political kingdom. He came to bear witness of the truth. Pilate's famous response — 'What is truth?' — may have been cynical, philosophical, or genuinely bewildered. Either way, the irony is devastating: Truth Himself was standing in front of Pilate, and Pilate could not recognize Him.\n\nAlma 42:15 reveals that truth is embedded in the very structure of the plan of redemption. God's plan does not work by ignoring justice or circumventing truth — it works through them. Mercy cannot rob justice. The Atonement satisfies the demands of justice while extending mercy. This is truth in its most operational sense: the plan works because it is true.\n\nD&C 11:28 offers a simple, powerful directive: study the word of truth. If we desire to understand Christ's mission, the method is straightforward — immerse ourselves in His word. The mission of truth-bearing requires truth-seekers.\n\nAcross Christian philosophy, the relationship between Christ and truth has generated centuries of reflection. Augustine argued that all truth is God's truth. Aquinas developed natural theology on the premise that reason and revelation converge. Restoration theology adds the claim that truth can be known not only through reason and scripture but through direct revelation by the Holy Ghost — a democratization of access to truth that is among the most radical claims of the Restoration.",
      patterns: "Christ's declaration before Pilate connects forward to Week 10 (Betrayal & Trials). Even in His trial, His mission did not change. He was still bearing witness of the truth, even to the man who would condemn Him.",
      reflection: "Pilate asked, 'What is truth?' and walked away from it. Are there truths in your life that you have recognized but not yet fully embraced?"
    },
    {
      label: "To bring salvation beyond the grave",
      focus: "Christ's mission did not end at Calvary. Today explores the astonishing teaching that His work extends to the world of spirits.",
      scriptures: [{book:"D&C",ch:138,vs:1,ve:4},{book:"1 Tim",ch:2,vs:3,ve:6},{book:"1 Pet",ch:3,vs:18,ve:20}],
      nuances: "In 1 Peter 3:19, the phrase 'spirits in prison' (pneumasin en phulak\u0113) uses 'phulak\u0113' — a word meaning a guarded holding place, not a place of punishment. Peter's language suggests a place of waiting, not damnation. This nuance is critical: the spirits were not beyond reach. Christ's mission extended even to those held in this intermediate state.",
      commentary: "D&C 138 records President Joseph F. Smith's 1918 vision of the redemption of the dead — one of the most theologically significant revelations in the Restoration. While meditating on 1 Peter 3 and 4, President Smith saw the Savior's visit to the spirit world between His death and resurrection. Christ organized righteous spirits to carry the gospel message to those who had not heard it in mortality.\n\nPaul's statement in 1 Timothy 2:3–6 declares that God desires all people to be saved and to come to a knowledge of the truth. The universality of this desire raises a question that most of Christianity has struggled to answer: what about the billions who lived and died without hearing the gospel? Restoration theology provides a distinctive answer through the doctrine of vicarious ordinances — baptism for the dead, temple sealings, and the spirit world mission.\n\n1 Peter 3:18–20 is one of the most debated passages in the New Testament. Peter describes Christ preaching to spirits who were disobedient in the days of Noah. Many Christian traditions have struggled with this passage, since it implies post-mortem evangelism. Latter-day Saint readers find in it a natural confirmation of what D&C 138 describes in detail.\n\nThis dimension of Christ's mission is among the most distinctive and hopeful teachings of the Restoration. His mission is not limited by mortality's boundaries. He seeks the lost even beyond the veil of death.",
      patterns: "The seeking mission from earlier this week (Luke 19:10) extends beyond mortality. The same Christ who sought Zacchaeus in a tree organized a mission to seek souls in the spirit world. The pattern is relentless: He does not stop seeking.",
      reflection: "How does the doctrine of salvation for the dead expand your understanding of God's fairness and Christ's mission? Does it change how you think about your own ancestors?"
    },
    {
      label: "His mission becomes our mission",
      focus: "Christ's mission was never meant to remain only His. Today explores how He commissions His followers to continue the work.",
      scriptures: [{book:"John",ch:17,vs:1,ve:5},{book:"Jacob",ch:1,vs:7},{book:"Mosiah",ch:15,vs:8,ve:9}],
      nuances: "John 17 is often called Christ's High Priestly Prayer or Intercessory Prayer. In verse 4, He says, 'I have finished the work thou gavest me to do.' The Greek 'teleios\u0101' (I have completed/perfected) is the same root as 'tetelestai' — 'It is finished' — spoken on the cross (John 19:30). His prayer anticipates the completion of His mission even before the Crucifixion.",
      commentary: "John 17 is perhaps the most intimate chapter in all of scripture. Jesus prays to the Father in the presence of His disciples, and we are allowed to overhear. He speaks of completing the work He was given, of glorifying the Father, and of the eternal life that consists in knowing the only true God and Jesus Christ whom He has sent. This is not a prayer of anxiety — it is a prayer of purposeful surrender.\n\nJacob 1:7 reveals that the early Nephite leaders understood their own mission in terms of Christ's mission. They labored diligently to persuade the people to come unto Christ and partake of the goodness of God. Their work was derivative — it drew its purpose from His purpose. Every missionary, every parent, every teacher who points someone to Christ is participating in His original mission.\n\nMosiah 15:8–9 describes the mechanics of Christ's mission in language that is both theological and deeply personal. The will of the Son is swallowed up in the will of the Father. He stands between mankind and justice, having broken the bands of death and taken upon Himself their iniquity. This is the mediatorial role — the core of His mission — and it continues through every ordinance and covenant offered in His Church.\n\nThe Great Commission in Matthew 28, the charge to the Nephite disciples in 3 Nephi, and the ongoing work of the Restoration all share a single theme: His mission continues through His people. We are not spectators of salvation history — we are participants in it.",
      patterns: "The mission-transfer pattern is consistent: God gives a mission to Christ, Christ completes it and commissions His followers, and the work continues until He returns. This pattern connects to every week in this study — each topic is not just about what Christ did but about what we are invited to do because of Him.",
      reflection: "In what specific way is Christ's mission your mission this week? Not in the abstract — in the concrete reality of your relationships, your ward, your community?"
    }
  ]
};

export default week09;
