import type { WeekContent } from '../types';

const week34: WeekContent = {
  title: "Spirit of — The Light of Christ in All Things",
  subtitle: "Before the Gift of the Holy Ghost, there is a light that fills the immensity of space — and it proceeds from the presence of Christ.",
  weekScriptures: "Rom 8:9-11; Gal 5:22-25; 1 Jn 4:13; D&C 11:12-13; D&C 93:36; Jacob 4:13; Alma 34:38; 3 Ne 9:20; Moro 8:16; D&C 8:2-3; D&C 42:14",
  synthesis: {
    summary: "This week explores the Spirit of Christ — often called the Light of Christ — a divine influence that fills all creation and is given to every person born into the world. It is the source of conscience, moral intuition, and the capacity to recognize truth. It is distinct from the Gift of the Holy Ghost but works in concert with it. Understanding this doctrine reveals that God has not left any of His children without access to His light, and it provides a framework for understanding how truth is recognized across all cultures and traditions.",
    connections: [
      "The Light of Christ studied this week is the universal foundation upon which the more specific gift of the Holy Ghost (Week 35) builds.",
      "This connects to Week 1's study of Christ's cosmic scope — D&C 88 describes the same light that governs stars and gives life to all things.",
      "Understanding the Spirit of Christ illuminates Week 33's teaching that the Son reveals the Father — the Light of Christ is one means by which that revelation reaches every soul."
    ],
    teaching: "What is the difference between the Light of Christ and the Gift of the Holy Ghost? Why does it matter to distinguish them, and how do they work together?",
    commitment: "This week, pay attention to moments of moral clarity, sudden understanding, or quiet conviction. Consider whether you are experiencing the Light of Christ — and respond to it with gratitude."
  },
  days: [
    {
      label: "Light that fills all things",
      focus: "D&C 88 describes a light that proceeds from God's presence to fill the immensity of space. Today examines this extraordinary cosmological claim.",
      scriptures: [{book:"D&C",ch:88,vs:6,ve:13},{book:"John",ch:1,vs:9},{book:"D&C",ch:93,vs:2}],
      nuances: "D&C 88:12 says the light of Christ 'proceedeth forth from the presence of God to fill the immensity of space.' The word 'proceedeth' implies continuous action — not a one-time event but an ongoing emanation. This light is not static; it is actively flowing from God at all times, sustaining all things in real time.",
      commentary: "D&C 88:6–13 is one of the most remarkable passages in all scripture. It describes the light of Christ as the light of the sun, the light that gives life to all things, the power by which the earth and the stars are governed, and the law by which all things are organized. This is not metaphor — it is a doctrinal claim about the relationship between Christ and physical reality.\n\nJohn 1:9 teaches that Christ is 'the true Light, which lighteth every man that cometh into the world.' Every person, regardless of culture, era, or religious background, has access to this light. It is not exclusive to the baptized or the believing — it is a universal endowment of birth.\n\nD&C 93:2 adds a dimension of progressive revelation: 'every soul who forsaketh his sins and cometh unto me, and calleth on my name, and obeyeth my voice, and keepeth my commandments, shall see my face and know that I am.' The light that reaches everyone can, if followed, lead to the fulness of Christ's presence.\n\nThis doctrine has profound interfaith implications. Wherever truth, beauty, or goodness are found in any culture or tradition, the Latter-day Saint understanding is that the Light of Christ is their source. God has not abandoned any of His children to complete darkness.",
      patterns: "The Light of Christ is the cosmic dimension of what Week 1 introduced — Christ operating at every scale, from the structure of the universe to individual conscience. This week narrows from the cosmic to the personal over seven days.",
      reflection: "If the Light of Christ literally fills the immensity of space, what does that mean about God's accessibility? Is there any place you could go where His light does not reach?"
    },
    {
      label: "The moral light within",
      focus: "The Light of Christ is not only cosmological — it is moral. Today examines how it functions as conscience and moral discernment in every person.",
      scriptures: [{book:"Moro",ch:7,vs:16,ve:19},{book:"D&C",ch:84,vs:45,ve:48},{book:"John",ch:1,vs:9}],
      nuances: "In Moroni 7:16, Mormon describes how to judge between good and evil: 'the Spirit of Christ is given to every man, that he may know good from evil.' The word 'given' (not 'offered' or 'available') indicates that this is an active endowment, not a passive possibility. Every person has already received this gift simply by being born.",
      commentary: "Mormon's discourse in Moroni 7 provides the clearest explanation of how the Light of Christ functions in moral life. Everything that invites to do good, to love God, and to serve Him is inspired of God. Everything that persuades to do evil is of the devil. And the mechanism for discernment is the Spirit of Christ, given to every person.\n\nThis teaching has extraordinary implications. It means that the capacity for moral discernment is not limited to those who have heard the gospel. A person in any era, any nation, any circumstance has access to this inner light. When someone who has never read scripture recognizes cruelty as wrong and kindness as right, they are responding to the Light of Christ.\n\nD&C 84:45–48 adds a progressive dimension: the word of the Lord is truth, truth is light, and light is the Spirit of Jesus Christ. Those who hearken to this spirit come unto God and are taught by the covenant of the Father. There is a trajectory here — the Light of Christ is not an end point but a beginning. It is designed to lead people toward greater light, toward covenant, toward Christ Himself.\n\nThis is why missionaries often find that people in diverse cultures already recognize many true principles before they hear the restored gospel. The Light of Christ has been preparing them.",
      patterns: "The moral function of the Light of Christ connects to the Restoration doctrine of moral agency — every person must be able to choose between good and evil, and the Light of Christ provides the capacity for that choice. This is foundational to the plan of salvation studied in Weeks 8 and 9.",
      reflection: "Think of a time you felt an unmistakable inner sense that something was right or wrong, even before you could explain why. Was that the Light of Christ? How do you distinguish it from mere preference?"
    },
    {
      label: "Distinct from the Holy Ghost",
      focus: "The Spirit of Christ and the Gift of the Holy Ghost are related but distinct. Today carefully distinguishes them and shows how they work together.",
      scriptures: [{book:"John",ch:14,vs:16,ve:17},{book:"D&C",ch:46,vs:13,ve:14},{book:"Moro",ch:10,vs:4,ve:5}],
      nuances: "In John 14:16, Christ promises 'another Comforter' — the Greek 'allon paraklēton' means 'another of the same kind.' The Holy Ghost is like Christ — another advocate, another helper. The word 'another' implies distinction: the Spirit is not Christ Himself, but a being who continues Christ's work.",
      commentary: "One of the most important doctrinal distinctions in Restoration theology is between the Light of Christ (given to all) and the Gift of the Holy Ghost (given through covenant ordinance). They are not the same, though they work in harmony. The Light of Christ is universal — it gives every person moral intuition and the capacity to recognize truth. The Gift of the Holy Ghost is specific — it is conferred by the laying on of hands after baptism and provides a constant, personal companionship.\n\nJohn 14:16–17 records Christ promising another Comforter who would dwell with the disciples and be in them. This indwelling presence goes beyond the general Light of Christ — it is a personal, ongoing relationship with a member of the Godhead.\n\nD&C 46:13–14 illustrates how the Holy Ghost functions: some are given the gift of knowing that Jesus Christ is the Son of God, while others are given the gift of believing on their words. Both are operations of the Holy Ghost — specific, personal, identifiable gifts.\n\nMoroni 10:4–5 brings the two together beautifully. Moroni invites readers to ask God with sincere intent and faith in Christ, and promises that the Holy Ghost will manifest the truth. But the reader's ability to recognize and respond to that manifestation is itself a product of the Light of Christ already at work within them. The two are concentric — the Light of Christ prepares the soul, and the Holy Ghost confirms the truth.",
      patterns: "The distinction between the Light of Christ and the Gift of the Holy Ghost helps explain how truth can be found outside the covenant community while still affirming the unique power of covenant ordinances. Both originate in Christ.",
      reflection: "Have you ever felt the difference between a general sense that something is true and a specific, personal witness of the Holy Ghost? What distinguished the two experiences?"
    },
    {
      label: "The Spirit and truth",
      focus: "The Spirit of Christ leads to truth — all truth. Today examines the relationship between Christ's Spirit and the recognition of truth in every domain.",
      scriptures: [{book:"John",ch:16,vs:13},{book:"D&C",ch:84,vs:45,ve:48},{book:"1 Cor",ch:2,vs:10,ve:14}],
      nuances: "In John 16:13, 'he will guide you into all truth' uses the Greek 'hodēgesei' — literally 'he will lead the way.' The Spirit does not simply inform the mind; He leads the whole person along a path. Truth in scripture is not merely propositional; it is directional. It takes you somewhere.",
      commentary: "Christ promised that the Spirit of truth would guide His followers into all truth — not some truth, not only religious truth, but all truth. This is a sweeping claim. It suggests that every genuine discovery of truth — in science, philosophy, art, or any field — involves the Spirit of Christ at some level.\n\nD&C 84:45–48 makes the chain explicit: the word of the Lord is truth, and truth is light, and light is the Spirit of Jesus Christ. There is no secular truth and sacred truth — there is only truth, and its ultimate source is Christ. This understanding frees the Latter-day Saint from false dichotomies between faith and reason, religion and science.\n\nPaul's teaching in 1 Corinthians 2:10–14 adds an important qualification. The things of God are spiritually discerned — the natural man does not receive them. While the Light of Christ gives everyone access to basic truth and moral intuition, the deeper things of the Spirit require spiritual maturity and receptivity. There are layers to truth, and deeper layers require greater spiritual preparation.\n\nThis progressive revelation of truth — from the Light of Christ to the Gift of the Holy Ghost to the fulness of gospel knowledge — is one of the most hopeful doctrines in Restoration theology. God meets every person where they are and leads them forward.",
      patterns: "The principle that all truth originates in Christ connects to the Restoration's embrace of learning and education — 'the glory of God is intelligence' (D&C 93:36). This will connect to future weeks exploring Christ as the source of all wisdom.",
      reflection: "Have you ever had a moment of insight — in study, in nature, in conversation — that felt illuminated by something beyond your own reasoning? How might the Light of Christ be involved in your everyday learning?"
    },
    {
      label: "The still small voice",
      focus: "The Spirit of Christ often operates quietly. Today examines the scriptural pattern of divine communication through still, small impressions.",
      scriptures: [{book:"Hel",ch:5,vs:30},{book:"1 Cor",ch:2,vs:10,ve:14},{book:"2 Ne",ch:32,vs:5}],
      nuances: "Helaman 5:30 describes a voice that 'was not a voice of thunder, neither was it a voice of a great tumultuous noise, but behold, it was a still voice of perfect mildness, as if it had been a whisper, and it did pierce even to the very soul.' The verb 'pierce' (the original English captures the Book of Mormon's meaning) creates a paradox: extreme gentleness combined with penetrating power. Quiet and force are not opposites in divine communication.",
      commentary: "Helaman 5:30 records one of the most vivid descriptions of spiritual communication in all scripture. The Lamanites in the prison heard a voice — not loud, not dramatic, but still and mild, and it pierced their souls. Three times it spoke, and the earth shook. The quiet voice carried more power than any earthquake.\n\nThis pattern is consistent across scripture. Elijah encountered God not in the wind, the earthquake, or the fire, but in a still small voice (1 Kings 19:12). The Spirit of Christ characteristically operates through gentle impression rather than dramatic spectacle.\n\n1 Corinthians 2:10–14 teaches that the Spirit searches all things, even the deep things of God. The imagery is one of depth rather than volume — the Spirit's work is to go deep, not loud. Spiritual discernment requires attentiveness, not amplification.\n\n2 Nephi 32:5 promises that after receiving the Holy Ghost, we can speak with the tongue of angels and the Spirit will show us all things we should do. But this guidance comes through that same still, small process — not usually through visions or audible voices but through quiet impressions that require a listening heart.\n\nThe practical implication is that cultivating sensitivity to the Spirit is largely a matter of cultivating silence and stillness in a noisy world.",
      patterns: "The still small voice is the primary mode of ongoing revelation — from Elijah's experience to Nephi's promise to modern temple worship. God consistently chooses gentleness as His preferred frequency.",
      reflection: "When was the last time you created enough stillness in your life to hear a quiet prompting? What would need to change in your daily routine to make more room for the still small voice?"
    },
    {
      label: "The natural man and the Spirit",
      focus: "The Spirit of Christ invites us to put off the natural man. Today examines the tension between carnal nature and spiritual receptivity.",
      scriptures: [{book:"Mosiah",ch:3,vs:19},{book:"1 Cor",ch:2,vs:14},{book:"John",ch:6,vs:63}],
      nuances: "In Mosiah 3:19, the phrase 'natural man is an enemy to God' uses strong language. The word 'enemy' does not mean that God sees the natural man as an adversary to be destroyed, but that the natural condition — unregenerate, self-centered — operates in opposition to God's purposes. The remedy is not destruction but transformation: yielding to the enticings of the Holy Spirit.",
      commentary: "Mosiah 3:19 is one of the most important verses in the Book of Mormon. King Benjamin teaches that the natural man is an enemy to God and has been since the fall of Adam. But the verse does not end there — it prescribes the cure: yielding to the enticings of the Holy Spirit, putting off the natural man, and becoming a saint through the Atonement of Christ.\n\nThe key word is 'yielding.' It is not a violent suppression of our nature but a willing surrender to the Spirit's invitation. The Spirit of Christ does not override agency — it entices, invites, and draws. Our part is to yield.\n\nPaul makes a parallel argument in 1 Corinthians 2:14: the natural man does not receive the things of the Spirit of God because they are spiritually discerned. There is a mode of perception that the unrenewed mind simply cannot access. The Spirit of Christ opens that mode of perception, but the person must be willing to receive it.\n\nJohn 6:63 adds Christ's own declaration: 'It is the spirit that quickeneth; the flesh profiteth nothing.' The flesh — meaning the unredeemed, natural condition — cannot generate spiritual life. Only the Spirit can quicken, or make alive, the inner person.\n\nThis is not a rejection of the body or of mortal experience. It is a recognition that without the Spirit's transforming influence, mortality becomes a closed system incapable of reaching God.",
      patterns: "The tension between the natural man and the Spirit is a theme that runs from the Fall (Week 8) through the Atonement (Week 12) to sanctification (Week 24). The Spirit of Christ is the agent of transformation at every stage.",
      reflection: "King Benjamin says we must 'yield' to the enticings of the Spirit. What does yielding look like in your life right now? Is there a specific area where you sense the Spirit enticing you but the natural man is resisting?"
    },
    {
      label: "Transformed by the Spirit",
      focus: "The Spirit of Christ does not merely inform — it transforms. Today examines the doctrine of spiritual rebirth and the change wrought by the Spirit.",
      scriptures: [{book:"2 Cor",ch:3,vs:17,ve:18},{book:"Alma",ch:5,vs:14},{book:"Moro",ch:7,vs:48}],
      nuances: "In 2 Corinthians 3:18, 'we all, with open face beholding as in a glass the glory of the Lord, are changed into the same image from glory to glory, even as by the Spirit of the Lord.' The Greek 'metamorphoumetha' (are changed/transformed) is the root of 'metamorphosis.' Paul is describing not a superficial adjustment but a fundamental transformation of nature — and its agent is the Spirit.",
      commentary: "Paul's teaching in 2 Corinthians 3:17–18 is breathtaking in its scope. Where the Spirit of the Lord is, there is liberty. And those who behold the glory of the Lord are transformed into the same image, from glory to glory. The Spirit does not merely give information about Christ — it makes us like Christ. The process is gradual ('glory to glory') but real.\n\nAlma 5:14 asks the penetrating question: 'Have ye spiritually been born of God? Have ye received his image in your countenances? Have ye experienced this mighty change in your hearts?' Alma is not asking about theological opinion. He is asking about transformation — whether the Spirit of Christ has actually changed who you are at the deepest level.\n\nMoroni 7:48 brings the week to its devotional climax: pray with all the energy of heart that you may be filled with the love the Father has bestowed on true followers of His Son, that you may become sons of God, and that when Christ appears you shall be like Him. The ultimate work of the Spirit is not knowledge but transformation — being changed into Christ's likeness, being filled with His love, becoming what He is.\n\nThis is the fulfillment of the Light of Christ's purpose. It begins as a universal endowment of conscience and moral awareness. It deepens through the Gift of the Holy Ghost into personal companionship with God. And its end is complete transformation — a new creature, born of the Spirit, bearing the image of Christ.",
      patterns: "The trajectory from light to transformation to Christlikeness is the entire arc of the plan of salvation. This week's study of the Spirit of Christ connects to Week 32 (divine sonship), Week 33 (relationship with the Father), and forward to Week 36 (taking upon us the name of Christ).",
      reflection: "Paul says we are transformed 'from glory to glory.' Transformation is not instantaneous but progressive. Where are you in that process? What is the next step the Spirit is inviting you toward?"
    }
  ]
};

export default week34;
