import type { WeekContent } from '../types';

const week28: WeekContent = {
  title: "Messenger of the Covenant — Christ as Mediator and Covenant Maker",
  subtitle: "He is the messenger the Father sent to establish, fulfill, and mediate every saving covenant between God and humanity.",
  weekScriptures: "Gen 15:9–18; Ex 24:3–8; Deut 4:13; Jer 31:31–34; Ezek 37:26–28; Matt 26:28; Heb 7:22; Heb 8:8–13; Heb 10:16–17; Heb 13:20; D&C 22:1–4; D&C 66:2; D&C 76:69; 3 Ne 20:46; Morm 7:10",
  synthesis: {
    summary: "Jesus Christ is the central figure in every covenant God has made with humanity. He is the messenger Malachi prophesied would come suddenly to His temple, the mediator of a new and better covenant described in Hebrews, and the one through whom all the promises of the Abrahamic covenant are fulfilled. Without Christ, no covenant has power — He is the reason covenants work, the one who satisfies justice so that mercy can operate within the covenant relationship.",
    connections: [
      "Christ's role as Messenger of the Covenant connects to His temple ministry (Week 42) and to His role as High Priest (Week 17).",
      "The covenant framework explored this week is the foundation for understanding His titles as Advocate (Week 18) and Mediator.",
      "The Abrahamic covenant thread ties to the gathering of Israel and the Restoration themes in Weeks 44–47."
    ],
    teaching: "What is the difference between a contract and a covenant? How does understanding Christ as the mediator change your view of the covenants you have made?",
    commitment: "Choose one covenant you have made (baptismal, sacramental, temple) and spend time this week considering how Christ personally makes that covenant operative in your life."
  },
  days: [
    {
      label: "The messenger comes to His temple",
      focus: "Malachi prophesied a messenger who would come suddenly to the temple. Today examines this prophecy and its layered fulfillments.",
      scriptures: [{book:"Mal",ch:3,vs:1,ve:3},{book:"3 Ne",ch:20,vs:25,ve:26},{book:"D&C",ch:107,vs:19}],
      nuances: "Malachi 3:1 uses two distinct Hebrew terms: 'mal'aki' (my messenger, referring to the forerunner) and 'ha'adon' (the Lord) who comes to His temple. The phrase 'messenger of the covenant' ('mal'ak habrit') is unique in the Old Testament — it appears only here. The word 'suddenly' ('pit'om') carries a sense of unexpectedness and immediacy, suggesting that when the Lord comes to His temple, it will catch people off guard.",
      commentary: "Malachi's prophecy is the last prophetic voice in the Old Testament, and it points forward with urgency: the Lord will send His messenger to prepare the way, and then the Lord Himself — the messenger of the covenant — will come suddenly to His temple. The prophecy has multiple layers of fulfillment. John the Baptist was the forerunner who prepared the way. Christ came to the Jerusalem temple, cleansing it and teaching within its walls. And in Restoration context, Christ appeared in the Kirtland Temple on April 3, 1836 (D&C 110), literally coming suddenly to His temple.\n\nMalachi adds that this coming will be like a refiner's fire and like fullers' soap. The messenger of the covenant does not come to leave things as they are. He comes to purify, to burn away dross, to cleanse. This is an uncomfortable image for those who prefer a gentle, accommodating Christ. The messenger of the covenant demands transformation.\n\n3 Nephi 20:25–26 records the resurrected Christ Himself quoting the covenant God made with Abraham and declaring that the Nephites are children of that covenant. Christ personally connects the ancient Abrahamic promises to the people standing before Him — acting as the living messenger who bridges the covenant across millennia.\n\nD&C 107:19 describes the power of the Melchizedek Priesthood as enabling access to the mysteries of the kingdom and communion with God — a direct extension of Christ's mediating role. The priesthood is not separate from the covenant; it is the mechanism through which the covenant messenger's authority continues to operate.",
      patterns: "Malachi's prophecy follows the pattern of dual fulfillment common in messianic prophecy — a near fulfillment (John the Baptist, Christ's mortal ministry) and a latter-day fulfillment (the Kirtland Temple, the Second Coming). This layered fulfillment pattern appears throughout the prophetic tradition.",
      reflection: "Malachi says the messenger comes like refiner's fire. What in your life might the Lord be seeking to refine or purify through your covenant relationship with Him?"
    },
    {
      label: "Mediator of a better covenant",
      focus: "The book of Hebrews argues that Christ mediates a covenant that is categorically superior to the old. Today examines what makes the new covenant 'better.'",
      scriptures: [{book:"Heb",ch:8,vs:6},{book:"Heb",ch:9,vs:15},{book:"Heb",ch:12,vs:24}],
      nuances: "Hebrews 8:6 uses the Greek 'mesitēs' for mediator — a legal term for someone who stands between two parties to guarantee an agreement. Christ is not merely the messenger who delivers covenant terms; He is the guarantor who stands between God and humanity, ensuring the covenant is honored from both sides. He satisfies justice on humanity's behalf and extends mercy on God's behalf.",
      commentary: "The epistle to the Hebrews builds its entire argument around the superiority of the new covenant over the old, and Christ's role as mediator is the linchpin. Hebrews 8:6 declares that Christ has obtained a more excellent ministry because He is the mediator of a better covenant established upon better promises. The old covenant was not bad — it was divinely given — but it could not ultimately solve the problem of sin. Animal sacrifices pointed to Christ but could not replace Him.\n\nHebrews 9:15 explains why a mediator was necessary: because there had been transgressions under the first covenant that required a death to redeem them. The new covenant is not merely a revised set of rules — it is the provision of an actual redeemer whose death ratifies the agreement. Every covenant requires a sacrifice, and this covenant is ratified by the blood of God Himself.\n\nHebrews 12:24 presents Jesus as the mediator of the new covenant, and His sprinkled blood as speaking 'better things than that of Abel.' Abel's blood cried from the ground for vengeance. Christ's blood speaks mercy, forgiveness, and reconciliation. The comparison is stunning: the first blood shed in human history cried for justice; the blood of the Lamb cries for grace.\n\nThe concept of mediation is essential to covenant theology. A mediator does not merely deliver a message — he stands in the gap, absorbs the consequences of broken promises, and makes it possible for the relationship to continue despite human failure. This is precisely what Christ does in the Atonement.",
      patterns: "The Hebrews argument follows the lesser-to-greater pattern (qal va-chomer in rabbinical interpretation): if the old covenant with animal sacrifices had power, how much more the new covenant with the sacrifice of the Son of God. This interpretive method connects to Paul's broader typological reading of the Old Testament.",
      reflection: "A mediator stands between two parties. In what ways do you experience Christ standing between you and the demands of justice — absorbing the gap between who you are and who the covenant requires you to be?"
    },
    {
      label: "A covenant in His blood",
      focus: "At the Last Supper, Jesus established the new covenant in His blood. Today examines the institution of the sacrament as covenant renewal.",
      scriptures: [{book:"Luke",ch:22,vs:20},{book:"1 Cor",ch:11,vs:25},{book:"Mosiah",ch:5,vs:5,ve:8}],
      nuances: "Luke 22:20 records Jesus saying 'This cup is the new testament in my blood, which is shed for you.' The Greek 'diathēkē' is translated as both 'testament' and 'covenant' — it carries the sense of a unilateral arrangement established by the superior party for the benefit of the inferior party. Christ is not negotiating; He is bestowing. The covenant is a gift ratified by His own blood.",
      commentary: "The institution of the sacrament at the Last Supper is the moment when Christ formally established the new covenant in His blood. Luke and Paul both record His words: this cup is the new covenant in my blood. The timing is deliberate — the new covenant is instituted at Passover, connecting it to the blood of the Passover lamb that marked the doorposts in Egypt. The old covenant of Sinai, sealed with the blood of sacrificial animals (Exodus 24:8), gives way to the new covenant sealed with the blood of the Lamb of God.\n\nEvery time the sacrament is administered, the covenant is renewed. The prayers in Moroni 4 and 5 (and D&C 20:77,79) include explicit covenant language: the participants witness that they are willing to take upon themselves the name of Christ, always remember Him, and keep His commandments. In return, they are promised His Spirit. This is not a memorial meal alone — it is a covenant ceremony.\n\nKing Benjamin's people in Mosiah 5 provide a model of covenant making. After hearing Benjamin's sermon about the Atonement, they enter a covenant to do God's will and to be obedient. In response, Benjamin tells them they shall be called the children of Christ — they take upon themselves His name. This is what the covenant does: it changes your identity. You become His.\n\nThe covenant in His blood is simultaneously the most intimate and the most universal reality in the gospel. It is intimate because it involves your personal promise and His personal sacrifice. It is universal because it is offered to every soul who has ever lived.",
      patterns: "The blood-covenant pattern runs from the Abrahamic covenant (Gen 15, where animals are cut in two) through Sinai (Ex 24:8) to the Last Supper to the sacrament table. Each iteration deepens the meaning and extends the reach of the covenant.",
      reflection: "The next time you partake of the sacrament, you are renewing a covenant sealed by Christ's blood. How does that awareness change your experience of what might otherwise feel like a routine ordinance?"
    },
    {
      label: "A light and covenant to the nations",
      focus: "Isaiah portrays the Servant of the Lord as a covenant personified — given as a covenant to the people and a light to the Gentiles. Today explores this unique concept.",
      scriptures: [{book:"Isa",ch:42,vs:6,ve:7},{book:"Isa",ch:49,vs:8,ve:9},{book:"2 Ne",ch:11,vs:4,ve:5}],
      nuances: "In Isaiah 42:6, the Hebrew is striking: God says He will give the Servant 'livrit am, le'or goyim' — 'for a covenant of the people, for a light of the nations.' The Servant is not merely the bearer of a covenant — He is given as a covenant. He is the covenant embodied. This is a unique construction in the Hebrew Bible and suggests that Christ's very person, not just His words or actions, constitutes the covenant between God and humanity.",
      commentary: "Isaiah 42 and 49 present one of the most remarkable ideas in all of scripture: the Servant of the Lord is not just the messenger of the covenant but the covenant itself. God says, 'I will give thee for a covenant of the people.' Christ does not merely bring the covenant — He is the covenant. His life, His sacrifice, His resurrection, His ongoing mediation — these are not additions to the covenant; they are the substance of it.\n\nIsaiah 42:6–7 adds that this covenant-person will open blind eyes, bring prisoners out of the dungeon, and free those who sit in darkness. The covenant is not abstract — it liberates. It has tangible effects on real human suffering. When Christ healed the blind and freed the captive, He was not merely performing miracles; He was enacting the covenant.\n\nIsaiah 49:8–9 extends the promise: in a time of favor, God heard the Servant, and in a day of salvation, He helped Him. The Servant is then given as a covenant to the people to restore the land and redistribute the desolate inheritances. The covenant has both spiritual and material dimensions — it restores not only souls but communities, lands, and inheritances.\n\nNephi in 2 Nephi 11:4–5 expresses his delight that all things given by God from the beginning are a typification of Christ. This includes the covenants themselves. Every covenant in every dispensation is a type and shadow of the Person who is the ultimate covenant — Jesus Christ.",
      patterns: "The concept of a person being a covenant (not just making one) is unique to Isaiah's Servant Songs and has no parallel in ancient Near Eastern treaty literature. It suggests that covenant relationship with God is ultimately personal relationship with Christ — not adherence to a legal code but union with a living Person.",
      reflection: "If Christ Himself is the covenant — not just the maker of it — what does that mean about the nature of your covenant relationship with God? Is it primarily legal or personal?"
    },
    {
      label: "The oath and covenant of the priesthood",
      focus: "D&C 84 describes the oath and covenant of the Melchizedek Priesthood, with Christ as the ultimate priest and covenant guarantor. Today explores this Restoration distinctive.",
      scriptures: [{book:"D&C",ch:84,vs:33,ve:40},{book:"Heb",ch:8,vs:6},{book:"Alma",ch:34,vs:14}],
      nuances: "D&C 84:33 uses the phrase 'oath and covenant' — in ancient Israelite practice, an oath ('shevu'ah') invoked God as witness and guarantor. When God Himself swears an oath (as in the Abrahamic covenant and the Melchizedek Priesthood), He swears by Himself because there is none greater (Heb 6:13). The oath and covenant of the priesthood is thus guaranteed by God's own character — it cannot fail unless the human party breaks it.",
      commentary: "D&C 84:33–40 lays out what is commonly called the oath and covenant of the priesthood. Those who faithfully magnify their callings are sanctified by the Spirit, receive the Father's kingdom, and become the elect of God. The promises are extraordinary in scope — they extend to receiving all that the Father has.\n\nBut the mechanism that makes this covenant operative is Christ. He is the great High Priest after the order of Melchizedek (Hebrews 7), and the priesthood that bears that name derives its power from Him. Without Christ's mediation, the priesthood covenant would be an empty promise — there would be no power to sanctify, no means to access the Father, no way to receive His kingdom.\n\nHebrews 8:6 reiterates that Christ's ministry is more excellent precisely because He mediates a better covenant. The Melchizedek Priesthood, restored through the Restoration, operates under this better covenant. Those who receive this priesthood enter into a covenant relationship that Christ personally guarantees.\n\nAlma 34:14 reminds us of the foundation: the whole meaning of the law points to the great and last sacrifice of the Son of God. The priesthood, the ordinances, the covenants — all of them are channels through which the power of Christ's sacrifice flows to individuals. Without the Lamb, the covenant structure collapses. With the Lamb, it becomes the mechanism by which mortals receive the fullness of the Father.\n\nThe covenant of the priesthood is not merely an obligation but an invitation into a relationship guaranteed by the most powerful Being in the universe.",
      patterns: "The oath-and-covenant structure appears in the Abrahamic covenant (Gen 22:16–18), the Davidic covenant (Ps 89:3–4), and the Melchizedek Priesthood (D&C 84). Each instance involves God binding Himself by oath — a remarkable act of condescension by the supreme sovereign.",
      reflection: "The oath and covenant of the priesthood promises 'all that the Father hath.' What does that promise mean to you, and what does it require of you in return?"
    },
    {
      label: "The Abrahamic covenant fulfilled in Christ",
      focus: "Every promise God made to Abraham finds its ultimate fulfillment in Jesus Christ. Today traces the Abrahamic covenant through to its christological center.",
      scriptures: [{book:"Gen",ch:17,vs:1,ve:7},{book:"3 Ne",ch:20,vs:25,ve:26},{book:"Gal",ch:3,vs:16}],
      nuances: "In Galatians 3:16, Paul makes a specific grammatical argument: the Abrahamic promises were made to Abraham and his 'seed' (Greek: 'spermati,' singular) — not 'seeds' (plural). Paul identifies this singular seed as Christ. While modern scholars debate the force of this argument, Paul's theological point is clear: the Abrahamic covenant ultimately converges on one Person, and through that Person it extends to all who belong to Him.",
      commentary: "God's covenant with Abraham in Genesis 17 promised descendants as numerous as the stars, a land of inheritance, and the blessing of all nations through his seed. These promises have been understood literally, nationally, and spiritually across Jewish and Christian traditions. Paul's interpretation in Galatians 3:16 cuts to the christological center: the seed of Abraham through whom all nations are blessed is Christ.\n\nThis means the Abrahamic covenant is not merely a national promise to Israel — it is a messianic promise fulfilled in Jesus. Every family of the earth that is blessed through Abraham's seed is blessed because of what Christ has done. The Abrahamic covenant is, at its core, a covenant about the Atonement.\n\n3 Nephi 20:25–26 records the resurrected Christ making this connection explicit to the Nephites. He tells them they are children of the covenant God made with Abraham, and that the Father has raised up His Servant Jesus to bless them by turning them from their iniquities. Christ is simultaneously the fulfillment of the Abrahamic promise and the active agent of its ongoing administration.\n\nRestoration theology adds distinctive dimensions: the gathering of Israel (a key Abrahamic promise) is occurring in the latter days as people enter the covenant through baptism and temple ordinances. Every person who enters the gospel covenant becomes a child of Abraham — not by blood but by covenant (Abraham 2:10). Christ is the doorway through which all people, regardless of lineage, enter the Abrahamic family.",
      patterns: "The Abrahamic covenant unfolds progressively through scripture: established in Genesis, reiterated to Isaac and Jacob, fulfilled partially in the Exodus, prophesied by Isaiah and Jeremiah, identified with Christ by Paul, and extended to all nations through the Restoration. Christ is the thread that holds every stage together.",
      reflection: "Through the gospel covenant, you are a child of Abraham regardless of your ancestry. How does being part of this ancient covenant family shape your sense of identity and mission?"
    },
    {
      label: "Come unto Christ and be perfected",
      focus: "The covenant culminates in an invitation. Today synthesizes the week with Moroni's closing appeal and the covenant's ultimate purpose: bringing us to Christ.",
      scriptures: [{book:"Moro",ch:10,vs:33},{book:"D&C",ch:84,vs:38},{book:"Heb",ch:12,vs:24}],
      nuances: "Moroni 10:33 uses the phrase 'come unto Christ and be perfected in him.' The word 'perfected' translates a concept that in Greek ('teleiōthēte') and Hebrew ('tamim') means completion, wholeness, reaching one's intended end — not flawlessness. The covenant's purpose is not to make you faultless but to make you complete through union with Christ.",
      commentary: "Moroni's final invitation is the capstone of the entire Book of Mormon: come unto Christ and be perfected in Him. After a thousand years of Nephite history, after wars and prophecies and civilizations rising and falling, the last prophet on the record distills everything into this single appeal. The covenant exists for one purpose: to bring you to Christ and to make you whole in Him.\n\nThis is the telos — the end, the purpose — of every covenant explored this week. Malachi's messenger comes to purify so that people can stand in God's presence. The mediator of the new covenant stands in the gap so that relationship with God is possible. The blood of the covenant seals the promises. The priesthood covenant channels divine power. The Abrahamic covenant extends the family of God to all nations. All of it — every thread — converges on the personal invitation to come to Christ.\n\nD&C 84:38 promises that those who receive the Father's servants receive the Father Himself — and all that the Father has. This is the ultimate covenant promise: not merely forgiveness, not merely improvement, but participation in the divine nature, receiving the fullness of the Father through the mediation of the Son.\n\nHebrews 12:24 provides the final image: Jesus, the mediator of the new covenant, and the blood of sprinkling that speaks better things than the blood of Abel. Abel's blood cried out for judgment. The blood of the covenant messenger speaks mercy, reconciliation, and eternal life. The last word of the covenant is not demand — it is invitation. Come. Be made whole. Be His.",
      patterns: "The entire Book of Mormon follows an arc from Lehi's departure (leaving behind a broken covenant people) to Moroni's final invitation (calling all people into covenant with Christ). The messenger of the covenant is the constant throughout: Christ is the reason Lehi left, the subject of Nephi's visions, the focus of Alma's preaching, the visitor in 3 Nephi, and the object of Moroni's closing plea.",
      reflection: "Moroni's invitation to 'come unto Christ and be perfected in him' is the final word of the Book of Mormon. If this is the most important message of the entire record, how are you responding to it today?"
    }
  ]
};

export default week28;
