import type { WeekContent } from '../types';

const week19: WeekContent = {
  title: "Exemplar — The Perfect Pattern",
  subtitle: "Christ is not only the Savior who rescues us but the Exemplar who shows us how to live — the pattern for every virtue, every relationship, and every response to suffering.",
  weekScriptures: "1 Pet 2:21–23; John 13:12–17; Matt 20:26–28; Philip 2:5–8; John 14:6; 3 Ne 12:48; 3 Ne 27:27; Matt 11:29; Matt 5:44–48; Luke 23:34; John 15:12–13; Heb 12:1–3; 1 Jn 2:6; 2 Ne 31:4–10; Mosiah 3:19; Moro 7:48; D&C 19:16–19; Alma 7:11–13; Matt 26:39; John 5:19–20; Ether 12:4",
  synthesis: {
    summary: "Christ is the perfect example — not merely in the sense that He avoided sin, but in the active sense that He demonstrated the right way to pray, serve, suffer, forgive, love, and submit to the Father's will. His example is not an impossible standard meant to discourage but a living pattern meant to be followed. He said 'Follow me,' and then walked the path first so we could see where to put our feet. This week examines the specific ways Christ exemplified the life He invites us to live.",
    connections: [
      "Christ as Exemplar depends on His condescension (Week 1) — only by becoming mortal could He show us how to live mortality.",
      "His example of suffering connects to His Atonement (Weeks 12-13) — He did not merely endure suffering; He sanctified it as a pathway to redemption.",
      "Following His example leads to the transformation explored in the glory of Christ (Week 17) — we become like what we consistently behold and imitate."
    ],
    teaching: "Which aspect of Christ's example is easiest for you to follow, and which is hardest? What does the gap reveal about your next step in discipleship?",
    commitment: "Choose one specific aspect of Christ's example studied this week — humility, service, forgiveness, or submission to God's will — and consciously practice it each day."
  },
  days: [
    {
      label: "Called to follow His steps",
      focus: "Christ did not merely command; He demonstrated. Today establishes the foundational principle that His life is a pattern for ours.",
      scriptures: [{book:"1 Pet",ch:2,vs:21,ve:23},{book:"1 Jn",ch:2,vs:6},{book:"3 Ne",ch:27,vs:27}],
      nuances: "Peter's word in 1 Peter 2:21 — 'leaving us an example, that ye should follow his steps' — uses the Greek 'hypogrammon,' which referred to the faint letters a writing teacher would trace for a student to write over. Christ's life is the pattern written lightly beneath our own, and discipleship is the process of tracing His lines. The metaphor implies both closeness and effort: you must look carefully and follow precisely.",
      commentary: "Peter writes to Christians under persecution, and his counsel is remarkable: Christ suffered for you, leaving an example that you should follow His steps. The example is not abstract moral perfection but specific behavior under specific pressure. When He was reviled, He did not revile back. When He suffered, He did not threaten. He committed Himself to the Father. This is a pattern for enduring injustice — not with passivity or resignation but with dignified trust in God's judgment.\n\nJohn's instruction in 1 John 2:6 makes the principle universal: 'He that saith he abideth in him ought himself also so to walk, even as he walked.' The claim of discipleship carries an obligation of imitation. You cannot say you belong to Christ and then live as though His life is irrelevant to yours. To abide in Him is to walk as He walked.\n\n3 Nephi 27:27 records the Savior's own summary: 'What manner of men ought ye to be? Verily I say unto you, even as I am.' This is the most direct statement of the exemplar principle in all of scripture. The standard is not a set of rules or a list of prohibitions but a person. The question of discipleship is not 'What should I do?' but 'What would He do?' — and then, more precisely, 'What did He actually do?'\n\nThe rest of this week explores specific dimensions of that example: humility, service, forgiveness, love, submission, and endurance.",
      patterns: "The call to follow Christ's example is echoed by Paul ('Be ye followers of me, even as I also am of Christ,' 1 Corinthians 11:1), by Nephi (who is baptized to 'follow the example of the Son,' 2 Nephi 31:16), and by Mormon ('follow Jesus Christ,' Mormon 7:10). Every dispensation emphasizes imitation as the method of discipleship.",
      reflection: "Peter says Christ left you a pattern to trace. In what area of your life are you most carefully tracing His pattern, and in what area have you wandered farthest from it?"
    },
    {
      label: "The example of humility",
      focus: "Christ, the God of the universe, washed feet and took the form of a servant. Today examines humility as the foundation of His entire example.",
      scriptures: [{book:"John",ch:13,vs:12,ve:17},{book:"Philip",ch:2,vs:5,ve:8},{book:"Mosiah",ch:3,vs:19}],
      nuances: "Philippians 2:7 says Christ 'made himself of no reputation, and took upon him the form of a servant.' The Greek 'ekenōsen' (emptied himself) is the root of the theological term 'kenosis.' It describes a voluntary self-emptying — not a loss of divine nature but a willing renunciation of divine prerogatives. Christ did not stop being God; He chose to live as though He were not. This is the deepest possible form of humility: having all power and choosing not to use it for yourself.",
      commentary: "The foot-washing in John 13 is one of the most vivid demonstrations of humility in all of scripture. Jesus, knowing that He came from God and was going to God — at the height of His awareness of His own divine identity — takes a towel, kneels, and washes His disciples' dirty feet. The timing is deliberate: He does the most menial act at the moment of greatest self-knowledge. True humility is not ignorance of your own worth; it is choosing to serve despite full knowledge of it.\n\nPaul's hymn in Philippians 2:5-8 describes the arc of Christ's humility in cosmic terms: He was in the form of God, He emptied Himself, He took the form of a servant, He was made in the likeness of men, He humbled Himself, He became obedient unto death — even the death of the cross. Each phrase descends further. The movement is relentlessly downward, from the highest possible position to the lowest possible experience. This is the opposite of every human instinct for self-promotion.\n\nKing Benjamin's teaching in Mosiah 3:19 connects this to discipleship: the natural man is an enemy to God 'unless he yields to the enticings of the Holy Spirit, and putteth off the natural man and becometh a saint through the atonement of Christ the Lord, and becometh as a child, submissive, meek, humble, patient.' The list of qualities — submissive, meek, humble, patient — reads like a character sketch of Christ Himself. To put off the natural man is to put on the character of Christ. His humility is not merely admired; it is the template for our transformation.",
      patterns: "The downward movement of Philippians 2 (God to servant to death) reverses the upward movement of human ambition. This 'great reversal' pattern appears throughout scripture: the last shall be first, the servant shall be greatest, and the cross becomes a throne. Christ's humility redefines power.",
      reflection: "Jesus washed feet knowing He was God. Where in your life do you resist serving because you feel it is beneath you? What would Christ's example look like in that situation?"
    },
    {
      label: "The example of service",
      focus: "Christ defined leadership as service and demonstrated it throughout His ministry. Today explores service as the central pattern of His life.",
      scriptures: [{book:"Matt",ch:20,vs:26,ve:28},{book:"John",ch:5,vs:19,ve:20},{book:"Matt",ch:11,vs:29}],
      nuances: "In Matthew 20:28, 'the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many,' the Greek 'diakonēsai' (to minister/serve) is the root of 'deacon.' Christ describes His entire mission — including His atoning death — as service. The ransom language ('lytron') was used for the price paid to free a slave. His ultimate act of service was to pay the price for human freedom with His own life.",
      commentary: "Matthew 20:26-28 overturns the world's understanding of greatness. The disciples had been jockeying for position — who would sit at Christ's right hand? Jesus' response redefines the entire category: 'Whosoever will be great among you, let him be your minister; and whosoever will be chief among you, let him be your servant.' In the kingdom of God, authority flows downward. The greatest is not the one with the most power but the one who serves the most people.\n\nJohn 5:19-20 reveals the source of Christ's service: 'The Son can do nothing of himself, but what he seeth the Father do.' Christ's service is not independent initiative but perfect responsiveness to the Father. He watches what the Father does and imitates it. This is the deepest form of service — not self-directed benevolence but God-directed obedience. Christ serves because the Father serves. His example invites us into the same orientation: service as an expression of our relationship with God, not our own virtue.\n\nMatthew 11:29 adds the personal invitation: 'Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.' A yoke is a work tool — it implies shared labor, not passive observation. Christ invites us to work alongside Him, learning His way of being in the world: meek and lowly in heart. The promise is that this way of living produces rest, not exhaustion. Service modeled on Christ's example is sustainable because it flows from a relationship with God, not from human willpower alone.",
      patterns: "The servant-leader pattern appears in Moses (the most meek man on earth, Numbers 12:3), in Nephi (who served his brothers despite their hostility), and in Joseph Smith (who said 'I teach them correct principles, and they govern themselves'). Every great prophet embodies Christ's service pattern.",
      reflection: "Christ said He came 'not to be ministered unto, but to minister.' In your roles — at home, at work, in the Church — are you primarily seeking to be served or to serve? What would shift if you adopted Christ's orientation?"
    },
    {
      label: "The example of forgiveness",
      focus: "From the cross, with nails in His hands, Christ forgave. Today examines the most radical act of forgiveness in history and what it means for us.",
      scriptures: [{book:"Luke",ch:23,vs:34},{book:"Matt",ch:5,vs:44,ve:48},{book:"3 Ne",ch:12,vs:48}],
      nuances: "Luke 23:34 — 'Father, forgive them; for they know not what they do' — is notable for several reasons. First, Jesus prays for His executioners' forgiveness rather than His own comfort. Second, He provides the reason: 'they know not what they do.' He extends interpretive charity to those who are killing Him, attributing their cruelty to ignorance rather than malice. Third, the imperfect tense in some manuscripts ('He was saying') suggests He said this repeatedly, not just once.",
      commentary: "Christ's prayer from the cross is the definitive example of forgiveness. He does not forgive after the offense has ended, from a position of safety and reflection. He forgives during the offense, while it is being inflicted. This is forgiveness at its most radical — not a decision made in calm retrospect but a posture maintained in active agony.\n\nThe Sermon on the Mount provides the teaching that the cross enacts: 'Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you' (Matthew 5:44). On the cross, Jesus does exactly what He taught. He loves His enemies. He prays for those who persecute Him. The consistency between His teaching and His practice is total.\n\nMatthew 5:48 gives the purpose: 'Be ye therefore perfect, even as your Father which is in heaven is perfect.' The Nephite version in 3 Nephi 12:48 adds a significant phrase: 'even as I, or your Father who is in heaven is perfect.' Having completed His mortal mission — including the Atonement, the cross, and the resurrection — Christ now includes Himself in the standard of perfection. His example of forgiveness is not a nice idea but a component of perfection itself. You cannot be complete without learning to forgive as He forgave.\n\nThis is perhaps the hardest aspect of Christ's example to follow. Forgiving those who have deeply hurt you requires a kind of death — a death of the claim to justified resentment. But it is precisely this death that Christ both exemplified and empowers.",
      patterns: "The forgiveness pattern in scripture escalates: Joseph forgives his brothers (Genesis 50:19-21), Stephen forgives his killers (Acts 7:60), and Christ forgives from the cross. Each instance expands the scope and depth of what forgiveness can include. The pattern culminates in Christ, who forgives the entire human race.",
      reflection: "Christ forgave while still suffering. Is there someone you have been waiting to forgive until the pain subsides? What would it look like to forgive in the midst of the pain, as Christ did?"
    },
    {
      label: "The example of love",
      focus: "Christ did not merely teach about love; He defined it by His life and death. Today examines love as the essence of His example.",
      scriptures: [{book:"John",ch:15,vs:12,ve:13},{book:"Moro",ch:7,vs:48},{book:"John",ch:14,vs:6}],
      nuances: "John 15:13 — 'Greater love hath no man than this, that a man lay down his life for his friends' — uses 'tithēmi' (to lay down, to place deliberately). This is not accidental death or martyrdom by circumstance but intentional sacrifice. The act of laying down one's life is presented as the ceiling of love — there is no higher expression. And Christ calls those for whom He dies 'friends' (philoi), a term of deep affection and equality.",
      commentary: "Christ's declaration in John 15:12-13 establishes the standard for love: willingness to lay down your life for others. This is not emotional warmth or romantic feeling but costly, self-giving action. Love, in Christ's definition, is measured by what you are willing to sacrifice, not by what you feel. And He set the standard at the maximum possible cost.\n\nMoroni 7:48 provides the Book of Mormon's great invitation: 'Pray unto the Father with all the energy of heart, that ye may be filled with this love, which he hath bestowed upon all who are true followers of his Son, Jesus Christ.' Mormon and Moroni call this love 'charity, the pure love of Christ.' The phrase 'pure love of Christ' can mean both the love that Christ has and the love that comes from Christ. Charity is not something you generate through effort alone; it is something bestowed through prayer and discipleship. You ask for it, and God gives it.\n\nJohn 14:6 — 'I am the way, the truth, and the life' — connects directly to the exemplar theme. Christ is not merely pointing to the way; He is the way. He does not merely teach the truth; He is the truth. He does not merely promise life; He is the life. His example is not external instruction but personal embodiment. To follow Him is not to follow a set of directions but to follow a person who is the destination.\n\nThe love Christ exemplified is comprehensive: He loved the sick, the sinful, the outcast, the enemy, the stranger, and the friend. He loved in words and in silence, in public miracles and in private prayers. His love was not selective or conditional but universal and complete.",
      patterns: "The love pattern culminates in two great commandments: love God and love your neighbor (Matthew 22:37-39). Christ exemplified both simultaneously — His love for the Father expressed itself as love for the Father's children. This dual orientation of love upward and outward is the pattern for all Christian living.",
      reflection: "Mormon says charity is 'bestowed' on true followers of Christ. Have you prayed for the gift of charity — not just the desire to love but the actual capacity to love as Christ loves?"
    },
    {
      label: "The example of submission",
      focus: "In Gethsemane, Christ showed us the hardest act of discipleship: submitting to the Father's will when every natural impulse resists. Today examines submission as the crown of His example.",
      scriptures: [{book:"Matt",ch:26,vs:39},{book:"D&C",ch:19,vs:16,ve:19},{book:"2 Ne",ch:31,vs:4,ve:10}],
      nuances: "Matthew 26:39 — 'O my Father, if it be possible, let this cup pass from me: nevertheless not my will, but thine, be done' — reveals the genuine human struggle within Christ. The word 'nevertheless' (Greek 'plēn') is a strong adversative, marking a sharp turn from natural desire to deliberate choice. Christ does not pretend the cup is easy. He asks for it to be removed. Then He overrides His own preference with submission. The honesty of the struggle makes the submission more, not less, meaningful.",
      commentary: "Gethsemane is the supreme example of submission. Matthew 26:39 records a prayer of raw honesty: Christ does not want to drink the cup. He asks His Father if there is another way. This is not weakness — it is authentic human experience. He felt the full weight of what was coming and still chose obedience. The phrase 'not my will, but thine, be done' is the most important sentence in human history. Everything that follows — the Atonement, the cross, the resurrection, the salvation of the human family — depends on this moment of submission.\n\nD&C 19:16-19 provides the only first-person account of Gethsemane from Christ Himself: 'Which suffering caused myself, even God, the greatest of all, to tremble because of pain, and to bleed at every pore, and to suffer both body and spirit — and would that I might not drink the bitter cup, and shrink.' The word 'shrink' is devastating in its honesty. The God of the universe shrank from what He was about to endure. And then He did it anyway: 'Nevertheless, glory be to the Father, and I partook and finished my preparations unto the children of men.' The 'nevertheless' echoes Matthew 26:39 — it is the pivot point of history.\n\nNephi's account in 2 Nephi 31:4-10 of Christ's baptism adds another dimension. Christ, who was without sin, submitted to baptism to 'fulfil all righteousness' and to show the way. His baptism was not for the remission of sins but as an example of obedience and humility. Even where the commandment does not technically apply to Him, He submits — showing that obedience is the pattern regardless of personal exemption.\n\nChrist's submission is not the abdication of a weak will but the exercise of an infinitely strong will aligned with the Father's. This is the example: not passive resignation but active, costly, chosen obedience.",
      patterns: "The pattern of submission — 'not my will, but thine' — runs from Abraham on Moriah to Joseph in Egypt to Job on the ash heap to Mary at the Annunciation to Christ in Gethsemane. In every case, submission produces outcomes that self-will could never have achieved.",
      reflection: "Christ said 'not my will, but thine' at the moment of greatest suffering. Is there a 'cup' in your life — a circumstance you would rather avoid — where you need to practice this same submission?"
    },
    {
      label: "Following the Exemplar forward",
      focus: "Christ's example is not a museum piece but a living pattern. Today asks: what does it mean to follow His example now, in your actual life?",
      scriptures: [{book:"Heb",ch:12,vs:1,ve:3},{book:"Alma",ch:7,vs:11,ve:13},{book:"Ether",ch:12,vs:4}],
      nuances: "Hebrews 12:2 calls Jesus 'the author and finisher of our faith.' The Greek 'archēgos' (author/pioneer/originator) and 'teleiōtēs' (completer/perfecter) describe someone who both begins and completes a journey. Christ is not only the example who started the path of faith; He is the one who finishes it in us. We do not follow His example by our own strength alone — He is both the pattern and the power to follow it.",
      commentary: "Hebrews 12:1-3 sets the example of Christ within the context of a great race. Surrounded by a 'cloud of witnesses' — all the faithful who have gone before — we are told to 'run with patience the race that is set before us, looking unto Jesus the author and finisher of our faith.' The image is of a runner who keeps their eyes fixed on the one who has already crossed the finish line. Christ is ahead of us, not behind us. He is not merely giving instructions from the sideline; He has run the course Himself and is now beckoning us forward.\n\nAlma 7:11-13 returns as a crucial text for this week's theme. Christ took upon Himself pains, afflictions, temptations, sickness, and death so that He would know 'according to the flesh how to succor his people.' His mortal experience was not merely an example to observe but an education in empathy. Because He has experienced everything you will face, His example is not that of a detached instructor but of a companion who has walked the same road.\n\nEther 12:4 closes the week with hope: 'Wherefore, whoso believeth in God might with surety hope for a better world, yea, even a place at the right hand of God, which hope cometh of faith, maketh an anchor to the souls of men.' Following Christ's example is not a grim duty but a hopeful journey. The destination is 'a place at the right hand of God,' and the hope of that destination anchors the soul through every trial along the way.\n\nThe week ends where it must: with an invitation. Christ has demonstrated humility, service, forgiveness, love, submission, and endurance. He has walked the path from beginning to end. He now stands at the end of that path and says, as He has always said, 'Follow me.'",
      patterns: "The cloud of witnesses in Hebrews 12 connects to the great chain of prophets who testified of Christ (Week 1, Day 3). Each faithful life is both a response to Christ's example and an example for those who follow. You are part of the chain — those who come after you will look to your faithfulness as part of their cloud of witnesses.",
      reflection: "Hebrews says to 'run with patience the race that is set before us, looking unto Jesus.' As you finish this week, what is the next step in your race? What aspect of Christ's example are you being invited to follow more closely?"
    }
  ]
};

export default week19;
