import type { WeekContent } from '../types';

const week36: WeekContent = {
  title: "Taking the Name of — Covenant Identity in Christ",
  subtitle: "To take upon us the name of Christ is not a formality — it is a transformation of identity, loyalty, and belonging.",
  weekScriptures: "Mosiah 5:7–12; Mosiah 18:8–10; Moro 4:3; Moro 5:2; D&C 20:77; D&C 20:79; 2 Ne 31:13; Acts 11:26; Mosiah 26:18; D&C 18:21–25; 3 Ne 27:5–8; King Benjamin discourse Mosiah 2–5; Philip 2:9–11; Alma 34:38; Gal 3:26–29; Col 3:17; Mosiah 1:11–12",
  synthesis: {
    summary: "This week explores the profound covenant act of taking upon ourselves the name of Jesus Christ. This happens at baptism, is renewed each week at the sacrament, and shapes every dimension of the disciple's life. Taking His name means accepting His identity as our own — becoming His people, bearing His cause, and representing Him in the world. It is the covenantal entry point into the divine relationship studied in preceding weeks and the practical expression of everything we have learned about Christ's nature, His Spirit, and His invitation to know Him.",
    connections: [
      "Week 32's study of divine sonship finds its covenantal counterpart here — Christ's sonship opens the way for us to become children of God through covenant.",
      "Taking the name of Christ is the practical expression of the unity with God studied in Week 33 — we enter the Father-Son relationship by covenant.",
      "This connects forward to Week 37's study of Christ as the Head of the Church — the community of those who have taken His name."
    ],
    teaching: "What does it mean to 'take upon you the name of Christ'? Is it different from simply believing in Him or attending church? How does the sacrament renew this covenant weekly?",
    commitment: "This week, pay attention during the sacrament prayers. Listen to the specific covenantal language. Ask yourself: Am I genuinely willing to take His name upon me — not as a label, but as an identity?"
  },
  days: [
    {
      label: "A new name given",
      focus: "King Benjamin's people received a new name — the name of Christ — through covenant. Today examines the original context and power of this naming.",
      scriptures: [{book:"Mosiah",ch:5,vs:7,ve:12},{book:"Mosiah",ch:1,vs:11,ve:12}],
      nuances: "In Mosiah 5:7, 'ye shall be called the children of Christ, his sons and his daughters,' the word 'called' carries covenantal weight in Hebrew thought. To be 'called by a name' is to belong to the one whose name you bear. It implies ownership, protection, and identity — not merely a label but a relationship.",
      commentary: "Mosiah 5:7–12 records one of the most powerful covenant moments in the Book of Mormon. After hearing King Benjamin's extraordinary sermon, the people experienced a mighty change of heart and declared their willingness to enter a covenant with God. Benjamin then gave them a name — the name of Christ — and told them it would never be blotted out except through transgression.\n\nThe context matters enormously. In Mosiah 1:11–12, Benjamin explains that one purpose of the great assembly was to give his people a name that would distinguish them from all other people. This name was not 'Nephite' or 'Benjamin's people' but the name of Christ. Their primary identity was to be found not in nation, tribe, or king but in their covenant relationship with the Savior.\n\nBenjamin warns in Mosiah 5:11–12 that those who transgress and do not repent will find the name blotted out. This is not punitive but relational — if you cease to act as a child of Christ, the name no longer describes you. The covenant is living; it requires ongoing faithfulness.\n\nThe power of this naming ceremony lies in its transformation of identity. Before the covenant, they were subjects of a king. After, they were children of Christ. Everything changed — not their circumstances, but who they understood themselves to be.",
      patterns: "The pattern of receiving a new name through covenant echoes throughout scripture — Abram becoming Abraham, Jacob becoming Israel, Saul becoming Paul. God renames those who enter into covenant with Him, and the new name signals a new identity and mission.",
      reflection: "King Benjamin's people received a new identity through covenant. If someone asked you who you are — not what you do, but who you are — would 'a covenant child of Christ' be among your first answers?"
    },
    {
      label: "Baptismal covenant",
      focus: "Baptism is the ordinance where we formally take upon us the name of Christ. Today examines the baptismal covenant as Alma taught it at the waters of Mormon.",
      scriptures: [{book:"Mosiah",ch:18,vs:8,ve:10},{book:"2 Ne",ch:31,vs:13},{book:"D&C",ch:18,vs:21,ve:25}],
      nuances: "In Mosiah 18:8, the series of questions Alma asks begins with 'as ye are desirous to come into the fold of God, and to be called his people.' The word 'fold' (Hebrew imagery of a sheep pen) implies protection, community, and belonging under a shepherd's care. To be called His people is to enter His fold — to belong to Christ in the way sheep belong to their shepherd.",
      commentary: "Alma's baptismal covenant at the waters of Mormon is the most detailed description of baptismal obligations in all scripture. Those who enter the covenant agree to bear one another's burdens, mourn with those who mourn, comfort those who need comfort, and stand as witnesses of God at all times, in all things, and in all places. The covenant is simultaneously vertical (with God) and horizontal (with fellow believers).\n\nThe reciprocal promise is extraordinary: God will pour out His Spirit more abundantly upon them, and they will be numbered among those of the first resurrection and have eternal life. The exchange is radically asymmetric — we offer our willingness and obedience, and God offers His Spirit and eternal life.\n\n2 Nephi 31:13 adds the witness of fire and the Holy Ghost that accompanies baptism. Taking the name of Christ is not merely a legal designation — it comes with spiritual power. The Holy Ghost seals the covenant and begins the transformation that the name represents.\n\nD&C 18:21–25 commands the modern Church to take upon them the name of Christ with full purpose of heart. The Lord warns that those who do not take His name with full purpose must repent. This is not a casual label — it is a solemn commitment that demands sincerity.",
      patterns: "The baptismal covenant connects backward to the Abrahamic covenant and forward to temple covenants. Each builds on the previous. Taking the name of Christ at baptism is the foundation for every subsequent covenant relationship.",
      reflection: "Alma's covenant includes mourning with those who mourn and comforting those who need comfort. How well does your daily life reflect these specific baptismal promises? Who might need you to fulfill this covenant this week?"
    },
    {
      label: "Renewed at the sacrament",
      focus: "The sacrament is the weekly renewal of the covenant to take upon us Christ's name. Today examines the sacrament prayers with careful attention.",
      scriptures: [{book:"Moro",ch:4,vs:3},{book:"Moro",ch:5,vs:2},{book:"D&C",ch:20,vs:77}],
      nuances: "In Moroni 4:3, the phrase 'willing to take upon them the name of thy Son' uses 'willing' — not 'they do take' but 'they are willing to take.' This subtle word choice suggests that the sacrament is about the orientation of the heart — a renewed willingness, a continual choosing. The covenant is not a past transaction but a present disposition.",
      commentary: "The sacrament prayers are among the few prayers in the Church given by direct revelation in exact wording. Every word was chosen with precision. The bread prayer (Moroni 4:3 and D&C 20:77) includes three commitments: willingness to take upon them the name of the Son, always remember Him, and keep His commandments. The promise is the companionship of the Spirit.\n\nThe word 'willing' deserves sustained attention. We do not pray that we have perfectly taken upon us His name — we witness that we are willing to do so. The sacrament meets us not in our perfection but in our desire. It is a weekly renewal of intent, a weekly recommitment of the heart's direction.\n\nMoroni 5:2 (the water prayer) adds the commitment to always remember Him. The two prayers together create a complete covenantal framework: take His name, remember Him, keep His commandments, and receive His Spirit. This is the entire gospel distilled into two short prayers, repeated weekly.\n\nThe sacrament is not merely a memorial of Christ's death — it is a covenant renewal ceremony. Every week, the disciple re-enters the covenant. Every week, the name is received again. This rhythm of weekly renewal is one of the most gracious provisions in the gospel: you are never more than a week away from a fresh start.",
      patterns: "The sacrament connects to the Passover, which was itself a covenant renewal meal. Christ instituted the sacrament at Passover, deliberately linking the old covenant meal to the new. The pattern of sacred meals marking covenant relationships runs from Abraham through the Last Supper to every sacrament meeting.",
      reflection: "The sacrament prayer says you are 'willing' to take upon you the name of Christ. During the sacrament this week, instead of reviewing your failures, what if you focused on renewing your willingness?"
    },
    {
      label: "Called by His name",
      focus: "The early disciples were called 'Christians' — bearers of Christ's name. Today examines what it means to be publicly identified with Christ.",
      scriptures: [{book:"Acts",ch:11,vs:26},{book:"3 Ne",ch:27,vs:5,ve:8},{book:"Alma",ch:34,vs:38}],
      nuances: "In Acts 11:26, the Greek 'Christianous' (Christians) was likely coined in Antioch, possibly as a derisive label from outsiders. The suffix '-ianos' in Latin and Greek denoted belonging to someone's household or party. The early believers were identified as belonging to Christ — whether they chose the label themselves or their neighbors gave it to them, the meaning was the same: these people belong to Christ.",
      commentary: "Acts 11:26 records a pivotal moment: the disciples were first called Christians at Antioch. Whether this name was self-chosen or externally imposed, it marked the community as belonging to Christ. Their identity was public, visible, and unmistakable. To be called a Christian was to be recognized as one who followed Christ — and in the Roman world, that carried real risk.\n\n3 Nephi 27:5–8 records Christ's own insistence that His Church be called by His name. The reason is plain: if a church is called by the name of a man, it is the church of a man. If it is called by Christ's name and built upon His gospel, it is His Church. The name is not cosmetic — it declares whose Church it is and whose work it does.\n\nAlma 34:38 provides the personal application: live in thanksgiving daily for the many mercies and blessings God bestows upon you. Amulek is describing the daily life of one who has taken upon themselves the name of Christ — a life of gratitude, worship, and practical holiness. The name shapes the life.\n\nBearing Christ's name publicly means representing Him. When people encounter you, they encounter someone who claims to belong to Christ. This is both a privilege and a responsibility — your life becomes a witness, for better or worse, of what Christ's name means.",
      patterns: "The public nature of covenant identity connects to the scriptural principle that testimony is meant to be shared, not hidden. Christ told His disciples they were the light of the world (Matthew 5:14). Taking His name and bearing witness of Him are inseparable.",
      reflection: "If the people in your workplace, neighborhood, or school were asked to describe what it means to follow Christ, would your life be evidence they could point to? What does bearing Christ's name publicly look like for you?"
    },
    {
      label: "Clothed in Christ",
      focus: "Paul taught that the baptized have 'put on Christ.' Today explores the metaphor of being clothed in Christ's identity and what it means for daily life.",
      scriptures: [{book:"Gal",ch:3,vs:26,ve:29},{book:"Col",ch:3,vs:17},{book:"Mosiah",ch:5,vs:7}],
      nuances: "In Galatians 3:27, 'as many of you as have been baptized into Christ have put on Christ,' the Greek 'enedusasthe' (put on, clothed yourselves with) was used for putting on a garment. In the ancient world, clothing signified status, identity, and role. To be clothed in Christ is to take on His identity as your own — like a soldier putting on a uniform that declares whose army he belongs to.",
      commentary: "Paul's metaphor of being clothed in Christ is one of the richest in the New Testament. In the ancient Mediterranean world, what you wore declared who you were — your social status, your occupation, your allegiance. To put on Christ in baptism was to declare a new primary allegiance that transcended every other identity marker.\n\nGalatians 3:28–29 draws out the implications: in Christ there is neither Jew nor Greek, bond nor free, male nor female. This was a radical declaration of unity. The divisions that defined the ancient world — ethnicity, social class, gender — were not erased but transcended by a higher identity. All who are baptized into Christ are one, and all are Abraham's seed and heirs of the promise.\n\nColossians 3:17 provides the practical application: 'Whatsoever ye do in word or deed, do all in the name of the Lord Jesus.' Taking His name is not a Sunday activity — it governs every word and every deed. The name of Christ becomes the standard by which all of life is measured.\n\nMosiah 5:7 confirms this from the Book of Mormon: those who have entered the covenant are called the children of Christ. The clothing metaphor and the naming ceremony converge — to be clothed in Christ and to be named as His child describe the same reality from different angles.",
      patterns: "The metaphor of sacred clothing connects to temple garments, which serve as a physical reminder of covenants made. The outward symbol points to an inward reality — identity in Christ is not theoretical but embodied.",
      reflection: "Paul says you have 'put on Christ.' If Christ is the garment you wear, does your life feel like it fits — or are there areas where you are still trying to wear something else underneath?"
    },
    {
      label: "Every knee shall bow",
      focus: "Ultimately, every being will acknowledge the name of Christ. Today examines the eschatological dimension of His name — its universal, final authority.",
      scriptures: [{book:"Philip",ch:2,vs:9,ve:11},{book:"Mosiah",ch:26,vs:18},{book:"D&C",ch:76,vs:110}],
      nuances: "In Philippians 2:10, 'at the name of Jesus every knee should bow,' the Greek 'en tō onomati' can mean 'at the name' or 'in the name.' Both senses are present: the name of Jesus evokes submission, and all things are gathered into that name. The universality is total — things in heaven, on earth, and under the earth.",
      commentary: "Philippians 2:9–11 is one of the earliest Christian hymns. It traces the arc of Christ's mission: He emptied Himself, became a servant, was obedient to death — and therefore God exalted Him and gave Him a name above every name. The name given is not merely 'Jesus' as a personal name but the name that represents His authority, His identity, and His Lordship over all creation.\n\nThe promise is that every knee will bow and every tongue confess that Jesus Christ is Lord. This is not a threat of forced submission but a prophecy of universal recognition. At the end of all things, every being will acknowledge the truth that has been available all along: Christ is Lord.\n\nMosiah 26:18 records the Lord's personal promise to Alma: 'thou art my servant; and I covenant with thee that thou shalt have eternal life.' The one who takes upon himself the name of Christ and serves faithfully receives in return the Lord's covenant promise. The exchange is deeply personal — not institutional but intimate.\n\nD&C 76:110 describes the culmination of Christ's redemptive work: every knee shall bow and every tongue confess to Him who sits upon the throne forever and ever. The name that we take upon ourselves in baptism is the name before which all creation will ultimately bend. We are not taking a minor name — we are taking the name that will be acknowledged as supreme throughout eternity.",
      patterns: "The universal acknowledgment of Christ's name connects to the Second Coming and final judgment studied in later weeks. The name we voluntarily take now, all will acknowledge then. The choice to take His name is a choice to align with the ultimate outcome of history.",
      reflection: "You have the opportunity to voluntarily take upon you the name that every being will eventually acknowledge. What does it mean to you that this ultimate name is already yours through covenant?"
    },
    {
      label: "Living worthy of the name",
      focus: "Taking the name of Christ is a beginning, not an end. Today synthesizes the week by examining what it means to live daily as one who bears His name.",
      scriptures: [{book:"Col",ch:3,vs:17},{book:"Mosiah",ch:5,vs:8},{book:"3 Ne",ch:27,vs:5,ve:8}],
      nuances: "In Colossians 3:17, 'whatsoever ye do in word or deed, do all in the name of the Lord Jesus,' the Greek 'pan ho ti' (whatsoever) is comprehensively inclusive — it leaves nothing outside the scope of the commandment. There is no secular space where the name of Christ does not apply. Every word, every action, every decision falls under the covenant.",
      commentary: "Colossians 3:17 is perhaps the most comprehensive ethical statement in the New Testament. Everything — word and deed, public and private, significant and mundane — is to be done in the name of the Lord Jesus. This is what taking His name ultimately means: not a weekly recitation but a total reorientation of life.\n\nMosiah 5:8 provides the spiritual consequence: those who faithfully keep the covenant are found on the right hand of God. The name of Christ becomes a means of recognition — God knows those who bear His Son's name, and they know God. The name creates a relationship of mutual recognition that persists into eternity.\n\n3 Nephi 27:5–8 returns to Christ's own words about why His name matters. A church must be built on His gospel and called by His name; otherwise it cannot be His. The same principle applies individually: a life must be built on His gospel and lived in His name; otherwise it does not truly bear His identity.\n\nThe week's study comes to this practical conclusion: taking the name of Christ is not a theological abstraction. It is a way of living. It means every conversation carries His name into the room. Every act of kindness extends His reach. Every choice to forgive demonstrates His character. Every act of worship honors the covenant. To bear His name is to make Him present in the world through your life.\n\nThis is the privilege and the weight of the covenant. You carry the most sacred name in the universe. Live accordingly.",
      patterns: "Living worthy of the name of Christ is the bridge between this week and Week 37, which studies Christ as Head of the Church. Those who take His name individually form the community — the body of Christ — that He leads collectively.",
      reflection: "As this week closes, ask yourself one honest question: if someone followed you through an ordinary day, would they see evidence that you carry the name of Christ? What is one specific thing you would change?"
    }
  ]
};

export default week36;
