import type { WeekContent } from '../types';

const week41: WeekContent = {
  title: "Types in Memory — Ordinances and Symbols That Point Back to Christ",
  subtitle: "Since the Resurrection, God has given us ordinances and emblems that look backward to the cross and forward to His return.",
  weekScriptures: "Luke 22:19–20; 3 Ne. 18:7–11; 3 Ne. 20:8–9; 1 Cor. 11:23–26; Moro. 4:3; Moro. 5:2; Matt. 28:19; 2 Ne. 31:5–13; 3 Ne. 11:23–26; Mosiah 18:8–10; D&C 20:72–74; Moro. 6:5–6; D&C 59:9–12; John 13:1–17; D&C 138:33–34; Moro. 10:32–33",
  synthesis: {
    summary: "If Week 40 explored symbols that pointed forward to a Messiah who had not yet come, this week examines symbols that point backward to a Savior who has already sacrificed. Baptism, the sacrament, and other ordinances of the gospel are not mere rituals — they are divinely appointed acts of remembrance that connect us to Christ's Atonement across time. Every time bread is broken and water is blessed, Calvary becomes present tense.",
    connections: [
      "This week is the companion to Week 40 (Types in Anticipation) — together they form a complete picture of how God uses symbols across time.",
      "The sacrament prayers connect directly to Week 20 (Atonement) and Week 18 (Crucifixion) as the weekly ordinance of remembrance.",
      "Baptism as a type connects to Week 10 (Baptism of Christ) and the covenant theology of Week 6."
    ],
    teaching: "Why does God continue to use physical symbols and ordinances even after Christ has come? What do we gain from these tangible reminders that we would not receive from doctrine alone?",
    commitment: "Next time you partake of the sacrament, focus on one element from this week's study. Let the bread and water connect you consciously to the events they represent."
  },
  days: [
    {
      label: "The sacrament instituted",
      focus: "Jesus established the sacrament at the Last Supper, transforming the Passover meal into a covenant of remembrance. Today examines the moment of institution.",
      scriptures: [{book:"Luke",ch:22,vs:19,ve:20},{book:"1 Cor",ch:11,vs:23,ve:26},{book:"Matt",ch:26,vs:26,ve:28}],
      nuances: "In Luke 22:19, Jesus says 'this do in remembrance of me.' The Greek 'anamnesis' means far more than casual recollection — it implies a re-presenting, a making-present of a past event. In the sacrament, we do not merely think about the Atonement; we participate in its reality anew.",
      commentary: "The Last Supper was a Passover meal — the annual commemoration of Israel's deliverance from Egypt. Jesus took the bread and wine of this familiar meal and invested them with radically new meaning. The bread became His body. The wine became His blood. The meal of backward-looking remembrance (the exodus) became a meal of both backward-looking remembrance (the cross) and forward-looking anticipation (His return).\n\nPaul's account in 1 Corinthians 11:23–26 adds a crucial phrase: 'For as often as ye eat this bread, and drink this cup, ye do shew the Lord's death till he come.' The sacrament exists in the tension between two events — the cross behind us and the Second Coming ahead. It is the ordinance that holds past and future together in the present moment.\n\nMatthew 26:28 records that Christ's blood was 'shed for many for the remission of sins.' This language connects the sacrament directly to the Atonement — not as a symbolic gesture but as a covenant renewal. Each time we partake, we re-enter the covenant relationship established by His sacrifice.\n\nThe transition from Passover to sacrament is one of the most significant moments in salvation history. The type (Passover lamb, Week 40) gives way to the memorial (sacrament). The shadow is replaced by the substance, and the substance is remembered through new symbols. God never leaves His people without tangible means of connecting to His saving acts.",
      patterns: "The Passover-to-sacrament transition demonstrates a pattern: as God fulfills one symbol, He provides a new one appropriate to the new dispensation. The form changes but the function remains — physically connecting covenant people to God's saving power.",
      reflection: "When you partake of the sacrament, do you experience it as a routine or as a covenant renewal? What might help you approach it with the same weight the apostles felt at the Last Supper?"
    },
    {
      label: "The sacrament among the Nephites",
      focus: "The resurrected Christ personally administered the sacrament in the Americas, providing a second witness of its importance and meaning.",
      scriptures: [{book:"3 Ne",ch:18,vs:7,ve:11},{book:"3 Ne",ch:20,vs:8,ve:9},{book:"Moro",ch:4,vs:3},{book:"Moro",ch:5,vs:2}],
      nuances: "In 3 Nephi 18:7, Christ states that partaking of the bread is a 'testimony unto the Father that ye do always remember me.' The Nephite account uniquely frames the sacrament as testimonial — an act of witness directed toward the Father, not merely an act of personal devotion.",
      commentary: "The Book of Mormon provides something extraordinary: an account of the resurrected Christ Himself instituting the sacrament among a second group of people. In 3 Nephi 18, Jesus breaks bread, blesses it, and gives it to the multitude. He commands them to do this always in remembrance of His body. He then takes the cup and gives it to them to drink in remembrance of His blood.\n\nThe repetition matters. Christ did not institute the sacrament once and assume it would be transmitted by tradition. He personally established it on two continents, ensuring that the ordinance came from His own hands in both the Old World and the New. This dual institution underscores the universal importance of the ordinance.\n\n3 Nephi 20:8–9 records a second administration the following day, during which Christ performed a miracle — providing bread and wine that had not been brought by the disciples. This miraculous provision echoes the manna (Week 40, Day 3) and the feeding of the five thousand, reinforcing the Bread of Life symbolism.\n\nThe sacrament prayers recorded in Moroni 4:3 and 5:2 are among the most carefully preserved texts in the Restoration. They are the only prayers in Latter-day Saint worship that are recited word for word. The bread prayer asks that participants 'always remember him and keep his commandments which he has given them.' The water prayer uses nearly identical language. The repetition each week — the same words, the same ordinance — creates a rhythm of covenant renewal that structures the life of a disciple.",
      patterns: "Christ's personal institution of the sacrament among the Nephites parallels His personal appearance to establish the Church, baptism, and priesthood authority (3 Nephi 11–18). Every essential ordinance came from His own direction, not human invention.",
      reflection: "The sacrament prayers promise that if you remember Him and keep His commandments, you will have His Spirit. How aware are you of the Spirit in the hours after you partake each Sunday?"
    },
    {
      label: "Baptism as a type of death and resurrection",
      focus: "Baptism is not merely an initiation rite — it is a symbolic burial and resurrection, connecting the believer to Christ's death and new life.",
      scriptures: [{book:"2 Ne",ch:31,vs:5,ve:13},{book:"3 Ne",ch:11,vs:23,ve:26},{book:"Rom",ch:6,vs:3,ve:6},{book:"D&C",ch:20,vs:72,ve:74}],
      nuances: "Paul's language in Romans 6:4 is vivid: 'We are buried with him by baptism into death.' The Greek 'sunetaphemen' means 'co-buried' — we are not merely symbolizing burial but participating in Christ's burial. Going under the water is going into the tomb. Rising is rising with Him.",
      commentary: "Nephi explains in 2 Nephi 31 that Christ Himself was baptized despite being sinless — to 'fulfil all righteousness' and to show humanity the gate through which they must enter. If the sinless Son of God submitted to this ordinance, no one is exempt. Baptism is the gate, not a suggestion.\n\nThe resurrected Christ, in His very first teaching to the Nephites (3 Nephi 11:23–26), provided the exact manner of baptism: immersion, in the name of the Father, Son, and Holy Ghost. The specificity is deliberate. Full immersion mirrors the full burial and full resurrection of Christ. Sprinkling, however well-intentioned, loses the typological meaning: you cannot partially bury and partially rise.\n\nPaul develops the typology most fully in Romans 6:3–6. Baptism is a death — we die to sin, are buried in water, and rise to a new life. The old self is crucified with Christ. This language is not metaphorical in the way modern readers often assume; Paul means it as the spiritual reality enacted through a physical ordinance.\n\nD&C 20:72–74 provides the Restoration's baptismal prayer, which echoes baptism's covenantal dimensions: the person takes upon them the name of Christ, commits to serve God, and witnesses their commitment before heaven. The ordinance is simultaneously a burial, a birth, a covenant, and a witness. It compresses the entire gospel into a single act.",
      patterns: "Baptism connects the types of Week 40 (passing through the Red Sea, washing rituals) with the memorial ordinances of the New Covenant. Israel passed through water to be delivered; Christians pass through water to be reborn. The element changes meaning but retains its power.",
      reflection: "If baptism represents dying to your old life and rising to a new one, what part of your 'old self' still needs to be left in the water?"
    },
    {
      label: "Washing of feet — the servant type",
      focus: "On the night before His death, Jesus washed His disciples' feet. This act of humble service is both a type and a teaching about the nature of His mission.",
      scriptures: [{book:"John",ch:13,vs:1,ve:17},{book:"Luke",ch:22,vs:27},{book:"Mark",ch:10,vs:43,ve:45},{book:"D&C",ch:88,vs:138,ve:141}],
      nuances: "In John 13:4, Jesus 'laid aside his garments' before washing feet. The Greek 'tithemi' — to lay down — is the same verb Jesus uses in John 10:15 for laying down His life. The literary echo is intentional: laying aside garments prefigures laying down His life. The act of service and the act of sacrifice use the same word.",
      commentary: "John 13 records an act that stunned the apostles. Jesus, their Lord and Master, removed His outer garment, tied a towel around His waist, and began washing their feet — the work of the lowest household servant. Peter resisted. Jesus insisted, telling Peter that unless He washed him, Peter had 'no part' with Him.\n\nThis was not merely a lesson in humility, though it was certainly that. It was a living parable of the Atonement. Christ descended from His glory, stripped Himself of divine prerogative, took on the form of a servant, and cleansed those who could not cleanse themselves. Philippians 2:5–8 describes the same movement in doctrinal terms: He emptied Himself, took the form of a servant, and humbled Himself to death on a cross.\n\nLuke 22:27 places Jesus' own words alongside the action: 'I am among you as he that serveth.' Mark 10:43–45 extends this to His followers: whoever would be great must be a servant, 'for even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.'\n\nD&C 88:138–141 reveals that the ordinance of washing of feet was restored in the latter days, performed in sacred settings. The Restoration did not treat this as merely a historical curiosity — it recognized the washing of feet as a sacred ordinance with continuing significance. The type is not dead; it lives in the covenant community.",
      patterns: "Christ's washing of feet inverts the world's power structure. This inversion — where the greatest serves the least — is the consistent pattern of Christ's ministry and connects to Week 26 (Compassion of) and Week 27 (Humility of).",
      reflection: "Is there someone in your life whose 'feet' you could symbolically wash this week — someone you could serve in a way that feels beneath your station?"
    },
    {
      label: "The Sabbath as a type of rest in Christ",
      focus: "The Sabbath is more than a day off. It is a weekly type of the rest God offers through Christ — rest from sin, labor, and spiritual exile.",
      scriptures: [{book:"D&C",ch:59,vs:9,ve:12},{book:"Heb",ch:4,vs:1,ve:11},{book:"Moro",ch:6,vs:5,ve:6},{book:"Ex",ch:20,vs:8,ve:11}],
      nuances: "Hebrews 4:9 uses a unique Greek word: 'sabbatismos' — a 'Sabbath-keeping' or 'Sabbath rest.' This word appears nowhere else in the New Testament. The author is not talking about a weekly day of rest but about a final, eschatological rest — the rest of eternal life that the weekly Sabbath foreshadows.",
      commentary: "The Sabbath was instituted at creation — God rested on the seventh day, not because He was tired, but to establish a pattern. The command to observe the Sabbath in Exodus 20 links it to both creation and (in Deuteronomy 5:15) to deliverance from Egypt. The Sabbath remembers both the beginning and the redemption.\n\nHebrews 4 transforms the Sabbath from a weekly observance into a theological category. The author argues that Joshua did not give Israel the true rest (the promised land was not the final destination), so 'there remaineth therefore a rest to the people of God.' This rest is entered through faith and obedience — it is the rest of being fully reconciled to God through Christ.\n\nD&C 59:9–12 commands Latter-day Saints to observe the Sabbath by going to the house of prayer, offering up sacraments, resting from labors, and paying devotions to the Most High. The section explicitly connects Sabbath observance to joy and gratitude. The Sabbath is not a burden but a gift — a weekly rehearsal of the eternal rest Christ offers.\n\nMoroni 6:5–6 describes the early Nephite church meeting 'oft' to fast, pray, speak of the welfare of their souls, and partake of bread and wine in remembrance of Christ. The gathering itself — the regular, communal act of worship — is the Sabbath pattern. We come together not primarily to hear talks or fulfill assignments but to remember Christ and renew our connection to His rest.",
      patterns: "The Sabbath connects Week 40's types (the seventh day of creation) to Week 41's memorials (weekly worship and sacrament). It is both a type of what is to come and a memorial of what has been done. It bridges anticipation and memory.",
      reflection: "Do you experience the Sabbath as rest or as obligation? What would it look like to approach Sunday as a rehearsal of the rest Christ offers you eternally?"
    },
    {
      label: "Ordinances for the dead — extending the types across the veil",
      focus: "Latter-day Saint temple ordinances extend the types of Christ to those who have died. Today examines the doctrine that the memorial symbols reach beyond mortality.",
      scriptures: [{book:"D&C",ch:138,vs:33,ve:34},{book:"1 Cor",ch:15,vs:29},{book:"Mal",ch:4,vs:5,ve:6},{book:"1 Pet",ch:3,vs:18,ve:20}],
      nuances: "In 1 Corinthians 15:29, Paul asks: 'Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?' The Greek 'huper ton nekron' — 'on behalf of the dead' — is straightforward. Paul mentions the practice without condemning it, using it as evidence for the reality of the resurrection.",
      commentary: "One of the most distinctive contributions of the Restoration is the doctrine that saving ordinances can be performed vicariously for those who have died. D&C 138, Joseph F. Smith's vision of the redemption of the dead, reveals that Christ organized the preaching of the gospel in the spirit world so that all who had died without hearing the gospel could receive it and accept the ordinances performed on their behalf.\n\nThis doctrine transforms baptism and the sacrament from personal ordinances into universal ones. The types and symbols of Christ's Atonement are not limited by mortality. They reach backward through time and across the veil of death. This is the most expansive claim any Christian theology makes about the scope of Christ's saving work.\n\nPaul's reference in 1 Corinthians 15:29 to baptism for the dead is often overlooked in mainstream Christian commentary because it does not fit easily into post-apostolic theology. But in the Restoration, it becomes a cornerstone: the same ordinance that connects the living to Christ can connect the dead to Him as well.\n\nMalachi's prophecy about Elijah turning the hearts of the fathers to the children (Malachi 4:5–6) finds its fulfillment in this temple work. The ordinances of remembrance — the types that point back to Christ — become the mechanism by which all of God's family, living and dead, are bound together in covenant. The symbols are not merely personal devotional acts; they are the connective tissue of an eternal family.",
      patterns: "Vicarious ordinances for the dead extend the pattern of types across the veil, connecting the living and dead in a single covenant community. This links to Week 38 (Family of Christ) and forward to Week 42 (Postmortal Appearances), where Christ's ministry to the dead is examined.",
      reflection: "Have you considered your temple and family history work as an extension of the sacrament — as carrying the symbols of Christ's Atonement to those who cannot receive them on their own?"
    },
    {
      label: "Living types — a life that points to Christ",
      focus: "Ultimately, the most important type of Christ is a life lived in discipleship. Today examines the call to become living symbols of His grace.",
      scriptures: [{book:"Moro",ch:10,vs:32,ve:33},{book:"Mosiah",ch:18,vs:8,ve:10},{book:"3 Ne",ch:27,vs:27},{book:"2 Cor",ch:3,vs:2,ve:3}],
      nuances: "Paul tells the Corinthians in 2 Corinthians 3:3 that they are 'the epistle of Christ... written not with ink, but with the Spirit of the living God; not in tables of stone, but in fleshy tables of the heart.' The metaphor transforms people into sacred texts — living scriptures that others can read. The community of believers is itself a type of Christ.",
      commentary: "This week has examined formal ordinances — the sacrament, baptism, the Sabbath, temple work. But the most powerful type of Christ is not an ordinance. It is a life.\n\n3 Nephi 27:27 records Christ's direct question to His Nephite disciples: 'What manner of men ought ye to be? Verily I say unto you, even as I am.' This is not an impossible standard designed to crush — it is an invitation to become. Through the Atonement, the same grace that saves us also transforms us into living reflections of the Savior.\n\nMosiah 18:8–10 describes the baptismal covenant in relational terms: to bear one another's burdens, mourn with those who mourn, comfort those who stand in need of comfort, and stand as witnesses of God at all times, in all things, and in all places. This is not a list of obligations — it is a description of the kind of person Christ is. The covenant transforms us into types of Him.\n\nMoroni 10:32–33 provides the capstone: come unto Christ, deny yourselves of all ungodliness, and love God with all your might, mind, and strength — 'that by his grace ye may be perfect in Christ.' Perfection is not achieved by effort alone. It is the result of grace working within a willing and covenanted heart.\n\nPaul's image of believers as 'epistles of Christ' is the ultimate typological claim: we are meant to be readable. When people observe our lives, they should see something of Christ. Not perfection — He alone achieved that — but direction. Our lives, like the ordinances, should point to Him.",
      patterns: "The arc of these two weeks (40–41) moves from ancient symbols through modern ordinances to living witnesses. The types begin in ritual and end in life. This is the pattern of the gospel: outward forms are meant to produce inward transformation.",
      reflection: "If someone read your life as a 'letter from Christ,' what would it say? What one change would make the message clearer?"
    }
  ]
};

export default week41;
