import type { WeekContent } from '../types';

const week31: WeekContent = {
  title: "Only Begotten Son — The Unique and Singular Christ",
  subtitle: "There is only one who holds this title — the Only Begotten of the Father, full of grace and truth, whose sacrifice could be made by no other.",
  weekScriptures: "John 1:14,18; John 3:16–18; 1 Jn 4:9; Heb 1:1–6; Heb 5:5–8; Jacob 4:5,11; Alma 12:33–34; Alma 13:9; D&C 20:21; D&C 29:42; D&C 76:23–24; D&C 93:11; Moses 1:6,33; Moses 4:1–2; Moses 5:7–9; Moses 6:52",
  synthesis: {
    summary: "The title 'Only Begotten Son' sets Jesus Christ apart from every other being who has ever lived. All humans are children of God in spirit, but only Christ is the Only Begotten of the Father in the flesh. This unique status is not a mere theological distinction — it is what gave His Atonement infinite power. Because He was the Only Begotten, His sacrifice could accomplish what no other sacrifice could: the redemption of all humanity. Restoration scripture uses this title with particular frequency and clarity, making it a cornerstone of Latter-day Saint Christology.",
    connections: [
      "This title builds directly on Week 29 (Son of God) and Week 30 (Son of Man), completing the triad of sonship titles.",
      "The Only Begotten's unique capacity to atone connects to Week 11 (Atonement) and Week 12 (Resurrection).",
      "Moses' encounters with the title 'Only Begotten' in the Pearl of Great Price connect to Week 3 (Premortal Christ) and Week 7 (Creator)."
    ],
    teaching: "What is the practical difference between knowing that Jesus is the Son of God and knowing that He is the Only Begotten Son? How does the word 'only' change the meaning?",
    commitment: "This week, focus on the uniqueness of Christ. When you are tempted to reduce Him to a good teacher or a moral example, recall that He is the Only Begotten — and no one else could have done what He did."
  },
  days: [
    {
      label: "Full of grace and truth",
      focus: "John introduces the Only Begotten with two defining characteristics: grace and truth. Today examines what it means that these qualities define the unique Son of God.",
      scriptures: [{book:"John",ch:1,vs:14},{book:"John",ch:1,vs:18},{book:"D&C",ch:93,vs:11}],
      nuances: "John 1:14 describes the Word made flesh as 'monogenous para patros' — the Only Begotten from the Father. The Greek 'monogenēs' combines 'monos' (only) and 'genos' (kind, type, offspring). In classical usage it could mean 'one of a kind' or 'only born.' The term 'para patros' (from the Father) specifies the source of this unique relationship. John is asserting not just uniqueness in general but unique derivation from God the Father.",
      commentary: "John 1:14 is one of the most theologically dense verses in scripture. The Word became flesh, dwelt among us, and the disciples beheld His glory — the glory as of the Only Begotten of the Father, full of grace and truth. The glory of the Only Begotten is not a display of raw power but is characterized by two attributes: grace and truth. These are the defining marks of the unique Son.\n\nGrace is unmerited divine favor — the willingness of God to give what is not earned. Truth is reality as God sees it — undistorted, uncorrupted, complete. The Only Begotten embodies both perfectly. He extends mercy without diminishing honesty. He speaks truth without withholding compassion. In a world that treats grace and truth as opposites — where kindness seems to require compromise and honesty seems to require harshness — the Only Begotten holds them together.\n\nJohn 1:18 adds that no one has seen God at any time; the Only Begotten Son, who is in the bosom of the Father, has declared Him. The word 'declared' translates the Greek 'exēgēsato,' from which we get 'exegesis.' The Only Begotten is the Father's exegesis — the authoritative interpretation of who God is. To know the Only Begotten is to know the Father, because only the Only Begotten has the intimate access ('in the bosom of the Father') that makes true knowledge possible.\n\nD&C 93:11 records John the Baptist's testimony: 'I saw his glory, that he was in the beginning, before the world was; Therefore, in the beginning the Word was, for he was the Word, even the messenger of salvation.' The Restoration confirms John's Gospel: the Only Begotten existed before creation and was the messenger of salvation from the beginning.",
      patterns: "The 'grace and truth' pairing echoes the Hebrew 'chesed ve-emet' (covenant loyalty and faithfulness) that characterizes God throughout the Old Testament (Exodus 34:6). The Only Begotten is the embodiment of what Israel had known of God for centuries.",
      reflection: "The Only Begotten is 'full of grace and truth' — not one or the other, but both in fullness. Which do you tend to emphasize more in your own discipleship — grace or truth — and how might the Only Begotten's example help you balance them?"
    },
    {
      label: "The Only Begotten in the premortal world",
      focus: "Restoration scripture reveals that the title 'Only Begotten' was used in the premortal councils and in the earliest dispensations. Today explores what the Pearl of Great Price adds to our understanding.",
      scriptures: [{book:"Moses",ch:4,vs:1,ve:2},{book:"Moses",ch:1,vs:6},{book:"Moses",ch:1,vs:33}],
      nuances: "In Moses 4:2, the Father refers to Christ as 'my Beloved Son, which was my Beloved and Chosen from the beginning.' The language of being 'chosen from the beginning' parallels 1 Peter 1:20 (foreordained before the foundation of the world) and establishes that the Only Begotten's role was determined in the premortal councils — not as a reaction to the Fall but as the central pillar of the eternal plan.",
      commentary: "The Pearl of Great Price provides context for the title 'Only Begotten' that is available nowhere else in scripture. Moses 4:1–2 records the premortal council in which Satan proposed an alternative plan and was rejected, while the Father's Beloved Son said, 'Father, thy will be done, and the glory be thine forever.' The Only Begotten is identified by submission, not self-assertion. His response to the Father is the defining act of His identity.\n\nMoses 1:6 records God speaking to Moses face to face and saying, 'Thou art in the similitude of mine Only Begotten; and mine Only Begotten is and shall be the Savior.' This statement serves a dual purpose: it elevates Moses by comparing him to Christ, and it establishes that the Only Begotten's saving role is both present ('is') and future ('shall be'). The Only Begotten is the Savior in every tense — past, present, and future.\n\nMoses 1:33 reveals the scope of the Only Begotten's creative work: worlds without number have been created by the Son. This is not a minor detail — it means the Only Begotten is not merely the Savior of this one earth but the Creator and Redeemer of an unfathomable number of worlds. The uniqueness of the Only Begotten is not provincial; it is cosmic.\n\nThese Restoration texts establish that the title 'Only Begotten' was known and used from the beginning of the world — not invented by John in the first century but revealed to the earliest prophets. Adam, Enoch, Noah, and Moses all knew the Only Begotten by this title. The New Testament did not introduce this doctrine; it confirmed what had been taught since Adam.",
      patterns: "The Pearl of Great Price consistently expands the historical depth of titles that appear in the New Testament. What John writes in the first century was known to Adam and Enoch. This 'restoration of all things' pattern — recovering ancient knowledge through modern revelation — is a defining feature of the Restoration.",
      reflection: "The Only Begotten said, 'Father, thy will be done, and the glory be thine forever.' How does this simple statement reshape your understanding of what it means to submit your will to God?"
    },
    {
      label: "God so loved the world",
      focus: "John 3:16 is the verse that makes 'Only Begotten' a household phrase. Today returns to this verse with the full weight of the week's context.",
      scriptures: [{book:"John",ch:3,vs:16,ve:18},{book:"1 Jn",ch:4,vs:9},{book:"D&C",ch:20,vs:21}],
      nuances: "In 1 John 4:9, 'God sent his only begotten Son into the world' uses the aorist tense for 'sent' (Greek: 'apestalken'), indicating a completed, definitive action. The sending of the Only Begotten was not a tentative experiment but a decisive, once-for-all act. The same verb root gives us 'apostle' (apostolos) — the Only Begotten is the supreme Apostle, the one sent by the Father on the ultimate mission.",
      commentary: "John 3:16 was explored in Week 29 through the lens of the title 'Son of God.' This week we return to it through the lens of the qualifier 'Only Begotten.' The word 'only' changes everything. God did not give one son among many — He gave His only Son. The costliness of the gift is precisely in its uniqueness. There is no replacement, no backup, no second Only Begotten. If this Son is lost, the plan collapses.\n\nThis is what makes the Atonement not merely impressive but staggering. The Father risked His only Son — the unique being through whom all worlds were created, through whom all salvation is offered. The Father's love for the world was so great that He placed the one irreplaceable being in creation into the hands of the very creatures He came to save.\n\n1 John 4:9 emphasizes that the purpose of sending the Only Begotten was 'that we might live through him.' The Only Begotten is the source of life — not a means to life among other means, but the exclusive source. Without Him, there is no path from death to life for any soul on any world.\n\nD&C 20:21 places this doctrine squarely within Restoration scripture: Christ 'was crucified, died, and rose again the third day; And ascended into heaven, to sit down on the right hand of the Father, to reign with almighty power according to the will of the Father.' The Only Begotten's mission followed a precise sequence: incarnation, crucifixion, death, resurrection, ascension, enthronement. Every stage was essential, and no other being could have completed any of them.",
      patterns: "The giving-of-the-Only-Begotten echoes and fulfills the near-sacrifice of Isaac in Genesis 22 (explored in Week 27). Abraham was asked to give his only son and was spared at the last moment. The Father was not spared. He gave His Only Begotten completely.",
      reflection: "The Father gave His Only Begotten — the one being that could not be replaced. What does the costliness of this gift tell you about how much God values your soul?"
    },
    {
      label: "In the similitude of the Only Begotten",
      focus: "The earliest ordinances of the gospel were performed 'in the similitude of the sacrifice of the Only Begotten.' Today explores what this means for every covenant we make.",
      scriptures: [{book:"Moses",ch:5,vs:7,ve:9},{book:"Jacob",ch:4,vs:5},{book:"Alma",ch:13,vs:9}],
      nuances: "Moses 5:7 records that Adam was commanded to offer the firstlings of his flocks as 'a similitude of the sacrifice of the Only Begotten of the Father.' The word 'similitude' (from the Latin 'similitudo,' meaning likeness or comparison) indicates that every sacrifice Adam offered was a deliberate re-enactment of the Only Begotten's future offering. The ordinance was not symbolic in a vague sense — it was a prophetic enactment pointing to a specific, real event.",
      commentary: "Moses 5:7–9 provides one of the most important passages in Restoration scripture for understanding the relationship between ordinances and the Only Begotten. After Adam and Eve were cast out of the garden, Adam offered sacrifice. When an angel asked why, Adam said he did not know — he was simply obeying. The angel then explained: this thing is a similitude of the sacrifice of the Only Begotten of the Father, who is full of grace and truth. You shall do all that you do in the name of the Son. Repent and call upon God in the name of the Son forevermore.\n\nThis passage establishes several foundational principles. First, every sacrifice from Adam forward was explicitly connected to the Only Begotten — the sacrificial system was not a generic religious practice but a specific prophetic witness. Second, everything in the gospel is done in the name of the Only Begotten — not as a formality but because He is the source of every covenant's power. Third, this knowledge was given at the very beginning, not developed gradually over centuries.\n\nJacob 4:5 confirms that Abraham's near-sacrifice of Isaac was also a similitude of the Only Begotten. Jacob says Abraham's offering was a type — and then declares that Abraham's faith and willingness point to God the Father, who would actually offer His Only Begotten Son.\n\nAlma 13:9 teaches that those ordained to the high priesthood were called 'after the order of his Son' — the Only Begotten. The priesthood itself operates as a similitude: those who hold it act in the name and authority of the Only Begotten, performing ordinances that point to His sacrifice and mediate His grace.",
      patterns: "The 'similitude' principle means that every gospel ordinance — from Adam's first sacrifice to the sacrament you partook of last Sunday — is a re-enactment of the Only Begotten's offering. Baptism, the sacrament, and temple ordinances all derive their meaning from this one source.",
      reflection: "Adam was told to do all things in the name of the Only Begotten. How conscious are you of the connection between the ordinances you participate in and the sacrifice they represent?"
    },
    {
      label: "Why it had to be the Only Begotten",
      focus: "No other being could have performed the Atonement. Today examines the theological reasons why only the Only Begotten Son could redeem humanity.",
      scriptures: [{book:"Alma",ch:34,vs:8,ve:14},{book:"D&C",ch:29,vs:42},{book:"Alma",ch:12,vs:33,ve:34}],
      nuances: "Alma 34:10 says the Atonement must be 'an infinite and eternal sacrifice.' The word 'infinite' (from the Latin 'infinitus,' meaning without limit or boundary) indicates that the sacrifice must be unlimited in scope — covering all sins, all people, all worlds. Only a being of infinite worth could offer an infinite sacrifice. A mortal, however righteous, is finite and therefore incapable of atoning for infinite sin. The Only Begotten, as the literal Son of God, possesses the infinite worth required.",
      commentary: "Amulek's discourse in Alma 34 is the Book of Mormon's most systematic explanation of why the Atonement could only be performed by the Only Begotten. The logic proceeds in steps: there must be an atonement; a human sacrifice will not suffice; an animal sacrifice will not suffice; it must be infinite and eternal; therefore it must be the sacrifice of the Son of God. The Only Begotten is not one option among many — He is the only option.\n\nThe reason is rooted in the nature of justice. The law demands a payment for sin. Human beings, being mortal and sinful themselves, cannot pay this debt — they owe it themselves. Only a being who does not owe the debt of sin can pay it on behalf of others. Only a being of infinite worth can pay a debt of infinite magnitude. Only the Only Begotten of the Father meets both conditions: sinless (He owes nothing) and infinite (His life has unlimited worth because He is the Son of God).\n\nD&C 29:42 adds a Restoration perspective: the Only Begotten is the one through whom the Father brings about the plan of redemption from the Fall. The connection between the Fall and the Atonement is absolute — without the Only Begotten, there is no recovery from Adam's transgression, no resurrection, no possibility of returning to God's presence.\n\nAlma 12:33–34 speaks of God's plan to bring about the redemption of the world through His Only Begotten Son, calling upon all people to repent. The plan and the Person are inseparable. There is no 'Plan B' because there is no other Only Begotten. The singularity of the title reflects the singularity of the mission: one Son, one sacrifice, one redemption, offered to all.",
      patterns: "The logical necessity of the Only Begotten's sacrifice — no other being could do it — runs parallel to the exclusivity claims in Acts 4:12 (no other name) and 2 Nephi 31:21 (no other way). The singularity of the Savior is a thread through every dispensation.",
      reflection: "If no one else could have atoned for your sins — not an angel, not a prophet, not any other being — what does it mean that the Only Begotten chose to do it anyway?"
    },
    {
      label: "The Only Begotten and the many worlds",
      focus: "Restoration scripture reveals that the Only Begotten created and redeems worlds without number. Today explores the cosmic scope of His unique role.",
      scriptures: [{book:"Moses",ch:1,vs:33},{book:"D&C",ch:76,vs:23,ve:24},{book:"Heb",ch:1,vs:1,ve:6}],
      nuances: "D&C 76:24 declares that 'by him, and through him, and of him, the worlds are and were created, and the inhabitants thereof are begotten sons and daughters unto God.' The prepositions 'by,' 'through,' and 'of' indicate that the Only Begotten is the agent, the means, and the source of all creation. He is not merely the craftsman who builds — He is the reason things exist at all.",
      commentary: "Moses 1:33 records God telling Moses: 'Worlds without number have I created; and I also created them for mine own purpose; and by the Son I created them, which is mine Only Begotten.' The scope is breathtaking. The Only Begotten is not the Savior of one small planet — He is the Creator and Redeemer of an uncountable number of worlds.\n\nD&C 76:23–24 provides the fullest Restoration statement of this truth. Joseph Smith and Sidney Rigdon testify that they saw the Son on the right hand of God, and heard the declaration that by Him, through Him, and of Him, the worlds are and were created, and the inhabitants thereof are begotten sons and daughters unto God. The Only Begotten's creative and redemptive work extends to the inhabitants of all these worlds — not just the inhabitants of Earth.\n\nHebrews 1:1–6 places the Son above the angels and declares that through Him God made the worlds ('tous aiōnas,' literally 'the ages' or 'the aeons'). The Son is the brightness of the Father's glory and the express image of His person, upholding all things by the word of His power. He is not a provincial deity — He sustains the entire fabric of reality.\n\nThis cosmic scope does not diminish the personal dimension of the Only Begotten's work. If anything, it magnifies it. The same being who created worlds without number also knows you by name, took upon Himself your specific sorrows (Alma 7:11–13), and offers you personally the covenant of redemption. The Only Begotten operates at every scale — from the galactic to the individual — without any loss of attention or care.",
      patterns: "The 'many worlds' doctrine in Moses and D&C echoes the 'many mansions' language in John 14:2 and expands it beyond a single planet. The Only Begotten's work is not finished with Earth — it extends across the entirety of the Father's creations.",
      reflection: "The Only Begotten created and redeems worlds without number — and yet He knows you personally. How does that combination of cosmic scope and individual attention affect the way you pray?"
    },
    {
      label: "Believing in the Only Begotten",
      focus: "The entire purpose of gospel teaching is to bring people to faith in the Only Begotten. Today synthesizes the week with the invitation to believe.",
      scriptures: [{book:"Moses",ch:6,vs:52},{book:"D&C",ch:76,vs:23,ve:24},{book:"Heb",ch:5,vs:5,ve:8}],
      nuances: "Moses 6:52 records God commanding Adam: 'Believe and repent of all thy transgressions, and be baptized, even in water, in the name of mine Only Begotten Son, who is full of grace and truth, which is Jesus Christ, the only name which shall be given under heaven, whereby salvation shall come unto the children of men.' Every element of the gospel — belief, repentance, baptism, salvation — is explicitly connected to the name of the Only Begotten. He is not adjacent to the gospel; He is the gospel.",
      commentary: "Moses 6:52 is a remarkable verse because it places the full gospel plan — faith, repentance, baptism, and the name of the Only Begotten — at the very beginning of human history, given directly to Adam. The gospel is not a late development in God's dealings with humanity. It was the first teaching, and the Only Begotten was its center from the start.\n\nThe commandment to believe in the Only Begotten is not a request for intellectual assent. Biblical and Book of Mormon 'belief' involves trust, reliance, commitment, and action. To believe in the Only Begotten is to stake your life on His sacrifice, to trust His promises, to structure your behavior around His teachings, and to anchor your hope in His resurrection.\n\nHebrews 5:5–8 reveals a dimension of the Only Begotten that is often overlooked: 'Though he were a Son, yet learned he obedience by the things which he suffered.' The Only Begotten was not born with a completed mortal education — He grew, learned, and was perfected through experience. His sinlessness was not effortless but was the product of real obedience in real trials. This makes His example not merely admirable but accessible. He did not bypass the human struggle; He mastered it.\n\nAs this week concludes, the central truth is this: there is one Only Begotten, one being in all of creation who occupies this unique role. He is the Creator of worlds, the author of the plan, the one who said 'Thy will be done,' the one who suffered in Gethsemane and died on Calvary, the one who rose on the third day, and the one who extends the covenant of salvation to every child of God on every world He has made. The title 'Only Begotten' is not a theological technicality — it is the name that carries the weight of infinite love, infinite sacrifice, and infinite redemption.",
      patterns: "The week's study of the Only Begotten completes the three-week sequence on Christ's sonship titles: Son of God (Week 29), Son of Man (Week 30), and Only Begotten Son (Week 31). Together they form a comprehensive portrait: He is divine (Son of God), He is human (Son of Man), and He is unique (Only Begotten) — the only being in existence who is all three.",
      reflection: "After three weeks studying Christ's sonship, how has your understanding of who He is deepened? What difference does it make to know that He is the Son of God, the Son of Man, and the Only Begotten — all at once?"
    }
  ]
};

export default week31;
