import type { WeekContent } from '../types';

const week42: WeekContent = {
  title: "Appearances, Postmortal — The Risen Christ Among His People",
  subtitle: "After His resurrection, Christ appeared to many — on roads, in rooms, at the seashore, and on another continent — proving that death had no hold on Him.",
  weekScriptures: "Matt. 28:1–10; Luke 24:13–35; Luke 24:36–43; John 20:11–18; John 20:19–29; John 21:1–17; Acts 1:1–11; 1 Cor. 15:3–8; 3 Ne. 11:1–17; D&C 76:22–24; D&C 110:1–10; JS-H 1:17",
  synthesis: {
    summary: "The resurrection of Jesus Christ is the most consequential event in human history. If it happened, everything changes. The postmortal appearances of Christ — to Mary, to the apostles, to five hundred at once, to an entire Nephite civilization, and to prophets in the latter days — constitute the evidentiary foundation of Christianity. This week studies each appearance not as a story but as a testimony, asking what each one reveals about the nature of the risen Lord and His relationship with His followers.",
    connections: [
      "The Resurrection was prophesied in detail during Week 39 (Prophecies about) and prefigured by the types in Week 40 (Isaac received back, the brazen serpent, the Day of Atonement).",
      "Christ's appearance to the Nephites connects to Week 1 (Overview, Day 7) and the broader witness of the Book of Mormon.",
      "The Restoration-era appearances (D&C 76, 110, JS-H 1) connect to Week 1 and forward to Week 43 (Second Coming) as evidence that Christ continues to appear and minister."
    ],
    teaching: "If the resurrection is true, what follows logically? If it is not true, what follows? Why does Paul say that if Christ is not risen, believers are 'of all men most miserable' (1 Corinthians 15:19)?",
    commitment: "Choose one postmortal appearance of Christ from this week and read the full account slowly. Let the reality of the Resurrection settle into your bones. Then ask yourself: do I live as though this is true?"
  },
  days: [
    {
      label: "The empty tomb and the first witness",
      focus: "The first person to see the risen Christ was Mary Magdalene. Today examines the significance of the empty tomb and why a woman was chosen as the first witness.",
      scriptures: [{book:"John",ch:20,vs:11,ve:18},{book:"Matt",ch:28,vs:1,ve:10},{book:"Mark",ch:16,vs:1,ve:7}],
      nuances: "In John 20:16, Jesus speaks one word — 'Mary' — and she instantly recognizes Him. The Greek records her response: 'Rabbouni,' an Aramaic term of deep personal endearment meaning 'my dear teacher' or 'my master.' It is more intimate than the common 'Rabbi.' Recognition came not through sight but through the sound of her own name in His voice.",
      commentary: "Mary Magdalene came to the tomb while it was still dark. She found the stone rolled away and the body gone. After running to tell Peter and John, she returned and stood weeping outside the tomb. Two angels asked why she wept. She turned and saw a figure she assumed was the gardener. Then He spoke her name — 'Mary' — and everything changed.\n\nThe detail that Mary did not recognize Jesus by sight is theologically rich. His resurrected body was real — He would later eat fish and invite Thomas to touch His wounds — but it was also glorified, changed. Recognition came through relationship, not appearance. He called her by name, as the Good Shepherd calls His own sheep (John 10:3).\n\nThat a woman was the first witness of the Resurrection is remarkable in historical context. In first-century Jewish and Roman culture, women's testimony was not accepted in courts of law. If the Gospel writers were fabricating the story, they would never have chosen a woman as the first witness — it would have undermined their credibility. The fact that they recorded it faithfully is itself evidence of authenticity.\n\nMatthew 28:1–10 adds that other women also encountered the risen Lord and were told to carry the news to the disciples. The first evangelists of the Resurrection were women. The gospel consistently elevates those the world overlooks.",
      patterns: "The pattern of Christ appearing first to the humble and overlooked — a woman at the tomb, shepherds at His birth — recurs throughout His ministry. He reveals Himself to the seeking heart, not the prestigious title.",
      reflection: "Mary recognized Jesus when He spoke her name. If Christ called you by name today, would you recognize His voice? What does His voice sound like in your life?"
    },
    {
      label: "The road to Emmaus",
      focus: "Two disciples walked with the risen Christ for miles without recognizing Him. Their experience teaches how scripture opens our eyes to His presence.",
      scriptures: [{book:"Luke",ch:24,vs:13,ve:35},{book:"D&C",ch:6,vs:22,ve:23},{book:"Mark",ch:16,vs:12,ve:13}],
      nuances: "Luke 24:32 — 'Did not our heart burn within us, while he talked with us by the way, and while he opened to us the scriptures?' The Greek 'dianoigo' (opened) means to open thoroughly, to unseal. Christ did not add to the scriptures — He unlocked what was already there. The burning heart was their recognition that the truth had been in front of them all along.",
      commentary: "The Emmaus road narrative is one of the most beautifully structured stories in the Gospels. Two disciples, devastated by the crucifixion, are walking away from Jerusalem. A stranger joins them. They pour out their grief: 'We trusted that it had been he which should have redeemed Israel.' Past tense. Their hope was dead.\n\nThe stranger then does something astonishing. Beginning with Moses and all the prophets, He expounds in all the scriptures the things concerning Himself. We are not told the specifics, but we can imagine: Genesis 3:15, the Akedah, the Passover, Isaiah 53, Psalm 22, Daniel 9 — every passage studied in Weeks 39 and 40. The entire Old Testament was opened as a single testimony of the Messiah who had to suffer and then enter His glory.\n\nAt supper, He took bread, blessed it, and broke it — the sacramental gesture. In that moment, their eyes were opened and they recognized Him. Then He vanished. They turned to each other and said, 'Did not our heart burn within us?'\n\nD&C 6:22–23 echoes this exact experience. The Lord reminds Oliver Cowdery of a time when He spoke peace to Oliver's mind — a burning in the heart that confirmed truth. The Emmaus pattern is the pattern of all spiritual witness: scripture opened, heart burning, Christ recognized. This is not ancient history. It is the ongoing experience of every sincere student of the word.",
      patterns: "The Emmaus pattern — walking in darkness, having scripture opened, recognizing Christ in the breaking of bread — is the pattern of every sacrament meeting, every scripture study session, every moment when truth suddenly becomes clear.",
      reflection: "Have you ever had a 'burning heart' moment while studying scripture or listening to a talk? What was happening in that moment, and what did it reveal to you?"
    },
    {
      label: "The upper room — Peace be unto you",
      focus: "Jesus appeared to the gathered apostles in a locked room, showing His wounds and offering peace. Thomas, absent the first time, received his own witness later.",
      scriptures: [{book:"Luke",ch:24,vs:36,ve:43},{book:"John",ch:20,vs:19,ve:29},{book:"1 Jn",ch:1,vs:1,ve:3}],
      nuances: "In John 20:27, Jesus tells Thomas: 'Reach hither thy finger, and behold my hands; and reach hither thy hand, and thrust it into my side: and be not faithless, but believing.' The Greek 'apistos' (faithless) and 'pistos' (believing) are not moral condemnations but descriptions of a state: move from unbelief to belief. Jesus is inviting, not rebuking.",
      commentary: "The disciples were hiding behind locked doors 'for fear of the Jews' when Jesus appeared among them. His first words were not rebuke for their cowardice or failure — they were 'Peace be unto you.' He showed them His hands and His side. They were glad.\n\nLuke adds a remarkable detail: they were 'terrified and affrighted, and supposed that they had seen a spirit.' Jesus responded by asking for food. He ate broiled fish in their presence. A spirit does not eat. The risen Christ has a tangible, physical, glorified body. This is not a ghost story or a vision — it is a bodily resurrection.\n\nThomas, who was absent, famously refused to believe without physical evidence. A week later, Jesus appeared again — specifically for Thomas. He invited Thomas to touch the wounds. Thomas responded with the most profound Christological confession in the Gospels: 'My Lord and my God.' This is not just an exclamation — it is a theological declaration that Jesus is both Lord (Kurios, Jehovah) and God (Theos).\n\nJesus' response to Thomas is often quoted partially: 'Blessed are they that have not seen, and yet have believed.' This is a benediction for every believer since — including you. Most of us will not see the wounds. We are asked to believe on the testimony of those who did. And Jesus calls that faith blessed.",
      patterns: "Christ appeared to the apostles in a group but also provided a personal witness for Thomas. The pattern is communal testimony confirmed by individual experience — the same pattern of general conference and personal prayer, of church worship and private revelation.",
      reflection: "Jesus did not rebuke Thomas for wanting evidence. What questions or doubts do you carry, and how might Christ be willing to meet you in them?"
    },
    {
      label: "The shore of Galilee — restored and commissioned",
      focus: "Jesus appeared at the Sea of Galilee and restored Peter after his denial. Today examines the appearance that turned failure into commission.",
      scriptures: [{book:"John",ch:21,vs:1,ve:17},{book:"Matt",ch:28,vs:18,ve:20},{book:"Acts",ch:1,vs:8}],
      nuances: "In John 21:15–17, Jesus asks Peter three times, 'Lovest thou me?' The first two times, Jesus uses 'agapas' (selfless, unconditional love). Peter responds with 'philo' (affectionate, friendship love). The third time, Jesus shifts to Peter's word — 'phileis me?' — meeting Peter where he is. The exchange mirrors Peter's threefold denial, but the word shift suggests Christ accepting Peter's honest, imperfect love rather than demanding a perfection Peter cannot yet offer.",
      commentary: "After the Resurrection, Peter returned to fishing — his old life, his old identity. Six other disciples joined him. They fished all night and caught nothing. At dawn, a figure on the shore called out and told them to cast on the right side. The net filled to bursting. John recognized the Lord first; Peter leaped into the water.\n\nOn the shore, Jesus had prepared a charcoal fire and breakfast. The detail of the charcoal fire is significant — the last charcoal fire in John's Gospel was in the courtyard where Peter denied Christ three times (John 18:18). Jesus deliberately recreated the setting of Peter's greatest failure. But instead of accusation, He offered a meal.\n\nThen came the threefold question: 'Simon, son of Jonas, lovest thou me?' Three questions to heal three denials. Each affirmation received a commission: 'Feed my lambs. Feed my sheep.' Peter's restoration was complete — not by erasing the past but by building a future on it. His deepest failure became the foundation of his ministry.\n\nMatthew 28:18–20 records the Great Commission: 'Go ye therefore, and teach all nations.' The risen Christ did not appear merely to prove He was alive. He appeared to commission. The Resurrection is not the end of the story — it is the beginning of the mission.",
      patterns: "Christ's restoration of Peter after failure is the pattern of all repentance: not erasure of the past but transformation of it. The very thing Peter was most ashamed of became the context for his deepest encounter with Christ's grace. This connects to Week 20 (Atonement) and Week 22 (Forgiveness).",
      reflection: "Peter's greatest failure did not disqualify him from Christ's service — it prepared him for it. Is there a failure in your past that Christ might be transforming into a commission?"
    },
    {
      label: "The Nephite appearance — a civilization witnesses",
      focus: "The most detailed account of a postmortal appearance of Christ is found in 3 Nephi, where 2,500 people saw, heard, and touched the risen Lord.",
      scriptures: [{book:"3 Ne",ch:11,vs:1,ve:17},{book:"3 Ne",ch:11,vs:33,ve:36},{book:"3 Ne",ch:17,vs:9,ve:10}],
      nuances: "3 Nephi 11:3 describes the Father's voice as 'not a harsh voice, neither was it a loud voice; nevertheless... it did pierce them that did hear to the center.' The voice was small yet penetrating — a deliberate echo of the 'still small voice' Elijah heard (1 Kings 19:12). God's most powerful communication is not shouting.",
      commentary: "The Nephite appearance of Christ is the climactic event of the Book of Mormon. A multitude of 2,500 people gathered at the temple in Bountiful. They heard a voice from heaven three times — twice they could not understand it. The third time, they heard the Father's introduction: 'Behold my Beloved Son, in whom I am well pleased, in whom I have glorified my name — hear ye him.'\n\nThen Christ descended from heaven, dressed in a white robe. He stretched forth His hand and spoke: 'I am Jesus Christ, whom the prophets testified shall come into the world.' He invited the multitude — all 2,500 — to come forward one by one, thrust their hands into His side, and feel the prints of the nails. This took hours. Every single person became a personal witness of the physical reality of the Resurrection.\n\nThe account then records some of the most tender moments in all of scripture. In 3 Nephi 17:9–10, Jesus healed every sick person among them. He called for their little children, and angels descended and encircled them with fire. He wept. The text says 'no one can conceive of the joy which filled our souls at the time we beheld Jesus pray for us unto the Father.'\n\nThis appearance is unique in the scriptural record. Nowhere else do we have 2,500 named witnesses who individually verified the Resurrection through touch. It is the Book of Mormon's most powerful testimony and its most sacred chapter.",
      patterns: "The Nephite appearance follows the same pattern as the Jerusalem appearances — showing wounds, inviting touch, commissioning disciples — but on a much larger scale. The pattern of personal witness combined with communal experience is God's established method for establishing truth.",
      reflection: "The Nephites each approached Christ individually and felt His wounds. If you had that opportunity, what would you want to say to Him?"
    },
    {
      label: "Appearances in the latter days",
      focus: "The risen Christ did not stop appearing after the New Testament. Today examines His appearances in the Restoration — the First Vision, the Kirtland Temple, and the vision of the degrees of glory.",
      scriptures: [{book:"JS-H",ch:1,vs:17},{book:"D&C",ch:110,vs:1,ve:10},{book:"D&C",ch:76,vs:22,ve:24},{book:"1 Cor",ch:15,vs:3,ve:8}],
      nuances: "In D&C 110:3, Joseph and Oliver describe Christ's eyes as 'a flame of fire' and His countenance as shining 'above the brightness of the sun.' This echoes the apocalyptic descriptions of Revelation 1:14–16, where John describes the glorified Christ in nearly identical terms. The consistency of these descriptions across eighteen centuries of witnesses is striking.",
      commentary: "Paul's list of resurrection witnesses in 1 Corinthians 15:3–8 concludes with himself: 'And last of all he was seen of me also, as of one born out of due time.' Paul did not see Christ during the forty-day post-resurrection ministry. His witness came later — on the road to Damascus. This establishes a precedent: Christ's appearances did not end with His ascension.\n\nJoseph Smith's First Vision (JS-H 1:17) is the foundational event of the Restoration. The Father and the Son appeared to a fourteen-year-old boy in a grove of trees. Whatever one concludes about this claim, it must be taken seriously: Joseph maintained this testimony throughout his life, at the cost of his life. The vision places the Restoration in direct continuity with the biblical pattern of divine appearance.\n\nD&C 110 records Christ's appearance in the Kirtland Temple on April 3, 1836 — which happened to be the Jewish Passover that year. Joseph and Oliver saw the Lord standing on the breastwork of the pulpit, His eyes as a flame of fire. He accepted the temple and declared: 'I am the first and the last; I am he who liveth, I am he who was slain; I am your advocate with the Father.'\n\nD&C 76:22–24 adds another modern witness: 'And now, after the many testimonies which have been given of him, this is the testimony, last of all, which we give of him: That he lives! For we saw him, even on the right hand of God.' The testimony is simple, direct, and consistent with every other post-resurrection witness in scripture.",
      patterns: "The Restoration appearances follow the exact pattern of biblical appearances: Christ is seen, He speaks, He commissions, and He is testified of. This continuity across dispensations is the strongest evidence that the same Lord is at work throughout history.",
      reflection: "The Restoration rests on the claim that Christ appeared again. How does your personal witness of Christ — however quiet — connect you to the chain of witnesses from Mary to Joseph Smith?"
    },
    {
      label: "The ascension and the promise of return",
      focus: "Christ's final visible departure included a promise: He will come again in the same manner. Today looks forward from the postmortal appearances to the Second Coming.",
      scriptures: [{book:"Acts",ch:1,vs:1,ve:11},{book:"1 Cor",ch:15,vs:20,ve:22},{book:"D&C",ch:45,vs:44,ve:46},{book:"Rev",ch:1,vs:7}],
      nuances: "In Acts 1:11, the angels say Christ will return 'in like manner as ye have seen him go into heaven.' The Greek 'hon tropon' means 'in the same way' — not symbolically or spiritually but visibly, bodily, from the clouds. The manner of departure defines the manner of return.",
      commentary: "Acts 1:1–11 records the final postmortal appearance of Christ to His apostles. After forty days of appearing and teaching about the kingdom of God, He gathered them on the Mount of Olives. They asked if He was about to restore the kingdom to Israel. He redirected their attention: they would receive power from the Holy Ghost and become witnesses to the ends of the earth. Then He was taken up, and a cloud received Him.\n\nTwo angels appeared immediately with a promise: 'This same Jesus, which is taken up from you into heaven, shall so come in like manner as ye have seen him go into heaven.' The Ascension is not the end — it is a pause between appearances. The same Jesus — bodily, glorified, wounded — will return.\n\nPaul's declaration in 1 Corinthians 15:20–22 places the Resurrection at the center of cosmic history: 'For as in Adam all die, even so in Christ shall all be made alive.' The Resurrection is not just Christ's personal triumph — it is the guarantee of universal resurrection. Because He rose, everyone will rise.\n\nD&C 45:44–46 describes the future scene: Christ will stand on the Mount of Olives, and the mount shall cleave in two. The saints shall be gathered. Revelation 1:7 adds that 'every eye shall see him, and they also which pierced him.' The postmortal appearances of this week are previews of the great and final appearance studied in Week 43.\n\nThe arc of this week moves from a single woman at an empty tomb to the promise that every eye will see Him. The appearances begin intimately and end cosmically. This is the trajectory of the gospel itself.",
      patterns: "The Ascension connects the postmortal appearances (this week) to the Second Coming (Week 43). The angels' promise creates a direct bridge: the manner of His departure guarantees the manner of His return. The same Christ will come again.",
      reflection: "The apostles were told to stop gazing into heaven and go to work. How do you balance longing for Christ's return with faithfully serving in the present?"
    }
  ]
};

export default week42;
