import type { WeekContent } from '../types';

const week29: WeekContent = {
  title: "Son of God — The Divine Identity of Jesus Christ",
  subtitle: "The title 'Son of God' is not honorary or metaphorical — it is a literal declaration of Christ's divine parentage and nature.",
  weekScriptures: "Matt 16:15–17; John 1:34; John 3:16–18; John 10:36; John 20:31; Luke 1:35; Mark 1:1,11; Heb 1:1–5; 1 Jn 4:9–10,15; 2 Ne 25:19; Alma 36:17; Hel 5:12; D&C 93:21; Moses 4:2; 1 Ne 11:18–21",
  synthesis: {
    summary: "The title 'Son of God' is the most fundamental declaration about who Jesus Christ is. It appears across every book of scripture, spoken by the Father, by angels, by prophets, by apostles, by demons, and by Christ Himself. Unlike 'Son of Man' (explored next week), which emphasizes His connection to humanity, 'Son of God' emphasizes His connection to divinity. Latter-day Saint theology affirms this title literally: Jesus is the literal Son of God the Father, with all the divine attributes and authority that relationship implies.",
    connections: [
      "The title 'Son of God' relates directly to 'Only Begotten Son' (Week 31) and provides the foundation for understanding Christ's dual nature as divine and human.",
      "Peter's confession of Christ as the Son of God (Matt 16) connects to the testimony themes in Week 24.",
      "Christ's divine sonship is the basis for His authority as Creator (Week 7), Redeemer (Week 8), and Judge (Week 36)."
    ],
    teaching: "When the Father declared 'This is my beloved Son,' what was He revealing about their relationship — and what does it imply about our potential relationship with God?",
    commitment: "This week, each time you pray to the Father 'in the name of Jesus Christ,' pause to consider what it means that you are approaching God through His literal Son."
  },
  days: [
    {
      label: "Peter's great confession",
      focus: "At Caesarea Philippi, Jesus asked the most important question in history: 'Who do you say that I am?' Peter's answer changed everything. Today explores that moment.",
      scriptures: [{book:"Matt",ch:16,vs:15,ve:17},{book:"John",ch:20,vs:31},{book:"Hel",ch:5,vs:12}],
      nuances: "In Matthew 16:16, Peter's confession 'Thou art the Christ, the Son of the living God' uses 'ho Christos' (the Anointed One, the Messiah) paired with 'ho huios tou theou tou zōntos' (the Son of the living God). The phrase 'living God' distinguishes the true God from the dead idols of the surrounding nations. Peter is not offering a vague spiritual compliment — he is making a precise theological claim about Jesus' unique relationship to the one true God.",
      commentary: "Caesarea Philippi was a deliberately provocative setting for this conversation. The region was dominated by a massive rock cliff with a cave dedicated to the Greek god Pan. Temples to Caesar and various Greco-Roman deities surrounded the area. Against this backdrop of competing religious claims, Jesus asked His disciples: 'Who do you say that I am?'\n\nPeter's answer cuts through every alternative: 'Thou art the Christ, the Son of the living God.' Jesus responds that this knowledge did not come from flesh and blood but from the Father in Heaven. The recognition of Christ as the Son of God is itself a revelation — it cannot be arrived at by human reasoning alone. It requires the witness of the Holy Ghost, a truth Paul confirmed in 1 Corinthians 12:3.\n\nJohn states the purpose of his entire Gospel in John 20:31: these things are written that you might believe that Jesus is the Christ, the Son of God, and that believing you might have life through His name. The title 'Son of God' is not one among many doctrines — it is the doctrine upon which eternal life depends.\n\nHelaman 5:12 provides the Book of Mormon's foundational statement about building upon the rock of the Redeemer, who is Christ, the Son of God. The metaphor of the rock is not incidental — it suggests permanence, immovability, and a foundation that cannot be shaken. Everything else in the gospel depends on this truth: Jesus is the Son of God.",
      patterns: "The confession-and-revelation pattern seen in Matthew 16 — a human declaring Christ's identity and Christ affirming that the knowledge came from God — appears throughout scripture: Nephi's vision (1 Ne 11), Alma's conversion (Alma 36), Joseph Smith's First Vision (JS-H 1). Divine identity is always revealed, not merely discovered.",
      reflection: "If Jesus asked you today, 'Who do you say that I am?' — what would you answer, and how would you know it was true?"
    },
    {
      label: "The Father's own declaration",
      focus: "At the baptism of Jesus, the Father spoke from heaven and declared His Son's identity. Today examines the moments when God the Father Himself testified of the Son.",
      scriptures: [{book:"Mark",ch:1,vs:1},{book:"Mark",ch:1,vs:11},{book:"Luke",ch:1,vs:35},{book:"1 Ne",ch:11,vs:18,ve:21}],
      nuances: "Mark 1:11 records the Father's voice at Jesus' baptism: 'Thou art my beloved Son, in whom I am well pleased.' The Greek 'ho huios mou ho agapētos' (my beloved Son) uses 'agapētos,' which carries the sense of 'uniquely loved' or 'one and only beloved.' This is the same word used in the Septuagint for Isaac in Genesis 22:2 — Abraham's 'only' beloved son. The Father's declaration at the baptism thus echoes the binding of Isaac and all its sacrificial overtones.",
      commentary: "Mark opens his Gospel with the most direct possible statement: 'The beginning of the gospel of Jesus Christ, the Son of God.' No genealogy, no birth narrative — just the declaration. Then at the Jordan River, the heavens open and the Father Himself speaks: 'Thou art my beloved Son, in whom I am well pleased.' This is not a prophet speaking, not an angel testifying, not a human confessing — this is God the Father Himself identifying His Son.\n\nThe Father repeats this declaration at the Transfiguration (Matt 17:5) and again to the Nephites (3 Ne 11:7). Three times in recorded scripture, the Father speaks from heaven, and each time the message is the same: This is my Son. The repetition across dispensations and continents underscores the supreme importance of this truth.\n\nLuke 1:35 records Gabriel's explanation to Mary: the Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee; therefore that holy thing which shall be born of thee shall be called the Son of God. The title is not bestowed at baptism or at some moment of spiritual achievement — it describes Christ's identity from conception. He is the Son of God by nature, not by adoption or appointment.\n\nNephi's vision in 1 Nephi 11 confirms this understanding. When Nephi sees the virgin bearing a child, the angel identifies the child as the Son of the Eternal Father. The Book of Mormon witnesses are fully aligned with the New Testament: Jesus' divine sonship is literal, originating in His relationship to God the Father.",
      patterns: "The Father's direct verbal testimony of the Son occurs at three pivotal moments: the baptism (beginning of ministry), the Transfiguration (approaching the cross), and the Nephite appearance (post-resurrection ministry). Each marks a transition point where the Son's identity must be established or reconfirmed.",
      reflection: "The Father's primary message from heaven was not a commandment or a doctrine but an identification: 'This is my Son.' Why do you think identity — knowing who Jesus is — was the Father's highest priority to communicate?"
    },
    {
      label: "For God so loved the world",
      focus: "John 3:16 is the most quoted verse in Christianity. Today explores what it actually claims about the Father, the Son, and the scope of divine love.",
      scriptures: [{book:"John",ch:3,vs:16,ve:18},{book:"1 Jn",ch:4,vs:9,ve:10},{book:"Alma",ch:36,vs:17}],
      nuances: "John 3:16 uses 'monogenēs' for 'only begotten' — a term whose meaning has been debated for centuries. In classical Greek it could mean 'unique, one of a kind' or 'only one born.' The Latter-day Saint reading takes the term literally: Jesus is the only person begotten by the Father in the flesh. This literal reading gives the verse its full sacrificial weight — God gave His actual Son, not merely a representative or agent.",
      commentary: "John 3:16 is so familiar that its radical claims can be overlooked. It asserts that God loved the world — not just Israel, not just the righteous, but the world in its fallen, rebellious state. It asserts that He loved the world enough to give His only begotten Son. And it asserts that the purpose of this gift is not condemnation but salvation: that whoever believes in Him should not perish but have everlasting life.\n\nThe title 'Son of God' in this context is inseparable from the concept of divine love. The Father's gift is not an object or a principle — it is a Person, His own Son. The costliness of the gift reveals the depth of the love. A God who gives His Son is a God whose love has no limit, because there is nothing more precious He could give.\n\n1 John 4:9–10 deepens this: God sent His only begotten Son into the world that we might live through Him. The love is defined by the sending — not that we loved God, but that He loved us and sent His Son as a propitiation for our sins. The initiative is entirely God's. The Son of God came not because humanity earned or deserved it but because the Father loved us while we were yet sinners.\n\nAlma 36:17 records Alma's conversion experience. In his darkest moment, racked with the pains of a damned soul, Alma remembered his father's teaching about Jesus Christ, the Son of God, who would atone for the sins of the world. The title 'Son of God' was the lifeline — the specific truth that pulled Alma from the jaws of destruction into the arms of mercy. This is not abstract theology. It is the most practical truth in the universe.",
      patterns: "The Father-sending-the-Son pattern appears across dispensations: the Father sends Christ in the meridian of time (John 3:16), introduces Him to the Nephites (3 Ne 11:7), presents Him in the First Vision (JS-H 1:17), and reveals Him in the degrees of glory vision (D&C 76:23). The Son is always sent by the Father, never self-appointed.",
      reflection: "Alma's entire conversion turned on remembering that Jesus Christ is the Son of God. When have you needed to remember this truth most urgently, and what difference did it make?"
    },
    {
      label: "He claimed it Himself",
      focus: "Jesus did not merely accept the title Son of God from others — He claimed it directly. Today examines the occasions when Christ asserted His own divine sonship.",
      scriptures: [{book:"John",ch:10,vs:36},{book:"D&C",ch:93,vs:21},{book:"Moses",ch:4,vs:2}],
      nuances: "In John 10:36, Jesus says 'I am the Son of God' after being accused of blasphemy for saying 'I and my Father are one' (John 10:30). The religious leaders understood precisely what He was claiming — not mere moral alignment with God, but actual divine sonship. Their response was to pick up stones, confirming that they heard a claim to deity, not merely to prophetic office.",
      commentary: "It is one thing for others to call Jesus the Son of God. It is another for Him to claim the title Himself. John 10:36 records Him doing exactly that, in the most confrontational possible setting. The Jewish leaders are accusing Him of blasphemy, and His response is not to soften the claim but to sharpen it: 'Say ye of him, whom the Father hath sanctified, and sent into the world, Thou blasphemest; because I said, I am the Son of God?'\n\nThe claim was either true or it was the most audacious blasphemy ever spoken. There is no middle ground. The leaders understood this, which is why they sought to kill Him. The title 'Son of God' was not a comfortable religious designation — it was a claim that divided audiences and ultimately led to the cross.\n\nD&C 93:21 provides a Restoration witness: Christ was 'in the beginning with the Father' and is 'the Firstborn.' This locates Christ's sonship in the premortal existence — before Bethlehem, before the world was created. His relationship to the Father did not begin at the Incarnation; it stretches back into eternity.\n\nMoses 4:2 records the premortal council where the Father's Beloved Son said, 'Father, thy will be done, and the glory be thine forever.' In this foundational moment, the Son of God identifies Himself not by asserting power but by submitting to the Father's will. His sonship is characterized by both divine authority and perfect obedience — the two are not in tension but are mutually reinforcing.",
      patterns: "Christ's self-identification as the Son of God follows a consistent pattern: He never claims the title to impress or dominate but always in the context of revealing truth and calling people to faith. His identity claims are invitations, not threats — even when they provoke violent opposition.",
      reflection: "Jesus' claim to be the Son of God left no room for neutrality — people had to accept or reject it. How fully have you reckoned with the implications of this claim?"
    },
    {
      label: "The Son who reveals the Father",
      focus: "One of the most important functions of the Son of God is to reveal the Father. Today examines how knowing the Son is the only way to know the Father.",
      scriptures: [{book:"Heb",ch:1,vs:1,ve:5},{book:"John",ch:14,vs:9},{book:"Mosiah",ch:15,vs:1,ve:4}],
      nuances: "Hebrews 1:3 describes the Son as 'the brightness of his glory, and the express image of his person' — the Greek 'charaktēr tēs hupostaseōs autou' means the exact impress or stamp of His underlying reality. 'Charaktēr' originally referred to the impression made by a signet ring or die — a perfect reproduction of the original. To see the Son is to see the exact imprint of the Father's nature.",
      commentary: "Hebrews 1 opens with a sweeping declaration: God, who spoke through prophets in many ways across many ages, has now spoken through His Son. The Son is the heir of all things, the one through whom the worlds were made, the brightness of God's glory, and the express image of His person. The Son does not merely represent the Father — He reveals the Father's actual nature with perfect fidelity.\n\nJesus makes this explicit in John 14:9: 'He that hath seen me hath seen the Father.' This is not a claim to be the Father (a heresy called modalism) but a claim that the Son so perfectly reveals the Father that to know one is to know the other. If you want to understand what God the Father is like — His character, His priorities, His way of relating to people — look at Jesus Christ.\n\nMosiah 15:1–4 presents Abinadi's teaching that Christ is both the Father and the Son — the Father because of the Spirit, and the Son because of the flesh. This passage has generated much discussion in Latter-day Saint theology. It is not teaching that the Father and Son are the same being (the First Vision and D&C 130:22 establish their separateness) but that Christ, as the Son of God, so fully embodies the Father's will and character that He functions with the Father's authority. He acts as the Father in the work of creation and redemption.\n\nThe practical implication is extraordinary: every act of Jesus recorded in the Gospels — healing, forgiving, teaching, weeping, serving — reveals the character of God the Father. The Father is not an unknowable distant deity. He has made Himself known through His Son.",
      patterns: "The Son-reveals-the-Father principle operates across all dispensations. Adam learned of the Father through the Son's commandments. Moses saw the Son and learned of the Father's plan. The Nephites received the Father's testimony of the Son. In every case, the Son is the accessible face of the Godhead.",
      reflection: "If to see Jesus is to see the Father, which aspect of Christ's character most shapes your understanding of what God the Father is like?"
    },
    {
      label: "Tested as the Son of God",
      focus: "Satan's temptations in the wilderness each began with 'If thou be the Son of God.' Today examines how Christ's divine identity was tested and what that means for our own.",
      scriptures: [{book:"Matt",ch:4,vs:3},{book:"Matt",ch:4,vs:6},{book:"Matt",ch:27,vs:40},{book:"2 Ne",ch:25,vs:19}],
      nuances: "In Matthew 4:3 and 4:6, Satan says 'If thou be the Son of God' — the Greek 'ei huios ei tou theou' uses a first-class conditional, which assumes the condition is true. Satan is not questioning whether Jesus is the Son of God; he is assuming it and suggesting that being the Son of God entitles Him to use divine power for selfish purposes. The temptation is not doubt but misuse of a true identity.",
      commentary: "The wilderness temptations reveal something crucial about what it means to be the Son of God. Satan does not tempt Jesus to deny His identity — he tempts Him to abuse it. 'If you are the Son of God, turn stones to bread. If you are the Son of God, throw yourself from the temple. I will give you all the kingdoms of the world.' Each temptation assumes Christ's divine sonship and proposes a distorted expression of it.\n\nJesus' responses define what true sonship looks like. The Son of God lives by every word from the Father's mouth, not by bread alone. The Son of God does not test the Father's protection through reckless presumption. The Son of God worships and serves only the Father, not rival powers offering shortcuts to glory. True divine sonship is expressed through obedience, trust, and exclusive loyalty — not through displays of power.\n\nThe same temptation appears at the cross in Matthew 27:40: those passing by mocked Him, saying, 'If thou be the Son of God, come down from the cross.' Again, the challenge assumes His identity and proposes a distorted expression of it. And again, Jesus refuses — not because He lacks the power to descend but because remaining on the cross is what the Son of God came to do.\n\n2 Nephi 25:19 affirms that the Messiah will come in the fullness of time to redeem the children of men from the fall. Nephi frames Christ's mission in terms of its purpose: redemption. The Son of God did not come to prove Himself through spectacle but to save humanity through sacrifice.",
      patterns: "The pattern of identity-tested-by-temptation applies not only to Christ but to every covenant disciple. When you are tempted, the fundamental question is often not 'Will you sin?' but 'Who are you?' — a child of God, or something less? Christ's response to temptation is the model for our own.",
      reflection: "Satan tempted Jesus to misuse His identity as the Son of God. In what ways are you tempted to forget or misuse your own identity as a child of God?"
    },
    {
      label: "Sons and daughters through the Son",
      focus: "Because Christ is the Son of God, we can become sons and daughters of God through Him. Today explores how His sonship opens the door for ours.",
      scriptures: [{book:"1 Jn",ch:4,vs:15},{book:"Mosiah",ch:5,vs:7},{book:"D&C",ch:93,vs:21,ve:22}],
      nuances: "1 John 4:15 states that 'whosoever shall confess that Jesus is the Son of God, God dwelleth in him, and he in God.' The Greek 'menei en autō' (dwelleth in him) uses 'menō,' a word that means to abide, remain, or make one's home. Confessing Christ as the Son of God is not a one-time declaration — it initiates an ongoing mutual indwelling between the believer and God.",
      commentary: "The week's study culminates in a truth that extends Christ's sonship to every disciple. Because He is the Son of God, we can become sons and daughters of God through Him. This is not metaphor — it is the central promise of the gospel.\n\n1 John 4:15 makes the connection: confessing that Jesus is the Son of God results in God dwelling in you and you in God. The acknowledgment of Christ's divine identity opens a relationship of mutual indwelling — the most intimate possible connection between the human soul and the divine.\n\nMosiah 5:7 provides King Benjamin's declaration: those who have entered the covenant are called the children of Christ. They are spiritually begotten through faith in His name. Christ's sonship becomes the mechanism of our adoption — we become children of God through the Son of God. His relationship with the Father is not exclusive; it is the door through which we enter our own relationship with the Father.\n\nD&C 93:21–22 completes the picture with breathtaking directness: Christ was in the beginning with the Father, and we were also in the beginning with the Father. What is received in fullness by Christ is offered to all who keep the commandments. The gap between Christ's sonship and our potential sonship is real — He is the Only Begotten in the flesh (Week 31 will explore this) — but the trajectory is the same: from child of God to heir of all the Father has.\n\nThis is the ultimate implication of the title 'Son of God.' It is not merely a statement about Christ's identity — it is a revelation about human destiny. If God has a Son, then sonship with God is real. And if sonship with God is real, then everything the Son has can be shared with those who enter the covenant.",
      patterns: "The adoption-through-covenant pattern runs from Mosiah 5 (becoming children of Christ through covenant) through Romans 8 (heirs and joint-heirs with Christ) to D&C 93 (receiving the fullness of the Father). Christ's sonship is not a status He hoards — it is a relationship He shares.",
      reflection: "Christ is the Son of God by nature; you are a child of God by creation and can become an heir by covenant. How does this understanding of your divine identity influence how you live day to day?"
    }
  ]
};

export default week29;
