import type { WeekContent } from '../types';

const week45: WeekContent = {
  title: "Seed of Christ — His Spiritual Posterity",
  subtitle: "Christ has children — not biologically, but covenantally. All who are born again through Him become His seed.",
  weekScriptures: "John 3:3-7; Mosiah 4:2-3; Alma 22:15; D&C 11:30; Isa 53:8; 2 Cor 5:17; Eph 2:19; Mosiah 5:11-12; Heb 2:11-13; D&C 35:2; Alma 7:14",
  synthesis: {
    summary: "Isaiah prophesied that the Messiah would 'see his seed' despite dying without mortal posterity. Abinadi's inspired commentary reveals that Christ's seed are those who receive His gospel, are born again through His Atonement, and take upon them His name through covenant. This week explores the profound truth that through faith, repentance, and baptism, we become the children of Christ — heirs of His promises, bearers of His name, and participants in His eternal family.",
    connections: [
      "The new birth studied here is made possible by the Atonement (Weeks 14–15) — without His suffering and death, there would be no power to change human nature.",
      "Taking upon us Christ's name (Week 23) is the covenant mechanism by which we become His seed.",
      "The Abrahamic covenant (Week 9) promised that Abraham's seed would bless all nations — Christ is that seed, and through Him, we become Abraham's seed too (Galatians 3:29)."
    ],
    teaching: "What is the difference between believing in Christ and becoming His child? How does the doctrine of spiritual rebirth change your understanding of what it means to be a Christian?",
    commitment: "This week, reflect on the moment you took upon yourself the name of Christ in baptism. What does it mean to you now to be called His?"
  },
  days: [
    {
      label: "He shall see His seed",
      focus: "Isaiah's Messianic servant would die without mortal children, yet the prophet says He would 'see his seed.' Today explores who those children are.",
      scriptures: [{book:"Isa",ch:53,vs:10,ve:11},{book:"Mosiah",ch:15,vs:10,ve:13},{book:"D&C",ch:76,vs:24}],
      nuances: "In Isaiah 53:10, the Hebrew 'zera' (seed) normally refers to biological descendants. Its application to the suffering servant creates a theological puzzle: how does a man who is 'cut off out of the land of the living' (v. 8) have posterity? Abinadi's commentary in Mosiah 15 provides the most detailed scriptural answer to this question.",
      commentary: "Isaiah 53 is the great suffering-servant chapter — a prophecy of Christ's Atonement so detailed that some early Christian writers considered Isaiah a fifth Gospel. Verse 10 presents a paradox: after the servant's soul is made an offering for sin, 'he shall see his seed, he shall prolong his days.' How does a man who dies have children and long life?\n\nAbinadi, speaking before the wicked priests of King Noah, provides the answer that unlocks the passage. Christ's seed are the prophets and all who have hearkened to their words — everyone who has believed in the Lord and looked forward to a remission of sins. These are His seed. They are His spiritual offspring, born not of flesh but of covenant.\n\nD&C 76:24 extends this even further: the inhabitants of the worlds that Christ created are 'begotten sons and daughters unto God.' The scope of Christ's spiritual posterity is not limited to one planet or one dispensation. Every soul who accepts His Atonement, in any world, becomes His child.\n\nThis reframes your entire relationship with Christ. He is not only your Savior and Redeemer — He is, in a covenantal sense, your Father. When you pray, serve, and worship, you do so as a child of Christ.",
      patterns: "The Atonement produces not only forgiveness but identity. This is a recurring pattern: Christ does not merely fix what is broken in us — He transforms who we are. We become new creatures, new children, new heirs.",
      reflection: "How does it change your sense of identity to know that through the Atonement, Christ considers you His child — not metaphorically, but covenantally?"
    },
    {
      label: "Born again as His children",
      focus: "The doctrine of the new birth is not just a New Testament teaching — it appears with power in the Book of Mormon. Today explores what it means to be spiritually reborn.",
      scriptures: [{book:"Mosiah",ch:27,vs:24,ve:26},{book:"Alma",ch:5,vs:14},{book:"John",ch:1,vs:12,ve:13}],
      nuances: "Mosiah 27:25 uses the language of birth — 'born of God' — not as a metaphor for improvement but as a description of ontological change. Alma's later question in Alma 5:14, 'Have ye spiritually been born of God?', uses the perfect tense in the underlying meaning: have you undergone this transformation? It is an event, not merely a process.",
      commentary: "Alma the Younger's conversion is one of the most dramatic in all scripture. Struck down by an angel, passing through agonizing spiritual torment, he emerged declaring that he had been 'born of God.' His description in Mosiah 27:24–26 is vivid: every person must be born again — changed from a carnal and fallen state to a state of righteousness. This is not self-improvement; it is divine recreation.\n\nAlma 5:14 takes this personal experience and turns it into a question for an entire congregation: Have you experienced this mighty change of heart? Have you received His image in your countenance? The question implies that the new birth is visible — that it changes not only what you feel inside but how you appear to others. People can see Christ in you.\n\nJohn 1:12–13 connects directly: to all who received Christ, He gave power to become the sons of God — born not of blood, nor of the will of the flesh, but of God. This spiritual birth transcends biology, nationality, and social status. Anyone who receives Christ becomes His child.\n\nThe new birth is the mechanism by which we become the 'seed' of Isaiah 53. Christ's suffering produces children — not through biology but through the transforming power of His Atonement applied to individual hearts.",
      patterns: "The new birth appears across dispensations: Nicodemus heard it from Jesus (John 3), the Nephites experienced it under King Benjamin (Mosiah 5), Alma testified of it personally, and modern revelation confirms it (D&C 5:16). The consistency of this doctrine across time and scripture is evidence of its importance.",
      reflection: "Alma asks: 'Have ye spiritually been born of God?' How would you answer that question today? Is the new birth something you have experienced once, or something you are still experiencing?"
    },
    {
      label: "Taking upon us His name",
      focus: "Becoming Christ's seed is not only an internal experience — it is a covenant act. Today examines the connection between the new birth and the covenant of baptism.",
      scriptures: [{book:"Mosiah",ch:5,vs:7,ve:10},{book:"Mosiah",ch:18,vs:8,ve:10},{book:"D&C",ch:25,vs:1}],
      nuances: "In Mosiah 5:7, King Benjamin says those who have made the covenant are 'called the children of Christ, his sons, and his daughters.' The Hebrew and Nephite naming convention carried legal and identity implications — to be called by someone's name meant to belong to their household and to be under their protection and authority.",
      commentary: "King Benjamin's address is one of the most theologically rich passages in the Book of Mormon. After his people experienced the mighty change of heart, he established a covenant: they took upon themselves the name of Christ. In doing so, they became His children. The name is not a label — it is an identity.\n\nMosiah 5:8–10 develops the consequences: those who take His name and keep the covenant will be found at God's right hand. Those who transgress and do not repent will find the name blotted out. The covenant creates a real relationship with real consequences — belonging to Christ means accountability to Christ.\n\nMosiah 18 records the baptismal covenant at the waters of Mormon: to bear one another's burdens, mourn with those who mourn, comfort those who stand in need of comfort, and stand as witnesses of God. These are the terms of becoming Christ's seed through baptism.\n\nD&C 25:1 addresses Emma Smith — and through her, every member — with the identity statement: 'thou art an elect lady, whom I have called.' To be called of Christ is to be chosen, named, and claimed. This is not honorary. It changes who you are.\n\nThe connection between covenant, name, and identity is at the heart of Latter-day Saint theology. Every time we partake of the sacrament, we renew our willingness to take upon us His name — to remain His children.",
      patterns: "The covenant pattern — name, identity, belonging — runs through every dispensation. Adam was given a name, Abraham was renamed, Israel was named, and Christ's followers are called by His name. The pattern of naming is a pattern of ownership and love.",
      reflection: "When you partake of the sacrament and renew your covenant to take upon you the name of Christ, what does that moment mean to you? Is it routine, or is it a renewal of identity?"
    },
    {
      label: "Heirs through covenant",
      focus: "If we are Christ's seed, we are also heirs. Today explores the inheritance that belongs to the children of Christ.",
      scriptures: [{book:"Rom",ch:8,vs:14,ve:17},{book:"Gal",ch:3,vs:26,ve:29},{book:"D&C",ch:84,vs:33,ve:40}],
      nuances: "Paul's language in Romans 8:17 is extraordinary: 'joint-heirs with Christ.' The Greek 'synklēronomoi' means co-inheritors — sharing the same inheritance equally. Paul does not say we receive a lesser portion or a derivative blessing. We inherit with Christ, the same glory, the same exaltation.",
      commentary: "Paul's letter to the Romans builds a breathtaking argument: if we are children of God, then we are heirs — heirs of God and joint-heirs with Christ. The inheritance is not a distant reward but a present identity. You are already a child; you are already an heir. The inheritance is realized as you remain faithful.\n\nGalatians 3:26–29 adds a critical dimension: in Christ, there is neither Jew nor Greek, bond nor free, male nor female — all are one in Christ Jesus, and if ye be Christ's, then ye are Abraham's seed and heirs according to the promise. The Abrahamic covenant, studied earlier in this plan, finds its universal application here. Through Christ, every person of every background can become a covenant heir.\n\nD&C 84:33–40, the oath and covenant of the priesthood, describes the inheritance in Restoration terms: those who magnify their callings are sanctified by the Spirit, receive the Father's kingdom, and all that the Father hath is given them. This is the most expansive promise in all scripture.\n\nThe doctrine of inheritance transforms how you understand your own worth and potential. You are not a servant begging for scraps — you are a child of the King, a joint-heir with the Son. Everything the Father has is offered to you through covenant faithfulness.",
      patterns: "The inheritance theme connects to the parable of the prodigal son (Luke 15) — the father's goods were already the son's. He only needed to come home. The entire gospel is structured as an invitation to receive what is already yours through Christ.",
      reflection: "Paul says you are a 'joint-heir with Christ.' How does that status shape the way you see yourself — not in pride, but in gratitude and responsibility?"
    },
    {
      label: "The mighty change of heart",
      focus: "Becoming Christ's seed requires transformation, not just information. Today explores the internal change that marks the new birth.",
      scriptures: [{book:"Alma",ch:5,vs:14},{book:"Mosiah",ch:5,vs:1,ve:5},{book:"Alma",ch:36,vs:23,ve:26}],
      nuances: "Alma 5:14 asks whether you have 'received his image in your countenances.' The word 'image' in this context suggests more than appearance — it implies that the person of Christ becomes visible in the disciple. The Greek 'eikōn' (image), used in related New Testament passages, carries the sense of an exact representation.",
      commentary: "Alma's great sermon in Alma 5 is structured around a single, penetrating question: have you experienced the mighty change of heart? He is not asking whether his listeners have been baptized, attended the synagogue, or performed the right rituals. He is asking whether they have been fundamentally changed from the inside out.\n\nMosiah 5:1–5 records the moment when King Benjamin's people experienced this change: the Spirit wrought a mighty change in their hearts, and they had no more disposition to do evil but to do good continually. This is not willpower or moral effort — it is a gift of the Spirit that transforms desire itself. They did not want to sin anymore.\n\nAlma 36:23–26 is Alma's personal testimony of this change. After his anguished repentance, he saw God sitting on His throne, and his soul longed to be there. From that moment, he labored without ceasing to bring souls to repentance, that they might experience the same joy. The mighty change produces not only personal peace but missionary urgency.\n\nThe mighty change of heart is not a one-time event for most people. It begins at conversion, deepens through covenant keeping, and matures over a lifetime. The question 'Have ye been born of God?' is one you should ask yourself regularly — not with anxiety but with honest self-examination.",
      patterns: "The mighty change appears in every age: Enos experienced it in solitary prayer, King Benjamin's people experienced it in communal worship, Paul experienced it on the road to Damascus, and Joseph Smith experienced it in the Sacred Grove. The circumstances vary; the result is the same — a new heart.",
      reflection: "King Benjamin's people had 'no more disposition to do evil.' Have you ever experienced even a moment of that kind of change? What brought it about?"
    },
    {
      label: "Abraham's seed through Christ",
      focus: "Paul teaches that those who belong to Christ are Abraham's seed. Today explores how Christ connects the Abrahamic covenant to every believer.",
      scriptures: [{book:"Gal",ch:3,vs:26,ve:29},{book:"Abr",ch:2,vs:9,ve:11},{book:"D&C",ch:39,vs:4},{book:"3 Ne",ch:9,vs:17}],
      nuances: "Abraham 2:10 contains a remarkable phrase: 'as many as receive this Gospel shall be called after thy name, and shall be accounted thy seed.' The word 'accounted' means reckoned or legally considered. It implies that Abrahamic lineage is not merely biological but covenantal — one is adopted into the family through accepting the gospel.",
      commentary: "Paul's argument in Galatians 3 is revolutionary: the promise made to Abraham was ultimately about Christ. Abraham's seed, in the singular and most important sense, is Christ Himself. And if you belong to Christ, then you are Abraham's seed and heirs according to the promise. Biology is transcended by covenant.\n\nAbraham 2:9–11, from the Pearl of Great Price, provides the Restoration's expanded understanding of the Abrahamic covenant. Those who receive the gospel are accounted Abraham's seed. They bear the priesthood and carry the responsibility to bless all the families of the earth. This is not passive inheritance — it is active mission.\n\nD&C 39:4 and 3 Nephi 9:17 both affirm that to as many as received Christ, He gave power to become the sons of God. The invitation is universal. No one is excluded by birth, nationality, or past. The only criterion is receiving Christ.\n\nThis doctrine demolishes every form of spiritual elitism. You do not need the right ancestry, the right culture, or the right background to become a child of God and a seed of Abraham. You need Christ. Through Him, the narrowest covenant in the Old Testament — the covenant with one man's family — becomes the widest embrace in the universe.",
      patterns: "The seed of Abraham multiplies through covenant, not biology. This is the same pattern as the seed of Christ: spiritual children created by spiritual rebirth. Covenant is the great equalizer, the mechanism by which God's family grows without limit.",
      reflection: "Abraham was promised that his seed would bless all nations. If you are his seed through Christ, what does that mission mean for you personally?"
    },
    {
      label: "Becoming like Him",
      focus: "The ultimate destiny of Christ's seed is not merely to be saved but to become like Him. Today explores the doctrine of divine potential.",
      scriptures: [{book:"Ether",ch:3,vs:14},{book:"Moro",ch:7,vs:48},{book:"1 Jn",ch:3,vs:1,ve:3},{book:"D&C",ch:76,vs:58,ve:62}],
      nuances: "1 John 3:2 says 'when he shall appear, we shall be like him; for we shall see him as he is.' The Greek 'homoioi autō esometha' means 'we shall be similar to him' — not identical but of the same kind. The promise is that Christ's children will share in His nature, His glory, and His joy.",
      commentary: "The brother of Jared received a stunning revelation: Jesus Christ appeared to him in His premortal spirit body and declared, 'I am the Father and the Son.' Ether 3:14 is one of the most intimate encounters with deity in all scripture. Christ reveals Himself personally to those who exercise great faith — and what they see is what they are becoming.\n\nMoroni 7:48 teaches us to pray with all the energy of heart that we may be filled with the love of Christ and that 'when he shall appear we shall be like him.' This is not a distant hope — it is the purpose of the entire gospel. The seed of Christ does not merely receive His blessings; it grows into His likeness.\n\n1 John 3:1–3 echoes the same truth: we are now the sons of God, and it does not yet appear what we shall be, but we know that when He appears, we shall be like Him. The transformation is ongoing and will reach its completion at His coming.\n\nD&C 76:58–62 describes those who inherit the celestial kingdom as priests and kings, gods and goddesses, who dwell in the presence of God and Christ forever. This is the fullest expression of what it means to be Christ's seed: not merely to be saved but to be exalted, to receive all that the Father has, to become as He is. This is the destiny of covenant children.",
      patterns: "The entire fifty-week study has traced the identity, mission, and glory of Jesus Christ. The doctrine of His seed reveals that His glory is not for Himself alone — it is shared with every child who comes unto Him. The story of Christ is, ultimately, your story too.",
      reflection: "Moroni says to pray 'with all the energy of heart' that you may become like Christ. What attribute of His do you most want to develop in yourself?"
    }
  ]
};

export default week45;
