import type { WeekContent } from '../types';

const week33: WeekContent = {
  title: "Relationship with the Father — One in Purpose, Distinct in Person",
  subtitle: "Christ's relationship with God the Father is the most important relationship in the universe — and the model for every other.",
  weekScriptures: "John 17:1–5; John 10:30; John 14:28; John 5:30; 3 Ne 11:27; Matt 26:39; John 8:28–29; D&C 130:22; Philip 2:5–11; 1 Cor 15:24–28; Mosiah 15:1–7; 3 Ne 19:23; D&C 93:3–5; Moses 1:6; John 14:9–11; Heb 1:3; Luke 22:42; 3 Ne 28:10",
  synthesis: {
    summary: "This week examines the profound relationship between Jesus Christ and His Father. Scripture reveals that they are perfectly united in purpose, will, and love — yet distinct as individual beings. Christ consistently defers to the Father, credits the Father, and seeks the Father's glory. This relationship is not merely theological information; it is the pattern for our own relationship with God. Christ's perfect submission to the Father's will is the engine that drives the entire plan of salvation.",
    connections: [
      "Week 32's study of divine sonship provides the foundation — Christ relates to the Father as a Son because He literally is one.",
      "The unity between Father and Son modeled here connects to Week 35's study of the Second Comforter and Week 34's exploration of the Spirit of Christ.",
      "Christ's submission in Gethsemane (studied this week) connects directly to Week 12's deeper examination of the Atonement."
    ],
    teaching: "Christ said 'I and my Father are one' and also 'My Father is greater than I.' How do both statements be true simultaneously? What does this teach about the nature of divine unity?",
    commitment: "This week, study your own relationship with God the Father. Does your prayer life reflect the same pattern Christ modeled — reverent, trusting, and submissive to the Father's will?"
  },
  days: [
    {
      label: "Perfect unity",
      focus: "Christ and the Father are one — but in what sense? Today examines the scriptural claim of their unity and what it actually means.",
      scriptures: [{book:"John",ch:10,vs:30},{book:"3 Ne",ch:11,vs:27},{book:"D&C",ch:130,vs:22}],
      nuances: "In John 10:30, 'I and my Father are one,' the Greek 'hen esmen' uses the neuter 'hen' (one thing) rather than the masculine 'heis' (one person). Grammatically, this suggests unity of purpose, will, or essence — not identity of person. This distinction was central to the Trinitarian debates of the fourth century.",
      commentary: "When Christ declared 'I and my Father are one,' His audience picked up stones. They understood He was claiming divinity. But the nature of that oneness has been debated for two millennia. Is it ontological oneness (one being in three persons, as Nicene theology holds) or volitional oneness (two distinct beings perfectly united in purpose)?\n\n3 Nephi 11:27 provides Restoration clarity: 'The Father, and the Son, and the Holy Ghost are one; and I am in the Father, and the Father in me.' This unity is relational and purposive. They are one in testimony, one in mission, one in love — and yet distinct.\n\nD&C 130:22 makes the distinction explicit: 'The Father has a body of flesh and bones as tangible as man's; the Son also.' This verse, along with the First Vision account, establishes that the Father and the Son are separate, embodied beings. Their unity is therefore the most remarkable kind — not the unity of a single entity but the freely chosen, perfect alignment of two sovereign wills.\n\nThis understanding has profound implications. If divine unity were simply a matter of metaphysical identity, it would have no moral content. But if it is the perfect harmony of two wills, it becomes the highest expression of love and the model for every covenant relationship.",
      patterns: "The principle of oneness through covenant alignment recurs throughout scripture — in marriage, in priesthood quorums, in Zion. Christ and the Father model what perfect relational unity looks like.",
      reflection: "If the highest beings in the universe achieve unity not by erasing distinction but by perfectly aligning their wills, what does that suggest about your own relationships — with God and with others?"
    },
    {
      label: "The Son submits",
      focus: "Christ never acted independently. He always deferred to the Father. Today explores this radical submission and what it reveals about divine character.",
      scriptures: [{book:"John",ch:5,vs:30},{book:"John",ch:8,vs:28,ve:29},{book:"Matt",ch:26,vs:39}],
      nuances: "In John 5:30, 'I can of mine own self do nothing' uses the Greek 'ou dunamai' — literally 'I am not able.' This is not false modesty. Christ is making an ontological claim about the nature of His mission: it is structurally dependent on the Father's will. His power is real but exercised only within the framework of the Father's purposes.",
      commentary: "John 5:30 is one of the most striking statements Christ ever made: 'I can of mine own self do nothing: as I hear, I judge: and my judgment is just; because I seek not mine own will, but the will of the Father which hath sent me.' The most powerful being to walk the earth claimed He could do nothing alone. This is not weakness — it is the highest form of strength: the voluntary restraint of power in deference to the Father.\n\nJohn 8:28–29 deepens this: Christ does nothing of Himself but speaks as the Father taught Him. And then the remarkable statement — 'the Father hath not left me alone; for I do always those things that please him.' The Son's constant obedience is met with the Father's constant presence. Obedience and divine companionship are inseparable.\n\nMatthew 26:39 brings this submission to its most agonizing expression: 'O my Father, if it be possible, let this cup pass from me: nevertheless not as I will, but as thou wilt.' In Gethsemane, the Son's will and the Father's will were not identical in desire — Christ did not want to suffer. But they were perfectly aligned in commitment. Christ chose the Father's will over His own natural recoil from infinite pain.\n\nThis is the pattern of all discipleship: not the absence of personal desire, but the subordination of it to God's purposes.",
      patterns: "Christ's submission in Gethsemane echoes His premortal 'thy will be done' (Moses 4:2, studied in Week 32). The pattern is consistent from the council in heaven to the garden. He has always chosen the Father's will.",
      reflection: "Is there an area of your life where you sense a gap between your will and God's? How does Christ's example in Gethsemane — acknowledging His own desire while choosing the Father's will — speak to that tension?"
    },
    {
      label: "The Father glorifies the Son",
      focus: "The relationship is not one-directional. The Father actively glorifies, sustains, and testifies of the Son. Today explores the Father's side of the relationship.",
      scriptures: [{book:"John",ch:17,vs:1,ve:5},{book:"Philip",ch:2,vs:5,ve:11},{book:"Heb",ch:1,vs:3}],
      nuances: "In John 17:5, Christ asks the Father to glorify Him 'with the glory which I had with thee before the world was.' The Greek 'para seautō' (with you, at your side) suggests physical proximity and shared experience. Christ is asking to return to a state of closeness with the Father that preceded creation itself.",
      commentary: "John 17 is called the High Priestly Prayer — Christ's most extended prayer to the Father recorded in scripture. In verses 1–5, He asks the Father to glorify Him so that He might glorify the Father. The relationship is reciprocal: the Son seeks the Father's glory, and the Father glorifies the Son in return. There is no competition, no jealousy, no self-seeking — only mutual exaltation.\n\nPhilippians 2:5–11 describes the great arc of Christ's mission: He was in the form of God, emptied Himself, became a servant, was obedient unto death — and therefore God highly exalted Him and gave Him a name above every name. The Father's response to the Son's submission is not indifference but supreme exaltation. The humility of the Son is met with the honor of the Father.\n\nHebrews 1:3 captures this in a single, dense phrase: Christ is 'the brightness of his glory, and the express image of his person.' The Greek 'charaktēr tēs hupostaseōs' means the exact imprint of His being — like a seal pressed into wax. The Son perfectly represents the Father. To see the Son is to see what the Father is like.\n\nThe Father does not begrudge the Son His glory. The Son does not hoard it. This is the economy of divine love: glory shared is glory multiplied.",
      patterns: "The pattern of humiliation followed by exaltation — Christ descends, then the Father raises Him up — recurs throughout scripture and is the template for the covenant path itself. We descend into the waters of baptism; God raises us to newness of life.",
      reflection: "Do you tend to think of God the Father as distant or involved? How does seeing the Father actively glorifying and sustaining the Son change your picture of the Father's character?"
    },
    {
      label: "The Son reveals the Father",
      focus: "Christ is not just sent by the Father — He makes the Father known. Today explores Christ as the revelation of who God the Father truly is.",
      scriptures: [{book:"John",ch:14,vs:9,ve:11},{book:"Moses",ch:1,vs:6},{book:"D&C",ch:93,vs:3,ve:5}],
      nuances: "In John 14:9, 'He that hath seen me hath seen the Father,' the Greek 'heōraken' (has seen) is in the perfect tense — indicating completed action with continuing results. Philip's encounter with Christ has given him a lasting, ongoing vision of the Father. Seeing Christ is not a momentary glimpse but a permanent revelation.",
      commentary: "Philip asked Jesus to show them the Father, and Jesus responded with gentle surprise: 'Have I been so long time with you, and yet hast thou not known me, Philip? He that hath seen me hath seen the Father.' This is not a claim that the Father and Son are the same person. It is a claim that the Son so perfectly embodies the Father's character, will, and love that to know one is to know the other.\n\nMoses 1:6 records God speaking to Moses: 'I have a work for thee, Moses, my son; and thou art in the similitude of mine Only Begotten.' Even Moses, one of the greatest prophets, is described in relation to Christ. The Only Begotten is the standard against which all things are measured — including human identity.\n\nD&C 93:3–5 teaches that Christ received a fulness of the glory of the Father, and that anyone who is faithful shall receive of His fulness. The revelation of the Father through the Son is not merely informational — it is transformational. As we come to know the Son, we come to know the Father, and that knowledge changes us.\n\nThis has practical devotional significance. When you read the Gospels and see Christ healing, teaching, forgiving, and weeping, you are seeing a portrait of the Father. The Father's heart is revealed in every act of the Son.",
      patterns: "The principle that the Son reveals the Father connects to Week 1's opening study of Christ's identity and forward to Week 34's exploration of the Spirit of Christ — the means by which this revelation continues after Christ's ascension.",
      reflection: "If you want to know what God the Father is like, look at Jesus Christ. Which moment in Christ's mortal ministry most powerfully reveals the Father's character to you?"
    },
    {
      label: "Greater than I",
      focus: "Christ said 'My Father is greater than I.' Today explores what this statement means and how it relates to the doctrine of divine unity.",
      scriptures: [{book:"John",ch:14,vs:28},{book:"1 Cor",ch:15,vs:24,ve:28},{book:"3 Ne",ch:28,vs:10}],
      nuances: "In John 14:28, 'My Father is greater than I' uses the Greek 'meizōn' (greater) — which can denote greater in rank, position, or authority rather than greater in nature or essence. This was a key text in the Arian controversy, with different sides reading it differently. Restoration theology reads it straightforwardly: the Father holds a position of primacy.",
      commentary: "Christ's statement that the Father is greater than Him has puzzled theologians for centuries. In Nicene theology, which affirms that the Father and Son are of the same substance, this verse requires careful qualification. In Restoration theology, it is taken at face value: the Father occupies a position of authority and primacy within the Godhead, and the Son willingly honors that order.\n\n1 Corinthians 15:24–28 provides Paul's vision of the end: Christ will deliver up the kingdom to the Father, having subdued all enemies, and the Son Himself shall be subject to the Father, 'that God may be all in all.' Even in the final triumph, the Son defers to the Father. The hierarchy of love is eternal.\n\n3 Nephi 28:10 records Christ's promise to His Nephite disciples that they will come unto the Father and experience a fulness of joy. The Father is the ultimate destination — and Christ is the way to reach Him. Christ does not position Himself as the final end but as the path to the Father.\n\nThis ordering is not a diminishment of Christ. It is, in fact, the source of His greatness. The willingness to subordinate Himself to the Father — not out of compulsion but out of love and perfect trust — is the very quality that makes Him worthy of all honor. His humility before the Father is the foundation of His authority over all else.",
      patterns: "The principle that authority comes through submission, not self-assertion, runs throughout scripture. Christ's relationship with the Father models this perfectly. The same principle applies to priesthood holders, parents, and leaders in God's kingdom.",
      reflection: "In a culture that prizes independence and self-assertion, what does Christ's voluntary deference to the Father teach you about true greatness?"
    },
    {
      label: "Intercessor with the Father",
      focus: "Christ does not merely point us toward the Father — He actively intercedes on our behalf. Today examines His role as our advocate.",
      scriptures: [{book:"John",ch:17,vs:1,ve:5},{book:"3 Ne",ch:19,vs:23},{book:"D&C",ch:45,vs:3,ve:5}],
      nuances: "In John 17, the verb 'ask' (Greek 'erōtaō') is used rather than 'aitēo.' In Koine Greek, 'erōtaō' often implies a request made between equals or from a position of relationship, while 'aitēo' can suggest a petition from an inferior. Christ's prayer to the Father carries the tone of intimate, relational communication — not distant supplication.",
      commentary: "John 17 is the most sustained intercessory prayer in scripture. Christ prays not only for His immediate disciples but for all who would believe through their word — that includes us. His prayer is that we might be one, as He and the Father are one. The unity between Father and Son is not a private arrangement; it is the prototype for what Christ wants for every believer.\n\n3 Nephi 19:23 records a similar prayer in the New World: Christ prays to the Father for His Nephite followers, asking that the Father would give them the Holy Ghost. Even after His resurrection, Christ's posture before the Father is one of petition on behalf of His people.\n\nD&C 45:3–5 gives perhaps the most tender description of Christ's advocacy: 'Listen to him who is the advocate with the Father, who is pleading your cause before him — saying: Father, behold the sufferings and death of him who did no sin, in whom thou wast well pleased.' Christ does not merely represent us — He holds up His own wounds as evidence of His love and as the grounds for mercy. He pleads our cause with His own blood.\n\nThis intercessory role reveals the deepest dimension of the Father-Son relationship as it relates to us. We are not outsiders looking in on their unity — we are the reason for it. The Father and Son are united in the project of our redemption.",
      patterns: "Christ's intercessory role connects to Week 35's study of the Second Comforter and to Week 12's study of the Atonement. His advocacy before the Father is ongoing — not a single past event but a continuing ministry.",
      reflection: "D&C 45 describes Christ pleading your cause before the Father right now. How does it affect your sense of worth and hope to know that the Son of God is advocating for you personally?"
    },
    {
      label: "The pattern for us",
      focus: "Christ's relationship with the Father is not just theology to admire — it is the model for our own relationship with God. Today applies the week's study to personal discipleship.",
      scriptures: [{book:"3 Ne",ch:19,vs:23},{book:"John",ch:17,vs:21,ve:23},{book:"Mosiah",ch:15,vs:1,ve:7}],
      nuances: "In John 17:21, 'that they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us,' the preposition 'en' (in) is used four times. The interpenetration of identities described here — Father in Son, Son in Father, believers in both — is sometimes called 'mutual indwelling.' It describes a relationship of such intimacy that the boundaries between persons are transcended without being erased.",
      commentary: "John 17:21–23 is the climax of Christ's intercessory prayer: He asks that believers may be one in the Father and the Son, just as they are one in each other. This is the ultimate invitation. The unity between Father and Son is not a closed circle — it is an open embrace, and we are invited in.\n\n3 Nephi 19:23 repeats this prayer in the New World setting, confirming that it is not a one-time wish but a standing petition. Christ continually asks the Father that His followers might experience the same unity with God that He experiences.\n\nMosiah 15:1–7 rounds out the week by returning to Abinadi's teaching about how the Father and Son relate. Abinadi teaches that Christ subjected the flesh to the will of the Father — and in doing so, became both Father and Son. The practical application is this: when we subject our will to God's will, we begin to participate in the same dynamic. We do not become God, but we enter into the relationship that defines God.\n\nThe entire week has been building to this point. The Father-Son relationship is not an abstraction to be debated. It is a lived reality to be entered. Through covenant, prayer, obedience, and the power of the Atonement, we are invited to know the Father the way the Son knows Him — not fully in this life, but truly, and increasingly.",
      patterns: "The progression from theology to personal application mirrors the structure of the gospel itself: we learn who God is so that we can become like Him. This connects to Week 36's study of taking upon us the name of Christ — the covenantal entry point into this divine relationship.",
      reflection: "Christ prayed that you might be one with the Father and the Son. What is one concrete step you can take this week to move deeper into that unity — through prayer, obedience, or surrender of your own will?"
    }
  ]
};

export default week33;
