import type { WeekContent } from '../types';

const week18: WeekContent = {
  title: "Light of the World & Rock — Foundation and Illumination",
  subtitle: "Christ is both the light that guides and the rock that holds — the source of vision and the ground of stability.",
  weekScriptures: "John 8:12; John 9:5; John 12:35–36; 1 Jn 1:5–7; Isa 60:19–20; 3 Ne 18:24; D&C 88:6–7; D&C 84:45–46; Matt 7:24–27; 1 Cor 10:1–4; Hel 5:12; 2 Ne 4:30–35; Ps 27:1; Ps 18:2; Ps 62:1–2; 2 Sam 22:32; 1 Ne 15:36; 3 Ne 11:39–40; Jacob 4:15–17; D&C 50:23–24",
  synthesis: {
    summary: "Two of the most enduring scriptural images for Christ are light and rock. Light reveals, guides, warms, and dispels darkness. Rock supports, stabilizes, endures, and provides defense. Together they describe a Savior who both illuminates the path and provides an unshakable foundation for those who walk it. This week explores both metaphors in depth, tracing them through the Old Testament, the Gospels, the Book of Mormon, and modern revelation.",
    connections: [
      "Christ as Light connects directly to the glory of Christ (Week 17) — glory is the fullness of light, and light is glory experienced in daily life.",
      "Christ as Rock connects to His role as Redeemer (Week 14) — the foundation on which the redeemed build their lives after deliverance.",
      "Both metaphors are grounded in Christ's power (Week 16) — the power to illuminate and the power to sustain."
    ],
    teaching: "If someone asked you why you trust Jesus Christ, would your answer lean more toward 'He is my light' or 'He is my rock'? What does your answer reveal about your current spiritual needs?",
    commitment: "Choose one of this week's metaphors — light or rock — and focus on it in your prayers each day. Ask Christ to be specifically that for you in a current challenge."
  },
  days: [
    {
      label: "I am the light of the world",
      focus: "Jesus made this declaration at the Feast of Tabernacles, surrounded by towering lampstands that illuminated all of Jerusalem. Today examines the context and meaning of His most visual self-identification.",
      scriptures: [{book:"John",ch:8,vs:12},{book:"John",ch:9,vs:5},{book:"John",ch:12,vs:35,ve:36}],
      nuances: "John 8:12 was spoken during the Feast of Tabernacles, when four enormous golden lampstands were lit in the Court of the Women, producing light visible across Jerusalem. The festival commemorated Israel's wilderness wandering, when the pillar of fire guided them by night. Against this backdrop, Jesus declares, 'I am the light of the world.' The claim is staggering: He is not pointing to the lampstands as symbols — He is saying that He is the reality they symbolize.",
      commentary: "The 'I am' declarations in John's Gospel are not casual metaphors. Each one echoes the divine name revealed to Moses ('I AM THAT I AM,' Exodus 3:14). When Jesus says 'I am the light of the world,' He is simultaneously claiming a function (illumination) and an identity (the God of Israel). The Pharisees understood this — their immediate response was to challenge His authority.\n\nIn John 9:5, Jesus repeats the claim in the context of healing a man born blind. The physical healing enacts the spiritual truth: the man who was in darkness receives sight from the one who is light. The miracle is a parable in action. Darkness — whether physical, spiritual, or intellectual — yields to Christ's presence.\n\nJohn 12:35-36 adds urgency: 'Walk while ye have the light, lest darkness come upon you.' Light is not merely available; it must be received and walked in. You can stand in a lit room and close your eyes. The light does not fail; the choice to receive it is yours. Jesus urges His listeners to become 'children of light' — people whose identity is shaped by the light they have received.\n\nFor Latter-day Saints, D&C 88:6-7 (studied this week) expands this claim to cosmological proportions: the light of Christ fills the immensity of space and gives life to all things. The light that healed a blind man in Jerusalem is the same light that sustains the stars.",
      patterns: "The light motif runs throughout John's Gospel: from the opening declaration that 'in him was life; and the life was the light of men' (John 1:4) through the 'I am' declarations to the resurrection scene where light breaks into the darkness of the tomb. Light and life are inseparable in John's theology.",
      reflection: "Jesus said 'he that followeth me shall not walk in darkness.' What areas of confusion, fear, or uncertainty in your life need His light right now?"
    },
    {
      label: "Walking in the light",
      focus: "Light is not just a title Christ claims; it is an experience He offers. Today explores the practical, daily reality of walking in Christ's light.",
      scriptures: [{book:"1 Jn",ch:1,vs:5,ve:7},{book:"D&C",ch:50,vs:23,ve:24},{book:"D&C",ch:84,vs:45,ve:46}],
      nuances: "In 1 John 1:5, 'God is light, and in him is no darkness at all' uses an absolute negative construction in Greek ('skotia en auto ouk estin oudemia') — literally, 'darkness in him there is not even one bit.' John eliminates every possible shade of grey. The claim is total: there is zero darkness in God. This is not a relative comparison (He has more light than darkness) but an absolute statement of nature.",
      commentary: "John's epistle begins with one of the most definitive theological statements in the New Testament: God is light, and in Him is no darkness at all. This is not a metaphor but a description of divine nature. God does not merely produce light or use light — He is light. To walk in fellowship with Him is therefore to walk in light, and to walk in darkness is to be out of fellowship with Him regardless of what one claims.\n\nD&C 50:23-24 connects light directly to spiritual growth: 'That which is of God is light; and he that receiveth light, and continueth in God, receiveth more light; and that light groweth brighter and brighter until the perfect day.' This is the principle of progressive illumination. Light is not given all at once but incrementally, and faithfulness with the light you have is the condition for receiving more. This matches the Restoration's broader theology of line upon line, precept upon precept.\n\nD&C 84:45-46 identifies the mechanism: 'The word of the Lord is truth, and whatsoever is truth is light, and whatsoever is light is Spirit, even the Spirit of Jesus Christ. And the Spirit giveth light to every man that cometh into the world.' The light of Christ is universal — every person born into the world receives it. It is the moral intuition, the sense of right and wrong, the capacity to recognize truth. This universal endowment means that no one is left entirely in the dark; everyone has at least some access to Christ's light.\n\nThe practical implication is that spiritual growth is not mysterious: walk in the light you have, and more will come. Ignore the light you have, and even that will fade.",
      patterns: "The progressive nature of light — growing 'brighter and brighter until the perfect day' — parallels the degrees of glory in D&C 76 and the process of sanctification described throughout scripture. Light is both the goal and the path.",
      reflection: "D&C 50 promises that the faithful receive 'more light' progressively. What light have you already received that you may be neglecting? What might change if you acted more fully on what you already know?"
    },
    {
      label: "A light to the nations",
      focus: "Christ's light is not private; it is meant to illuminate all nations and peoples. Today explores the prophetic vision of Christ as universal light.",
      scriptures: [{book:"Isa",ch:60,vs:19,ve:20},{book:"3 Ne",ch:18,vs:24},{book:"Ps",ch:27,vs:1}],
      nuances: "Isaiah 60:19 — 'The sun shall be no more thy light by day; neither for brightness shall the moon give light unto thee: but the Lord shall be unto thee an everlasting light' — uses 'or olam' (everlasting light). Unlike the sun, which sets and rises, this light is without interruption. The Hebrew emphasizes permanence and sufficiency: you will never need another light source.",
      commentary: "Isaiah 60:19-20 envisions a future state in which natural light sources become unnecessary because the Lord Himself is the light. This is not mere poetic exaggeration but prophetic description — the same vision John sees in Revelation 21:23. The trajectory of scripture moves toward a world so saturated with divine glory that the sun is redundant. The implication is that every current light source — physical, intellectual, moral — is a temporary substitute for the real thing.\n\nJesus' instruction in 3 Nephi 18:24 brings this cosmic vision into individual application: 'Hold up your light that it may shine unto the world. Behold I am the light which ye shall hold up.' Christ is the light, and His disciples are the lampstands. The light is not your goodness or your wisdom or your eloquence — it is Christ in you, shining through you. The disciple's job is not to generate light but to hold it up, unobstructed, where others can see it.\n\nPsalm 27:1 offers the personal dimension: 'The Lord is my light and my salvation; whom shall I fear?' David connects light and salvation in a single breath, and from that connection derives courage. If the Lord is your light, darkness has lost its power to terrify. If He is your salvation, threats have lost their power to destroy. The practical result of receiving Christ as light is the elimination of fear — not because danger disappears but because you can see clearly enough to navigate it.",
      patterns: "The movement from personal light (Psalm 27) to community light (3 Nephi 18) to cosmic light (Isaiah 60) traces the expanding scope of Christ's illumination. It begins in the individual heart, spreads through the community of disciples, and ultimately fills the entire earth.",
      reflection: "Jesus told His Nephite disciples to 'hold up your light.' In what specific ways can your life serve as a lampstand for Christ's light this week?"
    },
    {
      label: "Built upon the rock",
      focus: "Shifting from light to rock, today examines Christ as the immovable foundation — the one thing that cannot be shaken when everything else is.",
      scriptures: [{book:"Matt",ch:7,vs:24,ve:27},{book:"Hel",ch:5,vs:12},{book:"3 Ne",ch:11,vs:39,ve:40}],
      nuances: "In Matthew 7:25, the house on the rock survives 'the rain, the flood, and the winds.' These three represent different kinds of adversity: rain from above (trials from heaven or circumstance), floods from below (the pressures of earthly life), and winds from the side (opposition from others). The triple threat tests the foundation comprehensively. Jesus' point is not that the rock prevents storms but that it survives them.",
      commentary: "The parable of the wise and foolish builders in Matthew 7:24-27 is among the most well-known teachings of Jesus. Two builders, two houses, the same storm — but radically different outcomes. The difference is not in the quality of the house or the severity of the storm but in the foundation. The wise builder built on rock; the foolish builder built on sand. Christ is the rock, and building on Him means hearing His words and doing them.\n\nHelaman 5:12 is the Book of Mormon's most direct commentary on this principle, and its language is specifically chosen to echo Christ's parable: 'It is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation.' Helaman adds a vivid image: when the devil sends forth his mighty winds and shafts in the whirlwind, those built on the rock 'cannot fall.' The double negative is absolute — not 'will probably survive' but 'cannot fall.'\n\n3 Nephi 11:39-40 records the Savior Himself, appearing to the Nephites, teaching this same principle: 'Whoso buildeth upon this buildeth upon my rock, and the gates of hell shall not prevail against them.' Christ establishes His doctrine — faith, repentance, baptism, and the Holy Ghost — and then declares that this doctrine is the rock. Anyone who adds to it or subtracts from it builds on sand.\n\nThe rock metaphor is fundamentally about reliability under pressure. Everyone faces storms. The question is not whether the storm will come but what you are standing on when it arrives.",
      patterns: "The rock appears across all dispensations: the rock of Horeb that gave water (Exodus 17:6), the stone the builders rejected (Psalm 118:22), the stone cut without hands that fills the earth (Daniel 2:34-35), and the rock of revelation on which Christ builds His church (Matthew 16:18). Each reference adds a dimension to the same foundational truth.",
      reflection: "Helaman promised that those built on Christ's rock 'cannot fall.' What does it look like, in practical terms, for you to build your life more firmly on that foundation?"
    },
    {
      label: "The Rock of Israel",
      focus: "The title 'Rock' for God is ancient, appearing dozens of times in the Old Testament. Today traces this foundational metaphor through Israel's history.",
      scriptures: [{book:"Ps",ch:18,vs:2},{book:"Ps",ch:62,vs:1,ve:2},{book:"2 Sam",ch:22,vs:32}],
      nuances: "The Hebrew 'tsur' (rock, cliff, boulder) appears over 70 times in the Old Testament as a divine title. It describes immovable, enduring stone — not a small rock but a cliff face or mountain crag. When David calls God his 'tsur,' he is invoking the image of a massive, unyielding geological formation that provides shelter, vantage, and safety. The desert landscape of Israel made this metaphor viscerally real: a rock outcropping could mean the difference between life and death in battle or storm.",
      commentary: "Psalm 18:2 is David's testimony forged in adversity: 'The Lord is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, and my high tower.' Every metaphor describes a different function of the same rock: shelter (fortress), rescue (deliverer), stability (strength), protection (buckler and high tower). The accumulated images convey a comprehensive reliance on God that leaves nothing to chance or self-sufficiency.\n\nPsalm 62:1-2 adds a dimension of peace: 'My soul waiteth upon God: from him cometh my salvation. He only is my rock and my salvation; he is my defence; I shall not be greatly moved.' The word 'only' (Hebrew 'ak') is exclusive — God alone is the rock. Not God and my own efforts. Not God and my backup plan. God only. This exclusivity is the source of David's peace: when your foundation is singular and unshakable, anxiety loses its grip.\n\n2 Samuel 22:32 poses a rhetorical question: 'For who is God, save the Lord? and who is a rock, save our God?' The implied answer is 'no one.' David is not merely praising God as one rock among many; he is declaring that God is the only real rock — every other foundation is ultimately sand by comparison.\n\nPaul makes this connection to Christ explicit in 1 Corinthians 10:4, identifying the rock that followed Israel in the wilderness as Christ. The rock that gave water in the desert, the rock that sheltered David in battle, and the rock on which the wise man built are all the same person — the premortal and mortal Jesus Christ.",
      patterns: "David's experience of God as rock was forged in years of fleeing from Saul, hiding in caves and among cliffs. The rock metaphor is not theoretical for David but geographical — he literally sheltered in rocks and came to understand God through them. Experience shapes metaphor, and metaphor shapes understanding.",
      reflection: "David declared God as his 'only' rock. What competing foundations — financial security, relationships, reputation, personal ability — do you sometimes trust alongside or instead of Christ?"
    },
    {
      label: "The stone the builders rejected",
      focus: "Christ is not only a foundation for the faithful; He is a stumbling block for the faithless. Today explores the paradox of the stone that both supports and trips.",
      scriptures: [{book:"Jacob",ch:4,vs:15,ve:17},{book:"1 Cor",ch:10,vs:1,ve:4},{book:"1 Ne",ch:15,vs:36}],
      nuances: "Jacob's quotation in Jacob 4:17 — 'how is it possible that these, after having rejected the sure foundation, can ever build upon it, that it may become the head of their corner?' — refers to Psalm 118:22, the stone the builders rejected becoming the cornerstone. A cornerstone in ancient construction was the reference point for the entire building; every measurement was taken from it. To reject the cornerstone was not merely to discard one stone but to lose the reference point for everything else.",
      commentary: "Jacob 4:15-17 is a penetrating analysis of Israel's relationship with Christ. Jacob explains that the Jews would reject the 'sure foundation' — the very stone upon which they were supposed to build — and that God, by His 'overcoming power,' would use that rejection itself to accomplish His purposes. The cross, intended as destruction, became the means of salvation. The rejected stone became the cornerstone.\n\nPaul's identification in 1 Corinthians 10:1-4 of the wilderness rock with Christ is one of the New Testament's most important typological readings. The rock that Moses struck, from which water flowed to sustain Israel in the desert, was Christ. The physical sustenance prefigured spiritual sustenance. The rock that gave water in the wilderness is the same rock that gives living water to all who come to Him.\n\n1 Nephi 15:36 provides a sobering counterpoint: the wicked are 'rejected from the righteous, and also from that tree of life, whose fruit is most precious and most desirable above all other fruits.' The same Christ who is a sure foundation for the faithful becomes, for those who reject Him, the standard by which their rejection is measured.\n\nThe paradox of the rock is this: it is both foundation and stumbling block, cornerstone and stone of offense. The difference is not in the rock but in the response. Those who build on it find unshakable security. Those who reject it find that it remains immovable regardless of their opinion of it.",
      patterns: "The rejected-stone-becomes-cornerstone pattern is one of the great reversals in scripture, paralleling the cross becoming the means of salvation and the suffering Servant becoming King of kings. God's economy consistently turns rejection into triumph.",
      reflection: "Jacob asks how those who reject the 'sure foundation' can ever build on it. Are there teachings or commandments of Christ that you have been resistant to build upon? What would it look like to accept the whole cornerstone?"
    },
    {
      label: "Light and rock together",
      focus: "Today brings the week's two metaphors together, exploring how Christ simultaneously illuminates the path and provides the ground beneath your feet.",
      scriptures: [{book:"2 Ne",ch:4,vs:30,ve:35},{book:"D&C",ch:88,vs:6,ve:7},{book:"Hel",ch:5,vs:12}],
      nuances: "In 2 Nephi 4:35, Nephi's psalm moves between desperation and confidence: 'Yea, I know that God will give liberally to him that asketh... my God will give me, if I ask not amiss; therefore I will lift up my voice unto thee.' Nephi has just confessed his weaknesses and sorrows (the 'psalm of Nephi'), and his resolution is not self-improvement but turning to God as both his light ('enlighten my mind,' v. 28) and his rock ('my rock and my everlasting God,' v. 35). Both metaphors appear in the same prayer.",
      commentary: "Nephi's psalm in 2 Nephi 4:30-35 is one of the most emotionally honest passages in scripture. He has acknowledged anger, sorrow, weakness, and spiritual struggle. His resolution is not stoic self-discipline but passionate dependence on God: 'O Lord, I have trusted in thee, and I will trust in thee forever.' In this one passage, God is both Nephi's light (the source of understanding and clarity) and his rock (the source of stability and strength). The two metaphors work together: light shows where to go, and the rock ensures you do not fall on the way.\n\nD&C 88:6-7 expands this to a cosmic principle. The light of Christ is 'in all things, through all things, and round about all things.' It is the law by which all things are governed and the power by which they exist. This light is simultaneously illumination (showing the truth of things) and foundation (sustaining the existence of things). Christ is, in the deepest sense, both the ground of being and the light of understanding.\n\nHelaman 5:12, revisited from earlier this week, brings both metaphors into a single promise: build on the rock, and when the storms come, you cannot fall. The storms in Helaman's metaphor include 'mighty winds' and 'hail' — forces of confusion and destruction. The rock provides stability; the rock of the Redeemer who is also the light of the world provides clarity in the midst of the storm.\n\nThe week closes with this unified vision: you need both light and rock. You need to see where you are going and to stand on something unshakable while you go there. Christ is both. He does not offer illumination without stability or strength without wisdom. He is the complete foundation for a complete life.",
      patterns: "The combination of light and rock appears together in many of scripture's most climactic moments: the pillar of fire over the rock of Sinai, the lampstand in the rock-hewn temple, and Nephi's psalm invoking both in a single prayer. God provides for both of humanity's deepest needs — the need to see and the need to stand.",
      reflection: "As you close this week, consider: in your current season of life, do you need Christ more as light (guidance and clarity) or as rock (stability and strength)? Bring that need to Him in prayer."
    }
  ]
};

export default week18;
