import type { WeekContent } from '../types';

const week22: WeekContent = {
  title: "Temptation of — Christ in the Wilderness",
  subtitle: "Jesus was tempted in all things, yet without sin — and His victory over temptation is essential to His power to help us overcome our own.",
  weekScriptures: "Matt. 4:1–11; Luke 4:1–13; Mark 1:12–13; Heb. 4:14–16; Heb. 2:17–18; D&C 20:22; 2 Ne. 2:11–16; James 1:2–4; James 1:13–15; 1 Cor. 10:13; Alma 13:28; Moro. 7:12–17; D&C 29:39; 3 Ne. 18:18; Mosiah 3:19",
  synthesis: {
    summary: "The temptation of Jesus Christ in the wilderness was not a random trial but a defining confrontation between the Son of God and the adversary. Each temptation targeted a specific dimension of Christ's mission — His physical needs, His divine identity, and His relationship with the Father. Christ's perfect resistance demonstrated that temptation can be overcome, and His experience made Him uniquely qualified to succor every person who faces trial. His victory is not just an example — it is the source of power available to every disciple.",
    connections: [
      "Christ's temptation follows directly after His baptism (Week 21), illustrating the scriptural pattern that spiritual highs are often followed by intense trials.",
      "His reliance on scripture to resist temptation connects to Week 20 (Teaching Mode) — He used the word of God as both sword and shield.",
      "The empathic knowledge Christ gained through temptation connects to Week 12 (Atonement) and Week 6 (Compassion), where His ability to succor us is rooted in His personal experience of mortality."
    ],
    teaching: "Each of Christ's three temptations in the wilderness targeted a different vulnerability: physical need, pride, and power. Which of these three categories of temptation do you find most relevant to your own life? How does Christ's response to that specific temptation give you a pattern to follow?",
    commitment: "Identify one recurring temptation in your life this week. Each time it arises, consciously turn to a specific scripture — as Christ did — and use the word of God as your response."
  },
  days: [
    {
      label: "Led by the Spirit into the wilderness",
      focus: "Jesus did not stumble into temptation accidentally — He was led by the Spirit into the wilderness to be tested. Today examines why God allowed this confrontation.",
      scriptures: [{book:"Matt",ch:4,vs:1,ve:2},{book:"Mark",ch:1,vs:12,ve:13},{book:"D&C",ch:29,vs:39}],
      nuances: "In Mark 1:12, the Spirit 'driveth' Jesus into the wilderness — the Greek 'ekballei' is forceful, the same verb used for casting out demons. This is not a gentle leading but an urgent compulsion. Matthew's softer 'anechthe' (was led up) and Mark's forceful 'ekballei' together suggest both willingness and divine urgency. The wilderness (eremos) was understood in Jewish tradition as the domain of evil spirits — the place where chaos still reigned, uncultivated by God's order.",
      commentary: "Immediately after the glorious experience of His baptism — the heavens opened, the Spirit descended, the Father spoke — Jesus was driven into the wilderness to face Satan. The sequence is significant and not accidental. The Spirit Himself led Jesus into this confrontation. God did not merely permit the temptation; He orchestrated it as a necessary part of Christ's preparation.\n\nThis challenges a common assumption: that temptation is always a sign of spiritual failure or distance from God. Jesus was closer to the Father than any person has ever been, and He was led directly into the most intense spiritual combat imaginable. The wilderness was not a punishment but a proving ground.\n\nD&C 29:39 provides the theological framework: 'It must needs be that the devil should tempt the children of men, or they could not be agents unto themselves.' The capacity to choose requires real alternatives. Without genuine temptation, there is no genuine agency, and without genuine agency, there is no genuine growth. Christ entered this reality not because He needed to grow but because He needed to fully experience what every mortal faces.\n\nThe forty days of fasting echo Moses on Sinai (Ex. 34:28) and Elijah's journey to Horeb (1 Kgs. 19:8). In each case, a period of physical deprivation preceded a definitive encounter with God — or, in Christ's case, a definitive encounter with God's adversary. The number forty itself carries scriptural weight: Israel wandered forty years, the flood lasted forty days. Forty is the number of testing and preparation.",
      patterns: "The pattern of spiritual triumph followed by intense trial appears throughout scripture. Joseph Smith received the First Vision and then endured years of opposition. Lehi was called as a prophet and immediately faced threats to his life. The pattern suggests that divine encounters do not exempt us from difficulty — they prepare us for it.",
      reflection: "Have you ever experienced a spiritual high followed almost immediately by a significant trial? How does knowing that Christ's own experience followed this pattern change how you interpret those moments?"
    },
    {
      label: "Stones into bread: the temptation of appetite",
      focus: "The first temptation targeted Christ's most basic physical need after forty days of fasting. Today examines how Satan attacks through legitimate desires pushed beyond their proper bounds.",
      scriptures: [{book:"Matt",ch:4,vs:3,ve:4},{book:"Luke",ch:4,vs:3,ve:4},{book:"Mosiah",ch:3,vs:19}],
      nuances: "Satan's opening word is 'ei' — 'if' — followed by 'huios ei tou theou' (you are the Son of God). The Greek construction is a first-class conditional, which assumes the condition is true: 'Since you are the Son of God...' Satan is not questioning Christ's identity but weaponizing it — using a true premise to justify a wrong action. Christ's response quotes Deuteronomy 8:3, using the Septuagint Greek almost verbatim. He does not argue; He cites authority.",
      commentary: "After forty days without food, Jesus was genuinely, physically starving. The hunger was real. The temptation was not to do something evil in itself — bread is not sinful — but to use divine power to serve personal appetite outside the Father's will. Satan's logic was seductive: You have the power. You have the need. No one would blame you. Why not?\n\nChrist's response — 'Man shall not live by bread alone, but by every word that proceedeth out of the mouth of God' — is a quotation from Deuteronomy 8:3, where Moses reminded Israel that God had allowed them to hunger in the wilderness and then fed them manna to teach them dependence on His word. Jesus places Himself within Israel's experience. He is in the wilderness. He is hungry. But He will not feed Himself outside the Father's provision.\n\nThis first temptation establishes a category that covers far more than food. It is the temptation to let legitimate desire override divine timing and divine means. The desire for comfort, security, relief, pleasure — none of these are inherently wrong. But when they are pursued outside God's boundaries, they become paths of rebellion disguised as paths of reason.\n\nMosiah 3:19 describes the 'natural man' as 'an enemy to God.' King Benjamin's solution is to yield to the enticings of the Holy Spirit and become as a child — submissive, willing, patient. Christ modeled exactly this in the wilderness: He yielded His physical urgency to the Father's word.",
      patterns: "The pattern of appetite as a vector for temptation is ancient. In Eden, the forbidden fruit was 'good for food' (Gen. 3:6) — the appeal to appetite was the first point of attack. Esau sold his birthright for a meal (Gen. 25:33). Israel complained about food in the wilderness (Ex. 16:3). The consistent scriptural pattern is that mastery of appetite is the first test of discipleship.",
      reflection: "What legitimate desire in your life is most susceptible to being pushed beyond its proper bounds? How might Christ's strategy — turning to scripture rather than reasoning with the tempter — help you respond differently?"
    },
    {
      label: "Cast thyself down: the temptation of presumption",
      focus: "Satan quoted scripture to tempt Jesus. Today examines the second temptation — the subtle distortion of truth into a tool for spiritual recklessness.",
      scriptures: [{book:"Matt",ch:4,vs:5,ve:7},{book:"Luke",ch:4,vs:9,ve:12},{book:"Alma",ch:13,vs:28}],
      nuances: "Satan quotes Psalm 91:11–12, but omits the phrase 'to keep thee in all thy ways.' The full verse promises angelic protection within the bounds of one's appointed path — not in reckless acts of self-display. Satan's omission is a masterclass in proof-texting: using true scripture to support a false conclusion. Christ's counter-quotation of Deuteronomy 6:16 ('Thou shalt not tempt the Lord thy God') uses 'ekpeiraseis' — to test beyond limits, to put on trial.",
      commentary: "The second temptation is more sophisticated than the first. Satan has learned from Christ's response: if Jesus will appeal to scripture, Satan will use scripture too. He takes Jesus to the pinnacle of the temple and quotes a psalm that promises angelic protection. The logic seems airtight: God promised to protect you. Prove it. Jump.\n\nBut Christ saw through the distortion immediately. There is a difference between trusting God's promises and manufacturing crises to test them. Faith means relying on God's word in the situations He places you in, not creating artificial dangers to force His hand. The temptation to 'cast thyself down' is the temptation of presumption — treating God's grace as a blank check rather than a covenant relationship.\n\nThis category of temptation is particularly dangerous because it wears the appearance of faith. 'If God loves me, He will protect me no matter what I do.' 'If I am forgiven anyway, the sin does not matter.' 'If the Spirit will guide me, I do not need to prepare.' Each of these is a form of casting oneself off the pinnacle — using a true doctrine to justify a reckless choice.\n\nAlma 13:28 counsels to 'humble yourselves before the Lord, and call on his holy name, and watch and pray continually, that ye may not be tempted above that which ye can bear.' The emphasis on watching and praying is the antidote to presumption. Humility, not self-confidence, is the posture that resists this temptation.",
      patterns: "Satan's misuse of scripture to tempt Christ foreshadows the broader pattern of corrupted truth throughout history. Nehor used partial truths to lead people astray (Alma 1:3–4). Korihor used rationalistic arguments that contained elements of truth (Alma 30:17). The antidote in every case is not less scripture but better scripture — knowing the word well enough to recognize its distortion.",
      reflection: "Have you ever been tempted to take a spiritual shortcut — assuming God's grace would cover a choice you knew was unwise? What is the difference between genuine faith and presumption in your daily life?"
    },
    {
      label: "All the kingdoms: the temptation of power",
      focus: "The third temptation offered Jesus everything He would eventually receive — but through a shortcut that bypassed the cross. Today examines the temptation to achieve righteous ends through wrong means.",
      scriptures: [{book:"Matt",ch:4,vs:8,ve:11},{book:"Luke",ch:4,vs:5,ve:8},{book:"2 Ne",ch:2,vs:11,ve:16}],
      nuances: "In Matthew 4:9, Satan says 'fall down and worship me' — the Greek 'proskuneses' is the word for full prostration, the worship due only to God. The offer is absolute: 'all the kingdoms of the world.' Luke adds the detail that Satan showed them 'in a moment of time' (en stigme chronou), suggesting a supernatural vision compressing all earthly glory into a single, overwhelming instant. Christ's response, 'Get thee hence, Satan,' uses 'hupage' — an imperative of departure that carries finality.",
      commentary: "The third temptation is the most audacious. Satan offers Jesus all the kingdoms of the world and their glory — everything that earthly power, influence, and dominion could provide. The price: worship the adversary. The offer is not as absurd as it first appears. Christ came to redeem the world. He came to be King. Satan was offering the destination without the journey — the crown without the cross.\n\nThis is the deepest temptation: to achieve a righteous goal through an unrighteous method. It is the temptation of every leader who compromises integrity for results, every parent who uses manipulation instead of love, every disciple who pursues spiritual outcomes through worldly strategies. The end does not justify the means, and no kingdom gained through compromise with evil is worth having.\n\nChrist's response is His most forceful: 'Get thee hence, Satan: for it is written, Thou shalt worship the Lord thy God, and him only shalt thou serve.' He does not negotiate. He does not consider the offer. He commands Satan to leave and reasserts the foundational commandment: worship belongs to God alone.\n\n2 Nephi 2:11–16 provides the cosmic framework for this confrontation. Lehi teaches that opposition in all things is necessary for agency, righteousness, and existence itself. Satan is a real being with real power to tempt, and the temptation he offered Christ was genuine. But the existence of opposition also means that every choice for God is a real victory — not a predetermined outcome but a genuine triumph of will.",
      patterns: "The temptation to gain righteous ends through wrong means recurs throughout scripture. Moses was offered this temptation (Moses 1:12–22) and rejected it. David succumbed to it when he used his kingly power to take Bathsheba (2 Sam. 11). The pattern reveals a consistent truth: the method matters as much as the outcome, and character is built in the means, not just the ends.",
      reflection: "Where in your life are you most tempted to cut corners or compromise your integrity to achieve a good outcome? What would it look like to choose Christ's approach — the harder right over the easier wrong?"
    },
    {
      label: "He was tempted in all things",
      focus: "The wilderness temptations were not the only trials Jesus faced. Hebrews teaches He was tempted 'in all points like as we are.' Today explores the full scope of His tested mortality.",
      scriptures: [{book:"Heb",ch:4,vs:14,ve:16},{book:"Heb",ch:2,vs:17,ve:18},{book:"D&C",ch:20,vs:22}],
      nuances: "Hebrews 4:15 says Christ was 'tempted in all points' — the Greek 'kata panta' means 'in every respect' or 'according to all things.' The phrase 'yet without sin' (choris hamartias) does not mean He was never attracted or tested. It means He never yielded. The distinction is crucial: temptation and sin are not the same thing. The author of Hebrews insists on the reality of the temptation — it was genuine — while affirming the purity of the outcome.",
      commentary: "The three temptations in the wilderness are the ones recorded in detail, but Hebrews makes a much broader claim: Jesus was tempted 'in all points like as we are.' This means He experienced the full range of mortal temptation — not just hunger, pride, and power, but loneliness, frustration, grief, the desire to escape, the impulse to retaliate, the weight of being misunderstood. He knows what it feels like.\n\nHebrews 2:17–18 explains why this matters: 'In that he himself hath suffered being tempted, he is able to succour them that are tempted.' The word 'succour' (boethesai) means to run to help someone in distress. Christ's ability to help us in our temptations is not abstract omniscience — it is earned empathy. He does not merely know about temptation; He has felt it in a mortal body.\n\nD&C 20:22 adds the Restoration witness: 'He suffered temptations but gave no heed unto them.' This phrasing is instructive. It does not say He never felt temptation. It says He gave no heed. This is the model: temptation will come; the question is whether you will give heed — whether you will engage with it, entertain it, or turn from it.\n\nThe theological implications are profound. We worship a God who chose not to be immune to our struggles. He could have passed through mortality untouchable, but that would have defeated the purpose. He came to know, by experience, everything we face — so that when you cry out for help in your weakest moment, you are heard by Someone who has been there.",
      patterns: "The principle of divine empathy through personal experience is unique in the world's religious traditions. Most concepts of God emphasize transcendence and immunity from suffering. The Christian claim — and especially the Restoration elaboration in Alma 7:11–13 — insists that God chose to suffer, not because He was weak, but because He wanted to understand us from the inside.",
      reflection: "Knowing that Christ was genuinely tempted and genuinely resisted, how does that change the way you approach Him when you are struggling with temptation? Does it make it easier or harder to ask for His help?"
    },
    {
      label: "Discerning good from evil",
      focus: "If Satan can disguise temptation as reason and even quote scripture, how do we tell the difference between divine invitation and deceptive enticement? Today examines the tools of discernment.",
      scriptures: [{book:"Moro",ch:7,vs:12,ve:17},{book:"James",ch:1,vs:13,ve:15},{book:"3 Ne",ch:18,vs:18}],
      nuances: "In Moroni 7:16, the phrase 'the Spirit of Christ is given to every man' describes what Latter-day Saint theology calls the Light of Christ — a moral endowment given universally, distinct from the gift of the Holy Ghost. The test Mormon provides is functional: 'every thing which inviteth to do good, and to persuade to believe in Christ, is sent forth by the power and gift of Christ.' The Greek in James 1:14 uses 'exelkomenos' (dragged away) and 'deleazomenos' (enticed, as a fish by bait) — vivid images of temptation as a process with stages, not a single moment.",
      commentary: "Christ's victory over temptation in the wilderness gives us the model, but we need tools to apply it in the less dramatic, daily decisions of ordinary life. Mormon provides the clearest test in Moroni 7:12–17: everything that invites you to do good and believe in Christ comes from God; everything that persuades you to do evil and deny Christ comes from the devil. 'By their fruits ye shall know them.'\n\nThis test is practical and available to everyone, because it operates through the Light of Christ, which is given to every person. You do not need advanced theological training to discern between good and evil. You need to pay attention to the direction something is pulling you — toward Christ or away from Him. Toward light, kindness, truth, and covenant, or toward darkness, selfishness, deception, and isolation.\n\nJames 1:13–15 provides an important clarification: God does not tempt anyone. Temptation arises when a person is 'drawn away of his own lust, and enticed.' James describes a progression — desire conceives, gives birth to sin, and sin when full-grown brings death. The process has stages, and it can be interrupted at any point. The earlier you recognize the progression, the easier it is to stop.\n\n3 Nephi 18:18 contains Christ's own prescription: 'Watch and pray always lest ye enter into temptation.' The word 'watch' implies vigilance — a conscious awareness of your own spiritual state. Prayer adds divine power to human awareness. Together, they form the practical defense that Christ modeled in the wilderness and prescribed for His disciples.",
      patterns: "The principle of discernment through the Light of Christ connects to Week 34 (Spirit of Jesus Christ), where the role of the Spirit in guiding all truth is explored. The capacity to distinguish good from evil is not a Latter-day Saint invention but a universal endowment — part of what it means to be created in God's image.",
      reflection: "Think of a recent decision you faced. Can you trace the direction it was pulling you — toward Christ or away from Him? How does Mormon's test in Moroni 7 help clarify choices that seem ambiguous?"
    },
    {
      label: "Temptation as opportunity for growth",
      focus: "Scripture does not treat temptation only as a danger — it also describes it as a crucible for spiritual development. Today examines how trials and temptation produce strength.",
      scriptures: [{book:"James",ch:1,vs:2,ve:4},{book:"1 Cor",ch:10,vs:13},{book:"D&C",ch:29,vs:39}],
      nuances: "James 1:2 says 'count it all joy' — the Greek 'pasan charan' means complete or total joy. The word for 'temptations' (peirasmois) can also be translated 'trials' or 'tests,' encompassing a broader range than moral temptation alone. In 1 Corinthians 10:13, the phrase 'a way to escape' is 'ten ekbasin' — literally 'the exit.' Paul's definite article ('the') suggests there is a specific, divinely prepared exit for each temptation, not merely a general possibility of escape.",
      commentary: "James opens his epistle with a command that seems counterintuitive: 'Count it all joy when ye fall into divers temptations.' Joy in the face of trial? James explains: the testing of faith produces patience, and patience leads to completeness — being 'entire, wanting nothing.' The trials are not obstacles to spiritual maturity; they are the means of it.\n\nThis does not mean we should seek out temptation. Christ taught us to pray 'lead us not into temptation' (Matt. 6:13). But when temptation comes — and it will — the response can be something other than fear and guilt. It can be the recognition that this moment is a forge, and what emerges from it can be stronger than what entered.\n\n1 Corinthians 10:13 provides the critical assurance: God is faithful and will not allow you to be tempted beyond your capacity to resist. With every temptation, He provides the way out. This is a promise, not a platitude. It means that in your hardest moment, the escape route exists. The question is whether you will look for it and take it.\n\nD&C 29:39 returns to the foundational principle: 'It must needs be that the devil should tempt the children of men, or they could not be agents unto themselves.' Agency requires opposition. Without the genuine possibility of choosing wrong, the choice to do right has no moral weight. Temptation is not a flaw in God's plan — it is an essential feature of it. Christ demonstrated in the wilderness that temptation can be met, resisted, and transformed into a testimony of faithfulness.",
      patterns: "The pattern of growth through trial is woven throughout scripture: Abraham was tested with Isaac (Gen. 22), Job was tested with suffering (Job 1–2), and Joseph of Egypt was tested with Potiphar's wife (Gen. 39). In each case, the trial became the defining moment of the person's character. The same pattern applies to every disciple — your response to temptation shapes who you are becoming.",
      reflection: "Looking back on a past trial or temptation, can you see how it produced growth in you that could not have come any other way? How does that perspective change how you view the challenges you face right now?"
    }
  ]
};

export default week22;
