import type { WeekContent } from '../types';

const week27: WeekContent = {
  title: "Lamb of God — The Sacrifice That Saves",
  subtitle: "From the Passover lamb to John the Baptist's declaration, one image captures the heart of the gospel: the Lamb slain from the foundation of the world.",
  weekScriptures: "Ex 12:21–23; Ex 29:38–42; Lev 4:32–35; Isa 53:4–6; John 1:35–37; Acts 8:32–35; 1 Pet 1:19; Rev 5:9; Rev 12:11; Rev 14:1–4; Rev 15:3; Rev 17:14; Rev 22:1–3; 2 Ne 9:26; Alma 7:14",
  synthesis: {
    summary: "The image of Christ as the Lamb of God is among the most ancient and central in all scripture. It traces from Abel's offering through the Passover, through Isaiah's suffering servant, through John the Baptist's declaration, to the Lamb standing in the midst of the throne in Revelation. This title uniquely captures both Christ's innocence and His voluntary submission to sacrifice. He is not a victim — He is the Lamb who chose to be slain so that others could live.",
    connections: [
      "The Lamb imagery connects directly to the Atonement (Weeks 11–13) and to Christ as the Great High Priest who is also the offering (Week 17).",
      "The Passover typology explored this week anticipates the discussion of types and shadows in Weeks 39–41.",
      "The Lamb on the throne in Revelation ties to Christ as King of Kings (Week 26) — the slain Lamb reigns."
    ],
    teaching: "Why do you think God chose the image of a lamb — rather than a lion, an eagle, or a warrior — as the primary symbol for His Son's redemptive mission?",
    commitment: "This week, as you take the sacrament, consciously connect the bread and water to the Lamb that was slain. What does that connection change about the experience?"
  },
  days: [
    {
      label: "Behold the Lamb",
      focus: "John the Baptist's declaration is the defining moment: he looked at Jesus and named Him. Today examines what that title meant and why it was chosen.",
      scriptures: [{book:"John",ch:1,vs:29},{book:"John",ch:1,vs:36},{book:"1 Ne",ch:11,vs:31,ve:33}],
      nuances: "In John 1:29, 'Behold the Lamb of God' (Greek: 'Ide ho amnos tou theou') uses 'amnos,' which in the Septuagint specifically denotes a sacrificial lamb — distinct from 'aren' (a young lamb) or 'probaton' (a sheep in general). John is not using a generic pastoral image; he is using precise sacrificial vocabulary. The Baptist is identifying Jesus as the fulfillment of every lamb ever offered on an Israelite altar.",
      commentary: "John the Baptist had one supreme mission: to identify the Lamb. When he saw Jesus walking toward him at the Jordan, he declared to the world, 'Behold the Lamb of God, which taketh away the sin of the world.' The next day he said it again: 'Behold the Lamb of God.' The repetition is significant — this was not a passing remark but the definitive prophetic identification of the Messiah.\n\nFor John's audience, steeped in the rituals of the temple, 'Lamb of God' would have evoked the daily tamid offering — a lamb sacrificed every morning and evening in the temple. It would have recalled the Passover lamb whose blood marked the doorposts in Egypt. It would have pointed to Isaiah's suffering servant, led as a lamb to the slaughter. Every layer of meaning converged on the man walking along the Jordan.\n\nNephi's vision in 1 Nephi 11 uses the same title in a Book of Mormon context. Nephi sees the Lamb of God taken by the people, judged, lifted up on the cross, and slain for the sins of the world. The vision was given roughly 600 years before John the Baptist's declaration, yet it uses identical language — confirming that the 'Lamb of God' title was known prophetically long before it was publicly announced.\n\nThe title itself contains a paradox: a lamb is powerless, vulnerable, destined for the altar. Yet this Lamb takes away the sin of the world — an act of cosmic power. The weakness and the power are not contradictory; they are unified in the Atonement.",
      patterns: "The identification pattern — a prophet publicly declaring Christ's true nature — appears throughout scripture. Moses at the Red Sea, Peter at Caesarea Philippi, Joseph Smith in the First Vision. John's declaration is the pivotal instance of this pattern.",
      reflection: "When John said 'Behold the Lamb of God,' he was telling people to look — really look — at Jesus. What do you see when you look at Him?"
    },
    {
      label: "The Passover lamb",
      focus: "The exodus Passover is the foundational type of Christ's sacrifice. Today traces the detailed parallels between the Passover lamb and the Lamb of God.",
      scriptures: [{book:"Ex",ch:12,vs:3,ve:7},{book:"Ex",ch:12,vs:13},{book:"1 Cor",ch:5,vs:7}],
      nuances: "Exodus 12:5 requires the Passover lamb to be 'without blemish' — the Hebrew 'tamim,' which means whole, complete, sound. This is the same word used in Genesis 6:9 to describe Noah as 'perfect' (tamim) in his generations. It denotes not merely the absence of defect but a positive wholeness and integrity — a fitting type for the sinless Christ.",
      commentary: "The instructions for the Passover lamb in Exodus 12 are detailed and deliberate, and every detail points to Christ. The lamb must be without blemish — Christ was without sin. It must be a male of the first year — in the prime of life, as Christ was when He was crucified. It must be set apart on the tenth day and slain on the fourteenth — Christ entered Jerusalem on the tenth of Nisan and was crucified on the fourteenth. Its blood must be applied to the doorposts — not merely shed but personally appropriated by each household.\n\nThe blood on the doorposts is a particularly powerful detail. The death angel passed through Egypt, and wherever blood was applied, death passed over. The protection was not automatic — each family had to act, had to take the blood of the lamb and place it on their own door. This is an exact type of the Atonement: Christ's blood was shed for all, but its saving power must be personally received through faith, repentance, and covenant.\n\nPaul makes the connection explicit in 1 Corinthians 5:7: 'Christ our passover is sacrificed for us.' This is not allegory or metaphor in Paul's mind — it is typological fulfillment. The Passover was not merely a historical event that happened to resemble Christ's death; it was divinely designed as a prophetic enactment of what the Lamb of God would do.\n\nThe timing confirms this: Jesus was crucified on the day of Passover preparation, at approximately the same hour the Passover lambs were being slain in the temple. The entire sacrificial system was pointing to one afternoon on Golgotha.",
      patterns: "The Passover-to-Atonement typology is one of the most thoroughly developed in scripture. It connects Exodus to the Gospels, the temple to the cross, and the blood on doorposts to the sacrament table. This is the foundation for the types and shadows discussed in Weeks 39–41.",
      reflection: "The Passover blood had to be individually applied to each doorpost. In what ways are you personally applying the Atonement of Christ in your life — not just believing in it but actively receiving it?"
    },
    {
      label: "A lamb to the slaughter",
      focus: "Isaiah 53 is the most detailed Old Testament portrait of the suffering Messiah. Today examines the Lamb who was led in silence to His death.",
      scriptures: [{book:"Isa",ch:53,vs:7},{book:"Alma",ch:34,vs:8,ve:14},{book:"1 Pet",ch:1,vs:18,ve:20}],
      nuances: "Isaiah 53:7 says He 'opened not his mouth' — the Hebrew 'lo yiftach piv' emphasizes deliberate, chosen silence. This is not the silence of helplessness but of supreme self-control. A lamb being led to slaughter does not resist, but Isaiah's point is deeper: the Suffering Servant had the power to speak, to resist, to call down angels — and chose not to.",
      commentary: "Isaiah 53 stands as the most profound messianic prophecy in the Old Testament. Verse 7 captures the character of Christ's sacrifice in a single image: He is brought as a lamb to the slaughter, and as a sheep before her shearers is dumb, so He opened not His mouth. The silence of the Lamb is not weakness — it is the highest expression of voluntary submission.\n\nThe Gospels record this silence in multiple settings. Before the Sanhedrin, before Herod, before Pilate — Jesus' silence astonished His accusers. Pilate marveled that He would not defend Himself. This was not passivity. It was the deliberate fulfillment of Isaiah's prophecy and the clearest evidence that His death was chosen, not imposed.\n\nAmulek's great discourse in Alma 34 provides Restoration scripture's most systematic theology of the sacrifice. It must be infinite and eternal. It must be the sacrifice of a God to satisfy the demands of justice. No human offering could accomplish this — only the sacrifice of the great and last Lamb. Amulek explicitly connects the entire Mosaic sacrificial system to this one offering, arguing that every animal sacrifice was a type and shadow of the Lamb of God.\n\nPeter adds the dimension of foreordination: Christ was foreordained before the foundation of the world as a lamb without blemish and without spot. His sacrifice was not a contingency plan — it was the plan, established before creation began. The Lamb was chosen before the world was made.",
      patterns: "Isaiah 53, Alma 34, and 1 Peter 1 form a three-witness testimony across three dispensations and three continents that the Lamb's sacrifice was planned from the beginning, voluntary in its execution, and infinite in its scope.",
      reflection: "Christ chose silence before His accusers when He had the power to speak. Is there a situation in your life where choosing restraint rather than self-defense would be the more Christlike response?"
    },
    {
      label: "Slain from the foundation of the world",
      focus: "The Lamb's sacrifice was not a reaction to human sin — it was planned before creation. Today explores the premortal foreordination of the Atonement.",
      scriptures: [{book:"Rev",ch:13,vs:8},{book:"Moses",ch:7,vs:47},{book:"1 Pet",ch:1,vs:18,ve:20}],
      nuances: "Revelation 13:8 refers to 'the Lamb slain from the foundation of the world' — the Greek 'apo katabolēs kosmou' literally means 'from the casting down of the world,' using a word that implies the laying of a foundation stone. The sacrifice of Christ is presented as the foundational act upon which everything else in creation is built.",
      commentary: "Revelation 13:8 contains one of the most theologically dense phrases in all of scripture: the Lamb slain from the foundation of the world. This does not merely mean that God foresaw Christ's death. It means the Atonement was the foundational reality upon which creation itself was built. Before the first star burned, before Adam breathed, the Lamb's sacrifice was the settled certainty upon which the entire plan rested.\n\nMoses 7:47 provides a Restoration witness to this same truth. In Enoch's vision, the Lamb is slain from the foundation of the world — using virtually identical language to Revelation. This parallel between John's apocalyptic vision and Enoch's prophetic vision, separated by thousands of years, testifies that the teaching is ancient, consistent, and true.\n\nPeter confirms that Christ was foreordained before the foundation of the world but manifest in these last times. The word 'foreordained' (Greek: 'proegnōsmenou,' meaning foreknown) indicates that the Father's knowledge of and commitment to the Son's sacrifice preceded all of creation. Every covenant, every prophecy, every ordinance was designed in light of this already-established reality.\n\nThis has profound implications for how we understand suffering and the problem of evil. God did not create the world and then scramble to fix it when things went wrong. The remedy was embedded in the foundation. The Lamb was always the plan.",
      patterns: "The concept of foreordination runs through scripture — Christ was foreordained as Redeemer, prophets were foreordained to their callings (Jer 1:5, Alma 13:3), and the plan of salvation was established before the world was. This connects to the premortal existence themes in Week 3.",
      reflection: "If the Atonement was planned before creation, what does that tell you about how seriously God takes your individual salvation? What does it mean that you were worth planning for before you existed?"
    },
    {
      label: "The Lamb on the throne",
      focus: "The slain Lamb does not remain in death — He rises and takes His place at the center of heaven's throne. Today explores the exalted Lamb of Revelation.",
      scriptures: [{book:"Rev",ch:5,vs:6,ve:14},{book:"Rev",ch:7,vs:13,ve:17},{book:"D&C",ch:76,vs:85}],
      nuances: "In Revelation 5:6, the Lamb stands 'as it had been slain' — the Greek 'hōs esphagmenon' means bearing the marks of slaughter while being alive. The Lamb is simultaneously the sacrificial victim and the reigning sovereign. His wounds are not healed and hidden but displayed as signs of His triumph. This connects to the resurrected Christ showing His wounds in John 20 and 3 Nephi 11.",
      commentary: "Revelation 5 presents one of the most dramatic scenes in scripture. A scroll sealed with seven seals is held in the right hand of Him who sits on the throne. No one in heaven or earth can open it, and John weeps. Then the announcement comes: the Lion of the tribe of Judah has prevailed. But when John turns to look, he sees not a lion but a Lamb — standing, alive, yet bearing the marks of having been slain. This is the central paradox of Christian faith: the conqueror conquers by being slain.\n\nThe twenty-four elders and the four living creatures fall down before the Lamb and sing a new song: 'Thou art worthy to take the book, and to open the seals thereof: for thou wast slain, and hast redeemed us to God by thy blood out of every kindred, and tongue, and people, and nation.' The worthiness to rule comes directly from the willingness to die. No other claim to authority — not power, not wisdom, not lineage — is sufficient. Only sacrifice qualifies.\n\nRevelation 7 extends the image: the Lamb at the center of the throne will shepherd those who have come through great tribulation. He will lead them to living waters and wipe away every tear. The Lamb is simultaneously the sacrifice and the shepherd — the one who was slain and the one who tends the flock forever.\n\nD&C 76:85 places even those in the telestial kingdom under the Lamb's eventual ministry, confirming that His redemptive reach extends to every soul. The throne of the Lamb is not exclusive — it radiates grace outward to the furthest edges of creation.",
      patterns: "The 'slain yet standing' image is the visual summary of the entire gospel: death defeated, sacrifice vindicated, the victim enthroned. This connects Week 27 (Lamb) to Week 26 (King) — the Lamb is the King, and the King bears the marks of the Lamb.",
      reflection: "The Lamb's wounds are not hidden in heaven — they are displayed. What does it mean that Christ's suffering is eternally visible, eternally honored?"
    },
    {
      label: "Abraham's lamb and ours",
      focus: "When Isaac asked 'Where is the lamb?', Abraham answered with a prophecy that spans all of scripture. Today explores the binding of Isaac as a type of the Lamb.",
      scriptures: [{book:"Gen",ch:22,vs:7,ve:8},{book:"Gen",ch:22,vs:13},{book:"Moro",ch:10,vs:33}],
      nuances: "Genesis 22:8 reads 'God will provide himself a lamb' — the Hebrew 'Elohim yireh lo haseh' is ambiguous and theologically rich. It can mean 'God will provide for Himself a lamb' (God will supply the offering) or 'God will provide Himself as the lamb' (God Himself will be the offering). Both readings are true, and the ambiguity appears to be divinely intentional.",
      commentary: "The binding of Isaac in Genesis 22 is one of the most studied passages in all of scripture, and at its center is a question about a lamb. Isaac, carrying the wood for the sacrifice up Mount Moriah, asks his father: 'Where is the lamb for a burnt offering?' Abraham's answer is one of the most prophetic statements in the Old Testament: 'My son, God will provide himself a lamb.'\n\nThe immediate fulfillment was the ram caught in the thicket — a substitute provided at the last moment so Isaac could live. But the deeper fulfillment took two thousand years. On that same mountain range (tradition identifies Moriah with the temple mount in Jerusalem, and Golgotha is nearby), God did provide Himself as the Lamb. The Father offered His Son as the sacrifice that Abraham was spared from completing.\n\nThe parallels are striking and deliberate. Isaac carried the wood; Christ carried the cross. Isaac submitted to his father's will; Christ submitted to His Father's will. A substitute was provided so that Isaac might live; Christ became the substitute so that all humanity might live. The ram caught in the thorns prefigures the crown of thorns placed on the Lamb's head.\n\nMoroni 10:33 provides the closing invitation of the Book of Mormon: come unto Christ and be perfected in Him. The Lamb has been provided. The sacrifice has been made. The only question remaining is whether we will accept what God has provided — whether we will apply the blood to our own doorposts, lay our burdens on our own substitute, and receive the life the Lamb died to give.",
      patterns: "The Moriah-Golgotha geographic connection is one of the most powerful typological links in scripture, tying Genesis to the Gospels across two millennia. The substitutionary pattern — something dies so that someone else may live — is the structural foundation of the entire sacrificial system and the Atonement itself.",
      reflection: "Abraham trusted that God would provide the lamb, even when he could not see how. Where in your life are you being asked to trust God's provision before you can see the outcome?"
    },
    {
      label: "The Lamb's light",
      focus: "In the final vision of the Bible, there is no temple and no sun — because the Lamb Himself is the light of the eternal city. Today concludes with the Lamb's ultimate triumph.",
      scriptures: [{book:"Rev",ch:21,vs:22,ve:27},{book:"Rev",ch:5,vs:12,ve:13},{book:"Alma",ch:34,vs:10,ve:14}],
      nuances: "Revelation 21:23 says the city 'had no need of the sun, neither of the moon, to shine in it: for the glory of God did lighten it, and the Lamb is the light thereof.' The Greek 'luchnos' (lamp) is used for the Lamb — He is the personal, immediate source of light for the entire city. This connects to D&C 88:6–13 where the light of Christ fills the immensity of space.",
      commentary: "The final chapters of Revelation present the new Jerusalem — the culmination of God's redemptive plan. And in that city, there is no temple, because the Lord God Almighty and the Lamb are the temple. There is no sun, because the Lamb is its light. Every institution, every structure, every mediation that was necessary in a fallen world becomes unnecessary when the Lamb is fully present. He replaces every lesser source of light and every lesser means of access to God.\n\nThis is the ultimate vindication of the Lamb. The one who was rejected, mocked, and slain now illuminates the eternal city. The one whose blood was spilled on a criminal's cross now sits enthroned as the source of all light and life. The trajectory from Golgotha to the New Jerusalem is the trajectory of the entire gospel: apparent defeat transformed into ultimate triumph.\n\nRevelation 5:12–13 records the heavenly chorus declaring the Lamb worthy to receive power, riches, wisdom, strength, honor, glory, and blessing. Then every creature in heaven, on earth, under the earth, and in the sea joins the song. This is the universal acknowledgment that Philippians 2 promises — every knee bowing, every tongue confessing — but expressed in worship rather than compulsion.\n\nAlma 34:10–14 brings the week full circle by reminding us why all of this is possible: the sacrifice had to be infinite and eternal, not a human sacrifice but a divine one. Only the Lamb of God — God Himself taking the form of a sacrificial animal — could accomplish what needed to be done. Every other sacrifice in every dispensation was a shadow pointing to this single, sufficient, infinite offering.",
      patterns: "The Lamb as the light of the eternal city connects to Christ as the Light of the World (Week 15) and to the D&C 88 description of the light of Christ filling all space. The trajectory from sacrificial lamb to the source of eternal light is the master narrative of all scripture.",
      reflection: "If the Lamb is the only light in the eternal city, what does it mean to orient your life toward His light now — before that day arrives?"
    }
  ]
};

export default week27;
