import type { WeekContent } from '../types';

const week03: WeekContent = {
  title: "The Anointed One",
  subtitle: "What does it mean that Jesus was \u2018anointed\u2019? This week explores the ancient practice and its fulfillment in Christ.",
  weekScriptures: "Ex. 30:22\u201330; Lev. 8:10\u201312; Ps. 2:2; Deut. 18:15\u201318; Acts 3:22\u201323; 3 Ne. 20:23; Heb. 5:1\u20136; Heb. 7:24\u201327; Alma 13:1\u20139; Isa. 9:6\u20137; Luke 1:32\u201333; Rev. 19:16; Luke 4:16\u201321; Acts 10:38; 2 Ne. 10:3; 2 Cor. 1:21\u201322; 1 Jn. 2:20\u201327; D&C 109:80; Philip. 2:9\u201311; Mosiah 3:17; D&C 19:18\u201319",
  synthesis: {
    summary: "The titles \u2018Christ\u2019 (Greek) and \u2018Messiah\u2019 (Hebrew) both mean \u2018the Anointed One.\u2019 Anointing in ancient Israel set apart prophets, priests, and kings. Jesus fulfilled all three roles \u2014 not symbolically but completely.",
    connections: [
      "The God who gave the anointing ordinance in the Old Testament is the same God who fulfilled it (Week 8, Jehovah).",
      "The three anointed roles (prophet, priest, king) connect to future weeks: Teaching Mode (20), Head of the Church (37), King & Lord (26).",
      "Being set apart by anointing parallels how we are set apart through covenant (Week 36)."
    ],
    teaching: "How would you explain to a class what \u2018Christ\u2019 actually means? How does the anointing background enrich the way we use His name?",
    commitment: "Each time you say \u2018Jesus Christ\u2019 this week, let the word \u2018Christ\u2019 remind you that He was divinely set apart \u2014 and consider what you have been set apart to do."
  },
  days: [
    {
      label: "The meaning of anointing",
      focus: "Before we can understand why Jesus is called \u2018the Christ,\u2019 we need to understand what anointing meant in ancient Israel.",
      scriptures: [{book:"Ex",ch:30,vs:22,ve:30},{book:"Lev",ch:8,vs:10,ve:12},{book:"Ps",ch:2,vs:2}],
      nuances: "The Hebrew word for \u2018anointed\u2019 is \u2018mashiach\u2019 (Messiah); the Greek equivalent is \u2018christos\u2019 (Christ). Both words literally mean \u2018smeared\u2019 or \u2018rubbed with oil.\u2019 In Psalm 2:2, the \u2018anointed\u2019 is set in parallel with the Lord Himself \u2014 suggesting that the anointed one shares in divine authority.",
      commentary: "Anointing with oil was the ancient Israelite ordinance of consecration. Exodus 30 prescribes the sacred anointing oil \u2014 a specific mixture of myrrh, cinnamon, calamus, cassia, and olive oil. This was not a generic ritual; it was a precisely formulated sacrament reserved for sacred purposes. Leviticus 8 shows Aaron being anointed as high priest \u2014 oil poured on his head, setting him apart for service in the tabernacle.\n\nPsalm 2 prophesies of the Lord\u2019s \u2018anointed\u2019 \u2014 a royal, messianic figure whom the nations would rage against but could never overthrow. This psalm was read messianically by both Jewish and Christian interpreters for centuries.\n\nThe key principle: anointing was never self-appointed. It always came from God through an authorized servant. Kings were anointed by prophets (Samuel anointed Saul and David), priests were anointed through prescribed ritual, and prophets were called by divine commission. This matters because Christ\u2019s authority was not self-claimed \u2014 it was divinely given.",
      patterns: "Oil is associated with the Holy Spirit throughout scripture. The anointing pattern \u2014 divine appointment through authorized channels \u2014 is the same pattern that governs priesthood ordination today.",
      reflection: "What responsibilities or callings have you been \u2018set apart\u2019 for? How does understanding the weight of anointing change how you view those responsibilities?"
    },
    {
      label: "Anointed as Prophet",
      focus: "The first of three anointed roles. Today examines Christ as the prophet Moses foretold \u2014 and how three dispensations confirm it.",
      scriptures: [{book:"Deut",ch:18,vs:15,ve:18},{book:"Acts",ch:3,vs:22,ve:23},{book:"3 Ne",ch:20,vs:23}],
      nuances: "In Deuteronomy 18:15, \u2018a Prophet from the midst of thee, of thy brethren, like unto me\u2019 \u2014 the phrase \u2018like unto me\u2019 is significant. Moses was the greatest prophet Israel had known: deliverer, lawgiver, mediator, covenant-maker. To say Christ would be \u2018like Moses\u2019 was to say He would be all of these things and more.",
      commentary: "Moses prophesied that God would raise up a prophet like himself from among Israel. Peter, in Acts 3, identifies Jesus as that prophet \u2014 and adds a warning: those who will not hear Him will be destroyed. The resurrected Christ Himself, speaking to the Nephites in 3 Nephi 20, confirms the same identification.\n\nA prophet speaks for God. But Jesus did not merely speak for God \u2014 He was God speaking directly to humanity. This is the distinction between Christ and every other prophet: the others were messengers; He was the message.\n\nMoses as a type of Christ is one of the richest typological patterns in scripture (to be explored fully in Week 40). Both were born under threats to their lives, both delivered their people from bondage, both were mediators of covenants, both spoke with God face to face.\n\nBroader Christian theology has long recognized Christ\u2019s prophetic office. Calvin\u2019s \u2018threefold office\u2019 (prophet, priest, king) became standard Reformed theology and is reflected in many catechisms. Restoration theology embraces this framework while adding living prophets who serve under Christ\u2019s direction.",
      patterns: "God promises, centuries pass, and then God fulfills \u2014 precisely and completely. The gap between prophecy and fulfillment is never an accident; it is a test of faith.",
      reflection: "Do you listen to Christ as a prophet \u2014 someone whose words require a response and a change in behavior \u2014 or only as a historical figure whose words are optional?"
    },
    {
      label: "Anointed as Priest",
      focus: "The second anointed role. Today examines Christ\u2019s unique priesthood \u2014 not Levitical, but eternal.",
      scriptures: [{book:"Heb",ch:5,vs:1,ve:6},{book:"Heb",ch:7,vs:24,ve:27},{book:"Alma",ch:13,vs:1,ve:9}],
      nuances: "Hebrews 5:6 quotes Psalm 110:4: \u2018Thou art a priest for ever after the order of Melchisedec.\u2019 The Greek \u2018eis ton ai\u014dna\u2019 means \u2018into the age\u2019 \u2014 an unending priesthood. Unlike Levitical priests who served until death, Christ\u2019s priesthood has no terminus. Hebrews 7:24 uses \u2018aparabatos\u2019 \u2014 untransferable, permanent. No one succeeds Him in this office.",
      commentary: "Hebrews explains that Christ was not a Levitical priest but a priest after the order of Melchizedek \u2014 a higher, eternal priesthood. Unlike earthly priests who offered sacrifices daily and then died, He offered Himself once for all and lives forever to intercede.\n\nAlma 13 connects this priesthood to the pre-mortal foreordination of high priests. They were called and prepared \u2018from the foundation of the world according to the foreknowledge of God.\u2019 This is a uniquely Restoration insight: the Melchizedek Priesthood is not just a New Testament concept but an eternal one, operative before and after mortality.\n\nThe historical Melchizedek (Genesis 14) was a priest-king of Salem who blessed Abraham and received tithes from him. Hebrews interprets this as evidence of a priesthood greater than the Levitical line. Early Christian writers like Clement of Alexandria saw Melchizedek as a type of Christ. Restoration theology names the higher priesthood after this figure and traces its authority directly through Christ.",
      patterns: "The priesthood you hold or benefit from today traces its authority back to the same order Christ fulfilled. The ordinances performed in temples are exercises of this priesthood.",
      reflection: "How does knowing that Christ is your High Priest \u2014 actively interceding with a permanent, untransferable priesthood \u2014 change the way you think about repentance and access to God?"
    },
    {
      label: "Anointed as King",
      focus: "The third anointed role \u2014 and the one not yet fully realized. Today looks at Christ\u2019s kingship: prophesied, confirmed, and yet to come.",
      scriptures: [{book:"Isa",ch:9,vs:6,ve:7},{book:"Luke",ch:1,vs:32,ve:33},{book:"Rev",ch:19,vs:16}],
      nuances: "Isaiah 9:6 lists four throne names: Wonderful Counsellor, The mighty God, The everlasting Father, The Prince of Peace. In ancient Near Eastern practice, throne names declared the character and agenda of the king. These are not descriptions of four different beings \u2014 they are four dimensions of one King\u2019s rule.",
      commentary: "Isaiah prophesied a child whose government would never end, established upon the throne of David. Gabriel told Mary the same: her son would reign over the house of Jacob forever. Revelation 19 shows His return in full kingly glory: on His robe and on His thigh is written \u2018King of Kings, and Lord of Lords.\u2019\n\nChrist\u2019s kingship is the one anointed role not yet fully manifest. He was anointed prophet (fulfilled in His mortal ministry), priest (fulfilled in the Atonement and ongoing intercession), and king (to be fully realized at the Second Coming). The arc is deliberately incomplete. We live in the tension between His coronation in heaven and His kingdom on earth.\n\nJewish messianic expectation in the first century was heavily focused on the kingly role \u2014 a deliverer who would overthrow Roman occupation. Christ\u2019s first coming did not meet that expectation, which contributed to His rejection. The Second Coming will.\n\nRestoration theology affirms a literal millennial reign (Week 44) and the establishment of Zion \u2014 a political and spiritual kingdom governed by Christ Himself.",
      patterns: "Prophet (fulfilled in mortality), Priest (fulfilled in the Atonement), King (fulfilled at the Second Coming). The arc is incomplete by design \u2014 and we live in the space between promise and fulfillment.",
      reflection: "Do you treat Christ as your King \u2014 someone whose authority shapes your daily decisions \u2014 or only as a future ruler whose reign doesn\u2019t affect you yet?"
    },
    {
      label: "Anointed by the Spirit",
      focus: "His anointing was not ceremonial oil \u2014 it was the Holy Ghost. Today examines the moment He publicly claimed His mission.",
      scriptures: [{book:"Luke",ch:4,vs:16,ve:21},{book:"Acts",ch:10,vs:38},{book:"2 Ne",ch:10,vs:3}],
      nuances: "In Luke 4:18, Jesus reads from Isaiah 61. The phrase \u2018he hath anointed me\u2019 translates the Greek \u2018echrisen me\u2019 \u2014 from \u2018chri\u014d,\u2019 the verb root of \u2018Christos.\u2019 When Jesus says \u2018this day is this scripture fulfilled,\u2019 He is literally claiming to be the Christ \u2014 the Anointed One \u2014 in front of His hometown synagogue.",
      commentary: "In the synagogue at Nazareth, Jesus stood and read from Isaiah 61: the Spirit of the Lord is upon me, because He has anointed me to preach the gospel to the poor, to heal the brokenhearted, to proclaim liberty to the captives. Then He sat down and said: today this scripture is fulfilled in your hearing.\n\nThis is one of the most dramatic moments in the Gospels. His neighbors knew Him as the carpenter\u2019s son. Now He was claiming to be the fulfillment of messianic prophecy. Luke records that their initial amazement turned to murderous rage.\n\nPeter later described how God anointed Jesus of Nazareth with the Holy Ghost and with power (Acts 10:38). His anointing was spiritual, not merely ceremonial. The oil poured on priests and kings was always a symbol of the Spirit; in Christ, the symbol gave way to the reality.\n\n2 Nephi 10:3 adds that the name \u2018Christ\u2019 itself would be revealed by angels to Nephite prophets centuries before the event \u2014 evidence that His anointing was known and anticipated on both hemispheres.",
      patterns: "The anointing of the Holy Ghost gave His earthly ministry power. This same Spirit is offered to every baptized disciple through the gift of the Holy Ghost \u2014 connecting His anointing to ours.",
      reflection: "Have you experienced the Holy Ghost empowering you to do something you couldn\u2019t have done alone? That is participation in the same anointing that empowered Christ."
    },
    {
      label: "What His anointing means for us",
      focus: "The Anointed One creates an anointed people. Today traces how Christ\u2019s consecration flows down to His covenant followers.",
      scriptures: [{book:"2 Cor",ch:1,vs:21,ve:22},{book:"1 Jn",ch:2,vs:20,ve:27},{book:"D&C",ch:109,vs:80}],
      nuances: "In 1 John 2:20, \u2018unction\u2019 (Greek: \u2018chrisma\u2019) is directly related to \u2018Christos.\u2019 John is making a wordplay: because of the Christ, you have a \u2018christing\u2019 \u2014 an anointing of your own. The connection between His title and our endowment is built into the language itself.",
      commentary: "Paul writes that God has anointed us and sealed us with the Spirit (2 Corinthians 1:21\u201322). John says believers have an unction \u2014 an anointing \u2014 from the Holy One, and that this anointing teaches truth (1 John 2:20, 27). The Kirtland Temple dedicatory prayer (D&C 109:80) speaks of the Lord\u2019s servants being anointed with glory.\n\nThe theological principle is stunning: the Anointed One creates an anointed people. What He is, He shares. His consecration is not exclusive to Him \u2014 it flows downward through covenant to all who follow Him.\n\nThis concept has roots in ancient Israel: the whole nation was called to be \u2018a kingdom of priests\u2019 (Exodus 19:6). Peter applies the same language to Christians (1 Peter 2:9). Restoration theology makes this experiential through temple ordinances where individuals are set apart, endowed, and consecrated.\n\nThe practical implication is profound: if you have received the gift of the Holy Ghost, you have received an anointing. You are part of an anointed people with a consecrated mission.",
      patterns: "The Anointed One creates an anointed people. His consecration makes ours possible. This is the heart of covenant theology: what He is, He shares.",
      reflection: "If you are part of an \u2018anointed people,\u2019 set apart by covenant, how should that identity shape the way you live Monday through Saturday?"
    },
    {
      label: "The name above all names",
      focus: "We close the week by considering what it means that God gave Him the highest name \u2014 and what it cost Him to earn it.",
      scriptures: [{book:"Philip",ch:2,vs:9,ve:11},{book:"Mosiah",ch:3,vs:17},{book:"D&C",ch:19,vs:18,ve:19}],
      nuances: "In Philippians 2:9, \u2018a name which is above every name\u2019 \u2014 the Greek \u2018onoma\u2019 refers not just to a label but to the full reality of who someone is: their character, authority, and reputation. God gave Christ not just a title but the fullness of divine identity and authority. The \u2018name above every name\u2019 is likely \u2018Lord\u2019 (Kurios) \u2014 the divine name.",
      commentary: "Philippians 2:9\u201311 is one of the earliest Christian hymns, believed to predate Paul\u2019s letter. It describes Christ\u2019s self-emptying (\u2018kenosis\u2019): He was in the form of God, made Himself nothing, took the form of a servant, humbled Himself to death on a cross. Therefore God exalted Him and gave Him the name above every name, that every knee should bow.\n\nKing Benjamin taught there would be no other name given whereby salvation comes (Mosiah 3:17). The title \u2018Christ\u2019 is not a surname \u2014 it is a declaration of divine mission. Every time we say it, we acknowledge His appointment.\n\nD&C 19:18\u201319 is perhaps the most personal account of the Atonement in all scripture. The Lord Himself describes His suffering: the trembling, the bleeding from every pore, the desire to shrink from the cup. This passage reveals the cost behind the name. The exaltation of Philippians 2 came through the suffering of D&C 19. The glory was earned in agony.\n\nThis is the final insight of the week: the title \u2018the Anointed One\u2019 is not honorific. It was purchased.",
      patterns: "The title \u2018Christ\u2019 carries the weight of His mission, His suffering, and His divine appointment. It connects backward to the anointing of ancient Israel and forward to His kingship at the Second Coming.",
      reflection: "How intentionally do you use the name of Jesus Christ? Does it carry weight in your speech and prayers, or has it become routine?"
    }
  ]
};

export default week03;
