import type { WeekContent } from '../types';

const week20: WeekContent = {
  title: "Teaching Mode — How Christ Taught",
  subtitle: "The Master Teacher used parables, questions, object lessons, and silence to reach every kind of learner.",
  weekScriptures: "Matt 13:44-46; Luke 10:25-37; Luke 15:1-7; Luke 20:1-8; Matt 23:1-3; Mark 10:1; John 6:63; 2 Tim 3:16-17; 2 Ne 9:28-29; Alma 17:2-3; 3 Ne 11:29-30; D&C 42:12-14; D&C 68:3-4",
  synthesis: {
    summary: "Jesus Christ was not merely a teacher who happened to be divine — He was the divine Teacher whose methods perfectly matched His message. He used parables to simultaneously reveal and conceal truth, asked questions that changed the questioner, taught by example and enacted parable, and adjusted His delivery to the readiness of His hearers. His authority as Teacher rested not on credentials but on His relationship with the Father.",
    connections: [
      "Christ's teaching authority connects directly to Week 23 (Authority of), where we explore the source of His power to act.",
      "The parables studied this week often illustrate principles of the Atonement explored in Weeks 12–13 and the nature of the Kingdom discussed in Week 35.",
      "His method of teaching by the Spirit foreshadows Week 34 (Spirit of Jesus Christ) and the way personal revelation works."
    ],
    teaching: "Which of Christ's teaching methods — parables, questions, object lessons, silence, personal example — has been most effective in your own spiritual learning? Why do you think that method resonates with you?",
    commitment: "Choose one of Christ's teaching methods studied this week and consciously use it in a gospel conversation — whether in a class, with your family, or with a friend."
  },
  days: [
    {
      label: "Why He taught in parables",
      focus: "Jesus deliberately chose parables as His primary teaching mode. Today explores why — and what it reveals about how God communicates truth.",
      scriptures: [{book:"Matt",ch:13,vs:10,ve:17},{book:"Mark",ch:4,vs:33,ve:34},{book:"Alma",ch:12,vs:9,ve:11}],
      nuances: "The Greek 'parabole' means 'to throw alongside' — placing one thing next to another for comparison. When Jesus says in Matthew 13:13 that He speaks in parables 'because they seeing see not,' the Greek 'hoti' can mean both 'because' (causal) and 'so that' (purposive). This ambiguity is important: parables both reveal truth to the prepared heart and veil it from the resistant one.",
      commentary: "When the disciples ask Jesus why He teaches in parables, His answer is surprising. He does not say parables make things easier to understand. He says the opposite: parables function as a kind of filter, opening truth to those who are ready and concealing it from those who are not.\n\nThis is not arbitrary gatekeeping. Alma 12:9–11 explains the underlying principle: God gives truth 'according to the heed and diligence' people give to what they have already received. Those who treasure what they have been given receive more; those who neglect it find that even what they had grows dim. Parables operate on this same principle — the story is available to everyone, but its meaning opens only to those who seek it.\n\nMark 4:33–34 adds a crucial detail: Jesus spoke the word to the multitudes 'as they were able to hear it,' but explained everything privately to His disciples. This is graduated instruction — the same Teacher offering different depths to different learners based on their readiness. It is a model for how revelation works in every life: truth comes in proportion to hunger for it.\n\nThe parabolic method also protects the hearer. To receive sacred truth and then reject it increases accountability. By veiling truth in story, Christ allowed people to approach it at their own pace, reducing the condemnation that comes from rejecting what you clearly understand.",
      patterns: "The principle of graduated truth appears across dispensations. The temple, for instance, teaches through symbol and ritual rather than direct lecture — requiring participants to seek meaning. Nephi's method of 'likening' scriptures (1 Ne. 19:23) follows the same pattern: truth becomes personal only when you engage with it actively.",
      reflection: "Is there a parable of Jesus that meant nothing to you years ago but means something now? What changed — the parable or you?"
    },
    {
      label: "Teaching with authority",
      focus: "The crowds were 'astonished at his doctrine' because Jesus taught as one having authority. Today examines what made His teaching fundamentally different from every other teacher.",
      scriptures: [{book:"Matt",ch:7,vs:28,ve:29},{book:"Luke",ch:4,vs:16,ve:22},{book:"John",ch:7,vs:14,ve:17}],
      nuances: "In Matthew 7:29, the word 'authority' translates the Greek 'exousia,' meaning delegated power or right to act. The contrast is with the scribes, who taught by citing prior authorities (Rabbi Hillel said, Rabbi Shammai said). Jesus cited no one. He spoke as the source, not as a channel. In Luke 4:22, the people 'wondered at the gracious words' — the Greek 'logois tes charitos' literally means 'words of grace,' suggesting not just eloquence but divine enabling power flowing through His speech.",
      commentary: "Matthew records that when Jesus finished the Sermon on the Mount, the people were astonished — not merely impressed, but shaken. The Greek 'exeplessonto' implies being struck with amazement to the point of being overwhelmed. The reason given is specific: He taught 'as one having authority, and not as the scribes.'\n\nThe scribes were learned men. They knew the text, debated its meanings, and cited centuries of commentary. But their teaching was derivative — always pointing to someone else's authority. Jesus spoke as the Author. When He said 'I say unto you' in the Sermon on the Mount, He was not offering an opinion. He was declaring the mind of God with the full weight of the One who gave the law to Moses.\n\nIn the synagogue at Nazareth (Luke 4), Jesus read from Isaiah about the coming Messiah, then sat down and said, 'This day is this scripture fulfilled in your ears.' He did not interpret the passage — He claimed to be its subject. This is teaching by identity, not merely by skill.\n\nJohn 7:14–17 adds an important test for the hearer: 'If any man will do his will, he shall know of the doctrine.' The validation of Christ's teaching authority is experiential. You discover that He speaks truth by living what He teaches. This is profoundly different from academic verification — it is the epistemology of discipleship.",
      patterns: "The authority of Christ's teaching connects to the broader pattern of His authority explored in Week 23. His words carry power because of who He is. In 3 Nephi 11, when the resurrected Christ teaches the Nephites, His words have the same effect — the people are transformed not just by the content but by the Person delivering it.",
      reflection: "When have you experienced the difference between hearing true doctrine explained and feeling the authority of the Spirit confirm it? What made those moments different?"
    },
    {
      label: "The Sermon on the Mount as teaching model",
      focus: "The Sermon on the Mount is Christ's longest recorded discourse. Today examines not just what He said but how He structured it — and what that structure reveals.",
      scriptures: [{book:"Matt",ch:5,vs:1,ve:12},{book:"3 Ne",ch:12,vs:1,ve:12},{book:"D&C",ch:88,vs:77,ve:80}],
      nuances: "The Beatitudes use the Greek 'makarioi,' often translated 'blessed.' This word does not mean 'happy' in the modern sense. In Greek philosophical usage, 'makarios' described the state of the gods — a deep, settled well-being independent of circumstances. Jesus is describing not feelings but conditions of the soul that connect mortals to the divine nature.",
      commentary: "The Sermon on the Mount is not a random collection of sayings. It is a carefully structured discourse that moves from inner disposition (the Beatitudes) to outward conduct (the ethical teachings) to the relationship with God (prayer, fasting, trust). Christ begins with who you are becoming, not what you must do. This sequence matters — behavior change without heart change is the religion of the Pharisees.\n\nThe Beatitudes establish a surprising inversion of worldly values: the poor in spirit, the meek, the mourning, the persecuted — these are the ones pronounced blessed. Every category describes a condition that the world considers weakness. Christ redefines strength from the foundation.\n\nWhen Jesus delivered essentially the same sermon to the Nephites (3 Nephi 12), He made several notable adjustments. The most significant is the addition of 'who come unto me' in 3 Nephi 12:3 — 'Blessed are the poor in spirit who come unto me.' The Nephite version makes explicit that the Beatitudes are not generic moral advice but a path to Christ Himself.\n\nD&C 88:77–80 extends the teaching commission to all disciples: 'Teach ye diligently ... of things both in heaven and in the earth.' Christ's model in the Sermon is the pattern — begin with the heart, move to behavior, and ground everything in the relationship with God.",
      patterns: "The Sermon on the Mount provides the template that prophetic teaching follows across dispensations. King Benjamin's address (Mosiah 2–5), which is studied in connection with Week 11 (Atonement), follows a strikingly similar structure — moving from doctrine to covenant to transformation.",
      reflection: "Which Beatitude describes the condition of your soul right now? Which one describes where you feel the Lord is leading you?"
    },
    {
      label: "Questions that change the questioner",
      focus: "Jesus frequently answered questions with questions. Today explores how His questions were themselves a teaching tool — designed to transform the asker, not just transfer information.",
      scriptures: [{book:"Matt",ch:22,vs:15,ve:22},{book:"Mark",ch:11,vs:27,ve:33},{book:"John",ch:8,vs:2,ve:11}],
      nuances: "In Matthew 22:20, Jesus asks 'Whose is this image and superscription?' The Greek 'eikon' (image) is the same word used in Genesis 1:27 (Septuagint) for humanity being made in God's image. His question about the coin carries a layered implication: the coin bears Caesar's image and belongs to Caesar — but you bear God's image and belong to God.",
      commentary: "When the Pharisees tried to trap Jesus with the question about paying tribute to Caesar, He did not give a direct answer. Instead, He asked to see a coin, then asked whose image was on it. By making them supply the answer, He accomplished something a direct statement could not: He made them participants in the discovery of truth.\n\nThis is the Socratic method elevated to divine purpose. But unlike Socrates, Jesus was not merely stimulating thought. He was revealing the heart of the questioner to the questioner. In Mark 11:27–33, when the chief priests demanded to know by what authority He acted, Jesus responded with a question about John's baptism. They could not answer without exposing their own hypocrisy. The question was not evasion — it was diagnosis.\n\nThe encounter with the woman taken in adultery (John 8) provides the most powerful example. Surrounded by accusers demanding a verdict, Jesus stooped and wrote on the ground, then said, 'He that is without sin among you, let him first cast a stone.' This single sentence turned every accuser into a self-examiner. One by one, they left. The question convicted them not of the woman's sin but of their own.\n\nChrist's questions teach us that real spiritual growth often happens not when we receive answers but when we are asked the right question — one that reveals what we actually believe, fear, or desire.",
      patterns: "God's pattern of asking questions to teach goes back to Eden: 'Where art thou?' (Gen. 3:9). God knew where Adam was. The question was for Adam. The same pattern appears in Enos 1:5 ('Enos, what desirest thou?') and in D&C 6:22–23, where the Lord reveals what Oliver Cowdery already experienced to help him recognize his own testimony.",
      reflection: "If Jesus asked you one question right now, what do you think it would be? What does your answer to that reveal about where you are spiritually?"
    },
    {
      label: "Object lessons and enacted parables",
      focus: "Christ did not only tell stories — He created living demonstrations. Today examines how He used physical objects and symbolic actions as teaching tools.",
      scriptures: [{book:"John",ch:13,vs:12,ve:17},{book:"Matt",ch:13,vs:31,ve:33},{book:"2 Ne",ch:31,vs:5,ve:9}],
      nuances: "In John 13:14, 'ought' translates the Greek 'opheilete,' which carries a sense of moral debt or obligation. When Jesus says 'ye also ought to wash one another's feet,' He is not making a polite suggestion. He is saying that His act of service created a binding obligation. The enacted parable generates a covenant-like duty in those who witness it.",
      commentary: "At the Last Supper, Jesus wrapped a towel around His waist and washed the disciples' feet — work reserved for the lowest household servant. Peter resisted, unable to reconcile the Master with the servant's role. But Jesus was not merely being humble. He was teaching through enacted parable: the greatest in the kingdom serves. The lesson was not in His words but in His posture, kneeling at their feet.\n\nThe parables of the mustard seed and the leaven (Matthew 13:31–33) use physical objects the audience could see and touch. A seed so small it seems insignificant grows into something that shelters others. A pinch of leaven works invisibly through the entire lump. Christ anchors divine truth in the tangible world — not to diminish it, but because incarnational theology means physical things can carry spiritual meaning.\n\n2 Nephi 31:5–9 reveals Christ's baptism as an enacted parable on the grandest scale. He who had no sin submitted to baptism to 'fulfil all righteousness' and to show the children of men the path. His baptism taught not by explaining the doctrine but by demonstrating it — the sinless One doing what He asks every sinner to do. This connects directly to Week 21, where we study the baptism of Christ in detail.\n\nChrist's teaching method here is sacramental: physical acts become carriers of spiritual truth. This principle extends to every ordinance of the gospel — baptism, the sacrament, temple rites. Each is an enacted parable.",
      patterns: "The pattern of enacted parable runs from Moses lifting the brazen serpent (Num. 21:8–9; studied in connection with Week 39) to Christ breaking bread at the Last Supper. God consistently uses physical actions to teach spiritual realities, and the ordinances of the gospel are the continuation of this method.",
      reflection: "Which gospel ordinance has taught you the most through the experience of participating in it — not through explanation, but through the act itself?"
    },
    {
      label: "Teaching by the Spirit",
      focus: "Christ taught that the Spirit, not human cleverness, is the true mechanism of gospel teaching. Today examines the relationship between teacher, learner, and the Holy Ghost.",
      scriptures: [{book:"D&C",ch:50,vs:13,ve:22},{book:"Alma",ch:31,vs:5},{book:"Jacob",ch:4,vs:13}],
      nuances: "In D&C 50:22, the phrase 'both are edified and rejoice together' uses language that implies mutuality. The teacher does not simply transmit and the learner receive — both are changed by the Spirit's presence. The Greek root behind 'edify' (oikodomeo) means 'to build a house.' Teaching by the Spirit constructs something durable in both parties.",
      commentary: "D&C 50:13–22 is the Lord's own treatise on pedagogy. He asks: if a teacher preaches truth by the Spirit and a learner receives by the Spirit, do they not both understand and are both edified? The mechanism of true gospel teaching is not eloquence, preparation, or expertise (though these have their place). It is the Holy Ghost working simultaneously in the teacher and the learner.\n\nThis explains why a simple, unpolished testimony can pierce the heart while a brilliant lecture can leave the soul untouched. The power is not in the vessel but in the Spirit that fills it. D&C 50 also contains a warning: teaching that does not come by the Spirit, 'it is not of God.' This is a high standard. It does not mean every lesson must be a spiritual peak experience, but it does mean that the teacher's intent and reliance must be on the Spirit, not on personal performance.\n\nAlma 31:5 states that the preaching of the word had 'a great tendency to lead the people to do that which was just — yea, it had had more powerful effect upon the minds of the people than the sword.' This is a remarkable claim: teaching is more powerful than force. Christ's entire mortal ministry demonstrates this principle — He had the power to compel, but chose to teach.\n\nJacob 4:13 adds that 'the Spirit speaketh the truth and lieth not.' The Spirit is not merely an emotional amplifier — it is a truth-bearing agent. When teaching is done by the Spirit, the content itself is sanctified and clarified.",
      patterns: "The Spirit as the true teacher connects to Week 34 (Spirit of Jesus Christ). Christ promised the disciples that the Comforter would 'teach you all things' (John 14:26). Every faithful teacher in every dispensation has been a conduit for the Spirit's instruction, not its replacement.",
      reflection: "Think of a time you were taught the gospel and felt the Spirit powerfully. Was the power in the words, the teacher, or something beyond both? What does that tell you about how real learning happens?"
    },
    {
      label: "Adjusting to the learner",
      focus: "Christ never taught a one-size-fits-all curriculum. Today examines how He tailored His message to the individual — and what that reveals about how God communicates with you.",
      scriptures: [{book:"John",ch:3,vs:1,ve:12},{book:"3 Ne",ch:17,vs:1,ve:3},{book:"Mosiah",ch:4,vs:9,ve:10}],
      nuances: "In John 3:10, Jesus says to Nicodemus, 'Art thou a master of Israel, and knowest not these things?' The title 'didaskalos tou Israel' (teacher of Israel) is used with subtle irony — Nicodemus holds the very office responsible for teaching Israel about spiritual rebirth, yet he does not understand it. Jesus adjusts His teaching to expose the gap between Nicodemus's credentials and his comprehension.",
      commentary: "Nicodemus was a Pharisee, a ruler of the Jews, a man of education and religious authority. Jesus did not teach him as He taught the fishermen or the multitudes. He met Nicodemus at the level of his learning and then pushed beyond it: 'Ye must be born again.' When Nicodemus responded with a literal question ('How can a man enter his mother's womb a second time?'), Jesus did not mock him but pressed further, using the wind as an analogy for the Spirit — something an educated man could grasp.\n\nContrast this with 3 Nephi 17:1–3, where Jesus recognizes that the Nephites are overwhelmed by what He has taught. He does not push forward. He tells them to go home, ponder, pray, and prepare their minds for what He will teach the next day. This is the Master Teacher choosing to stop — recognizing that more information at that moment would not produce more understanding. Sometimes the most powerful teaching is knowing when to pause.\n\nKing Benjamin in Mosiah 4:9–10 teaches with extraordinary simplicity: 'Believe in God; believe that he is.' This is instruction pared to its essence, given to a people who need foundational faith before they can absorb complexity. The simplicity is not condescension — it is precision.\n\nChrist's pattern reveals a God who knows each learner individually. He does not broadcast a single signal and hope someone receives it. He speaks to Nicodemus as Nicodemus, to Peter as Peter, to you as you. This personalized teaching continues through the Holy Ghost, who, as promised, will 'bring all things to your remembrance' (John 14:26) — the specific things you need, when you need them.",
      patterns: "The principle of adapted teaching appears in the Lord's instruction to Joseph Smith: 'I will give unto the children of men line upon line, precept upon precept' (2 Ne. 28:30; D&C 98:12). God never overwhelms. He builds. This graduated approach is the foundation of personal revelation and connects to Week 5 (Appearances of Christ), where the Lord reveals Himself in ways each witness can receive.",
      reflection: "How does God seem to teach you best — through scripture, through other people, through experience, through quiet impressions? What does that tell you about how He knows you?"
    }
  ]
};

export default week20;
