import type { WeekContent } from '../types';

const week13: WeekContent = {
  title: "Atonement through — The Doctrine at the Heart of Everything",
  subtitle: "The Atonement of Jesus Christ is the central act of all human history — the event that makes repentance possible, justice satisfiable, and mercy real.",
  weekScriptures: "Lev 16:15-16; Isa 1:18; Matt 26:28; John 1:29; Rom 3:23-25; 1 Jn 1:7; Heb 10:10-14; 1 Jn 2:2; 2 Ne 25:23; Mosiah 4:6-8; Alma 36:17-21; D&C 76:40-42",
  synthesis: {
    summary: "The Atonement of Jesus Christ is the doctrine upon which all other doctrines depend. Without it, the plan of salvation has no mechanism, faith has no object, repentance has no power, and death has no remedy. This week explores what the Atonement is, why it was necessary, how it works, and what it demands of us. We draw from the richest scriptural treatments across the Bible, Book of Mormon, and Doctrine and Covenants to understand the infinite and eternal sacrifice that stands at the center of eternity.",
    connections: [
      "The Crucifixion (Week 11) and Resurrection (Week 12) are the historical events through which the Atonement was accomplished — this week explores the doctrine behind those events.",
      "The mission of Christ (Week 9) finds its ultimate purpose in the Atonement — everything He came to do was in service of this sacrifice.",
      "The identity of Christ (Week 1) establishes why only He could atone — His divine nature made the sacrifice infinite; His mortal nature made it experiential."
    ],
    teaching: "The Atonement satisfies both justice and mercy simultaneously. How do you explain this to someone who feels that forgiveness is unfair or that justice is cruel? How do both demands express God's love?",
    commitment: "Choose one burden — a sin, a sorrow, a weakness — and consciously give it to Christ this week through sincere prayer. Let the Atonement do what it was designed to do: carry what you cannot carry alone."
  },
  days: [
    {
      label: "He took upon Himself our pains",
      focus: "The Atonement was not limited to sin. Christ also bore our pains, sicknesses, and infirmities. Today explores the empathic dimension of the Atonement.",
      scriptures: [{book:"Alma",ch:7,vs:11,ve:13},{book:"Isa",ch:53,vs:4,ve:6},{book:"Heb",ch:2,vs:9,ve:10}],
      nuances: "In Alma 7:11, the phrase 'pains and afflictions and temptations of every kind' uses a catalog structure common in both Hebrew and Nephite literary tradition — the listing of specifics is meant to be exhaustive, not representative. Alma is saying Christ bore every kind of suffering, not a sampling. The word 'succor' in verse 12 comes from the Latin 'succurrere' — to run to help. Christ does not wait for us to reach Him; He runs to us.",
      commentary: "Alma 7:11–13 is one of the most distinctive and doctrinally rich passages in all of Restoration scripture. While broader Christianity has long understood the Atonement primarily in terms of sin-bearing, Alma expands the scope dramatically. Christ took upon Himself not only sins but pains, afflictions, temptations, sicknesses, infirmities, and death. The purpose was not merely legal substitution but experiential knowledge: He would know, according to the flesh, how to succor His people.\n\nThis empathic dimension transforms the Atonement from a transaction into a relationship. Christ does not merely pay for your sins from a distance — He has personally experienced your specific suffering. The depression you carry, the grief you endure, the physical pain that limits you — He knows it. Not theoretically. Experientially.\n\nIsaiah 53:4–6 is the Old Testament anchor for this teaching. He has borne our griefs and carried our sorrows. We esteemed Him stricken, smitten of God — but He was wounded for our transgressions. The Hebrew 'nasa' (bore/carried) implies lifting and carrying away, like a scapegoat bearing the sins of the people into the wilderness.\n\nHebrews 2:9–10 adds that it was fitting for God, in bringing many sons to glory, to make the captain of their salvation perfect through sufferings. The word 'perfect' (telei\u014dsai) means 'to complete' or 'to bring to full capacity.' Christ's suffering was not a deficiency to overcome — it was the means by which His capacity to help was completed.\n\nThe convergence of these three passages — Nephite, Israelite, and early Christian — establishes that the Atonement is as much about empathy as it is about justice. Christ saves not only from sin but through suffering.",
      patterns: "The empathic Atonement connects to Week 1's study of the Incarnation — God became mortal not merely to die but to understand. The same Christ who holds the universe together (Colossians 1:17) wept at Lazarus's tomb. He operates at every scale.",
      reflection: "What suffering in your life have you assumed Christ could not understand? How does Alma 7:11–13 challenge that assumption?"
    },
    {
      label: "An infinite and eternal sacrifice",
      focus: "The Atonement had to be infinite — not merely large but unlimited. Today examines why no lesser sacrifice could accomplish what was required.",
      scriptures: [{book:"Alma",ch:34,vs:8,ve:14},{book:"2 Ne",ch:9,vs:19,ve:26},{book:"2 Ne",ch:2,vs:6,ve:10}],
      nuances: "In Alma 34:10, Amulek uses the phrase 'infinite and eternal sacrifice.' The word 'infinite' translates a concept that has no direct Hebrew or reformed Egyptian equivalent — it means without boundary or limit. The sacrifice is not merely sufficient for a large number of sins; it is unlimited in its capacity. The word 'eternal' (from the same root as 'eternity') suggests the sacrifice operates outside time — it applies backward to Adam and forward to the last soul who will ever live.",
      commentary: "Amulek's discourse in Alma 34 is one of the most systematic treatments of Atonement theology in all of scripture. He explains that the law of Moses and its animal sacrifices were types pointing to the great and last sacrifice of the Son of God. That sacrifice must be infinite and eternal because the problem it addresses — the fall of all humanity, the demands of a universal law of justice — is itself infinite in scope.\n\nThe logic is precise: a finite sacrifice could cover a finite number of sins. But the sins of all humanity across all time are, in aggregate, beyond any finite measure. Therefore, only a being of infinite worth — the Son of God — could offer a sacrifice of sufficient scope. This is not arbitrary theology — it is the logical necessity of the plan.\n\nJacob's great sermon in 2 Nephi 9:19–26 lays out the consequences if there were no Atonement. Our spirits would become subject to the devil. Our flesh would rot and not rise again. We would be cast off forever. The Atonement is not a convenience — it is the only thing standing between humanity and permanent, irrecoverable ruin.\n\nLehi, in 2 Nephi 2:6–10, teaches that redemption comes through the merits, mercy, and grace of the Holy Messiah. The word 'merits' is significant — it is Christ's worthiness, not ours, that activates the Atonement. We bring a broken heart and contrite spirit; He brings infinite merit.\n\nBroader Christian theology has developed multiple atonement theories — ransom, satisfaction, moral influence, penal substitution, Christus Victor. Restoration scripture does not limit itself to one model but affirms elements of several: Christ satisfied justice (Alma 42), paid a ransom (2 Nephi 9), conquered death (Mosiah 16), and transformed hearts (Moroni 10). The Atonement is too vast for a single explanatory framework.",
      patterns: "The principle of infinite sacrifice answers a question that recurred across the law of Moses: why did sacrifices have to be repeated? Because they were finite. The great and last sacrifice is offered once because it is infinite. It does not run out.",
      reflection: "Do you ever feel your sins or problems are too great for the Atonement to cover? How does the doctrine of infinite sacrifice address that fear?"
    },
    {
      label: "The Savior's own account",
      focus: "In D&C 19, Christ Himself describes what He suffered. Today we hear the Atonement from the perspective of the one who endured it.",
      scriptures: [{book:"D&C",ch:19,vs:15,ve:19},{book:"Mosiah",ch:3,vs:5,ve:11},{book:"Luke",ch:22,vs:42,ve:44}],
      nuances: "D&C 19:18 is remarkable for its first-person perspective: 'Which suffering caused myself, even God, the greatest of all, to tremble because of pain, and to bleed at every pore, and to suffer both body and spirit.' The phrase 'even God, the greatest of all' is not boasting — it establishes the magnitude of the suffering. If the greatest being in the universe trembled, the suffering was beyond all human comprehension.",
      commentary: "D&C 19 is singular in all of scripture because it records the Savior's own first-person account of His atoning suffering, spoken to Martin Harris in 1830. Christ commands Martin — and by extension all of us — to repent, lest we suffer as He suffered. Then He describes that suffering: it caused Him to tremble because of pain, to bleed at every pore, and to wish He might not drink the bitter cup.\n\nThe honesty of this passage is staggering. The Son of God admits that He wished He could avoid the Atonement. He did not want to suffer. He chose to because the Father's will required it and because He loved us enough to endure what He did not want to endure. This is not robotic obedience — it is the highest form of love, exercised in the face of the deepest reluctance.\n\nKing Benjamin's angel-given sermon in Mosiah 3:5–11 describes the same suffering from a prophetic vantage: blood coming from every pore because of anguish over the wickedness and abominations of His people. The physical symptom (blood from every pore) is caused by an emotional and spiritual reality (anguish over sin). The Atonement was not merely a physical ordeal — it was a confrontation with every sin, every cruelty, every act of selfishness and violence in human history.\n\nLuke's account of Gethsemane (22:42–44), studied in Week 10 from the perspective of the arrest, takes on deeper meaning in the context of Atonement theology. The sweat like drops of blood, the angel strengthening Him, the prayer 'not my will but thine' — these are not incidental details but the record of the most consequential suffering in the history of the universe.\n\nNo human mind can fully comprehend what Christ endured. But we can stand at the edge of comprehension, in reverence, and let the weight of it deepen our gratitude and our determination to honor His sacrifice.",
      patterns: "D&C 19 is one of the few passages where Christ speaks in first person about His suffering. The rarity of this perspective makes it precious. He does not often describe what He endured — He more often describes what He offers. When He does speak of His suffering, we should listen with particular care.",
      reflection: "Christ wished He could avoid the suffering but chose to endure it anyway. Have you ever had to do something painful that you knew was right? How does Christ's example strengthen you for those moments?"
    },
    {
      label: "Justice and mercy reconciled",
      focus: "How can God be both perfectly just and perfectly merciful? Today examines the doctrine that the Atonement satisfies both demands simultaneously.",
      scriptures: [{book:"Alma",ch:42,vs:13,ve:15},{book:"Alma",ch:42,vs:22,ve:25},{book:"D&C",ch:45,vs:3,ve:5}],
      nuances: "In Alma 42:15, the phrase 'mercy claimeth the penitent' introduces a legal metaphor — mercy has a 'claim,' just as justice has a claim. The penitent person stands in a kind of court where both justice and mercy present their cases. The Atonement does not silence justice — it satisfies justice while giving mercy legal standing to intercede. Both are honored; neither is robbed.",
      commentary: "Alma 42 is one of the greatest chapters in the Book of Mormon, a theological discourse delivered by a father to a wayward son. Corianton was troubled by the apparent unfairness of divine punishment. Alma's response is a systematic treatment of justice, mercy, and the Atonement that rivals anything in the history of Christian theology.\n\nThe argument unfolds logically: God established a law. Violation of that law incurs a penalty. If the penalty is not enforced, God ceases to be just — and if God ceases to be just, He ceases to be God. Therefore, justice must be satisfied. But if justice alone governs, all humanity is condemned, because all have sinned. The Atonement resolves this by introducing a mediator — someone who satisfies the demands of justice on behalf of the sinner, thereby freeing mercy to claim the penitent.\n\nThe key insight is that mercy does not override justice — it works through it. Christ paid the price that justice demanded. Having paid it, He can now extend mercy to anyone who repents. The conditions of mercy are repentance and faith — a broken heart and a contrite spirit. These conditions are not arbitrary gatekeeping; they are the mechanism by which a person accepts the gift that has already been offered.\n\nD&C 45:3–5 presents Christ as the advocate with the Father — a legal term. He pleads our case not by arguing that we are innocent (we are not) but by pointing to His own sufferings: 'Father, behold the sufferings and death of him who did no sin, in whom thou wast well pleased.' His merit, not ours, is the basis of the plea.\n\nBroader Christian theology has explored this tension in various ways. Anselm's satisfaction theory, Reformed penal substitution, and Eastern Orthodox theosis all address the justice-mercy question. Restoration scripture offers a distinctively clear articulation through Alma 42, where both principles are honored within a single coherent framework.",
      patterns: "The justice-mercy framework in Alma 42 recapitulates the cosmic conflict described in the premortal council. The adversary proposed a plan that would circumvent agency and justice; Christ proposed a plan that would satisfy justice through sacrifice and preserve agency through mercy. The Atonement is the execution of that plan.",
      reflection: "Is there an area of your life where you struggle more with justice or with mercy — either wanting God to be sterner with others or wanting Him to be gentler with you? How does the Atonement address both impulses?"
    },
    {
      label: "The blood of the covenant",
      focus: "The Atonement is a covenant act, sealed in blood. Today examines the sacrificial and covenantal dimensions through the lens of Hebrews.",
      scriptures: [{book:"Heb",ch:9,vs:11,ve:14},{book:"1 Pet",ch:2,vs:21,ve:24},{book:"Mosiah",ch:3,vs:7,ve:8}],
      nuances: "In Hebrews 9:12, Christ entered the heavenly Holy of Holies 'by his own blood' — the Greek 'dia tou idiou haimatos' uses 'dia' (through/by means of). The preposition is instrumental: His blood was the means of access. In the Mosaic system, the high priest entered the Holy of Holies once a year with the blood of goats and calves. Christ entered the true Holy of Holies — the presence of God — with His own blood, once, and secured eternal redemption.",
      commentary: "The book of Hebrews presents the most sustained argument in the New Testament that Jesus Christ is the ultimate high priest whose sacrifice fulfills and supersedes the entire Mosaic sacrificial system. Hebrews 9:11–14 describes Christ entering not a man-made tabernacle but the heavenly one, offering not the blood of animals but His own blood, and obtaining not temporary cleansing but eternal redemption.\n\nThe sacrificial imagery is not incidental — it is the primary theological framework through which the early Christians understood the Atonement. Every lamb slain at Passover, every goat driven into the wilderness on the Day of Atonement, every burnt offering on the altar was a shadow of the reality that Christ accomplished. The blood was always the point. Leviticus 17:11 established the principle: the life of the flesh is in the blood, and it is the blood that makes atonement for the soul.\n\nPeter's teaching in 1 Peter 2:21–24 adds a moral dimension: Christ bore our sins in His own body on the tree, that we, being dead to sins, should live unto righteousness. By His stripes — the marks of the scourge — we are healed. The Atonement is not only a legal transaction but a transformative power that enables a new kind of life.\n\nMosiah 3:7–8 provides the Book of Mormon's most visceral description of the atoning suffering: blood coming from every pore, so great would be His anguish for the wickedness of His people. The connection between blood and covenant is ancient and deep — from the Abrahamic covenant sealed with blood, to the Passover blood on the doorposts, to the blood of Christ shed for many for the remission of sins.\n\nEvery time the sacrament is administered, this covenantal blood-language is invoked. The bread and water point to the body and blood of the sacrifice. The ordinance is a weekly renewal of the covenant sealed in Christ's blood.",
      patterns: "The blood-covenant pattern runs from Genesis to Revelation and from 1 Nephi to Moroni. Blood seals the covenant with Abraham, with Israel at Sinai, with the early Christians at the Last Supper, and with the Saints at every sacrament table. Christ's blood is the thread connecting all of them.",
      reflection: "When you partake of the sacrament, do you think about the covenantal blood that it represents? How might a deeper awareness of the sacrifice change your experience of that ordinance?"
    },
    {
      label: "Made new through the Atonement",
      focus: "The Atonement does not merely forgive — it transforms. Today examines the power of the Atonement to make fallen people into new creatures.",
      scriptures: [{book:"2 Cor",ch:5,vs:17,ve:21},{book:"Moro",ch:10,vs:32,ve:33},{book:"Gal",ch:2,vs:20,ve:21}],
      nuances: "In 2 Corinthians 5:17, the phrase 'new creature' (kain\u0113 ktisis) uses 'kain\u0113' — new in quality and character, not merely new in time (which would be 'neos'). Paul is describing a qualitative transformation of being, not simply a fresh start. The old things have 'passed away' (par\u0113lthen — gone by, ceased to exist). The language is absolute: the old is gone; everything has become new.",
      commentary: "Paul's declaration that anyone in Christ is a new creature is one of the most hopeful sentences in all of scripture. The Atonement does not merely pardon — it recreates. The alcoholic who comes to Christ is not simply forgiven for drinking; he is changed into someone for whom the desire diminishes and the capacity for a different life expands. The bitter heart that submits to the Savior is not merely excused for its bitterness; it is softened and renewed.\n\nThis transformative power is what distinguishes the Atonement from mere amnesty. A governor can pardon a prisoner and release him. Only Christ can pardon a prisoner and change his nature. The Atonement addresses not just the penalty for sin but the disposition toward sin.\n\nMoroni 10:32–33 frames this transformation as the culmination of the entire Book of Mormon. Come unto Christ, be perfected in Him, deny yourselves of all ungodliness, and love God with all your might, mind, and strength. Then — and only then — is His grace sufficient. His grace sanctifies you, making you holy and without spot. This is not a transaction completed in a single moment; it is a process of becoming, empowered by grace at every step.\n\nPaul's personal testimony in Galatians 2:20 is startling in its intimacy: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me.' Paul is not speaking metaphorically. He is describing an experience of such complete transformation that his old self no longer drives his life. Christ does.\n\nThe doctrine of transformation through the Atonement connects to the Restoration principle of sanctification — the process by which the Holy Ghost purifies and perfects human nature. Baptism by water initiates the covenant; baptism by fire transforms the person. Both are made possible by the Atonement.",
      patterns: "The transformation pattern echoes the Resurrection (Week 12): just as the mortal body is raised in glory, the mortal character is raised in holiness. Death to life, corruption to incorruption, old creature to new creature — the pattern is consistent. The Atonement is resurrection applied to the soul.",
      reflection: "In what area of your life do you most need to be made new? Are you willing to believe that the Atonement has the power to change not just your standing before God but your actual nature?"
    },
    {
      label: "Our response to the Atonement",
      focus: "The Atonement is a gift, but it requires a response. Today examines what Christ asks of us in return for the infinite sacrifice He has made.",
      scriptures: [{book:"Rom",ch:5,vs:6,ve:11},{book:"Jacob",ch:4,vs:11,ve:12},{book:"D&C",ch:19,vs:15,ve:17}],
      nuances: "In Romans 5:8, Paul writes that 'God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.' The Greek 'sunist\u0113sin' (commendeth/demonstrates) is a present tense verb — God's love is not something demonstrated once in the past but continuously demonstrated. The Atonement is an ongoing expression of divine love, not a historical event that fades with time.",
      commentary: "Paul's argument in Romans 5:6–11 establishes a principle that runs counter to human instinct: Christ died for us while we were still sinners. He did not wait for us to clean ourselves up, earn His favor, or prove our worthiness. He came while we were helpless, ungodly, and enemies. The Atonement is not a reward for good behavior — it is a rescue operation for those who cannot save themselves.\n\nThis does not mean the Atonement demands nothing of us. D&C 19:15–17 is as direct as scripture gets: repent, lest you suffer even as Christ suffered. The choice is stark. Either we accept the Atonement through repentance and faith, or we bear the consequences ourselves. The suffering Christ endured was real and terrible, and He offers to spare us from it — but only if we accept the terms of the gift.\n\nJacob 4:11–12 provides the Book of Mormon frame: be reconciled to God through the Atonement of Christ, His Only Begotten Son, that you may obtain a resurrection and be presented as the firstfruits of Christ unto God. The response to the Atonement is reconciliation — a restoration of the relationship with God that sin disrupted.\n\nThe terms of response are consistent across all scripture: faith in Christ, repentance, baptism, receiving the Holy Ghost, and enduring to the end. These are not bureaucratic requirements imposed by an arbitrary God. They are the natural responses of a soul that has grasped the magnitude of the gift. Faith is the response of a mind that recognizes truth. Repentance is the response of a heart that recognizes its need. Baptism is the response of a will that commits to change. Receiving the Holy Ghost is the response of a spirit that opens to divine companionship. Enduring to the end is the response of a life that has found its purpose.\n\nThe Atonement has been accomplished. The price has been paid. The question is not whether Christ has done enough — He has done everything. The question is whether we will receive what He offers.",
      patterns: "The Atonement as gift requiring response is the culmination of Weeks 9 through 13. Christ's mission, betrayal, crucifixion, resurrection, and atonement are His work. Our response — faith, repentance, covenant — is our work. The gospel is a dialogue, not a monologue.",
      reflection: "What is your honest response to the Atonement right now? Is there something you have been holding back from Christ — a sin unconfessed, a sorrow unshared, a commitment unmade? What would it look like to respond fully this week?"
    }
  ]
};

export default week13;
