import type { WeekContent } from '../types';

const week10: WeekContent = {
  title: "Betrayal & Trials — The Darkest Hours Before the Cross",
  subtitle: "In the span of a single night, Jesus was betrayed by a friend, abandoned by His disciples, and condemned by courts that had no authority over Him.",
  weekScriptures: "Matt 26:14–16; Luke 22:1–6; Matt 26:47–50; John 13:21–30; Luke 22:39–46; Matt 26:36–46; Mark 14:32–42; John 18:1–12; Matt 26:57–68; Mark 14:53–65; Luke 22:54–62; John 18:13–27; Matt 27:1–2; Luke 23:1–12; John 18:28–38; Matt 27:15–26; Mark 15:6–15",
  synthesis: {
    summary: "The betrayal, arrest, and trials of Jesus Christ constitute some of the most sobering passages in all of scripture. In a single night, every form of human failure converges on the sinless Son of God: treachery from a trusted disciple, abandonment by friends, false witnesses, corrupt religious proceedings, cowardly political maneuvering, and mob violence. Yet through it all, Christ remained composed, purposeful, and obedient. He was not a victim swept along by events — He was a willing participant in a divinely orchestrated plan, submitting to the very injustice He had the power to prevent.",
    connections: [
      "The mission explored in Week 9 now enters its most costly phase — everything He declared He came to do is tested in these dark hours.",
      "The trials foreshadow the Crucifixion of Week 11 — the legal proceedings that led to the cross were themselves part of the suffering.",
      "Christ's composure under trial models what He later teaches about enduring persecution (see Weeks 32 and 33 on discipleship)."
    ],
    teaching: "What do Christ's responses during His trials teach about how to respond when you are falsely accused, misunderstood, or mistreated? Where is the line between righteous silence and necessary speech?",
    commitment: "This week, when you feel the impulse to react in anger or self-defense, pause and consider how Christ responded under far greater provocation. Choose one moment to respond with deliberate composure."
  },
  days: [
    {
      label: "The price of betrayal",
      focus: "Judas Iscariot agreed to betray Jesus for thirty pieces of silver. Today examines the mechanics and meaning of betrayal from within.",
      scriptures: [{book:"Matt",ch:26,vs:14,ve:16},{book:"Luke",ch:22,vs:1,ve:6},{book:"Alma",ch:39,vs:5,ve:6}],
      nuances: "The thirty pieces of silver (triakonta arguria) in Matthew 26:15 corresponds to the price of a slave in Exodus 21:32 and to the prophetic passage in Zechariah 11:12–13. This was not a random amount — it was a deliberate devaluation. Judas accepted slave-price for the Lord of the universe. Luke adds that Satan 'entered into' Judas (Luke 22:3), using 'eiselthen' — the same word used for demons entering bodies in exorcism accounts.",
      commentary: "The betrayal of Christ by Judas is one of the most analyzed events in scripture and in Western literature. Matthew records the transaction with chilling brevity: Judas went to the chief priests and asked what they would give him. The initiative was his. Luke adds the detail that Satan entered Judas — not as an excuse but as a warning about what happens when a heart opens itself to darkness even while walking in the presence of light.\n\nThe amount — thirty pieces of silver — was prophetically significant. Zechariah had used this exact sum centuries earlier to describe the insulting price placed on the shepherd of Israel. The chief priests were unknowingly fulfilling prophecy while plotting murder.\n\nAlma 39:5–6 does not reference Judas directly, but Alma's warning to his son Corianton about the gravity of sin against knowledge is relevant. Judas had walked with Christ, heard His teachings, witnessed His miracles, and yet chose betrayal. Sin committed in the presence of great light carries a weight proportional to the light that was rejected.\n\nChristian theologians have debated Judas's motives for centuries. Was he greedy? Disillusioned? Trying to force Christ's hand politically? Scripture does not fully explain his motive, which may be the point: betrayal is ultimately irrational. There is no sufficient reason to betray the Son of God.",
      patterns: "Betrayal from within is a recurring scriptural pattern — Cain and Abel, Joseph sold by his brothers, David and Absalom. The deepest wounds often come from those closest to us. Christ experienced this pattern in its most concentrated form.",
      reflection: "Have you ever felt betrayed by someone you trusted? How does knowing that Christ experienced betrayal — from one of His chosen Twelve — shape how you process that pain?"
    },
    {
      label: "The Last Supper and Judas's departure",
      focus: "At the final meal, Jesus identified His betrayer and let him go. Today explores the profound sorrow and deliberate restraint of that moment.",
      scriptures: [{book:"John",ch:13,vs:21,ve:30},{book:"Matt",ch:26,vs:47,ve:50},{book:"Ps",ch:41,vs:9}],
      nuances: "John 13:30 contains one of the most haunting sentences in scripture: 'He then having received the sop went immediately out: and it was night.' The Greek 'nux' (night) functions on two levels — literal darkness and spiritual darkness. Judas walked out of the presence of the Light of the World and into the night. John's narrative artistry here is extraordinary.",
      commentary: "In the upper room, Jesus was troubled in spirit and announced that one of the Twelve would betray Him. The disciples looked at one another, uncertain. John, reclining next to Jesus, asked who it was. Jesus identified the betrayer by dipping bread and handing it to Judas — an act of table fellowship, even in that terrible moment. Then He said, 'What thou doest, do quickly.' The other disciples did not understand. Judas took the bread and went out. And it was night.\n\nThe restraint of Jesus in this scene is remarkable. He knew what Judas was about to do. He could have stopped it with a word. Instead, He let Judas go. The principle of agency — even the agency to commit the greatest of sins — was honored. God does not override human choice, even when that choice leads to the betrayal of His Son.\n\nMatthew 26:47–50 records the completion of the betrayal in the garden. Judas identified Jesus with a kiss — a sign of friendship and respect perverted into a weapon. Jesus responded, 'Friend, wherefore art thou come?' The use of 'friend' (hetaire) is not ironic — it is heartbreaking.\n\nPsalm 41:9, written centuries earlier, anticipated this moment: 'Yea, mine own familiar friend, in whom I trusted, which did eat of my bread, hath lifted up his heel against me.' The table fellowship of the Last Supper and the Psalm converge in Judas's betrayal.",
      patterns: "The 'darkness' motif is significant. Judas departed into night. The arrest happened in a dark garden. The trials occurred before dawn. Spiritually and literally, these events unfold in darkness — making Christ's composure and light all the more striking.",
      reflection: "Jesus allowed Judas to leave. He did not force, restrain, or publicly shame him. What does this teach about how God handles those who are choosing poorly — including when that person might be you?"
    },
    {
      label: "Gethsemane — the agony before the arrest",
      focus: "Before the arrest came the garden. Today we approach Gethsemane — the place where the weight of the world pressed upon the Savior.",
      scriptures: [{book:"Luke",ch:22,vs:39,ve:46},{book:"Matt",ch:26,vs:36,ve:46},{book:"Mark",ch:14,vs:32,ve:42}],
      nuances: "Luke 22:44 describes Jesus's sweat becoming 'like great drops of blood' — the Greek 'h\u014dsei thromboi haimatos' uses a medical term (thromboi, clots). Luke, traditionally identified as a physician, chose precise language. The condition of hematidrosis — sweating blood under extreme stress — is rare but documented in medical literature. Luke records a physiological reality, not merely a metaphor.",
      commentary: "Gethsemane is hallowed ground in Christian theology, and Latter-day Saint understanding of this event carries particular weight. All three Synoptic Gospels record that Jesus went to the garden with Peter, James, and John, asked them to watch and pray, then withdrew to pray alone. He fell on His face and pleaded with the Father: if it is possible, let this cup pass. Yet not my will, but thine be done.\n\nLuke alone records the angel strengthening Him and the sweat like drops of blood. Matthew and Mark record that He returned three times to find His disciples sleeping. The loneliness of this moment is profound — He bore the weight of the world's sin while His closest friends could not stay awake for one hour.\n\nLatter-day Saint theology, informed by D&C 19:16–19 (studied in Week 13), understands Gethsemane as the place where the infinite and eternal suffering of the Atonement began in its fullest measure. The agony was not merely anticipatory — it was the actual bearing of sin, pain, and sickness. Mosiah 3:7, studied in Week 1, described this suffering: blood coming from every pore, so great would be His anguish.\n\nAcross broader Christianity, Gethsemane is understood as the moment of supreme testing where Christ's human will submitted fully to the divine will. The prayer 'not my will but thine' is considered the highest model of prayer and surrender in the Christian tradition.",
      patterns: "The three sleeping disciples in the garden parallel the three who would deny or scatter. Human weakness is universal — and Christ bore the consequences of that weakness alone. This isolation will deepen through the trials and Crucifixion.",
      reflection: "Christ asked His friends to watch with Him and they could not. Is there someone in your life who is suffering and needs you to simply 'watch' with them — to be present, even when you cannot fix their pain?"
    },
    {
      label: "The arrest in the garden",
      focus: "Armed men came to arrest the Prince of Peace. Today examines the arrest itself and Christ's astonishing response to violence.",
      scriptures: [{book:"John",ch:18,vs:1,ve:12},{book:"Luke",ch:22,vs:49,ve:53},{book:"Mosiah",ch:15,vs:5,ve:7}],
      nuances: "In John 18:6, when Jesus said 'I am he' (eg\u014d eimi), the soldiers fell backward to the ground. The Greek 'eg\u014d eimi' without a predicate echoes the divine name revealed to Moses (Exodus 3:14, LXX). John is showing that even in His arrest, Christ's divine identity manifested with power. He was not captured — He submitted.",
      commentary: "John's account of the arrest is the most detailed and theologically rich. When the soldiers and temple officers arrived with torches and weapons, Jesus stepped forward and asked whom they sought. They answered, 'Jesus of Nazareth.' He replied, 'I am he' — and they fell to the ground. This is not a minor detail. John is recording a theophany in the midst of an arrest. The power that upholds the universe was present in that garden, and for one moment it surfaced.\n\nThen Jesus asked again, and allowed Himself to be taken. Peter drew a sword and cut off the ear of the high priest's servant. Luke records that Jesus touched the ear and healed it — His last recorded miracle before the cross, and it was an act of healing directed at someone who had come to arrest Him. The contrast between Peter's violence and Christ's mercy defines the difference between human instinct and divine mission.\n\nLuke 22:53 records Christ's words to the chief priests and captains: 'This is your hour, and the power of darkness.' He acknowledged that darkness had its moment — a permitted season of evil. But darkness having its hour does not mean darkness wins.\n\nMosiah 15:5–7 provides the theological framework. The Son submitted to the Father, even unto death. The will of the Son was swallowed up in the will of the Father. The submission in Gethsemane continues into the arrest. This is not passivity — it is the most active and costly form of obedience imaginable.",
      patterns: "Christ's response to violence with healing is not an isolated incident — it is a principle. He healed those who harmed Him, prayed for those who persecuted Him, and offered salvation to those who crucified Him. This pattern is central to His gospel.",
      reflection: "When someone acts against you, is your first instinct closer to Peter's sword or Christ's healing touch? What would it take to respond to hostility with grace?"
    },
    {
      label: "The Jewish trials",
      focus: "In the hours before dawn, Jesus was brought before Annas, Caiaphas, and the Sanhedrin. Today examines the religious proceedings that condemned the Son of God.",
      scriptures: [{book:"Matt",ch:26,vs:57,ve:68},{book:"Mark",ch:14,vs:53,ve:65},{book:"John",ch:18,vs:13,ve:27}],
      nuances: "In Matthew 26:63, the high priest demands Jesus answer 'by the living God' — the oath formula 'exorkiz\u014d se kata tou theou tou z\u014dntos.' This was a formal adjuration that, under Jewish law, required a response. Jesus had been silent under false testimony, but when placed under oath regarding His identity as the Christ, He answered directly. His silence was strategic; His speech was decisive.",
      commentary: "The Jewish trials of Jesus were fraught with procedural irregularities that ancient and modern scholars have documented extensively. Night trials were prohibited. The verdict of a capital case required a second hearing on a subsequent day. False witnesses were sought but their testimony did not agree. Despite these irregularities, the proceedings moved forward — driven not by justice but by political urgency.\n\nBefore Caiaphas, Jesus endured false testimony in silence. When directly adjured — placed under oath — He declared His identity: He was the Christ, the Son of the Blessed, and they would see the Son of Man sitting at the right hand of power. This was the definitive claim, and the high priest tore his robes and declared it blasphemy. The irony saturates the scene: the high priest — whose role was to intercede between God and Israel — declared God's own testimony to be blasphemy.\n\nJohn records the appearance before Annas first, the former high priest who still wielded considerable power. An officer struck Jesus for His response, and Jesus replied with quiet logic: 'If I have spoken evil, bear witness of the evil; but if well, why smitest thou me?' Even under assault, He appealed to reason and truth.\n\nMark records that they spat on Him, blindfolded Him, struck Him, and mockingly said, 'Prophesy!' The physical abuse was calculated to humiliate. They were taunting His prophetic claims while unknowingly fulfilling Isaiah's prophecy of the suffering servant who would be smitten and spat upon (Isaiah 50:6).",
      patterns: "The pattern of religious leaders rejecting the prophets is one of the oldest in scripture — from the priests who opposed Jeremiah to the Pharisees who sought to kill Jesus. Week 9 noted that Christ came to bear witness of truth; here, the institutions tasked with preserving truth reject it.",
      reflection: "Jesus was condemned by the very people who should have recognized Him. Have you ever felt rejected by a community where you expected to be understood? How did Christ's example shape your response?"
    },
    {
      label: "Peter's denial",
      focus: "While Jesus stood trial inside, Peter stood in the courtyard and denied knowing Him — three times. Today explores the anatomy of a disciple's failure.",
      scriptures: [{book:"Luke",ch:22,vs:54,ve:62},{book:"Mark",ch:14,vs:66,ve:72},{book:"John",ch:18,vs:25,ve:27}],
      nuances: "In Luke 22:61, after the third denial, 'the Lord turned, and looked upon Peter.' The Greek 'eneblepsen' means to gaze intently, to look directly into someone's face. This was not a glance — it was a searching, knowing look. That single look broke Peter. Luke is the only evangelist who records this detail, and it transforms the narrative from a story about failure into a story about being known.",
      commentary: "Peter's denial is one of the most psychologically honest accounts in all of scripture. Just hours earlier, Peter had declared he would die for Christ. Now, confronted by a servant girl, he swore he did not know the man. The contrast between his courage in the garden (drawing a sword against armed soldiers) and his cowardice in the courtyard (lying to a servant) reveals something important about human nature: we often fail not at the dramatic moments but at the mundane ones.\n\nAll four Gospels record the denial, each with slightly different details, but the core is the same: three denials, the rooster crowing, and Peter's devastation. Luke adds the devastating detail that Jesus turned and looked at Peter. Across the courtyard, through the chaos, their eyes met. Peter went out and wept bitterly.\n\nThis is not primarily a story of shame. It is a story of what comes next. Peter wept, but he did not run. He did not follow Judas's path into despair. He stayed. And after the Resurrection, Christ restored him with a threefold question — 'Do you love me?' — matching each denial with an opportunity to reaffirm (John 21:15–17).\n\nThe Restoration perspective adds depth here. Peter would go on to lead the early Church, receive the keys of the kingdom, and eventually give his life for Christ. His denial did not define him. His repentance and subsequent faithfulness did. This is profoundly hopeful for anyone who has failed in a moment of weakness.",
      patterns: "Peter's three denials and Christ's three questions in John 21 form a deliberate literary and theological pair. Failure is met with restoration, not condemnation. This pattern of divine response to human weakness recurs throughout scripture.",
      reflection: "Peter denied Christ under pressure and then wept bitterly. Is there a moment of spiritual failure in your past that you have wept over? Have you allowed Christ to restore you, or are you still carrying the weight of it?"
    },
    {
      label: "Before Pilate and Herod",
      focus: "The Roman trials reveal the intersection of cowardice, politics, and injustice that led to Christ's condemnation. Today examines the men who had the power to release Him and chose not to.",
      scriptures: [{book:"John",ch:18,vs:28,ve:38},{book:"Luke",ch:23,vs:1,ve:12},{book:"Matt",ch:27,vs:15,ve:26}],
      nuances: "In John 18:38, Pilate's famous question 'Ti estin al\u0113theia?' (What is truth?) is one of the most debated lines in the New Testament. The absence of an article before 'al\u0113theia' gives it a philosophical flavor — Pilate is asking about the nature of truth itself, not a specific truth claim. Ironically, he asks this while looking directly at the One who declared, 'I am the way, the truth, and the life' (John 14:6).",
      commentary: "The Roman phase of Christ's trial reveals layers of moral failure. Pilate examined Jesus and found no fault in Him — a verdict he repeated three times (Luke 23:4, 14, 22). Yet he still condemned Him. Pilate's failure was not ignorance but cowardice. He knew Jesus was innocent and sentenced Him anyway because the political cost of releasing Him was too high.\n\nLuke alone records that Pilate sent Jesus to Herod Antipas, who had jurisdiction over Galilee. Herod had long wanted to see Jesus — hoping to witness a miracle, as though the Son of God were a performing magician. Jesus refused to speak to Herod. This silence is striking: Christ answered Caiaphas's adjuration and engaged Pilate's questions but said nothing to Herod. There are moments when silence is the most powerful statement.\n\nThe crowd's choice of Barabbas over Christ is one of the most symbolically loaded moments in the trial narratives. Barabbas — whose name means 'son of the father' — was a convicted insurrectionist. The people chose a counterfeit 'son of the father' over the true Son of the Father. Matthew records Pilate washing his hands, declaring himself innocent of Christ's blood. But no symbolic gesture can absolve a man of the decision he had the authority to prevent.\n\nFrom the perspective of Christian theology, the trial before Pilate illustrates the collision between divine purpose and human agency. God's plan was accomplished through human choices — but those humans remained responsible for their choices. The Atonement was not fate — it was a convergence of divine willingness and human culpability.",
      patterns: "Pilate's failure to act on what he knew to be true echoes every moment when a person recognizes the right path and chooses the convenient one instead. This is not an ancient problem — it is a perpetual one. Christ's mission (Week 9) moved forward through the very injustice that tried to stop it.",
      reflection: "Pilate knew the truth and lacked the courage to act on it. Is there a truth in your life that you have recognized but not yet had the courage to act on? What is the cost of further delay?"
    }
  ]
};

export default week10;
