import type { WeekContent } from '../types';

const week39: WeekContent = {
  title: "Prophecies about — Ancient Witnesses of Christ's Coming",
  subtitle: "Centuries before His birth, prophets on two continents saw, named, and described the Messiah in astonishing detail.",
  weekScriptures: "Isa 11:1-5; Isa 42:1-4; Isa 61:1-3; Jer 23:5-6; Ezek 34:23-24; Zech 13:6; Ps 16:10; Ps 110:1-4; 1 Ne 19:10; 2 Ne 6:9; Hel 8:16-20; Isa 40:3-5; Jer 33:14-16",
  synthesis: {
    summary: "The messianic prophecies of the Old Testament and the Book of Mormon constitute one of the most remarkable bodies of evidence in religious history. Prophets separated by centuries and continents described the same Person — His birthplace, His manner of coming, His suffering, His mission, and His triumph. This convergence is not coincidence. It is the signature of a God who declares the end from the beginning and who prepared the way for His Son across every dispensation.",
    connections: [
      "The prophetic tradition studied this week flows directly into Week 40 (Types in Anticipation), where these verbal prophecies are embodied in rituals and events.",
      "Isaiah's Suffering Servant connects to Week 20 (Atonement) and Week 18 (Trial/Crucifixion), where the prophecies find literal fulfillment.",
      "The prophetic unity across dispensations was introduced in Week 1 (Overview) and finds its fullest expression here."
    ],
    teaching: "If you were explaining to someone unfamiliar with Christianity why these prophecies matter, which two or three would you begin with? What makes them compelling?",
    commitment: "Choose one messianic prophecy from this week and trace its fulfillment in the New Testament. Let the specificity of God's foreknowledge deepen your trust in His plans for your life."
  },
  days: [
    {
      label: "The Protoevangelium — the first prophecy",
      focus: "The very first messianic prophecy appears in Genesis 3. Today we trace the thread from Eden to Bethlehem.",
      scriptures: [{book:"Gen",ch:3,vs:15},{book:"1 Ne",ch:10,vs:4,ve:11},{book:"Rev",ch:12,vs:1,ve:5}],
      nuances: "Genesis 3:15 — 'he shall bruise thy head, and thou shalt bruise his heel' — uses the Hebrew 'shuph,' which can mean crush or strike. The asymmetry is theologically significant: the serpent wounds the heel (a painful but survivable injury — the cross), while the seed of the woman crushes the head (a fatal blow — the ultimate defeat of evil).",
      commentary: "Genesis 3:15 is traditionally called the Protoevangelium — the 'first gospel.' Immediately after the Fall, God pronounces a curse on the serpent and embeds within it a promise: the seed of the woman will crush the serpent's head. This is the first prophecy of Christ in all of scripture, and it appears before any law is given, before any covenant is formally established.\n\nThe significance of this placement cannot be overstated. Before God explains the consequences of the Fall in full, He announces the remedy. The plan of redemption predates the full experience of the Fall. This is not an afterthought — it is the point.\n\nLehi's teaching in 1 Nephi 10:4–11 expands on this: a Messiah would come to redeem mankind, would be baptized, would be slain, and would rise from the dead. Lehi knew these details six hundred years before they occurred. The specificity increases as the centuries unfold, but the core promise never changes.\n\nRevelation 12 recasts the same drama in apocalyptic imagery — the woman, the child, and the dragon. The cosmic conflict between Christ and Satan announced in Eden reverberates through the final book of the Bible. The promise given in a garden finds its consummation in a new heaven and earth.",
      patterns: "The pattern of promise-before-consequence recurs throughout scripture. God always provides the remedy before the full weight of the trial is felt. This is as true in your life as it was in Eden.",
      reflection: "God announced the plan of redemption before Adam and Eve fully experienced the Fall. What does this say about how God handles your failures and mistakes?"
    },
    {
      label: "The birthplace and the birth",
      focus: "Prophets named the time, the place, and the circumstances of Christ's birth centuries before it happened.",
      scriptures: [{book:"Micah",ch:5,vs:2},{book:"Alma",ch:7,vs:10},{book:"Isa",ch:7,vs:14},{book:"Hel",ch:14,vs:1,ve:7}],
      nuances: "Micah 5:2 describes Bethlehem as 'little among the thousands of Judah' — the Hebrew 'tsair' means insignificant or small. The deliberate selection of an obscure village for the birth of the ruler of Israel is a prophetic pattern: God consistently works through the small, the overlooked, and the humble.",
      commentary: "Micah, writing in the eighth century BC, identified Bethlehem as the birthplace of the Messiah. This is one of the most specific and verifiable messianic prophecies in the Old Testament. Seven hundred years later, a Roman census would move Mary and Joseph from Nazareth to Bethlehem at precisely the right moment.\n\nAlma 7:10, written roughly 83 BC, states that the Son of God would be born 'at Jerusalem which is the land of our forefathers.' Critics have noted that Alma says 'at Jerusalem' rather than 'at Bethlehem,' but this is actually evidence of authenticity — Bethlehem is approximately five miles south of Jerusalem and falls within the 'land of Jerusalem' as the term was used in ancient Near Eastern geography. The El-Amarna letters from the fourteenth century BC use 'land of Jerusalem' in exactly this way.\n\nIsaiah 7:14 adds the manner of birth: a virgin shall conceive. The Hebrew 'almah' has been debated for centuries — does it mean virgin or young woman? The Septuagint translators, working two centuries before Christ, chose the Greek 'parthenos,' which unambiguously means virgin. Matthew 1:23 cites this prophecy as fulfilled in Mary.\n\nSamuel the Lamanite in Helaman 14 provides the most dramatic sign: a day and a night and a day with no darkness. This prophecy is unique to the Book of Mormon and was fulfilled as recorded in 3 Nephi 1:15–21. The convergence of prophecies from two hemispheres about a single birth is remarkable.",
      patterns: "The specificity of these birth prophecies — naming the town, the manner of conception, and the accompanying signs — demonstrates that God's plans are precise, not vague. This precision continues in prophecies of Christ's death and resurrection studied later this week.",
      reflection: "God orchestrated centuries of events to fulfill the prophecies of Christ's birth. How does this affect your confidence that He is orchestrating the details of your own life?"
    },
    {
      label: "The Suffering Servant",
      focus: "Isaiah 53 is the most detailed prophecy of Christ's suffering, written seven centuries before the cross. Today we walk through it carefully.",
      scriptures: [{book:"Isa",ch:53,vs:1,ve:12},{book:"Mosiah",ch:14,vs:1,ve:12},{book:"Acts",ch:8,vs:30,ve:35}],
      nuances: "Isaiah 53:3 describes the Servant as 'a man of sorrows, and acquainted with grief.' The Hebrew 'ish makoboth' — 'man of pains' — and 'yedua choli' — 'known of sickness' — suggest not just emotional suffering but physical, embodied anguish. The Servant's suffering is total.",
      commentary: "Isaiah 53 is perhaps the most astonishing chapter in the Old Testament. Written approximately seven hundred years before Christ, it describes a figure who is despised and rejected, who bears our griefs and carries our sorrows, who is wounded for our transgressions and bruised for our iniquities, who is brought as a lamb to the slaughter, who makes his soul an offering for sin, and who sees his seed and prolongs his days afterward.\n\nThe detail is extraordinary. Verse 5 describes substitutionary suffering: 'the chastisement of our peace was upon him; and with his stripes we are healed.' Verse 7 describes His silence before His accusers — fulfilled in Matthew 27:12–14. Verse 9 describes His burial with the rich — fulfilled in Matthew 27:57–60. Verse 12 describes Him being 'numbered with the transgressors' — fulfilled when He was crucified between two thieves.\n\nAbinadi quoted this entire chapter in Mosiah 14 while on trial before King Noah, applying it directly to the coming Messiah. This is one of the earliest recorded Christological readings of Isaiah 53 — predating the New Testament by over a century.\n\nThe Ethiopian eunuch in Acts 8 was reading this very passage when Philip approached him and asked, 'Understandest thou what thou readest?' Philip then began at this scripture and 'preached unto him Jesus.' Isaiah 53 has been the gateway to Christ for countless seekers across two millennia.",
      patterns: "Isaiah 53 forms the prophetic backbone of the Atonement doctrine explored in Week 20. The language of bearing, carrying, and healing through wounds is the vocabulary of redemption that permeates every dispensation.",
      reflection: "Read Isaiah 53 slowly, as if for the first time. Which verse feels most personally directed at your own need for a Savior?"
    },
    {
      label: "The prophesied King and His entry",
      focus: "The Messiah was prophesied to come as both a humble servant and a triumphant king. Today explores this paradox.",
      scriptures: [{book:"Zech",ch:9,vs:9},{book:"Dan",ch:9,vs:25,ve:26},{book:"Isa",ch:9,vs:6,ve:7},{book:"Ps",ch:2,vs:6,ve:8}],
      nuances: "Zechariah 9:9 describes the coming king as 'lowly, and riding upon an ass.' The Hebrew 'ani' means afflicted or humble — the opposite of how ancient kings typically arrived. This verse was fulfilled on Palm Sunday (Matthew 21:4–5) and sets up the central paradox of Christ's ministry: He is the King who comes in humility.",
      commentary: "The messianic prophecies present a paradox that troubled Jewish scholars for centuries: the Messiah was described as both a suffering servant (Isaiah 53) and a triumphant king (Isaiah 9:6–7). How could both be true? Some rabbinical traditions proposed two messiahs — Messiah ben Joseph (who suffers) and Messiah ben David (who reigns). Christianity resolves this through two comings: the first in humility, the second in glory.\n\nZechariah 9:9 captures the humble arrival perfectly — a king riding a donkey, not a war horse. Jesus deliberately fulfilled this prophecy on Palm Sunday, arranging for the donkey in advance. He was not merely arriving in Jerusalem; He was enacting a prophecy known to every literate Jew in the crowd.\n\nDaniel 9:25–26 provides a remarkable timeline: from the decree to rebuild Jerusalem to the coming of 'Messiah the Prince' would be a specific period, after which the Messiah would be 'cut off, but not for himself.' The chronological precision of this prophecy has been analyzed extensively by scholars across centuries.\n\nIsaiah 9:6–7 gives the Messiah's titles: Wonderful, Counselor, the Mighty God, the Everlasting Father, the Prince of Peace. These titles ascribe full divinity to the coming child. Psalm 2 adds the Father's own declaration: 'Thou art my Son; this day have I begotten thee.' The kingly prophecies are not about political power but about divine authority that will ultimately encompass all the earth.",
      patterns: "The tension between Christ's two roles — suffering servant and reigning king — maps onto His two comings. Week 18 (Trial/Crucifixion) explores the first; Week 43 (Second Coming) explores the second. The same prophecies that were partially fulfilled in His mortal ministry await complete fulfillment at His return.",
      reflection: "The Jews expected a conquering king and received a suffering servant. Are there ways you might be looking for God to act in one way when He is actually working in another?"
    },
    {
      label: "Prophecies of His suffering and death",
      focus: "The Psalms contain vivid, specific prophecies of the crucifixion — details known only to eyewitnesses, written a thousand years before the event.",
      scriptures: [{book:"Ps",ch:22,vs:1,ve:18},{book:"Ps",ch:69,vs:20,ve:21},{book:"Zech",ch:12,vs:10},{book:"2 Ne",ch:10,vs:3}],
      nuances: "Psalm 22:16 — 'they pierced my hands and my feet' — is remarkable because crucifixion had not yet been invented when this psalm was written. The Hebrew 'kaari' has been debated (some manuscripts read 'like a lion' rather than 'pierced'), but the Septuagint unambiguously translated it as 'they pierced' centuries before Christ, indicating that ancient Jewish scholars understood the passage this way.",
      commentary: "Psalm 22 reads like an eyewitness account of the crucifixion, yet David composed it roughly a thousand years before Christ. The psalm opens with the very words Jesus cried from the cross: 'My God, my God, why hast thou forsaken me?' It describes the mocking of bystanders (verse 7, fulfilled in Matthew 27:39–43), the piercing of hands and feet (verse 16), and the casting of lots for garments (verse 18, fulfilled in John 19:23–24).\n\nPsalm 69:20–21 adds further detail: 'They gave me also gall for my meat; and in my thirst they gave me vinegar to drink.' This was fulfilled in Matthew 27:34 and 48. The specificity is haunting — these are not vague predictions but precise descriptions of events that would not occur for centuries.\n\nZechariah 12:10 prophesies that Israel will 'look upon me whom they have pierced, and they shall mourn for him.' This prophecy of piercing predates the Roman practice of crucifixion and points forward not only to the cross but to the Second Coming, when all will recognize the wounds in His hands, feet, and side.\n\nJacob's brother Nephi, in 2 Nephi 10:3, provides the Book of Mormon's own prophecy: Christ would be crucified. The word 'crucify' appears explicitly in the Nephite record, given by revelation centuries before the Romans adopted this method of execution. The convergence of witnesses is unmistakable.",
      patterns: "The prophetic details of Christ's death — piercing, vinegar, lots for garments, the cry of desolation — were each recorded by different prophets in different centuries, yet they converge on a single afternoon in Jerusalem. This convergence of independent witnesses is the pattern God uses to establish truth (2 Corinthians 13:1).",
      reflection: "Which prophetic detail of Christ's suffering strikes you most? Why might God have revealed these specifics centuries in advance?"
    },
    {
      label: "Book of Mormon prophecies — a second witness",
      focus: "The Book of Mormon contains some of the most explicit and detailed messianic prophecies ever recorded. Today examines their unique contribution.",
      scriptures: [{book:"2 Ne",ch:25,vs:19,ve:20},{book:"Mosiah",ch:3,vs:5,ve:10},{book:"Alma",ch:7,vs:10,ve:13},{book:"Jacob",ch:4,vs:4,ve:5}],
      nuances: "Nephi in 2 Nephi 25:19 gives the Messiah a name: 'Jesus Christ, the Son of God.' This is the most explicit naming of Christ in pre-Christian prophecy anywhere in scripture. Old Testament prophets used titles (Wonderful, Prince of Peace, Branch); Nephi used His actual name, six hundred years before His birth.",
      commentary: "The Book of Mormon's messianic prophecies are remarkable for their clarity. Where Old Testament prophecies are often poetic, symbolic, and open to interpretation, Book of Mormon prophets speak with directness that leaves little room for ambiguity. Nephi names Him — Jesus Christ. King Benjamin describes His ministry in detail: He will cast out devils, heal the sick, raise the dead, and suffer temptations, pain, hunger, thirst, and fatigue beyond what any mortal can bear.\n\nAlma 7:10–13 adds dimensions not found in any other prophetic text. Not only will Christ suffer for sins, but He will take upon Himself the pains and sicknesses of His people. He will take upon Him death and their infirmities. The purpose is explicitly stated: 'that his bowels may be filled with mercy, according to the flesh, that he may know according to the flesh how to succor his people.' This is empathic atonement — He suffers not only to pay a price but to gain experiential knowledge of human pain.\n\nJacob 4:4–5 makes a sweeping claim: all the prophets who preceded Jacob knew of Christ and worshipped Him. The law of Moses and the temple ordinances all pointed to Christ. This is not a casual observation but a fundamental hermeneutical principle: the entire Nephite religious system was consciously and explicitly Christ-centered from its founding.\n\nThe explicitness of these prophecies is one of the Book of Mormon's most distinctive contributions. It eliminates the ambiguity that allowed some ancient Jewish readers to miss the messianic meaning of their own scriptures.",
      patterns: "The Book of Mormon functions as a 'second witness' (2 Nephi 29:8) that clarifies what the Old Testament taught in types and shadows. This principle of dual witnesses — one from the Eastern Hemisphere, one from the Western — is the evidentiary pattern God established for the latter days.",
      reflection: "The Book of Mormon prophets knew Christ by name centuries before His birth. How does this specificity affect your confidence in the Book of Mormon as scripture?"
    },
    {
      label: "The prophetic mosaic completed",
      focus: "Today we step back and see the full picture: dozens of prophecies from multiple continents and centuries forming a single, coherent portrait of Jesus Christ.",
      scriptures: [{book:"Mal",ch:3,vs:1},{book:"Hosea",ch:11,vs:1},{book:"Deut",ch:18,vs:15,ve:19},{book:"Luke",ch:24,vs:25,ve:27}],
      nuances: "In Luke 24:27, the resurrected Christ on the road to Emmaus 'beginning at Moses and all the prophets, expounded unto them in all the scriptures the things concerning himself.' The Greek 'diermeneuen' means to interpret thoroughly or translate — He was giving them the hermeneutical key to the entire Old Testament: it was all about Him.",
      commentary: "Malachi 3:1 prophesied that a messenger would prepare the way before the Lord, and then 'the Lord, whom ye seek, shall suddenly come to his temple.' John the Baptist fulfilled the first part; Christ's cleansing of the temple fulfilled the second. Hosea 11:1 — 'Out of Egypt have I called my son' — was fulfilled when Joseph brought the child Jesus back from Egypt (Matthew 2:15). Moses prophesied in Deuteronomy 18:15 that God would raise up a prophet 'like unto me' — Peter explicitly identified this prophet as Jesus Christ in Acts 3:22.\n\nEach of these prophecies was given independently, by different prophets, in different centuries, for different immediate audiences. Yet they all converge on a single life, a single mission, and a single Person. The mathematical probability of one individual fulfilling even a fraction of these prophecies by coincidence has been calculated by scholars and found to be astronomically small.\n\nThe most powerful moment in all of prophetic fulfillment may be the scene on the road to Emmaus in Luke 24. Two disciples are walking, grief-stricken, when the risen Christ joins them — unrecognized. He asks why they are sad. They tell Him about Jesus of Nazareth. And then He opens the scriptures: beginning at Moses, He walks them through every prophecy, showing how all of it pointed to exactly what had just happened. Their hearts burned within them.\n\nThis is the invitation for our day as well. The prophecies are not academic curiosities — they are the testimony of God, given across millennia, that Jesus is the Christ. To study them is to walk the road to Emmaus and let the scriptures set your heart on fire.",
      patterns: "The Emmaus road experience — scriptures being opened, hearts burning, Christ revealed — is the pattern for all scripture study. Every week of this plan is an invitation to the same experience: seeing Christ in the text and feeling your heart confirm the truth.",
      reflection: "If Christ walked beside you today and opened the scriptures to show you everything written about Himself, what would you most want to understand?"
    }
  ]
};

export default week39;
