import type { WeekContent } from '../types';

const week05: WeekContent = {
  title: "Appearances, Antemortal — Before He Came in the Flesh",
  subtitle: "Christ appeared to prophets long before Bethlehem, revealing Himself across the centuries to those who sought Him.",
  weekScriptures: "Judg 13:21-22; 1 Kgs 19:11-13; Ezek 1:26-28; Dan 7:9-14; Num 12:6-8; Acts 7:55-56; 3 Ne 11:8-12; D&C 76:19-24; D&C 110:1-4; Mosiah 27:8-16; Rev 1:12-18; Alma 19:12-13",
  synthesis: {
    summary: "Before Christ was born in Bethlehem, He appeared to prophets across multiple dispensations. These antemortal appearances — sometimes called theophanies or Christophanies — demonstrate that the God of the Old Testament was the premortal Jehovah, the same being who would later take on flesh. They reveal a God who does not remain hidden but actively seeks to be known by His covenant people.",
    connections: [
      "These antemortal appearances confirm Week 1's principle that every prophet testified of Christ — many of them did so because they had seen Him personally.",
      "The identity of Christ as Jehovah (Week 8) is inseparable from these appearances: the God who spoke to Moses and Abraham is the same being who was born in Bethlehem.",
      "Christ's willingness to appear to mortals before His birth foreshadows the Incarnation itself (Week 1, Day 2) — the pattern of God descending to reach His people."
    ],
    teaching: "Why do you think Christ chose to appear to prophets before His mortal birth? What purposes did these appearances serve for the individuals and for the broader covenant community?",
    commitment: "As you study this week, consider how God has made Himself known to you personally. Record one experience where you felt the Lord was not distant but near."
  },
  days: [
    {
      label: "The brother of Jared sees Him",
      focus: "The most detailed antemortal appearance in scripture: the brother of Jared sees the Lord's finger, then His entire spirit body. Today examines what this encounter reveals about Christ's premortal nature.",
      scriptures: [{book:"Ether",ch:3,vs:6,ve:16},{book:"Ether",ch:3,vs:17,ve:20},{book:"2 Ne",ch:11,vs:2,ve:3}],
      nuances: "In Ether 3:15, the Lord tells the brother of Jared that He has been 'prepared from the foundation of the world to redeem my people.' The phrase 'prepared from the foundation' mirrors language in Revelation 13:8 about the 'Lamb slain from the foundation of the world.' Both point to the Atonement as an event planned before mortality, not an afterthought.",
      commentary: "Ether 3 is one of the most theologically rich chapters in all scripture. When the brother of Jared comes before the Lord with sixteen small stones, asking that they be touched to give light, he does not expect to see a finger. Yet his faith is so extraordinary that the veil is pulled aside, and he sees the Lord's spirit body — a body that looks exactly like the mortal body Christ would later take upon Himself.\n\nThis passage teaches something profound: the premortal Christ already had a spirit body in the form of a man. Verse 15 makes this explicit — this is the body in which He would appear to His people in the flesh. The spirit body was not vague or ethereal but concrete and recognizable. This has significant theological implications: the human form is not an accident of evolution but a reflection of divine design.\n\nNephi, in 2 Nephi 11:2–3, testifies that he too saw the Redeemer, as did his father Lehi and the prophet Isaiah. Three witnesses in three lines — Nephi is establishing that antemortal visions of Christ were not rare or isolated events but a pattern of prophetic experience. The Restoration makes explicit what is implicit in the biblical tradition: God has always been willing to show Himself to those who seek Him with sufficient faith.",
      patterns: "The brother of Jared's experience establishes a pattern repeated throughout scripture: extraordinary faith leads to direct encounters with God. This pattern appears again with Moses (later this week), with Nephi, and with Joseph Smith (Week 1, Day 7). Faith is the precondition for theophany.",
      reflection: "The brother of Jared saw the Lord because he 'could not be kept from within the veil.' What would it mean for your faith to press forward with that kind of intensity?"
    },
    {
      label: "Jacob wrestles with God",
      focus: "In one of the most mysterious episodes in Genesis, Jacob wrestles through the night with a divine being and receives a new name. Today explores this encounter as a Christophany.",
      scriptures: [{book:"Gen",ch:32,vs:24,ve:30},{book:"Hosea",ch:12,vs:3,ve:4},{book:"Enos",ch:1,vs:1,ve:8}],
      nuances: "The name 'Peniel' (Gen 32:30) means 'face of God' in Hebrew. Jacob names the place this because, as he says, 'I have seen God face to face, and my life is preserved.' The Hebrew 'panim el panim' is the same phrase used of Moses in Exodus 33:11 and Deuteronomy 34:10. The text treats this as a literal encounter with deity, not a dream or metaphor.",
      commentary: "Genesis 32 is among the most enigmatic passages in scripture. Jacob, on the eve of his reunion with Esau, is left alone in the night and wrestles with a 'man' until dawn. Yet this is no ordinary man — the being renames Jacob 'Israel' (meaning 'one who prevails with God') and Jacob declares he has seen God face to face. Hosea 12:3–4 clarifies that Jacob wrestled 'with the angel, and prevailed,' identifying the divine visitor.\n\nEarly Christian interpreters, including Justin Martyr and Clement of Alexandria, identified this figure as the premortal Christ — the same Lord who later appeared to Moses and Isaiah. This reading aligns with Latter-day Saint theology: since no one can see the Father without the mediation of the Son (John 1:18, D&C 67:11), Old Testament theophanies are understood as appearances of Jehovah — the premortal Jesus Christ.\n\nEnos provides a Book of Mormon parallel. Like Jacob, Enos wrestles — not physically but spiritually — pouring out his soul to God in mighty prayer. And like Jacob, Enos receives a divine assurance: his sins are forgiven, and his faith has made him whole. The pattern is the same across dispensations: wrestling with God leads to transformation and covenant blessing.",
      patterns: "The wrestling motif connects to the broader theme of covenant encounter: you cannot be changed by God from a distance. Jacob's physical struggle, Enos's spiritual struggle, and the brother of Jared's act of faith (yesterday) all involve personal exertion that brings one face to face with divinity. This theme returns in Week 21 (Taking upon the name of Christ).",
      reflection: "What does it mean to 'wrestle' with God in your own spiritual life? Is there something you need to bring before Him with that kind of honest intensity?"
    },
    {
      label: "Moses at the burning bush",
      focus: "God reveals His name and nature to Moses from a bush that burns without being consumed. Today examines one of the most foundational theophanies in all of scripture.",
      scriptures: [{book:"Ex",ch:3,vs:1,ve:14},{book:"Moses",ch:1,vs:1,ve:6},{book:"Abr",ch:3,vs:22,ve:28}],
      nuances: "The divine name 'I AM THAT I AM' (Hebrew 'ehyeh asher ehyeh') is notoriously difficult to translate. It could mean 'I am who I am,' 'I will be what I will be,' or even 'I cause to be what is.' The name resists neat categorization — it is a statement of self-existence and sovereignty. In John 8:58, Jesus applies this name to Himself: 'Before Abraham was, I am.' The connection is not accidental.",
      commentary: "Exodus 3 marks a turning point in salvation history. God calls Moses by name from within a bush that burns but is not consumed — a symbol of divine presence that is powerful but does not destroy the ordinary thing it inhabits. When Moses asks for God's name, the answer is 'I AM THAT I AM,' a declaration of eternal, self-existent being.\n\nMoses 1:1–6, restored through the Prophet Joseph Smith, provides additional context for this encounter. There God tells Moses that He is 'the Lord God Almighty' and that Moses is 'in the similitude of mine Only Begotten.' This language is explicitly Christological: Moses is being taught not merely about an abstract deity but about the relationship between the Father and the Son.\n\nAbraham 3:22–28 extends the picture further back, revealing the premortal council where Christ — described as 'one among them that was like unto God' — volunteered to be the Redeemer. The God who speaks to Moses at the bush is the same being who stood in the premortal council and said, 'Here am I, send me.' His willingness to descend begins before the foundation of the world.",
      patterns: "The burning bush theophany connects to Week 8 (Jehovah): the God who reveals the name 'I AM' is the premortal Christ. It also connects to Week 6 (Creator): the God who made the heavens and the earth is the same God who calls a shepherd in Midian to deliver His people. The divine name 'I AM' will echo through Christ's own ministry in John 8.",
      reflection: "God called Moses by name from the bush. How have you experienced the Lord knowing you personally — calling you by name in your own circumstances?"
    },
    {
      label: "Moses sees God face to face",
      focus: "Moses asks to see God's glory and is shown as much as mortal flesh can bear. Today examines the tension between God's desire to reveal Himself and the limits of mortal capacity.",
      scriptures: [{book:"Ex",ch:33,vs:11},{book:"Ex",ch:33,vs:20,ve:23},{book:"Moses",ch:1,vs:1,ve:2},{book:"D&C",ch:67,vs:10,ve:12}],
      nuances: "Exodus 33 contains an apparent contradiction: verse 11 says God spoke to Moses 'face to face, as a man speaketh unto his friend,' while verse 20 says 'Thou canst not see my face: for there shall no man see me, and live.' Latter-day revelation resolves this: Moses 1:11 explains that Moses was 'transfigured before Him' during the encounter. Without being quickened by the Spirit, mortal flesh cannot endure God's presence.",
      commentary: "Exodus 33 presents one of the most intimate divine-human encounters in scripture. Moses speaks with God face to face — the language of friendship, not terror. Yet when Moses asks to see the fullness of God's glory, the Lord says no mortal can see His face and live. God places Moses in a cleft of rock and covers him with His hand, allowing Moses to see His 'back parts' as He passes by.\n\nMoses 1:1–2 from the Pearl of Great Price fills in what the biblical text leaves ambiguous: Moses was caught up to a high mountain, transfigured by the Spirit, and saw God face to face. The transfiguration is the key — mortal bodies must be temporarily changed to endure divine glory. This same principle appears in D&C 67:11–12, where the Lord promises that those who are purified will see His face.\n\nThe theological tension here is important: God wants to be known, but His glory is so overwhelming that special preparation is required. This is not about God hiding Himself but about the gap between infinite holiness and finite mortality. The entire plan of salvation — including the Atonement, resurrection, and exaltation — can be understood as God's program for closing that gap permanently.",
      patterns: "The concept of being 'transfigured' to see God appears repeatedly: Moses here, the three Nephites in 3 Nephi 28, the Mount of Transfiguration in Matthew 17, and Joseph Smith in the First Vision. It connects to Week 42 (Appearances after resurrection) where the risen Christ appears in glorified form.",
      reflection: "What spiritual preparation might be needed in your own life to draw closer to God's presence? What 'cleft in the rock' is He offering you right now?"
    },
    {
      label: "Isaiah's throne-room vision",
      focus: "Isaiah sees the Lord sitting upon a throne, high and lifted up, surrounded by seraphim. Today explores the prophetic call that comes through direct encounter with the divine.",
      scriptures: [{book:"Isa",ch:6,vs:1,ve:5},{book:"John",ch:12,vs:40,ve:41},{book:"2 Ne",ch:16,vs:1,ve:5}],
      nuances: "John 12:41, commenting on Isaiah's vision, states plainly: 'These things said Esaias, when he saw his glory, and spake of him' — referring to Christ. The apostle John identifies the Lord whom Isaiah saw on the throne as Jesus Christ. This is one of the clearest New Testament statements that Old Testament theophanies were encounters with the premortal Son.",
      commentary: "Isaiah 6 records the prophet's vision of the Lord in the temple, sitting on a throne so elevated that even the train of His robe fills the entire sanctuary. Seraphim surround Him, calling out 'Holy, holy, holy.' Isaiah's immediate response is terror: 'Woe is me! for I am undone; because I am a man of unclean lips.' The gap between divine holiness and human sinfulness is felt viscerally.\n\nJohn 12:41 makes a remarkable interpretive claim: the Lord whom Isaiah saw was Christ. This identification was standard in early Christian theology — the premortal Jesus is the God of Israel's throne-room visions. 2 Nephi 16 reproduces Isaiah's account, placing it within a Book of Mormon context and confirming its importance for Nephite theology.\n\nWhat follows Isaiah's vision is equally significant: a seraph touches a burning coal to his lips, cleansing him of sin, and God asks, 'Whom shall I send?' Isaiah responds, 'Here am I; send me.' The pattern is encounter, purification, and commission. Seeing God does not leave a person unchanged — it transforms and sends them. This same sequence appears in the brother of Jared's experience, in Moses's call, and in Joseph Smith's First Vision.",
      patterns: "The throne-room vision connects to Week 8 (Jehovah): the God on Isaiah's throne is Jehovah, the premortal Christ. The seraph's cleansing coal anticipates the Atonement — purification that makes it possible to stand in God's presence and serve. The commission 'Whom shall I send?' echoes Abraham 3:27 (Week 7) where Christ Himself said, 'Here am I, send me.'",
      reflection: "Isaiah saw God and was immediately aware of his own unworthiness. How does encountering the holiness of Christ make you more aware of your need for His grace?"
    },
    {
      label: "Visions among Book of Mormon prophets",
      focus: "Lehi, Nephi, Alma, and the Lamanite converts each encountered the divine in powerful ways. Today surveys antemortal appearances unique to the Book of Mormon.",
      scriptures: [{book:"1 Ne",ch:1,vs:8,ve:10},{book:"Alma",ch:36,vs:17,ve:22},{book:"Hel",ch:5,vs:36,ve:43}],
      nuances: "In 1 Nephi 1:8, Lehi sees God 'sitting upon his throne, surrounded with numberless concourses of angels.' The Hebrew literary tradition of the 'divine council' (sod Yahweh) is echoed here — God surrounded by His heavenly court. This places Lehi squarely within the prophetic tradition of Isaiah, Ezekiel, and Micaiah (1 Kings 22), all of whom saw God enthroned among heavenly beings.",
      commentary: "The Book of Mormon provides multiple accounts of prophets encountering the premortal Christ. Lehi opens 1 Nephi with a vision of God on His throne — an experience that parallels Isaiah 6 and Ezekiel 1. Lehi sees 'One descending out of the midst of heaven,' whose brightness exceeds the sun, followed by twelve others. This is widely understood as a vision of the premortal Christ and His apostles.\n\nAlma's experience in Alma 36 is different in character — it begins not with worship but with agony. Racked with torment for his sins, Alma cries out to Jesus Christ for mercy, and immediately his pain gives way to exquisite joy. He sees God on His throne, surrounded by angels, and longs to be there. This is a conversion theophany: the encounter with Christ that transforms a rebel into a witness.\n\nHelaman 5 records perhaps the most unusual theophany in the Book of Mormon. Three hundred Lamanite converts, imprisoned with Nephi and Lehi, are surrounded by darkness and fire. A voice speaks through the darkness — not a voice of thunder but 'a still voice of perfect mildness.' They look up and see Nephi and Lehi conversing with angels, their faces shining. The divine presence here is communal, not individual — an entire group is brought into God's presence together.",
      patterns: "These Book of Mormon theophanies parallel biblical patterns while adding distinctly Restoration elements. The communal experience in Helaman 5 anticipates 3 Nephi 11 (Week 42) where the entire Nephite multitude sees and touches the risen Christ. The individual-to-communal progression is itself a pattern: God reveals Himself to prophets, who then bring entire communities into covenant relationship.",
      reflection: "Alma's encounter with Christ came in his darkest moment. Have you experienced the Lord drawing near to you during a time of struggle or sorrow rather than only in times of peace?"
    },
    {
      label: "The pattern of divine appearance",
      focus: "Drawing the week together: what do all these antemortal appearances have in common? Today identifies the recurring elements that characterize how God makes Himself known.",
      scriptures: [{book:"Moses",ch:1,vs:1,ve:6},{book:"JS-H",ch:1,vs:16,ve:17},{book:"D&C",ch:93,vs:1},{book:"Jacob",ch:2,vs:4}],
      nuances: "D&C 93:1 contains a sweeping promise: 'Every soul who forsaketh his sins and cometh unto me, and calleth on my name, and obeyeth my voice, and keepeth my commandments, shall see my face and know that I am.' The verb 'shall' (Greek-equivalent future indicative) is a promise, not a possibility. The conditions are moral and spiritual, not circumstantial.",
      commentary: "As we conclude this week, it is worth stepping back to observe the patterns that unite these antemortal appearances. In every case — the brother of Jared, Jacob, Moses, Isaiah, Lehi, Alma, the Lamanite converts, and Joseph Smith — certain elements recur. There is seeking (often accompanied by struggle or sacrifice), divine initiative (God chooses to reveal Himself), transformation (the person is changed by the encounter), and commission (the person is sent to serve).\n\nMoses 1:1–6 captures all four elements in a few verses: Moses is called up to the mountain, God speaks to him face to face, Moses learns his identity as a son of God, and he is given a work to do. Joseph Smith's First Vision in JS—H 1:16–17 follows the same pattern: a boy enters the grove seeking truth, God appears, Joseph's understanding is transformed, and a prophetic mission begins.\n\nD&C 93:1 universalizes the promise. Seeing the face of God is not reserved for prophets alone but is held out to every soul who meets the conditions of repentance, obedience, and faith. Jacob 2:4 similarly speaks of God's willingness to 'console' His people through revelation. The trajectory of the entire gospel is to bring every person into the kind of direct relationship with Christ that the prophets experienced.\n\nThis has profound implications: the theophanies studied this week are not anomalies but prototypes. They show what God wants for every covenant disciple — not just knowledge about Him but knowledge of Him, face to face.",
      patterns: "This week's theme of divine appearance connects backward to Week 1 (personal witness of Christ), forward to Week 8 (Jehovah, the God who appeared), and ultimately to Week 42 (post-resurrection appearances). The entire 50-week plan traces the arc of a God who refuses to remain unknown.",
      reflection: "D&C 93:1 promises that every faithful soul shall see God's face. What would it mean for your daily discipleship to take that promise seriously — not as metaphor but as the ultimate trajectory of your covenant life?"
    }
  ]
};

export default week05;
