import type { WeekContent } from '../types';

const week15: WeekContent = {
  title: "Deliverer — Set Free by Christ",
  subtitle: "Christ does not merely forgive sin; He breaks every chain that holds us captive — sin, death, fear, and spiritual bondage.",
  weekScriptures: "Rom 11:26–27; 2 Sam 22:2–4; Ps 18:2; Ps 40:1–3; Isa 61:1–3; Luke 4:16–21; Col 1:13–14; Rom 6:16–18; 1 Cor 15:55–57; 2 Ne 9:10–13; Mosiah 27:24–29; Alma 36:17–21; 3 Ne 9:13–14; D&C 128:22; D&C 138:18–19; Heb 2:14–15; Matt 11:28–30; John 8:31–36; 2 Tim 1:10; Ex 14:13–14",
  synthesis: {
    summary: "While Week 14 focused on the price Christ paid, this week focuses on the lived experience of being delivered. Deliverance is what redemption feels like. It is the chains falling off, the prison doors opening, the darkness giving way to light. Scripture records this experience across every dispensation — from Israel at the Red Sea to Alma in the depths of despair to Joseph Smith in Liberty Jail. The Deliverer breaks every kind of bondage: the bondage of sin, the bondage of death, the bondage of fear, and the bondage of spiritual ignorance.",
    connections: [
      "Deliverance is the experiential side of redemption (Week 14) — what it feels like when the Redeemer's price is applied to your life.",
      "Christ's power to deliver (this week) flows from the power of Christ (Week 16) — the same power that governs the cosmos also breaks personal chains.",
      "The deliverance from death explored here connects forward to Week 36 (Resurrection) and the final victory over the grave."
    ],
    teaching: "What is the difference between being forgiven and being delivered? Can you think of a time when Christ not only forgave you but actually freed you from a pattern, a fear, or a burden?",
    commitment: "Is there a form of bondage — a habit, a fear, a resentment, a false belief — that you have been trying to break on your own? This week, bring it to Christ and ask Him to deliver you."
  },
  days: [
    {
      label: "The Deliverer shall come",
      focus: "The promise of a Deliverer runs through the Old Testament like a golden thread. Today traces that promise from David to Paul.",
      scriptures: [{book:"Rom",ch:11,vs:26,ve:27},{book:"2 Sam",ch:22,vs:2,ve:4},{book:"Ps",ch:18,vs:2}],
      nuances: "David's declaration in 2 Samuel 22:2 uses a cascade of metaphors: rock, fortress, deliverer, shield, horn of salvation, high tower, refuge, savior. The Hebrew 'mephalti' (my deliverer) comes from 'palat,' meaning to escape, to slip away from danger. It connotes a narrow rescue — being snatched from the jaws of death. David is speaking from battlefield experience but pointing toward a greater deliverance.",
      commentary: "Paul quotes Isaiah in Romans 11:26-27 to declare that 'there shall come out of Sion the Deliverer, and shall turn away ungodliness from Jacob.' This is both a retrospective claim (Christ has come) and a prophetic one (He will come again). The Deliverer's work spans both advents.\n\nDavid's song in 2 Samuel 22 is one of the most intensely personal passages in the Old Testament. Written near the end of his life, it reviews decades of divine rescue — from Saul's spear, from battlefield enemies, from his own failures. Every metaphor describes a different aspect of God's delivering power: a rock that cannot be moved, a fortress that cannot be breached, a shield that absorbs the blow.\n\nPsalm 18:2 echoes the same language, confirming that this was not a one-time reflection but a lifelong conviction. David knew God as Deliverer not because he had read it in a text but because he had lived it. This experiential knowledge is what transforms theology into testimony.\n\nFor Latter-day Saints, these Old Testament passages gain additional meaning through the understanding that the Jehovah David worshipped is the premortal Jesus Christ. David's Deliverer is the same being who would later be born in Bethlehem, suffer in Gethsemane, and rise from the tomb.",
      patterns: "The pattern of divine deliverance in the Old Testament — from Egypt, from Babylon, from enemies — is always both literal and typological. Each historical rescue points forward to the ultimate deliverance from sin and death that Christ would accomplish.",
      reflection: "David called God his 'rock, fortress, and deliverer' based on lived experience. What would your personal list of metaphors for Christ's delivering power include?"
    },
    {
      label: "Deliverance proclaimed",
      focus: "Jesus opened His public ministry by declaring Himself the fulfillment of Isaiah's prophecy of deliverance. Today examines that bold declaration and its implications.",
      scriptures: [{book:"Isa",ch:61,vs:1,ve:3},{book:"Luke",ch:4,vs:16,ve:21},{book:"Matt",ch:11,vs:28,ve:30}],
      nuances: "When Jesus read from Isaiah 61 in the Nazareth synagogue and then declared 'This day is this scripture fulfilled in your ears' (Luke 4:21), the Greek 'peplerōtai' (fulfilled) is in the perfect tense — indicating a completed action with present and continuing results. He was not saying 'I will fulfill this someday' but 'This is accomplished right now, in your hearing.' The deliverance had already begun.",
      commentary: "Isaiah 61:1-3 is a manifesto of deliverance. The anointed one is sent to bind up the brokenhearted, proclaim liberty to captives, open prisons, comfort mourners, and give beauty for ashes. Every phrase describes a different dimension of human suffering — and for each, the Deliverer has a specific remedy. Brokenness receives binding. Captivity receives liberty. Mourning receives comfort. Ashes become beauty.\n\nLuke 4:16-21 records the moment Jesus applied this manifesto to Himself. In His hometown synagogue, surrounded by people who knew Him as Joseph's son, He claimed to be the fulfillment of seven centuries of prophetic hope. The audience's initial reaction was wonder — and then rage. They tried to throw Him off a cliff. Deliverance, it turns out, is threatening to those who prefer the status quo.\n\nMatthew 11:28-30 adds the gentle personal invitation: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.' The Deliverer does not shout commands from a distance. He invites. He promises rest — not freedom from all difficulty, but a yoke that is easy and a burden that is light. The image is of shared labor: Christ walks beside you in the yoke, bearing the greater weight.",
      patterns: "Jesus' pattern of fulfilling Old Testament prophecy in specific, public ways is a recurring theme in the Gospels. He does not simply teach about deliverance — He enacts it, declares it, and embodies it. This connects to Weeks 39-41 (Prophecies about and Types of Christ).",
      reflection: "Isaiah lists specific kinds of brokenness that the Deliverer heals. Which phrase from Isaiah 61 speaks most directly to where you are right now?"
    },
    {
      label: "Delivered from the dominion of sin",
      focus: "Sin is not just an action but a master. Today explores Christ's power to free us from sin's dominion — not just forgive its consequences but break its hold.",
      scriptures: [{book:"Col",ch:1,vs:13,ve:14},{book:"Rom",ch:6,vs:16,ve:18},{book:"John",ch:8,vs:31,ve:36}],
      nuances: "Paul's language in Colossians 1:13 is dramatic: God 'hath delivered us from the power of darkness, and hath translated us into the kingdom of his dear Son.' The Greek 'exousia tou skotous' (power/authority of darkness) describes an organized realm with governing authority. Deliverance is not a minor adjustment but a transfer of citizenship — from one kingdom to another entirely.",
      commentary: "Colossians 1:13-14 describes deliverance as a regime change. Before Christ, we were under the authority of darkness — not just occasionally sinning but living within a system governed by sin. Christ does not merely improve conditions within that old kingdom; He extracts us from it entirely and transplants us into a new one. This is more radical than most people realize.\n\nPaul's argument in Romans 6:16-18 adds the psychological dimension. Sin is a master, and obedience to it produces servitude. But Christ breaks that servitude: 'Being then made free from sin, ye became the servants of righteousness.' Freedom from sin does not mean freedom from all service — it means a change of masters. You move from compulsory service to willing devotion.\n\nJesus Himself makes the decisive statement in John 8:34-36: 'Whosoever committeth sin is the servant of sin.' And then: 'If the Son therefore shall make you free, ye shall be free indeed.' The word 'indeed' (Greek 'ontōs') means truly, in reality. There are many false freedoms — licentiousness that calls itself liberty, indulgence that masquerades as autonomy. Christ offers the real thing: freedom from the compulsive power of sin itself.",
      patterns: "The 'kingdom transfer' pattern in Colossians echoes Israel's exodus from Egypt — a move from slavery to freedom, from Pharaoh's kingdom to God's. This pattern recurs in every conversion story in scripture, including Alma's (studied later this week).",
      reflection: "Is there an area of your life where sin has felt more like a master than a mistake — where you feel trapped rather than merely imperfect? How might Christ's power to 'transfer kingdoms' apply to that situation?"
    },
    {
      label: "Victory over death",
      focus: "The ultimate bondage is death. Today explores Christ's decisive victory over both physical and spiritual death.",
      scriptures: [{book:"1 Cor",ch:15,vs:55,ve:57},{book:"2 Ne",ch:9,vs:10,ve:13},{book:"Heb",ch:2,vs:14,ve:15}],
      nuances: "Paul's taunt in 1 Corinthians 15:55 — 'O death, where is thy sting? O grave, where is thy victory?' — echoes Hosea 13:14. The Greek 'kentron' (sting) was used for the stinger of a scorpion or the goad used to drive oxen. Paul personifies death as a creature that once had the power to sting and terrify but has now been rendered impotent. The sting is still there in form — we still die — but its poison has been neutralized by the resurrection.",
      commentary: "Paul's triumphant declaration in 1 Corinthians 15 is the crescendo of the longest sustained argument about resurrection in the New Testament. After establishing the historical reality of Christ's resurrection, the theological necessity of resurrection, and the nature of resurrected bodies, Paul arrives at the climax: death has lost. The final enemy is destroyed. The victory is given to us 'through our Lord Jesus Christ.'\n\nJacob's teaching in 2 Nephi 9:10-13 provides the most explicit Book of Mormon commentary on Christ's double deliverance — from physical death through resurrection and from spiritual death through the Atonement. Jacob calls death and hell a 'monster' and describes the deliverance in vivid terms: the grave delivers up the body, and hell (the spirit prison) delivers up the captive spirits. This is not gentle metaphor but confrontational language — Christ storms the gates of death and takes back what was stolen.\n\nHebrews 2:14-15 adds a remarkable dimension: Christ took on flesh and blood specifically so that 'through death he might destroy him that had the power of death, that is, the devil; and deliver them who through fear of death were all their lifetime subject to bondage.' Fear of death is itself a form of bondage, and Christ's resurrection delivers us from that fear. You need not live in terror of the grave when you know someone who has already walked out of it.",
      patterns: "The victory over death is foreshadowed in every scriptural story of rescue from physical danger — Daniel in the lions' den, the three Hebrews in the furnace, Nephi and Lehi in the prison surrounded by fire. Each prefigures the ultimate rescue from the ultimate threat.",
      reflection: "Hebrews says many people live 'all their lifetime subject to bondage' through fear of death. How has Christ's resurrection changed your relationship with mortality and its limitations?"
    },
    {
      label: "Personal deliverance — Alma's story",
      focus: "Doctrine becomes real in personal experience. Today studies the most detailed conversion account in scripture — Alma the Younger's deliverance from spiritual bondage.",
      scriptures: [{book:"Mosiah",ch:27,vs:24,ve:29},{book:"Alma",ch:36,vs:17,ve:21},{book:"3 Ne",ch:9,vs:13,ve:14}],
      nuances: "Alma's phrase in Alma 36:18, 'O Jesus, thou Son of God, have mercy on me,' is striking in its simplicity. After three days of suffering described as 'the very pains of a damned soul,' the turning point is not a complex theological formulation but a desperate, one-sentence plea. The Greek and Hebrew traditions of prayer both recognize this pattern — the cry of extremity is brief because the sufferer has no energy for elaboration. What matters is the name invoked: Jesus.",
      commentary: "Mosiah 27:24-29 records King Mosiah's account of Alma's transformation. The language is vivid: Alma was 'in the darkest abyss' and is now 'born of the Spirit.' He was 'racked with eternal torment' and his soul was 'redeemed from the gall of bitterness and bonds of iniquity.' Every phrase is a deliverance metaphor — abyss to light, torment to peace, bitterness to sweetness, bondage to freedom.\n\nAlma 36:17-21, Alma's own retelling years later to his son Helaman, adds the interior experience. He describes remembering his father's teaching about Christ, crying out for mercy, and then — in a single moment — having his pain replaced with 'exquisite and sweet' joy. The contrast is total: 'there could be nothing so exquisite and so bitter as were my pains... there can be nothing so exquisite and sweet as was my joy.' Deliverance is not gradual improvement; it is transformation.\n\n3 Nephi 9:13-14 provides the Savior's own invitation, spoken to the Nephites after the destruction that preceded His appearance: 'Will ye not now return unto me, and repent of your sins, and be converted, that I may heal you?' The Deliverer does not force deliverance. He invites. He asks. He waits. The door is open, but you must walk through it.",
      patterns: "Alma's conversion follows the same pattern as Paul's (Acts 9) — both were actively opposing Christ, both were struck down, both experienced a period of darkness, and both emerged as powerful witnesses. The pattern suggests that no one is beyond the Deliverer's reach.",
      reflection: "Alma's deliverance came in a single moment of crying out to Christ. Is there a burden you have been carrying that you could bring to Him in simple, honest prayer today?"
    },
    {
      label: "Deliverance beyond the veil",
      focus: "Christ's delivering power extends beyond mortality. Today explores the remarkable doctrine that He delivers even the dead.",
      scriptures: [{book:"D&C",ch:138,vs:18,ve:19},{book:"D&C",ch:128,vs:22},{book:"2 Tim",ch:1,vs:10}],
      nuances: "In D&C 138:18, President Joseph F. Smith saw that Christ visited the spirits in prison 'and the dead who repented will be redeemed, through obedience to the ordinances of the house of God.' The phrase 'house of God' connects the spirit world directly to the temple. Deliverance for the dead is not abstract or automatic — it operates through the same covenant framework available to the living, made accessible by vicarious ordinances.",
      commentary: "D&C 138 is one of the last canonized revelations in Latter-day Saint scripture. President Joseph F. Smith, meditating on 1 Peter 3-4 shortly before his own death, received a vision of Christ's visit to the spirit world between His death and resurrection. The spirits in prison were described as those who had been 'faithful in the testimony of Jesus while they lived in mortality' or who later received that testimony. Christ organized the righteous dead to carry the message of deliverance to those still in bondage.\n\nThis doctrine — that deliverance extends beyond the grave — is one of the most distinctive teachings of the Restoration. It resolves one of the oldest problems in Christian theology: what happens to those who never heard the gospel? The answer is not universalism (everyone is saved regardless) nor exclusivism (those who never heard are lost). It is that the Deliverer's work continues, and every soul will have a genuine opportunity to receive or reject His deliverance.\n\nD&C 128:22 celebrates this doctrine with almost lyrical exuberance, connecting it to the great chain of dispensations: voices from heaven and earth, from Moroni to Michael, all declaring the same message. Paul's statement in 2 Timothy 1:10 that Christ 'hath abolished death, and hath brought life and immortality to light through the gospel' takes on expanded meaning in this context — the gospel brings life and immortality to light for all, not merely those who happened to live in the right place and time.",
      patterns: "Christ's visit to the spirit world echoes His pattern of going where the lost are — among sinners in Galilee, among the Nephites in the Americas, and now among the dead in the spirit world. The Deliverer does not wait for the captive to come to Him; He goes to the prison.",
      reflection: "The doctrine of deliverance for the dead means that your temple service participates in Christ's delivering work. How does this change the way you think about temple worship?"
    },
    {
      label: "Living as the delivered",
      focus: "Deliverance is not just an event but an ongoing way of life. Today explores what it means to live as someone who has been set free.",
      scriptures: [{book:"Ex",ch:14,vs:13,ve:14},{book:"John",ch:8,vs:31,ve:36},{book:"Alma",ch:36,vs:17,ve:21}],
      nuances: "Moses' instruction at the Red Sea — 'Stand still, and see the salvation of the Lord' (Exodus 14:13) — uses the Hebrew 'hityatzvu' (stand firm, take your position). It does not mean passivity but readiness. The people are told to stop running and trust that the Lord will fight for them. This is the posture of the delivered: not frantic self-rescue but confident trust in the Deliverer.",
      commentary: "Exodus 14:13-14 captures a pivotal moment. Israel stands between Pharaoh's army and the Red Sea — trapped. Moses' counsel is counterintuitive: stop. Stand still. Watch what God does. The Lord will fight for you. This is the foundational deliverance story of the Old Testament, and it establishes a pattern that repeats endlessly: God's people find themselves in impossible situations, and God delivers them in ways they could not have engineered.\n\nJesus' teaching in John 8:31-36, revisited from earlier this week, adds the critical condition for ongoing deliverance: 'If ye continue in my word, then are ye my disciples indeed; and ye shall know the truth, and the truth shall make you free.' Deliverance is not a one-time event that requires no further participation. It is sustained by continuing in Christ's word. The disciple who walks away from the word walks back toward bondage.\n\nAlma 36, also revisited, reminds us that deliverance is both a moment and a lifetime. Alma was delivered in an instant — but he spent the rest of his life living as a delivered man, testifying of Christ, serving others, and calling people to repentance. The initial deliverance was a gift; the ongoing freedom was a choice, renewed daily.\n\nThe week closes with this truth: the Deliverer has done His part. The chains are broken. The prison doors are open. The question is not whether He is able to deliver but whether we will walk through the open door and keep walking in the light.",
      patterns: "The 'stand still and see' pattern appears throughout scripture — at the Red Sea, in Jehoshaphat's battle (2 Chronicles 20:17), and in D&C 123:17 ('Let us cheerfully do all things that lie in our power; and then may we stand still, with the utmost assurance, to see the salvation of God'). Deliverance always requires a moment of trust.",
      reflection: "Moses told Israel, 'The Lord shall fight for you, and ye shall hold your peace.' Is there a battle in your life where you need to stop fighting alone and let the Deliverer fight for you?"
    }
  ]
};

export default week15;
