import type { WeekContent } from '../types';

const week37: WeekContent = {
  title: "Head of the Church — Christ Leads His People",
  subtitle: "The Church is not an institution that honors Christ — it is His body, directed by His mind, animated by His Spirit.",
  weekScriptures: "Eph 2:19-22; Eph 4:4-6; Col 2:19; 1 Pet 2:5-6; D&C 10:67-69; D&C 21:4-6; 3 Ne 18:1-7; Mosiah 26:22; Acts 20:28; D&C 20:1-4; D&C 42:11",
  synthesis: {
    summary: "This week examines the doctrine that Jesus Christ is the head of His Church. He is not its figurehead or its historical founder only — He is its living, active leader. The Church exists to do His work, bear His name, administer His ordinances, and extend His reach into the world. Christ directs His Church through prophets, apostles, and the Holy Ghost, and every member of the body has a vital function. Understanding Christ as the Head transforms how we experience Church membership — from institutional obligation to participation in Christ's living body.",
    connections: [
      "Week 36's study of taking the name of Christ finds its communal expression here — those who individually take His name collectively form His Church.",
      "Christ's headship connects to Week 33's study of His relationship with the Father — He leads the Church under the Father's direction, just as He did everything in mortality.",
      "This connects forward to later weeks on Christ's role as King and Judge — His headship of the Church is one dimension of His universal authority."
    ],
    teaching: "If Christ is truly the head of His Church, what does that mean for how we relate to Church leaders, Church policies, and Church callings? How do we distinguish between human administration and divine direction?",
    commitment: "This week, approach your Church experience — Sunday worship, callings, interactions with members — with the conscious awareness that Christ is present and leading. Notice how that awareness changes your experience."
  },
  days: [
    {
      label: "Christ the Head",
      focus: "Paul declared Christ to be the head over all things to the Church. Today examines the foundational doctrine of Christ's headship and what it means.",
      scriptures: [{book:"Eph",ch:1,vs:22,ve:23},{book:"Col",ch:1,vs:18},{book:"Eph",ch:5,vs:23}],
      nuances: "In Ephesians 1:22, 'gave him to be the head over all things to the church,' the Greek 'kephalēn' (head) in ancient usage carried connotations of both authority and source — the head directs the body and is the origin of its life. Paul is saying Christ both governs and sustains the Church. It exists because of Him and moves at His direction.",
      commentary: "Ephesians 1:22–23 makes a claim of extraordinary scope: God has placed all things under Christ's feet and given Him to be the head over all things to the Church, which is His body. The Church is not merely an organization that serves Christ — it is His body. The metaphor is organic, not institutional. A body without a head is dead. The Church without Christ is nothing.\n\nColossians 1:18 adds that Christ is the beginning, the firstborn from the dead, so that in all things He might have the preeminence. His headship is rooted in His resurrection — He conquered death, and therefore He leads the community of the redeemed. His authority is not delegated from below but established from above.\n\nEphesians 5:23 draws an analogy between Christ's headship of the Church and the relationship between husband and wife. This is not a statement about human hierarchy but about self-giving love: Christ loved the Church and gave Himself for it. His headship is defined by sacrifice, not domination.\n\nThe practical implication is that the Church belongs to Christ. It is not the property of its leaders, its members, or its culture. Every policy, program, and practice exists to serve His purposes. When the Church functions as it should, Christ's will is what moves through its structures.",
      patterns: "The head-body metaphor recurs throughout Paul's epistles and is one of the defining images of the New Testament Church. It connects to the Restoration's emphasis that the Church is Christ's — bearing His name, doing His work, administered by His authority.",
      reflection: "Do you experience Church membership primarily as participation in Christ's living body, or primarily as belonging to an institution? What would shift if the body metaphor became more central to your experience?"
    },
    {
      label: "Built upon His rock",
      focus: "Christ declared He would build His Church upon a rock. Today examines the foundation of the Church and what makes it secure.",
      scriptures: [{book:"Matt",ch:16,vs:18},{book:"3 Ne",ch:27,vs:8,ve:10},{book:"D&C",ch:1,vs:30}],
      nuances: "In Matthew 16:18, 'upon this rock I will build my church,' the Greek 'petra' (rock, bedrock) is distinct from 'Petros' (Peter, a stone). There is a deliberate wordplay: Peter is a stone, but the rock upon which the Church is built is something larger — traditionally understood as Peter's confession of Christ, or Christ Himself, or the principle of revelation. The Church stands on something more permanent than any individual.",
      commentary: "Matthew 16:18 is one of the most debated verses in Christian history. Catholics read it as establishing Peter's authority; Protestants generally read it as pointing to Peter's confession or to Christ Himself. Restoration theology embraces the principle of revelation: the rock is the ongoing, living revelation from God that sustains and directs the Church. Without revelation, the Church becomes an empty institution.\n\n3 Nephi 27:8–10 provides Christ's own definitive statement: the Church must be called by His name and built upon His gospel. If it is built upon the works of men or the devil, it has temporary satisfaction but eventual destruction. Only what is built on Christ's gospel endures. This is a searching standard — it applies not only to the institutional Church but to every ward, every quorum, every family.\n\nD&C 1:30 identifies the restored Church as 'the only true and living church upon the face of the whole earth.' The word 'living' is as important as 'true.' A true church without living revelation would be a museum. A living church led by Christ is an organism — growing, adapting, responding to His direction in real time.\n\nThe foundation matters because it determines what the Church can withstand. Built on human wisdom, it will crumble under pressure. Built on Christ and His gospel, it stands against every opposition.",
      patterns: "The principle that the Church must be built on revelation connects to Amos 3:7 (studied later this week) and to the Restoration's foundational claim that God speaks today. Without living revelation, there is no living Church.",
      reflection: "Is your testimony of the Church built on the rock of personal revelation — your own witness that Christ leads it — or on something more fragile? What would strengthen that foundation?"
    },
    {
      label: "The body of Christ",
      focus: "Paul taught that the Church is the body of Christ, with each member serving a vital function. Today examines this organic vision of the Church.",
      scriptures: [{book:"1 Cor",ch:12,vs:12,ve:27},{book:"Eph",ch:4,vs:11,ve:16},{book:"Moro",ch:6,vs:4}],
      nuances: "In 1 Corinthians 12:21, 'the eye cannot say unto the hand, I have no need of thee,' Paul personifies body parts to make a relational argument. The Greek 'ou chreian sou echō' (I have no need of you) is a formula of social dismissal — the very kind of status-based rejection that plagued the Corinthian church. Paul is dismantling spiritual elitism within the body.",
      commentary: "1 Corinthians 12 is the most extended development of the body metaphor in all of Paul's writings. The body is one but has many members. The foot cannot say it is not part of the body because it is not the hand. The eye cannot say to the hand that it has no need of it. Every member is necessary, and the members that seem weakest are in fact indispensable.\n\nThis has profound implications for Church life. No calling is unimportant. No member is expendable. The person sitting quietly in the back pew may be serving a function that the most visible leader cannot serve. The body functions through the interdependence of all its parts — not through the dominance of a few.\n\nEphesians 4:11–16 adds the growth dimension: Christ gave apostles, prophets, evangelists, pastors, and teachers for the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ. The offices exist to serve the body, not the other way around. And the goal is that the whole body, fitly joined together, grows unto Him who is the head.\n\nMoroni 6:4 describes the early Nephite church: those who were baptized were numbered among the people of the Church and their names were taken, that they might be remembered and nourished by the good word of God. Membership was not bureaucratic — it was pastoral. To be numbered was to be known, remembered, and fed.\n\nThe Church as body means that your participation matters — not just for you but for everyone connected to you. When you serve, the whole body is strengthened. When you withdraw, the body is diminished.",
      patterns: "The body metaphor connects to the sacrament (Week 36) — the bread broken and shared represents the body of Christ, both His physical body and His church body. When we partake together, we enact our unity in Him.",
      reflection: "In the body of Christ, what is your function? Not your calling title, but the actual contribution you make to the spiritual life of those around you. How does knowing that the body needs you change how you show up?"
    },
    {
      label: "Led through prophets",
      focus: "Christ leads His Church through prophets and apostles. Today examines the doctrine of prophetic leadership and how revelation flows through the Church.",
      scriptures: [{book:"Amos",ch:3,vs:7},{book:"D&C",ch:107,vs:91,ve:92},{book:"Eph",ch:4,vs:11,ve:14}],
      nuances: "In Amos 3:7, 'Surely the Lord God will do nothing, but he revealeth his secret unto his servants the prophets.' The Hebrew 'sōd' (secret, counsel) implies intimate, insider knowledge — the kind shared between close confidants. God treats His prophets as trusted advisors, sharing His plans with them before acting. This is not micromanagement but partnership.",
      commentary: "Amos 3:7 is one of the most important verses in the Old Testament for understanding how God operates. He does not act in human history without first revealing His purposes to His prophets. This is not a description of ancient practice only — it is a statement of divine principle. God still works through prophets because that is how He has always worked.\n\nD&C 107:91–92 identifies the President of the Church as the presiding high priest, who holds the keys of all spiritual blessings and has the privilege of receiving revelations for the Church. This is the structural expression of Christ's headship — He leads through a mortal servant who holds the keys of revelation. The prophet does not replace Christ but serves as His mouthpiece.\n\nEphesians 4:11–14 explains why Christ gave apostles and prophets: to prevent the saints from being tossed about by every wind of doctrine. The prophetic office provides doctrinal stability and directional clarity. Without it, the Church would fracture into competing opinions and local traditions — which is precisely what happened during the Great Apostasy.\n\nThe balance here is critical. Prophetic leadership does not eliminate individual responsibility for personal revelation. It provides a framework within which personal revelation operates. The prophet speaks for Christ to the Church; the Spirit confirms the prophet's words to the individual. Both are necessary.",
      patterns: "The prophetic pattern — God speaking through authorized servants — runs from Adam through Moses through the biblical prophets through the Book of Mormon prophets to Joseph Smith and his successors. Christ's headship of the Church has always been mediated through mortal prophets.",
      reflection: "How do you personally sustain the prophet — not just by raising your hand but by seeking confirmation through the Spirit that his counsel is from Christ? When was the last time you received such a witness?"
    },
    {
      label: "Ordinances and authority",
      focus: "Christ directs His Church through ordinances performed by His authority. Today examines how priesthood ordinances make Christ's headship operational.",
      scriptures: [{book:"3 Ne",ch:11,vs:21,ve:22},{book:"D&C",ch:84,vs:19,ve:22},{book:"Matt",ch:28,vs:18,ve:20}],
      nuances: "In 3 Nephi 11:21, Christ gives Nephi specific authority to baptize: 'I give unto you power that ye shall baptize this people.' The Greek-equivalent 'exousia' (authority, power, right) in Matthew's account implies delegated authority — it originates with Christ and is bestowed upon His servants. Priesthood authority is always derivative, never self-generated.",
      commentary: "When the risen Christ appeared to the Nephites, one of His first acts was to establish the ordinance of baptism and delegate the authority to perform it. This was not an afterthought — it was foundational. Before teaching doctrine, before establishing governance, He established the ordinance and the authority. The order reveals the priority: ordinances come first because they are the means by which Christ's grace reaches His people.\n\nD&C 84:19–22 teaches that the ordinances of the priesthood carry the power of godliness, and without them the power of godliness is not manifest to human beings in the flesh. This is a remarkable claim: the ordinances are not mere symbols or reminders. They are the actual means by which God's power enters mortal life. Christ's headship is not abstract — it is mediated through tangible, physical acts performed under His authority.\n\nMatthew 28:18–20 records the Great Commission: Christ sends His apostles to teach and baptize all nations. The commission is grounded in His declaration that all power in heaven and earth is given to Him. The authority of the apostles derives entirely from His authority. They do not go in their own name but in His.\n\nThis understanding transforms how we experience ordinances. When you are baptized, confirmed, ordained, or sealed, you are not merely participating in a religious ceremony — you are receiving something from Christ through His authorized servants. His headship is made tangible in every ordinance.",
      patterns: "The pattern of delegated authority — from Christ to apostles to priesthood holders — runs from the New Testament through the Restoration. The chain is always traceable to Christ. This connects to Week 36's study of acting in His name.",
      reflection: "The next time you witness or participate in an ordinance, consider: this authority traces back to Christ Himself. How does that awareness change the way you experience the ordinance?"
    },
    {
      label: "A faithful servant",
      focus: "Christ entrusts His Church to mortal servants who must be faithful stewards. Today examines the principle of stewardship within Christ's Church.",
      scriptures: [{book:"Hel",ch:10,vs:4,ve:7},{book:"D&C",ch:84,vs:33,ve:38},{book:"Mosiah",ch:18,vs:17}],
      nuances: "In Helaman 10:4, the Lord tells Nephi: 'thou hast not sought thine own life, but hast sought my will, and to keep my commandments.' The word 'sought' (Hebrew 'darash' carries the sense of diligent seeking) implies sustained, deliberate orientation — not momentary compliance but a life consistently directed toward God's purposes. This is the qualification for stewardship.",
      commentary: "Helaman 10:4–7 records one of the most extraordinary delegations of authority in scripture. The Lord tells Nephi that because he has been unwearyingly faithful and has sought God's will above his own, He will make Nephi mighty in word and deed, and whatever Nephi asks shall be done. This is not blanket power — it is power given to one whose will has become so aligned with God's that he will not ask anything contrary to God's purposes.\n\nD&C 84:33–38 describes the oath and covenant of the priesthood. Those who magnify their callings receive the Father's kingdom and all that the Father has. But the passage also contains a warning: those who break this covenant and turn from it entirely have no forgiveness. The stewardship is serious because the authority is real. Leading in Christ's Church is not a volunteer activity — it is a sacred trust.\n\nMosiah 18:17 records that Alma, having been converted and authorized, organized the Church of God. He did not create his own movement — he established what God directed. The organizational acts were not bureaucratic but priestly: Alma acted as a steward of Christ's work, not as a founder of his own.\n\nThe principle is that those who lead in Christ's Church are stewards, not owners. Christ remains the head. Every bishop, stake president, Relief Society president, and teacher serves under His direction and will give an accounting to Him. The stewardship model keeps human ego in check and orients all service toward Christ.",
      patterns: "The stewardship principle runs from the parable of the talents to the modern Church's emphasis on magnifying callings. Authority in Christ's Church is always accountable to Christ Himself. This connects to Week 33's study of how Christ Himself operated under the Father's authority.",
      reflection: "Whether you hold a visible leadership calling or serve quietly in the background, you are a steward of Christ's work. How are you stewarding the trust He has placed in you — in your calling, your family, your personal ministry?"
    },
    {
      label: "His Church endures",
      focus: "Christ promised that the gates of hell would not prevail against His Church. Today examines the durability and destiny of the Church Christ leads.",
      scriptures: [{book:"Matt",ch:16,vs:18},{book:"D&C",ch:115,vs:4},{book:"Acts",ch:2,vs:41,ve:47}],
      nuances: "In Matthew 16:18, 'the gates of hell shall not prevail against it,' the Greek 'pulai hadou' (gates of Hades/the underworld) refers not to offensive attack but to the holding power of death and darkness. Gates are defensive structures. Christ is saying that death itself — the ultimate imprisoning force — will not be able to contain or overcome His Church. The Church will break through even the gates of death.",
      commentary: "Christ's promise in Matthew 16:18 is a statement of ultimate confidence. His Church will endure. Not because its members are perfect, not because its leaders are infallible, but because He is its head and He has promised. The gates of hell — every force of darkness, death, and opposition — will not prevail against it.\n\nD&C 115:4 gives the restored Church its full name: The Church of Jesus Christ of Latter-day Saints. Every element of the name is significant. It is His Church. It is composed of saints — covenant people striving to follow Him. And it is established in the latter days — the final dispensation before His return. The name is a declaration of identity, ownership, and timing.\n\nActs 2:41–47 describes the earliest Church in action: three thousand were baptized, they continued in the apostles' doctrine and fellowship, they broke bread together, they shared their possessions, and the Lord added to the Church daily. This is the pattern: a community of believers, united by covenant, sustained by ordinances, led by apostles, and growing under the Lord's direction.\n\nThe restored Church follows the same pattern. It is not a new invention but a restoration of what existed in the beginning. Christ leads it now as He led it then — through prophets, through ordinances, through the Holy Ghost, and through the faithful response of His people.\n\nThe Church will endure because Christ endures. His headship is not a historical artifact — it is a present reality. He is leading His Church today, and He will lead it until He comes again.",
      patterns: "The pattern of apostasy and restoration — the Church established, lost, and restored — demonstrates that Christ's headship is persistent. He did not abandon His work when apostasy came; He waited and restored it in the fulness of times. This connects to the entire Restoration narrative studied in earlier weeks.",
      reflection: "Christ promised His Church would endure. How does that promise affect the way you navigate moments of doubt, frustration, or discouragement within the Church? Does knowing Christ leads it change how you respond to imperfection in its members — including yourself?"
    }
  ]
};

export default week37;
