import type { WeekContent } from '../types';

const week16: WeekContent = {
  title: "Power of — The Almighty Christ",
  subtitle: "The power of Jesus Christ is not abstract theology; it is the operative force that created worlds, heals bodies, transforms hearts, and will raise the dead.",
  weekScriptures: "Matt 28:18; Luke 4:36; Mark 4:37–41; John 10:17–18; Matt 9:6–8; Philip 4:13; 2 Cor 12:9–10; Eph 1:19–21; Eph 3:20; Moro 10:32–33; 2 Ne 1:15; Mosiah 4:6–7; Alma 26:12; D&C 88:6–13; D&C 17:1; Hel 5:17–18; 3 Ne 28:6–7; Morm 9:15–21; Jacob 4:6–7; 1 Ne 17:46–48",
      synthesis: {
    summary: "Christ possesses all power — in heaven and on earth, over nature and nations, over sin and death. This is not merely a theological assertion but a demonstrated reality. He calmed storms, healed bodies, forgave sins, conquered death, and promised that His power would be available to His disciples. The Book of Mormon and Doctrine and Covenants add the teaching that this same power operates in individual lives through faith, enabling ordinary people to do extraordinary things.",
    connections: [
      "Christ's power is what makes His redemption (Week 14) and deliverance (Week 15) effective — without infinite power, infinite mercy would be merely infinite sympathy.",
      "The glory of Christ (Week 17) is inseparable from His power — glory is power made visible.",
      "Christ as Rock (Week 18) provides the foundation on which His power can be accessed through faith."
    ],
    teaching: "What is the difference between knowing that Christ is powerful and actually relying on His power in your daily life? What keeps you from accessing power that is freely offered?",
    commitment: "This week, identify one challenge you have been trying to handle through your own strength alone. Consciously bring it to Christ and rely on His power, noting any difference in your experience."
  },
  days: [
    {
      label: "All power given unto Him",
      focus: "The scope of Christ's power is total. Today examines His own declaration of universal authority and what it means for every other claim to power.",
      scriptures: [{book:"Matt",ch:28,vs:18},{book:"Eph",ch:1,vs:19,ve:21},{book:"D&C",ch:88,vs:6,ve:13}],
      nuances: "In Matthew 28:18, 'All power is given unto me in heaven and in earth' uses the Greek 'pasa exousia' — not merely 'dynamis' (raw power) but 'exousia' (authority, legitimate right to rule). Christ does not claim brute force but sovereign jurisdiction. Every form of authority in heaven and earth derives from and answers to Him. This is the most comprehensive claim to authority in the entire New Testament.",
      commentary: "The resurrected Christ stands before His disciples and makes the most sweeping claim of authority ever uttered: all power, in all places. This declaration is the basis for the Great Commission that follows — because He has all authority, His followers can go to all nations. The authority of the mission derives from the authority of the one who sends.\n\nPaul elaborates in Ephesians 1:19-21, describing the power that raised Christ from the dead and seated Him 'far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come.' The cascade of terms is deliberate: Paul is systematically eliminating every possible rival claim to authority. Whatever power structure you can name — political, spiritual, cosmic — Christ is above it.\n\nD&C 88:6-13 expands this further than any other scriptural text. The light of Christ proceeds from His presence to fill the immensity of space. It gives life to all things. It is the law by which all things are governed. It is in the sun, the moon, the stars, and the earth. This is not merely spiritual power but cosmological power — Christ is the sustaining force behind physical reality itself.\n\nTaken together, these three passages establish that Christ's power is not one force among many but the foundational force from which all others derive.",
      patterns: "The declaration of universal power in Matthew 28 follows the pattern of authority established through suffering. Christ receives all power after His crucifixion and resurrection — not despite them. This pattern recurs in scripture: power is unlocked through faithful suffering, not through the avoidance of it.",
      reflection: "If Christ truly possesses all power in heaven and earth, what implications does that have for the fears or obstacles you are currently facing?"
    },
    {
      label: "Power over nature",
      focus: "Christ commanded the wind, the waves, and the elements. Today explores His authority over the physical world and what it reveals about His identity.",
      scriptures: [{book:"Mark",ch:4,vs:37,ve:41},{book:"1 Ne",ch:17,vs:46,ve:48},{book:"Jacob",ch:4,vs:6,ve:7}],
      nuances: "In Mark 4:39, Jesus 'rebuked the wind, and said unto the sea, Peace, be still.' The Greek 'siōpa, pephimōso' literally means 'Be silent! Be muzzled!' — the same language used to silence demons (Mark 1:25). Jesus speaks to the storm as if it were a hostile, animate force that must obey His command. The sea, which in Hebrew thought often symbolized chaos and threat, submits instantly to His word.",
      commentary: "The stilling of the storm in Mark 4 is not primarily a miracle story — it is an identity revelation. When Jesus calms the sea, the disciples ask, 'What manner of man is this, that even the wind and the sea obey him?' In the Old Testament, commanding the sea is the exclusive prerogative of Yahweh (Psalm 107:29, Job 38:8-11). The disciples, steeped in these scriptures, are confronting an inescapable conclusion: the man sleeping in the boat is the God who made the sea.\n\nNephi's declaration in 1 Nephi 17:46-48 extends this power to the Western Hemisphere and an earlier dispensation. When his brothers doubt God's power to help them build a ship, Nephi reminds them that God commanded the waters and the earth, shook mountains, and can do 'all things.' Nephi's faith is grounded not in his own abilities but in the demonstrated power of the God of Israel.\n\nJacob 4:6-7 provides the theological principle underlying both passages: 'We truly can command in the name of Jesus and the very trees obey us, or the mountains, or the waves of the sea.' The faith that moves mountains is not magical thinking but trust in the specific being who made the mountains. Jacob explicitly states that this power operates through knowledge of Christ and confidence in His word.\n\nChrist's power over nature is not a parlor trick or a display for its own sake. It is the Creator demonstrating His ongoing authority over creation — and inviting His people to participate in that authority through faith.",
      patterns: "The pattern of divine power over creation runs from Genesis 1 (creation by divine word) through the plagues of Egypt, the parting of the Red Sea, Joshua commanding the sun, and Christ calming the storm. In every case, the elements obey the voice of their Creator.",
      reflection: "The disciples in the boat experienced both terror and awe. When has a display of God's power in your life moved you from fear to faith?"
    },
    {
      label: "Power to heal and forgive",
      focus: "Christ healed bodies and forgave sins — and deliberately linked the two. Today explores the connection between physical healing and spiritual power.",
      scriptures: [{book:"Matt",ch:9,vs:6,ve:8},{book:"Luke",ch:4,vs:36},{book:"Mosiah",ch:4,vs:6,ve:7}],
      nuances: "In Matthew 9:6, Jesus heals the paralytic specifically to prove His authority to forgive sins: 'But that ye may know that the Son of man hath power on earth to forgive sins, (then saith he to the sick of the palsy,) Arise, take up thy bed, and go.' The visible miracle (healing) is offered as evidence of the invisible one (forgiveness). The Greek 'exousia' (authority/power) is the same word used in Matthew 28:18 — the same universal authority that governs the cosmos also operates in a single room to heal one man.",
      commentary: "The healing of the paralytic in Matthew 9 is one of the most theologically charged miracle accounts in the Gospels. The scribes are offended when Jesus pronounces the man's sins forgiven — in their view, only God can forgive sins. Jesus does not dispute their premise. Instead, He demonstrates His authority by doing something they can verify: healing the man's paralysis. The logic is precise: if He has power to heal (which you can see), then He has power to forgive (which you cannot see).\n\nLuke 4:36 records the astonishment of the crowd at Capernaum: 'What a word is this! for with authority and power he commandeth the unclean spirits, and they come out.' The combination of authority (exousia) and power (dynamis) is significant — Christ has both the right to command and the force to execute. His word is not merely instructive but operative: things happen when He speaks.\n\nKing Benjamin's teaching in Mosiah 4:6-7 connects Christ's power directly to the experience of the believer: knowledge of the goodness of God, His matchless power, wisdom, patience, and long-suffering awakens faith, which leads to salvation. The power of Christ is not theoretical — it becomes real to us through personal encounter. Benjamin's people had just fallen to the earth under the weight of their own sinfulness; it was the power of Christ's Spirit that lifted them.",
      patterns: "The connection between physical healing and spiritual forgiveness is a pattern throughout Christ's ministry. He heals the body to demonstrate His power over the soul. This pattern is preserved in priesthood blessings in the Restoration, where physical healing and spiritual comfort are administered together.",
      reflection: "Jesus healed the paralytic's body to prove He could heal the man's soul. Is there an area of spiritual paralysis in your life where you need to trust Christ's power to make you whole?"
    },
    {
      label: "Power over death",
      focus: "The supreme demonstration of Christ's power is His authority over death itself. Today examines His unique claim to lay down His life and take it up again.",
      scriptures: [{book:"John",ch:10,vs:17,ve:18},{book:"Morm",ch:9,vs:15,ve:21},{book:"3 Ne",ch:28,vs:6,ve:7}],
      nuances: "John 10:17-18 contains the most extraordinary claim about death in all of scripture: 'I lay down my life, that I might take it again. No man taketh it from me, but I lay it down of myself. I have power to lay it down, and I have power to take it again.' The Greek 'exousian echo' (I have authority) appears twice — once for dying and once for rising. Christ's death was not an accident, a tragedy, or a defeat. It was a sovereign act of will, and so was His resurrection.",
      commentary: "John 10:17-18 reveals something unique about Christ: His death was voluntary in a way that no other death has ever been. He was not killed against His will; He chose to die. And He did not depend on someone else to raise Him; He had power to rise Himself. This dual authority — over His own death and His own resurrection — is what sets Him apart from every other figure in human history.\n\nMormon's son Moroni, writing in a time of civilizational collapse, grounds his final testimony in this power. In Mormon 9:15-21, he argues that the God who created the heavens and the earth, who created Adam and brought about the Fall, is the same God who brought about the redemption. If God has power to create, He has power to resurrect. If He has power to make the world, He has power to remake it. Moroni's argument is that denying miracles and resurrection is logically inconsistent with believing in a Creator God.\n\n3 Nephi 28:6-7 records Christ's promise to three Nephite disciples that they would never taste death but would live until His Second Coming. This is a specific exercise of the same power declared in John 10 — power over death is not limited to His own experience but extends to others according to His will and purpose.\n\nThe power over death is the keystone of Christian faith. Paul said it plainly: if Christ is not risen, faith is vain (1 Corinthians 15:14). But He is risen — and that changes everything.",
      patterns: "The voluntary nature of Christ's death echoes the voluntary nature of His condescension (Week 1, Day 2) and His voluntary submission to suffering (Weeks 12-13). At every stage, Christ's power is exercised through willing submission, not through domination.",
      reflection: "Christ had power to avoid death but chose to die for you. How does His voluntary sacrifice change the way you think about your own willingness to sacrifice for others?"
    },
    {
      label: "Power made perfect in weakness",
      focus: "Christ's power is most fully experienced not in human strength but in human weakness. Today explores the paradox that divine power flows most freely into empty vessels.",
      scriptures: [{book:"2 Cor",ch:12,vs:9,ve:10},{book:"Alma",ch:26,vs:12},{book:"Ether",ch:12,vs:27}],
      nuances: "Paul's 'thorn in the flesh' (2 Corinthians 12:7) has generated centuries of speculation — was it a physical illness, poor eyesight, a speech impediment, or persecution? Paul deliberately does not specify, and this ambiguity is itself instructive. By leaving the thorn unnamed, Paul ensures that every reader can map their own weakness onto his experience. The principle is universal: whatever your thorn, Christ's grace is sufficient.",
      commentary: "Paul asked three times for his thorn to be removed. The Lord's answer was not removal but revelation: 'My grace is sufficient for thee: for my strength is made perfect in weakness.' This is among the most counterintuitive statements in scripture. God does not say, 'I will make you strong enough to handle this.' He says, 'Your weakness is the very context in which my power operates most fully.' Paul's response is equally radical: 'When I am weak, then am I strong.'\n\nAmmon's exultation in Alma 26:12 resonates with Paul's teaching: 'I will not boast of myself, but I will boast of my God, for in his strength I can do all things.' Ammon had just accomplished one of the most remarkable missionary successes in the Book of Mormon, but he attributes none of it to his own ability. His power was borrowed — it came entirely from God.\n\nThe Lord's teaching to Moroni in Ether 12:27 completes the principle: 'If men come unto me I will show unto them their weakness. I give unto men weakness that they may be humble; and my grace is sufficient for all men that humble themselves before me.' Weakness is not merely tolerated by God — it is given by Him as a pathway to grace. This reframes every limitation, every inadequacy, every failure as a potential access point for divine power.\n\nThis paradox runs throughout scripture and stands in sharp contrast to worldly notions of power. The world says power belongs to the strong; Christ says His power flows into the weak.",
      patterns: "The weakness-to-strength pattern appears in Moses (who could not speak well), Gideon (who was the least of his family), David (who was the youngest son), Enoch (who was slow of speech), and Joseph Smith (who was unlearned). God consistently chooses unlikely vessels to demonstrate that the power is His, not theirs.",
      reflection: "What is your 'thorn in the flesh' — the weakness you have asked God to remove? How might it be the very place where His power wants to manifest most fully?"
    },
    {
      label: "Power available to disciples",
      focus: "Christ's power is not reserved for Himself alone. Today examines how that power becomes available to His followers through faith and covenant.",
      scriptures: [{book:"Philip",ch:4,vs:13},{book:"Hel",ch:5,vs:17,ve:18},{book:"D&C",ch:17,vs:1}],
      nuances: "Philippians 4:13 — 'I can do all things through Christ which strengtheneth me' — is one of the most quoted and most misunderstood verses in scripture. The Greek 'ischyō' (I am strong, I have power) and 'endynamounti' (the one empowering me) form a deliberate wordplay. Paul is not claiming unlimited personal ability but unlimited access to Christ's ability. The subject is Christ's power, not Paul's potential.",
      commentary: "Philippians 4:13 is often quoted as a motivational slogan, but its context is deeply specific. Paul writes this from prison, having learned to be content in both abundance and deprivation. His 'I can do all things' is not a claim about personal ambition but about spiritual endurance. He can face anything — not because he is naturally resilient but because Christ empowers him from within.\n\nHelaman 5:17-18 records that Nephi and Lehi (sons of Helaman) performed miracles so numerous that they could not all be written. They baptized thousands, and the power of God was with them. The narrative is clear: the power was God's, channeled through faithful men. They did not generate it; they received it. Their qualifications were righteousness and faith, not education or political position.\n\nD&C 17:1, addressed to the Three Witnesses of the Book of Mormon, states: 'It is by your faith that you shall obtain a view of them, even by that faith which was had by the prophets of old.' The power to receive divine manifestation is linked directly to faith — the same faith that operated in ancient prophets is available to modern disciples. There is no qualitative difference between the faith of Moses and the faith available to you.\n\nThe practical implication is both humbling and empowering: you do not need to be extraordinary. You need to be connected to the one who is.",
      patterns: "The pattern of divine power flowing through mortal agents is constant: Moses parts the sea, Elijah calls fire from heaven, Peter heals the lame, Nephi and Lehi are encircled by fire. In every case, the agent is clear that the power is not theirs. This humility is the condition for the power's operation.",
      reflection: "Paul learned that Christ's power was sufficient in prison. Nephi and Lehi experienced it in missionary service. Where in your current circumstances do you most need to access Christ's power through faith?"
    },
    {
      label: "The arms of His power",
      focus: "Christ's power is not cold or impersonal. Today explores the intimate, embracing nature of divine power — arms that encircle as well as uphold.",
      scriptures: [{book:"2 Ne",ch:1,vs:15},{book:"Eph",ch:3,vs:20},{book:"Moro",ch:10,vs:32,ve:33}],
      nuances: "Lehi's phrase 'encircled about eternally in the arms of his love' (2 Nephi 1:15) uses the image of embrace, not merely protection. The Hebrew concept behind 'arms' (zeroa) in reference to God connotes both strength and tenderness — the same arm that fights battles also cradles children. Lehi, near death, is describing not a theological concept but a felt experience: he has been held by God.",
      commentary: "Lehi's dying testimony in 2 Nephi 1:15 is one of the most beautiful sentences in the Book of Mormon. After a lifetime of hardship — leaving Jerusalem, crossing the desert, sailing an ocean, enduring family conflict — he describes his ultimate experience of God's power in the language of embrace. He is 'encircled about eternally in the arms of his love.' Power and love are not competing attributes but unified experience. The arms that hold you are the same arms that made the worlds.\n\nPaul's prayer in Ephesians 3:20 points in the same direction: God 'is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us.' The power is not external only — it works 'in us.' It is internal, personal, and beyond anything we can imagine or request. This is not the power of a distant emperor but the power of an indwelling God.\n\nMoroni's final invitation in Moroni 10:32-33 closes the Book of Mormon with a promise of perfection through Christ. 'Come unto Christ, and be perfected in him... then is his grace sufficient for you, that by his grace ye may be perfect in Christ.' The power of Christ does not merely rescue you from failure; it elevates you to completion. Grace is not only pardon — it is enabling, perfecting, finishing power.\n\nThe week ends where the gospel always ends: with an invitation. Christ's power is real, vast, demonstrated, and available. The question is not whether He can but whether you will come to Him and let His arms encircle you.",
      patterns: "The image of divine arms — holding, carrying, fighting, embracing — runs from Deuteronomy 33:27 ('the everlasting arms') through Isaiah 40:11 ('He shall gather the lambs with his arm') to 2 Nephi 1:15 and Mormon 5:11. Power in scripture is never separated from personal, tender care.",
      reflection: "Lehi spoke of being 'encircled about eternally in the arms of his love.' Have you experienced Christ's power as both strong and tender? What did that feel like?"
    }
  ]
};

export default week16;
