import type { WeekContent } from '../types';

const week50: WeekContent = {
  title: "Messiah — The Anointed One, the Fulfillment of All Things",
  subtitle: "The final week: Christ is the Messiah, the Anointed One — the answer to every prophecy, every covenant, and every longing of the human heart.",
  weekScriptures: "John 1:41; John 4:25–26; Dan. 9:25–26; Acts 2:36; Acts 3:18–20; Luke 4:16–21; 2 Ne. 25:16–20; Jacob 4:4–5; Mosiah 13:33–35; D&C 18:21–25; Matt. 16:15–17; John 6:68–69; Ps. 2:1–7; Isa. 61:1–3; Luke 24:25–27; D&C 76:1; John 20:31; 2 Ne. 11:4; Alma 34:8–14; D&C 46:13",
  synthesis: {
    summary: "For fifty weeks, we have studied Jesus Christ from every angle scripture provides — His identity, His roles, His covenants, His suffering, His glory. This final week gathers everything into one title: Messiah. The Hebrew 'Mashiach' and the Greek 'Christos' both mean 'the Anointed One' — the one chosen, consecrated, and empowered by God to save the world. Every prophecy pointed to Him. Every type foreshadowed Him. Every covenant depended on Him. He is not one option among many; He is the One. This week is both a culmination and a beginning — the end of a year of study and the start of a deeper, lifelong relationship with the Anointed One.",
    connections: [
      "Every week of this fifty-week plan is a facet of the Messiah's identity: Creator (Week 2), Lawgiver (Week 8), Atoner (Weeks 14–15), Risen Lord (Week 16), Prophet, Priest, and King (Weeks 36–38), Judge (Week 42), and Shepherd (Week 47). The Messiah encompasses all.",
      "The prophetic anticipation of the Messiah (Weeks 39–41) finds its full expression here: He came, He fulfilled, and He will come again.",
      "The birth of the Messiah (Week 49) was the beginning of His mortal mission; this week reflects on the completeness of who He is and what He accomplished."
    ],
    teaching: "After fifty weeks of studying Jesus Christ, what do you know now that you did not know at the beginning? How has your relationship with Him changed?",
    commitment: "This year of study ends, but your walk with Christ does not. Choose one practice from this year — a scripture, a question, a habit of reflection — and carry it forward. The Messiah is not a subject to be completed; He is a Person to be known."
  },
  days: [
    {
      label: "We have found the Messiah",
      focus: "Andrew's declaration to Peter is one of the most joyful sentences in scripture: 'We have found the Messiah.' Today enters the moment of discovery.",
      scriptures: [{book:"John",ch:1,vs:41},{book:"John",ch:4,vs:25,ve:26},{book:"Dan",ch:9,vs:25,ve:26}],
      nuances: "John 1:41 records Andrew's words: 'We have found the Messias, which is, being interpreted, the Christ.' John translates the Hebrew 'Mashiach' into Greek 'Christos' for his readers. Both words mean 'anointed one.' In ancient Israel, prophets, priests, and kings were anointed with oil as a sign of divine commission. The Messiah is the ultimate Anointed One — holding all three offices in Himself.",
      commentary: "Andrew's words vibrate with excitement: 'We have found the Messiah!' This is the sentence Israel had been waiting centuries to hear. Since the Babylonian exile, through the silence of the intertestamental period, through Roman occupation, the Jewish people waited for the Anointed One who would fulfill God's promises, restore the kingdom, and bring salvation. Andrew believed he had found Him.\n\nJohn 4:25–26 records a parallel moment of stunning intimacy. The Samaritan woman at the well says, 'I know that Messias cometh, which is called Christ: when he is come, he will tell us all things.' Jesus responds with the most direct messianic declaration in the Gospels: 'I that speak unto thee am he.' No parable, no riddle, no indirection — just a clear statement to an unlikely recipient. The Messiah revealed Himself not to the religious elite but to a Samaritan woman drawing water at noon.\n\nDaniel 9:25–26 prophesied that the Messiah would come at a specific time — after a determined number of weeks (prophetic periods) following the decree to rebuild Jerusalem. The prophecy also foretold that the Messiah would be 'cut off, but not for himself' — a clear reference to the Atonement. The Messiah's mission included both His coming and His suffering. You cannot have one without the other.\n\nThe discovery of the Messiah is the pivotal event in any person's spiritual life. Andrew found Him by the Jordan. The Samaritan woman found Him at the well. Where did you find Him?",
      patterns: "The pattern of discovering the Messiah is always personal: Andrew found Him through John the Baptist, Philip found Him through Andrew, the Samaritan woman found Him in conversation, Paul found Him on the road to Damascus. The Messiah is found, but He is also seeking — as Week 47 (Good Shepherd) reminded us.",
      reflection: "Andrew said, 'We have found the Messiah.' Can you say the same? When and how did you first discover that Jesus is the Christ?"
    },
    {
      label: "The anointed mission",
      focus: "In the synagogue at Nazareth, Jesus read Isaiah's prophecy about the Anointed One and declared: 'This day is this scripture fulfilled.' Today examines what the Messiah was anointed to do.",
      scriptures: [{book:"Luke",ch:4,vs:16,ve:21},{book:"Isa",ch:61,vs:1,ve:3},{book:"Ps",ch:2,vs:1,ve:7}],
      nuances: "Luke 4:18 quotes Isaiah 61:1: 'The Spirit of the Lord is upon me, because he hath anointed me to preach the gospel to the poor.' The Greek 'echrisen me' (anointed me) uses the verb form of 'Christos.' To say 'God anointed me' is to say 'God made me the Christ.' Jesus was declaring His messianic identity through the language of anointing itself.",
      commentary: "The scene in the Nazareth synagogue is one of the most dramatic moments in the Gospels. Jesus stood, unrolled the scroll of Isaiah, and read: the Spirit of the Lord is upon me because He has anointed me to preach good news to the poor, recovery of sight to the blind, liberty to the captives, and the acceptable year of the Lord. Then He sat down, every eye upon Him, and said: 'This day is this scripture fulfilled in your ears.'\n\nThe claim is breathtaking. Jesus was not saying that Isaiah's prophecy would be fulfilled someday. He was saying it was fulfilled now, in Him, in that room. The Messiah had arrived, and He was standing before them.\n\nIsaiah 61:1–3 defines the messianic mission: it is a mission of compassion, liberation, and restoration. The Messiah comes not to conquer but to heal. The poor hear good news. The brokenhearted are bound up. The captives are freed. This is the character of the anointing — power directed toward the suffering.\n\nPsalm 2 adds the royal dimension: God declares, 'Thou art my Son; this day have I begotten thee.' The Messiah is both the compassionate healer of Isaiah 61 and the enthroned King of Psalm 2. Tenderness and authority are inseparable in the Anointed One. This is the Messiah the entire plan of salvation depends on — a King who heals, a Healer who reigns.",
      patterns: "The messianic mission defined in Isaiah 61 echoes through every week of this study: good news (the gospel), healing (the Atonement), liberty (redemption from sin and death), and restoration (the gathering and the Millennium). The anointed mission is the whole plan.",
      reflection: "Jesus was anointed to bring good news to the poor, heal the brokenhearted, and free the captives. Which aspect of His messianic mission do you need most in your life right now?"
    },
    {
      label: "Every prophet testified of Him",
      focus: "On the road to Emmaus, the risen Christ opened the scriptures and showed that all things written by the prophets pointed to Him. Today we see the Messiah in the sweep of all scripture.",
      scriptures: [{book:"Luke",ch:24,vs:25,ve:27},{book:"Jacob",ch:4,vs:4,ve:5},{book:"Mosiah",ch:13,vs:33,ve:35},{book:"2 Ne",ch:11,vs:4}],
      nuances: "Luke 24:27 says Jesus 'beginning at Moses and all the prophets, expounded unto them in all the scriptures the things concerning himself.' The Greek 'diermēneusen' (expounded) means to interpret thoroughly — Christ gave a comprehensive, authoritative reading of the entire Old Testament as messianic testimony. This was the original 'Christological reading' of scripture, performed by Christ Himself.",
      commentary: "The Emmaus road is one of the most poignant post-resurrection appearances. Two disciples, despairing after the crucifixion, were walking away from Jerusalem when a stranger joined them. He asked why they were sad. They explained: Jesus of Nazareth, whom they had hoped was the Messiah, had been crucified. The stranger rebuked their slowness of heart and then, beginning with Moses, walked them through every scripture that pointed to the Christ.\n\nWe do not have the specific passages He cited, but we know the principle: all scripture testifies of Christ. Jacob 4:4–5 makes this explicit from the Book of Mormon: all the holy prophets who were before the Nephites believed in Christ and worshipped the Father in His name. The law of Moses itself was given as a type of Christ. Everything — every sacrifice, every feast, every prophetic oracle — pointed forward to the Messiah.\n\nAbinadi declared the same to King Noah's priests in Mosiah 13:33–35: God Himself would come down among the children of men and redeem His people. Prophets since the beginning had testified of this.\n\nNephi stated the principle with characteristic clarity in 2 Nephi 11:4: 'All things which have been given of God from the beginning of the world, unto man, are the typifying of him.' Every gift God has ever given humanity is a type, a shadow, a foretaste of the Messiah. The entire created order is a testimony of Christ.\n\nAfter fifty weeks of study, this should now be visible to you. When you read any scripture — Genesis or Revelation, 1 Nephi or Doctrine and Covenants — you are reading about the Messiah.",
      patterns: "The Emmaus road conversation is the interpretive key to the entire Bible. Christ taught His own disciples to read all scripture as messianic testimony. This is the same lens we have used throughout this fifty-week plan — and it transforms every page.",
      reflection: "Christ opened the scriptures on the Emmaus road and the disciples' hearts burned. Has your heart burned during this year of study? Which moment or passage awakened you most?"
    },
    {
      label: "Thou art the Christ",
      focus: "Peter's confession at Caesarea Philippi is the pivotal moment of the Gospels. Today we stand with Peter and make our own declaration.",
      scriptures: [{book:"Matt",ch:16,vs:15,ve:17},{book:"John",ch:6,vs:68,ve:69},{book:"D&C",ch:46,vs:13},{book:"Acts",ch:2,vs:36}],
      nuances: "Matthew 16:16 records Peter's confession: 'Thou art the Christ, the Son of the living God.' The Greek 'ho Christos ho huios tou theou tou zōntos' is emphatically definite — not a Christ but the Christ, not a son but the Son, not of a god but of the living God. Every article is deliberate. Peter was not offering a tentative opinion; he was making the most absolute declaration of identity possible in the language.",
      commentary: "Jesus asked His disciples the most important question in the Gospels: 'Whom say ye that I am?' People had opinions — some said John the Baptist, others Elijah or Jeremiah. But Jesus was not asking for a poll. He was asking for a confession. Peter answered: 'Thou art the Christ, the Son of the living God.'\n\nJesus' response affirmed both the confession and its source: 'Flesh and blood hath not revealed it unto thee, but my Father which is in heaven.' Peter did not arrive at this knowledge through logic, tradition, or social pressure. It came by revelation from the Father. This is the only way anyone truly knows that Jesus is the Messiah — through the witness of the Holy Spirit.\n\nJohn 6:68–69 records another, perhaps even more moving confession. After many disciples left because Jesus' teachings were too hard, He asked the Twelve: 'Will ye also go away?' Peter answered: 'Lord, to whom shall we go? thou hast the words of eternal life. And we believe and are sure that thou art that Christ, the Son of the living God.' The confession here is born not from triumphant insight but from loyalty tested by difficulty. Where else would we go? There is no alternative.\n\nActs 2:36 records Peter's Pentecost declaration to all Israel: 'God hath made that same Jesus, whom ye have crucified, both Lord and Christ.' The Messiah was not merely born — He was crucified, raised, and exalted. The cross and the empty tomb are the credentials of the Christ.\n\nD&C 46:13 teaches that knowing that Jesus Christ is the Son of God and was crucified for the sins of the world is a spiritual gift. Not everyone arrives at this knowledge in the same way or at the same time. But the gift is available to all who seek it sincerely.",
      patterns: "Confessions of Christ mark the turning points of every dispensation: Peter at Caesarea Philippi, the Nephites at the temple in Bountiful, Joseph Smith in the Sacred Grove, and every individual who kneels and says, 'Thou art the Christ.' The pattern is always the same: the question is asked, and faith gives the answer.",
      reflection: "Jesus asks you the same question He asked Peter: 'Whom say ye that I am?' After fifty weeks of study, how do you answer?"
    },
    {
      label: "The great and last sacrifice",
      focus: "The Messiah came not only to teach and reign but to offer Himself as the final sacrifice. Today examines how the messianic mission centers on the Atonement.",
      scriptures: [{book:"Alma",ch:34,vs:8,ve:14},{book:"Acts",ch:3,vs:18,ve:20},{book:"2 Ne",ch:25,vs:16,ve:20}],
      nuances: "Alma 34:10 says the Atonement must be 'an infinite and eternal sacrifice.' The word 'infinite' is used deliberately — not merely 'large' or 'comprehensive' but without limit. The sacrifice of the Messiah is infinite in scope (covering all people), infinite in time (reaching backward and forward across all history), and infinite in depth (addressing every degree of human suffering and sin).",
      commentary: "Amulek's teaching in Alma 34 is one of the clearest expositions of atonement theology in all scripture. The law of Moses, with its endless sacrifices of animals, was a type and shadow pointing forward to a great and last sacrifice. That sacrifice must not be of an animal but of a God — infinite and eternal. Without it, the entire plan of redemption is void.\n\nThis is why the Messiah is the center of everything. Without Him, there is no forgiveness, no resurrection, no hope. The sacrificial system of the law was never the solution — it was the pointer. The solution was always the Anointed One who would offer Himself willingly.\n\nActs 3:18–20 records Peter's teaching that God had shown by the mouth of all His prophets that Christ should suffer. The suffering Messiah was not a plan B; it was the plan from the beginning. Peter calls on his listeners to repent so that their sins may be blotted out when the times of refreshing come from the Lord's presence.\n\nNephi prophesied with perfect clarity in 2 Nephi 25:16–20: the Messiah would come six hundred years from the time Lehi left Jerusalem, and His name would be Jesus Christ, the Son of God. Nephi also predicted the rejection: the Jews would crucify their God, and after being scattered, they would eventually come to know the true Messiah. The prophecy is both heartbreaking and hopeful — rejection now, recognition later. God is patient.\n\nThe messianic title encompasses everything studied in Weeks 14 and 15 on the Atonement: the suffering in Gethsemane, the death on Calvary, the three days in the tomb, and the triumphant Resurrection. The Messiah's anointing was an anointing for sacrifice.",
      patterns: "Every sacrifice in every dispensation — from Abel's lamb to the temple offerings to the sacrament — points to the Messiah's one great sacrifice. The pattern of sacrifice is the deepest structure in scripture, and it leads always to Christ.",
      reflection: "Amulek called the Atonement 'the great and last sacrifice.' How does understanding it as the fulfillment of every previous sacrifice deepen your appreciation for what Christ did?"
    },
    {
      label: "That ye might believe",
      focus: "John wrote his Gospel so that readers 'might believe that Jesus is the Christ.' Today explores the purpose of testimony and the power of belief in the Messiah.",
      scriptures: [{book:"John",ch:20,vs:31},{book:"D&C",ch:18,vs:21,ve:25},{book:"D&C",ch:76,vs:1}],
      nuances: "John 20:31 states the purpose of his Gospel: 'These are written, that ye might believe that Jesus is the Christ, the Son of God; and that believing ye might have life through his name.' The Greek 'pisteusēte' (believe) is in the subjunctive mood — expressing purpose and desire. John's entire Gospel is not merely informational but persuasive; it exists to produce faith, and faith produces eternal life.",
      commentary: "John 20:31 is the thesis statement of the Fourth Gospel. Everything John wrote — every miracle, every discourse, every encounter — was selected to produce one result: belief that Jesus is the Christ. John did not aim for biographical completeness; he aimed for faith. The Gospel is a tool designed to change hearts.\n\nD&C 18:21–25 teaches that the Lord commands all people to repent and be baptized in the name of Jesus Christ. Verse 23 adds: 'Behold, Jesus Christ is the name which is given of the Father, and there is none other name given whereby man can be saved.' The messianic name is not merely a label — it is the mechanism of salvation. To believe in the Messiah is to access the power of His name.\n\nD&C 76:1 opens the great vision of the degrees of glory: 'Hear, O ye heavens, and give ear, O earth, and rejoice ye inhabitants thereof, for the Lord is God, and beside him there is no Savior.' There is no Savior besides the Messiah. The exclusivity is not narrow — it is clarifying. In a world of competing claims and countless philosophies, the gospel declares that there is one Anointed One, one path back to God, one name that saves.\n\nThis is what fifty weeks of study have been building toward: not merely knowledge about Christ but belief in Him. The intellectual content matters, but its purpose is relational. Every scripture, every commentary, every reflection has been aimed at deepening your faith in Jesus as the Messiah — the Anointed One who can save you, change you, and bring you home.",
      patterns: "The purpose of all scripture is stated explicitly in multiple places: to persuade people to believe in Christ (2 Nephi 25:26), to convince Jew and Gentile that Jesus is the Christ (Book of Mormon title page), and that they might have life through His name (John 20:31). All sacred text serves one mission.",
      reflection: "John wrote his Gospel to produce belief. Has this year of study deepened your belief? What passage or insight has been most transformative for you?"
    },
    {
      label: "He is the Messiah — now and forever",
      focus: "The final day of the final week. We look back across fifty weeks and forward to an eternal relationship with the Anointed One.",
      scriptures: [{book:"2 Ne",ch:25,vs:26},{book:"3 Ne",ch:11,vs:10,ve:11},{book:"D&C",ch:93,vs:1},{book:"Moro",ch:10,vs:32,ve:33}],
      nuances: "Moroni 10:32 — 'Come unto Christ, and be perfected in him' — uses the word 'perfected' in a way that differs from common usage. The underlying concept is completion, not flawlessness. To be perfected in Christ is to be made whole, to have nothing lacking. The Messiah does not demand perfection as a prerequisite; He provides it as a gift to those who come.",
      commentary: "We began this fifty-week journey with 2 Nephi 25:26: 'We talk of Christ, we rejoice in Christ, we preach Christ, we prophesy of Christ.' These words framed the entire study. Now, at the end, they take on deeper meaning. After exploring His identity, His roles, His covenants, His suffering, His glory, and His love, the declaration that we talk of Christ is no longer a motto — it is a way of life.\n\n3 Nephi 11:10–11 is the moment when the resurrected Messiah appeared to the Nephites and introduced Himself: 'I am Jesus Christ, whom the prophets testified shall come into the world. I have drunk out of that bitter cup which the Father hath given me, and have glorified the Father in taking upon me the sins of the world.' The Messiah identifies Himself by His suffering. His credentials are His wounds. His glory is inseparable from His sacrifice.\n\nD&C 93:1 promises: 'Every soul who forsaketh his sins and cometh unto me, and calleth on my name, and obeyeth my voice, and keepeth my commandments, shall see my face and know that I am.' The Messiah is not a historical figure sealed in ancient texts. He is a living Person who can be known, seen, and experienced by anyone who seeks Him with real intent.\n\nMoroni closes the Book of Mormon with an invitation that is also the perfect close to this year of study: come unto Christ, deny yourselves of all ungodliness, and love God with all your might, mind, and strength. Then His grace is sufficient, and you are perfected in Him. This is the promise of the Messiah: not that you must be perfect to come but that in coming, you are made complete.\n\nThe study ends here. The relationship does not. The Messiah who was prophesied for centuries, born in Bethlehem, anointed by the Spirit, crucified at Calvary, resurrected on the third day, and glorified at the Father's right hand is alive. He knows your name. He invites you to come. The Anointed One is not a topic to be finished — He is the beginning and the end, the first and the last, the Alpha and Omega. And He is yours, if you will have Him.",
      patterns: "The entire arc of fifty weeks forms one testimony: Jesus is the Christ, the Son of the living God. Every role, every title, every covenant, every prophecy converges on this Person. The study has been comprehensive, but the Person is inexhaustible. There is always more to know, more to receive, more to become through Him.",
      reflection: "This is the final reflection of the year. Sit with this question quietly: after fifty weeks of walking with the Messiah through scripture, who is He to you now? And what will you do about it?"
    }
  ]
};

export default week50;
