import type { WeekContent } from '../types';

const week44: WeekContent = {
  title: "Millennial Reign — The King Shall Reign in Righteousness",
  subtitle: "Christ will return to earth and reign personally for a thousand years of peace, justice, and glory.",
  weekScriptures: "Rev. 20:1–6; Isa. 11:1–9; D&C 101:22–34; 1 Ne. 22:24–26; D&C 29:11; D&C 45:55–59; Isa. 65:17–25; Zech. 14:9; 3 Ne. 21:23–25; D&C 43:29–33; Isa. 2:2–4; Micah 4:1–4; D&C 88:95–101; D&C 133:25; Acts 3:19–21; Ether 13:3–6; D&C 84:98–102; Ps. 72:1–11; Isa. 32:1; D&C 45:58",
  synthesis: {
    summary: "The millennial reign of Christ is not a metaphor — it is a literal, prophesied period when the Savior will personally govern the earth. Old Testament prophets, Book of Mormon seers, and modern revelation all describe a world transformed: Satan bound, death conquered for the righteous, the earth renewed, and Christ enthroned. The Millennium is the culmination of every covenant, the answer to every prayer for justice, and the fulfillment of every hope for peace.",
    connections: [
      "The Second Coming (Week 43) inaugurates the Millennium; the King's reign is what follows the King's arrival.",
      "Christ's role as Judge (Week 42) finds its fullest expression during the Millennium, when all governance flows from His perfect justice.",
      "The Davidic Descent studied in Week 46 is fulfilled here — the Son of David sits upon an everlasting throne."
    ],
    teaching: "The prophets describe the Millennium in terms of what will be absent (war, death, sorrow) and what will be present (knowledge of God, peace, unity). Which description matters most to you, and why?",
    commitment: "How can you live this week as though Christ's millennial peace were already breaking into the world through your choices?"
  },
  days: [
    {
      label: "Satan bound, Christ enthroned",
      focus: "The Millennium begins with a decisive act: Satan is bound and Christ takes His rightful throne. Today examines the opening conditions of the thousand years.",
      scriptures: [{book:"Rev",ch:20,vs:1,ve:6},{book:"1 Ne",ch:22,vs:24,ve:26},{book:"D&C",ch:29,vs:11}],
      nuances: "In Revelation 20:2, the 'binding' of Satan uses the Greek 'edēsen' — a strong, decisive action. Nephi adds a critical doctrinal clarification in 1 Nephi 22:26: Satan is bound because of the righteousness of the people, not merely by external force. The binding is both divine act and human condition — when people choose Christ, the adversary loses power.",
      commentary: "Revelation 20 describes the thousand-year reign in apocalyptic imagery: an angel descends with a great chain, binds the dragon, and seals him. Then those who were faithful to Christ reign with Him. This is not allegory in Latter-day Saint theology — it is prophecy of a literal future.\n\nNephi's insight in 1 Nephi 22 adds a dimension that many Christian traditions overlook: Satan is bound not only by divine decree but by the righteousness of God's people. When there is no audience for evil, the adversary has no stage. This principle operates even now — in homes, communities, and hearts where Christ is chosen, Satan's influence diminishes.\n\nD&C 29:11 affirms that Christ shall reign personally upon the earth. The word 'personally' is significant. This is not governance through proxies or abstract spiritual influence. The resurrected, glorified Christ will be present. For a world that has known Him only through faith, this will be the beginning of knowing Him by sight.",
      patterns: "The binding of Satan reverses the pattern of the Fall. In Eden, the adversary gained power through deception. In the Millennium, his power is removed through righteousness. The entire arc of human history — from Garden to Millennium — is a story of Christ reclaiming what was lost.",
      reflection: "Nephi teaches that Satan is bound when people choose righteousness. In what areas of your life could you contribute to 'binding' the adversary's influence right now?"
    },
    {
      label: "Peace among all creatures",
      focus: "Isaiah's vision of the Millennium includes not only human peace but the transformation of the natural world itself. Today we explore the scope of millennial renewal.",
      scriptures: [{book:"Isa",ch:11,vs:1,ve:9},{book:"Isa",ch:65,vs:17,ve:25},{book:"D&C",ch:101,vs:22,ve:34}],
      nuances: "Isaiah 11:6 describes the wolf dwelling with the lamb. The Hebrew 'gur' (dwell) implies more than coexistence — it means to sojourn together, to share life. Isaiah is describing a world where the predatory instinct itself is healed. This is not domestication; it is transformation at the deepest level of creation.",
      commentary: "Isaiah 11 paints one of the most beloved images in all scripture: the wolf and the lamb, the leopard and the kid, the child and the serpent, all at peace. A little child shall lead them. This is not poetic decoration — it is a prophecy about the renewal of the entire created order. The curse that fell upon the earth in Genesis 3 is reversed.\n\nIsaiah 65 adds further detail: no infant death, no premature aging, and the labor of human hands will not be in vain. The heartbreaks that define mortality — burying children, watching work destroyed, living in fear — will be gone. The earth itself will be different.\n\nD&C 101 provides Restoration-specific detail: the earth will be transfigured, enmity between humans and animals will cease, and whatever anyone asks in faith will be given. This is not heaven — it is earth, but earth as God always intended it to be. The Millennium is not an escape from creation but its fulfillment.",
      patterns: "The millennial renewal echoes the Garden of Eden. Isaiah's peaceable kingdom looks like Genesis 2 restored — harmony between humans, animals, and the earth. The plan of salvation is not linear but circular: it brings us home.",
      reflection: "Isaiah describes a world where even the natural order is at peace. What does this tell you about the depth and scope of what Christ's Atonement can heal?"
    },
    {
      label: "One King over all the earth",
      focus: "Multiple prophets declare that in the Millennium, there will be one Lord, one law, one governance. Today examines Christ's universal sovereignty.",
      scriptures: [{book:"Zech",ch:14,vs:9},{book:"Ps",ch:72,vs:1,ve:11},{book:"Isa",ch:32,vs:1},{book:"D&C",ch:45,vs:55,ve:59}],
      nuances: "Zechariah 14:9 declares 'the Lord shall be king over all the earth: in that day shall there be one Lord, and his name one.' The Hebrew 'echad' (one) is the same word used in the Shema of Deuteronomy 6:4. Zechariah is saying that the unity of God, long confessed in Israel's central prayer, will become the political and spiritual reality of the entire planet.",
      commentary: "Zechariah's prophecy is staggering in its simplicity: one Lord over all the earth. The fragmentation that has defined human history — nations against nations, religions against religions, ideologies against ideologies — will be resolved not by compromise but by the personal presence of the one true King.\n\nPsalm 72 describes this King's reign in terms of justice: He shall judge the poor, save the children of the needy, and break in pieces the oppressor. This is not abstract governance — it is advocacy for those who have been crushed by the world's power structures. Every injustice that has gone unanswered will be answered.\n\nIsaiah 32:1 adds that princes (subordinate rulers) shall also rule in judgment. D&C 45:55–59 describes the righteous who are gathered, including those who have not known Christ's law but who are taught during the Millennium. Christ's reign is not tyranny — it is perfect government, where every soul is known, taught, and loved.",
      patterns: "The many thrones and kingdoms of the world give way to one throne. This fulfills Daniel's vision of the stone cut without hands filling the whole earth (Daniel 2), studied in connection with the kingdom of God. All earthly kingdoms were temporary; Christ's is eternal.",
      reflection: "What would it mean for your daily decisions if you truly treated Christ as your King — not just your Savior, but your governing authority?"
    },
    {
      label: "Gathering and temple glory",
      focus: "The Millennium is an era of gathering, temple work, and the completion of covenants for all humanity. Today explores the sacred work of the thousand years.",
      scriptures: [{book:"3 Ne",ch:21,vs:23,ve:25},{book:"Isa",ch:2,vs:2,ve:4},{book:"Ether",ch:13,vs:3,ve:6},{book:"D&C",ch:133,vs:25}],
      nuances: "Isaiah 2:2 says 'the mountain of the Lord's house shall be established in the top of the mountains.' The Hebrew 'rosh heharim' (top of the mountains) can also mean 'chief among the mountains' — not geographically highest but preeminent in importance. The temple becomes the center of world civilization.",
      commentary: "Isaiah and Micah both prophesy that the mountain of the Lord's house will be exalted above the hills, and all nations will flow to it. This is temple-centered civilization — a world organized not around military power or economic exchange but around the house of God.\n\nEther 13 describes a New Jerusalem to be built upon the American continent, a holy city comparable to the Jerusalem of old. 3 Nephi 21 records Christ Himself declaring that the Father's covenant with Israel will be fulfilled and the New Jerusalem established. These are not speculative interpretations — they are direct declarations from the resurrected Lord.\n\nThe millennial temple work will be vast. Joseph Smith taught that the great work of the Millennium will include performing ordinances for the billions who have lived without them. D&C 133 describes scattered Israel gathered from the four quarters of the earth. Every covenant ever made with Abraham, Isaac, Jacob, and their posterity will reach completion. The Millennium is not merely a time of peace — it is the finishing of God's work.",
      patterns: "Temples have been central since Week 1 of this study — from the tabernacle to Solomon's temple to the Restoration temples. The Millennium represents the culmination: a world where temple blessings reach every soul who has ever lived.",
      reflection: "If the great work of the Millennium is completing temple ordinances for all of God's children, what does that tell you about the importance of temple worship now?"
    },
    {
      label: "Knowledge of God fills the earth",
      focus: "The Millennium is an age of revelation and knowledge. Today examines the promise that every soul will know the Lord.",
      scriptures: [{book:"Isa",ch:11,vs:9},{book:"D&C",ch:84,vs:98,ve:102},{book:"D&C",ch:101,vs:32,ve:34},{book:"Micah",ch:4,vs:1,ve:4}],
      nuances: "Isaiah 11:9 says the earth shall be 'full of the knowledge of the Lord, as the waters cover the sea.' The Hebrew 'de'ah' (knowledge) implies intimate, experiential knowing — not merely factual awareness. The image of water covering the sea suggests totality: there will be no pocket of the earth untouched by the knowledge of God.",
      commentary: "Isaiah's promise is breathtaking: every corner of the earth will be saturated with the knowledge of God. This is not religious education in the modern sense — it is the removal of spiritual blindness on a planetary scale. Every person will know the Lord, not by hearsay but by direct experience.\n\nD&C 101:32–34 adds stunning specificity: in the Millennium, God will reveal all things — the creation of the earth, the fall of man, and all things past, present, and future. Questions that have occupied theologians, scientists, and philosophers for millennia will be answered. The divide between sacred and secular knowledge will dissolve because all truth comes from one Source.\n\nD&C 84:98–102 describes a time when everyone will know the Lord from the least to the greatest. This echoes Jeremiah 31:34 and Hebrews 8:11. Micah adds that every person will sit under their own vine and fig tree — an image of security, sufficiency, and personal peace. Knowledge of God is not abstract in the Millennium; it produces tangible safety and abundance.",
      patterns: "Throughout this study, we have seen that knowing Christ is the purpose of all scripture (Week 1), all covenants (Week 9), and all ordinances (Week 22). The Millennium is when that knowing becomes universal and complete.",
      reflection: "D&C 101 promises that all hidden things will be revealed. What questions about God, the universe, or your own life do you most want answered?"
    },
    {
      label: "Death conquered, sorrow ended",
      focus: "During the Millennium, the righteous will be transformed — death will lose its power and sorrow its grip. Today explores the mortal conditions that will change.",
      scriptures: [{book:"D&C",ch:43,vs:29,ve:33},{book:"D&C",ch:45,vs:58},{book:"Isa",ch:65,vs:20,ve:22},{book:"D&C",ch:88,vs:95,ve:101}],
      nuances: "D&C 45:58 says that those born during the Millennium 'shall grow up without sin unto salvation.' The phrase 'without sin' does not mean without agency — it means without the pervasive influence of Satan that makes mortality so difficult. Children will still choose, but they will choose in a world saturated with light.",
      commentary: "One of the most remarkable promises about the Millennium concerns death itself. D&C 43 and 45 teach that children born during this time will grow up unto salvation, and when they reach old age, they will not die in the traditional sense but will be changed 'in the twinkling of an eye.' There will be no graves, no mourning, no funerals as we know them.\n\nIsaiah 65:20 describes a world where dying at a hundred years old would be considered premature — suggesting lifespans comparable to the antediluvian patriarchs. The sting of death, which has haunted humanity since Adam, will be removed.\n\nD&C 88:95–101 describes the sequence of resurrections that accompanies the Millennium. The righteous dead are raised first, then others at appointed times. The Millennium is not static — it is a dynamic period of ongoing resurrection, restoration, and revelation. The great reunion of the living and the dead begins.\n\nFor those who have buried loved ones, who have felt the crushing weight of grief, the millennial promise is personal: death will not have the final word. Christ's conquest of the grave, accomplished at Gethsemane and Golgotha (Weeks 14–15), reaches its full effect in the Millennium.",
      patterns: "Christ conquered death through His own Resurrection (Week 16). The Millennium is the large-scale application of that personal victory — what He accomplished alone, He extends to all creation.",
      reflection: "How does the promise that death and sorrow will be conquered during the Millennium shape the way you face grief and loss in the present?"
    },
    {
      label: "The earth restored to paradisiacal glory",
      focus: "The tenth Article of Faith declares that 'the earth will be renewed and receive its paradisiacal glory.' Today we explore what that means and why it matters.",
      scriptures: [{book:"D&C",ch:88,vs:17,ve:20},{book:"Acts",ch:3,vs:19,ve:21},{book:"D&C",ch:101,vs:23,ve:26},{book:"Isa",ch:65,vs:17}],
      nuances: "Acts 3:21 speaks of the 'restitution of all things.' The Greek 'apokatastasis panton' means a comprehensive restoration — not a partial repair but a complete return to an original state. Peter is teaching that the Millennium represents the fulfillment of everything God has ever spoken through His prophets since the world began.",
      commentary: "D&C 88:17–20 contains one of the most profound statements in all Restoration scripture: the earth abides the law of a celestial kingdom and will be sanctified, quickened, and crowned with glory. The earth is not disposable — it has a destiny. It will become the celestial kingdom for those who inherit it.\n\nPeter's sermon in Acts 3 describes the Millennium as the 'times of restitution of all things.' The word 'restitution' implies that something was lost and will be returned. What was lost? The paradisiacal state of Eden — the world as God created it before the Fall introduced thorns, death, and entropy.\n\nIsaiah 65:17 promises new heavens and a new earth. D&C 101 adds that the Lord will be in the midst of His people and will be their king and their lawgiver. The veil between heaven and earth — the barrier that makes faith so difficult and revelation so rare — will thin dramatically during the Millennium.\n\nThis is the answer to the whole plan. Creation, Fall, Atonement, and Restoration are not disconnected events but chapters in a single story that culminates here: God dwelling with His people on a glorified earth.",
      patterns: "The arc of the entire fifty-week study is visible here. From the identity of Christ (Week 1) through His Atonement, Resurrection, and roles as Prophet, Priest, and King, every truth converges on this: He is bringing everything home. The Millennium is not the end — it is the beginning of eternity.",
      reflection: "If the earth itself has a destiny and a glory, what does that teach you about how God views the physical, material world — including your body and the world around you?"
    }
  ]
};

export default week44;
