import type { WeekContent } from '../types';

const week07: WeekContent = {
  title: "Foreordained & Firstborn — Chosen Before the World Was",
  subtitle: "Christ was the Firstborn of the Father in the spirit and was foreordained to be the Redeemer before the foundations of the earth were laid.",
  weekScriptures: "Abr 3:22–28; Moses 4:1–4; Rev 13:8; 1 Pet 1:18–20; Eph 1:3–5; Rom 8:29; Col 1:15–18; D&C 93:21–23; D&C 138:55–56; Alma 13:1–9; Jer 1:4–5; Isa 49:1–6; 2 Ne 9:5–9; John 15:16; Heb 5:4–5; Acts 2:23; Ether 3:14",
  synthesis: {
    summary: "Before the earth was formed, Christ held a unique status: He was the Firstborn of the Father in the spirit, preeminent among all God's children, and foreordained to be the Redeemer. The premortal council in heaven established the plan of salvation, and Christ's voluntary acceptance of the role of Savior was the hinge on which all of human history would turn. Understanding His foreordination reveals that the Atonement was not a contingency plan but the central purpose of creation from the beginning.",
    connections: [
      "Week 5 (Appearances, Antemortal) showed Christ appearing to prophets before His birth; this week explains the premortal identity that made those appearances possible.",
      "Week 6 (Creator) showed Christ creating worlds; this week reveals that His creative work was part of a larger foreordained plan of redemption.",
      "Week 8 (Jehovah) will show how Christ's premortal identity as the Firstborn manifested as the God of the Old Testament."
    ],
    teaching: "If Christ was foreordained to be the Redeemer, does that diminish the significance of His choice in Gethsemane? How does foreordination relate to agency?",
    commitment: "Reflect this week on your own premortal identity. If prophets were foreordained to their callings (D&C 138, Alma 13), what might God have prepared you to do?"
  },
  days: [
    {
      label: "The premortal council",
      focus: "Before the earth was formed, a great council was held in heaven. Today examines the moment Christ volunteered to be the Redeemer — and the alternative that was rejected.",
      scriptures: [{book:"Abr",ch:3,vs:22,ve:28},{book:"Moses",ch:4,vs:1,ve:4},{book:"Rev",ch:13,vs:8}],
      nuances: "In Abraham 3:27, the one 'like unto God' says 'Here am I, send me.' This echoes Isaiah 6:8, where Isaiah responds to God's call with the same words. The parallel is theologically rich: Christ's response in the premortal council is the model for every prophet's response to divine commission. The phrase 'send me' also anticipates the title 'Apostle' (Greek 'apostolos' — one who is sent), which Hebrews 3:1 applies directly to Christ.",
      commentary: "Abraham 3:22–28 opens a window into the premortal existence that is found nowhere in the Bible. Abraham is shown the intelligences organized before the world was, and among them 'one that was like unto God' — this is the premortal Christ. The Father presents His plan, and two voices respond. The first says, 'Here am I, send me' and offers to preserve the Father's honor and the agency of His children. The second — identified in Moses 4:1–4 as Lucifer — proposes an alternative: compulsion without risk, salvation without agency.\n\nThe difference between the two proposals is not merely tactical but moral. Christ's plan preserves the fundamental dignity of God's children by allowing them to choose. Lucifer's plan treats them as objects to be managed. The Father chose Christ's plan because it alone honored both justice and mercy while preserving the agency essential to genuine moral growth.\n\nRevelation 13:8 adds a crucial detail: Christ is described as 'the Lamb slain from the foundation of the world.' Before the earth existed, the Atonement was already determined. This means the suffering of Gethsemane and Calvary was not an emergency response to sin but the planned center of all of salvation history. The creation itself was built around the Atonement, not the other way around.",
      patterns: "Christ's 'Here am I, send me' in Abraham 3:27 connects to Isaiah's identical response in Isaiah 6:8 (Week 5, Day 5). The pattern of voluntary descent — God choosing to come down — begins in the premortal council and culminates in the Incarnation (Week 1) and the Atonement (Weeks 12–13). Every act of divine condescension follows from this first premortal choice.",
      reflection: "Christ chose a plan that preserved agency even though it guaranteed suffering — His own and ours. What does His willingness to choose this harder path tell you about how He views your freedom?"
    },
    {
      label: "The Firstborn of the Father",
      focus: "Christ's title as the 'Firstborn' is not merely honorific — it carries profound theological weight. Today examines what it means for Christ to be first among all of God's spirit children.",
      scriptures: [{book:"Col",ch:1,vs:15,ve:18},{book:"D&C",ch:93,vs:21,ve:23},{book:"Rom",ch:8,vs:29},{book:"Heb",ch:1,vs:5,ve:6}],
      nuances: "The Greek 'prototokos' (firstborn) in Colossians 1:15 has generated centuries of debate. Arians argued it meant Christ was a created being; Nicene theologians countered that 'firstborn' denotes rank and preeminence, not mere chronological origin. Latter-day Saint theology affirms both dimensions: Christ is literally the first spirit child of the Father (D&C 93:21) and holds preeminence over all creation by right of that status and His divine nature.",
      commentary: "Colossians 1:15 calls Christ 'the firstborn of every creature,' and verse 18 adds that He is 'the firstborn from the dead; that in all things he might have the preeminence.' The title 'Firstborn' carries both chronological and covenantal meaning. In ancient Israelite culture, the firstborn son received a double portion of the inheritance and carried the family name forward. Christ, as the Firstborn, holds the rights of the Father's household.\n\nD&C 93:21–23 provides distinctively Restoration context: 'I was in the beginning with the Father, and am the Firstborn.' This is Christ speaking directly, confirming His identity as the first among the Father's spirit children. Verse 23 extends the principle: 'Ye were also in the beginning with the Father; that which is Spirit, even the Spirit of truth.' All human beings existed premortally — but Christ was first.\n\nRomans 8:29 adds that God foreordained the faithful to be 'conformed to the image of his Son, that he might be the firstborn among many brethren.' The Firstborn is not separate from the rest of the family — He is the eldest brother, and the purpose of the plan is to bring the entire family to share in His glory. Christ's status as Firstborn is not about distance but about leading the way.",
      patterns: "The 'Firstborn' title connects to Week 6 (Creator): because He was first, He had the authority and capacity to create. It also foreshadows the Atonement — the Firstborn's double portion is not wealth but suffering, taken upon Himself so that His younger siblings might inherit eternal life. This 'elder brother' motif returns in Weeks 12–13 and 34.",
      reflection: "Romans 8:29 says God's purpose is to conform you to the image of His Firstborn Son. What aspect of Christ's character do you most want to grow into this week?"
    },
    {
      label: "Foreordained as Redeemer",
      focus: "The Atonement was planned before the world was. Today explores the doctrine of Christ's foreordination — not as a limitation of His agency but as an expression of His character.",
      scriptures: [{book:"1 Pet",ch:1,vs:18,ve:20},{book:"Acts",ch:2,vs:23},{book:"Ether",ch:3,vs:14},{book:"2 Ne",ch:9,vs:5,ve:9}],
      nuances: "1 Peter 1:20 says Christ was 'foreordained before the foundation of the world.' The Greek 'proegnosmenou' (foreknown) carries the connotation of both knowledge and relational intimacy — God did not merely foresee Christ's mission; He chose Him with full knowledge of who He was. Acts 2:23 uses 'boule' (counsel/deliberate plan) — Peter is telling Jerusalem that the crucifixion was not a tragedy that escaped God's control but the execution of a divine plan determined in advance.",
      commentary: "Peter makes two stunning claims. First, that Christ was foreordained as the Redeemer before the foundation of the world (1 Peter 1:20). Second, that the crucifixion happened 'by the determinate counsel and foreknowledge of God' (Acts 2:23). Taken together, these verses teach that the cross was not an accident or a defeat — it was the purpose for which Christ came.\n\nEther 3:14 records Christ's own declaration to the brother of Jared: 'I am he who was prepared from the foundation of the world to redeem my people.' The word 'prepared' is significant — it suggests not mere willingness but readiness, a being whose entire premortal existence was oriented toward this one redemptive act.\n\n2 Nephi 9:5–9, Jacob's great sermon on the Atonement, explains why foreordination was necessary. Without an 'infinite atonement,' the Fall would have produced permanent spiritual and physical death. The bodies and spirits of all humanity would have become subject to the devil. The Atonement had to be planned from the beginning because without it, the entire purpose of creation would fail. Foreordination is not about determinism — it is about the seriousness of the problem and the certainty of the solution.",
      patterns: "Christ's foreordination connects creation (Week 6) to redemption: the world was made in order that the Atonement might take place. This week's emphasis on premortal planning prepares for the detailed study of the Atonement in Weeks 12–13, where the plan foreordained before the world becomes an event in time.",
      reflection: "If the Atonement was planned before the world was created, what does that tell you about how seriously God takes your salvation? Is there any part of your life you have assumed is beyond His reach?"
    },
    {
      label: "Foreordination of prophets and Saints",
      focus: "Christ was not the only one foreordained. Today examines the doctrine that prophets and faithful Saints were also appointed to their roles before birth — and what this means for your own life.",
      scriptures: [{book:"Alma",ch:13,vs:1,ve:9},{book:"Jer",ch:1,vs:4,ve:5},{book:"D&C",ch:138,vs:55,ve:56},{book:"Eph",ch:1,vs:3,ve:5}],
      nuances: "Alma 13:3 teaches that priests were 'called and prepared from the foundation of the world according to the foreknowledge of God, on account of their exceeding faith and good works.' The phrase 'on account of' is significant: foreordination was not arbitrary but based on demonstrated character. This implies that choices made in the premortal life had consequences — moral development did not begin at birth.",
      commentary: "Alma 13 contains the most detailed discussion of foreordination in the Book of Mormon. High priests were 'ordained after the order of the Son, from the foundation of the world' because of their 'exceeding faith and good works' in the premortal existence. This is a remarkable doctrine: before they were born, certain individuals had already demonstrated the spiritual capacity that would qualify them for their earthly callings.\n\nJeremiah 1:4–5 provides a biblical parallel: 'Before I formed thee in the belly I knew thee; and before thou camest forth out of the womb I sanctified thee, and I ordained thee a prophet unto the nations.' The Hebrew 'yada' (knew) implies intimate, personal knowledge — God's relationship with Jeremiah preceded his birth.\n\nD&C 138:55–56, from President Joseph F. Smith's vision of the redemption of the dead, expands the principle further: 'I observed that they were also among the noble and great ones who were chosen in the beginning to be rulers in the Church of God.' Joseph Smith, Hyrum Smith, Brigham Young, and others are identified as foreordained to their specific missions. Ephesians 1:3–5 universalizes this: God 'hath chosen us in him before the foundation of the world.' Foreordination is not only for prophets — it extends to every faithful soul.",
      patterns: "The foreordination of prophets connects to Week 1's principle that all prophets testified of Christ — they did so not merely because they learned about Him but because many knew Him personally in the premortal world. It also connects to Week 5 (Antemortal Appearances): prophets who saw Christ before His birth may have known Him before their own births.",
      reflection: "If you were among the spirits who shouted for joy at the plan of salvation (Job 38:7), what might God have prepared you to do in this life? What promptings or persistent desires might be echoes of a premortal calling?"
    },
    {
      label: "Chosen, not forced",
      focus: "Foreordination does not eliminate agency. Today explores the crucial distinction between being foreordained and being predestined, and how Christ's own choice exemplifies the principle.",
      scriptures: [{book:"John",ch:15,vs:16},{book:"Heb",ch:5,vs:4,ve:5},{book:"Abr",ch:3,vs:22,ve:23},{book:"Alma",ch:13,vs:4,ve:5}],
      nuances: "In John 15:16, Jesus tells His apostles, 'Ye have not chosen me, but I have chosen you, and ordained you.' The Greek 'exelexamen' (chose) is a deliberate act of selection. Yet this divine choosing does not override human response — Judas, who was among those chosen, still exercised his agency to betray. Foreordination sets the stage; agency determines the outcome.",
      commentary: "One of the most important distinctions in Latter-day Saint theology is the difference between foreordination and predestination. Predestination, as taught by some Reformation theologians, holds that God unilaterally determines who will be saved and who will not, with no meaningful human choice involved. Foreordination, by contrast, is a divine appointment that requires human faithfulness to be fulfilled. It is an opportunity, not a guarantee.\n\nAlma 13:4–5 makes this explicit: those foreordained to the priesthood were 'left to choose good or evil.' Their foreordination did not eliminate their agency — it was based on their agency, specifically the 'exceeding faith and good works' they exhibited premortally. And even after being called, they could still reject the call. Alma 13:4 notes that some 'would reject the Spirit of God on account of the hardness of their hearts.'\n\nHebrews 5:4–5 applies this principle to Christ Himself: 'No man taketh this honour unto himself, but he that is called of God, as was Aaron. So also Christ glorified not himself to be made an high priest; but he that said unto him, Thou art my Son.' Christ was chosen by the Father — but He also chose to accept. His foreordination and His agency worked together, not against each other. This is the model for every foreordained calling: God appoints, and we respond.",
      patterns: "The relationship between foreordination and agency is central to the Plan of Salvation and will recur throughout the year. It connects to Week 12 (Gethsemane), where Christ's foreordained mission meets His agonizing personal choice: 'Not my will, but thine, be done.' Foreordination made the Atonement planned; agency made it a genuine sacrifice.",
      reflection: "Have you ever felt a sense of spiritual calling or purpose that seemed to precede your conscious choosing? How might the doctrine of foreordination help you understand that feeling?"
    },
    {
      label: "The Servant chosen from the womb",
      focus: "Isaiah's Servant Songs describe a figure chosen before birth for a redemptive mission. Today reads these prophecies as descriptions of the foreordained Christ.",
      scriptures: [{book:"Isa",ch:49,vs:1,ve:6},{book:"Isa",ch:42,vs:1,ve:4},{book:"1 Ne",ch:21,vs:1,ve:6},{book:"Mosiah",ch:15,vs:1,ve:4}],
      nuances: "Isaiah 49:1 states, 'The Lord hath called me from the womb; from the bowels of my mother hath he made mention of my name.' The Hebrew 'mibbeten' (from the womb) and 'mimme'ei immi' (from the inward parts of my mother) emphasize that this calling preceded birth. While some scholars read this as referring to Isaiah or the nation of Israel, the messianic application — confirmed by the New Testament and Book of Mormon — sees this as a prophecy of the foreordained Christ.",
      commentary: "Isaiah's Servant Songs (Isaiah 42, 49, 50, 52–53) are among the most christologically rich passages in the Old Testament. Isaiah 49:1–6 describes a servant called from the womb, named before birth, and given a mission that extends beyond Israel to be 'a light to the Gentiles' and bring salvation 'unto the end of the earth.' The scope of the mission — universal, not merely national — points beyond any individual prophet to the Messiah.\n\nIsaiah 42:1–4 adds detail to the portrait: this chosen servant will not cry out in the streets, will not break a bruised reed or quench smoking flax. The Messiah's power is expressed in gentleness, not force. He is foreordained not to a mission of conquest but of compassion.\n\n1 Nephi 21 reproduces Isaiah 49 in the Book of Mormon, and Nephi applies it directly to Christ and His covenant with Israel. Mosiah 15:1–4 then makes one of the most profound christological statements in scripture: the Messiah is both Father and Son — Father because He was 'conceived by the power of God' and Son because of His mortal flesh. Abinadi is describing a being whose dual nature was part of the foreordained plan from the beginning. He was chosen to be the unique bridge between divinity and mortality.",
      patterns: "Isaiah's Servant Songs connect to multiple weeks in this plan: the suffering servant of Isaiah 53 will be central to Weeks 12–13 (Atonement), the light-to-the-Gentiles theme connects to Week 24 (Testimony of Christ), and the servant called from the womb ties directly to this week's foreordination theme. Abinadi's teaching in Mosiah 15 also prepares for Week 8 (Jehovah) and the question of Christ's divine identity.",
      reflection: "Isaiah describes the foreordained Servant as one who would not break a bruised reed. How does the gentleness of Christ's foreordained mission affect how you approach Him with your own brokenness?"
    },
    {
      label: "From before the world to within it",
      focus: "Drawing the week together: the arc from premortal council to mortal birth. Christ's foreordination finds its fulfillment when the Firstborn enters the world as an infant.",
      scriptures: [{book:"Moses",ch:4,vs:1,ve:2},{book:"Gal",ch:4,vs:4,ve:5},{book:"D&C",ch:93,vs:21},{book:"Luke",ch:2,vs:10,ve:14}],
      nuances: "Galatians 4:4 says 'when the fulness of the time was come, God sent forth his Son, made of a woman, made under the law.' The Greek 'pleroma tou chronou' (fullness of time) implies that history itself was moving toward a predetermined moment. The Incarnation was not random — it occurred at precisely the right time in God's eternal plan. 'Made of a woman' (genomenon ek gunaikos) emphasizes that the premortal Firstborn genuinely became mortal.",
      commentary: "This week has traced an arc from eternity to time. In the premortal council, Christ was the Firstborn, preeminent among the Father's spirit children (D&C 93:21). He volunteered to be the Redeemer (Moses 4:1–2). He was foreordained before the foundation of the world (1 Peter 1:20). And then — in the fullness of time — He came.\n\nGalatians 4:4–5 captures this transition with elegant brevity: 'God sent forth his Son, made of a woman, made under the law, to redeem them that were under the law, that we might receive the adoption of sons.' The Firstborn became an infant. The Creator submitted to the laws of His own creation. The one foreordained to save the world entered it in the most vulnerable way imaginable — as a baby born in a borrowed stable.\n\nLuke 2:10–14 records the angelic announcement: 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.' The angels knew what the shepherds could not yet comprehend: this infant was the same being who had stood in the premortal council, created the earth, and been foreordained from before the foundation of the world. The entire plan — from the council in heaven to the manger in Bethlehem — was one seamless act of divine love.\n\nAs we close this week, consider the staggering humility of the Firstborn. He who was first in rank chose to descend to the lowest place. He who was foreordained as Redeemer embraced that calling not with the triumphalism of a conqueror but with the vulnerability of a newborn child.",
      patterns: "This day bridges the premortal weeks (5–8) to the mortal weeks that will follow. The Firstborn's entry into mortality leads directly to Week 8 (Jehovah — Christ's identity as the God of the Old Testament), and forward to the mortal ministry, Atonement, and Resurrection studied in later weeks. The entire plan unfolds from what was set in motion before the world was.",
      reflection: "The Firstborn of the Father chose to enter the world as the most helpless of all creatures — a newborn. What does this teach you about the kind of God you worship, and the kind of greatness He values?"
    }
  ]
};

export default week07;
