import type { WeekContent } from '../types';

const week04: WeekContent = {
  title: "Antemortal Existence of Christ",
  subtitle: "Before Bethlehem, before Genesis \u2014 who was Jesus Christ in the pre-mortal world?",
  weekScriptures: "John 1:1\u20133; John 17:5; D&C 93:7\u201310; 1 Pet. 1:19\u201320; Rev. 13:8; Moses 4:1\u20132; Abr. 3:22\u201328; D&C 29:36\u201338; Isa. 14:12\u201314; Heb. 1:1\u20133; Col. 1:16\u201317; Moses 1:33; Alma 13:3\u20135; Jer. 1:5; D&C 138:55\u201356; Abr. 3:24\u201326; 2 Ne. 2:25; D&C 93:29\u201333; Philip. 2:5\u20138; John 6:38; 3 Ne. 1:14",
  synthesis: {
    summary: "Jesus Christ did not begin at Bethlehem. He existed as a spirit being \u2014 Jehovah, the Firstborn \u2014 before the foundation of the world. He participated in creation, presented the Father\u2019s plan, and was chosen as the Redeemer before any of us were born.",
    connections: [
      "Week 5 (Appearances, Antemortal) builds directly on this \u2014 having established His pre-mortal existence, we see how He appeared to prophets before His birth.",
      "Week 7 (Foreordained & Firstborn) expands on His status among the Father\u2019s children.",
      "Week 6 (Creator) is grounded in the truth taught this week: He was the active agent of creation before becoming mortal."
    ],
    teaching: "Why does it matter that Christ existed before His mortal life? What doctrines depend on this truth?",
    commitment: "How does knowing that Christ chose His mission \u2014 before the world began \u2014 affect the way you trust Him with your life?"
  },
  days: [
    {
      label: "In the beginning with God",
      focus: "We start where eternity starts: Christ\u2019s existence \u2018before the world was.\u2019 Today establishes the pre-mortal reality through three witnesses.",
      scriptures: [{book:"John",ch:1,vs:1,ve:3},{book:"John",ch:17,vs:5},{book:"D&C",ch:93,vs:7,ve:10}],
      nuances: "In John 17:5, Jesus prays for the glory He had \u2018with thee before the world was.\u2019 The Greek \u2018para soi\u2019 means \u2018alongside you\u2019 or \u2018in your presence\u2019 \u2014 implying personal relationship, not mere coexistence. He had glory with the Father, in the Father\u2019s presence, before creation. This is relational preexistence, not abstract eternity.",
      commentary: "John 1 states that the Word was in the beginning with God, and the Word was God. This is not a late theological development \u2014 it is how the earliest Christian witness chose to open the story of Jesus.\n\nJohn 17:5 is Christ\u2019s own testimony, spoken in prayer the night before His crucifixion. He asks the Father to restore the glory they shared before the world existed. This is not a doctrinal claim by an apostle \u2014 it is a personal memory spoken by Christ Himself.\n\nD&C 93:7\u201310 (from what Joseph Smith called \u2018the record of John\u2019) adds that Christ was in the beginning with the Father, that He was the Word, the messenger of salvation. Restoration scripture takes John\u2019s testimony and expands it, providing detail about the pre-mortal Christ that the biblical text only gestures toward.\n\nAcross broader Christianity, Christ\u2019s preexistence is affirmed in the Nicene Creed (\u2018begotten of the Father before all worlds\u2019) and has been the consensus of orthodox theology for nearly two millennia. Restoration theology agrees but adds a specific narrative: He was not only preexistent but personally known, followed, and chosen in a council of spirits.",
      patterns: "Scripture uses \u2018in the beginning\u2019 as a timestamp for Christ\u2019s pre-mortal existence. This phrase appears in John 1, D&C 93, and Abraham 3 \u2014 a marker worth noticing whenever it appears.",
      reflection: "If Christ existed before the world, then your relationship with Him is older than you realize. How does that affect the way you pray to the Father in His name?"
    },
    {
      label: "Chosen before the foundation",
      focus: "His sacrifice was not a reaction to the Fall. It was the plan from before the beginning. Today examines the evidence.",
      scriptures: [{book:"1 Pet",ch:1,vs:19,ve:20},{book:"Rev",ch:13,vs:8},{book:"Moses",ch:4,vs:1,ve:2}],
      nuances: "\u2018Foreordained\u2019 in 1 Peter 1:20 translates the Greek \u2018proegnosmenou\u2019 \u2014 literally \u2018known beforehand.\u2019 Many modern translations render this \u2018foreknown\u2019 or \u2018chosen beforehand.\u2019 The Greek conveys deliberate prior designation, not mere anticipation. In Revelation 13:8, some translations attach \u2018from the foundation of the world\u2019 to the writing of names in the book of life rather than to the Lamb. Either way, the theological point stands: Christ\u2019s redemptive role was eternal in scope.",
      commentary: "Peter writes that Christ was foreordained before the foundation of the world. Revelation refers to the Lamb slain from the foundation of the world \u2014 His sacrifice was planned before mortality began.\n\nMoses 4:1\u20132 records the actual moment of choice: the Father asked who should be sent, and Jesus responded, \u2018Here am I, send me.\u2019 He then added, \u2018Father, thy will be done, and the glory be thine forever.\u2019 This is not just willingness \u2014 it is willing subordination to the Father\u2019s plan and glory.\n\nThe pre-mortal council is one of the most important doctrinal events in Restoration scripture. It establishes that the Atonement was not Plan B \u2014 it was always the plan. God did not create the world, watch it fail, and then improvise a rescue. The rescue was designed before the world was made.\n\nClassical Christian theology affirms the eternal nature of God\u2019s redemptive purpose (Ephesians 1:4, 2 Timothy 1:9) but generally does not develop the council narrative found in Restoration scripture. The Pearl of Great Price provides a dramatic, specific account that enriches the biblical data.",
      patterns: "The pre-mortal council establishes a principle that governs everything: the Atonement was always the plan. God\u2019s purposes are not reactive.",
      reflection: "Knowing that Christ volunteered for everything He endured \u2014 that He chose it before you were born \u2014 how does that change the weight you give to His suffering?"
    },
    {
      label: "The pre-mortal council",
      focus: "Two plans, two proposers, one choice. Today examines the council where the fate of humanity was decided.",
      scriptures: [{book:"Abr",ch:3,vs:22,ve:28},{book:"D&C",ch:29,vs:36,ve:38},{book:"Isa",ch:14,vs:12,ve:14}],
      nuances: "In Abraham 3:24, \u2018We will go down\u2019 uses the first-person plural \u2014 implying that creation was collaborative under divine direction. The Hebrew behind Isaiah 14:12\u2019s \u2018Lucifer\u2019 is \u2018helel ben shachar\u2019 \u2014 \u2018shining one, son of the dawn.\u2019 The name itself implies a being of light who fell. The Latin \u2018Lucifer\u2019 (light-bearer) entered English through the Vulgate and KJV.",
      commentary: "Abraham 3 provides the clearest view of the pre-mortal council in any scripture. Among the intelligences, one was \u2018like unto God\u2019 and said: \u2018We will go down, for there is space there, and we will take of these materials, and we will make an earth whereon these may dwell.\u2019 This is not myth \u2014 it is Restoration scripture\u2019s account of how the plan of salvation was set in motion.\n\nD&C 29:36\u201338 describes the rebellion: Lucifer, an angel with authority in God\u2019s presence, rebelled and sought to destroy the agency of man. He and a third of the host of heaven were cast out. Isaiah 14:12\u201314 gives the prophetic poetic account of that fall: \u2018I will ascend above the heights of the clouds; I will be like the most High.\u2019\n\nThe dividing line of the council was agency. Christ honored it; Lucifer sought to destroy it. This is not a minor detail \u2014 it is the defining principle. Every doctrine about Christ\u2019s mission must be understood through this lens: He will save, but He will not force. Compulsion is the adversary\u2019s method, not God\u2019s.\n\nBroader Christian theology generally acknowledges a pre-mortal fall of Satan but does not develop the council narrative in the way Restoration scripture does. The unique contribution here is the contrast between two proposed plans \u2014 one preserving agency, one destroying it \u2014 and the pre-mortal exercise of agency by all who chose to follow Christ.",
      patterns: "Agency is the dividing line of the council. Christ honored it; Lucifer sought to destroy it. Every act of coercion, manipulation, or forced righteousness echoes the wrong side of the council.",
      reflection: "In your own life, are you following Christ\u2019s model of respecting agency \u2014 or are you tempted to force outcomes in your relationships or responsibilities?"
    },
    {
      label: "Creator before mortal",
      focus: "Before He was born in a manger, He built the universe. Today examines Christ\u2019s role as the active agent of creation.",
      scriptures: [{book:"Heb",ch:1,vs:1,ve:3},{book:"Col",ch:1,vs:16,ve:17},{book:"Moses",ch:1,vs:33}],
      nuances: "Hebrews 1:3 says the Son is \u2018the brightness of his glory, and the express image of his person.\u2019 The Greek \u2018charakt\u0113r t\u0113s hupostase\u014ds\u2019 is precise: \u2018charakt\u0113r\u2019 means an exact imprint (like a stamp in wax), and \u2018hupostasis\u2019 means underlying reality or substance. The Son is not a dim reflection of the Father; He is the precise imprint of the Father\u2019s very being.",
      commentary: "Hebrews 1 says God made the worlds through His Son. Colossians 1 says by Him were all things created, in heaven and in earth, visible and invisible. Moses 1:33 adds the Restoration\u2019s cosmic scope: \u2018Worlds without number have I created; and I also created them for mine own purpose; and by the Son I created them.\u2019\n\nBefore He was born in a manger, He built the universe. The Being who formed galaxies, who designed the laws of physics, who spoke light into existence \u2014 chose to enter His own creation as a helpless infant. This is the scale of the condescension.\n\nCreation is not a separate topic from Christology \u2014 it is a Christ-topic. The Creator became the Redeemer. The one who made the world entered it to save it. This will be the full focus of Week 6.\n\nIn broader Christian theology, the doctrine of creation through Christ (sometimes called \u2018Christological creation\u2019) is well-attested in the New Testament and was central to early Church councils. Restoration scripture expands the scale: not one world but worlds without number, all created through the Son.",
      patterns: "Creation through Christ is affirmed in the New Testament, the Pearl of Great Price, and the Doctrine and Covenants. The Creator became the Redeemer \u2014 a pattern that makes both doctrines richer.",
      reflection: "The Being who created galaxies also created you. What does that say about your worth?"
    },
    {
      label: "Known to the Father\u2019s children",
      focus: "Pre-mortal life was not passive. Today examines the evidence that spirits exercised faith, made choices, and followed Christ before birth.",
      scriptures: [{book:"Alma",ch:13,vs:3,ve:5},{book:"Jer",ch:1,vs:5},{book:"D&C",ch:138,vs:55,ve:56}],
      nuances: "In Jeremiah 1:5, \u2018Before I formed thee in the belly I knew thee\u2019 \u2014 the Hebrew \u2018yada\u2019 means deep, intimate knowledge, not just awareness. God did not merely know about Jeremiah; He knew him personally. The same verb is used of the covenant relationship between God and Israel. This suggests that pre-mortal relationships had depth and substance.",
      commentary: "Alma 13 teaches that priests were foreordained according to the foreknowledge of God, on account of their exceeding faith and good works in a pre-mortal state. This is a remarkable claim: assignments in mortality were influenced by choices made before birth.\n\nJeremiah was told: before I formed thee in the belly I knew thee, and before thou camest forth out of the womb I sanctified thee. This is a direct Old Testament witness of pre-mortal identity and divine foreknowledge.\n\nD&C 138 (Joseph F. Smith\u2019s vision of the spirit world) lists specific individuals among the \u2018noble and great ones\u2019 in the pre-mortal life: Adam, Eve, Abraham, Isaac, Jacob, Moses, Isaiah, Ezekiel, Daniel, and others. Christ was the leader of that pre-mortal community \u2014 known, followed, and trusted by all who would come to earth.\n\nThe doctrine of pre-mortal existence is distinctive to Restoration theology. Classical Christianity generally does not teach that human spirits existed before conception (the early theologian Origen taught it but was later condemned). The biblical evidence (Jeremiah 1:5, Ecclesiastes 12:7, John 9:2) is suggestive but not conclusive without Restoration scripture to clarify it.",
      patterns: "Pre-mortal life was not passive. Choices were made, faith was exercised, and assignments were given. Christ\u2019s leadership was established long before Bethlehem.",
      reflection: "You chose to follow Christ before you were born. What does it mean to re-choose Him now, in mortality, when it\u2019s harder and the veil is in place?"
    },
    {
      label: "The veil and the purpose of mortality",
      focus: "If we lived with God before, why don\u2019t we remember? Today examines why the veil exists and what it makes possible.",
      scriptures: [{book:"Abr",ch:3,vs:24,ve:26},{book:"2 Ne",ch:2,vs:25},{book:"D&C",ch:93,vs:29,ve:33}],
      nuances: "In Abraham 3:25, \u2018We will prove them herewith\u2019 \u2014 the word \u2018prove\u2019 does not mean \u2018test to see if they fail.\u2019 The Hebrew and English both carry the sense of refining, demonstrating quality, or showing what something is made of. The purpose of mortality is not a pass/fail exam but a process of revealing and developing character.",
      commentary: "Abraham 3:24\u201326 explains the purpose of mortality: \u2018We will prove them herewith, to see if they will do all things whatsoever the Lord their God shall command them.\u2019 The veil of forgetfulness is essential to this test. Without it, faith would have no meaning \u2014 obedience would be obvious self-interest rather than trust.\n\n2 Nephi 2:25 provides one of the most quoted verses in Restoration scripture: \u2018Adam fell that men might be; and men are, that they might have joy.\u2019 The Fall was not a catastrophe but a necessary step. Mortality is not a punishment \u2014 it is the arena where joy becomes possible.\n\nD&C 93:29\u201333 teaches that intelligence was not created or made, and that God\u2019s purpose is to bring His children truth and light. This adds a philosophical depth: we are not creations ex nihilo but co-eternal intelligences whom God is helping to grow into their full potential.\n\nThe doctrine of the veil resolves a question that has troubled philosophers and theologians for millennia: why does God seem hidden? Restoration theology answers: He is not hidden out of indifference but out of love. The veil makes faith possible, and faith is the engine of growth.",
      patterns: "The antemortal existence frames mortality: we came from somewhere, we are being tested, and Christ made both the departure and the return possible.",
      reflection: "If mortality is a deliberate test you agreed to before birth, how does that change the way you view your trials \u2014 not as random suffering but as part of a plan you once understood and accepted?"
    },
    {
      label: "What He gave up to come",
      focus: "He left glory to become mortal. Today examines the cost of Christ\u2019s condescension from the pre-mortal perspective.",
      scriptures: [{book:"Philip",ch:2,vs:5,ve:8},{book:"John",ch:6,vs:38},{book:"3 Ne",ch:1,vs:14}],
      nuances: "Philippians 2:7 says He \u2018made himself of no reputation\u2019 \u2014 the Greek \u2018ekenosen\u2019 literally means \u2018emptied himself.\u2019 This is the theological concept of \u2018kenosis\u2019 (self-emptying). The question of what exactly Christ \u2018emptied\u2019 Himself of \u2014 divine prerogatives, glory, power, knowledge \u2014 has been debated for centuries. The text is clear about the direction: downward, voluntary, total.",
      commentary: "Philippians 2:5\u20138 is likely an early Christian hymn that Paul incorporated into his letter. It describes Christ as being in the form of God but choosing to make Himself nothing, taking the form of a servant, becoming obedient unto death \u2014 even the death of the cross. The movement is entirely downward: from divine glory to human servanthood to the most degrading form of execution.\n\nJohn 6:38 records Christ\u2019s own statement: He came not to do His own will but the will of the Father who sent Him. This is voluntary mission, not compulsion.\n\n3 Nephi 1:14 captures a tender moment: on the eve of His birth, Christ\u2019s voice comes to the prophet Nephi: \u2018Behold, I come unto my own, to fulfil all things which I have made known unto man from the foundation of the world.\u2019 He knew what was coming. He had made it known to prophets for millennia. And He came anyway.\n\nThe gap between what He was in the pre-mortal world and what He became in mortality is the measure of His love. He descended from a glory we can barely comprehend into a mortal body that would suffer hunger, exhaustion, rejection, torture, and death.\n\nKenotic theology (from Philippians 2) has been a rich field of Christian reflection. The Restoration adds specific content to the kenosis: He left the presence and glory of the Father, where He was known as Jehovah, the Firstborn, the Creator \u2014 and arrived in a stable.",
      patterns: "The condescension from Week 1 is grounded here: He descended from pre-mortal glory. The gap between what He was and what He became is the measure of His love.",
      reflection: "What are you willing to give up to follow the plan God has for you? Christ\u2019s example is not just inspirational \u2014 it is the pattern for discipleship."
    }
  ]
};

export default week04;
