import type { WeekContent } from '../types';

const week06: WeekContent = {
  title: "Creator — All Things Were Made by Him",
  subtitle: "Jesus Christ, under the direction of the Father, created the heavens and the earth and all things in them.",
  weekScriptures: "Ps 33:6-9; Ps 104:24-30; Prov 3:19-20; Isa 40:28; Isa 45:12; Jer 10:12; Rev 4:11; Ether 3:15; D&C 14:9; D&C 45:1; Morm 9:17; Mosiah 4:9",
  synthesis: {
    summary: "Christ is not merely a moral teacher or even a Redeemer alone — He is the Creator of heaven and earth. The New Testament, Book of Mormon, and Pearl of Great Price all identify Jesus Christ as the agent through whom the Father organized the cosmos. Understanding Christ as Creator changes how we see the natural world, our physical bodies, and the purpose of mortality itself.",
    connections: [
      "Week 1 introduced Christ's cosmic scope through D&C 88 and Colossians 1; this week examines the creation in full detail.",
      "Week 7 (Foreordained & Firstborn) explains how Christ's premortal status qualified Him to be the Creator.",
      "Week 8 (Jehovah) identifies the Creator-God of Genesis as the premortal Christ — the same being who later walked in Galilee."
    ],
    teaching: "If Jesus Christ created the physical world, what does that tell us about how God views matter, bodies, and the natural world? How should it shape our own relationship with creation?",
    commitment: "Spend time outdoors this week. As you observe the natural world, consider that the same hands that shaped mountains and seas also reached out to heal the sick and bless children."
  },
  days: [
    {
      label: "All things made by Him",
      focus: "The New Testament declares plainly that Christ is the Creator. Today establishes the biblical foundation for this doctrine.",
      scriptures: [{book:"John",ch:1,vs:1,ve:3},{book:"Col",ch:1,vs:15,ve:17},{book:"Heb",ch:1,vs:1,ve:3},{book:"Heb",ch:1,vs:10,ve:12}],
      nuances: "In John 1:3, 'without him was not any thing made that was made' uses the Greek 'egeneto' (came into being) — indicating that all created reality owes its existence to the Logos. The double negation ('without him was not anything made') is emphatic and absolute. Hebrews 1:2 uses the phrase 'by whom also he made the worlds' — the Greek 'aionas' (ages/worlds) suggests not just the physical universe but the epochs of time themselves.",
      commentary: "Three New Testament witnesses converge on a single claim: Jesus Christ is the Creator. John declares that all things were made by the Word and nothing exists apart from Him. Paul tells the Colossians that by Christ 'were all things created, that are in heaven, and that are in earth, visible and invisible.' The author of Hebrews states that the Father made the worlds through the Son.\n\nThis was a radical claim in the first century. Greek philosophy generally held that the material world was inferior to the spiritual — created by a lesser being or an accident. The Christian declaration that the divine Logos Himself created matter was a revolutionary affirmation of the goodness of the physical world.\n\nColossians 1:17 goes further: 'by him all things consist' — Christ does not merely create and withdraw. He sustains reality in an ongoing way. The universe holds together because of His active, present power. This has implications for how we understand science, nature, and the physical body: they are not distractions from spiritual life but products of divine creative intelligence.",
      patterns: "The New Testament identification of Christ as Creator connects directly to the Old Testament creation accounts (studied this week) and to the Pearl of Great Price's expanded creation narratives. It also undergirds Week 1's teaching about the light of Christ filling the immensity of space (D&C 88).",
      reflection: "If Christ created the physical world — including your body — what does that say about the value God places on physical, embodied existence?"
    },
    {
      label: "The Genesis creation",
      focus: "The foundational account of creation in Genesis reveals order, purpose, and divine intention. Today reads Genesis through the lens of Christ as Creator.",
      scriptures: [{book:"Gen",ch:1,vs:1,ve:5},{book:"Gen",ch:1,vs:26,ve:31},{book:"Gen",ch:2,vs:1,ve:7}],
      nuances: "Genesis 1:1 begins with 'Bereshit bara Elohim' — 'In the beginning, God created.' The Hebrew 'Elohim' is grammatically plural, which has long intrigued scholars. While Hebrew uses the plural form for majesty, Latter-day Saint theology sees here a hint of the divine council: the creation was a collaborative work involving the Father, Son, and other divine agents. Genesis 1:26 makes this explicit: 'Let us make man in our image.'",
      commentary: "Genesis 1 presents creation as an act of supreme order. Light is separated from darkness, waters from dry land, day from night. Each creative act follows a pattern: God speaks, the thing comes into being, and God declares it good. This is not a random explosion but a deliberate, intelligent design executed with care and delight.\n\nThe plural pronouns in Genesis 1:26 — 'Let us make man in our image, after our likeness' — have been debated for millennia. Traditional Christian theology often reads this as a reference to the Trinity. Latter-day Saint theology understands it more concretely: the Father directed the creation, and the Son (along with other premortal agents) carried it out. Abraham 4 (studied later this week) makes this collaborative process explicit.\n\nGenesis 2:7 describes the creation of Adam from the dust of the ground, with God breathing into his nostrils the breath of life. The Hebrew 'nishmat chayyim' (breath of life) suggests not merely biological animation but the imparting of divine life-force. The God who breathes life into humanity is the same Christ who would later breathe on His apostles and say, 'Receive ye the Holy Ghost' (John 20:22). Creation and redemption flow from the same divine source.",
      patterns: "The creation of humanity 'in the image of God' (Gen 1:27) is foundational to every subsequent doctrine: the Fall presupposes a divine original from which humanity fell, the Atonement restores that image, and exaltation completes it. This connects to Week 7 (Christ as the Firstborn — the original image) and Week 49 (Second Coming and renewal of creation).",
      reflection: "God declared each stage of creation 'good' and humanity 'very good.' How does this divine assessment of creation shape how you view your own body and the physical world around you?"
    },
    {
      label: "Creation through the lens of Moses",
      focus: "The book of Moses restores details lost from Genesis and places the creation in a larger cosmic context. Today examines what the Restoration adds to our understanding of the Creator's work.",
      scriptures: [{book:"Moses",ch:1,vs:30,ve:33},{book:"Moses",ch:2,vs:1},{book:"Moses",ch:2,vs:26,ve:31},{book:"Moses",ch:3,vs:1,ve:7}],
      nuances: "Moses 1:33 introduces a staggering claim: 'worlds without number have I created.' The Hebrew concept of creation in Genesis is local — focused on this earth. The Restoration expands the scope to a universe of created worlds, each with inhabitants, all made through the Son. The phrase 'by the Son I created them' (Moses 1:33) makes the Christological agency of creation explicit in a way Genesis does not.",
      commentary: "The book of Moses, revealed through the Prophet Joseph Smith, reframes the Genesis creation account in two critical ways. First, it provides a cosmic context: before showing Moses the creation of this earth, God reveals that He has created 'worlds without number' and that 'there is no end to my works' (Moses 1:38). This earth is not the totality of God's creative work — it is one expression of an infinite pattern.\n\nSecond, Moses makes the Christological agency of creation explicit. Moses 2:1 states that God spoke to Moses, saying, 'by mine Only Begotten I created these things.' Where Genesis leaves the mechanism of creation somewhat ambiguous (God speaks and it happens), Moses clarifies that the Son is the agent through whom the Father works. This aligns perfectly with John 1:3, Colossians 1:16, and Hebrews 1:2.\n\nMoses 3:5 adds another significant detail: all things were 'created spiritually' before they were 'naturally upon the face of the earth.' This two-stage creation — spiritual followed by physical — is a distinctive Restoration teaching with profound implications. It suggests that the physical world is not random but the realization of a prior spiritual blueprint, designed with purpose and intention by the Creator.",
      patterns: "The Mosaic creation account connects to Week 5 (Appearances, Antemortal) — the God who speaks to Moses and reveals the creation is the same premortal Christ who appeared to him on the mountain. It also foreshadows Week 7: if Christ created worlds without number, His premortal status must have been extraordinary indeed.",
      reflection: "Moses learned that God created 'worlds without number' yet still said to him personally, 'I have a work for thee.' How does the vastness of creation affect your sense of your own significance to God?"
    },
    {
      label: "The Abraham creation account",
      focus: "Abraham's account of the creation emphasizes organization, divine council, and collaboration. Today explores what 'organized' means versus 'created from nothing.'",
      scriptures: [{book:"Abr",ch:4,vs:1,ve:10},{book:"Abr",ch:4,vs:26,ve:31},{book:"Abr",ch:5,vs:1,ve:8}],
      nuances: "Abraham 4 consistently uses the verb 'organized' rather than 'created' — and uses the plural 'the Gods' throughout. This reflects a distinct theological vocabulary: creation as the organizing of existing materials rather than creation ex nihilo (from nothing). The difference is significant — it implies that matter is co-eternal with God and that creation is an act of intelligent design and ordering rather than conjuring from void.",
      commentary: "Abraham 4–5 provides a third creation account in Latter-day Saint scripture, and its differences from Genesis and Moses are theologically significant. Where Genesis uses 'God created,' Abraham uses 'the Gods organized.' Where Genesis is singular, Abraham is consistently plural. Where Genesis implies creation from nothing (the traditional Christian doctrine of creatio ex nihilo), Abraham describes the ordering of existing materials.\n\nThis distinction matters enormously. If matter is co-eternal with God — not created from nothing but organized into purposeful form — then the physical world has a dignity and reality that some theological traditions have denied. Bodies are not prisons for the spirit; they are organized by divine intelligence for divine purposes. The doctrine of resurrection (Christ taking up His body permanently) makes more sense against this backdrop.\n\nAbraham 5:2–3 also reveals that the creation involved planning and consultation: 'Let us go down... and we will take of these materials, and we will make an earth.' The 'us' here refers to the premortal council, with Christ as the chief agent. Creation was not an arbitrary act of power but a deliberate, collaborative work of love. Every mountain, ocean, and living creature reflects thoughtful design by the Savior of the world.",
      patterns: "The collaborative language of Abraham 4 connects directly to Week 7 (the premortal council where Christ was foreordained). The emphasis on organizing existing matter connects to D&C 93:33 and the Restoration's distinctive theology of eternal matter, which shapes how we understand the physical body and resurrection (Weeks 14–15).",
      reflection: "The creation accounts portray God not as an isolated power but as a collaborative organizer, working with a council. What does this reveal about how God works with you in your own life?"
    },
    {
      label: "Book of Mormon witnesses of the Creator",
      focus: "The Book of Mormon testifies of Christ as Creator from multiple prophetic voices. Today examines what Nephite prophets knew about the God who made heaven and earth.",
      scriptures: [{book:"Mosiah",ch:3,vs:8},{book:"2 Ne",ch:2,vs:14},{book:"Alma",ch:30,vs:44},{book:"Hel",ch:14,vs:12}],
      nuances: "In Alma 30:44, Alma responds to the anti-Christ Korihor by pointing to creation as evidence of God: 'All things denote there is a God; yea, even the earth, and all things that are upon the face of it, yea, and its motion, yea, and also all the planets which move in their regular form do witness that there is a Supreme Creator.' The argument from design here anticipates by two millennia what philosophers would later call the teleological argument.",
      commentary: "The Book of Mormon does not contain its own creation narrative, but its prophets repeatedly testify of Christ as the Creator. King Benjamin, speaking by angelic revelation in Mosiah 3:8, identifies the coming Messiah as 'the Creator of all things from the beginning.' This is not an abstract theological claim — it is a prophet declaring to his people that the God who made their world would soon descend to live in it.\n\nLehi teaches in 2 Nephi 2:14 that God created 'things to act and things to be acted upon' — a compact philosophical statement about the structure of reality. Creation is not just the production of objects but the establishment of a moral universe in which agency (the power to act) is real and meaningful.\n\nAlma's exchange with Korihor in Alma 30:44 is one of the great apologetic moments in scripture. Faced with philosophical skepticism, Alma does not retreat into private testimony alone — he points to the observable order of the natural world as evidence of a Creator. The earth, the planets, their regular motions: all bear witness. Samuel the Lamanite adds in Helaman 14:12 that Christ created humanity 'from the beginning.' Each of these witnesses approaches creation from a different angle: theological (Benjamin), philosophical (Lehi), evidential (Alma), and prophetic (Samuel).",
      patterns: "The Book of Mormon's testimony of Christ as Creator reinforces Week 1's principle that all prophets testified of Christ. It also connects to Week 8 (Jehovah): the Creator-God whom Nephite prophets worship is the same Jehovah of the Old Testament who would become Jesus of Nazareth.",
      reflection: "Alma pointed to the natural world as evidence of a Creator. When you look at the world around you, what aspects of creation speak most powerfully to you of Christ's hand?"
    },
    {
      label: "Worlds without number",
      focus: "The scope of Christ's creative work extends beyond this earth to an infinity of worlds. Today grapples with the staggering scale of the Creator's labor.",
      scriptures: [{book:"Moses",ch:1,vs:30,ve:39},{book:"D&C",ch:76,vs:22,ve:24},{book:"D&C",ch:88,vs:41,ve:47}],
      nuances: "D&C 76:24 declares that the inhabitants of the many worlds created by Christ 'are begotten sons and daughters unto God.' The word 'begotten' here carries immense theological weight — it implies that the relationship between God and His children on other worlds is the same filial, covenantal relationship He has with the inhabitants of this earth. The scope is staggering, but the intimacy is preserved.",
      commentary: "Moses 1:33 and D&C 76:24 together make a claim unparalleled in traditional Christian theology: Christ has created worlds without number, and each of them is populated by children of God. This is not science fiction — it is revealed cosmology. The universe is not empty or purposeless; it is filled with divine creative work and inhabited by beings for whom Christ is also Savior.\n\nD&C 88:41–47 extends this vision further. God's understanding comprehends all things, and 'all kingdoms have a law given' — every sphere of creation operates under divine order. The passage describes the earth and the other planets as kingdoms with their own glory, governed by laws decreed by God. The Creator has not made one world and forgotten the rest; He governs all of them.\n\nMoses 1:39 then reveals the purpose behind all this creative activity: 'This is my work and my glory — to bring to pass the immortality and eternal life of man.' The creation of worlds without number is not an exercise in cosmic architecture for its own sake. Every world, every star, every particle of matter organized by Christ serves the ultimate purpose of bringing God's children home. Creation is an act of love, not merely of power.",
      patterns: "The infinite scope of creation studied today stands in deliberate tension with the intimate, personal Christ of Week 1 (Day 6, Alma 7:11–13). The same being who organized galaxies wept at the tomb of Lazarus. Holding both truths simultaneously is central to understanding who Christ is. This cosmic perspective also prepares for Week 49 (Second Coming) when Christ returns to glorify and renew His creation.",
      reflection: "If the purpose of all creation is 'the immortality and eternal life of man,' how does that reshape your understanding of why the physical world exists — and why you exist within it?"
    },
    {
      label: "Creator and Redeemer — the same hands",
      focus: "Drawing the week together: the hands that created the world are the same hands that bear the prints of the nails. Today connects creation and redemption as one seamless work.",
      scriptures: [{book:"D&C",ch:38,vs:1,ve:3},{book:"Jacob",ch:4,vs:9},{book:"John",ch:1,vs:1,ve:3},{book:"3 Ne",ch:9,vs:15}],
      nuances: "D&C 38:1–3 opens with Christ identifying Himself: 'I am the same which have taken the Zion of Enoch... the same which looketh upon the wide expanse of eternity... the same which made the world, and all things came by me.' The accumulation of 'the same' is rhetorically powerful — it insists that the Creator, the Redeemer, the God of Enoch, and the speaker in 1831 are one being. There is no separation between the God of creation and the God of salvation.",
      commentary: "D&C 38:1–3 is one of the most comprehensive self-identifications Christ makes in modern revelation. He is the Creator of all things, the God who took Enoch's Zion to Himself, the one who looks upon the wide expanse of eternity, and the one who speaks to His Saints in the latter days. Every role — Creator, covenant God, Redeemer, revelator — belongs to the same Person.\n\nJacob 4:9 adds a crucial insight: 'the earth was created by the power of his word.' Jacob is not merely stating a fact about origins — he is making an argument about trust. If God is powerful enough to create the earth by speaking, then surely He is powerful enough to fulfill His promises. The doctrine of creation is not just cosmology; it is the ground of faith.\n\n3 Nephi 9:15 completes the picture. The risen Christ, speaking from the darkness after the destruction in the Americas, declares: 'I am Jesus Christ the Son of God. I created the heavens and the earth, and all things that in them are.' He identifies Himself as Creator in the very moment He is inviting the survivors to come to Him and be saved. Creation and redemption are not two separate projects — they are two dimensions of the same divine work, performed by the same Person, with the same hands.\n\nThe hands that separated light from darkness in Genesis 1 are the same hands that were pierced on Calvary. The voice that said 'Let there be light' is the same voice that said 'Father, forgive them.' Seeing creation and redemption as one unified work of Christ is among the most powerful insights scripture offers.",
      patterns: "This day's synthesis connects to every week in the plan. The Creator studied this week is the Firstborn of Week 7, the Jehovah of Week 8, the suffering Messiah of Weeks 12–13, the resurrected Lord of Weeks 14–15, and the returning King of Week 49. Every topic in this plan is an aspect of the one Christ who made and redeems all things.",
      reflection: "The same Christ who created the world also descended below all things to save you. How does holding these two truths together — His creative power and His suffering love — deepen your worship of Him?"
    }
  ]
};

export default week06;
