import type { WeekContent } from '../types';

const week30: WeekContent = {
  title: "Son of Man — The Lord Who Shares Our Humanity",
  subtitle: "Jesus called Himself the Son of Man more than any other title — a name that declares His solidarity with humanity and His authority over it.",
  weekScriptures: "Matt 12:8; Matt 12:40; Matt 13:41; Matt 17:9,12,22; Matt 18:11; Matt 20:18,28; Mark 2:10; Mark 14:21,41,62; Luke 6:22; Luke 9:22,44,58; Luke 12:8,40; Luke 17:24,26; John 8:28; John 12:23,34",
  synthesis: {
    summary: "While 'Son of God' (Week 29) emphasizes Christ's divine nature, 'Son of Man' emphasizes His chosen connection to humanity. Jesus used this title for Himself more than 80 times in the Gospels — far more than any other designation. It draws from Daniel's vision of a divine figure receiving an everlasting kingdom, while simultaneously affirming that the God of the universe chose to enter the human condition. The Son of Man has authority to forgive sins, will come in glory to judge, and has no place to lay His head. The title holds together Christ's cosmic authority and His earthly vulnerability.",
    connections: [
      "The 'Son of Man' title complements 'Son of God' (Week 29) and 'Only Begotten Son' (Week 31), together forming a complete picture of Christ's identity.",
      "Christ's identification with human suffering connects to Week 11 (Atonement) and Week 6 (Condescension).",
      "The eschatological Son of Man coming in glory ties to Week 43 (Second Coming) and Week 36 (Judge)."
    ],
    teaching: "Why do you think Jesus preferred calling Himself 'Son of Man' over 'Son of God' or 'Messiah'? What does this choice reveal about His priorities and character?",
    commitment: "This week, when you face a difficult or humbling human experience — fatigue, disappointment, physical pain — consciously remember that the Son of Man experienced the same things. Let that awareness draw you closer to Him."
  },
  days: [
    {
      label: "Daniel's Son of Man",
      focus: "The title originates in Daniel's apocalyptic vision: a figure 'like the Son of man' approaches the Ancient of Days and receives an everlasting kingdom. Today examines this foundational text.",
      scriptures: [{book:"Dan",ch:7,vs:13,ve:14},{book:"Matt",ch:26,vs:64},{book:"D&C",ch:45,vs:39}],
      nuances: "In Daniel 7:13, 'one like the Son of man' uses the Aramaic 'bar enash,' which literally means 'son of humanity' or 'a human one.' The phrase 'like' (ke-bar) indicates resemblance — this figure appears human but is clearly more than human, since He approaches the divine throne and receives everlasting dominion. The Aramaic deliberately holds together the human and the transcendent.",
      commentary: "Daniel's vision in chapter 7 is the origin point for the title 'Son of Man' as Jesus used it. In the vision, four beasts representing world empires rise from the sea. Then the scene shifts to heaven: the Ancient of Days (God the Father) takes His seat, and one 'like the Son of man' comes with the clouds and is brought before Him. This figure receives dominion, glory, and a kingdom that all peoples, nations, and languages shall serve — an everlasting dominion that will not pass away.\n\nThe vision is extraordinary because the Son of Man is simultaneously human ('like a son of man') and divine (He approaches God's throne and receives universal, eternal authority). No human king in Israel's history — not David, not Solomon — received anything approaching this. Daniel is describing a figure who transcends every category.\n\nWhen Jesus stood before the Sanhedrin in Matthew 26:64, He directly claimed Daniel's vision for Himself: 'Hereafter shall ye see the Son of man sitting on the right hand of power, and coming in the clouds of heaven.' The high priest tore his robes and declared it blasphemy — because he understood exactly what Jesus was claiming. He was identifying Himself as Daniel's Son of Man: the one who would receive everlasting dominion from the Ancient of Days.\n\nD&C 45:39 places this same imagery in a latter-day context, speaking of the time when the Son of Man will come. The Restoration does not reinvent the title — it confirms and extends Daniel's vision into the unfolding events of the last days.",
      patterns: "Daniel's Son of Man vision establishes a pattern where divine authority is expressed through a human form — God reaches humanity not by remaining distant but by taking on human likeness. This pattern culminates in the Incarnation and extends through every theophany recorded in scripture.",
      reflection: "Daniel's Son of Man is both fully human in appearance and invested with divine authority. How does this dual nature change your understanding of what it means that God became a man?"
    },
    {
      label: "Nowhere to lay His head",
      focus: "The Son of Man who would receive an everlasting kingdom had no home on earth. Today explores the voluntary poverty and vulnerability of Christ.",
      scriptures: [{book:"Matt",ch:8,vs:20},{book:"Luke",ch:19,vs:10},{book:"Mosiah",ch:3,vs:7}],
      nuances: "Matthew 8:20 records Jesus saying 'Foxes have holes, and the birds of the air have nests; but the Son of man hath not where to lay his head.' The contrast is deliberately humbling: even animals have shelter, but the Lord of creation has less than they do. The phrase 'Son of man' here carries its full Danielic weight — the one who will receive an everlasting kingdom currently has no earthly place to rest.",
      commentary: "There is a stunning contrast between Daniel 7, where the Son of Man receives everlasting dominion, and Matthew 8:20, where the Son of Man has nowhere to lay His head. The same title is used for both descriptions. Jesus is not using two different identities — He is revealing that the path to the throne passes through homelessness, rejection, and vulnerability.\n\nA would-be follower came to Jesus and said he would follow Him wherever He went. Jesus' response was not a recruitment pitch but a warning: if you follow the Son of Man, expect dispossession. Foxes and birds are more securely housed than your Master. This is not asceticism for its own sake — it is the reality of a mission that required complete dependence on the Father.\n\nLuke 19:10 provides the purpose statement: the Son of Man has come to seek and to save that which was lost. The homelessness is not accidental — it is the cost of the mission. A savior who remained comfortable in a palace could not seek the lost in their hovels. The Son of Man went where the lost were, which meant going where comfort was not.\n\nMosiah 3:7 describes the suffering the Lord Omnipotent would endure: anguish so great that blood would come from every pore. The same being who had no place to lay His head would have His blood soaking into the ground of Gethsemane. The vulnerability of the Son of Man is not a weakness in the plan — it is the plan. He must descend below all things to lift all things.",
      patterns: "The voluntary poverty of the Son of Man follows the kenotic pattern of Philippians 2 — the one who was in the form of God emptied Himself. This descent-before-ascent pattern is the structural backbone of the gospel and connects to Week 6 (Condescension) and Week 12 (Resurrection).",
      reflection: "The Son of Man chose to be homeless so He could seek the lost. What comforts might you need to set aside to reach the people in your life who are spiritually lost?"
    },
    {
      label: "Authority to forgive sins",
      focus: "The Son of Man claimed authority that belongs only to God — the power to forgive sins. Today examines this radical assertion and its implications.",
      scriptures: [{book:"Matt",ch:9,vs:6},{book:"Mark",ch:10,vs:45},{book:"John",ch:6,vs:53}],
      nuances: "In Matthew 9:6, Jesus says 'that ye may know that the Son of man hath power on earth to forgive sins.' The Greek 'exousian' (authority/power) is significant — it denotes not just ability but rightful authority. The scribes were right that only God can forgive sins. Their error was in not recognizing that the Son of Man standing before them was God. The healing of the paralytic was the visible proof of the invisible authority.",
      commentary: "When Jesus told the paralytic, 'Thy sins be forgiven thee,' the scribes immediately thought He was blaspheming — because only God can forgive sins. Jesus responded not by backing down but by escalating: 'That ye may know that the Son of man hath power on earth to forgive sins, arise, take up thy bed, and go.' The healing was the visible evidence of the invisible authority. If He can restore a body, He can restore a soul.\n\nThe phrase 'on earth' is crucial. Jesus is asserting that divine authority to forgive is not reserved for some future heavenly tribunal — it operates now, on earth, through the Son of Man. This was new. The temple system required sacrifices, priests, and rituals to mediate forgiveness. Jesus claims that the Son of Man possesses this authority in His own person.\n\nMark 10:45 adds the purpose: the Son of Man came not to be served but to serve, and to give His life a ransom for many. The authority to forgive is grounded in the willingness to die. He can forgive because He will pay the price. The ransom language implies a cost — forgiveness is not cheap, and the Son of Man bears its full expense.\n\nJohn 6:53 extends the claim further: unless you eat the flesh of the Son of Man and drink His blood, you have no life in you. This sacramental language ties the Son of Man's authority directly to His sacrifice and to the personal appropriation of that sacrifice by each believer. Forgiveness, life, and communion with God all flow through the Son of Man.",
      patterns: "The forgiveness-proven-by-healing pattern appears throughout the Gospels and establishes a principle: spiritual restoration and physical wholeness are connected. The Son of Man addresses both because He has authority over both — a theme that connects to Week 20 (Healer).",
      reflection: "Jesus claimed the authority to forgive sins on earth, in real time. Do you truly believe that when you repent, the Son of Man forgives you completely — or do you carry guilt He has already resolved?"
    },
    {
      label: "The Son of Man must suffer",
      focus: "Three times Jesus predicted His suffering and death, each time using the title Son of Man. Today examines why suffering was not optional but necessary.",
      scriptures: [{book:"Mark",ch:8,vs:31},{book:"Mark",ch:9,vs:31},{book:"Mark",ch:10,vs:33,ve:34}],
      nuances: "In Mark 8:31, 'the Son of man must suffer' uses the Greek 'dei' — meaning it is necessary, it is divinely ordained. This is not fate in a Greek sense but divine necessity: the suffering is required by the plan of salvation, not imposed by circumstances. The 'must' reflects the Father's will, and the Son of Man's acceptance of it is the supreme act of obedience.",
      commentary: "Three times in Mark's Gospel, Jesus explicitly predicts His suffering, death, and resurrection — and each time He uses the title Son of Man. The first prediction (Mark 8:31) follows Peter's confession that Jesus is the Christ. The sequence is striking: the moment the disciples recognize His identity, He begins to explain that the Son of Man must suffer, be rejected, be killed, and after three days rise again.\n\nThe second prediction (Mark 9:31) is even more direct: the Son of Man is delivered into the hands of men, and they shall kill Him. The juxtaposition of 'Son of Man' and 'hands of men' creates a terrible irony — the representative of all humanity will be destroyed by the very humanity He represents.\n\nThe third prediction (Mark 10:33–34) is the most detailed: the Son of Man will be delivered to the chief priests, condemned to death, delivered to the Gentiles, mocked, spat upon, scourged, and killed — and the third day He will rise. Jesus narrates His own passion with clinical specificity. There is no surprise here, no victimhood. The Son of Man walks into His suffering with full knowledge and full consent.\n\nThe word 'must' in these predictions is theologically loaded. The suffering is not accidental, not a failure of the plan, not a tragedy that God will later redeem. It is the plan. The Son of Man must suffer because without His suffering, there is no Atonement, no forgiveness, no resurrection, no salvation. The necessity is rooted in divine love: the cost of redeeming humanity is the suffering of the Son of Man, and He was willing to pay it.",
      patterns: "The threefold prediction pattern — suffering, death, resurrection — mirrors the three days in the tomb and the three-part structure of the Atonement (Gethsemane, Cross, Resurrection). The repetition ensures the disciples cannot claim ignorance: the Son of Man told them in advance.",
      reflection: "Jesus said the Son of Man 'must' suffer. How does knowing that His suffering was not accidental but necessary change the way you think about suffering in your own life?"
    },
    {
      label: "Lifted up as the serpent",
      focus: "Jesus compared Himself to the bronze serpent Moses lifted in the wilderness. Today explores this unexpected type and what it reveals about the Son of Man.",
      scriptures: [{book:"John",ch:3,vs:13,ve:14},{book:"John",ch:1,vs:51},{book:"Hel",ch:8,vs:14,ve:15}],
      nuances: "John 3:14 says the Son of Man must be 'lifted up' — the Greek 'hupsōthēnai' is deliberately ambiguous, meaning both physical elevation (on the cross) and exaltation (glorification). John uses this double meaning throughout his Gospel (John 8:28, 12:32–34). The cross is simultaneously the lowest point of humiliation and the moment of supreme glorification. In being lifted up on the cross, the Son of Man is lifted up to His throne.",
      commentary: "In John 3:13–14, Jesus makes two extraordinary claims. First, no one has ascended to heaven except the Son of Man who came down from heaven — asserting His heavenly origin and unique authority. Second, as Moses lifted up the serpent in the wilderness, so must the Son of Man be lifted up, that whoever believes in Him may have eternal life.\n\nThe bronze serpent reference (Numbers 21:4–9) is an unexpected type. The Israelites, bitten by fiery serpents in the wilderness, were told to look at a bronze serpent on a pole to be healed. The image is counterintuitive — the cure looks like the disease. The serpent that kills is also the serpent that heals, when lifted up by God's command.\n\nThe typology is profound: sin and death afflict humanity like the serpents in the wilderness. The cure is to look upon the Son of Man lifted up on the cross — the place where He took upon Himself the consequences of sin and death. He becomes, in Paul's language, 'sin for us' (2 Cor 5:21) so that we might be made righteous. The cure resembles the disease because Christ takes on our condition to transform it.\n\nJohn 1:51 adds another layer: Jesus tells Nathanael he will see heaven opened and the angels of God ascending and descending on the Son of Man. This is a direct reference to Jacob's ladder (Genesis 28:12) — and Jesus identifies Himself as the ladder. The Son of Man is the connection between heaven and earth, the bridge between God and humanity.\n\nHelaman 8:14–15 confirms that Moses' serpent was a type of the Son of God, and Nephi insists that those who refused to look upon it perished — not because the remedy was insufficient but because they chose not to use it.",
      patterns: "The looking-and-being-healed pattern runs from the bronze serpent through Alma 33:19–22 to the sacrament: the cure for spiritual death is to look upon Christ, lifted up, and believe. The simplicity of the remedy does not diminish its power. This connects to the faith themes in Week 23.",
      reflection: "The Israelites who were healed had only to look at the serpent on the pole. What does it mean to truly 'look' upon the Son of Man lifted up on the cross — and what keeps you from looking?"
    },
    {
      label: "Coming in glory",
      focus: "The Son of Man who suffered in obscurity will return in undeniable glory. Today examines the eschatological dimension of the title.",
      scriptures: [{book:"Matt",ch:24,vs:30},{book:"Matt",ch:25,vs:31},{book:"Acts",ch:7,vs:56}],
      nuances: "Matthew 24:30 says 'they shall see the Son of man coming in the clouds of heaven with power and great glory.' The Greek 'meta dunameōs kai doxēs pollēs' (with power and great glory) directly inverts the conditions of His first coming — born in a stable, rejected, crucified. The second coming of the Son of Man will be everything the first coming was not: visible, powerful, glorious, and unmistakable.",
      commentary: "The Olivet Discourse in Matthew 24 is Jesus' most extended teaching about the end times, and He consistently uses the title Son of Man to describe His return. The sign of the Son of Man will appear in heaven. All the tribes of the earth will see the Son of Man coming in the clouds with power and great glory. The visibility is total — there will be no ambiguity, no debate, no one asking 'Was that really Him?'\n\nMatthew 25:31 connects the return to judgment: when the Son of Man comes in His glory with all the holy angels, He will sit upon the throne of His glory and separate the nations. The title Son of Man is used for the judge because it captures both His authority (Daniel 7) and His empathy (He has lived the human experience). He judges not as a detached deity but as one who has walked in our shoes and bled our blood.\n\nActs 7:56 provides a unique witness: Stephen, being stoned to death, looks up and sees the heavens opened and the Son of Man standing at the right hand of God. In all other descriptions, Christ is seated at the right hand. For Stephen, He is standing — as if He has risen from the throne to receive His faithful servant. This detail, recorded by Luke, suggests that the Son of Man is not a passive figure waiting for the end times. He is actively engaged, attentive to His people, even standing to honor a single martyr.\n\nThe eschatological Son of Man is the same person who had nowhere to lay His head. The homeless wanderer becomes the enthroned judge. The rejected teacher becomes the returning king. The suffering servant receives the everlasting dominion Daniel foresaw.",
      patterns: "The first-coming/second-coming contrast is a master pattern in scripture: humility then glory, suffering then triumph, a manger then a throne. The Son of Man title holds both halves together, insisting that the judge and the servant are the same person.",
      reflection: "Stephen saw the Son of Man standing — rising to receive him in his moment of greatest suffering. Do you believe the Son of Man is standing to receive you in your hardest moments?"
    },
    {
      label: "The Son of Man and you",
      focus: "The Son of Man title tells you something about Christ — and something about yourself. Today synthesizes the week by asking what His chosen identification with humanity means for you.",
      scriptures: [{book:"Matt",ch:16,vs:13},{book:"Moses",ch:6,vs:57},{book:"Alma",ch:7,vs:11,ve:13}],
      nuances: "Moses 6:57 contains the phrase 'in the language of Adam, Man of Holiness is his name, and the name of his Only Begotten is the Son of Man of Holiness.' This remarkable Restoration text reframes the title: 'Son of Man' is not merely 'son of humanity' but 'Son of the Man of Holiness' — a title that points simultaneously to Christ's humanity and to the Father's divine designation. It elevates the word 'Man' itself by applying it first to God.",
      commentary: "When Jesus asked the disciples at Caesarea Philippi, 'Whom do men say that I the Son of man am?' He was not seeking information — He was inviting them to wrestle with His identity. The title Son of Man was His preferred self-designation. Of all the titles available to Him — Son of God, Messiah, Lord, King — He chose the one that emphasized His connection to us.\n\nMoses 6:57 reveals why this title is not a step down from divinity but a revelation of it. The Father's name is Man of Holiness. The Son's name is the Son of Man of Holiness. In this light, 'Son of Man' is not a humbler alternative to 'Son of God' — it is the same truth expressed from a different angle. The Father is the Man of Holiness; the Son is His Son.\n\nAlma 7:11–13 provides the climactic explanation of why the Son of Man entered the human condition: He took upon Himself pain, sickness, death, infirmity, and the sins of the world. He did this so He would know according to the flesh how to succor His people. The Son of Man title is not merely an identity — it is a job description. He became human so He could help humans from the inside out.\n\nThis week has traced the title from Daniel's throne room to the streets of Galilee to the cross to the Second Coming. Through it all, the constant truth is this: the Son of Man chose to identify with humanity not because He had to but because He loves us. His solidarity with us is not theoretical — it is experiential. He has felt what you feel. He has borne what you bear. And He will come again in glory to gather every son and daughter of God into the kingdom that Daniel foresaw.",
      patterns: "The entire fifty-week study traces the interplay between Christ's divine titles and His human experience. 'Son of Man' is the title that holds these two realities together, and this week serves as the bridge between Week 29 (Son of God) and Week 31 (Only Begotten Son).",
      reflection: "Of all the titles He could have used, Jesus preferred 'Son of Man.' What does it mean to you that He chose to identify Himself primarily by His connection to you — to humanity — rather than by His distance from it?"
    }
  ]
};

export default week30;
