import type { WeekContent } from '../types';

const week46: WeekContent = {
  title: "Davidic Descent — Son of David, King of Kings",
  subtitle: "Christ's lineage through David was not incidental — it fulfilled ancient covenants and established His right to an eternal throne.",
  weekScriptures: "Isa 9:6-7; Ps 89:3-4; Ps 89:35-37; Amos 9:11; Zech 3:8; Matt 9:27; Matt 15:22; Matt 12:23; Mark 10:47-48; Luke 1:69; Jer 33:15-17",
  synthesis: {
    summary: "God promised David that his throne would be established forever. A thousand years later, a child was born in Bethlehem — David's city — through David's lineage. Both Matthew and Luke trace Christ's genealogy to David, establishing His legal and biological right to the throne of Israel. But Christ is more than a political heir; He is the eternal King whose reign will never end. The Davidic covenant finds its ultimate fulfillment not in a mortal monarchy but in the millennial and eternal kingship of Jesus Christ.",
    connections: [
      "The Millennial Reign (Week 44) is when Christ sits on David's throne forever — the Davidic covenant reaches its complete fulfillment.",
      "Christ as King (Week 38) explored His royal authority; this week examines the covenantal and genealogical basis for that authority.",
      "The birth narratives studied in Week 49 (Christmas week) begin with genealogies precisely because lineage establishes Christ's right to reign."
    ],
    teaching: "Why does God work through lineage and covenant rather than simply declaring Christ to be King by divine fiat? What does this teach about how God operates in human history?",
    commitment: "Consider your own spiritual lineage — the people who brought the gospel to you. Thank God this week for the chain of faithfulness that connects you to Christ."
  },
  days: [
    {
      label: "The genealogy of the King",
      focus: "Matthew opens his Gospel not with narrative but with a genealogy. Today examines why lineage matters to the story of Christ.",
      scriptures: [{book:"Matt",ch:1,vs:1,ve:17},{book:"Luke",ch:3,vs:23,ve:38},{book:"Rom",ch:1,vs:3}],
      nuances: "Matthew 1:1 calls Jesus 'the son of David, the son of Abraham.' The Greek 'huios David' is a royal title — not merely a statement of ancestry but a claim to the Davidic throne. Matthew structures his genealogy into three sets of fourteen generations, and scholars have noted that the Hebrew numerical value of David's name (D-V-D: 4+6+4) is fourteen — the genealogy itself is encoded with David's identity.",
      commentary: "Matthew begins his Gospel with what modern readers often skip: a genealogy. But for his original audience, this was the most important possible opening. If Jesus is the Messiah, He must be of David's line. Matthew traces the lineage from Abraham through David, through the Babylonian exile, to Joseph and Mary. The message is unmistakable: this child has a legal right to the throne.\n\nLuke's genealogy works in reverse, tracing from Jesus all the way back to Adam and then to God. Luke's purpose is broader — showing that Jesus is not only the Jewish Messiah but the Son of all humanity. Together, the two genealogies establish Christ's credentials from two directions: forward from the covenant (Matthew) and backward to creation (Luke).\n\nPaul confirms the doctrine simply in Romans 1:3: Jesus was made of the seed of David according to the flesh. This was not incidental. God could have incarnated His Son in any family, any nation. He chose the house of David because He had made a covenant, and God keeps His covenants — even across a thousand years.\n\nThe genealogies also contain surprises: Rahab the Canaanite, Ruth the Moabite, Bathsheba the wife of Uriah. The royal line includes outsiders, converts, and people with complicated histories. The lineage of the King is not pure in the way the world expects — it is pure in the way God defines purity: through covenant faithfulness.",
      patterns: "Genealogies in scripture are never filler — they are theological statements. The line from Adam to Noah, from Abraham to Israel, and from David to Christ tells the story of God's covenant working through real families across real centuries.",
      reflection: "The genealogy of Christ includes unexpected people — Gentiles, converts, people with difficult pasts. What does this tell you about who belongs in God's family?"
    },
    {
      label: "The covenant with David",
      focus: "God made a specific, unconditional promise to David: his throne would endure forever. Today examines this covenant and its fulfillment in Christ.",
      scriptures: [{book:"2 Sam",ch:7,vs:12,ve:16},{book:"Ps",ch:132,vs:11},{book:"Luke",ch:1,vs:32,ve:33}],
      nuances: "In 2 Samuel 7:13, God says of David's descendant: 'I will establish the throne of his kingdom forever.' The Hebrew 'ad olam' (forever) is unconditional — unlike the Mosaic covenant, which was conditional on Israel's obedience, the Davidic covenant is grounded in God's own faithfulness. The throne will endure not because David's descendants are perfect but because God's word does not fail.",
      commentary: "The Davidic covenant, recorded in 2 Samuel 7, is one of the most consequential promises in the Bible. David wanted to build a house for God (a temple); God responded by promising to build a house for David (a dynasty). The descendant of David would reign forever. His throne would never end.\n\nPsalm 132:11 records this as an oath: 'The Lord hath sworn in truth unto David; he will not turn from it; Of the fruit of thy body will I set upon thy throne.' An oath from God is the highest possible assurance. When God swears, He stakes His own nature on the outcome.\n\nLuke 1:32–33, the angel Gabriel's announcement to Mary, directly fulfills this covenant: 'The Lord God shall give unto him the throne of his father David: And he shall reign over the house of Jacob for ever; and of his kingdom there shall be no end.' Gabriel does not say Christ will be like David or will follow David's example. He says Christ will sit on David's throne. The covenant made a millennium earlier is being honored to the letter.\n\nThis teaches something profound about how God works: He makes promises and keeps them across centuries. The Davidic covenant was not fulfilled in David's lifetime, not in Solomon's, not during the monarchy, not during the exile. It waited a thousand years. But it was never forgotten.",
      patterns: "The pattern of long-delayed covenant fulfillment recurs throughout scripture: the Abrahamic promise took centuries, the Mosaic covenant endured generations, and the Davidic covenant waited a millennium. God's timing is not human timing, but His faithfulness is absolute.",
      reflection: "God kept His promise to David across a thousand years. What promises has God made to you — through patriarchal blessings, personal revelation, or scripture — that you are still waiting to see fulfilled?"
    },
    {
      label: "The branch of David",
      focus: "The prophets used vivid imagery — a rod, a branch, a root — to describe the coming Davidic king. Today explores these prophetic images.",
      scriptures: [{book:"Isa",ch:11,vs:1,ve:2},{book:"Jer",ch:23,vs:5,ve:6},{book:"Rev",ch:22,vs:16},{book:"Rev",ch:5,vs:5}],
      nuances: "Isaiah 11:1 uses two Hebrew words: 'choter' (rod or shoot) from the 'geza' (stump) of Jesse, and 'netser' (branch) from his roots. The image of a stump implies that the Davidic dynasty has been cut down — by the time of Isaiah, the royal line was already in decline. The Messiah comes not from a flourishing tree but from what appears to be dead wood. New life from apparent death is Isaiah's signature theme.",
      commentary: "Isaiah 11:1 is one of the most celebrated messianic prophecies. Jesse was David's father, so the 'stem of Jesse' is the Davidic line. By Isaiah's time, the monarchy was weakening; by the Babylonian exile, it appeared to be destroyed. The royal family became commoners. Yet Isaiah says a branch will grow from the roots — life will emerge from apparent death.\n\nJeremiah 23:5–6 calls this coming king 'the Lord our righteousness' — in Hebrew, 'Yahweh Tsidkenu.' This is an extraordinary title: a human descendant of David who bears the divine name. Jeremiah is not predicting merely a great king but a divine one.\n\nRevelation 22:16 records Christ's own declaration: 'I am the root and the offspring of David.' This is a paradox: Christ is both the ancestor and the descendant of David. He is the root from which David grew (as the premortal Jehovah who established the covenant) and the branch that grew from David (as the mortal Jesus born into David's line). He is both the source and the fruit of the Davidic line.\n\nRevelation 5:5 calls Him 'the Lion of the tribe of Judah, the Root of David.' In the heavenly vision, no one in heaven or earth could open the sealed book — except this Lion. His Davidic identity is His credential even in the courts of heaven.",
      patterns: "The image of new life from dead wood recurs throughout scripture: Aaron's rod that budded, the dry bones of Ezekiel, the seed that falls into the ground and dies before bearing fruit. God's pattern is resurrection — life from death, hope from despair.",
      reflection: "The Messiah came from what looked like a dead stump. Have you ever seen God bring new life from something that appeared hopeless in your own experience?"
    },
    {
      label: "Son of David — a title of faith",
      focus: "In Jesus' day, calling someone 'Son of David' was not a genealogical observation — it was a declaration of messianic faith. Today examines how this title functioned.",
      scriptures: [{book:"Matt",ch:21,vs:9},{book:"Matt",ch:22,vs:41,ve:46},{book:"John",ch:7,vs:42}],
      nuances: "In Matthew 21:9, the crowd cries 'Hosanna to the Son of David!' The word 'Hosanna' (Hebrew 'hoshi'a na') means 'save us now.' Combined with 'Son of David,' the crowd is making an explicitly messianic proclamation: they are calling Jesus the promised King and asking Him to inaugurate His reign. This is why the Pharisees were alarmed — the title carried political and theological weight.",
      commentary: "When Jesus entered Jerusalem on a donkey and the crowds shouted 'Hosanna to the Son of David,' they were not making small talk about His family tree. They were proclaiming Him the Messiah. The title 'Son of David' was the most politically charged designation in first-century Judaism — it meant the long-awaited King who would restore Israel.\n\nJesus Himself engaged with this title in a remarkable exchange recorded in Matthew 22:41–46. He asked the Pharisees: if the Messiah is David's son, why does David in Psalm 110 call Him 'Lord'? If David calls Him Lord, how is He merely David's son? The Pharisees had no answer. Jesus was not denying His Davidic descent — He was asserting that the Messiah is more than a political heir. He is David's Lord as well as David's descendant.\n\nJohn 7:42 reveals that even Jesus' critics knew the Messiah must come from David's line and from Bethlehem. Some used this to argue against Jesus, not knowing He had been born in Bethlehem. The irony is thick: the very prophecy that should have confirmed Jesus' identity was used to reject Him because His opponents did not investigate thoroughly.\n\nThe title 'Son of David' thus became a dividing line: those who used it in faith recognized the Messiah; those who used it as a test missed Him entirely.",
      patterns: "Titles of Christ function as tests of faith throughout the Gospels. 'Son of David,' 'Son of God,' 'King of Israel' — each one divided audiences into those who believed and those who rejected. The same is true today: the titles of Christ demand a response.",
      reflection: "The crowds called Jesus 'Son of David' as a declaration of faith. When you call Jesus by His titles — Lord, Savior, Redeemer — do those words carry genuine faith, or have they become routine?"
    },
    {
      label: "David's throne fulfilled in Christ",
      focus: "Peter declared at Pentecost that the Davidic covenant was fulfilled in the resurrection of Christ. Today examines how the eternal throne was established.",
      scriptures: [{book:"Acts",ch:2,vs:29,ve:36},{book:"Acts",ch:13,vs:22,ve:23},{book:"Ezek",ch:37,vs:24,ve:25}],
      nuances: "In Acts 2:30, Peter says David 'being a prophet, and knowing that God had sworn with an oath to him, that of the fruit of his loins, according to the flesh, he would raise up Christ to sit on his throne.' The Greek 'kathisai epi ton thronon autou' (to sit upon his throne) indicates permanent enthronement — not a temporary rule but an everlasting reign.",
      commentary: "Peter's Pentecost sermon is a masterpiece of scriptural reasoning. He argues that David spoke prophetically about the Resurrection — that the Holy One would not see corruption. David himself died and was buried (his tomb was still visible in Jerusalem), so the prophecy could not have been about David. It was about David's descendant: Christ, who was raised from the dead and exalted to God's right hand.\n\nThis is Peter's argument for how the Davidic covenant is fulfilled: not through a mortal monarchy but through resurrection and heavenly enthronement. Christ sits on David's throne not in a palace in Jerusalem (at least not yet) but at the right hand of God. The throne is eternal because the King is eternal — death could not hold Him.\n\nPaul echoes this in Acts 13:22–23, connecting David's selection as king directly to the coming of Jesus as Savior. God raised up David; from David's seed, God brought forth Jesus. The entire Davidic dynasty existed to produce this one King.\n\nEzekiel 37:24–25 prophesies of a future fulfillment as well: David's servant (meaning Christ) will be king over a reunited Israel forever. This points to the Millennium (Week 44), when Christ's throne will be established on the renewed earth. The Davidic covenant has both a heavenly fulfillment (now, through the Resurrection) and an earthly fulfillment (future, in the Millennium).",
      patterns: "The Resurrection transformed every expectation. Israel expected a mortal king; God provided a resurrected one. The pattern of divine surprise — fulfillment exceeding expectation — is a hallmark of how God works.",
      reflection: "Peter argued that the Davidic throne was fulfilled through resurrection, not politics. How does this change the way you think about what it means for Christ to be King?"
    },
    {
      label: "Christ's lineage in Latter-day revelation",
      focus: "The Book of Mormon and Doctrine and Covenants affirm Christ's identity as the Son of David and expand its meaning. Today explores Restoration perspectives on Davidic descent.",
      scriptures: [{book:"Alma",ch:5,vs:48},{book:"2 Ne",ch:19,vs:6,ve:7},{book:"D&C",ch:113,vs:1,ve:6},{book:"2 Tim",ch:2,vs:8}],
      nuances: "D&C 113:1–2 asks and answers: 'Who is the Stem of Jesse spoken of in the 11th chapter of Isaiah?' The answer: 'It is Christ.' D&C 113:3–4 then identifies the rod coming from the stem as a servant in the latter days — a distinction between Christ Himself and those who serve under His authority. This interpretive key unlocks Isaiah 11 for Latter-day Saint readers.",
      commentary: "Alma 5:48 is Alma's personal testimony: he knows that Jesus Christ shall come — the Son, the Only Begotten of the Father, full of grace, mercy, and truth. While Alma does not use the title 'Son of David,' his testimony affirms the coming of the same Messiah prophesied by Isaiah and Jeremiah. The Book of Mormon confirms the Old Testament messianic hope from an independent witness on another continent.\n\n2 Nephi 19:6–7, quoting Isaiah 9:6–7, declares that of the increase of His government there shall be no end, 'upon the throne of David, and upon his kingdom, to order it, and to establish it with judgment and with justice.' Nephi preserved these words precisely because they testify of Christ.\n\nD&C 113 provides a Restoration interpretive key to Isaiah 11. The stem of Jesse is Christ. The rod from that stem and the root of Jesse are identified with latter-day servants — suggesting that the Davidic covenant extends into the Restoration era through those who hold priesthood authority and carry out Christ's work.\n\nPaul's counsel to Timothy in 2 Timothy 2:8 is simple and direct: remember that Jesus Christ, of the seed of David, was raised from the dead. Even in pastoral correspondence, the Davidic identity and resurrection of Christ are inseparable. Lineage and resurrection together form the basis of the gospel message.",
      patterns: "The Book of Mormon serves as a second witness to Old Testament messianic prophecy. What Isaiah, Jeremiah, and the Psalms promised, Nephi, Alma, and other Nephite prophets independently confirmed. Two hemispheres, one testimony.",
      reflection: "D&C 113 identifies Christ as the stem of Jesse and latter-day servants as the rod and root. What does it mean to you that the Davidic mission continues through Christ's servants today?"
    },
    {
      label: "More than David's son",
      focus: "Jesus challenged His contemporaries: the Messiah is David's Lord, not merely David's descendant. Today we sit with the fullness of who this King is.",
      scriptures: [{book:"Matt",ch:22,vs:41,ve:46},{book:"Ps",ch:110,vs:1,ve:4},{book:"Heb",ch:7,vs:1,ve:3},{book:"Rev",ch:19,vs:16}],
      nuances: "Psalm 110:1 — 'The Lord said unto my Lord' — uses two different Hebrew words: 'Yahweh' (the covenant God of Israel) said unto 'Adoni' (my master/lord). David is writing, and he calls the Messiah 'my Lord.' In ancient Near Eastern culture, a father never called his son 'my Lord' — authority flowed downward. David's use of this title indicates that the Messiah is superior to David himself.",
      commentary: "Jesus' question to the Pharisees in Matthew 22 is one of the most important Christological arguments in the Gospels. If the Messiah is merely David's human descendant, why does David himself, inspired by the Spirit, call the Messiah 'Lord'? The answer the Pharisees could not give is the answer the gospel proclaims: the Messiah is both human and divine. He is David's son according to the flesh and David's Lord according to His eternal, premortal identity.\n\nPsalm 110 also introduces the Messiah as 'a priest for ever after the order of Melchizedek.' The book of Hebrews (chapter 7) develops this at length: Christ holds a priesthood that predates and supersedes the Levitical order. He is not only a king from David's line but a priest from an older, higher order. King and Priest — the two roles that were always separated in Israel — are united in one Person.\n\nRevelation 19:16 provides the ultimate title: 'King of Kings, and Lord of Lords.' This is not a title that belongs to David or any mortal monarch. It belongs to the divine Son who condescended to enter David's family, walked the dusty roads of Palestine, and will return in glory to claim His throne.\n\nThe Davidic descent is real and important — but it is only part of the story. Christ is the Son of David, yes, but He is infinitely more. He is the Son of God, the Creator, the Redeemer, and the eternal King. David's line gave Him legal standing; His divine nature gives Him cosmic authority.",
      patterns: "Throughout this study, we have seen that every human title for Christ — Prophet, Priest, King, Shepherd, Judge — points beyond itself to His divine nature. The titles describe real roles, but the Person is always greater than the role.",
      reflection: "Jesus is both David's descendant and David's Lord. How do you hold together the humanity and divinity of Christ in your own faith? Does one aspect feel more real to you than the other?"
    }
  ]
};

export default week46;
