import type { WeekContent } from '../types';

const week48: WeekContent = {
  title: "Glory of Christ — The Radiance of the Eternal Son",
  subtitle: "The glory of Jesus Christ is not borrowed or temporary — it is the inherent, eternal radiance of the Son of God, shared with the Father before the world was.",
  weekScriptures: "Col 1:15-17; John 1:14; Isa 60:19-20; Hab 3:3-4; Acts 26:13-15; D&C 76:70-71; D&C 133:49; Rev 21:23; Alma 19:6; D&C 88:67-68; 1 Tim 6:15-16",
      synthesis: {
    summary: "The glory of Christ is not merely an attribute — it is the very nature of His being. Before the world was, He shared the Father's glory. During His mortal ministry, that glory was veiled but occasionally broke through — on the Mount of Transfiguration, in answered prayers, in moments of divine power. After His resurrection, the full glory was restored and magnified. This week explores Christ's glory in its eternal, revealed, and shared dimensions — and the breathtaking promise that His glory will one day be ours.",
    connections: [
      "Week 17 explored the glory of Christ in His mortal ministry and divine attributes; this week focuses on His premortal, postmortal, and eternal glory — the glory He had before the world began.",
      "The Transfiguration (Week 5) was a momentary revelation of the glory studied here — a glimpse behind the veil of mortality.",
      "Christ's exaltation (Philip. 2:9–11) connects to His role as King (Week 38) and the Millennial Reign (Week 44) where His glory will be fully manifest on earth."
    ],
    teaching: "Moses saw God's glory and then said, 'Now I know that man is nothing.' How can seeing Christ's glory produce both humility and empowerment at the same time?",
    commitment: "This week, look for moments when the glory of Christ breaks through the ordinary — in nature, in worship, in the faces of those around you."
  },
  days: [
    {
      label: "The glory He had before the world",
      focus: "In His great intercessory prayer, Jesus spoke of a glory He shared with the Father before the world existed. Today examines Christ's premortal glory.",
      scriptures: [{book:"John",ch:17,vs:1,ve:5},{book:"John",ch:17,vs:22,ve:24},{book:"D&C",ch:93,vs:1,ve:5}],
      nuances: "In John 17:5, Jesus prays: 'Glorify thou me with thine own self with the glory which I had with thee before the world was.' The Greek 'para seautō' (with thine own self) implies intimate proximity — Christ's premortal glory was not separate from the Father but shared in His very presence. The request is not for new glory but for restored glory — a return to what He had voluntarily set aside.",
      commentary: "John 17 is the most sacred prayer recorded in scripture — Christ's final prayer before Gethsemane. In it, He speaks of a glory He possessed with the Father before creation. This is not aspirational language; it is a statement of premortal reality. Christ was glorified before He ever became mortal. His glory is not earned through mortality — it is intrinsic to His divine nature.\n\nVerses 22–24 extend this glory to His followers: 'The glory which thou gavest me I have given them.' Christ does not hoard His glory. He shares it. The purpose of His mission is not to keep glory for Himself but to bring His children into the same unity and radiance that He shares with the Father. This is the most generous act in all of theology.\n\nD&C 93:1–5 provides Restoration light: every soul who forsakes sins, comes unto Christ, calls on His name, obeys His voice, and keeps His commandments shall see His face and know that He is. John bore record that Christ received a fulness of the glory of the Father, and that He received all power in heaven and on earth. The fulness of divine glory resides in Christ — not partially, not symbolically, but fully.",
      patterns: "The premortal glory of Christ connects to His role as Creator (Week 2). The same glory that existed before creation is the glory that will fill the earth in the Millennium (Week 44). Glory bookends all of history.",
      reflection: "Jesus prayed that His followers would behold and share His glory. What does it mean to you that Christ's ultimate desire is not just to save you but to glorify you?"
    },
    {
      label: "The brightness of the Father's glory",
      focus: "The author of Hebrews describes Christ as the 'brightness of the Father's glory.' Today explores how Christ makes the invisible God visible.",
      scriptures: [{book:"Heb",ch:1,vs:1,ve:3},{book:"2 Cor",ch:4,vs:6},{book:"D&C",ch:88,vs:7,ve:13}],
      nuances: "Hebrews 1:3 describes Christ as the 'apaugasma tēs doxēs' — the radiance or effulgence of God's glory. The word 'apaugasma' means an outshining, like rays from the sun. Christ is not a reflection of the Father's glory (as the moon reflects the sun); He is the direct radiation of it. He is glory going forth — the Father's nature made visible and active.",
      commentary: "Hebrews opens with one of the most exalted Christological statements in the New Testament. God, who spoke through prophets in scattered ways, has now spoken through His Son — who is the brightness of His glory and the express image of His person. Every previous revelation was partial; Christ is the complete disclosure of who God is.\n\nPaul writes in 2 Corinthians 4:6 that God has 'shined in our hearts, to give the light of the knowledge of the glory of God in the face of Jesus Christ.' The glory of God is seen in the face of Christ. This is both literal (those who saw the resurrected Lord saw radiance) and spiritual (those who come to know Christ encounter divine glory through His character, teachings, and love).\n\nD&C 88:7–13 expands this with breathtaking scope: the light of Christ proceeds forth from His presence to fill the immensity of space. It is the light of the sun, the moon, the stars. It is the light that gives life to all things. It is the law by which all things are governed. The glory of Christ is not abstract theology — it is the operating principle of the universe. Every photon is a testimony of His radiance.\n\nTo know Christ's glory is not to be overwhelmed by brightness but to begin to see reality as it truly is — saturated with divine light, sustained by divine power, and pointed toward divine purpose.",
      patterns: "The connection between light and glory runs through all scripture: the pillar of fire, the Shekinah glory in the tabernacle, the Transfiguration, the First Vision, the celestial kingdom described as the glory of the sun. Light is how God makes Himself known.",
      reflection: "Paul says the glory of God is seen 'in the face of Jesus Christ.' When you read about Christ or pray to Him, do you sense that you are encountering glory — the very nature of God?"
    },
    {
      label: "Theophanies of glory",
      focus: "Throughout history, God has revealed His glory to chosen witnesses in overwhelming encounters. Today examines the great theophanies.",
      scriptures: [{book:"Ex",ch:33,vs:18,ve:23},{book:"Isa",ch:6,vs:1,ve:5},{book:"Moses",ch:1,vs:1,ve:11},{book:"JS-H",ch:1,vs:16,ve:17}],
      nuances: "In Exodus 33:20, God tells Moses: 'Thou canst not see my face: for there shall no man see me, and live.' Yet Moses 1:2 says Moses saw God face to face. The resolution lies in the principle of transfiguration — Moses was 'transfigured before him' (Moses 1:11), temporarily endowed with the capacity to endure divine glory. Without this enabling power, mortal bodies cannot withstand God's presence.",
      commentary: "Moses asked to see God's glory, and God granted a partial vision — His back parts, His goodness proclaimed — because the full glory would have consumed Moses in his mortal state. This sets a pattern: divine glory is real, physical, and overwhelming. It is not a metaphor for warm feelings.\n\nIsaiah's vision of the Lord in the temple (Isaiah 6) produced the same effect: the seraphim covered their faces, the temple shook, and Isaiah cried out, 'Woe is me! for I am undone; because I am a man of unclean lips.' The encounter with glory produces simultaneous awe and self-awareness. You cannot see God's greatness without also seeing your own smallness.\n\nMoses 1 in the Pearl of Great Price records a more complete theophany. Moses saw God face to face, spoke with Him, and beheld the world and all its inhabitants. Then the vision withdrew, and Moses fell to the earth, declaring, 'Now, for this cause I know that man is nothing, which thing I never had supposed.' The encounter with glory recalibrated Moses' entire understanding of reality.\n\nThe First Vision (JS-H 1:16–17) stands as the great modern theophany. Joseph Smith saw two Personages whose brightness and glory defied description. One spoke, calling Joseph by name, and introduced the other as His Beloved Son. The glory was real, the Personages were real, and the message was personal. Every other event in the Restoration flows from this encounter with divine glory.",
      patterns: "Theophanies follow a pattern: the mortal is prepared (often through crisis or seeking), the glory appears, the mortal is overwhelmed, and a commission follows. Moses, Isaiah, Joseph Smith — each encounter with glory led to a mission. Glory is not an end in itself; it empowers service.",
      reflection: "Moses said, 'Man is nothing.' Isaiah said, 'I am undone.' Joseph Smith fell to the earth. Why does encountering God's glory produce humility rather than pride? What does this teach about the nature of true greatness?"
    },
    {
      label: "The Transfiguration and the veil",
      focus: "On the mount of Transfiguration, Christ's mortal appearance gave way to His inner glory. Today examines this moment and its meaning.",
      scriptures: [{book:"Matt",ch:17,vs:1,ve:5},{book:"D&C",ch:110,vs:1,ve:4},{book:"3 Ne",ch:19,vs:25}],
      nuances: "Matthew 17:2 says Jesus 'was transfigured before them: and his face did shine as the sun, and his raiment was white as the light.' The Greek 'metemorphōthē' (was transfigured) means to be changed in form — the inner reality broke through the outer appearance. This was not something added to Christ; it was something revealed about Him. His glory was always there, hidden beneath mortality.",
      commentary: "The Transfiguration is one of the most mysterious and important events in the Gospels. Jesus took Peter, James, and John to a high mountain, and His appearance changed. His face shone like the sun. His clothing became brilliant white. Moses and Elijah appeared with Him. The Father's voice spoke from the cloud: 'This is my beloved Son; hear Him.'\n\nThis was not a new glory given to Christ — it was His preexisting glory temporarily unveiled. During His mortal ministry, Christ's divine nature was cloaked in ordinary human appearance. On the mount, the veil was briefly pulled back. The disciples saw what Christ always was beneath the surface of flesh.\n\nD&C 110:1–4 records a latter-day parallel: Joseph Smith and Oliver Cowdery saw the resurrected Lord in the Kirtland Temple. His eyes were as a flame of fire, His hair white like snow, His countenance above the brightness of the sun, and His voice like the sound of rushing waters. The glory was the same — the glory of John 17, the glory of the Mount of Transfiguration, the glory of the premortal council.\n\n3 Nephi 19:25 records that the Nephite disciples were transfigured as they prayed — they became as white as the countenance and garments of Jesus. The glory was shared. When mortals enter the presence of divine glory, they are changed by it. This is not just an ancient event — it is the pattern of sanctification.",
      patterns: "The Transfiguration, the Kirtland Temple vision, and the transfiguration of the Nephite disciples all demonstrate the same principle: divine glory is communicable. It changes those who encounter it. This is the mechanism of exaltation — glory shared transforms the receiver.",
      reflection: "The Transfiguration revealed who Christ truly was beneath His mortal appearance. Do you believe there is more to Christ — and more to you — than what meets the eye?"
    },
    {
      label: "The glory of the Risen Lord",
      focus: "After the Resurrection, Christ's glory was no longer hidden. Today examines the glorified Christ as seen by post-resurrection witnesses.",
      scriptures: [{book:"Rev",ch:1,vs:12,ve:18},{book:"D&C",ch:76,vs:19,ve:24},{book:"Philip",ch:2,vs:9,ve:11}],
      nuances: "In Revelation 1:16, John describes Christ's countenance as 'the sun shineth in his strength.' The Greek 'en tē dunamei autou' (in his strength/power) indicates that this is not reflected light but emitted glory — the sun at its maximum intensity. John, who had leaned against Jesus at the Last Supper, fell at His feet 'as dead' upon seeing His glorified form. The intimacy of mortality gave way to the majesty of exaltation.",
      commentary: "John's vision of the glorified Christ on Patmos is stunning in its detail: He stood among seven golden candlesticks, clothed in a garment to the feet, His hair white, His eyes like flames, His feet like burnished brass, His voice like many waters, and His countenance like the sun in full strength. John, who had known Jesus personally during His mortal life, was so overwhelmed that he collapsed.\n\nThis is what the Resurrection produced: not merely a resuscitated body but a glorified one. The same Jesus who ate fish on the shore of Galilee now radiates the full glory of the Father. Philippians 2:9–11 explains the theological meaning: because Christ humbled Himself and became obedient to death, God has highly exalted Him and given Him a name above every name. The glory is both inherent (He always possessed it) and earned (His mortal obedience merited its full restoration and amplification).\n\nD&C 76:19–24 records Joseph Smith and Sidney Rigdon's vision: they saw the Son on the right hand of God and bore record that He lives. Of Him they testified that He is the Only Begotten of the Father, that by Him, through Him, and of Him the worlds are and were created. The modern witnesses saw the same glory that overwhelmed John on Patmos.\n\nThe glorified Christ is not a different person from the mortal Jesus. He is the same — but now seen as He truly is. The glory that was always present is now fully visible, fully active, fully triumphant.",
      patterns: "The pattern of humiliation followed by exaltation runs through Christ's entire story: premortal glory, mortal condescension, suffering and death, resurrection and glorification. This is also the pattern promised to His followers — through trial, glory.",
      reflection: "John knew Jesus intimately and still fell as dead before His glorified presence. How should this shape the way you approach Christ in worship and prayer?"
    },
    {
      label: "Glory shared with His people",
      focus: "Christ does not keep His glory for Himself. He shares it with those who follow Him. Today explores the doctrine of communicated glory.",
      scriptures: [{book:"2 Cor",ch:3,vs:18},{book:"D&C",ch:76,vs:50,ve:58},{book:"John",ch:17,vs:22}],
      nuances: "2 Corinthians 3:18 says we are 'changed into the same image from glory to glory.' The Greek 'apo doxēs eis doxan' (from glory to glory) describes a progressive transformation — not a sudden leap but an incremental journey of increasing radiance. Sanctification is the process of becoming more and more glorious as we behold and reflect Christ's character.",
      commentary: "Paul's statement in 2 Corinthians 3:18 is among the most hopeful in all scripture: we, beholding the glory of the Lord as in a mirror, are being changed into the same image from glory to glory. The transformation is ongoing. Every time you encounter Christ — in scripture, in the temple, in prayer, in service — you are changed incrementally into His likeness. The glory is communicable.\n\nJohn 17:22 records Christ's own words: 'The glory which thou gavest me I have given them.' This is not a future promise; it is a present reality. The glory that belongs to Christ is being shared with His followers now. It will reach its fulness in the celestial kingdom, but the process has already begun.\n\nD&C 76:50–58 describes those who inherit the celestial kingdom: they are they who received the testimony of Jesus, were baptized, received the Holy Ghost, overcame by faith, and are sealed by the Holy Spirit of promise. These are made perfect through Jesus and dwell in the presence of God and Christ forever. They are priests and kings, having received of His fulness and His glory.\n\nThe destiny of the faithful is not merely to be saved from punishment but to be glorified with Christ. The doctrine of theosis — of becoming like God — is not a peripheral Latter-day Saint teaching. It is the culminating promise of the entire gospel. The glory of Christ is not the end of the story; it is the beginning of yours.",
      patterns: "The sharing of glory follows the same pattern as the sharing of priesthood, covenants, and ordinances — what belongs to Christ is offered to His children. The entire gospel is a system of divine inheritance: what the Father gave the Son, the Son gives to us.",
      reflection: "Paul says we are being changed 'from glory to glory.' Can you identify ways you have grown more like Christ over time? What is the next step in your transformation?"
    },
    {
      label: "Every knee shall bow",
      focus: "There is coming a day when Christ's glory will be universally acknowledged. Today contemplates the ultimate revelation of His glory.",
      scriptures: [{book:"Philip",ch:2,vs:9,ve:11},{book:"D&C",ch:76,vs:108,ve:112},{book:"Rev",ch:5,vs:12,ve:14},{book:"Isa",ch:45,vs:23}],
      nuances: "Philippians 2:10–11 says every knee shall bow — 'epouraniōn kai epigeiōn kai katachthoniōn' — those in heaven, on earth, and under the earth. This is a total, three-realm submission. The confession that Jesus Christ is Lord will be universal, extending even to those who rejected Him. This is not forced worship but the inevitable recognition of reality.",
      commentary: "Paul quotes Isaiah's prophecy in Philippians 2:10–11: at the name of Jesus, every knee shall bow and every tongue confess that He is Lord. This is the final, universal acknowledgment of what has always been true. The glory that was hidden in the manger, veiled in mortality, and rejected at the cross will one day be undeniable. Every soul who has ever lived will know who Jesus Christ is.\n\nRevelation 5:12–14 envisions this scene in heavenly terms: myriads of angels, the four living creatures, the twenty-four elders, and every creature in heaven, on earth, under the earth, and in the sea — all of them declaring that the Lamb is worthy to receive power, riches, wisdom, strength, honor, glory, and blessing. The response is universal and voluntary: Amen.\n\nD&C 76:108–112 adds that even those who inherit the lowest degree of glory will eventually bow the knee and confess that Jesus is the Christ. The recognition may not come in mortality, but it will come. God's patience is infinite, and His glory is patient too — it waits until every heart is ready to acknowledge it.\n\nThis is the ultimate end of the story of Christ's glory: not that it overwhelms and destroys opposition, but that it outlasts it. The glory is so vast, so beautiful, so undeniable that eventually every soul surrenders — not to force but to truth. The glory of Christ is the final argument, and it wins not by compulsion but by being what it is.",
      patterns: "The arc of scripture bends toward universal acknowledgment of Christ. From His hidden birth in a stable to His public return in glory, the trajectory is always the same: from concealment to revelation, from rejection to recognition. The glory that was always present will one day be universally seen.",
      reflection: "Every knee will bow and every tongue confess. What would it mean for you to make that confession fully and willingly now, rather than waiting for the final day?"
    }
  ]
};

export default week48;
