import type { WeekContent } from '../types';

const week47: WeekContent = {
  title: "Good Shepherd — He Knows His Sheep by Name",
  subtitle: "Christ is not a distant ruler but an intimate shepherd who calls, feeds, protects, and lays down His life for His flock.",
  weekScriptures: "Jer 31:10; Ezek 34:23-24; Micah 7:14; Zech 11:4-9; Matt 18:12-14; Mark 6:34; Heb 13:20-21; 1 Pet 5:4; Matt 25:32-33; Alma 5:41-42; Gen 49:24",
  synthesis: {
    summary: "The image of the shepherd is among the most personal and tender in all scripture. Christ did not choose the title of general, philosopher, or emperor — He called Himself the Good Shepherd. This week explores what that title means: He knows each sheep individually, He leads rather than drives, He provides green pastures and still waters, He searches for the lost, and He lays down His life voluntarily. No other title captures the combination of authority and intimacy that defines Christ's relationship with His people.",
    connections: [
      "The Good Shepherd lays down His life — connecting directly to the Atonement (Weeks 14–15), where the Shepherd became the Lamb.",
      "Christ's role as Shepherd relates to His role as the 'Seed of' (Week 45): the Shepherd calls His flock, and they become His children.",
      "The gathering of scattered Israel (Week 31) is the work of the Shepherd gathering His lost sheep from the four corners of the earth."
    ],
    teaching: "What is the difference between a hireling and a shepherd? How does this distinction apply to leadership, teaching, and ministry in your own life?",
    commitment: "This week, listen for the Shepherd's voice in your daily life — in scripture, in prayer, in the words of others. Can you recognize it?"
  },
  days: [
    {
      label: "I am the Good Shepherd",
      focus: "Jesus declared 'I am the good shepherd' — one of the great 'I Am' statements. Today examines the core meaning of this self-identification.",
      scriptures: [{book:"John",ch:10,vs:1,ve:18},{book:"D&C",ch:50,vs:44}],
      nuances: "In John 10:11, 'good' translates the Greek 'kalos' — which means not merely morally good but beautiful, noble, ideal. Christ is not claiming to be an adequate shepherd; He is claiming to be the model, the archetype, the perfect Shepherd against whom all others are measured. 'Kalos' carries aesthetic and moral weight: this is shepherding at its most beautiful.",
      commentary: "John 10 is one of the most carefully structured discourses in the Gospels. Jesus builds an extended metaphor: the shepherd enters through the door (not by climbing over the wall like a thief), the sheep hear his voice, he calls them by name, and he leads them out. Then comes the central declaration: 'I am the good shepherd: the good shepherd giveth his life for the sheep.'\n\nThe contrast with the hireling is critical. The hireling cares for the sheep because he is paid to do so. When the wolf comes, he flees — because the sheep are not his. The shepherd stays because the sheep belong to him. Christ's ministry is not professional obligation; it is personal ownership rooted in love.\n\nD&C 50:44 adds a Restoration dimension: 'I am the good shepherd, and the stone of Israel.' The combination of shepherd (tender, personal) and stone (immovable, foundational) captures the paradox of Christ: He is both gentle enough to carry a lamb and strong enough to be the foundation of everything.\n\nIn the ancient Near East, a shepherd's job was dangerous, unglamorous, and low-status. Shepherds slept in the open, fought predators, and spent long stretches in isolation. That Jesus chose this image — not king, not priest, not warrior — as His primary self-description tells us something essential about how He sees His relationship with us.",
      patterns: "Each of Christ's 'I Am' statements in John reveals a different dimension of His mission: bread, light, door, vine, resurrection, and shepherd. The shepherd image is the most relational — it is about personal knowledge and sacrificial love.",
      reflection: "Christ calls His sheep by name. Do you believe He knows you personally — not just as part of a flock but as an individual? What evidence do you have of this?"
    },
    {
      label: "He leads beside still waters",
      focus: "Psalm 23 is the most beloved psalm in the world. Today we read it not as poetry but as theology — a precise description of how Christ shepherds His people.",
      scriptures: [{book:"Ps",ch:23,vs:1,ve:6},{book:"Isa",ch:40,vs:11},{book:"1 Ne",ch:22,vs:25}],
      nuances: "Psalm 23:1, 'The Lord is my shepherd; I shall not want,' uses the Hebrew 'Yahweh ro'i' — the personal name of God combined with the intimate word for shepherd. David is not speaking abstractly; he is saying that the covenant God of Israel personally tends him. The phrase 'I shall not want' (Hebrew 'lo echsar') means 'I will lack nothing' — a statement of total sufficiency.",
      commentary: "Psalm 23 is so familiar that its radicalism can be missed. David — a king, a warrior, a man of great power — describes himself as a sheep. He does not boast of his own strength; he rests in the Shepherd's care. Green pastures, still waters, restored soul, right paths — these are not luxuries but necessities, and the Shepherd provides them all.\n\nThe psalm moves from provision (verses 1–3) to protection (verse 4: the valley of the shadow of death) to honor (verse 5: a table prepared before enemies) to eternal promise (verse 6: dwelling in the house of the Lord forever). It is a complete map of the Shepherd's care across an entire life — and beyond it.\n\nIsaiah 40:11 adds tenderness: He shall feed His flock like a shepherd, gather the lambs with His arm, carry them in His bosom, and gently lead those that are with young. The image of carrying lambs in His bosom is one of the most intimate in all scripture. This is not management from a distance; this is the warmth of a body pressed against a body.\n\n1 Nephi 22:25 confirms that this Shepherd will gather His children from the four quarters of the earth. The Book of Mormon applies the shepherd image to the global gathering of Israel — the same personal care, extended to nations and dispensations.",
      patterns: "The Shepherd provides, protects, and guides — the same three functions of the Atonement. Christ provides grace, protects from spiritual death, and guides through the Holy Spirit. Psalm 23 is a miniature Atonement theology.",
      reflection: "Which image from Psalm 23 speaks most to your current situation — green pastures, still waters, the valley of shadow, or the table before your enemies? Why?"
    },
    {
      label: "Seeking the lost sheep",
      focus: "The Shepherd does not wait for lost sheep to return on their own — He goes after them. Today examines the doctrine of divine pursuit.",
      scriptures: [{book:"Luke",ch:15,vs:3,ve:7},{book:"Ezek",ch:34,vs:11,ve:16},{book:"Alma",ch:5,vs:37,ve:39}],
      nuances: "In Luke 15:4, Jesus asks: 'What man of you, having an hundred sheep, if he lose one of them, doth not leave the ninety and nine in the wilderness, and go after that which is lost, until he find it?' The Greek 'heos heurei auto' (until he find it) is emphatic: the shepherd does not give up after a reasonable search. He searches until the search succeeds.",
      commentary: "The parable of the lost sheep is one of the most important stories Jesus ever told, and its context matters enormously. Jesus told it in response to the Pharisees' complaint that He was eating with sinners. His answer redefined the entire discussion: God is not a judge annoyed by sinners; He is a shepherd who leaves the ninety-nine to find the one.\n\nThe mathematics are absurd by worldly standards. No rational manager would risk ninety-nine sheep for one. But this is not management — it is love. The one lost sheep is not a statistic; it is a soul known by name. And when the shepherd finds it, he does not scold it — he lays it on his shoulders, rejoicing.\n\nEzekiel 34:11–16 expands this from parable to prophecy. God Himself declares: 'I, even I, will both search my sheep, and seek them out.' He will deliver them from all places where they have been scattered, feed them on the mountains of Israel, bind up the broken, and strengthen the sick. This is not gentle poetry — it is a divine commitment.\n\nAlma 5:37–39 applies this to those who have heard the gospel but turned away. The good shepherd calls, but some will not hearken. Alma's anguish is palpable: the Shepherd is calling — why will they not come? The invitation is always open, but it requires a response.",
      patterns: "The pattern of seeking the lost appears across dispensations: Enoch sought the scattered, Moses sought Israel in the wilderness, Christ sought sinners in Galilee, and missionaries seek converts today. The Shepherd's work of seeking is never finished.",
      reflection: "Have you ever been the lost sheep — wandering, confused, far from the flock? How did the Shepherd find you? Or is He seeking you now?"
    },
    {
      label: "He knows His sheep",
      focus: "The Shepherd's relationship with His sheep is not institutional but intimate. Today explores the doctrine of divine personal knowledge.",
      scriptures: [{book:"John",ch:10,vs:27,ve:30},{book:"Mosiah",ch:26,vs:20,ve:21},{book:"3 Ne",ch:18,vs:31}],
      nuances: "John 10:27 — 'My sheep hear my voice, and I know them, and they follow me' — uses the Greek 'ginōskō' for 'know.' This is not intellectual awareness but relational, experiential knowledge. It is the same word used for the deepest forms of human knowing. Christ does not know about His sheep; He knows them — their struggles, their hopes, their names.",
      commentary: "John 10:27–30 contains some of the most comforting words in the New Testament. Christ's sheep hear His voice. He knows them. They follow Him. He gives them eternal life. They shall never perish. No one can pluck them from His hand. The security described here is not conditional on the sheep's strength but on the Shepherd's grip.\n\nMosiah 26:20–21 records the Lord's personal words to Alma: 'Thou art my servant; and I covenant with thee that thou shalt have eternal life; and thou shalt serve me and go forth in my name, and shalt gather together my sheep.' The Lord called Alma by identity ('my servant'), gave him a personal covenant, and commissioned him to do the Shepherd's work. This is how Christ operates — personally, covenantally, by name.\n\n3 Nephi 18:31 adds an important pastoral instruction: Christ commands His disciples not to cast anyone out of their worship services but to continue to minister to them. Even those who are not yet fully gathered are not to be abandoned. The Shepherd's patience extends through His under-shepherds.\n\nThe doctrine of divine personal knowledge is one of the most important truths in the gospel. You are not a number in a celestial database. You are a sheep known by name to a Shepherd who left heaven to find you.",
      patterns: "Personal knowledge is a divine attribute that recurs throughout scripture: God called Moses by name at the burning bush, called Samuel by name in the night, and called Joseph by name in the grove. The Shepherd always knows the name of the sheep He is calling.",
      reflection: "Christ says, 'I know my sheep.' Do you believe He knows you — your specific situation, your particular struggles, your individual hopes? What would change if you fully trusted that?"
    },
    {
      label: "The Shepherd lays down His life",
      focus: "What makes this Shepherd 'good' is not only that He leads and feeds but that He dies for His flock. Today examines the voluntary nature of Christ's sacrifice.",
      scriptures: [{book:"John",ch:10,vs:15,ve:18},{book:"Heb",ch:13,vs:20},{book:"1 Pet",ch:2,vs:25}],
      nuances: "John 10:18 is doctrinally extraordinary: 'No man taketh it from me, but I lay it down of myself. I have power to lay it down, and I have power to take it again.' The Greek 'exousian echo' (I have authority/power) appears twice — Christ has the authority both to die and to rise. His death was not forced upon Him; it was an exercise of divine power, not a surrender of it.",
      commentary: "The Good Shepherd discourse reaches its climax in John 10:15–18. The shepherd lays down his life for the sheep — not accidentally, not reluctantly, but voluntarily. 'No man taketh it from me.' The Roman soldiers, the Jewish leaders, Pilate — none of them had the power to kill Jesus. He chose to die. The cross was not a tragedy that happened to Christ; it was a mission He accepted.\n\nThis changes everything about how we understand the Atonement. It was not a cosmic accident or an unfortunate consequence of political conflict. It was the deliberate, voluntary, authoritative act of the Shepherd who loved His sheep enough to die for them — and powerful enough to take His life back again.\n\nHebrews 13:20 calls God 'the God of peace, that brought again from the dead our Lord Jesus, that great shepherd of the sheep, through the blood of the everlasting covenant.' The blood and the covenant are inseparable. The Shepherd's death sealed an everlasting covenant — a permanent bond between God and His people, ratified in blood.\n\n1 Peter 2:25 addresses the sheep directly: you were as sheep going astray, but are now returned unto the Shepherd and Bishop of your souls. The word 'Bishop' (Greek 'episkopos') means overseer — one who watches over. The Shepherd who died for you now watches over you. His death was not the end of His care; it was the ultimate expression of it.",
      patterns: "The Shepherd who lays down His life is also the Lamb who was slain (Revelation 5). The titles merge: the one who protects the flock becomes the sacrifice that saves the flock. Shepherd and Lamb are two sides of the same love.",
      reflection: "Christ's death was voluntary — 'No man taketh it from me.' How does knowing His sacrifice was chosen, not forced, affect the way you receive it?"
    },
    {
      label: "Other sheep I have",
      focus: "Christ told His disciples in Jerusalem that He had 'other sheep' not of that fold. Today examines this statement and its fulfillment in 3 Nephi.",
      scriptures: [{book:"John",ch:10,vs:16},{book:"3 Ne",ch:15,vs:17,ve:21},{book:"3 Ne",ch:16,vs:1,ve:3}],
      nuances: "John 10:16 — 'Other sheep I have, which are not of this fold: them also I must bring' — uses the Greek 'dei' for 'must,' indicating divine necessity. This was not optional outreach; it was a covenantal obligation. The Shepherd was bound by His own love and His Father's will to visit all His sheep, wherever they were scattered.",
      commentary: "John 10:16 is one of the most intriguing verses in the New Testament. Jesus speaks of 'other sheep' that are not of the fold in Jerusalem. Most Christian interpreters have understood this as a reference to Gentile believers. Latter-day Saints read it with additional light: the resurrected Christ Himself explained the passage to the Nephites.\n\nIn 3 Nephi 15:17–21, Christ declares to the people gathered at the temple in Bountiful: 'Ye are they of whom I said: Other sheep I have which are not of this fold.' The Nephites were the other sheep. Christ visited them after His resurrection, ministered among them, taught them, blessed their children, and established His Church. The promise of John 10:16 was literally, physically fulfilled.\n\n3 Nephi 16:1–3 reveals even more: there were still other sheep — the lost tribes of Israel scattered to other locations. Christ would visit them also. The scope of the Shepherd's ministry extends beyond any single continent or people. Every scattered branch of Israel would hear the Shepherd's voice.\n\nThis is one of the most distinctive contributions of the Book of Mormon to Christian theology: the Good Shepherd did not limit His post-resurrection ministry to Jerusalem. He went wherever His sheep were. The gospel is not a Western story or an Eastern story — it is a universal story, told on every land where covenant children dwell.",
      patterns: "The pattern of Christ visiting multiple peoples connects to the doctrine of gathering (Week 31) and the global scope of the Abrahamic covenant. The Shepherd's fold is not one pen in one country — it is every place where a faithful heart responds to His voice.",
      reflection: "Christ had 'other sheep' that His original disciples did not know about. Are there people in your life whom Christ loves and claims that you have overlooked or underestimated?"
    },
    {
      label: "Feed my sheep",
      focus: "After His resurrection, Christ commissioned Peter with a simple, repeated charge: feed my sheep. Today examines the ongoing work of the Shepherd through His servants.",
      scriptures: [{book:"John",ch:21,vs:15,ve:17},{book:"Alma",ch:5,vs:57,ve:60},{book:"1 Pet",ch:5,vs:1,ve:4}],
      nuances: "In John 21:15–17, Jesus asks Peter three times 'Do you love me?' and three times commands him to feed or tend His sheep. The repetition echoes Peter's three denials. But the Greek also shifts: Jesus first uses 'agapaō' (divine, selfless love) and Peter responds with 'phileō' (affectionate, brotherly love). On the third question, Jesus descends to Peter's word — meeting him where he is. The exchange is simultaneously a restoration, a commission, and a lesson in pastoral humility.",
      commentary: "The scene on the shore of Galilee after the Resurrection is one of the most moving in scripture. Jesus has prepared breakfast for His disciples. Then He turns to Peter — the disciple who denied Him three times — and asks, three times, 'Do you love me?' Each time Peter affirms his love, Jesus gives the same commission: feed my lambs, tend my sheep, feed my sheep.\n\nThis is how the Shepherd extends His ministry: through under-shepherds. Peter is not replacing Christ; he is being given the privilege of continuing Christ's work. The sheep still belong to Christ — 'my sheep,' Jesus says, not 'your sheep.' Every bishop, Relief Society president, home teacher, and parent who feeds and tends God's children is participating in the Good Shepherd's ongoing ministry.\n\nAlma 5:57–60 contains a parallel commission: the Good Shepherd calls, and those who hear must separate themselves from the wicked and come into His fold. The names of the righteous will be written; the names of the unrepentant will be blotted out. The Shepherd's call is both invitation and accountability.\n\n1 Peter 5:1–4 brings the image full circle: Peter, now an aged apostle, instructs other leaders to feed the flock of God — not by compulsion but willingly, not for money but eagerly, not lording over them but being examples. When the Chief Shepherd appears, they will receive a crown of glory. The under-shepherd serves; the Chief Shepherd rewards.",
      patterns: "The commission 'Feed my sheep' has been repeated to every prophet and apostle in every dispensation. It is the defining work of Christ's Church: not institutional maintenance but soul-by-soul shepherding.",
      reflection: "Christ asked Peter, 'Do you love me?' and then said, 'Feed my sheep.' Who are the sheep Christ has given you to feed — in your family, your ward, your community? How are you feeding them?"
    }
  ]
};

export default week47;
