import type { WeekContent } from '../types';

const week49: WeekContent = {
  title: "Birth of Jesus Christ — The Word Made Flesh",
  subtitle: "Christmas week: the God of heaven entered the world as a helpless infant, and nothing has been the same since.",
  weekScriptures: "Luke 2:40; Luke 2:46-52; Matt 1:21; 2 Ne 17:14; Mosiah 3:9-10; Hel 14:12; Alma 7:11-12; Gen 3:15; Rev 12:1-5; Matt 2:6; D&C 93:12-14",
  synthesis: {
    summary: "This is Christmas week — the celebration of the most consequential birth in the history of the universe. The Creator of worlds became an infant. The King of Kings was laid in a manger. Angels sang to shepherds, a star guided wise men, and prophets on two continents bore witness. Every week of this study has explored some facet of who Jesus Christ is; this week, we return to where it all began in mortality — a young mother, a stable, a night that split history in two. The birth of Christ is the hinge of eternity: everything before it pointed forward; everything after it looks back.",
    connections: [
      "The condescension of God (Week 1, Day 2) reaches its most literal expression here — the Almighty becomes a newborn.",
      "The Davidic Descent (Week 46) is why Jesus was born in Bethlehem — Joseph's ancestral city — fulfilling Micah's ancient prophecy.",
      "The doctrine of the Incarnation connects to Week 45 (Seed of Christ): because He took on flesh, we can be spiritually reborn as His children."
    ],
    teaching: "Why did the God of the universe choose to enter the world as a helpless baby in a manger rather than as a conquering king in a palace? What does this tell us about the nature of divine power?",
    commitment: "This Christmas week, let the birth of Christ renew your wonder. Read Luke 2 aloud with someone you love. Let the story be new again."
  },
  days: [
    {
      label: "Prophesied for centuries",
      focus: "The birth of Christ was foretold by prophets across centuries and continents. Today traces the prophetic anticipation — the long wait for the promised child.",
      scriptures: [{book:"Isa",ch:7,vs:14},{book:"Isa",ch:9,vs:6,ve:7},{book:"Micah",ch:5,vs:2},{book:"1 Ne",ch:11,vs:13,ve:21}],
      nuances: "Isaiah 7:14 uses the Hebrew 'almah' (young woman), which the Septuagint translated as 'parthenos' (virgin). Matthew, writing in Greek, used the Septuagint's translation, making the virgin birth explicit. The Book of Mormon, revealed through a separate prophetic line, independently confirms the virgin birth (1 Nephi 11:18–20), providing a second hemispheric witness to the same miraculous event.",
      commentary: "Seven hundred years before Bethlehem, Isaiah prophesied that a virgin would conceive and bear a son called Immanuel — God with us. Isaiah 9:6 expanded the vision: this child would be called Wonderful, Counsellor, The Mighty God, The Everlasting Father, The Prince of Peace. The titles are staggering — they are divine attributes applied to a baby. No ordinary child bears such names.\n\nMicah 5:2 identified the location: Bethlehem Ephratah, a village so small it was barely counted among the clans of Judah. The God of the universe chose the smallest, most insignificant place to make His entrance. This is a deliberate theological statement: divine power does not need human grandeur.\n\nNephi, six hundred years before the birth and an ocean away, saw the vision: a virgin most beautiful and fair, bearing a child in her arms — the Lamb of God, the Son of the Eternal Father. The angel asked Nephi: 'Knowest thou the condescension of God?' This is the question the entire nativity answers. The condescension is not simply that God became human; it is that He became an infant — dependent, vulnerable, wrapped in cloth and laid in a feeding trough.\n\nThe long prophetic wait — centuries of anticipation — tells us something about how God works. He does not rush. He prepares, promises, and then fulfills in the fulness of time. The birth of Christ was the most anticipated event in human history, and it came exactly when and where it was supposed to.",
      patterns: "The pattern of prophecy followed by long waiting and eventual fulfillment recurs throughout scripture: the promise to Abraham waited generations, the promise to David waited a millennium, and the promise of Christ's birth waited centuries. God's timing is perfect, even when it requires extraordinary patience.",
      reflection: "The prophets waited centuries for the birth they foretold. What promises from God are you currently waiting to see fulfilled? What does the nativity teach you about divine timing?"
    },
    {
      label: "The annunciation to Mary",
      focus: "An angel appeared to a young woman in Nazareth and announced that she would bear the Son of God. Today we stand with Mary at the moment everything changed.",
      scriptures: [{book:"Luke",ch:1,vs:26,ve:38},{book:"Luke",ch:1,vs:46,ve:55},{book:"Alma",ch:7,vs:10}],
      nuances: "Luke 1:28 records the angel's greeting: 'Hail, thou that art highly favoured' — in Greek, 'kecharitōmenē,' a perfect passive participle meaning 'one who has been graced.' Mary is not merely receiving a favor; she has been prepared by grace for this moment. The word implies a completed prior action — God had already been at work in her life before Gabriel arrived.",
      commentary: "The annunciation is one of the most intimate scenes in scripture. Gabriel appears to Mary — a young woman, probably a teenager, in the insignificant town of Nazareth — and announces that she will conceive by the power of the Holy Ghost and bear a son called Jesus. He will be great, He will be called the Son of the Highest, and of His kingdom there shall be no end.\n\nMary's response is a model of faithful courage: 'Behold the handmaid of the Lord; be it unto me according to thy word.' She did not fully understand what was being asked of her. She knew it would be socially devastating — an unwed pregnancy in first-century Jewish culture could mean ostracism or worse. Yet she consented. Her 'yes' to God is one of the bravest acts in all of human history.\n\nHer song — the Magnificat in Luke 1:46–55 — is a masterpiece of prophetic poetry. Mary declares that God has regarded the low estate of His handmaiden, has scattered the proud, put down the mighty, exalted the humble, and filled the hungry. She understood that the birth of her son was not merely personal good news — it was the revolution of the world's value system. God was overturning everything.\n\nAlma 7:10 confirms from the Book of Mormon that the mother of the Son of God would be called Mary — a prophetic detail delivered on a separate continent, centuries after Isaiah and centuries before Luke. The convergence of witnesses is remarkable.",
      patterns: "God consistently chooses the humble and unlikely for His greatest works: a young woman for the Incarnation, shepherds for the first announcement, a stable for the birthplace. The pattern of divine inversion — last becoming first, small becoming great — is the signature of the nativity.",
      reflection: "Mary said 'yes' to God without fully understanding the cost. When has God asked something of you that required trust beyond understanding? How did you respond?"
    },
    {
      label: "Born in Bethlehem",
      focus: "The night itself. The manger, the swaddling clothes, the glory of the Lord shining around the shepherds. Today we enter the Christmas story.",
      scriptures: [{book:"Luke",ch:2,vs:1,ve:20},{book:"Mosiah",ch:3,vs:5,ve:8},{book:"Hel",ch:14,vs:1,ve:6}],
      nuances: "Luke 2:7 says Mary 'wrapped him in swaddling clothes, and laid him in a manger; because there was no room for them in the inn.' The Greek 'kataluma' (translated 'inn') more likely refers to a guest chamber in a private home — the upper room was full, so the family was lodged in the lower level where animals were kept. The manger (phatnē) was a stone or wooden feeding trough. The King of the universe took His first breaths in a space meant for livestock.",
      commentary: "Luke's account of the birth is simple and powerful. A decree from Caesar Augustus required a census. Joseph traveled from Nazareth to Bethlehem — David's city — because he was of David's lineage. There, in circumstances of poverty and displacement, Mary gave birth to her firstborn son, wrapped Him in strips of cloth, and laid Him in an animal's feeding trough.\n\nThe contrast is almost unbearable. The God who spoke worlds into existence entered His own creation as a baby who could not speak, could not walk, could not feed Himself. The hands that formed the stars needed a mother's arms to hold them. This is the condescension of God — not merely becoming human but becoming helpless.\n\nAngels announced the birth — not to the powerful or the religious establishment but to shepherds keeping watch over their flocks at night. The announcement came with glory: the glory of the Lord shone round about them. Then the heavenly host sang: glory to God in the highest, and on earth peace, good will toward men. Heaven could not contain its joy.\n\nMosiah 3:5–8 records the angel's words to King Benjamin about this same birth: the Lord Omnipotent who reigns in heaven would come down among the children of men, dwell in a tabernacle of clay, and go forth among men working mighty miracles. Helaman 14 records Samuel the Lamanite's prophecy of signs: a night without darkness, a new star, and great lights in heaven. On two continents, the heavens testified.",
      patterns: "The birth of Christ inverts every expectation: the King is born in poverty, announced to the lowly, and laid in a manger. This pattern of divine inversion continues throughout His life — He washes feet, dines with sinners, and dies between criminals. Power expressed through humility is the signature of Christ.",
      reflection: "There was no room in the inn. Is there room for Christ in your life this Christmas — not just in a general sense, but in the specific, crowded, busy reality of this week?"
    },
    {
      label: "Wise men and a guiding star",
      focus: "Wise men from the East followed a star to find the newborn King. Today explores the Gentile witness and the star of Bethlehem.",
      scriptures: [{book:"Matt",ch:2,vs:1,ve:12},{book:"Hel",ch:14,vs:5,ve:6},{book:"3 Ne",ch:1,vs:13,ve:21}],
      nuances: "Matthew 2:2 says the wise men saw 'his star in the east.' The Greek 'aster' could refer to a star, a comet, a planetary conjunction, or a supernatural light. Whatever its astronomical nature, its theological significance is clear: even the heavens declared the birth of the King. The wise men (Greek 'magoi') were likely Zoroastrian scholars from Persia — Gentiles who recognized through their own traditions that a great King had been born in Israel.",
      commentary: "Matthew's account introduces figures who are unexpected at a Jewish Messiah's birth: Gentile scholars from the East. They had seen a star — whether a natural astronomical event given prophetic significance or a supernatural phenomenon — and interpreted it as announcing the birth of a King. They traveled a great distance, at great expense, to worship.\n\nTheir arrival in Jerusalem created a political earthquake. Herod was troubled — a rival king was intolerable. The chief priests and scribes identified Bethlehem as the prophesied birthplace (Micah 5:2) but apparently felt no urgency to go and see for themselves. The irony is sharp: the Gentile seekers found the Messiah while the professional theologians stayed home.\n\nHelaman 14:5–6 records Samuel the Lamanite's prophecy of the sign: a new star unlike any they had seen. 3 Nephi 1:13–21 records the fulfillment on the American continent: the sign was given, the night without darkness came, and many fell to the earth in astonishment. The star was seen by the wise men in the East and the Nephites in the West. The birth of Christ was a hemispheric event, witnessed across the world.\n\nThe wise men brought gifts of gold, frankincense, and myrrh — gifts traditionally interpreted as symbols of kingship, divinity, and burial. From the moment of His birth, the shadow of the cross was present. The gifts acknowledged who He was and what He would do.",
      patterns: "Gentiles recognizing the Messiah before some of Israel's own leaders is a pattern that recurs throughout Christ's life: the Roman centurion's faith, the Syrophoenician woman's persistence, Pilate's wife's dream. God's reach has never been limited to one people.",
      reflection: "The wise men traveled far to find Christ and worship Him. What journey — physical, emotional, or spiritual — has brought you to Christ? What did you bring with you?"
    },
    {
      label: "Simeon, Anna, and patient witnesses",
      focus: "In the temple, an aged man and a devoted prophetess recognized the infant Jesus as the promised Savior. Today honors the faithful who waited a lifetime.",
      scriptures: [{book:"Luke",ch:2,vs:25,ve:35},{book:"Luke",ch:2,vs:36,ve:38},{book:"D&C",ch:93,vs:1,ve:5}],
      nuances: "Luke 2:25 describes Simeon as 'waiting for the consolation of Israel.' The Greek 'paraklēsis' (consolation) carries the same root as 'paraklētos' (comforter/advocate) — the term used for the Holy Spirit in John 14. Simeon was waiting for the ultimate Comforter, and the Holy Ghost had promised him he would not die before seeing the Lord's Christ. His entire life was oriented around this promise.",
      commentary: "Simeon had been promised by the Holy Ghost that he would not see death before he saw the Lord's Christ. When Mary and Joseph brought the infant Jesus to the temple for the customary dedication, Simeon took the child in his arms and spoke words of extraordinary beauty: 'Lord, now lettest thou thy servant depart in peace, according to thy word: For mine eyes have seen thy salvation.'\n\nThis is one of the most poignant moments in the nativity narrative. An old man, at the end of a long life of waiting, holds a baby and declares that his life is now complete. He has seen salvation — not as a concept but as a person, an infant, a warm body in his arms. The God he had served his whole life was now resting against his chest.\n\nSimeon also prophesied to Mary that a sword would pierce through her own soul — a foreshadowing of the cross. Even in the tenderness of the temple presentation, the full cost of the Incarnation was acknowledged.\n\nAnna, described as a prophetess, was eighty-four years old. She had served in the temple with fasting and prayer day and night. When she saw the child, she gave thanks and spoke of Him to all who were looking for the redemption of Jerusalem. Her lifetime of devotion had prepared her to recognize the Messiah when others walked right past.\n\nD&C 93:1–5 teaches that those who forsake their sins and come unto Christ will see His face and know that He is. Simeon and Anna embody this promise — their lives of faithfulness opened their eyes to see what others could not.",
      patterns: "The pattern of long, patient faithfulness rewarded by divine encounter appears throughout scripture: Abraham waited for a son, Israel waited for deliverance, Simeon waited for the Messiah. God honors those who wait with faith.",
      reflection: "Simeon and Anna waited their entire lives for a promise to be fulfilled. What does their example teach you about patience, faithfulness, and the timing of God's promises in your own life?"
    },
    {
      label: "God with us — the theology of incarnation",
      focus: "The birth of Christ is not just a story — it is the central doctrine of the Christian faith. Today explores what it means that God became human.",
      scriptures: [{book:"John",ch:1,vs:1,ve:14},{book:"Philip",ch:2,vs:5,ve:8},{book:"Gal",ch:4,vs:4},{book:"Matt",ch:1,vs:18,ve:25}],
      nuances: "Philippians 2:7 says Christ 'made himself of no reputation' — the Greek 'ekenōsen' means He emptied Himself. This is the doctrine of kenosis: the voluntary self-emptying of the divine Son. He did not cease to be God, but He set aside the exercise of His divine prerogatives to become fully human. The Incarnation is not God pretending to be human; it is God truly becoming human while remaining divine.",
      commentary: "John 1:14 states the doctrine with breathtaking simplicity: the Word became flesh and dwelt among us. The Greek 'eskēnōsen' (dwelt/tabernacled) echoes the Old Testament tabernacle — God's dwelling place among Israel. In Christ, God no longer dwells in a tent or a temple; He dwells in a human body. The body of Jesus is the ultimate temple.\n\nPhilippians 2:5–8 traces the full arc: Christ, being in the form of God, did not consider equality with God something to be grasped but emptied Himself, took the form of a servant, was made in the likeness of men, and humbled Himself to the point of death on a cross. This is the most concise summary of the entire Christ story — from premortal glory through incarnation, humiliation, and death.\n\nGalatians 4:4 places this in covenantal time: 'When the fulness of the time was come, God sent forth his Son, made of a woman, made under the law.' The birth was not random — it was timed, purposed, and placed within the covenant framework. Made of a woman: fully human. Made under the law: subject to the same commandments and conditions as everyone else.\n\nMatthew 1:23 quotes Isaiah: 'They shall call his name Emmanuel, which being interpreted is, God with us.' The name is the doctrine. God is not above us, beyond us, or indifferent to us. He is with us. The manger declares it. The cross confirms it. The Resurrection seals it forever.",
      patterns: "The Incarnation is the center point of the entire fifty-week study. Every role of Christ — Creator, Lawgiver, Prophet, Priest, King, Judge, Shepherd — is exercised through one who became human. The doctrine of 'God with us' is the foundation of everything.",
      reflection: "Emmanuel means 'God with us.' During this Christmas season, where do you most need to feel the reality of God's presence — not above you, not far away, but with you?"
    },
    {
      label: "Let earth receive her King",
      focus: "Christmas Day and beyond. Today we celebrate, reflect, and let the full weight of the nativity settle into our hearts.",
      scriptures: [{book:"Luke",ch:2,vs:10,ve:14},{book:"Matt",ch:2,vs:13,ve:23},{book:"3 Ne",ch:1,vs:15,ve:21},{book:"Mosiah",ch:3,vs:5,ve:8}],
      nuances: "Luke 2:10–11 contains the angelic announcement: 'Fear not: for, behold, I bring you good tidings of great joy, which shall be to all people. For unto you is born this day in the city of David a Saviour, which is Christ the Lord.' The Greek 'euangelizomai' (I bring good tidings) is the verb from which 'gospel' (euangelion) derives. The first gospel sermon was preached by angels to shepherds on the night Christ was born.",
      commentary: "The angels' message to the shepherds is the gospel in miniature: fear not, great joy, all people, a Savior, Christ the Lord. Every element of the Christian message is compressed into two verses. The good news is not for a select few — it is for all people. And the good news is a Person: a Savior born, who is Christ the Lord.\n\nBut the nativity is not all glory and song. Matthew 2:13–23 records the darker side: Herod, threatened by the newborn King, ordered the slaughter of Bethlehem's infants. Joseph was warned in a dream and fled with Mary and Jesus to Egypt. The Incarnation placed God's Son in a world of violence, political cruelty, and refugee flight. The baby in the manger became a refugee in Egypt. Christ entered not a sanitized world but the real one — with all its brutality.\n\n3 Nephi 1:15–21 records the sign of Christ's birth in the New World: a night without darkness, followed by the rising of a new star. The Nephites who had believed Samuel's prophecy were vindicated; those who had mocked were astonished. Even on the other side of the world, the birth of Christ was marked by heaven.\n\nMosiah 3:5–8 places the birth within the cosmic frame: the Lord Omnipotent who reigns from all eternity to all eternity descended from heaven, dwelt among the children of men, and suffered temptation, pain, hunger, thirst, and fatigue, even more than man can suffer. The Christmas story is not only about a baby born in Bethlehem — it is about the Almighty choosing to enter suffering so that suffering could be redeemed.\n\nThis Christmas, let the story be new. Let the wonder break through the familiarity. The God who sustains every atom of the universe lay in a manger and needed His mother's milk. This is the good news. This is the gospel. This is the joy that the angels sang about.",
      patterns: "The birth narratives contain the full gospel in seed form: prophecy fulfilled, divine condescension, witness by humble people, opposition from the powerful, and signs in the heavens. Every theme in Christ's life is present at His birth. The manger is a microcosm of the entire plan of salvation.",
      reflection: "As this Christmas week closes, what has this study of Christ's birth renewed or deepened in you? What will you carry forward from the manger into the rest of the year?"
    }
  ]
};

export default week49;
