import type { WeekContent } from '../types';

const week08: WeekContent = {
  title: "Jehovah — The God of the Old Testament",
  subtitle: "The God who spoke to Abraham, parted the Red Sea, and thundered from Sinai is the premortal Jesus Christ.",
  weekScriptures: "Ex 15:2-3; Isa 41:14; Isa 48:17; Isa 54:5; Hosea 13:4; Zech 14:9; Rev 1:8; 3 Ne 11:14; Ether 4:7-8; D&C 39:1-2; D&C 43:34; Mosiah 7:19",
  synthesis: {
    summary: "One of the most distinctive and consequential teachings of Restoration theology is the identification of Jehovah — the covenant God of Israel throughout the Old Testament — as the premortal Jesus Christ. This means that every divine act recorded in the Hebrew Bible, from the creation to the Exodus to the prophetic visions, was performed by the same being who would later be born in Bethlehem. The God of Abraham, Isaac, and Jacob is Jesus of Nazareth.",
    connections: [
      "Week 5 (Appearances, Antemortal) showed Christ appearing to prophets — this week identifies Him as the specific divine being they encountered: Jehovah.",
      "Week 6 (Creator) taught that Christ created the heavens and the earth — this week confirms that the Creator-God of Genesis 1 is Jehovah, the premortal Christ.",
      "Week 7 (Foreordained & Firstborn) showed Christ's premortal status — this week shows how that status was expressed throughout Old Testament history."
    ],
    teaching: "How does knowing that Jesus Christ is the Jehovah of the Old Testament change the way you read the Hebrew Bible? What Old Testament stories feel different when you realize it was Christ acting in them?",
    commitment: "Choose one Old Testament story this week — the Exodus, the giving of the law at Sinai, or a prophetic call — and reread it knowing that the God acting in it is Jesus Christ. Journal what you discover."
  },
  days: [
    {
      label: "The divine name revealed",
      focus: "God revealed His name to Moses as 'I AM' — a name Jesus would later claim for Himself. Today examines the significance of the divine name and its christological implications.",
      scriptures: [{book:"Ex",ch:3,vs:13,ve:15},{book:"Ex",ch:6,vs:2,ve:3},{book:"John",ch:8,vs:56,ve:58},{book:"Ps",ch:83,vs:18}],
      nuances: "The name 'Jehovah' (more precisely 'Yahweh,' from the Hebrew YHWH) is related to the verb 'hayah' — to be. When Jesus says 'Before Abraham was, I am' (John 8:58), the Greek 'ego eimi' directly echoes the Septuagint rendering of the divine name in Exodus 3:14. His audience understood the claim immediately — they picked up stones to kill Him for blasphemy. He was not merely claiming to predate Abraham; He was claiming to be Jehovah.",
      commentary: "Exodus 3:13–15 records one of the most momentous moments in scripture: God reveals His personal name. When Moses asks who is sending him, God responds with 'I AM THAT I AM' and then instructs Moses to tell Israel, 'The Lord God of your fathers, the God of Abraham, the God of Isaac, and the God of Jacob, hath sent me unto you: this is my name for ever.' Exodus 6:2–3 adds that God appeared to Abraham, Isaac, and Jacob by the name 'God Almighty' (El Shaddai) but was not known to them by His name Jehovah — now revealed for the first time in its fullness.\n\nJohn 8:58 is the christological key. When Jesus tells the Jewish leaders, 'Before Abraham was, I am,' He is not making a casual statement about longevity. He is speaking the divine name. The reaction of His hearers — immediate rage and an attempt at stoning — confirms they understood perfectly what He was claiming. Jesus was asserting that He is Jehovah, the I AM of Exodus 3.\n\nLatter-day Saint theology makes this identification explicit and systematic. The God who spoke from the burning bush, who led Israel through the wilderness, and who gave the law at Sinai is the premortal Jesus Christ, acting under the direction of the Father. This identification transforms the entire Old Testament from a record of a distant, often fierce deity into the story of the same gentle, compassionate Savior who healed the blind and blessed the children.",
      patterns: "The divine name 'I AM' connects back to Week 5, Day 3 (Moses at the burning bush) and forward to Christ's mortal ministry, where He repeatedly uses 'I am' statements (I am the bread of life, I am the good shepherd, I am the way). Each 'I am' in John's Gospel is an echo of Exodus 3 — Jehovah identifying Himself in the flesh.",
      reflection: "Jesus claimed the divine name of the Old Testament God as His own. How does this identification of Christ as Jehovah affect the way you read the Old Testament?"
    },
    {
      label: "Jehovah — the only Savior",
      focus: "Isaiah declares that Jehovah alone is God and Savior. The New Testament applies these very passages to Jesus Christ. Today traces this extraordinary identification.",
      scriptures: [{book:"Isa",ch:43,vs:3},{book:"Isa",ch:43,vs:10,ve:11},{book:"Isa",ch:44,vs:6},{book:"Isa",ch:45,vs:5,ve:6},{book:"Isa",ch:45,vs:21,ve:22}],
      nuances: "Isaiah 43:11 is emphatic: 'I, even I, am the Lord; and beside me there is no saviour.' The Hebrew places 'anoki, anoki' (I, even I) at the beginning for maximum emphasis. Isaiah 44:6 adds: 'I am the first, and I am the last; and beside me there is no God.' In Revelation 1:17 and 22:13, the risen Jesus Christ applies the title 'first and last' to Himself — directly claiming the identity of Isaiah's Jehovah.",
      commentary: "Isaiah contains some of the most forceful monotheistic declarations in the Bible. Jehovah declares through the prophet that there is no God beside Him, no Savior apart from Him, and He is both the first and the last. These are absolute claims of exclusive divine authority.\n\nThe theological implications become explosive when you trace how the New Testament handles these passages. The title 'first and last,' which Jehovah claims in Isaiah 44:6, is applied to the risen Christ in the book of Revelation. The claim that there is 'no saviour' besides Jehovah (Isaiah 43:11) is reconciled with Acts 4:12 (there is 'no other name' for salvation besides Jesus Christ) only if Jesus and Jehovah are the same being.\n\nLatter-day Saint theology resolves this cleanly: Jehovah is the premortal Christ. He is the Savior beside whom there is no other because He is the only one with the power and foreordination to perform the Atonement. The Father directed the plan; the Son — Jehovah — executed it. When Isaiah's God says 'beside me there is no saviour,' He is making a claim that Jesus would fulfill in Gethsemane and on Calvary. The continuity between Old Testament and New Testament is not merely thematic — it is personal. The same being speaks in both.",
      patterns: "Isaiah's 'no other Savior' declarations connect directly to Week 1, Day 4 ('The only name') and the multiple-dispensation witnesses that salvation comes through Christ alone. The 'first and last' title also connects to Week 49 (Second Coming), where Christ returns as the Alpha and Omega — completing what He began as Jehovah.",
      reflection: "Isaiah's Jehovah says, 'Look unto me, and be ye saved, all the ends of the earth' (45:22). How does it change this invitation to know that the speaker is Jesus Christ?"
    },
    {
      label: "Jehovah as the Rock of Israel",
      focus: "Throughout the Old Testament, God is called 'the Rock.' Paul identifies this Rock as Christ. Today examines one of the most enduring metaphors for Jehovah's character.",
      scriptures: [{book:"Deut",ch:32,vs:3,ve:4},{book:"Ps",ch:18,vs:2},{book:"Ps",ch:18,vs:31},{book:"1 Cor",ch:10,vs:1,ve:4},{book:"Hel",ch:5,vs:12}],
      nuances: "In 1 Corinthians 10:4, Paul writes that the Israelites in the wilderness 'drank of that spiritual Rock that followed them: and that Rock was Christ.' The Greek 'petra' is the same word used in Matthew 16:18 ('upon this rock I will build my church'). Paul is making an astonishing hermeneutical move: he retroactively identifies the miraculous provision of water in the Exodus as an act of the premortal Christ.",
      commentary: "Moses' song in Deuteronomy 32:3–4 calls Jehovah 'the Rock, his work is perfect.' David echoes this in Psalm 18:2 — 'The Lord is my rock, and my fortress, and my deliverer.' The metaphor of rock conveys stability, permanence, and unshakable faithfulness. In a desert landscape, a massive rock provided shade, shelter, and sometimes water. Jehovah is all of these for His people.\n\nPaul's identification in 1 Corinthians 10:1–4 is one of the most important christological statements in the epistles. He tells the Corinthian church that the Israelites were all baptized 'unto Moses,' ate spiritual food (manna), and drank from a spiritual Rock — and that Rock was Christ. Paul is not being figurative. He is teaching that the premortal Christ was actively present with Israel during the Exodus, providing sustenance and salvation.\n\nHelaman 5:12 draws this imagery into the Book of Mormon: 'It is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation.' Helaman explicitly identifies the Rock of Israel as Christ and urges the Nephites to build their lives upon Him. The metaphor that began with Moses in Deuteronomy, was claimed by David in the Psalms, was identified by Paul as Christ, and is reaffirmed by Helaman — all pointing to the same Jehovah, the same Rock, across millennia.",
      patterns: "The Rock metaphor connects to Week 5, Day 4 (Moses in the cleft of the rock on Sinai) and Week 6 (the Creator whose word formed the rocks themselves). It also anticipates Christ's own teaching about building on rock versus sand (Matthew 7), which will appear in later weeks studying His mortal ministry.",
      reflection: "What does it mean practically to build your life on Christ as your 'rock'? Where in your life do you feel the need for the stability and shelter that only He can provide?"
    },
    {
      label: "Jehovah and the Exodus",
      focus: "The Exodus is the defining act of the Old Testament — God delivering His people from bondage. Today recognizes the Deliverer as the premortal Christ.",
      scriptures: [{book:"Ex",ch:14,vs:13,ve:14},{book:"Ex",ch:14,vs:21,ve:22},{book:"1 Cor",ch:10,vs:1,ve:4},{book:"1 Ne",ch:17,vs:23,ve:30}],
      nuances: "Exodus 14:13 records Moses saying, 'Stand still, and see the salvation of the Lord.' The Hebrew 'yeshu'at YHWH' (salvation of Jehovah) contains the same root as the name 'Yeshua' — Jesus. The salvation of Jehovah at the Red Sea is linguistically and theologically connected to the name Jesus: He who saves. Every time the Old Testament speaks of Jehovah's salvation, it is foreshadowing the work of Jesus Christ.",
      commentary: "The Exodus is the defining event of the Old Testament — the moment Jehovah demonstrated His power and faithfulness by liberating Israel from slavery in Egypt. The parting of the Red Sea, the pillar of fire by night and cloud by day, the manna from heaven, the water from the rock — all of these were acts of Jehovah. And Jehovah is Christ.\n\nThis means that the being who parted the Red Sea is the same being who calmed the storm on Galilee. The God who led Israel through the wilderness by night is the same God who said, 'I am the light of the world.' The one who fed Israel with manna is the same one who said, 'I am the bread of life.' The correspondences are not accidental — Christ's mortal ministry deliberately echoes and fulfills His Jehovah ministry.\n\nNephi understood this. In 1 Nephi 17:23–30, he recounts the Exodus to his rebellious brothers, reminding them that the God who delivered Israel from Egypt is the same God who will deliver the faithful in every generation. For Nephi, the Exodus is not just history — it is a pattern of how God works. He hears the cries of His people, He delivers them through impossible circumstances, and He leads them to a promised land. This pattern operates in the Book of Mormon, in the Restoration, and in your own life.",
      patterns: "The Exodus typology is one of the most important patterns in scripture. It connects to Week 39 (Types and Shadows of Christ), where the Passover lamb, the crossing of the Red Sea, and the manna all prefigure Christ's atoning work. It also connects to baptism — Paul himself draws this connection in 1 Corinthians 10, describing the crossing of the sea as a kind of baptism.",
      reflection: "The Exodus teaches that Jehovah (Christ) delivers His people from bondage. What form of bondage — spiritual, emotional, habitual — do you need Christ to deliver you from today?"
    },
    {
      label: "Jehovah at Sinai",
      focus: "When God descended on Mount Sinai and gave the law to Israel, it was Christ who spoke. Today examines the giving of the law through a christological lens.",
      scriptures: [{book:"Ex",ch:19,vs:16,ve:20},{book:"Ex",ch:20,vs:1,ve:3},{book:"3 Ne",ch:15,vs:3,ve:5},{book:"Mosiah",ch:3,vs:5}],
      nuances: "3 Nephi 15:5 is remarkably direct: 'Behold, I am he that gave the law, and I am he who covenanted with my people Israel.' The risen Christ, speaking to the Nephites, claims personal authorship of the Mosaic law. This retrospective self-identification transforms how we read the entire Torah: every commandment, every statute, every ordinance given at Sinai was given by the premortal Jesus Christ.",
      commentary: "Exodus 19 describes one of the most terrifying scenes in scripture. Mount Sinai is wrapped in smoke and fire, the earth quakes, a trumpet sounds louder and louder, and God descends. The Israelites tremble at the base of the mountain. From this overwhelming display of divine power, the Ten Commandments are spoken. The God who speaks is Jehovah.\n\n3 Nephi 15:3–5 removes all ambiguity about the identity of this God. The resurrected Christ tells the Nephites: 'I am he that gave the law.' He then explains that the law of Moses has been fulfilled in Him — the lawgiver has now completed the purpose of the law through His own death and resurrection. This passage is theologically crucial because it establishes that Christ was not replacing a foreign God's law with His own gospel. He was fulfilling His own law. The continuity is total.\n\nMosiah 3:5 adds King Benjamin's angelic revelation that the Lord Omnipotent would come down from heaven and dwell in a tabernacle of clay. The being who descended on Sinai in fire and thunder would later descend to Bethlehem as an infant. The contrast is breathtaking — the same divine Person, one time terrifying in glory, another time asleep in a manger. But it is the same Person, and the same mission of covenant love.",
      patterns: "Jehovah as lawgiver connects to later weeks studying Christ's Sermon on the Mount (a deliberate parallel to Sinai) and the higher law He gave to both the Nephites and the Saints in this dispensation. The 'fulfillment' of the law discussed in 3 Nephi 15 will be central to understanding Christ's mortal teachings.",
      reflection: "The same God who thundered the commandments from Sinai later said, 'Come unto me, all ye that labour and are heavy laden.' How do you reconcile the justice of the lawgiver with the mercy of the Savior — and what does it mean that they are the same Person?"
    },
    {
      label: "Jehovah's covenant faithfulness",
      focus: "Jehovah is a covenant God. Today examines how the Abrahamic covenant reveals Christ's enduring commitment to His people across millennia.",
      scriptures: [{book:"Abr",ch:2,vs:6,ve:8},{book:"Gen",ch:17,vs:1,ve:8},{book:"Abr",ch:1,vs:15,ve:16},{book:"D&C",ch:29,vs:1}],
      nuances: "In Abraham 2:8, Jehovah promises Abraham: 'In thy seed after thee... shall all the families of the earth be blessed, even with the blessings of the Gospel, which are the blessings of salvation, even of life eternal.' The phrase 'in thy seed' is interpreted by Paul in Galatians 3:16 as referring to Christ: 'He saith not, And to seeds, as of many; but as of one, And to thy seed, which is Christ.' The Abrahamic covenant's ultimate fulfillment is the Atonement of Jesus Christ.",
      commentary: "The Abrahamic covenant is the backbone of the Old Testament. God promises Abraham land, posterity, and that through his seed all nations will be blessed. Abraham 2:6–8 makes explicit what is implicit in Genesis: the blessings promised include the gospel itself and eternal life. The God making this covenant is Jehovah — the premortal Christ.\n\nThis means that the Abrahamic covenant is a christological covenant. Its ultimate fulfillment is not merely the nation of Israel but the coming of Christ through Abraham's lineage. Paul makes this connection explicitly in Galatians 3:16 — the 'seed' of Abraham through whom all nations are blessed is Christ. Every time God renewed this covenant — to Isaac, to Jacob, to Moses, to David — it was Christ recommitting Himself to His redemptive mission.\n\nD&C 29:1 opens with Christ identifying Himself as the one who has 'gathered' His people — using covenant gathering language that stretches back to Abraham. The same God who called Abraham out of Ur, who led Israel out of Egypt, and who promised David an everlasting throne is the same Jesus Christ who speaks to Joseph Smith in the latter days. Jehovah's covenant faithfulness spans the entire scriptural record without interruption.\n\nAbraham 1:15–16 provides poignant context: Abraham himself was nearly sacrificed by idolatrous priests. The God who rescued Abraham from that altar is the same God who would allow His own Son to be placed on the altar of Calvary. The covenant God saves His people — and ultimately saves them by offering Himself.",
      patterns: "The Abrahamic covenant connects forward to Week 21 (Taking upon the name of Christ — entering His covenant) and to the gathering of Israel themes in Weeks 46–47. Understanding that Jehovah's covenants with Israel were Christ's covenants transforms the entire arc of salvation history into a single, personal story of divine commitment.",
      reflection: "Jehovah's covenants with Abraham, Isaac, and Jacob were ultimately about bringing Christ into the world to save all people. How does understanding the covenant as a personal commitment by Christ — to you — change how you view your own baptismal covenant?"
    },
    {
      label: "Jehovah revealed in the latter days",
      focus: "Drawing the week together: the same Jehovah who appeared to Moses and Isaiah appeared again in the Kirtland Temple in 1836. Christ's identity spans from eternity to the present day.",
      scriptures: [{book:"D&C",ch:110,vs:1,ve:4},{book:"D&C",ch:38,vs:1},{book:"Morm",ch:9,vs:10,ve:12},{book:"Hel",ch:8,vs:22,ve:23}],
      nuances: "D&C 110:3 describes the Lord's appearance in the Kirtland Temple: 'His eyes were as a flame of fire; the hair of his head was white like the pure snow; his countenance shone above the brightness of the sun.' This description closely parallels Revelation 1:14–16 and Daniel 7:9 — the same glorified divine being described in ancient apocalyptic visions appears to Joseph Smith and Oliver Cowdery in 1836. The visual continuity is deliberate and unmistakable.",
      commentary: "On April 3, 1836, the Lord Jesus Christ appeared to Joseph Smith and Oliver Cowdery in the Kirtland Temple. He declared: 'I am the first and the last; I am he who liveth, I am he who was slain; I am your advocate with the Father' (D&C 110:4). This self-identification combines the Jehovah titles of the Old Testament ('first and last,' from Isaiah 44:6) with the Savior claims of the New Testament ('he who was slain,' echoing Revelation 5:12). In a single verse, Christ bridges the entire scriptural record.\n\nD&C 38:1 provides another comprehensive self-identification: Christ is 'the same which have taken the Zion of Enoch... the Maker of heaven and earth.' He is the God of every dispensation — Enoch's, Abraham's, Moses's, Isaiah's, and ours.\n\nMormon 9:10–12 makes the theological principle explicit: God is the same yesterday, today, and forever. He is unchangeable. The Jehovah who parted the Red Sea is the same Christ who rose from the tomb is the same Lord who appeared in the Kirtland Temple. Helaman 8:22–23 adds that Abraham, Moses, and many others testified of Christ's coming — they knew the God they worshipped would one day take upon Himself flesh and redeem the world.\n\nThe Kirtland Temple appearance is the capstone of the Jehovah identification. It closes the circle: the God who revealed Himself to Moses at the bush, who thundered from Sinai, who promised Abraham a covenant nation, and who spoke through Isaiah now stands in a latter-day temple and reveals Himself again. He is the same. He has always been the same. And He invites you to know Him as He has been known by prophets from the beginning.",
      patterns: "D&C 110 connects to Week 5 (Appearances, Antemortal) and Week 1 (modern witness of Christ). The Kirtland Temple appearance also connects to Weeks 46–47 (gathering of Israel) because Moses, Elias, and Elijah appeared immediately after Christ in D&C 110, restoring priesthood keys related to the covenant promises studied this week.",
      reflection: "The Jehovah of the Old Testament, the Jesus of the New Testament, and the Lord of the Restoration are all the same Person. As you close this week, what does the unchangeable nature of Christ mean for your trust in Him today?"
    }
  ]
};

export default week08;
