import type { WeekContent } from '../types';

const week43: WeekContent = {
  title: "Second Coming — The Return of the King",
  subtitle: "Every prophecy, every ordinance, and every dispensation converges on one event: the glorious return of Jesus Christ to reign on the earth.",
  weekScriptures: "Matt. 24:3–44; Matt. 25:1–13; D&C 45:36–53; D&C 29:9–11; D&C 133:46–53; Acts 1:11; Rev. 19:11–16; 1 Thes. 4:16–17; 2 Thes. 1:7–10; JS-M 1:26–40; Zech. 14:3–5; Mal. 4:1–2; 3 Ne. 24:1–3; 2 Pet. 3:10–13; D&C 88:95–98; Morm. 9:2",
  synthesis: {
    summary: "The Second Coming of Jesus Christ is the culminating event of mortal history. He will return in glory, with power, to a world that has been warned and prepared by His servants. The signs will be unmistakable. The wicked will mourn. The righteous will be gathered. The earth itself will be renewed. This week studies the scriptural witness of that return — not as speculation about timing but as preparation of the heart.",
    connections: [
      "The Second Coming fulfills the prophecies studied in Week 39 that were not fulfilled at Christ's first coming — the triumphant king, the universal reign, the judgment.",
      "Week 42 (Postmortal Appearances) ended with the angelic promise that Christ would return 'in like manner.' This week studies the fulfillment of that promise.",
      "The judgment associated with the Second Coming connects to the Atonement (Week 20) — the same Christ who atoned is the Christ who judges."
    ],
    teaching: "The scriptures devote far more space to preparation for the Second Coming than to predicting its timing. What does that emphasis tell you about God's priorities?",
    commitment: "Rather than trying to calculate when Christ will return, identify one thing this week's study reveals you should be doing now to be ready. Begin doing it."
  },
  days: [
    {
      label: "The disciples' question and the Olivet Discourse",
      focus: "Jesus' most extended teaching about the last days came in response to a question from His disciples on the Mount of Olives. Today examines the framework He provided.",
      scriptures: [{book:"Matt",ch:24,vs:3,ve:14},{book:"JS-M",ch:1,vs:26,ve:40},{book:"D&C",ch:45,vs:36,ve:42}],
      nuances: "In Matthew 24:3, the disciples ask three questions that are often collapsed into one: 'When shall these things be? What shall be the sign of thy coming? And of the end of the world?' The Greek 'sunteleia tou aionos' (end of the age) does not mean the destruction of the planet but the conclusion of an era — the closing of the present age and the dawning of the millennial age.",
      commentary: "The Olivet Discourse is Jesus' longest sustained teaching about the future. Seated on the Mount of Olives, looking across at the temple, He described wars, famines, earthquakes, false prophets, persecution, and the darkening of the sun and moon. These signs have recurred throughout history, leading every generation to wonder if the end is near.\n\nJoseph Smith's inspired revision (JS-M 1:26–40) clarifies ambiguities in Matthew 24. The JST makes it clear that certain verses apply to the destruction of Jerusalem in AD 70, while others apply to the final return of Christ. This distinction, which scholars have debated for centuries, is resolved in the Restoration text.\n\nD&C 45:36–42 adds a Restoration-era expansion of the Olivet Discourse: the Lord describes a time when the love of men shall wax cold, iniquity shall abound, and people shall be 'looking forth for the signs of my coming.' The faithful, however, will watch and be ready.\n\nWhat is striking about all three accounts is the balance between warning and reassurance. Yes, terrible things will happen. But 'he that shall not be overcome, the same shall be saved' (JS-M 1:11). The point of these prophecies is not to generate anxiety but to produce readiness. Christ tells us what is coming so that when it happens, we will remember who told us — and trust Him.",
      patterns: "The Olivet Discourse follows the prophetic pattern of dual fulfillment: events that partially occur in one era and fully occur in another. The destruction of Jerusalem in AD 70 was a type of the final destruction. This layered prophetic structure was discussed in Week 39.",
      reflection: "Jesus said these signs would come so that when they happen, you would believe. As you observe current events, do they strengthen your faith in His word or increase your anxiety? What would it take to shift from fear to trust?"
    },
    {
      label: "The ten virgins — readiness and oil",
      focus: "The parable of the ten virgins is Christ's most direct teaching on personal preparation for His return. Today examines what the oil represents and why it cannot be borrowed.",
      scriptures: [{book:"Matt",ch:25,vs:1,ve:13},{book:"D&C",ch:45,vs:56,ve:57},{book:"D&C",ch:33,vs:17}],
      nuances: "In Matthew 25:8, the foolish virgins ask to borrow oil: 'Give us of your oil; for our lamps are gone out.' The Greek 'sbennuntai' means 'are being extinguished' — a present tense, indicating the process had already begun. Their lamps were flickering out while they watched. Spiritual decline is often a gradual dimming, not a sudden failure.",
      commentary: "The parable of the ten virgins is deceptively simple. Ten women wait for a bridegroom. Five have oil; five do not. When the bridegroom arrives at midnight, the five without oil cannot buy or borrow it in time. The door shuts. They are left outside.\n\nThe elements of the parable each carry meaning. The bridegroom is Christ. The wedding feast is His return. The midnight arrival represents the unexpected timing. The oil — this is the critical element. Latter-day prophets have taught that the oil represents personal spiritual preparation: testimony gained, covenants kept, service rendered, character developed. It is the cumulative spiritual life of the individual.\n\nD&C 45:56–57 applies the parable directly: 'And at that day, when I shall come in my glory, shall the parable be fulfilled which I spake concerning the ten virgins.' The Lord then identifies the wise as those who 'have received the truth, and have taken the Holy Spirit for their guide.'\n\nThe most sobering element of the parable is that the oil cannot be borrowed. The wise virgins are not selfish for refusing to share — they simply cannot. Testimony, character, and spiritual preparedness are not transferable. A parent cannot give their faith to a child. A friend cannot lend their spiritual reserves. Each person must fill their own lamp.\n\nD&C 33:17 issues the urgent command: 'Wherefore, be faithful, praying always, having your lamps trimmed and burning, and oil with you, that you may be ready at the coming of the Bridegroom.' The question is not when He comes. The question is whether your lamp will be burning when He does.",
      patterns: "The parable of the ten virgins is the Second Coming counterpart to the Passover type (Week 40): in the Passover, those who applied the blood were saved; here, those who gathered oil are admitted. In both cases, preparation must be personal and completed before the moment of need arrives.",
      reflection: "If Christ returned tonight, what is the current state of your oil? Not in a spirit of fear but honest evaluation — what area of spiritual preparation needs your attention?"
    },
    {
      label: "The manner of His coming",
      focus: "Christ's return will be visible, physical, and unmistakable. Today studies what the scriptures reveal about the manner and nature of His appearance.",
      scriptures: [{book:"Acts",ch:1,vs:11},{book:"Rev",ch:19,vs:11,ve:16},{book:"D&C",ch:133,vs:46,ve:53},{book:"Zech",ch:14,vs:3,ve:5}],
      nuances: "Revelation 19:12 describes Christ's eyes as 'a flame of fire' and says 'he had a name written, that no man knew, but he himself.' The hidden name suggests that there are dimensions of Christ's identity and glory that remain unrevealed even to the prophets — aspects of His nature that will only be known at His appearing.",
      commentary: "The scriptures are remarkably specific about the manner of Christ's return. Acts 1:11 promises He will come in the clouds, visibly, physically. Revelation 19 describes Him riding a white horse, wearing a robe dipped in blood, bearing the name 'King of Kings, and Lord of Lords.' This is not the meek and lowly Jesus of the first coming — this is the conquering King whose word is a sharp sword and whose authority is absolute.\n\nD&C 133:46–53 provides one of the most vivid accounts in all of scripture. Christ will come in red apparel, having trodden the winepress alone. When asked 'Who is this that cometh from Edom, with dyed garments from Bozrah?' He will answer: 'I am he who spake in righteousness, mighty to save.' His garments are red because of the blood of His atoning sacrifice and the judgment He brings upon the wicked.\n\nZechariah 14:3–5 prophesies that Christ's feet shall stand on the Mount of Olives — the very place from which He ascended — and the mount shall cleave in two. The geographic specificity is deliberate: the return will be as physically real as the departure.\n\nThe contrast between the two comings is total. The first time: a manger, a stable, poverty, obscurity. The second time: clouds, fire, armies of heaven, universal visibility. The first time He came as the Lamb; the second time He comes as the Lion. Both are the same Jesus. Both fulfill prophecy. The humble servant and the reigning king, as discussed in Week 39, are one and the same.",
      patterns: "The contrast between Christ's two comings — humility and glory — resolves the prophetic tension explored in Week 39. Everything unfulfilled at the first coming will be fulfilled at the second. The arc of scripture bends toward His triumphant return.",
      reflection: "The same Jesus who washed feet and wept at a grave will return in fire and glory. How do you hold both of these images together? What does each reveal about His character?"
    },
    {
      label: "Signs of the times",
      focus: "Jesus described specific signs that would precede His return. Today examines these signs — not for date-setting but for spiritual orientation.",
      scriptures: [{book:"Matt",ch:24,vs:29,ve:44},{book:"D&C",ch:88,vs:95,ve:98},{book:"2 Pet",ch:3,vs:10,ve:13},{book:"Mal",ch:4,vs:1,ve:2}],
      nuances: "In Matthew 24:36, Jesus states: 'But of that day and hour knoweth no man, no, not the angels of heaven, but my Father only.' The Greek 'oudeis oiden' is emphatic: absolutely no one knows. This includes (as Mark 13:32 specifies) the Son Himself during His mortal ministry. Any claim to know the date of the Second Coming contradicts Christ's own words.",
      commentary: "The signs preceding the Second Coming are described across multiple scriptural texts: the sun darkened, the moon turned to blood, stars falling, the powers of heaven shaken. D&C 88:95–98 provides a sequence: an angel sounds a trump, and the dead are raised in order — the righteous first, then others. The earth trembles and reels.\n\n2 Peter 3:10–13 warns that the day of the Lord will come 'as a thief in the night' — unexpected. The elements shall melt with fervent heat. But Peter frames this not as a reason for terror but as motivation for holiness: 'What manner of persons ought ye to be in all holy conversation and godliness?' If the world is temporary, only character and covenant are permanent.\n\nMalachi 4:1–2 presents the dual nature of that day: for the proud and wicked, it will burn as an oven. For those who fear God's name, 'the Sun of righteousness shall arise with healing in his wings.' The same event — the same day — is both destruction and healing, depending on the preparation of the heart.\n\nThe consistent message across all these texts is that the timing is not yours to know, but the preparation is yours to make. Jesus said to 'watch and be ready.' The signs are given not so that you can calculate dates but so that you can recognize the season and live accordingly. Spiritual readiness is the only response to uncertainty that the scriptures endorse.",
      patterns: "The dual nature of the Second Coming — destruction for the wicked, deliverance for the righteous — mirrors the Passover (destruction for Egypt, deliverance for Israel) and the flood (destruction for the world, deliverance for Noah). God's pattern is always to warn, prepare a remnant, and then act.",
      reflection: "Peter asked, 'What manner of persons ought ye to be?' rather than 'When exactly will this happen?' How does shifting from the question of timing to the question of character change your approach to the last days?"
    },
    {
      label: "The gathering before the coming",
      focus: "Before Christ returns, the righteous will be gathered. Today examines the doctrine of gathering as preparation for the Second Coming.",
      scriptures: [{book:"D&C",ch:29,vs:9,ve:11},{book:"3 Ne",ch:24,vs:1,ve:3},{book:"1 Thes",ch:4,vs:16,ve:17},{book:"Matt",ch:24,vs:31}],
      nuances: "In D&C 29:9, the Lord says He will 'gather mine elect from the four quarters of the earth.' The phrase 'four quarters' translates an ancient Near Eastern expression for totality — it means from everywhere, from every direction. The gathering is geographically universal, not limited to one land or people.",
      commentary: "The doctrine of gathering is central to Latter-day Saint theology and is directly tied to the Second Coming. D&C 29:9–11 states plainly: the elect are gathered so that they can be prepared, so that the righteous may be in one place when the Lord comes. The gathering is not incidental — it is the preparatory work of the last dispensation.\n\n3 Nephi 24 (quoting Malachi 3) describes the Lord coming suddenly to His temple. But before He comes, He sends a messenger to prepare the way. He then refines and purifies the sons of Levi — those who bear the priesthood and offer offerings. The gathering includes a refining process: those who are gathered must also be prepared spiritually.\n\nPaul's description in 1 Thessalonians 4:16–17 is one of the most dramatic images in scripture: 'The Lord himself shall descend from heaven with a shout, with the voice of the archangel, and with the trump of God: and the dead in Christ shall rise first: Then we which are alive and remain shall be caught up together with them in the clouds, to meet the Lord in the air.' The gathered righteous — both living and dead — will be united to meet Christ.\n\nMatthew 24:31 adds that angels will gather the elect from one end of heaven to the other. The gathering is not a human organizational effort alone — it is a divine operation conducted by angelic ministers under Christ's direction. Missionary work, temple work, and the establishment of Zion communities are the mortal components of this cosmic gathering.",
      patterns: "The gathering before the Second Coming mirrors the gathering of Israel from Egypt before the Passover, the gathering of Noah's family before the flood, and the gathering of the Nephites to the temple before Christ's appearance (3 Nephi 11). God gathers His people before His great acts.",
      reflection: "The gathering of Israel is happening now — through missionary work, temple work, and the building of covenant communities. How are you participating in this gathering?"
    },
    {
      label: "The wounds and the recognition",
      focus: "When Christ returns, He will bear the marks of His crucifixion. Today examines the profoundly personal moment when the world recognizes the wounded God.",
      scriptures: [{book:"D&C",ch:45,vs:51,ve:53},{book:"Zech",ch:13,vs:6},{book:"D&C",ch:133,vs:51,ve:53},{book:"Morm",ch:9,vs:2}],
      nuances: "In D&C 45:52, when the Jews see Christ's wounds, they ask: 'What are these wounds in thine hands and in thy feet?' He answers: 'These wounds are the wounds with which I was wounded in the house of my friends.' The phrase 'house of my friends' echoes Zechariah 13:6 and carries layers of meaning — He was wounded by His covenant people, those who should have received Him.",
      commentary: "D&C 45:51–53 describes a scene of extraordinary emotional power. When Christ appears on the Mount of Olives, the Jews — who have been gathered and besieged — will look upon Him and see the wounds. They will ask about them. And He will answer that these are the wounds He received in the house of His friends. Then, the text says, 'they shall weep because of their iniquities; then shall they lament because they persecuted their king.'\n\nThis is not a scene of condemnation. It is a scene of recognition and grief. The same people who (as a nation) rejected the Messiah two thousand years ago will finally see Him and understand what happened. The wounds remain — glorified but visible — as eternal evidence of what love cost.\n\nD&C 133:51–53 expands on this: 'And the Lord shall be red in his apparel, and his garments like him that treadeth in the wine-vat.' The imagery of the winepress connects to Gethsemane and Golgotha — the places where He was crushed for our sake. His red garments at the Second Coming are a visual testimony of the Atonement.\n\nMormon 9:2 adds a sobering perspective from the Book of Mormon: for the unrepentant, appearing before Christ will be a source of anguish rather than joy. They would be 'happier to dwell with the damned' than to stand before 'that holy Being... with a consciousness of your uncleanliness.' The Second Coming is joy for the prepared and torment for the unrepentant — not because Christ is cruel, but because His presence reveals everything.\n\nThe wounds at the Second Coming are the same wounds Thomas touched in the upper room, the same wounds 2,500 Nephites felt at the temple in Bountiful. They are the constant across every appearance — the signature of a love that death could not erase.",
      patterns: "The wounds as marks of identity connect every appearance of Christ across scripture: to Thomas, to the Nephites, and at the Second Coming. He is always recognized by His wounds. The Atonement is not something He did — it is part of who He is, permanently.",
      reflection: "Christ chose to retain His wounds forever. What does this say about how He views His sacrifice? How should it shape your gratitude?"
    },
    {
      label: "The millennial reign and the renewal of all things",
      focus: "The Second Coming inaugurates the Millennium — a thousand years of peace under Christ's personal reign. Today looks at what the scriptures reveal about that era.",
      scriptures: [{book:"Rev",ch:20,vs:1,ve:6},{book:"D&C",ch:101,vs:23,ve:31},{book:"Isa",ch:11,vs:6,ve:9},{book:"D&C",ch:29,vs:11}],
      nuances: "In Revelation 20:6, those who reign with Christ during the Millennium are called 'priests of God and of Christ.' The Greek 'hiereis' — priests — is not metaphorical. The millennial community is not merely governed by Christ but actively serves in priestly ministry. Worship and governance become one.",
      commentary: "Revelation 20 describes a thousand-year period during which Satan is bound and Christ reigns with His saints. D&C 101:23–31 fills in the details from a Restoration perspective: when the Lord comes, every corruptible thing shall be consumed. He shall stand in the midst of His people and reign for a thousand years. During this time, there will be no death as we know it — people shall live to the age of a tree and then be changed in the twinkling of an eye.\n\nIsaiah 11:6–9 provides the most beloved image of the Millennium: the wolf shall dwell with the lamb, the leopard with the kid, the calf and the lion together, and a little child shall lead them. 'They shall not hurt nor destroy in all my holy mountain: for the earth shall be full of the knowledge of the Lord, as the waters cover the sea.' The violence and predation that characterize the fallen world will cease. Creation itself will be healed.\n\nD&C 29:11 states that Christ shall 'dwell in righteousness with men on earth a thousand years, and the wicked shall not stand.' This is not a symbolic reign or a spiritual presence — it is a physical, personal, terrestrial kingship. The same Jesus who walked the roads of Galilee and the paths of Bountiful will walk among His people again.\n\nThe Millennium is not the end of the plan — it is the penultimate chapter. After the thousand years, a final confrontation and the celestialization of the earth will follow. But the Millennium represents the fulfillment of every prophetic vision of peace, justice, and the knowledge of God covering the earth. It is the world as God always intended it to be.",
      patterns: "The Millennium fulfills the prophetic arc that runs from Eden (a garden of peace) through the Fall (a world of conflict) to the restoration of Edenic conditions. The entire fifty-week study plan traces this arc: from Christ's identity (Week 1) through His atoning work to His triumphant return and eternal reign.",
      reflection: "The Millennium is described as a time when the earth is full of the knowledge of the Lord. What would your community look like if every person knew Christ? What can you do now to move toward that reality in your own sphere?"
    }
  ]
};

export default week43;
