import type { WeekContent } from '../types';

const week11: WeekContent = {
  title: "Crucifixion & Death — The Sacrifice Completed",
  subtitle: "On a hill called Golgotha, the Creator of the world gave His life — not because He had to, but because He chose to.",
  weekScriptures: "Zech 12:10; Ps 69:20-21; Gal 6:14; Mark 15:34-39; Luke 23:46; John 10:17-18; John 3:14-15; Alma 34:14; Heb 12:2; 1 Pet 2:24; Mosiah 15:7-9; Acts 2:23",
  synthesis: {
    summary: "The Crucifixion of Jesus Christ is the hinge on which all of human history turns. Every ordinance of the Mosaic law, every prophecy of the Old Testament, every promise of the Book of Mormon pointed forward to this hour. And every covenant, every baptism, every act of repentance since that day points back to it. This week we walk slowly through those final hours — the scourging, the cross, the seven last words, the darkness, and the death. We do so not to sensationalize suffering but to understand the cost of our redemption.",
    connections: [
      "The betrayal and trials of Week 10 led directly to this moment — the injustice of the proceedings becomes the mechanism of the sacrifice.",
      "The mission of Christ (Week 9) finds its ultimate expression here — everything He came to do converges on the cross.",
      "The Resurrection of Week 12 transforms the Crucifixion from tragedy into triumph — without it, the cross would be only suffering, not salvation."
    ],
    teaching: "Why was it necessary for the Son of God to die in this specific way — publicly, painfully, and at the hands of those He came to save? What would be lost if the Atonement had been accomplished privately?",
    commitment: "Spend time this week in quiet contemplation of what Christ endured. Let the reality of the Crucifixion deepen your gratitude and strengthen your resolve to follow Him."
  },
  days: [
    {
      label: "The scourging and mockery",
      focus: "Before the cross came the Roman scourging and the soldiers' mockery. Today examines the physical and psychological abuse that preceded Calvary.",
      scriptures: [{book:"Matt",ch:27,vs:27,ve:31},{book:"Mark",ch:15,vs:16,ve:20},{book:"Isa",ch:53,vs:3,ve:5}],
      nuances: "The Roman scourge (flagrum) was a whip with multiple leather thongs embedded with bone or metal fragments. The Greek 'phragello\u014d' (Matthew 27:26) refers specifically to this instrument. Roman law limited scourging for citizens to a set number of strokes, but Jesus, as a non-citizen provincial, had no such protection. Ancient sources describe scourging as a punishment that often exposed muscle and bone.",
      commentary: "Matthew and Mark both record that the entire cohort — potentially hundreds of soldiers — gathered to mock Jesus. They stripped Him, placed a scarlet robe on His torn back, pressed a crown of thorns onto His head, put a reed in His hand as a mock scepter, and knelt before Him in parody of worship. They struck Him, spat on Him, and then led Him away to be crucified.\n\nThe mockery is as theologically significant as the physical suffering. The soldiers were acting out a burlesque of kingship — and in doing so, they were unwittingly declaring the truth. He was a king. The crown, the robe, the scepter, the kneeling — all were real, though the soldiers meant them as insults. The irony is devastating and deliberate in the Gospel accounts.\n\nIsaiah 53:3–5, written seven centuries before the event, describes the suffering servant as despised and rejected, a man of sorrows acquainted with grief. He was wounded for our transgressions, bruised for our iniquities. The correspondence between prophecy and fulfillment is not vague — it is specific. Isaiah described the mechanism of salvation centuries before it occurred.\n\nBroader Christian reflection on the scourging has emphasized both its physicality and its substitutionary nature. The early Church father Irenaeus wrote that Christ 'recapitulated' all human suffering in Himself. Restoration theology affirms this with particular reference to Mosiah 3:7 — His suffering would cause blood to come from every pore.",
      patterns: "The mockery of Christ as king is an inversion of the triumphal entry earlier that week, when crowds genuinely hailed Him as king. The world's opinion of Christ swings wildly — but His identity never changes. This contrast between public opinion and divine reality recurs throughout scripture.",
      reflection: "The soldiers mocked Christ's kingship without realizing it was real. Are there truths about Christ that you have treated casually or taken for granted? How might you reclaim a sense of reverence?"
    },
    {
      label: "The road to Golgotha",
      focus: "Jesus carried His cross through the streets of Jerusalem. Today follows the road to Calvary and those who accompanied Him.",
      scriptures: [{book:"Luke",ch:23,vs:26,ve:32},{book:"John",ch:19,vs:16,ve:17},{book:"1 Ne",ch:11,vs:32,ve:33}],
      nuances: "In Luke 23:26, Simon of Cyrene was 'compelled' (from the Greek 'epilambanomai' — to seize or lay hold of) to carry the cross. Mark 15:21 identifies Simon as the father of Alexander and Rufus — apparently known to the early Christian community. The naming suggests Simon may have become a believer. A man forced to carry the instrument of death may have found in that burden the pathway to faith.",
      commentary: "John records that Jesus carried His own cross. The Synoptic Gospels record that Simon of Cyrene was pressed into service to carry it — likely because Jesus, weakened by scourging and blood loss, could no longer bear the weight. Both statements can be true: Jesus began carrying it and Simon was conscripted partway.\n\nLuke alone records Jesus's words to the weeping women of Jerusalem: 'Daughters of Jerusalem, weep not for me, but weep for yourselves and for your children.' Even on the road to His own execution, He was thinking of others. His warning about the coming destruction of Jerusalem (fulfilled in AD 70) reveals that even in His agony, His prophetic clarity was undiminished.\n\nNephi, in vision, saw the Son of God 'lifted up upon the cross and slain for the sins of the world.' The simplicity of 1 Nephi 11:33 is its power. Six hundred years before the event, a Nephite prophet saw it happen. The Book of Mormon does not provide extensive detail about the Crucifixion — it does not need to. The four Gospels provide the detail; the Book of Mormon provides the second witness.\n\nThe road to Golgotha has been a subject of intense devotion in Christian tradition. The Via Dolorosa in Jerusalem, the Stations of the Cross in Catholic practice, and countless hymns and artistic works all attempt to walk this path with Christ. The impulse is sound: we are meant to accompany Him, at least in our hearts.",
      patterns: "Simon of Cyrene — a man from Africa, compelled to carry a cross not his own — becomes a symbol of discipleship. We are all invited to take up our cross and follow Christ (Matthew 16:24). Sometimes the cross finds us before we find it.",
      reflection: "Simon did not choose to carry the cross — it was placed on him. Have you experienced an unwanted burden that ultimately brought you closer to Christ? Can you see that burden differently now?"
    },
    {
      label: "The seven last words — Part 1",
      focus: "From the cross, Jesus spoke seven final statements. Today examines the first four, spoken in the hours of daylight.",
      scriptures: [{book:"Luke",ch:23,vs:33,ve:43},{book:"John",ch:19,vs:25,ve:27},{book:"Ps",ch:22,vs:1,ve:8}],
      nuances: "In Luke 23:34, 'Father, forgive them; for they know not what they do' — the Greek 'aphes autois' is a present imperative, suggesting ongoing action: 'Keep forgiving them.' Some early manuscripts omit this verse, but its attestation is strong and its theology is consistent with everything Jesus taught. The prayer for forgiveness was not a one-time statement but a continuing intercession.",
      commentary: "The first word from the cross was a prayer of forgiveness for His executioners. While nails were being driven through His wrists and feet, Jesus asked the Father to forgive. The scope of this forgiveness is breathtaking — it extended not merely to the Roman soldiers but to all who contributed to His death, which, theologically, includes all of humanity. We are all implicated in the Crucifixion because we are all the reason for it.\n\nThe second word was spoken to the penitent thief: 'Today shalt thou be with me in paradise.' This is one of the most hopeful statements in scripture. A man with no time left for ordinances, for service, for years of faithful living, was promised paradise by the Savior. Grace reaches even the last moment of life.\n\nThe third word was spoken to Mary and John: 'Woman, behold thy son' and 'Behold thy mother.' Even in His extremity, Jesus ensured the care of His mother. The filial duty He performed on the cross speaks to the sanctity of family bonds — a principle central to Restoration theology and the sealing ordinances of the temple.\n\nPsalm 22, a messianic psalm written by David a thousand years earlier, describes the experience of crucifixion in remarkable detail — pierced hands and feet, garments divided by lot, surrounded by mockers. David described a form of execution that would not be invented for centuries. This psalm provides the prophetic backdrop against which the Crucifixion must be read.",
      patterns: "Forgiveness, hope, and family care — these are the themes of Christ's first words from the cross. They reveal His priorities even in death. The pattern connects to His entire ministry: He always forgave, always offered hope, and always honored sacred relationships.",
      reflection: "Of Christ's first three statements from the cross — forgiveness, hope for the repentant, and care for family — which one speaks most directly to your life right now? Why?"
    },
    {
      label: "The seven last words — Part 2",
      focus: "Darkness fell at midday. Today examines the final three statements from the cross, spoken from within the deepest suffering.",
      scriptures: [{book:"Matt",ch:27,vs:45,ve:50},{book:"John",ch:19,vs:28,ve:30},{book:"Mosiah",ch:3,vs:7,ve:8}],
      nuances: "In Matthew 27:46, 'Eli, Eli, lama sabachthani' is Aramaic, not Hebrew — Jesus cried out in His mother tongue, not the liturgical language. The shift to Aramaic in this moment of extremity suggests raw, unfiltered anguish. The quote is from Psalm 22:1. Some bystanders misheard 'Eli' as 'Elias' (Elijah), thinking He was calling for the prophet. The misunderstanding adds to the isolation: even His words were not understood.",
      commentary: "At the sixth hour (noon), darkness covered the land until the ninth hour (3:00 PM). This was not an eclipse — Passover falls on a full moon when solar eclipses are astronomically impossible. The darkness was supernatural, a sign that creation itself recoiled at what was happening.\n\nThe fourth word — 'My God, my God, why hast thou forsaken me?' — is the most agonizing cry in scripture. Jesus quoted Psalm 22:1, but He was not merely citing scripture. He was experiencing the withdrawal of the Father's sustaining presence. For the first and only time in His eternal existence, the Son experienced separation from the Father. This was necessary so that the full weight of sin, death, and hell could rest upon Him without divine support. He bore it alone so that we would never have to.\n\nThe fifth word — 'I thirst' — is the most human statement from the cross. John records it to fulfill Psalm 69:21. The Creator of water thirsted. The incarnation was not symbolic — it was real, and its cost was physical.\n\nThe sixth word — 'It is finished' (tetelestai) — is a declaration of completion. The Greek is a perfect tense verb: it has been accomplished and remains accomplished. This is not a cry of defeat but of triumph. The mission described in Week 9 is complete.\n\nThe seventh word — 'Father, into thy hands I commend my spirit' — is a prayer of trust. Having experienced the darkest moment of forsakenness, Jesus returned to address God as Father. The relationship was restored. He died as He lived: in submission to the Father.\n\nMosiah 3:7–8 describes this suffering from a prophetic vantage: He would suffer temptations, pain, hunger, thirst, and fatigue more than any human could endure without dying — and blood would come from every pore.",
      patterns: "The arc from 'My God, why hast thou forsaken me?' to 'Father, into thy hands' is the arc of redemption itself — from abandonment to restoration, from desolation to trust. This is the pattern Christ makes possible for every soul.",
      reflection: "Christ moved from feeling forsaken to entrusting Himself to the Father. Have you experienced a season of spiritual darkness? How did you find your way back to trust?"
    },
    {
      label: "The signs of His death",
      focus: "At the moment of Christ's death, extraordinary signs occurred — in Jerusalem and in the Americas. Today examines what creation did when the Creator died.",
      scriptures: [{book:"Matt",ch:27,vs:51,ve:56},{book:"Hel",ch:14,vs:14,ve:19},{book:"3 Ne",ch:8,vs:5,ve:23}],
      nuances: "In Matthew 27:51, the veil of the temple was torn 'from the top to the bottom' — 'ap' an\u014dthen he\u014ds kat\u014d.' The direction matters: it was torn from above, not from below. No human hand ripped it — God did. The veil separated the Holy Place from the Holy of Holies, where only the high priest could enter once a year. Its tearing signified that access to God's presence was now open to all through Christ.",
      commentary: "Matthew records that at the moment of Christ's death, the veil of the temple was torn in two, the earth shook, rocks split, and graves opened. These were not coincidences — they were declarations. The tearing of the veil is the most theologically significant of these signs. The barrier between humanity and God's most holy presence was removed. Access to the divine had been democratized through the death of the Son.\n\nThe earthquake and the opening of graves anticipate the Resurrection (Week 12). Even at the moment of death, the signs pointed to life. The centurion standing nearby, having witnessed everything, declared: 'Truly this was the Son of God.' A Roman soldier — a Gentile, an agent of the empire that crucified Christ — became a witness. The cross does not respect social boundaries.\n\nIn the Western Hemisphere, 3 Nephi 8 records catastrophic destruction: storms, earthquakes, cities burned, others sunk into the sea, darkness so thick it could be felt. The land was changed. Samuel the Lamanite had prophesied these signs in Helaman 14, specifying that they would occur at Christ's death. The fulfillment was precise and devastating.\n\nThe three days of darkness in the Americas (3 Nephi 8:19–23) parallel the three hours of darkness over Jerusalem. The entire creation responded to the death of its Creator. This is not mythology — it is the scriptural claim that the physical world is connected to the spiritual reality of Christ's sacrifice. When He died, the world shook.",
      patterns: "Signs at Christ's death occurred on two continents simultaneously — confirming the global scope of His sacrifice. The torn veil in Jerusalem and the destroyed cities in the Americas both declare the same truth: this death changed everything, everywhere.",
      reflection: "The veil of the temple was torn, opening access to God's presence. Are there 'veils' in your life — barriers between you and God — that Christ's sacrifice has already removed, if you will accept it?"
    },
    {
      label: "The suffering foretold",
      focus: "Prophets across centuries foresaw and described the Crucifixion. Today examines the prophetic testimony that proves this death was planned, not accidental.",
      scriptures: [{book:"Isa",ch:53,vs:3,ve:7},{book:"Ps",ch:22,vs:14,ve:18},{book:"2 Ne",ch:9,vs:5,ve:9}],
      nuances: "In Isaiah 53:7, the suffering servant is compared to 'a lamb brought to the slaughter' — the Hebrew 'seh' is the same word used for the Passover lamb in Exodus 12:3. Isaiah is explicitly connecting the servant's death to the Passover sacrifice. The servant does not merely resemble a lamb — He is the Lamb, the one to which all previous lambs pointed.",
      commentary: "Isaiah 53 is the most extensively quoted Old Testament passage in the New Testament. Written approximately 700 years before the Crucifixion, it describes the suffering servant with details that correspond precisely to the Gospel accounts: He was despised, rejected, a man of sorrows. He was wounded for our transgressions. He was oppressed and afflicted, yet He opened not His mouth. He was brought as a lamb to the slaughter.\n\nPsalm 22 adds even more specific detail. The psalmist describes pierced hands and feet, bones out of joint, a heart melted like wax, garments divided and lots cast. David wrote these words roughly 1,000 years before Calvary, describing a method of execution that did not yet exist in Israel. The specificity is stunning. These are not vague predictions — they are detailed descriptions of an event that had not yet occurred.\n\nJacob, Nephi's brother, provides the Book of Mormon's most systematic theological treatment of the Crucifixion in 2 Nephi 9. He explains why the Atonement required an infinite sacrifice. Without it, the flesh would rot, the spirit would become subject to the devil, and all humanity would be lost forever. The death of Christ was not an optional feature of the plan — it was the indispensable mechanism without which the entire plan of salvation would collapse.\n\nThe convergence of these three witnesses — Israelite prophet, Israelite king, Nephite prophet — across different centuries and continents, all describing the same event, constitutes one of the most powerful evidences of divine foreknowledge in all of scripture.",
      patterns: "Prophecy and fulfillment is one of the deepest patterns in scripture. What Isaiah saw, what David described, what Jacob taught, and what the Gospels recorded are all accounts of the same event. This convergence will be explored more fully in Weeks 39–41.",
      reflection: "The Crucifixion was not an accident or a tragedy that caught God off guard. It was planned before the foundation of the world. How does this change your understanding of suffering — both Christ's and your own?"
    },
    {
      label: "The burial and the silence",
      focus: "After His death, Jesus was laid in a borrowed tomb. Today we sit with the silence of Saturday — the day between death and resurrection.",
      scriptures: [{book:"Matt",ch:27,vs:57,ve:66},{book:"John",ch:19,vs:38,ve:42},{book:"D&C",ch:45,vs:51,ve:53}],
      nuances: "In Matthew 27:60, Joseph of Arimathea placed Jesus in his own 'new tomb' — 'kainon mn\u0113meion.' The word 'kainos' means new in quality, unused, fresh. No one had been laid there before. This detail matters: there could be no claim that the subsequent resurrection was confused with another body. The newness of the tomb eliminates ambiguity.",
      commentary: "Joseph of Arimathea, described by all four Gospels as a member of the Sanhedrin, came to Pilate and asked for the body of Jesus. This was an act of extraordinary courage. He had been a secret disciple, but the cross made him public. John adds that Nicodemus — who had first come to Jesus by night (John 3) — brought seventy-five pounds of burial spices. Two men who had hidden their discipleship now declared it openly, at the moment of Christ's apparent defeat. The cross drew out courage that persecution could not.\n\nThe burial was hasty because the Sabbath was approaching. They wrapped the body in linen, placed it in the tomb, and rolled a great stone across the entrance. Matthew records that the chief priests asked Pilate to set a guard, fearing the disciples might steal the body and claim a resurrection. The very precautions they took to prevent the appearance of resurrection would become evidence that it actually occurred.\n\nThen came Saturday — the most silent day in history. The disciples were in hiding, grieving, confused. Their leader was dead. Their movement appeared finished. We know the Resurrection is coming (Week 12), but they did not. To sit in that Saturday silence is to experience the faith that endures when hope seems dead.\n\nD&C 45:51–53 describes the future day when the Lord will stand on the Mount of Olives and the Jews will recognize His wounds. Even in prophecy about the Second Coming, the marks of the Crucifixion remain. He will bear those scars forever — not as evidence of defeat but as proof of love.",
      patterns: "The Saturday silence between Crucifixion and Resurrection mirrors many experiences in the life of faith — seasons when God seems silent, when prayers feel unanswered, when hope appears dead. But the silence of Saturday is followed by the triumph of Sunday. This pattern connects directly to Week 12.",
      reflection: "Are you in a 'Saturday' season — between a loss and a hoped-for deliverance that has not yet come? How does knowing that Sunday always follows Saturday sustain your faith?"
    }
  ]
};

export default week11;
