import type { WeekContent } from '../types';

const week25: WeekContent = {
  title: "Judge — Christ as the Eternal Judge",
  subtitle: "Jesus Christ will judge all humanity — and His judgment is perfect because He knows perfectly, loves perfectly, and has suffered perfectly.",
  weekScriptures: "Ps 96:13; Isa 33:22; Matt 12:36-37; Matt 16:27; John 5:45; Acts 17:31; Rom 2:5-8; 2 Cor 5:10; Heb 9:27; Rev 22:12; Alma 5:22; Alma 33:22; D&C 19:3; D&C 29:12",
  synthesis: {
    summary: "The doctrine of Christ as Judge is not a threat but a promise: the one who will judge you is the one who died for you. His judgment is not arbitrary or punitive — it is a perfect assessment by the Being who knows every heart, has felt every pain, and has already paid the price for every sin. Understanding Christ as Judge brings both sobriety and hope, because His justice and His mercy are equally infinite.",
    connections: [
      "Christ's role as Judge depends on His Atonement (Weeks 12–13) — He can judge perfectly because He has experienced all things and paid for all sins.",
      "The authority to judge is part of the authority of Christ studied in Week 23 — the Father has committed all judgment to the Son (John 5:22).",
      "The principles of judgment connect to Week 9 (Grace) and Week 10 (Mercy), where the interplay between justice and mercy is explored."
    ],
    teaching: "How does knowing that your Judge is also your Advocate (D&C 45:3–5) change the way you think about the final judgment? Does the doctrine of Christ as Judge produce more fear or more hope in you — and why?",
    commitment: "This week, bring one specific sin or burden to Christ in prayer — not asking merely for comfort but specifically asking Him to exercise His role as Advocate and Mediator on your behalf. Trust that the Judge is on your side."
  },
  days: [
    {
      label: "All judgment given to the Son",
      focus: "The Father has entrusted all judgment to Jesus Christ. Today examines why the Son — rather than the Father — is the appointed Judge of all humanity.",
      scriptures: [{book:"John",ch:5,vs:22,ve:30},{book:"Acts",ch:10,vs:42},{book:"2 Tim",ch:4,vs:1}],
      nuances: "In John 5:22, 'the Father judgeth no man, but hath committed all judgment unto the Son' — the Greek 'krisin pasan' (all judgment) is comprehensive, and 'dedoken' (has given) is perfect tense, indicating a completed, permanent transfer. In John 5:27, authority to judge is given because He is 'the Son of man' — His humanity, not just His divinity, qualifies Him. He judges as one who has lived the mortal experience. Acts 10:42 uses 'horismenos' (appointed, ordained) — Christ was specifically designated for this role.",
      commentary: "The Father has given all judgment to the Son. This is not delegation by convenience — it is theologically necessary. The Son became mortal. He lived in a body of flesh, experienced hunger and fatigue, felt the sting of betrayal, and suffered the full weight of human sin and sorrow. He judges not from a distance but from the inside of the human experience.\n\nJohn 5:27 makes this explicit: the Father gave Him authority to execute judgment 'because he is the Son of man.' The title 'Son of man' emphasizes His humanity. He is qualified to judge you not only because He is God but because He is human — or rather, because He is both. He knows what it is like to be you. He has felt what you feel. His judgment is informed by perfect empathy as well as perfect knowledge.\n\nActs 10:42 records Peter's testimony that God 'ordained' Christ to be the judge of the living and the dead. The appointment is intentional and announced. No one will stand before an unfamiliar judge. Every person will stand before the Being who created them, redeemed them, and knows them by name.\n\n2 Timothy 4:1 adds that Christ will judge 'the quick and the dead at his appearing and his kingdom.' The judgment is tied to His return — a future event that every prophet has anticipated. The second coming is not only a rescue but a reckoning, and the one who comes is qualified for both.",
      patterns: "The pattern of Christ as Judge is foreshadowed in the Old Testament. The Lord is repeatedly called 'the Judge of all the earth' (Gen. 18:25). The Psalms declare that God 'cometh to judge the earth' (Ps. 96:13). The Book of Mormon prophets consistently identify Jesus Christ as this coming Judge (2 Ne. 9:15; Morm. 3:20). The identity of the God who judges Israel and the Christ who saves the world are one and the same.",
      reflection: "Does knowing that your Judge has personally experienced every temptation, sorrow, and weakness you have ever faced make you more or less anxious about the final judgment? Why?"
    },
    {
      label: "Judged by our works and desires",
      focus: "Scripture describes judgment based on works, words, thoughts, and desires. Today examines what exactly Christ will judge — and what standard He will use.",
      scriptures: [{book:"Rev",ch:20,vs:12,ve:13},{book:"Alma",ch:12,vs:12,ve:15},{book:"Eccl",ch:12,vs:14}],
      nuances: "In Revelation 20:12, 'the books were opened' — 'biblia' (books, the root of 'Bible') here refers to the records of human deeds. A second book, 'the book of life,' is also opened. Judgment involves both a record of what you did and a registry of who you are. In Alma 12:14, 'our words will condemn us, yea, all our works will condemn us ... and our thoughts will also condemn us' — the progression from external to internal suggests that judgment penetrates to the deepest level of the person.",
      commentary: "The judgment described in Revelation 20 is comprehensive: the dead are judged 'out of those things which were written in the books, according to their works.' Every life is recorded. Every act has a witness. This is not meant to terrify but to communicate that nothing is overlooked — neither your worst moments nor your best ones. The full picture will be seen.\n\nAlma 12:12–15 extends the scope of judgment beyond actions to include words and thoughts. This is both sobering and liberating. It is sobering because it means outward compliance is not enough — the heart matters. It is liberating because it means the quiet acts of faithfulness that no one saw, the private prayers, the internal battles you fought and won, are all part of the record. Nothing good is lost.\n\nEcclesiastes 12:14 states that 'God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil.' The inclusion of secret things means there is no hiding — but it also means there is no unnoticed sacrifice. The kindness you showed when no one was watching is known to the Judge.\n\nThe standard of judgment is not perfection in isolation. Alma 41 teaches that restoration is the principle — you receive back what you have put forth. If you have sent out righteousness, mercy, and faith, that is what returns to you. The judgment is not an arbitrary pass-fail exam but a harvest of what you have sown throughout your life.",
      patterns: "The principle that God judges the heart as well as the hand appears throughout scripture. Samuel was taught, 'The Lord looketh on the heart' (1 Sam. 16:7). Jesus taught that a person who looks on someone with lust has already committed sin in his heart (Matt. 5:28). The internal life matters as much as the external — and the Judge sees both with perfect clarity.",
      reflection: "If Christ were to judge your heart right now — not just your actions but your desires, intentions, and private thoughts — what would He find that gives you hope? What would you want Him to help you change?"
    },
    {
      label: "Justice and the demands of the law",
      focus: "Christ as Judge must satisfy the demands of justice. Today examines the scriptural teaching that justice is a real, unalterable law — and what that means for every sinner.",
      scriptures: [{book:"2 Ne",ch:9,vs:15,ve:16},{book:"Mosiah",ch:3,vs:24,ve:27},{book:"Mosiah",ch:16,vs:10,ve:11}],
      nuances: "In 2 Nephi 9:15, 'all men shall stand in the presence of God to be judged' — the word 'all' (kol in Hebrew, pantes in Greek equivalents) permits no exception. Every person who has ever lived will face this moment. In Mosiah 3:25, the 'awful view of their own guilt' uses the word 'awful' in its older sense of 'full of awe' — an overwhelming, terrifying realization of the gap between what they were and what they could have been.",
      commentary: "Jacob's sermon in 2 Nephi 9 is one of the most unflinching descriptions of judgment in scripture. All will stand before God, and the righteous will have a 'perfect knowledge of their enjoyment, and their righteousness.' But the wicked will also have a perfect knowledge — of their guilt, their uncleanness, and their nakedness before a holy God. The asymmetry is stark: perfect knowledge is a blessing for the righteous and a torment for the wicked.\n\nMosiah 3:24–27, part of King Benjamin's address, describes those who die in their sins as being in a state where justice has 'full sway' — unmitigated by mercy. They drink damnation 'as if there were no redemption made.' The language is severe because the stakes are real. Justice is not a metaphor. It is the foundational law of the universe, and it demands that every debt be paid.\n\nMosiah 16:10–11 (Abinadi's words before he was executed) makes the duality clear: those who have listened to the prophets and believed in Christ are raised to eternal life, while those who have persisted in rebellion 'shall be as though there had been no redemption made.' The Atonement is real, but it must be accepted. Justice is the default; mercy is the exception that requires engagement.\n\nThis is why the Atonement is not merely a nice idea but an absolute necessity. Without it, justice would condemn every imperfect person — which means everyone. Christ as Judge has the authority to execute justice, but He has also paid the price that makes mercy available. The question is not whether justice will be satisfied (it will) but whether you will allow Christ's sacrifice to satisfy it on your behalf.",
      patterns: "The tension between justice and mercy is the central dramatic tension of the gospel. Alma 42 is the most systematic treatment: justice cannot be destroyed without God ceasing to be God, but mercy can claim the penitent through the Atonement. This tension is resolved only in Christ — the unique being who can be both perfectly just and perfectly merciful. This connects directly to Weeks 9–10 (Grace and Mercy).",
      reflection: "Do you tend to emphasize God's justice or God's mercy in your personal understanding? How might a fuller appreciation of both change the way you approach repentance and the final judgment?"
    },
    {
      label: "Mercy and the Advocate",
      focus: "Christ is both Judge and Advocate — the one who pronounces the verdict is the same one who pleads your case. Today examines the doctrine that the Judge is on your side.",
      scriptures: [{book:"3 Ne",ch:27,vs:14,ve:16},{book:"D&C",ch:76,vs:68},{book:"2 Ne",ch:9,vs:21,ve:22}],
      nuances: "In 3 Nephi 27:14, 'I have been lifted up upon the cross ... that I might draw all men unto me' — the verb 'draw' (helkuo in Greek equivalents) means to pull with force, as a fisherman draws in a net. Christ's Atonement is not a passive offer but an active drawing. In D&C 76:68, those who inherit the celestial kingdom are described as those 'into whose hands the Father has given all things.' The language parallels John 5:22 — the same Christ who judges also gives all things to the redeemed.",
      commentary: "The most remarkable feature of Christ as Judge is that He is simultaneously the one who judges and the one who has already paid the price for every sin He is judging. He is not a disinterested magistrate. He is the Advocate — the one who pleads the case of the accused before the bar of justice. D&C 45:3–5 makes this explicit: Christ says to the Father, 'Spare these my brethren that believe on my name, that they may come unto me and have everlasting life.'\n\n3 Nephi 27:14–16 reveals the mechanics: Christ was lifted up on the cross to draw all people to Him, and He will stand before the Father to judge the world. His judgment is not vindictive but redemptive — He judges in order to claim those who have come to Him. The purpose of judgment is not to condemn but to sort — to give every person the glory they have prepared themselves to receive.\n\n2 Nephi 9:21–22 describes the comprehensive scope of Christ's suffering: He suffered for all, that all might be brought to stand before Him. The suffering was not selective. He bore the sins and pains of every person who has ever lived or ever will live. This means that when He judges you, He does so as someone who has already carried your exact burden. He knows the weight of your specific sins because He has felt them.\n\nD&C 76:68 places Christ at the center of the celestial kingdom — the judge is also the host. Those who are judged worthy do not enter a courtroom; they enter a home. The judgment leads to reunion, not sentence. For the repentant, the final judgment is not a trial to be feared but a homecoming to be anticipated.",
      patterns: "The dual role of Judge and Advocate resolves what appears to be a contradiction in the gospel: how can the same God be perfectly just and perfectly merciful? The answer is that He paid the price Himself. Justice is satisfied because someone paid; mercy is extended because the one who paid is the one who judges. This resolution is unique to the Christian gospel and finds its fullest expression in Restoration theology.",
      reflection: "When you think about standing before Christ at the judgment, do you imagine a courtroom or a reunion? What would it take for your dominant feeling about that moment to shift from fear to hope?"
    },
    {
      label: "Judging the living and the dead",
      focus: "Christ's judgment extends to every person who has ever lived — including those who never heard His name. Today examines the scope of His judgment and the doctrine of a fair opportunity for all.",
      scriptures: [{book:"D&C",ch:137,vs:7,ve:9},{book:"Morm",ch:3,vs:20},{book:"Rom",ch:14,vs:10,ve:12}],
      nuances: "In D&C 137:7, Joseph Smith sees his deceased brother Alvin in the celestial kingdom and is told that 'all who have died without a knowledge of this gospel, who would have received it if they had been permitted to tarry, shall be heirs of the celestial kingdom.' The verb 'would have received' (conditional) acknowledges the full agency of those being judged — God judges on the basis of the heart's intent, not merely the accident of circumstance. In Romans 14:12, 'every one of us shall give account of himself to God' — the singular 'hekastos' (each one) individualizes the judgment.",
      commentary: "One of the deepest questions in theology is what happens to the billions of people who lived and died without ever hearing of Jesus Christ. If salvation requires faith in His name, are they condemned by geography and timing? The Restoration provides a distinctive and powerful answer.\n\nD&C 137:7–9 records Joseph Smith's vision of the celestial kingdom, where he saw people who had not been baptized in mortality but who were nevertheless heirs of celestial glory. The Lord explained the principle: those who died without knowledge of the gospel but who would have received it if they had the chance are saved. God judges the heart — not just the actions that circumstances permitted, but the actions the heart would have chosen.\n\nThis doctrine expands the scope of Christ's judgment to encompass every soul who has ever lived, in every era and every land. No one falls through the cracks. The judgment is individually tailored — each person is assessed according to the light they received, the opportunities they had, and the desires of their heart. This is why vicarious ordinances for the dead (baptism for the dead, temple work) are essential: they provide the outward form that the inward heart has already accepted.\n\nMormon 3:20 urges all people — 'ye Gentiles, and also ye house of Israel' — to prepare for the day when they must stand before the judgment seat of Christ. The address is universal. Romans 14:12 confirms that every person will give account individually — not as a nation, a family, or a church, but as a single soul standing before the one who knows them completely.",
      patterns: "The principle of judgment according to light received appears throughout scripture. Jesus Himself taught that the servant who knew his master's will and did not do it would be beaten with many stripes, while the servant who did not know would be beaten with few (Luke 12:47–48). Alma taught that men are judged according to the law they have received (Alma 42:21–22). The principle is consistent: God is perfectly fair.",
      reflection: "How does the doctrine that God judges the heart — including what a person would have done if given the opportunity — change the way you think about people who never heard the gospel? How does it change the way you think about yourself?"
    },
    {
      label: "The sheep and the goats",
      focus: "In one of His most vivid parables, Jesus described the final judgment as a separation based on how people treated the least among them. Today examines what this teaches about the criteria of judgment.",
      scriptures: [{book:"Matt",ch:25,vs:31,ve:46},{book:"Mosiah",ch:4,vs:16,ve:19},{book:"Alma",ch:5,vs:15,ve:18}],
      nuances: "In Matthew 25:40, 'the least of these my brethren' — 'elachistos' (least, smallest) describes those at the very bottom of social status. The identification of Christ with the vulnerable is radical: serving the hungry, the stranger, the naked, and the imprisoned is literally serving Christ. The parable inverts social categories — the criteria for eternal judgment is not doctrinal knowledge or ritual observance but compassionate action toward the overlooked.",
      commentary: "The parable of the sheep and the goats is the most detailed description of the final judgment in the Gospels. The King separates humanity into two groups based on a single criterion: how they treated the hungry, the thirsty, the stranger, the naked, the sick, and the imprisoned. Those who served these 'least' are welcomed into the kingdom. Those who ignored them are sent away.\n\nThe most astonishing element of the parable is Christ's self-identification with the vulnerable: 'Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me.' This is not metaphor. Christ is present in the person who needs help. When you feed the hungry, you feed Him. When you ignore the suffering, you ignore Him. The judgment reveals a truth that was always operative: every encounter with a person in need is an encounter with Christ.\n\nKing Benjamin taught the same principle in Mosiah 4:16–19: 'Are we not all beggars?' He connects charitable action to an understanding of our own dependence on God's grace. We serve others not from a position of superiority but from the recognition that we are all recipients of divine mercy. The judgment in the parable is not about earning salvation through good works but about whether we have internalized the character of Christ — whether compassion has become part of who we are.\n\nAlma 5:15–18 asks pointed questions about readiness for judgment: 'Can you imagine yourselves brought before the tribunal of God with your souls filled with guilt and remorse?' Alma is not trying to terrify — he is trying to awaken. The time to develop a heart of compassion is now, not at the judgment bar.",
      patterns: "The principle that treatment of others reveals one's relationship with God appears throughout scripture. The two great commandments (love God, love your neighbor) are inseparable (Matt. 22:36–40). John teaches that if you do not love your brother whom you have seen, you cannot love God whom you have not seen (1 Jn. 4:20). The judgment of the sheep and goats is the culmination of this principle.",
      reflection: "If the final judgment were based primarily on how you treated the 'least' in your life, how would you fare? Who are the 'least' in your sphere — the overlooked, the struggling, the forgotten — and what can you do for them this week?"
    },
    {
      label: "Facing the Judge with confidence",
      focus: "Scripture invites disciples to approach the judgment not with terror but with hope. Today examines how the Atonement transforms the judgment from a sentence into a homecoming.",
      scriptures: [{book:"Moro",ch:10,vs:34},{book:"John",ch:12,vs:47,ve:48},{book:"Alma",ch:41,vs:2,ve:6}],
      nuances: "In Moroni 10:34, 'the pleasing bar of the great Jehovah, the Eternal Judge of both quick and dead' — the word 'pleasing' is remarkable. Moroni does not call it the 'dreadful' or 'fearsome' bar but the pleasing bar. For the faithful, the judgment is not dreaded but welcomed. In John 12:47, 'I came not to judge the world, but to save the world' — 'sozein' (to save) is Christ's stated purpose. Judgment is His function; salvation is His intent. Alma 41:3's principle of restoration means the judgment is organic: you receive back the quality of life you lived.",
      commentary: "Moroni's farewell — the last words of the last Nephite prophet — looks forward to the judgment with anticipation, not dread. He describes it as 'the pleasing bar of the great Jehovah.' This is a man who lost his entire civilization, watched his people destroyed, and wandered alone for decades. Yet his final words are hopeful. He will meet his Savior, and that meeting will be pleasing.\n\nJohn 12:47–48 contains one of Christ's most reassuring statements: 'I came not to judge the world, but to save the world.' Judgment is a necessary function, but it is not His primary purpose. He came to rescue, not to condemn. The word that He has spoken will serve as the standard of judgment — not an arbitrary standard but the very words He used to try to save people. Those who reject His word reject not an angry judge but a pleading savior.\n\nAlma 41:2–6 teaches the principle of restoration: in the resurrection and judgment, every person is restored to the condition they have created through their choices. If they have desired righteousness, they are restored to righteousness. If they have desired evil, they are restored to evil. The judgment is not an external imposition but an internal revelation — you receive what you have become.\n\nThis is profoundly hopeful for the repentant. If you have turned to Christ, sought His forgiveness, and allowed His Atonement to change your desires, then the restoration will bring you back to the righteousness He has cultivated in you. The judgment reveals what grace has done. For the faithful disciple, standing before Christ is not the moment of sentencing — it is the moment of recognition. You will see the one who saved you, and He will see the person He helped you become.",
      patterns: "The scriptural pattern of judgment as restoration and recognition rather than mere sentencing runs from the Psalms ('the righteous shall be glad when they see thy face,' Ps. 17:15) to the Revelation of John ('they shall see his face,' Rev. 22:4). The final judgment is the ultimate fulfillment of the promise to know God face to face — and for those who have sought Him, that encounter will be the greatest joy of their eternal existence.",
      reflection: "When you imagine meeting Jesus Christ face to face, what is the dominant emotion — fear, hope, joy, uncertainty? What would it take for that encounter to feel like the 'pleasing bar' that Moroni describes?"
    }
  ]
};

export default week25;
