import type { WeekContent } from '../types';

const week35: WeekContent = {
  title: "Second Comforter — Christ Himself as the Promise",
  subtitle: "Beyond the Holy Ghost, there is a greater promise: that Christ Himself will manifest to the faithful.",
  weekScriptures: "John 14:26; John 16:7; D&C 88:67-68; D&C 121:45-46; D&C 50:45; Gen 32:30; Ex 33:11; Isa 25:9; 1 Jn 3:2; Moro 7:26; D&C 76:12-14; Moses 7:4; D&C 97:16",
  synthesis: {
    summary: "This week explores one of the most sacred doctrines in Restoration theology: the Second Comforter. Christ promised His disciples that after the first Comforter (the Holy Ghost), He Himself would come to those who love Him and keep His commandments. This is not merely symbolic — it is a literal promise that the faithful may come to know Christ personally. The doctrine of the Second Comforter frames the entire purpose of the gospel: not merely to learn about Christ, but to know Him and to be known by Him.",
    connections: [
      "Week 34's study of the Spirit of Christ provides the foundation — the Light of Christ and the Holy Ghost prepare the soul for the greater manifestation of Christ Himself.",
      "The Second Comforter doctrine connects to Week 33's study of Christ's relationship with the Father — Christ promised that He and the Father would come together (John 14:23).",
      "This promise of personal knowledge of Christ connects forward to Weeks 42–43 on Christ's appearances and to Week 1's culminating theme of knowing Him."
    ],
    teaching: "What is the relationship between the first Comforter (the Holy Ghost) and the Second Comforter (Christ Himself)? Is the Second Comforter a realistic hope for ordinary believers, or is it reserved for prophets?",
    commitment: "This week, let John 14:21 guide your prayers: 'He that hath my commandments, and keepeth them, he it is that loveth me... and I will manifest myself to him.' Ask yourself what commandment you could keep more faithfully."
  },
  days: [
    {
      label: "Two Comforters promised",
      focus: "Christ promised not one but two Comforters. Today examines the distinction and the progressive nature of the promise.",
      scriptures: [{book:"John",ch:14,vs:16,ve:18},{book:"D&C",ch:88,vs:3,ve:4},{book:"John",ch:14,vs:21}],
      nuances: "In John 14:16, Christ says the Father will give 'another Comforter' — the Greek 'allon paraklēton' (another advocate/helper of the same kind). Then in verse 18, He says 'I will not leave you comfortless: I will come to you.' The shift from 'another' to 'I myself' signals two distinct promises: first the Holy Ghost, then Christ's own return to the believer.",
      commentary: "John 14 contains some of the most intimate promises Christ ever made. He begins by promising 'another Comforter' — the Holy Ghost — who would abide with the disciples forever. This is the first Comforter, and it is the gift every confirmed member of the Church receives.\n\nBut Christ did not stop there. In verse 18, He promised something more: 'I will come to you.' This is not a reference to the Second Coming but to a personal manifestation. Verse 21 makes the conditions explicit: 'He that hath my commandments, and keepeth them, he it is that loveth me: and he that loveth me shall be loved of my Father, and I will love him, and will manifest myself to him.'\n\nD&C 88:3–4 identifies this as the doctrine of the Second Comforter — the promise of the Lord's presence, the promise of eternal life, the 'other Comforter' spoken of in John 14. Joseph Smith taught that when a person receives the Second Comforter, the Lord Jesus Christ visits them personally and reveals the Father.\n\nThis is not reserved for the distant future or for only a few. The conditions are stated plainly: love Him, keep His commandments, and He will manifest Himself. The promise is conditional but not exclusive. It stands open to every faithful disciple.",
      patterns: "The two-Comforter pattern mirrors the progressive structure of the gospel ordinances: baptism and confirmation as the gate, then a lifetime of covenant faithfulness leading toward the fulness of God's presence. This parallels the temple's own progressive symbolism.",
      reflection: "Christ promised to manifest Himself to those who love Him and keep His commandments. Do you believe this promise is for you? If hesitation arises, why?"
    },
    {
      label: "Making His abode",
      focus: "Christ promised that He and the Father would come and make their abode with the faithful. Today examines this remarkable promise of divine indwelling.",
      scriptures: [{book:"John",ch:14,vs:21,ve:23},{book:"Rev",ch:3,vs:20},{book:"D&C",ch:130,vs:3}],
      nuances: "In John 14:23, 'we will come unto him, and make our abode with him,' the Greek 'monēn' (abode, dwelling place) is the same word used in verse 2 for the 'mansions' in the Father's house. The parallel is deliberate: just as the Father's house has a dwelling place prepared for us, so we can become a dwelling place for the Father and the Son. The relationship is reciprocal.",
      commentary: "John 14:23 contains one of the most astonishing promises in all scripture: 'If a man love me, he will keep my words: and my Father will love him, and we will come unto him, and make our abode with him.' Not just the Son, but the Father and the Son together will come and dwell with the faithful disciple. The language of 'abode' implies permanence — not a brief visit but a lasting presence.\n\nRevelation 3:20 offers the same invitation in different imagery: Christ stands at the door and knocks. If anyone hears and opens, He will come in and dine with them. The initiative is Christ's — He is the one knocking. But the response must be ours — we must open the door. He will not force entry.\n\nD&C 130:3 confirms and expands: the appearing of the Father and the Son (in John 14:23) is a personal appearance, and the idea that the Father and the Son dwell in a man's heart is an old sectarian notion and is false. The Restoration takes these promises literally — not as metaphorical indwelling but as actual divine visitation.\n\nThis literalness matters because it grounds the promise in reality. The Second Comforter is not a warm feeling or a theological concept. It is the living Christ coming to a living person. The scriptures record multiple instances of this happening — to Stephen, to Paul, to the brother of Jared, to Joseph Smith — and promise that it can happen to any who qualify through faithfulness.",
      patterns: "The image of Christ standing at the door connects to the temple, where symbolic entry into God's presence follows a pattern of progressive worthiness and invitation. The temple ordinances prepare us for what the Second Comforter promises in reality.",
      reflection: "Revelation 3:20 says Christ is already knocking. If He is knocking at the door of your life right now, what might be preventing you from fully opening it?"
    },
    {
      label: "Face to face",
      focus: "Scripture records multiple instances of mortals seeing Christ face to face. Today examines these encounters and what they teach about the Second Comforter.",
      scriptures: [{book:"Ether",ch:3,vs:13,ve:16},{book:"D&C",ch:67,vs:10,ve:13},{book:"D&C",ch:93,vs:1}],
      nuances: "In Ether 3:13, when the Lord reveals Himself to the brother of Jared, He says 'never has man come before me with such exceeding faith as thou hast.' The word 'come' (rather than 'called' or 'prayed') suggests physical or spiritual proximity — the brother of Jared drew near to God. Faith here is not passive belief but active approach.",
      commentary: "The brother of Jared's experience in Ether 3 is one of the most detailed accounts of a mortal encountering the premortal Christ. Because of his extraordinary faith, the veil was taken from his eyes and he saw the finger of the Lord — then the Lord revealed His full spirit body. Christ told him that He would take upon Himself this same body in the flesh. The brother of Jared saw what no one before him had seen, because he believed what no one before him had believed with such intensity.\n\nD&C 67:10–13 extends the invitation to the modern era: 'ye are not able to abide the presence of God now, neither the ministering of angels; wherefore, continue in patience until ye are perfected.' The Lord acknowledges that this encounter requires preparation — purification of heart, stripping of jealousies and fears, humbling oneself before God. The Second Comforter is not casual; it requires readiness.\n\nD&C 93:1 states the principle universally: 'every soul who forsaketh his sins and cometh unto me, and calleth on my name, and obeyeth my voice, and keepeth my commandments, shall see my face and know that I am.' The word 'every' is significant. This is not an elite promise for prophets alone — it is stated as a universal principle with universal conditions.\n\nThe conditions are demanding but clear: forsake sin, come to Christ, call on His name, obey His voice, keep His commandments. The path is not mysterious. It is the covenant path, walked with full intent and faith.",
      patterns: "Face-to-face encounters with God occur across all dispensations: Adam, Enoch, Moses, the brother of Jared, Isaiah, Nephi, Joseph Smith. The pattern is consistent — faith, purity, and persistent seeking lead to the divine presence. This connects to Week 42's study of Christ's appearances.",
      reflection: "D&C 93:1 says 'every soul' who meets the conditions shall see Christ's face. Do you take this promise literally? What would change in your life if you did?"
    },
    {
      label: "Knowing Him",
      focus: "The Second Comforter is not merely about seeing Christ but about knowing Him. Today examines the doctrine of personal, experiential knowledge of God.",
      scriptures: [{book:"John",ch:17,vs:3},{book:"3 Ne",ch:11,vs:14,ve:15},{book:"D&C",ch:76,vs:116,ve:118}],
      nuances: "In John 17:3, 'this is life eternal, that they might know thee the only true God, and Jesus Christ, whom thou hast sent,' the Greek 'ginōskōsin' (know) implies experiential, relational knowledge — not mere intellectual awareness. It is the same word used for the most intimate forms of human knowing. Eternal life is defined not as endless duration but as a quality of relationship.",
      commentary: "John 17:3 redefines eternal life. It is not primarily about living forever — it is about knowing God. The word 'know' here carries the weight of personal, experiential relationship. It is the difference between reading about a person and sitting across from them at a table. Eternal life is relationship with God carried to its fulness.\n\n3 Nephi 11:14–15 records the most physically intimate encounter with the risen Christ in all scripture. He invited the Nephite multitude — all 2,500 of them — to come forward one by one, thrust their hands into His side, and feel the prints of the nails in His hands and feet. This was not a distant theophany; it was personal, physical, tactile. They knew Him not by argument but by touch.\n\nD&C 76:116–118 describes a vision so glorious that Joseph Smith and Sidney Rigdon were commanded to seal it up. They saw what no one else has seen in this dispensation — the full scope of God's plan, the glory of the celestial kingdom, the fate of all humanity. And the closing testimony is that the vision was seen 'while we were yet in the Spirit.' The knowing came through the Spirit's power.\n\nThe doctrine of the Second Comforter insists that the goal of the gospel is not theological correctness but personal encounter. You can know true things about Christ without knowing Christ. The Second Comforter closes that gap.",
      patterns: "The progression from knowing about God to knowing God personally runs through the entire scriptural narrative. Abraham sought to be a greater follower of righteousness and received personal encounters. The pattern is always the same: seeking leads to finding.",
      reflection: "There is a difference between knowing about Christ and knowing Him. Where do you feel you are on that spectrum? What would it look like to move from information toward intimacy?"
    },
    {
      label: "Abiding in the vine",
      focus: "The Second Comforter is not a single event but an ongoing relationship. Today examines Christ's teaching about abiding — remaining connected to Him.",
      scriptures: [{book:"John",ch:15,vs:4,ve:5},{book:"3 Ne",ch:19,vs:29},{book:"Alma",ch:32,vs:41,ve:43}],
      nuances: "In John 15:4, 'abide in me, and I in you,' the Greek 'meinate' (abide, remain, stay) is an imperative — a command. It is in the aorist tense, which in the imperative can carry the sense of a decisive commitment: not 'keep abiding' (which would be present tense) but 'make the choice to abide.' The decision to remain in Christ is active and deliberate.",
      commentary: "The image of the vine and the branches in John 15 is one of Christ's most powerful metaphors. The branch cannot bear fruit by itself — it must abide in the vine. Apart from Christ, we can do nothing. The relationship is not optional for spiritual productivity; it is essential.\n\nBut the metaphor also implies intimacy. A branch does not merely touch the vine — it is organically connected. The life of the vine flows through the branch. This is what abiding means: not proximity but union. The same life force that sustains Christ sustains the disciple who remains connected to Him.\n\n3 Nephi 19:29 records a moment of extraordinary abiding: Christ's Nephite disciples were filled with the Holy Ghost and with fire, and Christ prayed for them, and the Father heard Him because of their faith. The unity between Christ, the Father, and the disciples was complete — a living demonstration of the vine and branches.\n\nAlma 32:41–43 adds the dimension of patience. The tree of faith, once planted, must be nourished over time before it bears fruit. Alma warns against casting the tree out by neglect. Abiding is not a single decision but a sustained commitment — daily nourishing, daily choosing to remain in Christ even when the fruit has not yet appeared.\n\nThe Second Comforter, then, is not only a dramatic encounter but the culmination of a lifetime of quiet abiding.",
      patterns: "The vine and branches metaphor parallels the tree of life (1 Nephi 8, 11) — remaining connected to the source of life is the central challenge of discipleship. This connects to Week 36's exploration of covenant faithfulness.",
      reflection: "What does 'abiding in Christ' look like practically in your daily life? Is there an area where you sense the connection growing thin — and what would it take to strengthen it?"
    },
    {
      label: "The charity that qualifies",
      focus: "The Second Comforter requires preparation of heart. Today examines charity — the pure love of Christ — as the qualifying attribute.",
      scriptures: [{book:"Moro",ch:7,vs:47,ve:48},{book:"John",ch:14,vs:21},{book:"2 Ne",ch:32,vs:6}],
      nuances: "In Moroni 7:47, 'charity is the pure love of Christ, and it endureth forever,' the phrase 'pure love of Christ' is grammatically ambiguous — it can mean the love that Christ has for us, or the love we have that is like Christ's, or both. Mormon may have intended the ambiguity: charity is both the love Christ gives and the love Christ inspires, and they are ultimately the same love flowing through different vessels.",
      commentary: "Moroni 7:47–48 is the capstone of Mormon's great sermon. After discussing faith, hope, and charity, he declares that charity is the greatest, defines it as the pure love of Christ, and commands us to pray for it with all the energy of heart. The one who possesses charity will be like Christ when He appears — because charity is Christ's own nature shared with the believer.\n\nJohn 14:21 ties this directly to the Second Comforter: the one who has Christ's commandments and keeps them is the one who loves Him. And the one who loves Him will be loved by the Father, and Christ will manifest Himself to that person. The qualifying condition is love expressed through obedience. Not perfect performance, but a heart genuinely oriented toward Christ and demonstrated through faithful living.\n\n2 Nephi 32:6 records Nephi's sorrow that the people could not understand his plain words about relying on the Holy Ghost. The reason was that they had hardened their hearts against the Spirit. The barrier to the Second Comforter is not intellectual — it is spiritual. A hard heart cannot receive what a soft heart is promised.\n\nCharity softens the heart. It is not merely a nice quality to develop — it is the very condition that makes divine encounter possible. When Mormon says to pray for charity with all the energy of heart, he is describing the preparation for the Second Comforter itself.",
      patterns: "Charity as the qualifying attribute connects to the temple, where the final promise is to enter God's presence. The progression — faith, hope, charity, divine encounter — is the same progression taught in Moroni 7 and enacted in temple ordinances.",
      reflection: "Mormon commands us to pray for charity with 'all the energy of heart.' Have you ever prayed for charity with that kind of intensity? What would such a prayer look like tonight?"
    },
    {
      label: "The open invitation",
      focus: "The doctrine of the Second Comforter is not reserved for prophets or the ancient past. Today brings the week's study home as a present, personal invitation.",
      scriptures: [{book:"D&C",ch:93,vs:1},{book:"John",ch:14,vs:23},{book:"D&C",ch:76,vs:116,ve:118}],
      nuances: "D&C 93:1 begins with the word 'Verily' — a translation convention, but in Joseph Smith's revelatory vocabulary, it consistently introduces statements of binding, covenantal truth. What follows is not a suggestion but a divine guarantee: meet the conditions, and the result is sure.",
      commentary: "D&C 93:1 states the doctrine with absolute clarity: every soul who forsakes sin, comes unto Christ, calls on His name, obeys His voice, and keeps His commandments shall see His face and know that He is. The word 'every' makes this universal. The word 'shall' makes it certain. This is a divine guarantee with stated conditions.\n\nJohn 14:23 repeats the promise from Christ's own lips: the Father and the Son will come to the faithful and make their abode. The language is warm, domestic, intimate — an abode, a home. God does not promise a brief audience but a sustained dwelling. He wants to live with us.\n\nD&C 76:116–118 reminds us that the fulness of God's glory is beyond present capacity to describe or comprehend. The Second Comforter is not the end of the journey but the beginning of an eternal one — the entrance into a relationship with God that deepens forever.\n\nThe practical question for the believer is not whether this doctrine is true but whether it is personally relevant. The scriptures answer emphatically: yes. This promise is not for a spiritual elite. It is for every covenant-keeping disciple who pursues it with patience, faith, and obedience. The path is the covenant path. The destination is Christ Himself.\n\nThis week has traced a trajectory from promise to preparation to encounter. The invitation stands open. The door is not locked. Christ is already knocking.",
      patterns: "The Second Comforter doctrine brings together the threads of Week 32 (divine sonship), Week 33 (relationship with the Father), and Week 34 (the Spirit of Christ). The Spirit leads to Christ; Christ leads to the Father. The entire sequence is one continuous invitation into the divine presence.",
      reflection: "As you close this week's study, consider: the Second Comforter is not a doctrine to admire from a distance but a promise to claim through faithfulness. What is one thing you will do differently starting today because of what you have learned?"
    }
  ]
};

export default week35;
