import type { WeekContent } from '../types';

const week38: WeekContent = {
  title: "Family of — The Mortal and Eternal Family of Jesus Christ",
  subtitle: "Christ was born into a real family, shaped by real relationships, and invites all of us into His spiritual family.",
  weekScriptures: "Luke 2:1-7; John 2:1-5; John 6:42; Isa 7:14; Eph 2:19; Eph 3:14-15; Heb 2:11-13; Mosiah 27:25; D&C 39:4; D&C 93:23; Heb 2:17-18; 1 Jn 3:1-2; Rom 9:5; D&C 93:38",
  synthesis: {
    summary: "Jesus Christ was not born into abstraction. He had a mother who pondered, a father who protected, siblings who doubted, and a cousin who prepared His way. His mortal family shaped His experience and fulfilled prophecy. Yet He also defined family in radically spiritual terms — declaring that all who do the will of His Father belong to Him. This week explores both the human and the eternal dimensions of Christ's family.",
    connections: [
      "Christ's mortal family ties connect to Week 12 (Birth/Nativity), where the circumstances of His arrival are studied in depth.",
      "The concept of becoming sons and daughters of Christ through covenant connects to Week 20 (Atonement) and Week 41 (Types in Memory).",
      "Mary's role as a witness foreshadows the theme of personal testimony explored in Week 24 (Testimony of Jesus Christ)."
    ],
    teaching: "What does it mean that God chose a specific family — with all its imperfections and challenges — as the setting for the mortal life of His Son?",
    commitment: "Consider your own family relationships this week. How does understanding Christ's family experience change how you approach yours?"
  },
  days: [
    {
      label: "Mary, the chosen vessel",
      focus: "The angel's visit to Mary and her extraordinary response of faith. What does her willingness teach about discipleship?",
      scriptures: [{book:"Luke",ch:1,vs:26,ve:38},{book:"1 Ne",ch:11,vs:13,ve:21},{book:"Mosiah",ch:3,vs:8}],
      nuances: "The Greek 'kecharitomene' in Luke 1:28, translated 'highly favoured,' is a perfect passive participle indicating Mary had already been graced by God — it describes an existing state, not a new event. Her selection was prepared long before the angel appeared.",
      commentary: "Luke's account of the Annunciation reveals Mary as a young woman of extraordinary faith. When Gabriel tells her she will bear the Son of God, her response is not refusal or doubt but a question of logistics — 'How shall this be?' — followed by complete submission: 'Be it unto me according to thy word.' This is one of the great acts of faith in all of scripture.\n\nNephi's vision in 1 Nephi 11 adds a striking detail. When shown the mother of the Son of God, Nephi describes her as 'exceedingly fair and white' — beautiful — and the angel asks if he understands the condescension of God. The answer is given not through theological explanation but through the image of a mortal woman bearing a divine child. The condescension begins with a mother.\n\nMosiah 3:8 names her directly: 'his mother shall be called Mary.' This prophecy, given roughly 124 years before Christ's birth, demonstrates that Mary's role was known and foretold across dispensations. She was not incidental to the plan — she was integral to it.\n\nAcross Christian tradition, Mary has been honored as a model of faithful submission to God's will. Latter-day Saint theology does not venerate her in the manner of Catholic or Orthodox traditions, but it deeply respects her chosen role and her courage in accepting a calling that would bring both joy and a sword through her own soul (Luke 2:35).",
      patterns: "Mary's pattern of faith — receiving a divine commission, asking honest questions, then submitting fully — is the same pattern seen in prophets from Moses to Joseph Smith. God calls, the person questions, and then faith acts.",
      reflection: "Mary said yes to something she could not fully understand. When has God asked you to trust Him before you had all the answers?"
    },
    {
      label: "Joseph, the just guardian",
      focus: "Joseph's quiet faithfulness protected the Christ child and fulfilled prophecy. Today examines the man chosen to be Christ's mortal father figure.",
      scriptures: [{book:"Matt",ch:1,vs:18,ve:25},{book:"Matt",ch:2,vs:13,ve:15},{book:"Luke",ch:2,vs:41,ve:52}],
      nuances: "Matthew 1:19 describes Joseph as 'dikaios' — just or righteous. In Jewish usage, this meant a man who carefully observed the law. Yet Joseph's righteousness led him not to strict legal enforcement (publicly accusing Mary) but to mercy — he planned to put her away 'privily.' His justice was tempered by compassion even before the angel appeared.",
      commentary: "Joseph receives remarkably little dialogue in the Gospels. He never speaks a recorded word. Yet his actions reveal a man of profound character. When confronted with Mary's pregnancy, his first instinct was mercy. When warned in a dream, he immediately obeyed — rising in the night to flee to Egypt. When the danger passed, he returned and settled in Nazareth.\n\nMatthew frames Joseph's actions as fulfillments of prophecy. The flight to Egypt echoes Hosea 11:1 ('Out of Egypt have I called my son'), and the settlement in Nazareth fulfills the prophetic designation of Jesus as a Nazarene. Joseph's obedience was not merely personal faithfulness — it was the mechanism by which ancient prophecy found its fulfillment.\n\nLuke 2:41–52 gives us the only glimpse of Jesus' childhood in the canonical Gospels. Joseph and Mary took Jesus to the temple annually — a sign of devoted religious practice. When the twelve-year-old Jesus remained behind, Joseph and Mary searched for three days. The incident reveals a normal family dynamic: worry, searching, and a gentle rebuke that hints at the tension between Jesus' earthly family and His divine mission.\n\nJoseph likely died before Jesus' public ministry began, as he is absent from every account after the temple visit. His quiet, obedient life provided the shelter within which the Son of God grew to maturity. He is a model of faithfulness without fame.",
      patterns: "Joseph's pattern of receiving divine direction through dreams connects to the broader biblical pattern of God communicating through visions and dreams — from Jacob's ladder to Lehi's tree of life to Joseph Smith's First Vision.",
      reflection: "Joseph served faithfully in a role that brought him no public recognition. Where in your life might God be asking you to serve quietly and faithfully?"
    },
    {
      label: "His brothers and the challenge of familiarity",
      focus: "Jesus' own siblings struggled to believe in Him. What does their doubt — and eventual faith — teach about recognizing divinity in the familiar?",
      scriptures: [{book:"John",ch:7,vs:1,ve:5},{book:"Matt",ch:13,vs:55,ve:56},{book:"Ps",ch:69,vs:8},{book:"Acts",ch:1,vs:14}],
      nuances: "John 7:5 states plainly: 'Neither did his brethren believe in him.' The Greek 'episteuon' is in the imperfect tense, indicating ongoing, habitual unbelief — not a single moment of doubt but a sustained posture of skepticism during His mortal ministry.",
      commentary: "The Gospels record something both human and painful: Jesus' own brothers did not believe in Him during His ministry. John 7:3–5 shows them urging Him to go to Judea and perform miracles publicly — a challenge tinged with sarcasm rather than faith. Matthew 13:55–56 records the people of Nazareth dismissing Him by naming His family: 'Is not this the carpenter's son? Is not his mother called Mary? and his brethren, James, and Joses, and Simon, and Judas?'\n\nPsalm 69:8 is often read as a messianic prophecy of this very experience: 'I am become a stranger unto my brethren, and an alien unto my mother's children.' The pain of being unrecognized by those closest to you is anticipated in the Psalms centuries before it occurred.\n\nBut the story does not end with doubt. Acts 1:14 records that after the Resurrection, Jesus' brothers were among the believers gathered in the upper room. James became a leader of the Jerusalem church and the author of the epistle that bears his name. Jude also wrote a New Testament letter. Their journey from skepticism to devoted discipleship is one of the most compelling evidences for the Resurrection — those who knew Him best in mortality came to know Him as Lord.\n\nThis pattern offers hope. Conversion is not always immediate. The people closest to us may take the longest to see what God is doing in our lives — and we may take the longest to see what He is doing in theirs.",
      patterns: "The pattern of initial rejection followed by later acceptance appears throughout scripture — from Joseph in Egypt (rejected then honored by his brothers) to the Lamanites who eventually accepted the gospel. Proximity does not guarantee recognition.",
      reflection: "Have you ever struggled to recognize God's work in someone you know well? What helped you see more clearly?"
    },
    {
      label: "Christ redefines family",
      focus: "Jesus taught that spiritual kinship transcends biology. Today examines His radical expansion of the concept of family.",
      scriptures: [{book:"Matt",ch:12,vs:46,ve:50},{book:"Mark",ch:3,vs:31,ve:35},{book:"Mosiah",ch:5,vs:7}],
      nuances: "In Matthew 12:49, Jesus 'stretched forth his hand toward his disciples' — the Greek 'ekteinas ten cheira' is a deliberate, visible gesture. He is physically pointing to His followers and declaring them His family. The gesture transforms an abstract teaching into a concrete claim about identity.",
      commentary: "In one of the most striking moments in the Gospels, Jesus is told that His mother and brothers are outside waiting to speak with Him. His response redefines family entirely: 'Who is my mother? and who are my brethren?' Then, gesturing toward His disciples: 'Whosoever shall do the will of my Father which is in heaven, the same is my brother, and sister, and mother.'\n\nThis is not a rejection of Mary or His siblings. It is an expansion of the category. Jesus is teaching that the deepest bonds are covenantal, not merely biological. Those who align their will with the Father's enter a family relationship with the Son that is as real — and in some ways more enduring — than blood ties.\n\nMosiah 5:7 provides the doctrinal framework for this teaching. King Benjamin tells his people that through their covenant, they have become 'the children of Christ, his sons and his daughters.' This is not metaphor. Through the Atonement and the covenant, believers are spiritually begotten — born into a new family with Christ as the father of their salvation.\n\nThis teaching has profound implications for those who feel isolated from their biological families. In Christ's economy, the lonely are adopted, the estranged are welcomed, and the covenant creates bonds that transcend every earthly limitation.",
      patterns: "The redefinition of family through covenant is a thread running from Abraham's covenant (Week 6) through the Atonement (Week 20) to the sealing power (relevant to temple theology). God's family has always been defined by faith and covenant, not biology alone.",
      reflection: "How does belonging to the spiritual family of Christ change the way you view your ward, your community, or people you might otherwise consider strangers?"
    },
    {
      label: "Christ at the cross — family in the hour of death",
      focus: "Even in agony, Jesus cared for His mother. Today studies the tender family moment at the foot of the cross.",
      scriptures: [{book:"John",ch:19,vs:25,ve:27},{book:"Luke",ch:2,vs:34,ve:35},{book:"Alma",ch:7,vs:11,ve:12}],
      nuances: "In John 19:26, Jesus addresses Mary as 'Gunai' — 'Woman' — the same term He used at the wedding in Cana (John 2:4). While it may sound distant in English, in Greek it was a term of respect and tenderness. By entrusting her to the beloved disciple, He was ensuring her care in a culture where a widow without a son's protection was deeply vulnerable.",
      commentary: "John alone records this moment. Jesus, hanging on the cross, looks down and sees His mother standing beside the disciple He loved. In the midst of incomprehensible suffering, He performs an act of familial tenderness: 'Woman, behold thy son!' and to the disciple, 'Behold thy mother!' From that hour, John took Mary into his own home.\n\nThis was more than an arrangement of convenience. Jesus was fulfilling His duty as the eldest son to provide for His mother. With His death imminent and His brothers not yet believers, He entrusted her to the disciple closest to Him. It is a profoundly human moment within the most divine event in history.\n\nSimeon's prophecy in Luke 2:34–35 finds its fulfillment here. He had told Mary that a sword would pierce through her own soul. Standing at the cross, watching her son die, that sword fell. Mary's suffering was not redemptive in the way Christ's was, but it was real and prophesied — a mother's grief that has resonated across two thousand years of Christian devotion.\n\nAlma 7:11–12 reminds us that Christ took upon Himself all human pain, including grief. He understood Mary's anguish because He bore it Himself. The cross was not only a place of atonement — it was a place where family bonds were honored, transferred, and sanctified even in the darkest hour.",
      patterns: "Christ's care for His mother at the cross demonstrates that covenant responsibilities do not cease under trial. This connects to Week 26 (Compassion of) — even in His greatest suffering, He turned outward.",
      reflection: "In your most difficult moments, are you able to think of others' needs? What does Christ's example at the cross teach about love under pressure?"
    },
    {
      label: "Sons and daughters of God through Christ",
      focus: "Through the Atonement, we are adopted into God's family. Today explores the doctrine of spiritual rebirth and divine inheritance.",
      scriptures: [{book:"Gal",ch:4,vs:4,ve:7},{book:"Rom",ch:8,vs:16,ve:17},{book:"Mosiah",ch:15,vs:10,ve:13},{book:"Ether",ch:3,vs:14}],
      nuances: "Paul's word 'huiothesian' in Galatians 4:5 means 'adoption as sons.' In Roman law, an adopted son had the exact same legal rights as a biological son — including full inheritance. Paul is using a legal metaphor his audience would immediately understand: through Christ, Gentile believers receive the same inheritance as natural-born covenant members.",
      commentary: "Galatians 4:4–7 is one of Paul's most powerful theological statements. God sent His Son, born of a woman, born under the law, to redeem those under the law so that we might receive adoption as sons. The result: 'Thou art no more a servant, but a son; and if a son, then an heir of God through Christ.' The progression is breathtaking — from bondage to sonship to inheritance.\n\nRomans 8:16–17 deepens this: the Spirit bears witness that we are children of God, and if children, then heirs — heirs of God and joint-heirs with Christ. The phrase 'joint-heirs' means we inherit not a portion but the same inheritance Christ receives. This is the most expansive promise in all of scripture.\n\nMosiah 15:10–13 offers the Book of Mormon's parallel teaching. Abinadi explains that those who receive the prophets' message and believe in the Lord's redemption — these are Christ's seed. His 'seed' are the spiritually reborn, those whose hearts have been changed through faith and covenant. This passage defines Christ's posterity not biologically but spiritually.\n\nThe brother of Jared's experience in Ether 3:14 adds another dimension. Christ declares, 'I am the Father and the Son' — a statement that Latter-day prophets have explained refers to His role as the Father of salvation for all who come unto Him. He is simultaneously the Son of God and the Father of our spiritual rebirth.",
      patterns: "The doctrine of spiritual adoption connects Abraham's covenant (Week 6), the Atonement (Week 20), and the ordinance of baptism (Week 41). Every covenant is an adoption into the family of Christ.",
      reflection: "Do you live as though you are an heir of God? How would your daily decisions change if you truly believed in your divine inheritance?"
    },
    {
      label: "The eternal family of Christ",
      focus: "Christ's ultimate purpose is to bring all of God's children home. Today synthesizes the mortal and the eternal dimensions of His family.",
      scriptures: [{book:"D&C",ch:25,vs:1},{book:"D&C",ch:93,vs:21,ve:22},{book:"John",ch:14,vs:2,ve:3},{book:"Moro",ch:7,vs:19}],
      nuances: "In D&C 25:1, Emma Smith is addressed as 'my daughter' by the Lord — a direct, personal claim of spiritual parentage. The Hebrew and Greek traditions both use familial language for covenant relationships, but Restoration scripture makes this personal and direct in a way that is distinctive.",
      commentary: "D&C 25:1 reveals something tender: the Lord addresses Emma Smith as 'my daughter.' This is not a general theological category — it is a personal address from the Savior to a specific woman. It demonstrates that Christ's family is not an abstraction but a reality composed of individual relationships.\n\nD&C 93:21–22 teaches that all who are begotten through Christ 'are the church of the Firstborn.' This is the ultimate family — those who through faithfulness receive all that the Father has. The 'church of the Firstborn' is not a separate organization but a description of those who achieve the highest degree of celestial glory and become part of Christ's eternal family in the fullest sense.\n\nJohn 14:2–3 provides the Savior's own promise: 'In my Father's house are many mansions... I go to prepare a place for you.' The image is familial — a father's house with room for all His children. Christ's work, from His mortal ministry to His postmortal labors, is fundamentally about gathering a family.\n\nMoroni 7:19 invites us to 'lay hold upon every good thing' — a reminder that belonging to Christ's family is not passive. We participate in our own adoption through faith, repentance, covenant, and continued discipleship. The family of Christ is entered by choice and sustained by faithfulness.",
      patterns: "This week's arc — from mortal family to spiritual family to eternal family — mirrors the plan of salvation itself: a premortal family, a mortal experience, and an eternal reunion. Christ is the connecting thread at every stage.",
      reflection: "If Christ personally addressed you as 'my son' or 'my daughter,' how would that change your sense of identity and worth? What prevents you from believing He already does?"
    }
  ]
};

export default week38;
