import type { WeekContent } from '../types';

const week14: WeekContent = {
  title: "Redeemer & Savior — Bought with a Price",
  subtitle: "Christ is not merely a teacher or moral guide; He is the one who paid the price to reclaim us from sin and death.",
  weekScriptures: "Isa 44:6; Isa 44:22–24; Job 19:25–27; Ps 130:7–8; Isa 53:4–7; 1 Pet 1:18–20; Gal 3:13; Rev 5:9–10; 2 Ne 2:6–8; Alma 34:8–14; Mosiah 15:1–9; Hel 5:9–12; D&C 18:10–12; D&C 76:40–42; Moses 1:39; Luke 2:11; John 3:16–17; Titus 2:13–14; 1 Jn 4:14; Acts 5:30–31",
  synthesis: {
    summary: "The titles Redeemer and Savior are not interchangeable synonyms but complementary descriptions of what Christ does. To redeem is to buy back, to pay a price to reclaim something lost. To save is to deliver from destruction. Together they describe a God who entered mortality, paid an infinite cost, and rescued the entire human family from both physical and spiritual death. Every prophet in every age has testified that this redemption was planned before the world was and that no one else could accomplish it.",
    connections: [
      "The Redeemer's work is inseparable from the Atonement explored in Weeks 12 and 13 — those weeks focus on the suffering; this week focuses on what it purchased.",
      "Christ as Deliverer (Week 15) builds directly on this foundation — redemption is the price, deliverance is the experience.",
      "The power of Christ (Week 16) is the force by which redemption becomes operative in individual lives."
    ],
    teaching: "What is the difference between being 'saved' and being 'redeemed'? Why does scripture use both terms, and what does each add to your understanding of what Christ did?",
    commitment: "Identify one area in your life where you need to rely more fully on Christ's redeeming power this week. What would it look like to let Him reclaim that part of your life?"
  },
  days: [
    {
      label: "The Redeemer of Israel",
      focus: "Before the mortal ministry of Jesus, Israel already knew their God as Redeemer. Today we explore the Old Testament roots of this title and what it reveals about God's character.",
      scriptures: [{book:"Isa",ch:44,vs:6},{book:"Isa",ch:44,vs:22,ve:24},{book:"Job",ch:19,vs:25,ve:27}],
      nuances: "The Hebrew word 'go'el' (redeemer) carried deeply personal legal meaning in ancient Israel. A go'el was a kinsman-redeemer — a close family member obligated by law to buy back a relative's lost property, pay their debts, or avenge their blood. When Isaiah calls Jehovah the Redeemer, he is invoking this kinship framework: God is not a distant judge but a close relative who takes personal responsibility for our losses.",
      commentary: "Isaiah 44 presents a God who simultaneously declares His cosmic supremacy ('I am the first, and I am the last; and beside me there is no God') and His intimate commitment to His people ('I have blotted out, as a thick cloud, thy transgressions'). The juxtaposition is deliberate. The God who made the heavens is the same God who erases your sins.\n\nJob's declaration in Job 19:25-27 is one of the most striking in all scripture: 'I know that my redeemer liveth.' Job speaks from the depths of unimaginable suffering — loss of children, wealth, health, and the understanding of his friends. Yet he does not say 'I hope' or 'I believe'; he says 'I know.' And his knowledge is not abstract theology but personal expectation: he will see God in his own flesh.\n\nThe Restoration adds texture to Job's declaration. Latter-day Saints understand that Job's confidence in seeing God 'in my flesh' was not metaphor but prophecy — the resurrection is literal, physical, and personal. Christ as Redeemer is not merely a title; it is a job description. He pays the price. He reclaims what was lost. He restores what was broken.",
      patterns: "The kinsman-redeemer pattern appears across scripture: Boaz redeems Ruth, Jehovah redeems Israel, Christ redeems all humanity. Each iteration expands the scope but preserves the principle — redemption requires a personal relationship and a personal cost.",
      reflection: "Job declared 'I know that my redeemer liveth' in his darkest hour. What sustains your knowledge of Christ when circumstances challenge your faith?"
    },
    {
      label: "The price of redemption",
      focus: "Redemption is not free — someone pays. Today examines the specific cost Christ bore and why no lesser payment would suffice.",
      scriptures: [{book:"Isa",ch:53,vs:4,ve:7},{book:"1 Pet",ch:1,vs:18,ve:20},{book:"Gal",ch:3,vs:13}],
      nuances: "Peter's phrase 'not redeemed with corruptible things, as silver and gold' (1 Peter 1:18) deliberately contrasts two kinds of ransom. In the Roman world, slaves could be purchased and freed — redeemed — with money. Peter says Christ's redemption operates on a fundamentally different currency: 'the precious blood of Christ, as of a lamb without blemish.' The adjective 'precious' (Greek 'timios') denotes something of supreme value, the highest possible price.",
      commentary: "Isaiah 53 is the great prophetic portrait of the suffering Redeemer. He was wounded for our transgressions, bruised for our iniquities. The language is substitutionary — He bears what we deserved. This chapter was so central to early Christian proclamation that Philip used it to teach the Ethiopian eunuch about Christ (Acts 8:32-35).\n\nPeter, writing to scattered Christians under persecution, grounds their hope not in their own endurance but in the price already paid. They were redeemed not with perishable currency but with the blood of Christ, foreordained before the foundation of the world. This last detail is critical: redemption was not an afterthought or a backup plan. It was the plan from the beginning.\n\nPaul adds in Galatians 3:13 that Christ 'hath redeemed us from the curse of the law, being made a curse for us.' The theological weight here is enormous. Christ did not merely pay a fine; He absorbed the curse. He took upon Himself the full consequence of human failure under divine law. This is why Alma 34 will insist (later this week) that the Atonement must be infinite — no finite payment could absorb an infinite debt.",
      patterns: "The pattern of substitutionary payment runs from the Passover lamb (Exodus 12) through the temple sacrifices to the cross. Each sacrifice pointed forward to the one sacrifice that would actually accomplish what all the types only symbolized.",
      reflection: "Peter says you were redeemed with 'the precious blood of Christ.' How does understanding the cost of your redemption affect how you value your own life and choices?"
    },
    {
      label: "A new song of redemption",
      focus: "The redeemed respond with worship. Today explores redemption as the foundation of praise and the source of a new identity.",
      scriptures: [{book:"Rev",ch:5,vs:9,ve:10},{book:"Ps",ch:130,vs:7,ve:8},{book:"Luke",ch:2,vs:11}],
      nuances: "In Revelation 5:9, the 'new song' (Greek 'oden kainen') is significant. In the Psalms, a new song typically celebrates a new act of divine deliverance (Psalm 33:3, 96:1, 144:9). The heavenly song in Revelation celebrates the ultimate new act: the Lamb who was slain has redeemed people 'out of every kindred, and tongue, and people, and nation.' The scope is universal — not one tribe or nation, but the entire human family.",
      commentary: "Revelation 5 presents a scene of cosmic worship. No one in heaven or earth is found worthy to open the sealed book — except the Lamb who was slain. His worthiness is grounded in His redemptive act: 'Thou wast slain, and hast redeemed us to God by thy blood.' The redeemed do not merely receive a pardon; they receive a new identity — they are made 'kings and priests unto our God.'\n\nPsalm 130 captures the Israelite experience of waiting for redemption. 'Let Israel hope in the Lord: for with the Lord there is mercy, and with him is plenteous redemption.' The psalm moves from the depths of despair ('Out of the depths have I cried') to confident hope. Redemption is what makes that journey possible.\n\nThe angel's announcement to the shepherds in Luke 2:11 ties it together: 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.' The titles stack: Savior, Christ (Anointed One), Lord (Kurios — the divine name). From the moment of His birth, the Redeemer's identity and mission were declared.",
      patterns: "The pattern of a 'new song' appears whenever God performs a decisive act of salvation. Israel sang at the Red Sea (Exodus 15), the Psalmist sang of deliverance, and the redeemed sing before the throne. Redemption always produces worship.",
      reflection: "If redemption produces a 'new song,' what would your song of gratitude to Christ sound like? What has He redeemed you from?"
    },
    {
      label: "The infinite Atonement as redemption",
      focus: "The Book of Mormon's most direct teaching on why redemption requires an infinite sacrifice. Today examines the theological logic of the Atonement as payment.",
      scriptures: [{book:"2 Ne",ch:2,vs:6,ve:8},{book:"Alma",ch:34,vs:8,ve:14},{book:"Mosiah",ch:15,vs:1,ve:9}],
      nuances: "Amulek's phrase 'infinite and eternal sacrifice' in Alma 34:10 is carefully constructed. 'Infinite' means without boundary — the sacrifice cannot be limited in scope, duration, or effect. 'Eternal' connects to the name of God Himself (D&C 19:10-12 reveals that 'Eternal' is one of God's names). An eternal sacrifice is literally a God-quality sacrifice — only a being of infinite worth could pay an infinite debt.",
      commentary: "Lehi's teaching in 2 Nephi 2:6-8 establishes the necessity of redemption within the framework of the plan of salvation. Because of the Fall, all humanity is 'cut off from the presence of the Lord.' Redemption is the only way back, and it comes through 'the merits, and mercy, and grace of the Holy Messiah.' Note the sequence: merits (what Christ earned through His perfect life), mercy (His willingness to forgive), and grace (His power to transform).\n\nAmulek in Alma 34 provides the most detailed explanation in all of scripture for why the Atonement must be infinite. A human sacrifice would only be 'a man for a man' — it could not transcend the individual. Animal sacrifices were types and shadows that pointed to the real offering but could not themselves redeem. Only an infinite sacrifice — one performed by a being of infinite worth — could satisfy the demands of justice for the entire human family across all of time.\n\nMosiah 15:1-9 adds the doctrinal key that makes this possible: Jesus Christ is both the Father and the Son — divine and mortal, God and man. Because He has the power of the Father (divine, infinite, eternal) and the experience of the Son (mortal, suffering, dying), He alone bridges the gap between justice and mercy. Abinadi taught this while standing trial for his life, making it one of the most courageous theological declarations in scripture.",
      patterns: "The Book of Mormon repeatedly provides the doctrinal explanation for what the Bible affirms as fact. The Bible declares that Christ redeemed us; the Book of Mormon explains why only He could. This complementary witness pattern is central to Restoration scripture study.",
      reflection: "Amulek teaches that without the infinite Atonement, 'this corruption could not put on incorruption.' What aspects of your mortal experience most make you grateful for an infinite, not limited, redemption?"
    },
    {
      label: "The Savior who remembers",
      focus: "Christ does not redeem from a distance. Today explores the deeply personal nature of His saving work — He knows you individually.",
      scriptures: [{book:"Hel",ch:5,vs:9,ve:12},{book:"D&C",ch:18,vs:10,ve:12},{book:"John",ch:3,vs:16,ve:17}],
      nuances: "In D&C 18:10, the phrase 'the worth of souls is great in the sight of God' uses 'souls' (not 'humanity' or 'mankind'). The emphasis is individual. The following verses clarify that Christ suffered and died 'for all, that all might repent and come unto him.' The universal scope ('all') and the personal invitation ('come unto him') are held together — no one is excluded, and no one is merely part of a crowd.",
      commentary: "Helaman 5:9-12 records the counsel of Helaman to his sons Nephi and Lehi, reminding them that 'there is no other way nor means whereby man can be saved, only through the atoning blood of Jesus Christ.' He then gives them the great metaphor: build your foundation upon the rock of the Redeemer, 'which is a sure foundation, a foundation whereon if men build they cannot fall.' The Redeemer is not only the one who pays the price but the one who provides the stability to move forward.\n\nD&C 18:10-12 reveals the emotional dimension of Christ's redemptive work. He suffered for all so that all might repent. The logic is not transactional but relational — His suffering was motivated by how much each soul is worth to Him. This passage has become one of the most quoted in the Restoration, and for good reason: it anchors the worth of every human being in the price the Savior was willing to pay.\n\nJohn 3:16-17 is perhaps the most famous verse in all of Christianity: 'For God so loved the world, that he gave his only begotten Son.' The motivation for redemption is love — not obligation, not cosmic necessity, but love. And verse 17 adds an often-overlooked clarification: God sent His Son 'not to condemn the world; but that the world through him might be saved.' The Savior came to save, not to condemn. His posture toward you is rescue, not judgment.",
      patterns: "The personal nature of Christ's redemption connects to His role as the Good Shepherd (Week 21), who knows each sheep by name. Redemption is cosmic in scope but intimate in application — this tension runs throughout scripture.",
      reflection: "D&C 18:11 says Christ 'suffered the pain of all men.' How does it change your relationship with Christ to know that He experienced your specific pain, not just pain in general?"
    },
    {
      label: "Savior of body and spirit",
      focus: "Christ saves the whole person — not just the soul, but the body. Today explores the fulness of salvation through both resurrection and forgiveness.",
      scriptures: [{book:"D&C",ch:76,vs:40,ve:42},{book:"Acts",ch:5,vs:30,ve:31},{book:"Titus",ch:2,vs:13,ve:14}],
      nuances: "In Acts 5:31, the Greek 'archegos kai soter' is translated 'a Prince and a Saviour.' The word 'archegos' means originator, pioneer, or author — the one who goes first and opens the way. It is the same word used in Hebrews 2:10 ('the captain of their salvation') and Hebrews 12:2 ('the author and finisher of our faith'). Christ is not merely a rescuer who pulls us from danger; He is the pioneer who walked the path first and now leads us through.",
      commentary: "D&C 76:40-42 provides one of the clearest statements of the gospel in all of scripture. The gospel is that Christ 'came into the world to be crucified for the world, and to bear the sins of the world, and to sanctify the world, and to cleanse it from all unrighteousness.' It then declares that 'through him all might be saved.' This is not selective salvation for the few but universal opportunity.\n\nPeter's declaration in Acts 5:30-31 was delivered to the same Sanhedrin that had orchestrated Christ's crucifixion. His courage is remarkable. He calls Jesus both Prince and Savior, raised by the same God whose servants the Sanhedrin claimed to be. Christ was exalted 'to give repentance to Israel, and forgiveness of sins.' Repentance is presented not as a burden but as a gift — something the Savior gives.\n\nPaul's letter to Titus describes Christ as the one 'who gave himself for us, that he might redeem us from all iniquity, and purify unto himself a peculiar people, zealous of good works.' The purpose of redemption is not merely escape from punishment but transformation of character. Christ redeems us from sin and refashions us into something new. Salvation is not just a legal transaction; it is a complete renovation of the person — body and spirit, here and hereafter.",
      patterns: "The dual nature of salvation — from physical death through resurrection and from spiritual death through forgiveness — is a distinctive emphasis of Restoration theology. D&C 76 and 88 develop this more fully than perhaps any other scriptural texts. This connects forward to Week 36 (Resurrection).",
      reflection: "Christ saves both body and spirit. How does the promise of physical resurrection shape your relationship with your own body and its limitations?"
    },
    {
      label: "Waiting for the Savior",
      focus: "The titles Redeemer and Savior point not only backward to what Christ did but forward to what He will yet do. Today explores the hope of His return.",
      scriptures: [{book:"1 Jn",ch:4,vs:14},{book:"Moses",ch:1,vs:39},{book:"D&C",ch:76,vs:40,ve:42}],
      nuances: "In 1 John 4:14, 'the Father sent the Son to be the Saviour of the world' uses the Greek perfect tense for 'sent' (apestalken), indicating a completed action with ongoing results. The sending was a historical event, but its effects continue. Christ's saving mission did not end at the cross or the empty tomb — it continues now and will culminate at His return.",
      commentary: "John the Beloved writes as an eyewitness: 'We have seen and do testify that the Father sent the Son to be the Saviour of the world.' His testimony is personal ('we have seen'), universal ('the world'), and Christological ('the Father sent the Son'). The entire gospel is compressed into one verse.\n\nMoses 1:39 reveals the divine motive behind all of God's work: 'This is my work and my glory — to bring to pass the immortality and eternal life of man.' The Savior's redemptive mission is not a secondary project or an emergency response — it is the central purpose of God's existence as it relates to us. Everything else — creation, law, prophecy, ordinances — serves this aim.\n\nD&C 76:40-42, revisited from yesterday, gains additional depth when read as a forward-looking declaration. Christ came, bore sins, and sanctified the world — and through Him all 'might be saved.' The word 'might' preserves agency. Redemption is accomplished; salvation is offered; but the individual must choose to receive it. The Redeemer has paid the price, but the redeemed must accept the gift.\n\nThe week closes where it began: with the certainty that Christ lives, that He redeems, and that His saving work continues until every knee bows and every tongue confesses. The Redeemer of Israel is also the Redeemer of each individual soul who turns to Him.",
      patterns: "The forward-looking dimension of redemption connects to Weeks 42-44 (Second Coming, Millennial Reign, and Final Judgment). The Savior who redeemed us in Gethsemane and on Calvary is the same Savior who will return in glory to complete His work.",
      reflection: "Moses 1:39 says God's entire work and glory is your immortality and eternal life. How does that change how you see your own story — not as incidental, but as central to God's purpose?"
    }
  ]
};

export default week14;
