import type { WeekContent } from '../types';

const week32: WeekContent = {
  title: "Divine Sonship — The Only Begotten of the Father",
  subtitle: "Christ's sonship is not honorary or adoptive — it is literal, unique, and the foundation of His saving power.",
  weekScriptures: "Matt 16:16; Mark 1:1; John 10:36; John 20:31; Acts 9:20; Rom 1:3-4; Gal 4:4; Heb 4:14; 1 Jn 5:5; 2 Ne 25:19; Mosiah 3:8; D&C 68:6",
  synthesis: {
    summary: "This week explores the doctrine that Jesus Christ is literally the Son of God — the Only Begotten of the Father in the flesh. His divine sonship is not metaphorical but the actual basis of His power to atone, to create, and to redeem. Every dispensation has proclaimed this truth, from the Psalms to the Restoration. Understanding Christ's unique relationship to the Father transforms how we understand His mission, His authority, and our own potential as children of God.",
    connections: [
      "Christ's divine sonship is what makes His Atonement infinite — a merely human sacrifice could not have redeemed all humanity.",
      "The doctrine of divine sonship connects directly to Week 33's study of Christ's relationship with the Father and to Week 1's foundational overview of His identity.",
      "Understanding Christ as the literal Son of God illuminates Week 12's study of the Atonement — His divine nature gave Him power over death itself."
    ],
    teaching: "Why does it matter doctrinally that Christ is literally the Son of God, rather than a great teacher adopted into a divine role? How does His sonship affect the power of His Atonement?",
    commitment: "This week, each time you pray to the Father 'in the name of Jesus Christ,' pause and consider what it means that you are invoking the name of the Father's Only Begotten Son."
  },
  days: [
    {
      label: "The Only Begotten",
      focus: "The title 'Only Begotten' is not casual. Today examines what this specific designation means and why scripture insists on it so emphatically.",
      scriptures: [{book:"John",ch:3,vs:16,ve:17},{book:"1 Jn",ch:4,vs:9,ve:10},{book:"Jacob",ch:4,vs:5}],
      nuances: "The Greek 'monogenēs' (translated 'only begotten' in John 3:16) combines 'monos' (only, unique) and 'genos' (kind, offspring). Scholars debate whether it means 'only born' or 'one of a kind,' but both senses converge on the same doctrinal point: Christ's relationship to the Father is singular and unrepeatable. No other being holds this title.",
      commentary: "John 3:16 is perhaps the most memorized verse in all of scripture, yet its core claim is often glossed over. God gave His Only Begotten Son. The emphasis is not merely on the giving but on who was given — not an angel, not a prophet, not a symbolic figure, but the Father's unique, literal Son.\n\n1 John 4:9–10 deepens this by framing the sending of the Only Begotten as the definitive act of divine love. Love is not an abstraction in scripture — it is measured by what was sacrificed. The Father gave the most precious being in existence.\n\nJacob 4:5 adds a striking Nephite dimension: Abraham's willingness to offer Isaac was a 'similitude of God and his Only Begotten Son.' The binding of Isaac, one of the most harrowing narratives in the Old Testament, was itself a prophetic type of the Father offering Christ. The parallel is not incidental — it is doctrinal. When Abraham lifted the knife, he was enacting in shadow what the Father would enact in full.\n\nThe insistence on 'Only Begotten' across multiple dispensations marks this as a doctrine of the highest order. Christ's sonship is not one teaching among many — it is the teaching upon which all others depend.",
      patterns: "The title 'Only Begotten' appears in both Testaments and in Restoration scripture, always with the same doctrinal weight. When a title persists unchanged across dispensations, it signals an unchangeable truth about Christ's nature.",
      reflection: "When you hear 'God so loved the world,' do you tend to focus on the love or on the cost? How does understanding the uniqueness of the Son deepen your sense of what the Father sacrificed?"
    },
    {
      label: "Declared by the Father",
      focus: "The Father Himself testified of the Son's divine identity. Today examines the moments when heaven opened and the Father's voice was heard.",
      scriptures: [{book:"Matt",ch:3,vs:17},{book:"Ps",ch:2,vs:7},{book:"3 Ne",ch:11,vs:7}],
      nuances: "In Matthew 3:17, the Father's declaration 'This is my beloved Son' uses the Greek 'agapētos' for 'beloved' — the same word used in the Septuagint for Isaac in Genesis 22:2, the son of Abraham who was to be offered as a sacrifice. The verbal echo connects Christ's baptism to His eventual sacrifice.",
      commentary: "At Christ's baptism, the Father spoke audibly: 'This is my beloved Son, in whom I am well pleased.' This was not a private experience — it was a public, divine attestation of sonship. The heavens opened, the Spirit descended, and the Father bore witness. The moment marks the formal beginning of Christ's mortal ministry, and the Father chose to inaugurate it with an unmistakable declaration of paternity.\n\nPsalm 2:7 records what many scholars recognize as a royal enthronement psalm, but with messianic depth: 'Thou art my Son; this day have I begotten thee.' The writer of Hebrews later applies this directly to Christ (Hebrews 1:5), reading the psalm not merely as ancient Israelite coronation poetry but as a divine decree about the Messiah.\n\n3 Nephi 11:7 records the same declaration in the New World. When the Father introduced the risen Christ to the Nephites, He used nearly identical language: 'Behold my Beloved Son, in whom I am well pleased.' The consistency is remarkable — the same words, the same relationship, the same witness, separated by an ocean and a hemisphere. The Father does not change His testimony about His Son.",
      patterns: "The Father's vocal testimony of the Son occurs at the baptism, the Mount of Transfiguration, and in 3 Nephi. In the First Vision (JS—H 1:17), the pattern continues into the modern dispensation. Every time the Father introduces the Son, He does so as a parent presenting His child.",
      reflection: "Have you ever considered that the Father's declaration at the baptism was as much for Christ (affirming Him before His ministry) as it was for those listening? What does it mean that God publicly claimed His Son?"
    },
    {
      label: "Son in the flesh",
      focus: "Christ's divine sonship extends to His mortal birth. Today examines the doctrine that He was the Son of God not only in spirit but in the flesh.",
      scriptures: [{book:"Luke",ch:1,vs:35},{book:"Alma",ch:7,vs:10},{book:"Mosiah",ch:15,vs:1,ve:4}],
      nuances: "In Luke 1:35, the angel tells Mary that 'the Holy Ghost shall come upon thee, and the power of the Highest shall overshadow thee.' The Greek 'episkiasei' (overshadow) is the same word used for the divine cloud that covered the tabernacle in Exodus 40:35 (Septuagint). Luke is deliberately echoing the Old Testament to convey that the same divine presence that filled the tabernacle would now bring forth the Son of God.",
      commentary: "Luke's account of the Annunciation establishes that Christ's conception was divine. Mary was told plainly: the child would be called the Son of the Highest, and the Son of God. This was not an honorary title conferred later — it described His nature from the moment of conception.\n\nAlma 7:10, spoken over a century before the event, prophesied that the Son of God would be born of Mary at Jerusalem. The specificity is notable: Alma names both the mother and the region. Book of Mormon prophets understood Christ's mortal birth as an essential part of the divine plan, not merely an incidental detail.\n\nMosiah 15:1–4 offers one of the most theologically dense passages in all Restoration scripture. Abinadi teaches that Christ is both the Father and the Son — the Father because of His divine conception and power, and the Son because of His mortal flesh. This is not a contradiction but a description of Christ's dual nature: fully divine, fully mortal, united in one person. The passage parallels the Christological debates of the early Christian centuries, where councils wrestled with how divinity and humanity could coexist in one being. Abinadi's teaching is remarkably precise and deserves slow, careful reading.",
      patterns: "The doctrine of Christ's divine-mortal dual nature is taught by Abinadi, by Luke, and is implicit throughout John's Gospel. This connects forward to Week 33's exploration of how Christ relates to the Father — His sonship is the foundation of that relationship.",
      reflection: "Mosiah 15:1–4 can be confusing on first reading. What does it mean to you that Christ carried both divine power and mortal vulnerability in the same person?"
    },
    {
      label: "Heir of all things",
      focus: "Sonship implies inheritance. Today examines the doctrine that Christ, as the Son, is the rightful heir of all the Father has.",
      scriptures: [{book:"Heb",ch:1,vs:1,ve:5},{book:"D&C",ch:93,vs:21,ve:23},{book:"John",ch:5,vs:19,ve:23}],
      nuances: "Hebrews 1:2 describes Christ as 'heir of all things' — the Greek 'klēronomon pantōn' carries legal force. In the Roman world, an heir did not merely receive property; he assumed the full identity and authority of the father. To be heir of all things is to possess all that the Father possesses.",
      commentary: "The opening of Hebrews is one of the most exalted Christological statements in the New Testament. Christ is described as the brightness of the Father's glory, the express image of His person, the one who upholds all things by the word of His power. And He is called the heir of all things — meaning that everything the Father has belongs to the Son by right of sonship.\n\nD&C 93:21–23 extends this into Restoration theology with a striking declaration: Christ was in the beginning with the Father, and received a fulness of truth and glory. Verse 23 then turns the doctrine toward us: 'Ye were also in the beginning with the Father.' The implication is breathtaking — our own divine potential is patterned after Christ's sonship. He is the Firstborn, and we are invited to become joint-heirs with Him (Romans 8:17).\n\nJohn 5:19–23 reveals the intimacy of the Father-Son relationship. The Son does nothing independently — He does what He sees the Father do. This is not limitation but perfect unity. The Father has committed all judgment to the Son, and all should honor the Son even as they honor the Father. Sonship here is not subordination — it is full participation in divine authority.\n\nThe doctrine of inheritance matters because it gives Christ's work its ultimate context. He does not atone as a servant performing a task but as a Son fulfilling His Father's deepest purposes.",
      patterns: "The concept of Christ as heir connects to the broader scriptural theme of covenant inheritance — from Abraham's promises to the sealing ordinances of the temple. What Christ inherits from the Father, He offers to share with those who enter His covenant.",
      reflection: "Romans 8:17 says we can become 'joint-heirs with Christ.' What does it mean to you that Christ's inheritance is something He desires to share rather than keep for Himself?"
    },
    {
      label: "The premortal Son",
      focus: "Christ's sonship did not begin at Bethlehem. Today explores His identity as the Firstborn in the premortal realm and His role in the great council.",
      scriptures: [{book:"Abr",ch:3,vs:27},{book:"Moses",ch:4,vs:2},{book:"D&C",ch:93,vs:21,ve:22}],
      nuances: "In Abraham 3:27, when the Father asks 'Whom shall I send?' the response 'Here am I, send me' echoes Isaiah 6:8 — but in Abraham's account, it is the Son who speaks these words in the premortal council. The Restoration places Christ's willingness to serve not at the beginning of His mortal life but before the foundation of the world.",
      commentary: "Abraham 3:27 and Moses 4:2 together provide a window into the premortal council. The Father presented the plan, and two figures responded. Christ said, 'Father, thy will be done, and the glory be thine forever.' Lucifer said, 'Send me... and I will redeem all... and surely I will do it; wherefore give me thine honor.' The contrast is absolute: the Son sought the Father's glory; the adversary sought his own.\n\nThis premortal choice reveals the character of Christ's sonship. He was not drafted or compelled — He volunteered. And His volunteering was not self-serving but self-giving. The same disposition that led Him to say 'thy will be done' in the council led Him to say the same words in Gethsemane (Luke 22:42). His character is consistent across eternity.\n\nD&C 93:21–22 affirms that Christ was in the beginning with the Father and was the Firstborn. This title — Firstborn — is not merely chronological but covenantal. In ancient Israelite law, the firstborn received a double portion and carried the family's priestly responsibilities. Christ as the Firstborn carries the full weight of the Father's redemptive purposes.\n\nThe premortal sonship of Christ is a distinctive contribution of Restoration theology. While many Christian traditions affirm Christ's preexistence (drawing on John 1:1 and Colossians 1:15), the detailed narrative of a premortal council and Christ's voluntary acceptance of His mission is unique to Latter-day Saint scripture.",
      patterns: "Christ's premortal 'thy will be done' anticipates Gethsemane. The pattern of submission to the Father's will is not something He learned in mortality — it is who He has always been. This connects to Week 33's study of His relationship with the Father.",
      reflection: "Christ volunteered for the most difficult mission in existence, and His motive was love for the Father and for you. How does knowing His choice was voluntary change how you receive His sacrifice?"
    },
    {
      label: "Son and Redeemer",
      focus: "Christ's sonship is not just a title — it is the source of His redemptive power. Today examines how His divine parentage made the Atonement possible.",
      scriptures: [{book:"Alma",ch:5,vs:48},{book:"Morm",ch:9,vs:12},{book:"2 Ne",ch:25,vs:12}],
      nuances: "In Alma 5:48, Alma testifies that Christ is 'the Son of the living God.' The phrase 'living God' (Hebrew 'El Chai') distinguishes the true God from dead idols. Alma's declaration that Christ is the Son of the living God echoes Peter's confession in Matthew 16:16 — a remarkable parallel between a Nephite prophet and a Galilean apostle, both arriving at the same testimony.",
      commentary: "Alma 5:48 is one of the most powerful personal testimonies in the Book of Mormon. Alma declares that he knows these things not by hearsay but by revelation — the Holy Spirit of God has made them known to him. His testimony that Christ is the Son of God, who will come to redeem His people, connects sonship directly to redemption. These are not separate doctrines; they are one doctrine.\n\nMormon 9:12 makes the logic explicit: because of the fall of Adam, the Atonement was necessary, and because Christ is the Son of God, the Atonement was possible. A merely human savior could not have satisfied the demands of justice for all humanity across all time. The infinite scope of the Atonement required a being of infinite capacity — and that capacity came from His divine parentage.\n\n2 Nephi 25:12 ties the prophecy together: the Only Begotten of the Father would manifest Himself in the flesh to those who believe. Nephi's entire prophetic framework is built on the premise that the Redeemer is the Son of God. Remove the sonship, and the redemption collapses.\n\nThis is why the doctrine of divine sonship is not academic theology — it is existentially urgent. If Christ is not who He claims to be, there is no Atonement, no resurrection, no hope. But if He is the Son of God, then everything He promised is sure.",
      patterns: "Across the Book of Mormon, the connection between Christ's identity as Son of God and His power to redeem is made repeatedly — by Nephi, Abinadi, Alma, and Mormon. The prophets never separate who He is from what He can do.",
      reflection: "How does understanding Christ's divine sonship as the source of His atoning power affect the way you approach Him in prayer when you need forgiveness or help?"
    },
    {
      label: "What sonship means for us",
      focus: "Christ's divine sonship opens a path for our own divine potential. Today explores how His relationship to the Father patterns what is offered to us.",
      scriptures: [{book:"John",ch:1,vs:14},{book:"D&C",ch:93,vs:21,ve:23},{book:"Moro",ch:7,vs:48}],
      nuances: "John 1:14 says we 'beheld his glory, the glory as of the only begotten of the Father, full of grace and truth.' The word 'beheld' (Greek 'etheasametha') implies prolonged, attentive contemplation — not a passing glance. John is saying they gazed at Christ's glory with sustained attention, and what they saw was the glory of sonship.",
      commentary: "John 1:14 describes the glory of the Only Begotten — full of grace and truth. This glory is not hidden but revealed to those who are willing to look. The disciples beheld it during their years with Him, and John invites every reader to behold it through scripture and the Spirit.\n\nD&C 93:21–23 then makes an astonishing turn. After affirming Christ's premortal glory and His reception of a fulness, verse 23 declares: 'Ye were also in the beginning with the Father.' We too are children of God, and Christ's sonship is the pattern for our own divine potential. He received grace for grace until He received a fulness (D&C 93:12–13), and we are invited to follow the same path.\n\nMoroni 7:48 brings this to its devotional climax: we should pray with all the energy of heart that we may be filled with the love that the Father has bestowed upon all true followers of His Son, that we may become the sons of God, and that when He appears we shall be like Him. The goal of the gospel is not merely to admire Christ's sonship from a distance but to be transformed by it — to become, in a derivative but real sense, what He is.\n\nThis is the ultimate implication of divine sonship: Christ is not merely the object of worship but the pattern of our becoming. His relationship with the Father is the prototype of the relationship God offers to every soul who will receive it.",
      patterns: "The trajectory from Christ's sonship to our potential as children of God runs through the entire plan of salvation. This connects to Week 36's study of taking upon us the name of Christ — covenant identity as children of God.",
      reflection: "Moroni invites us to pray that we may become 'sons of God' and be 'like Him' when He appears. What would it look like to take that prayer seriously this week?"
    }
  ]
};

export default week32;
