import type { WeekContent } from '../types';

const week24: WeekContent = {
  title: "Testimony of — Bearing Witness of Christ",
  subtitle: "Every dispensation is built on personal witnesses of Jesus Christ, and every disciple is invited to become one.",
  weekScriptures: "John 15:26–27; Acts 1:8; 1 Cor. 12:3; D&C 46:13–14; Moro. 10:4–5; Rev. 19:10; 2 Ne. 33:10–11; Mosiah 18:8–10; Alma 5:45–46; D&C 76:22–24; JS-H 1:25; 1 Jn. 5:9–12; John 21:24; 3 Ne. 11:14–17; D&C 62:3; Acts 4:18–20; Alma 36:26; 2 Tim. 1:7–8; Ether 12:38–41",
  synthesis: {
    summary: "Testimony of Jesus Christ is not a genre of religious speech — it is the animating power of the gospel. The Spirit of prophecy is the testimony of Jesus. Every true prophet, from Adam to the living prophet today, is fundamentally a witness of Christ. Testimony is born by the Holy Ghost, nurtured through faithfulness, and carried by individuals who are willing to share what they have experienced. This week explores where testimony comes from, how it grows, and why bearing it is both privilege and commandment.",
    connections: [
      "The role of the Holy Ghost in testimony connects directly to Week 1 (Overview, Day 5) and Week 34 (Spirit of Jesus Christ), where the Spirit's witness is examined in depth.",
      "The prophetic witness of Christ studied here extends the pattern from Week 1 (Day 3) that all prophets testified of Him — this week focuses on how ordinary disciples join that witness.",
      "The baptismal covenant to 'stand as witnesses of God' (Mosiah 18:9) connects to Week 21 (Baptism of) and the covenantal nature of testimony."
    ],
    teaching: "What is the difference between believing something is true and bearing testimony that it is true? Why does the Lord command His disciples not just to believe in Christ but to actively testify of Him?",
    commitment: "Bear your testimony of Jesus Christ to someone this week — not in a formal setting but in a natural conversation. It does not need to be long or eloquent. Simply share what you know or what you have experienced."
  },
  days: [
    {
      label: "The Spirit of testimony",
      focus: "True testimony of Jesus Christ comes not from argument or evidence but from the Holy Ghost. Today examines the spiritual mechanism by which testimony is born.",
      scriptures: [{book:"John",ch:15,vs:26,ve:27},{book:"1 Cor",ch:12,vs:3},{book:"D&C",ch:46,vs:13,ve:14}],
      nuances: "In John 15:26, the 'Comforter' (Parakletos) will 'testify of me' — the Greek 'martureo' is the root of 'martyr' and means to bear witness with full personal commitment. The Spirit does not merely inform; He testifies with the weight of a witness in court. In D&C 46:14, the gift of believing on the words of others ('that they might also have eternal life if they continue faithful') treats secondhand faith as a genuine spiritual gift, not a lesser category.",
      commentary: "Jesus told His disciples that when the Comforter came, He would testify of Christ — and then added, 'And ye also shall bear witness.' The sequence matters. The Spirit testifies first, within the heart, and then the disciple gives voice to what the Spirit has communicated. Testimony is not something we generate through study alone, though study can prepare the soil. It is something the Spirit plants.\n\nPaul affirms this in 1 Corinthians 12:3: 'No man can say that Jesus is the Lord, but by the Holy Ghost.' As explored in Week 1, this does not mean people cannot physically speak the words. It means the genuine, soul-deep recognition of Jesus as Lord — not just teacher, not just example, but the divine Son of God — comes only through spiritual revelation.\n\nD&C 46:13–14 introduces an important and often overlooked nuance. Some have the gift of knowing by the Spirit that Jesus Christ is the Son of God. Others have the gift of believing on their words. Both gifts are from God. Both lead to eternal life. The person whose testimony is built on the witness of others — a parent's testimony, a prophet's declaration, a friend's quiet conviction — is not operating with a deficient faith. They are exercising a genuine spiritual gift.\n\nThis means testimony is communal as well as personal. We bear testimony not only to express what we know but to provide the foundation on which others can believe. Your witness may be the spiritual gift that sustains someone who has not yet received their own.",
      patterns: "The Spirit as the source of testimony is a constant across dispensations. Nephi learned by the Spirit that his father's visions were true (1 Ne. 11:1). Peter's confession of Christ was revealed by the Father (Matt. 16:17). Joseph Smith's testimony came through direct experience confirmed by the Spirit (JS-H 1:25). The mechanism is always the same: God reveals, the Spirit confirms, the disciple testifies.",
      reflection: "When you bear testimony of Jesus Christ, are you sharing what the Spirit has communicated to you, or are you repeating what you think you should say? What would it take to make your testimony more genuinely your own?"
    },
    {
      label: "The testimony of Jesus is the spirit of prophecy",
      focus: "Revelation declares that the testimony of Jesus IS the spirit of prophecy. Today examines this stunning equation and what it means for every believer.",
      scriptures: [{book:"Rev",ch:19,vs:10},{book:"Alma",ch:5,vs:45,ve:46},{book:"Acts",ch:1,vs:8}],
      nuances: "In Revelation 19:10, 'the testimony of Jesus is the spirit of prophecy' — the Greek 'he martyria Iesou estin to pneuma tes propheteias' can be read two ways: (1) the testimony about Jesus, or (2) the testimony that Jesus Himself bears. Both readings are theologically rich. If every testimony of Jesus participates in the spirit of prophecy, then every sincere witness of Christ is, in a real sense, a prophetic act. In Alma 5:46, Alma says he knows 'not of myself' but 'by the Holy Spirit of God' — separating personal opinion from revealed knowledge.",
      commentary: "Revelation 19:10 contains a definition that elevates testimony from a devotional practice to a prophetic one: the testimony of Jesus is the spirit of prophecy. This means that when you bear witness of Christ under the influence of the Holy Ghost, you are participating in the same power that animated Isaiah, Nephi, and Joseph Smith. Prophecy is not only about predicting the future — it is fundamentally about testifying of Jesus Christ.\n\nThis equation demolishes the artificial boundary between prophets and ordinary disciples. Every member of Christ's Church who has received the gift of the Holy Ghost has access to the spirit of prophecy. The teenager who says in testimony meeting, 'I know Jesus Christ is real,' is operating in the same prophetic tradition as Alma, who declared, 'I have fasted and prayed many days that I might know these things of myself. And now I do know of myself that they are true' (Alma 5:46).\n\nActs 1:8 records Christ's promise to the apostles: 'Ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me.' The word 'power' (dunamis) here means enabling force — the capacity to do what you could not do on your own. The Holy Ghost does not just give you knowledge of Christ; He gives you the power to bear witness of that knowledge effectively.\n\nAlma's testimony in Alma 5:45–46 provides a model of what prophetic testimony looks like: it is personal (he knows), it is spiritual (by the Holy Spirit of God), and it is costly (he fasted and prayed many days). Testimony is not cheap. The deepest knowledge of Christ comes through sustained effort and sacrifice.",
      patterns: "The pattern of prophetic testimony appears in every dispensation: Adam testified to his posterity (Moses 5:10–12), Abraham was told his seed would bear witness (Abr. 2:9–11), and the apostles were commissioned as witnesses (Acts 1:8). The pattern will continue to the end — the two witnesses of Revelation 11 will testify of Christ in the last days.",
      reflection: "If the testimony of Jesus is the spirit of prophecy, then bearing your testimony is a prophetic act. How does that understanding change the way you think about sharing what you know?"
    },
    {
      label: "Eyewitnesses of Christ",
      focus: "Throughout history, specific individuals have been chosen to see the risen Lord and testify from firsthand experience. Today examines the role and weight of eyewitness testimony.",
      scriptures: [{book:"D&C",ch:76,vs:22,ve:24},{book:"3 Ne",ch:11,vs:14,ve:17},{book:"John",ch:21,vs:24}],
      nuances: "In D&C 76:22, 'after the many testimonies which have been given of him, this is the testimony, last of all, which we give' — 'last of all' (eschaten) is the same word family used for 'eschatological,' meaning climactic or final. Joseph and Sidney position their witness as the capstone of all previous testimonies. In 3 Nephi 11:15, the multitude went forth 'one by one' — the individual, personal nature of touching the wounds is emphasized. This was not a mass event experienced at a distance but an intimate encounter.",
      commentary: "The Christian faith is built on eyewitness testimony. The apostles did not say, 'We have reasoned our way to the conclusion that Jesus rose.' They said, 'We saw Him. We touched Him. We ate with Him.' The entire weight of the gospel rests on the truthfulness of these witnesses.\n\nJoseph Smith and Sidney Rigdon added their witness in D&C 76:22–24: 'He lives! For we saw him, even on the right hand of God.' This testimony is deliberately modeled on the apostolic witness — simple, direct, and based on personal experience. The Restoration does not ask the world to believe in an ancient Christ on the basis of ancient testimony alone. It provides modern witnesses.\n\n3 Nephi 11:14–17 records perhaps the most expansive eyewitness event in scripture. The resurrected Christ appeared to approximately 2,500 Nephites and invited every one of them to come forward individually, feel the prints of the nails in His hands and feet, and thrust their hands into His side. This was not vision or impression — it was physical, tangible, one-person-at-a-time verification. They 'did see with their eyes and did feel with their hands, and did know of a surety.'\n\nJohn's claim in John 21:24 — 'This is the disciple which testifieth of these things ... and we know that his testimony is true' — emphasizes that the Gospel of John is not theological speculation but the testimony of someone who was there. The eyewitness stands behind the text.",
      patterns: "God consistently raises up eyewitnesses at critical moments: Moses saw God face to face (Moses 1:2), Isaiah saw the Lord in the temple (Isa. 6:1), Stephen saw Christ at the right hand of God (Acts 7:55–56), and Joseph Smith saw the Father and the Son (JS-H 1:17). The pattern of eyewitness testimony is central to how God establishes truth across dispensations.",
      reflection: "You may not be an eyewitness of Christ in the physical sense, but you have experienced His influence in your life. What have you 'seen' — what experiences have given you personal evidence that He is real and active?"
    },
    {
      label: "Testimony that cannot be silenced",
      focus: "The authorities commanded the apostles to stop testifying. They could not comply. Today examines what happens when testimony becomes so deeply rooted that silencing it is impossible.",
      scriptures: [{book:"Acts",ch:4,vs:18,ve:20},{book:"JS-H",ch:1,vs:25},{book:"2 Tim",ch:1,vs:7,ve:8}],
      nuances: "In Acts 4:20, 'We cannot but speak' — the Greek 'ou dunametha ... me lalein' is a double negative expressing absolute impossibility: we are unable not to speak. This is not defiance for its own sake but the irrepressible overflow of experienced reality. Joseph Smith's comparison to Paul in JS-H 1:25 is deliberate — both men were called liars for reporting what they saw, and both found the testimony impossible to retract.",
      commentary: "When the Sanhedrin commanded Peter and John to stop teaching in the name of Jesus, their response was immediate and unwavering: 'We cannot but speak the things which we have seen and heard.' This was not bravado. It was the simple impossibility of denying what they had experienced. They had walked with Jesus, watched Him die, and seen Him alive again. Silence was not an option.\n\nJoseph Smith described the same impossibility in JS-H 1:25. He was fourteen years old, facing ridicule, hostility, and accusations of deception. His response echoes Peter's: 'I had actually seen a light, and in the midst of that light I had seen two Personages, and they did in reality speak to me; and though I was hated and persecuted for saying that I had seen a vision, yet it was true.' He could not deny it without lying, and he would not lie.\n\nPaul's counsel to Timothy in 2 Timothy 1:7–8 provides the theological framework: 'God hath not given us the spirit of fear; but of power, and of love, and of a sound mind. Be not thou therefore ashamed of the testimony of our Lord.' Fear and shame are the weapons used to suppress testimony. The Spirit of God counters them with power, love, and clarity.\n\nThe cost of testimony can be high. Many of the early apostles died for their witness. Joseph Smith was murdered. Missionaries have been imprisoned and killed. But the pattern is consistent: when testimony is genuine, it cannot be extinguished by opposition. It can only be silenced by the death of the witness — and even then, the record endures.",
      patterns: "The pattern of costly testimony runs from Abel (whose righteous offering provoked his murder) to the martyrs of the Restoration. Abinadi testified before King Noah and was burned alive (Mosiah 17). Stephen testified before the Sanhedrin and was stoned (Acts 7). The blood of martyrs does not silence testimony — it amplifies it across generations.",
      reflection: "Have you ever felt pressure — social, intellectual, or emotional — to downplay or silence your testimony of Christ? What gave you the courage to speak, or what held you back?"
    },
    {
      label: "Growing a testimony",
      focus: "Testimony is not static — it can grow, deepen, and mature over a lifetime. It can also atrophy. Today examines how testimony develops and what sustains it.",
      scriptures: [{book:"Moro",ch:10,vs:4,ve:5},{book:"Alma",ch:5,vs:45,ve:46},{book:"1 Jn",ch:5,vs:9,ve:12}],
      nuances: "In Moroni 10:4, 'with a sincere heart, with real intent' — the qualifiers are demanding. 'Sincere' (from Latin 'sincerus,' meaning unmixed, pure) implies no hidden agenda. 'Real intent' means you genuinely intend to act on the answer. Moroni is saying the experiment only works if you are willing to be changed by the result. In 1 John 5:10, 'he that believeth on the Son of God hath the witness in himself' — the perfect tense 'echei' indicates an ongoing, present possession, not a past event.",
      commentary: "Moroni's promise is the most famous invitation to seek testimony in all of scripture: ask God with a sincere heart, with real intent, having faith in Christ, and He will manifest the truth by the power of the Holy Ghost. The promise is simple, but its conditions are rigorous. Sincerity means you are not testing God to fail. Real intent means you will act on what you receive. Faith in Christ means you approach the experiment already trusting the One you are asking about.\n\nAlma 5:45–46 reveals that testimony, even for a prophet, requires sustained effort. Alma fasted and prayed many days. He did not receive his testimony in a flash of instant certainty but through a process of seeking, asking, and waiting. This is instructive for anyone who has prayed once, felt nothing, and concluded that the experiment failed. Testimony often arrives gradually, like dawn rather than a light switch.\n\n1 John 5:9–12 adds that the person who believes in the Son of God has 'the witness in himself.' Testimony, once received, becomes internal — part of who you are, not just something you think. It resides in the heart, not merely in the intellect. This is why testimony can survive intellectual challenge: it is not primarily an intellectual product.\n\nBut testimony must also be maintained. Like any living thing, it requires nourishment — scripture study, prayer, obedience, service, and the regular exercise of sharing it with others. Alma compared the word to a seed that must be nurtured or it will wither (Alma 32:37–43). The same principle applies to testimony itself: neglect it and it fades; feed it and it grows into something unshakable.",
      patterns: "The growth of testimony follows the pattern of Alma 32 — planting, nourishing, and eventually partaking of the fruit. This is the same pattern the Lord uses in all spiritual development: line upon line, precept upon precept (2 Ne. 28:30). Testimony grows by the same principles as faith, charity, and knowledge — through consistent, faithful practice over time.",
      reflection: "How has your testimony of Jesus Christ changed over the past year? What specific practices have nourished it? What, if anything, has weakened it — and what would it take to rebuild?"
    },
    {
      label: "Standing as witnesses",
      focus: "The baptismal covenant includes a commitment to stand as witnesses of God at all times, in all things, and in all places. Today examines what this covenant obligation looks like in practice.",
      scriptures: [{book:"Mosiah",ch:18,vs:8,ve:10},{book:"D&C",ch:62,vs:3},{book:"Alma",ch:36,vs:26}],
      nuances: "In Mosiah 18:9, 'stand as witnesses of God at all times and in all things, and in all places' — the triple 'all' (which translates emphatic Nephite language) eliminates every exception. There is no time, circumstance, or location exempt from the covenant to witness. D&C 62:3 says 'the testimony which ye have borne is recorded in heaven for the angels to look upon' — the heavenly record metaphor suggests that testimony carries weight in the eternal courts, not just on earth.",
      commentary: "When Alma taught at the waters of Mormon, he defined the baptismal covenant in terms of testimony: those who enter the water are willing to 'stand as witnesses of God at all times and in all things, and in all places.' This is not a call to constant preaching. It is a call to a consistent life — one that witnesses by word and deed, by character and choice, by presence and compassion.\n\nStanding as a witness means different things in different settings. In a classroom, it may mean sharing your belief. In a workplace, it may mean living with integrity when no one is watching. In a family, it may mean showing patience that comes from faith. In a moment of crisis, it may mean praying publicly or privately. The covenant is not prescriptive about method — it is comprehensive about scope.\n\nD&C 62:3 adds a dimension that should humble every testimony bearer: your testimony is recorded in heaven. The angels observe it. This means that the quiet, private testimony you share with a struggling friend is noted in the records of eternity. It also means that the testimony you withhold — the moment you could have spoken but chose silence out of fear — is also noted.\n\nAlma 36:26 reveals the result of Alma's own witness: 'Many have been born of God, and have tasted as I have tasted, and have seen eye to eye as I have seen.' Alma's testimony created a chain reaction — others received testimony because he bore his. This is the generative power of testimony: it multiplies. Your witness becomes someone else's seed.",
      patterns: "The pattern of testimony creating testimony runs from Lehi (whose vision led Nephi to seek his own) to the missionaries of every dispensation. The sons of Mosiah bore testimony among the Lamanites and entire cities were converted (Alma 23). Abinadi's testimony converted one man — Alma — and Alma's testimony converted thousands. One witness is enough to start a chain that reaches across generations.",
      reflection: "Think of the places and circumstances of your daily life. Where is it easiest to stand as a witness of God? Where is it hardest? What would it look like to be more consistently faithful to this covenant?"
    },
    {
      label: "The final testimony",
      focus: "Scripture closes with testimonies of Christ, and each disciple's life is ultimately a testimony. Today examines the weight, permanence, and purpose of bearing witness to the end.",
      scriptures: [{book:"2 Ne",ch:33,vs:10,ve:11},{book:"Ether",ch:12,vs:38,ve:41},{book:"D&C",ch:76,vs:22,ve:24}],
      nuances: "In 2 Nephi 33:11, 'these words shall condemn you at the last day' — Nephi's testimony becomes a juridical witness. The Greek/Hebrew legal concept of testimony involves binding accountability: once a witness has spoken, the hearer is responsible for what they have heard. Moroni's farewell in Ether 12:38–41 uses the phrase 'I bid farewell' (repeated) with the solemnity of a deathbed witness — his final act is testimony.",
      commentary: "Nephi closes his record with a testimony that is simultaneously tender and weighty: 'I glory in plainness; I glory in truth; I glory in my Jesus.' These are among the most personal words in the Book of Mormon. Nephi then adds that these words will stand as a witness at the last day — they will either bless or condemn those who read them. Testimony carries eternal consequences for both the giver and the receiver.\n\nMoroni's farewell in Ether 12:38–41 is written by a man who is alone, hunted, and likely aware that death is near. His final message is testimony: he commends the reader to seek Jesus, and he looks forward to meeting them 'before the pleasing bar of the great Jehovah, the Eternal Judge of both quick and dead.' His testimony is his legacy — it is all he has left to give, and it is enough.\n\nD&C 76:22–24 provides the Restoration's capstone testimony: 'He lives! For we saw him.' Joseph Smith and Sidney Rigdon place their witness alongside Peter's, John's, and Moroni's — a modern addition to the prophetic chain. The brevity of their declaration matches the apostolic pattern: testimony at its most powerful is not long but direct.\n\nYour life is, in a sense, your final testimony. What you build, how you love, what you prioritize, and who you become all testify of what you believed about Jesus Christ. The words you speak matter, but the life you live speaks louder. Every disciple is writing, day by day, the testimony that will stand at the last day.",
      patterns: "The pattern of closing with testimony is consistent across the standard works. Nephi closes with testimony. Moroni closes with testimony. John closes Revelation with testimony. Joseph Smith closes D&C 76 with testimony. The pattern suggests that the ultimate purpose of every prophet's work — and every disciple's life — is to bear witness of Jesus Christ.",
      reflection: "If your life ended today, what would your testimony of Jesus Christ be? Not what you would say in a formal setting, but what your life — your choices, your priorities, your relationships — has testified about Him?"
    }
  ]
};

export default week24;
