import type { WeekContent } from '../types';

const week23: WeekContent = {
  title: "Authority of — The Power Behind the Mission",
  subtitle: "Jesus Christ acted with divine authority in everything He did — and the question of where that authority came from was the central controversy of His ministry.",
  weekScriptures: "Ps 110:1-4; Matt 11:27; Luke 10:22; John 14:10; John 20:21-23; Acts 4:7-12; 1 Cor 15:24-27; Heb 3:1-6; D&C 6:2; D&C 50:26-28; D&C 107:3-4; Jacob 7:8-11; Mosiah 18:17-18; Col 2:10",
  synthesis: {
    summary: "The authority of Jesus Christ was not assumed, inherited through earthly channels, or self-appointed. It was given by the Father, demonstrated through works of power, and recognized by those with spiritual eyes to see. His authority extended over sin, death, nature, demons, and the law itself — because He was the Author of all of them. Understanding Christ's authority is essential to understanding why His ordinances, His Atonement, and His Church have binding power.",
    connections: [
      "Christ's authority is demonstrated through His teaching (Week 20) and His ordinances, especially baptism (Week 21). The authority studied here is the foundation beneath both.",
      "The priesthood authority that flows from Christ connects to Week 33 (Mediator) and the covenant structure of the gospel.",
      "Christ's authority over sin and death, examined this week, directly undergirds the Atonement studied in Weeks 12–13."
    ],
    teaching: "The Jewish leaders repeatedly asked Jesus, 'By what authority do you do these things?' If someone asked you the same question about the ordinances and practices of the Church today, how would you answer? What is the chain of authority?",
    commitment: "This week, as you participate in an ordinance (even if it is just the sacrament), consciously consider the chain of authority that makes it valid — from Christ to His servants to the person officiating. Let that awareness deepen the experience."
  },
  days: [
    {
      label: "All power is given unto Me",
      focus: "The resurrected Christ declared that all authority in heaven and earth had been given to Him. Today examines the scope and source of His authority.",
      scriptures: [{book:"Matt",ch:28,vs:18},{book:"John",ch:5,vs:19,ve:27},{book:"Moses",ch:1,vs:25,ve:33}],
      nuances: "In Matthew 28:18, 'all power' translates 'pasa exousia' — all authority, all right to act. The passive 'was given' (edothe) indicates this authority was conferred by the Father, not self-claimed. In John 5:22, 'all judgment' (ten krisin pasan) is committed to the Son — the Father has delegated the judicial function entirely. The scope is total: creation, redemption, judgment, and glorification all rest in Christ's hands.",
      commentary: "The resurrected Christ's declaration in Matthew 28:18 is one of the most sweeping claims in all of scripture: 'All power is given unto me in heaven and in earth.' This is not a boast but a statement of fact — and it is the foundation on which the Great Commission rests. The apostles are sent to teach and baptize all nations not on their own authority but on His. Every act of priesthood ministry since traces back to this moment.\n\nJohn 5:19–27 reveals the intimate relationship between the Father's authority and the Son's. Jesus does nothing of Himself — He does what He sees the Father do. This is not limitation but perfect unity. The Father has given the Son authority to execute judgment, to give life, and to act in all things. The authority is delegated but total.\n\nMoses 1:25–33 expands the scope to a cosmic scale. God reveals to Moses that He has created worlds without number, and that all of this was accomplished through His Only Begotten. The authority of Christ is not confined to this earth or this dispensation. He is the agent of creation across the universe. This is the being who stood in the synagogue, who healed the lame, who broke bread with fishermen — and behind every humble act was the authority of the Creator of worlds.\n\nThe theological point is crucial: Christ's authority is not positional in the human sense. It does not come from rank, wealth, or political power. It comes from His relationship with the Father and His nature as the divine Son. This is why no earthly authority can replicate or replace it.",
      patterns: "The pattern of delegated authority runs throughout scripture. The Father gives authority to the Son. The Son gives authority to His apostles. The apostles ordain others. The chain is personal and traceable — never institutional or abstract. This pattern of personal delegation will be explored further in the context of priesthood restoration (D&C 13; D&C 84).",
      reflection: "How does the reality that Christ holds all authority in heaven and earth affect the way you approach Him in prayer? Does it change the kind of things you feel you can ask for?"
    },
    {
      label: "Authority to forgive sins",
      focus: "When Jesus forgave a paralytic's sins, the religious leaders erupted. Today examines the most controversial exercise of Christ's authority — and why it mattered more than the miracle that followed.",
      scriptures: [{book:"Mark",ch:2,vs:5,ve:12},{book:"Luke",ch:5,vs:17,ve:26},{book:"Matt",ch:9,vs:6,ve:8}],
      nuances: "In Mark 2:5, Jesus says 'thy sins be forgiven thee' — the Greek 'aphientai' is present passive: 'your sins are being forgiven.' It is happening in that moment, by His word. The scribes' objection — 'Who can forgive sins but God only?' (tis dunatai aphienai hamartias ei me heis ho theos) — is theologically correct. Their error was not in the theology but in failing to recognize who was speaking. In Mark 2:10, 'the Son of man' (ho huios tou anthropou) is Christ's preferred self-designation, drawn from Daniel 7:13–14, where it describes a divine figure receiving everlasting dominion.",
      commentary: "A paralyzed man is lowered through the roof by his friends. Jesus looks at him and says, 'Son, thy sins be forgiven thee.' The scribes are immediately scandalized — not because they misunderstand the claim but because they understand it perfectly. Only God can forgive sins. By forgiving this man, Jesus is claiming to be God.\n\nJesus responds not with theological argument but with a test: 'Whether is it easier to say, Thy sins be forgiven thee; or to say, Arise, take up thy bed, and walk?' The logic is pointed. Anyone can claim to forgive sins — the claim is invisible, unverifiable by human means. But commanding a paralyzed man to walk is immediately testable. Jesus performs the harder, visible miracle to validate the easier, invisible one: 'That ye may know that the Son of man hath power on earth to forgive sins.'\n\nThe authority to forgive sins is the most important authority Christ possesses, because sin is the fundamental human problem. Healing bodies is temporary — every healed person eventually dies. But forgiveness of sin addresses the eternal condition of the soul. The miracle of walking was spectacular, but the miracle of forgiveness was the real point.\n\nMatthew records that the multitude 'marvelled, and glorified God, which had given such power unto men.' They sensed, even if they did not fully understand, that something unprecedented had entered the world — authority over the deepest human condition, exercised by a man who was more than a man.",
      patterns: "The pattern of visible miracles validating invisible spiritual authority recurs throughout Christ's ministry. He calmed the storm to demonstrate authority over nature. He cast out demons to demonstrate authority over evil. He raised the dead to demonstrate authority over death. Each miracle points past itself to a deeper claim about who He is.",
      reflection: "If you truly believed that Jesus Christ has the authority to forgive your sins — completely and permanently — how would that change the way you carry your past mistakes?"
    },
    {
      label: "Authority over death",
      focus: "Jesus claimed power to lay down His life and take it up again. Today examines the ultimate scope of Christ's authority — power over death itself.",
      scriptures: [{book:"John",ch:10,vs:17,ve:18},{book:"Mosiah",ch:15,vs:1,ve:7},{book:"Heb",ch:5,vs:1,ve:10}],
      nuances: "In John 10:18, 'No man taketh it from me' — 'oudeis airei' uses the present tense: no one is taking it. The statement applies not just to the future crucifixion but to any moment. His life is not vulnerable to human power without His consent. 'I have power to lay it down, and I have power to take it again' — 'exousian echo' (I have authority) appears twice, emphasizing the volitional nature of both His death and His resurrection. Mosiah 15:7 describes Christ's will being 'swallowed up in the will of the Father,' using imagery of complete absorption.",
      commentary: "John 10:17–18 contains a claim found nowhere else in the religious literature of the world: 'I have power to lay down my life, and I have power to take it again.' No prophet, saint, or sage in any tradition has ever made this claim. Christ did not merely accept death — He had authority over it. His death was voluntary, and His resurrection was self-enacted.\n\nThis claim depends on Christ's unique nature. Mosiah 15:1–7 provides the Book of Mormon's deepest theological reflection on this: because Christ was both God and man — the Father in the power of His divinity and the Son in the submission of His mortality — He had the power to overcome death from within. His divine nature gave Him authority over death; His mortal nature gave Him the ability to die. No other being in the universe occupies this position.\n\nHebrews 5:1–10 adds that Christ was 'called of God a high priest after the order of Melchizedek.' His priestly authority was not inherited through the Levitical line but appointed directly by God — an eternal priesthood without beginning of days or end of years. This priesthood authority is what empowered the Atonement itself. The offering Christ made was not merely moral or substitutionary — it was priestly, authorized, and accepted by God.\n\nThe authority over death has cosmic implications. Because Christ conquered death, every human being who has ever lived will be resurrected (1 Cor. 15:22). This is not conditional on faith, obedience, or knowledge — it is a universal gift of Christ's authority. The resurrection is the broadest exercise of divine power in all of scripture.",
      patterns: "The authority over death connects to every resurrection account in scripture — Elijah raising the widow's son (1 Kgs. 17:22), Jesus raising Lazarus (John 11), and the promise of universal resurrection (Alma 11:42–44). Each instance points forward to Christ's own resurrection as the source and guarantee of all others.",
      reflection: "Christ chose to die so that He could choose to rise. How does the voluntary nature of His sacrifice — that He was never a victim but always in control — affect the way you understand the Atonement?"
    },
    {
      label: "By what authority?",
      focus: "The religious leaders demanded to know where Jesus got His authority. Today examines this confrontation and what it reveals about how authority is recognized — and missed.",
      scriptures: [{book:"Matt",ch:21,vs:23,ve:27},{book:"D&C",ch:1,vs:38},{book:"John",ch:17,vs:1,ve:5}],
      nuances: "In Matthew 21:24, Jesus responds to the question about His authority with a counter-question — the Greek 'logon hena' (one word/question) suggests He will answer their question with a single decisive test. 'The baptism of John, whence was it? from heaven, or of men?' The chief priests are trapped because any honest answer leads to conclusions they cannot accept. In D&C 1:38, 'whether by mine own voice or by the voice of my servants, it is the same' — the Lord equates His personal authority with the authority He delegates.",
      commentary: "In the temple courts, the chief priests and elders confronted Jesus with the question that defined the conflict of His entire ministry: 'By what authority doest thou these things? and who gave thee this authority?' The question was not idle. In Judaism, religious authority came through recognized channels — ordination by established teachers, appointment by the Sanhedrin, or Levitical descent. Jesus had none of these.\n\nHis counter-question about John's baptism was not evasion. It was diagnostic. If they could recognize John's divine commission, they could recognize His. If they could not, no amount of explanation would convince them. The chief priests deliberated and admitted privately that they could not answer without either condemning themselves or endorsing Jesus. They chose silence: 'We cannot tell.' Jesus responded, 'Neither tell I you by what authority I do these things.' Authority is recognized by the prepared heart, not proven by argument.\n\nIn John 17:1–5, Jesus prays to the Father and reveals the source of His authority in the most intimate terms: 'Thou hast given him power over all flesh.' His authority is not self-generated — it is given by the Father within the context of their eternal relationship. Jesus came from the Father, acts for the Father, and returns to the Father. His authority is relational, not institutional.\n\nD&C 1:38 extends this principle to the modern day: when the Lord's servants speak by His Spirit, their words carry His authority. This is the foundation of prophetic and priesthood authority in the Restoration — not personal charisma or institutional position, but divine delegation recognized by the Spirit.",
      patterns: "The question 'By what authority?' is asked of every prophetic figure in scripture. Moses faced it from Korah (Num. 16). Samuel faced it from Israel (1 Sam. 8). Joseph Smith faced it from virtually everyone. The pattern reveals that divine authority is always contested by those whose power it threatens.",
      reflection: "How do you personally recognize divine authority when you encounter it — in a sermon, in a counsel from a leader, in a prompting of the Spirit? What is the difference between authority that is merely claimed and authority that is genuinely felt?"
    },
    {
      label: "Priesthood authority from Christ",
      focus: "Christ is the source of all priesthood authority. Today examines how that authority is conferred, transmitted, and operates in the lives of His servants.",
      scriptures: [{book:"Alma",ch:13,vs:1,ve:9},{book:"D&C",ch:84,vs:19,ve:22},{book:"D&C",ch:13,vs:1}],
      nuances: "In Alma 13:2, priests were 'called and prepared from the foundation of the world according to the foreknowledge of God.' The phrase suggests that priesthood callings are not arbitrary but are part of the pre-mortal plan. In D&C 84:19, the Melchizedek Priesthood 'holdeth the key of the mysteries of the kingdom, even the key of the knowledge of God.' The word 'key' (Greek 'kleis,' used in Matt. 16:19) implies the power to open what is locked — access to divine knowledge and saving ordinances.",
      commentary: "Alma 13 is one of the most profound priesthood texts in all of scripture. It describes an order of the priesthood that existed before the foundation of the world — men ordained 'according to the foreknowledge of God, on account of their exceeding faith and good works.' This is the Melchizedek Priesthood, and its origin is not earthly but heavenly. It was conferred to help people 'look forward to the Son of God for a redemption.'\n\nD&C 84:19–22 makes explicit what Alma described: the greater priesthood holds the key of the knowledge of God. Without the ordinances of this priesthood, 'the power of godliness is not manifest unto men in the flesh.' This is a remarkable claim — the ordinances performed by priesthood authority are not mere symbols but actual channels through which God's power becomes accessible to mortals.\n\nD&C 13:1 records the moment John the Baptist restored the Aaronic Priesthood to Joseph Smith and Oliver Cowdery. The restoration was not gradual or conceptual — it was a specific event, performed by a specific resurrected being, with specific words. The priesthood was conferred by the laying on of hands, just as it had been in ancient times. The chain of authority was reconnected.\n\nThe practical implication is that every priesthood ordinance performed today — every baptism, every sacrament prayer, every temple rite — traces its authority back through an unbroken chain to Jesus Christ Himself. The ordinances are not valid because of the worthiness of the officiant alone (though worthiness matters) but because of the authority that stands behind them.",
      patterns: "The restoration of priesthood authority through angelic ministration connects to the broader pattern of restoration studied across the fifty-week plan. Each dispensation receives its authority through direct bestowal from a being who already holds it — never through scholarly discovery, institutional succession, or popular vote.",
      reflection: "How does understanding the chain of priesthood authority — from Christ through specific individuals to the present — affect the way you experience ordinances like the sacrament or temple worship?"
    },
    {
      label: "Authority exercised in righteousness",
      focus: "Having authority is not the same as using it properly. Today examines the Lord's own standards for how divine authority must be exercised.",
      scriptures: [{book:"D&C",ch:121,vs:34,ve:46},{book:"3 Ne",ch:11,vs:21,ve:25},{book:"Matt",ch:7,vs:28,ve:29}],
      nuances: "In D&C 121:37, 'Amen to the priesthood or the authority of that man' uses 'amen' in its Hebrew sense of 'so be it' or 'it is finished.' When a man exercises authority unrighteously, heaven withdraws its ratification — the authority technically remains but is no longer backed by divine power. D&C 121:41 lists the principles of righteous authority: 'persuasion, long-suffering, gentleness and meekness, and love unfeigned.' Every term describes Christ's own character.",
      commentary: "D&C 121:34–46 is the Lord's most detailed instruction on how authority must be exercised, and it was given to Joseph Smith while he languished in Liberty Jail — a setting where the abuse of authority was pressing and personal. The revelation makes clear that priesthood authority is inseparable from Christlike character. The moment a person uses authority to 'cover sins, or to gratify pride, or vain ambition,' the heavens withdraw and the authority becomes hollow.\n\nThe principles prescribed are extraordinary: persuasion, long-suffering, gentleness, meekness, love unfeigned, kindness, and pure knowledge. There is no mention of coercion, rank-pulling, or institutional leverage. The Lord's model for authority is not the boardroom or the battlefield — it is the Savior washing feet, inviting children to come, and weeping at the tomb of a friend.\n\nIn 3 Nephi 11:21–25, the resurrected Christ personally delegates authority to perform baptism. The manner of delegation is direct and personal — He speaks to individuals by name. Authority is not distributed through a memo or a manual but through a personal encounter with the Source of that authority.\n\nMatthew 7:28–29 reminds us that the crowds recognized Christ's authority not because He held a title but because of how He spoke and what He did. His authority was self-evident to those with ears to hear. The same should be true of anyone who exercises authority in His name — it should be recognizable not by its force but by its fruits.",
      patterns: "The contrast between righteous and unrighteous authority runs through scripture. Compare the servant leadership of King Benjamin (Mosiah 2:12–16) with the tyranny of King Noah (Mosiah 11:1–6). Compare the gentle persuasion of the sons of Mosiah (Alma 17–26) with the coercion of Amalickiah (Alma 46–48). The pattern is consistent: divine authority leads; worldly authority compels.",
      reflection: "Think of someone in your life who exercises authority in a Christlike way — a parent, teacher, leader, or friend. What specifically do they do that reflects the principles of D&C 121? How can you incorporate those principles into the influence you have over others?"
    },
    {
      label: "Recognizing His authority today",
      focus: "Christ's authority is not a historical artifact — it is active and present. Today examines how that authority operates in the world now and how disciples encounter it.",
      scriptures: [{book:"D&C",ch:1,vs:38},{book:"D&C",ch:84,vs:19,ve:22},{book:"Heb",ch:5,vs:4,ve:6}],
      nuances: "In Hebrews 5:4, 'no man taketh this honour unto himself, but he that is called of God, as was Aaron' — the verb 'called' (kaloumenos) is a present passive participle: being called, an ongoing divine act. This is not a one-time event but a continuous relationship between God and His authorized servants. The comparison to Aaron is significant because Aaron's authority was publicly validated by God through miraculous signs (the budding rod, Num. 17:8), not merely by Moses' appointment.",
      commentary: "D&C 1:38 contains a principle that extends Christ's authority across all time and all His servants: 'What I the Lord have spoken, I have spoken, and I excuse not myself; and though the heavens and the earth pass away, my word shall not pass away, but shall all be fulfilled, whether by mine own voice or by the voice of my servants, it is the same.' Christ's authority is not diminished by delegation. When His authorized servants speak by His Spirit, He stands behind their words.\n\nThis does not mean every word spoken by every Church leader carries equal prophetic weight. The Lord Himself distinguishes between speaking by the Spirit and speaking from personal opinion (D&C 68:3–4). But the principle is clear: Christ has established a pattern of authoritative communication through living prophets and apostles, and the Spirit confirms when that communication carries divine endorsement.\n\nD&C 84:19–22 describes the priesthood as the channel through which the power of godliness is manifest. Without the ordinances administered by this authority, the face of God cannot be fully revealed to mortals. This is a strong claim — it means that priesthood authority is not merely organizational but cosmically functional. It opens doors that cannot be opened any other way.\n\nHebrews 5:4–6 provides the timeless standard: no one takes this authority to himself. It must be conferred by God. This protects the saints from self-appointed prophets and ensures that the chain of authority remains traceable to its source. The question is never 'Is this person impressive?' but 'Was this person called by God through recognized channels?'",
      patterns: "The principle that authority must be received, not assumed, connects to every dispensational restoration. Adam received authority from God. Abraham received it by covenant. Moses received it at the burning bush. The apostles received it from Christ. Joseph Smith received it from angelic ministers. The pattern is unbroken: authority always flows downward from God, never upward from human ambition.",
      reflection: "Where do you encounter Christ's living authority in your daily life — in the sacrament, in prophetic counsel, in priesthood blessings, in the temple? How attentive are you to those encounters, and how might you be more present to them?"
    }
  ]
};

export default week23;
