import type { WeekContent } from '../types';

const week12: WeekContent = {
  title: "Resurrection & Ascension — He Is Risen!",
  subtitle: "Easter 2026. The tomb is empty. The Savior lives. Death has been conquered, and the entire plan of salvation is vindicated.",
  weekScriptures: "Hosea 13:14; Isa 25:8; Dan 12:2; John 5:28-29; John 11:25-26; John 14:19; Rom 6:9; 1 Cor 15:55-57; Hel 14:15-17; Jacob 4:11; D&C 29:26; D&C 88:14-17",
  synthesis: {
    summary: "This is Easter week — the most important week in the Christian calendar and the culmination of everything studied in Weeks 10 and 11. The Resurrection of Jesus Christ is not a metaphor, not a spiritual idea, not a comforting myth. It is a historical claim: the man who was crucified on Friday was alive, bodily, on Sunday. If the Resurrection happened, it changes everything. Death is not permanent. Sin is not fatal. Separation from God is not final. The tomb is empty, and because it is empty, every promise God has ever made is guaranteed.",
    connections: [
      "The Crucifixion of Week 11 is transformed from tragedy into triumph — the cross was not the end but the necessary prelude to the empty tomb.",
      "The mission of Christ (Week 9) is vindicated by the Resurrection — He came to conquer death, and He did.",
      "The Atonement explored in Week 13 is made effectual by the Resurrection — without it, there is no redemption, no immortality, no eternal life."
    ],
    teaching: "Paul wrote that if Christ is not risen, our faith is vain. Why is the physical, bodily Resurrection so central to the gospel? What would be lost if the Resurrection were merely metaphorical — a 'spiritual' survival rather than a literal, physical rising?",
    commitment: "This Easter, bear testimony of the risen Christ to someone — a family member, a friend, a neighbor. Make it personal and specific. The Resurrection is too important to celebrate only in silence."
  },
  days: [
    {
      label: "The empty tomb",
      focus: "Easter Sunday. Women came to anoint a body and found the stone rolled away. Today we approach the moment that changed everything.",
      scriptures: [{book:"Matt",ch:28,vs:1,ve:10},{book:"Mark",ch:16,vs:1,ve:8},{book:"Luke",ch:24,vs:1,ve:12}],
      nuances: "In Mark 16:4, the stone was 'rolled away' — the Greek 'apokekulistai' is a perfect passive, meaning someone else had already rolled it. The stone was not moved to let Jesus out — a glorified, resurrected body does not need doors opened. The stone was rolled away to let the witnesses in. The empty tomb was arranged for human eyes, not divine necessity.",
      commentary: "All four Gospels agree on the essential facts: early on Sunday morning, women went to the tomb and found it open and empty. Angels announced what had happened: He is not here. He is risen. The variations between the Gospel accounts — which women, how many angels, the exact sequence of events — are precisely what we would expect from independent witnesses describing the same extraordinary event from different vantage points. Perfect agreement would suggest collusion; the variations authenticate the accounts.\n\nThe fact that women were the first witnesses is historically significant. In first-century Jewish and Roman culture, women's testimony was generally not accepted in court. If the early Christians were fabricating a resurrection story, they would never have chosen women as the primary witnesses. The Gospels report women first because women were first. The historical reality overrode cultural convention.\n\nMatthew records the earthquake and the angel's descent. Mark records the women's fear and amazement. Luke records Peter running to the tomb and finding the linen cloths lying by themselves. Each detail adds to the composite picture of an event so overwhelming that no single account could capture it fully.\n\nThis is the morning that defines Christianity. Every church that has ever existed, every hymn that has ever been sung, every baptism that has ever been performed traces its authority back to this morning. The tomb was empty. And because it was empty, everything Christ promised is true.",
      patterns: "The empty tomb fulfills the pattern of every prior deliverance in scripture: Noah from the flood, Israel from Egypt, Daniel from the lions' den, the three Hebrews from the furnace. God delivers His people from death. The Resurrection is the ultimate and final deliverance.",
      reflection: "This is Easter. The tomb is empty. He lives. How will you honor this truth today — not merely with belief, but with the way you live, speak, and hope?"
    },
    {
      label: "Mary Magdalene and the risen Lord",
      focus: "The first person to see the resurrected Christ was Mary Magdalene. Today explores that singular, tender encounter in the garden.",
      scriptures: [{book:"John",ch:20,vs:1,ve:18},{book:"Mark",ch:16,vs:9},{book:"Ps",ch:30,vs:5}],
      nuances: "In John 20:16, Jesus said 'Mary' — one word, her name, in a voice she recognized. The Greek 'Mariam' is the personal, intimate form. She immediately responded 'Rabboni' — Aramaic for 'my Teacher,' a more personal form than 'Rabbi.' The entire recognition scene turns on the intimacy of a name spoken and recognized. The Resurrection was not first revealed in a sermon or a theological argument — it was revealed in a personal encounter.",
      commentary: "John's account of Mary Magdalene at the tomb is among the most moving passages in all of scripture. She arrived while it was still dark, found the stone removed, and ran to tell Peter and John. After they came, saw, and left, Mary stayed. She stood outside the tomb weeping. She looked inside and saw two angels. She turned and saw a man she took to be the gardener. And then He spoke her name.\n\nOne word — 'Mary' — and she knew. The Good Shepherd calls His own sheep by name, and they know His voice (John 10:3). This was not a dramatic revelation with thunderclaps and glory. It was a quiet moment in a garden at dawn. The risen Lord's first act was to comfort a grieving woman by speaking her name.\n\nJesus told Mary not to hold onto Him (the Greek 'mē mou haptou' suggests 'do not keep clinging to me') because He had not yet ascended to the Father. There was work still to be done. But He gave her a commission: go tell the disciples. Mary Magdalene became the first evangelist of the Resurrection — an apostle to the apostles, as some early Christian writers described her.\n\nPsalm 30:5 finds its deepest fulfillment here: weeping endured for a night, but joy came in the morning. Mary wept in the darkness of Friday and Saturday. Sunday morning brought joy that has not diminished in two thousand years.\n\nThe Restoration affirms the personal nature of Christ's revelation. Just as He spoke Mary's name, He appeared personally to Joseph Smith, to the Nephites, and continues to reveal Himself to those who seek Him with full purpose of heart.",
      patterns: "Christ revealed Himself first to a single, grieving individual — not to a crowd or an institution. This pattern recurs throughout scripture: God meets us in our most personal moments of need. The Resurrection is both a cosmic event and an intimate one.",
      reflection: "Mary recognized Jesus when He spoke her name. In what moments of your life have you felt Christ speak to you personally — calling you by name, as it were? How did that recognition change you?"
    },
    {
      label: "The road to Emmaus",
      focus: "Two disciples walked a dusty road in despair, not realizing the risen Christ was walking beside them. Today explores how Christ reveals Himself through scripture and sacrament.",
      scriptures: [{book:"Luke",ch:24,vs:13,ve:35},{book:"Mosiah",ch:16,vs:7,ve:9},{book:"D&C",ch:76,vs:22,ve:24}],
      nuances: "In Luke 24:32, after recognizing Christ at the breaking of bread, the disciples reflected: 'Did not our heart burn within us while he talked with us by the way, and while he opened to us the scriptures?' The Greek 'kaiomenē' (burning) describes an ongoing, sustained burning — not a flash but a steady fire. This is Luke's description of how the Spirit confirms truth: a sustained warmth during the encounter with the living word.",
      commentary: "The Emmaus road account is unique to Luke and is a masterwork of narrative theology. Two disciples — one named Cleopas, the other unnamed — were walking the seven miles from Jerusalem to Emmaus, discussing the events of the weekend in deep grief. A stranger joined them and asked what they were discussing. They were astonished that anyone in the region could be unaware of the crucifixion of Jesus of Nazareth.\n\nThe stranger then did something extraordinary: beginning with Moses and all the prophets, He expounded in all the scriptures the things concerning Himself. This was the greatest Bible study in history, taught by the Author of the text. Christ showed them that His suffering, death, and resurrection were not the failure of the messianic hope — they were its fulfillment.\n\nWhen they arrived at Emmaus, the stranger made as if to continue. They urged Him to stay. At supper, He took bread, blessed it, and broke it. Their eyes were opened, and they recognized Him — and He vanished. They had encountered the risen Christ in two modes: through scripture and through the breaking of bread. These remain the two primary means by which Christians encounter Christ: in the word and in the ordinance.\n\nMosiah 16:7–9 declares the triumph of the Resurrection: the grave has no victory, the sting of death is swallowed up in Christ. Abinadi, who was himself about to be martyred, proclaimed this truth with his life.\n\nD&C 76:22–24 provides the Restoration's own Emmaus moment. Joseph Smith and Sidney Rigdon testify that, after many testimonies given before them, they too can declare: He lives. For we saw Him.",
      patterns: "The Emmaus pattern — Christ present but unrecognized, revealed through scripture and sacrament — is the pattern of every Sabbath worship. He walks with us, opens the scriptures to us, and reveals Himself in the ordinance. The question is whether we have eyes to see.",
      reflection: "The Emmaus disciples did not recognize Christ until He broke bread with them. Have you experienced moments during the sacrament when Christ felt especially present? What conditions allowed that recognition?"
    },
    {
      label: "Peace be unto you",
      focus: "The risen Christ appeared to His assembled disciples, showed them His wounds, and spoke peace. Today examines the gift of peace that only the Resurrection can give.",
      scriptures: [{book:"Luke",ch:24,vs:36,ve:49},{book:"John",ch:20,vs:19,ve:29},{book:"3 Ne",ch:11,vs:1,ve:17}],
      nuances: "In John 20:19, the doors were 'shut for fear of the Jews,' yet Jesus 'came and stood in the midst.' The Greek text does not say He walked through the door — it simply says He was suddenly there. A resurrected body, while tangible and real, is not limited by physical barriers. Jesus then showed His hands and side — the wounds remained. A glorified body retains the marks of sacrifice, not as defects but as tokens of triumph.",
      commentary: "On the evening of that first Easter Sunday, the disciples were gathered behind locked doors, terrified. Suddenly Jesus stood among them and said, 'Peace be unto you.' The first word of the risen Christ to His assembled Church was peace. Not rebuke for their abandonment. Not disappointment in their fear. Peace.\n\nHe showed them His hands and His side. The wounds were still there — healed but visible. Thomas, absent that evening, famously refused to believe without physical evidence. A week later, Christ appeared again and invited Thomas to touch the wounds. Thomas responded with the most concise and powerful confession in the Gospels: 'My Lord and my God.' Jesus then spoke a benediction that reaches across time: 'Blessed are they that have not seen, and yet have believed.'\n\nThe Nephite account in 3 Nephi 11 is the Book of Mormon's most sacred chapter. After the destruction at Christ's death, after the days of darkness, a multitude gathered at the temple in Bountiful. They heard a voice from heaven — three times — before they understood it. The Father introduced the Son. Christ descended. And then, one by one, 2,500 people came forward and felt the prints of the nails in His hands and feet and the wound in His side. They fell at His feet and worshipped. This was not hearsay or metaphor — it was tactile, individual witness.\n\nThe physical reality of the Resurrection matters immensely. Christ did not survive as a ghost or a memory. He rose with a body of flesh and bone. D&C 130:22 confirms this: the Father and the Son have bodies of flesh and bones as tangible as man's. The Resurrection is the promise that our bodies, too, will be reclaimed, glorified, and made eternal.",
      patterns: "Christ spoke peace to frightened disciples, invited doubters to touch His wounds, and descended personally to a people who had suffered destruction. The pattern is consistent: He meets people exactly where they are — in their fear, their doubt, and their devastation — and offers tangible evidence of hope.",
      reflection: "Thomas needed to touch the wounds before he could believe. Christ honored that need without shaming it. What kind of evidence or experience do you need to strengthen your faith? Are you willing to ask for it?"
    },
    {
      label: "The Resurrection body",
      focus: "The Resurrection was physical, not merely spiritual. Today explores what Paul and Restoration scripture teach about the nature of resurrected bodies.",
      scriptures: [{book:"1 Cor",ch:15,vs:35,ve:44},{book:"Alma",ch:11,vs:42,ve:44},{book:"D&C",ch:93,vs:33,ve:34}],
      nuances: "In 1 Corinthians 15:44, Paul distinguishes between a 'natural body' (s\u014dma psuchikon — an ensouled, mortal body) and a 'spiritual body' (s\u014dma pneumatikon — a body animated by spirit/Spirit). The 'spiritual body' is not immaterial — it is still a 's\u014dma' (body). Paul is describing the animating principle (spirit rather than natural life), not the substance. A spiritual body is still a body.",
      commentary: "Paul devotes an entire chapter — 1 Corinthians 15, the longest sustained argument about resurrection in the New Testament — to establishing the reality and nature of the resurrected body. He uses analogies: a seed is planted in one form and raised in another; celestial bodies differ from terrestrial; the body is sown in corruption and raised in incorruption. The point throughout is that resurrection transforms the body without destroying it. Identity continues. You will still be you — but glorified, perfected, and immortal.\n\nAmulek's testimony in Alma 11:42–44 is among the clearest statements about resurrection in all of scripture. Every limb, joint, hair, and feature will be restored to its proper and perfect frame. Nothing will be lost. The spirit and the body will be reunited, never again to be separated. This completeness of restoration addresses one of humanity's deepest fears: that death dissolves identity. It does not. The Resurrection guarantees that you — the whole you — will live again.\n\nD&C 93:33–34 adds a uniquely Restoration insight: spirit and element (body), inseparably connected, receive a fulness of joy. Separation of spirit and body is bondage. The Resurrection is therefore not merely survival — it is liberation. A disembodied spirit, however conscious, lacks fulness. The body is not a prison to escape but a gift to be reclaimed and perfected.\n\nThis doctrine stands in contrast to much of Greek philosophical tradition, which viewed the body as inferior to the soul. The Resurrection inverts that hierarchy: the body is essential to eternal joy. Physical existence is not a temporary inconvenience — it is part of God's eternal design for His children.",
      patterns: "The doctrine of bodily resurrection connects to the Incarnation studied in Week 1 — Christ took a body because bodies matter. The Resurrection confirms what the Incarnation initiated: the physical world is not disposable but sacred.",
      reflection: "Do you view your physical body as a burden or as a gift? How does the promise of resurrection — that every part of you will be restored and glorified — change your relationship with your body right now?"
    },
    {
      label: "The Ascension and the promise of return",
      focus: "Forty days after the Resurrection, Christ ascended to heaven. Today examines His departure and the promise that He will come again.",
      scriptures: [{book:"Acts",ch:1,vs:1,ve:11},{book:"1 Cor",ch:15,vs:20,ve:22},{book:"Morm",ch:9,vs:13,ve:14}],
      nuances: "In Acts 1:9, a 'cloud received him out of their sight.' The Greek 'nephel\u0113' (cloud) is the same word used in the Septuagint for the cloud of glory (the Shekinah) that filled the tabernacle and the temple. Christ did not merely float upward into ordinary weather — He was received into the divine presence. The cloud of glory that once settled on the mercy seat now enveloped the risen Lord.",
      commentary: "The Ascension is one of the most underappreciated events in Christian theology. For forty days after the Resurrection, Christ appeared to His disciples, teaching them about the kingdom of God (Acts 1:3). Then, on the Mount of Olives, He was lifted up and a cloud received Him. Two angels appeared and declared that this same Jesus would return in the same manner they had seen Him go — visibly, bodily, and to the same location.\n\nThe Ascension matters because it means Christ did not merely survive death — He completed His earthly mission and returned to the Father in glory. The resurrected body that bore the nail prints ascended to the right hand of God. The Incarnation is permanent. God has a body. He will have one forever.\n\nPaul's declaration in 1 Corinthians 15:20–22 places the Resurrection within the broadest possible frame. Christ is the firstfruits of them that slept. In Adam all die; in Christ shall all be made alive. The Resurrection is not a private miracle for one man — it is the beginning of a universal harvest. Because He rose, all will rise.\n\nMormon 9:13–14 echoes this universal scope from a Book of Mormon perspective. All shall be raised from the dead and stand before God to be judged. The Resurrection is both a gift and a summons — it restores the body and brings the whole person before the judgment bar of God. This is not a neutral event; it carries moral weight.\n\nThe promise of Christ's return — the Second Coming — extends the Resurrection narrative into the future. The Ascension is not an ending but an intermission. He will return, and when He does, the resurrection of the just will be completed, and the millennial reign will begin.",
      patterns: "The Ascension from the Mount of Olives creates a bookend. Christ will return to the same mountain (Zechariah 14:4, D&C 45:48). The departure and the return form a single narrative arc that encompasses all of Christian history — the era in which we now live.",
      reflection: "The angels said Jesus would return. Two thousand years later, we are still waiting. How do you maintain faith and urgency about the Second Coming in a world that has largely stopped expecting it?"
    },
    {
      label: "Because He lives",
      focus: "The Resurrection changes everything — how we understand death, how we face suffering, and how we live each day. Today synthesizes the meaning of the risen Christ for your life.",
      scriptures: [{book:"1 Cor",ch:15,vs:3,ve:8},{book:"2 Ne",ch:9,vs:10,ve:15},{book:"Alma",ch:40,vs:21,ve:23}],
      nuances: "In 1 Corinthians 15:3–4, Paul uses the technical language of tradition transmission: 'I delivered unto you that which I also received' — the Greek 'paredoka' and 'parelabon' are rabbinic terms for passing on authoritative teaching. Paul is not sharing personal opinions — he is transmitting the earliest Christian creed, which scholars date to within five years of the Crucifixion. This is the oldest recorded statement of Christian faith.",
      commentary: "Paul's summary in 1 Corinthians 15:3–8 is the earliest written account of the Resurrection appearances. Christ died, was buried, rose on the third day, and appeared to Cephas (Peter), then to the Twelve, then to five hundred at once, then to James, then to all the apostles, and finally to Paul himself. This list is a roll call of witnesses — not a philosophical argument but a chain of testimony.\n\nJacob's teaching in 2 Nephi 9:10–15 provides the most comprehensive Book of Mormon treatment of what the Resurrection accomplishes. Death and hell deliver up their dead. The spirit and the body are reunited. All people stand before God with a perfect knowledge of their guilt or their righteousness. The Resurrection is the mechanism by which the entire plan of salvation reaches its fulfillment. Without it, the Atonement has no lasting effect, the Fall is unreversed, and mortality is a pointless tragedy.\n\nAlma 40:21–23 confirms that the restoration is both physical and moral. Every limb and joint is restored; the righteous are received into a state of happiness called paradise. The Resurrection is just — it restores precisely, completely, and equitably.\n\nBecause Christ lives, death is not the end. Because Christ lives, sin can be forgiven. Because Christ lives, families can be sealed. Because Christ lives, the suffering you endure in mortality is temporary and purposeful. Because Christ lives, every promise made at the baptismal font, at the sacrament table, and at the temple altar will be honored.\n\nThis Easter week, let the reality of the Resurrection settle deeply into your heart. It is the most important fact in the history of the universe. He is risen. He lives. And because He lives, you will live too.",
      patterns: "The Resurrection is the climax of the gospel narrative but not the end of the story. Next week (Week 13) explores the Atonement — the doctrine that explains why Christ's death and resurrection have saving power. The empty tomb validates the sacrifice; the Atonement gives it meaning.",
      reflection: "If you truly believed — not just intellectually but with every fiber of your being — that Jesus Christ rose from the dead and lives today, what would change about the way you lived tomorrow morning?"
    }
  ]
};

export default week12;
